### ISSUE TITLE
Why I set smaller update-freq will be error when i want to continue to train a model.

### ISSUE THREAD

**Issue by PlayDeep** [pytorch/fairseq#1001]
I have use a big update-freq=56 to train a model,  then I want to stop it and continue a new training with trained model, I set update-freq = 1, it will be a error like following log. and I have try other settings like update-freq=4 will be ok . That is why?

`RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing its output (the return value of `forward`). You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`. If you already have this argument set, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /opt/conda/conda-bld/pytorch_1556653183467/work/torch/csrc/distributed/c10d/reducer.cpp:408)`

**Comment by myleott** [comment]
Interesting, what version of PyTorch? Did you try adding `--find-unused-parameters`?

**Comment by PlayDeep** [comment]
@myleott  my pytorch version is 1.1.0, and I did not try adding `--find-unused-parameters`, I just try different update-freq.
