### ISSUE TITLE
Why is incremental decoding available for the self-attention based model?

### ISSUE THREAD

**Issue by Michaelvll** [pytorch/fairseq#1003]
Hi,

Sorry for my naive question, but why is the incremental decoding available for the self-attention-based model? 

Won't the activation of each token in the input (of length L) of the k-th layer be different from the former timestep? As the (k-1)-th layer will add activation of the L-th token into it according to the attention weight, which does not happen in the former timestep. (There are only (L-1) tokens in the former timestep.) 

For example, let the attention weight of the (k-1)-th self-attention be (a_ij) and value be (v_i) (for simplicity we just ignore those linear layers). In the former timestep, the activation of the first token of the k-th input would be a_11 v_1 + ... + a_1(L-1) v_(L-1). In current timestep, the activation of the first token would be a_11 v_1 + ... + a_1L v_L. So the key of the k-th layer would be different from the key in the cache, right?

It seems that the `MultiHeadAttention` module just uses the key and value from the former step when inferencing.

B.t.w. I have read the blog about incremental decoding but apparently, I had some misunderstanding.

Thank you!

**Comment by MichaelZhouwang** [comment]
I have the same question, have you figured it out? Thanks!

**Comment by Michaelvll** [comment]
Yes. It is actually the target of the task. A token in the decoder will never use the information from the tokens after it, i.e. p(x_i|x_1, ..., x_{i-1}). In order to do that, there will be a lower triangular mask applied to the attention weight and only weights for the prefix of each token will be preserved. Therefore, while training, the embedding of each token in the output of the self-attention of the decoder is the weighted combination of the embedding of tokens in the prefix. For the inference, it is the same that the embedding of each token will not change when a token from the suffix fed into the decoder. And that is why the incremental decoding holds.

**Comment by MichaelZhouwang** [comment]
> Yes. It is actually the target of the task. A token in the decoder will never use the information from the tokens after it, i.e. p(x_i|x_1, ..., x_{i-1}). In order to do that, there will be a lower triangular mask applied to the attention weight and only weights for the prefix of each token will be preserved. Therefore, while training, the embedding of each token in the output of the self-attention of the decoder is the weighted combination of the embedding of tokens in the prefix. For the inference, it is the same that the embedding of each token will not change when a token from the suffix fed into the decoder. And that is why the incremental decoding holds.

Oh it make sense. By the way, I notice the arg named ''prev_self_attn_state'' in the transformer decoder is never used in the code and I could not see how the incremental_state can be updated without the prev_self_attn_state. Do you have any idea about this? Thanks!
