### ISSUE TITLE
Typo in fairseq/tasks/sentence_prediction.py 

### ISSUE THREAD

**Issue by Bakser** [pytorch/fairseq#1021]
Maybe [this line](https://github.com/pytorch/fairseq/blob/f840564da943f3f95bf80e93fd49be6f93d98348/fairseq/tasks/sentence_prediction.py#L108) should be replaced with `dictionary,`?
Otherwise, the [line 149](https://github.com/pytorch/fairseq/blob/f840564da943f3f95bf80e93fd49be6f93d98348/fairseq/tasks/sentence_prediction.py#L149) would make no sense.

**Comment by myleott** [comment]
They're aliases, as defined here: https://github.com/pytorch/fairseq/blob/f840564da943f3f95bf80e93fd49be6f93d98348/fairseq/tasks/sentence_prediction.py#L203

Various places in fairseq use souce_dictionary and target_dictionary to refer to the input and output dictionaries, so we define them for most tasks (including sentence prediction).
