### ISSUE TITLE
BoolQ model 

### ISSUE THREAD

**Issue by danyaljj** [pytorch/fairseq#1027]
Wondering if you will share the RoBERTa models for BoolQ (or you have already shared it.)

**Comment by ngoyal2707** [comment]
There's no plan to release models for `BoolQ`. 
The input format we used for BoolQ was same as other tasks ie. `<s> passage </s> </s> question </s>` and we feed first `<s>` representation to the classifier. While truncation for `seq_len>512`, we always truncate `passage`.

You can follow example for custom classification task [here](https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.custom_classification.md) and it should be the same.

Feel free to let me know if you have more questions on this.
