### ISSUE TITLE
How to binarize numberized data?

### ISSUE THREAD

**Issue by YuxianMeng** [pytorch/fairseq#1032]
Current preprocess.py deal with raw data(original tokens like "I love using fairseq"), but could not directly binarize the numberized txt files(integers like "3 6 9 10"). Is there a simple way to do this?

**Comment by myleott** [comment]
Hmm, you could hack it :) We support "raw", which splits plain text on spaces and passes it through the given Dictionary. So you just need to create a Dictionary that maps "3" -> 3, "4" -> 4, etc.

Try creating a new `dict.txt` with:
```bash
for I in $(seq 4 100000); do echo "$I 0"; done > dict.txt
```

Then preprocess with:
```bash
fairseq-preprocess --dataset-impl raw --srcdict dict.txt --trainpref path/to/file.txt --only-source
```

Test:
```python
from fairseq.data import data_utils
from fairseq.data import Dictionary
x = data_utils.load_indexed_dataset('data-bin/train', Dictionary.load('dict.txt'))
print(x[0])
# tensor([ 3,  6,  9, 10,  2])
```

**Comment by YuxianMeng** [comment]
> Hmm, you could hack it :) We support "raw", which splits plain text on spaces and passes it through the given Dictionary. So you just need to create a Dictionary that maps "3" -> 3, "4" -> 4, etc.
> 
> Try creating a new `dict.txt` with:
> 
> ```shell
> for I in $(seq 4 100000); do echo "$I 0"; done > dict.txt
> ```
> 
> Then preprocess with:
> 
> ```shell
> fairseq-preprocess --dataset-impl raw --srcdict dict.txt --trainpref path/to/file.txt
> ```
> 
> Test:
> 
> ```python
> from fairseq.data import data_utils
> from fairseq.data import Dictionary
> x = data_utils.load_indexed_dataset('data-bin/train', Dictionary.load('dict.txt'))
> print(x[0])
> # tensor([ 3,  6,  9, 10,  2])
> ```

Yes, this indeed is the method I thought. Thanks :)

**Comment by Chenfei-Kang** [comment]
Hello, why after I preprocess with "--dataset-impl raw", I got "train.None-None", and "x = data_utils.load_indexed_dataset('data-bin/train', Dictionary.load('dict.txt'))" got "NoneType"?

**Comment by Chenfei-Kang** [comment]
Hello, after I preprocess the data, I got NoneType by x = data_utils.load_indexed_dataset('data-bin/train', Dictionary.load('dict.txt'))
