### ISSUE TITLE
Reproducing RoBERTa CommonsenseQA results

### ISSUE THREAD

**Issue by huminghao16** [pytorch/fairseq#1038]
Thanks for your great work! I have followed the tutorial for finetuning roberta-large on CommonsenseQA. However, I was unable to reproduce the result. I can only get 76.33% accuracy while the reported one is 78.46%.

Here is my finetuning command:
```
LR=1e-05              # Peak LR for polynomial LR scheduler.
SEED=1                # Random seed.
PRETRAIN_MODEL_PATH="../../pretrained_models"
DATA_DIR=./data/CommonsenseQA
FAIRSEQ_USER_DIR=./examples/roberta/commonsense_qa
MAX_SENTENCES=4      # Batch size.
MAX_UPDATES=3000      # Number of training steps.
WARMUP_UPDATES=150    # Linearly increase LR over this many steps.
ROBERTA_PATH=${PRETRAIN_MODEL_PATH}/roberta.large/model.pt
CUDA_VISIBLE_DEVICES=0 fairseq-train --fp16 \
    $DATA_DIR \
    --user-dir $FAIRSEQ_USER_DIR \
    --restore-file $ROBERTA_PATH \
    --reset-optimizer --reset-dataloader --reset-meters \
    --no-epoch-checkpoints --no-last-checkpoints --no-save-optimizer-state \
    --best-checkpoint-metric accuracy --maximize-best-checkpoint-metric \
    --task commonsense_qa --init-token 0 --bpe gpt2 \
    --arch roberta_large --max-positions 512 \
    --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 \
    --criterion sentence_ranking --num-classes 5 \
    --optimizer adam --adam-betas '(0.9, 0.98)' --adam-eps 1e-06 --clip-norm 0.0 \
    --lr-scheduler polynomial_decay --lr $LR \
    --warmup-updates $WARMUP_UPDATES --total-num-update $MAX_UPDATES \
    --max-sentences $MAX_SENTENCES \
    --max-update $MAX_UPDATES \
    --log-format simple --log-interval 200 \
    --update-freq 4 \
    --seed $SEED
```

The experiment was run on a single TITAN Xp GPU with 12GB RAM. I use the official inference code and here is the result:
```
loading archive file checkpoints
loading archive file data/CommonsenseQA
| dictionary: 50265 types
Accuracy: 0.7633087633087633
```

Could you please tell me how to replicate the SoTA result? Thanks!

**Comment by myleott** [comment]
Was that from a single run? As mentioned in the tutorial, we did a hyperparameter search over the learning rate (1e-5, 2e-5, 3e-5), batch size (8, 16), number of training steps (2000, 3000, 4000) and random seed. Out of 100 runs we picked the best one, which gave 78.46%.

**Comment by huminghao16** [comment]
Yes. I have only conducted a single run due to limited computing resources. It would be great if you could share the exact setting (lr, batch size, steps, and so on), so that the community can benefit from your hyperparameter search. Thanks a lot!

**Comment by myleott** [comment]
The batch size, learning rate and number of training steps already match the best run. The only remaining difference is the ransom seed, but unfortunately the torch RNG is not guaranteed to produce the same results across systems: https://pytorch.org/docs/stable/notes/randomness.html. So even with the exact seed you will get different results.

**Comment by huminghao16** [comment]
Thanks! I will try several different seeds to see if I can get a better score.

**Comment by yuchenlin** [comment]
Hi @myleott , any updates on this issue? Did you find the seed back? Thanks!

**Comment by batselem** [comment]
I run roberta on commonsenseqa data with the same setting as yours on 11Gb memory GPU but I am getting cuda out of memory error. How were you able to run it on 12GB GPU?
