### ISSUE TITLE
Will you release the code of finetuning on SuperGlue

### ISSUE THREAD

**Issue by HMJiangGatech** [pytorch/fairseq#1042]
Hi, I wonder if you will release the code of finetuning on SuperGlue?

**Comment by ngoyal2707** [comment]
It's not currently under the plan. For most of the tasks, we use same input format as mentioned in the SuperGLUE paper. For some tasks we have different input format / objective function that we will cover in our updated paper soon.

**Comment by HMJiangGatech** [comment]
Thank you for your quick reply. I will keep eyes on the update of your paper.
