### ISSUE TITLE
How is RoBerta base trained?

### ISSUE THREAD

**Issue by XuhuiZhou** [pytorch/fairseq#1043]
How's roberta base pre-trained? It seems that you did not mention it in your paper. Specifically, I would like to know what data it used for pre-training?

**Comment by myleott** [comment]
Details are provided in Table 9 in the Appendix: https://arxiv.org/pdf/1907.11692.pdf. `roberta.base` follows the architecture of BERT-base and is trained on the same data as `roberta.large`.
