### ISSUE TITLE
Resuming training from pre-trained models.

### ISSUE THREAD

**Issue by Raghava14** [pytorch/fairseq#1046]
Hi ,
I have downloaded pretrained `transformer.wmt18.en-de` from [here](https://github.com/pytorch/fairseq/tree/master/examples/translation#pre-trained-models). Now when I try to resume train (or say fine tune) one of the ensemble models. I get this following error.

```
Traceback (most recent call last):

  File "/miniconda3/envs/myenv_s/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/Sugeeth/fairseq/train.py", line 284, in distributed_main
    main(args, init_distributed=True)
  File "/Sugeeth/fairseq/train.py", line 68, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/Sugeeth/fairseq/fairseq/checkpoint_utils.py", line 109, in load_checkpoint
    reset_meters=args.reset_meters,
  File "/Sugeeth/fairseq/fairseq/trainer.py", line 172, in load_checkpoint
    'Optimizer does not match; please reset the optimizer (--reset-optimizer).'
AssertionError: Optimizer does not match; please reset the optimizer (--reset-optimizer).
```
When I tried to see the optimizer [here](https://github.com/pytorch/fairseq/blob/49177c99c45f7d6e99a8f1500d16396e2d7b4519/fairseq/trainer.py#L169)
I get  `last_optim['optimizer_name']  = FairseqAdam`
 and `self.optimizer.__class__.__name__ = FP16Optimizer` which is causing the assertion error.

I have  passed `--fp16` as mentioned in the issue [here](https://github.com/pytorch/fairseq/issues/755) (Also the namespace from the downloaded model has `fp16=True`) and getting this error.  Why is the optimizer changing to `FP16Optimizer` even though I give `--optimizer adam` in the train command . Am I missing something ?

**Comment by myleott** [comment]
We modified the way FP16 optimization is implemented, which caused the naming mismatch. You can try disabling the check by commenting out this line: https://github.com/pytorch/fairseq/blob/49177c99c45f7d6e99a8f1500d16396e2d7b4519/fairseq/trainer.py#L169-L170

Otherwise `--reset-optimizer` is usually fine as well.

**Comment by Raghava14** [comment]
Thanks it works now.

**Comment by vigneshram95** [comment]
@Raghava14 can you please share the procedure for transfer learning, and is there any open dataset for transformer.wmt18.en-de  for fine tuning
