### ISSUE TITLE
libbleu is support case sensitive or not by parameters?

### ISSUE THREAD

**Issue by PlayDeep** [pytorch/fairseq#1049]
I have read this libbleu code and found it is unsupported case sensitive or not sensitive. It is Inconvenient.

**Comment by myleott** [comment]
It's meant to be a very simple and fast BLEU implementation that operates over tensors. Case sensitivity would require knowledge of the underlying dictionary and tokenization, which would add a lot of overhead. You can use `--sacrebleu` for a more full featured (but slower) implementation.
