### ISSUE TITLE
TypeError: 'NoneType' object is not iterable in torch.hub.list('pytorch/fairseq')

### ISSUE THREAD

**Issue by sekewei** [pytorch/fairseq#1062]
>import torch
># List available models
>torch.hub.list('pytorch/fairseq', force_reload=True)  # [..., 'transformer_lm.wmt19.en', ...]

When running the above torch.hub command on 'pytorch/fairseq',
the folloinwg TypeError on default='cross_entropy' is shown.

Downloading: "https://github.com/pytorch/fairseq/archive/master.zip" to /root/.cache/torch/hub/master.zip
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-2178edcac019> in <module>()
      2 
      3 # List available models
----> 4 torch.hub.list('pytorch/fairseq', force_reload=True)  # [..., 'transformer_lm.wmt19.en', ...]
      5 
      6 # Load an English LM trained on WMT'19 News Crawl data

6 frames
/root/.cache/torch/hub/pytorch_fairseq_master/fairseq/criterions/__init__.py in <module>()
     14     '--criterion',
     15     base_class=FairseqCriterion,
---> 16     default='cross_entropy',
     17 )
     18 
TypeError: 'NoneType' object is not iterable

**Comment by sekewei** [comment]
Maybe the following error is related as it is shown when running torch.hub.list('pytorch/fairseq', force_reload=True) for the first time.

     ModuleNotFoundError: No module named 'fairseq.data.data_utils_fast'

TypeError is shown the second time when running torch.hub.list('pytorch/fairseq', force_reload=True) by ignoring the first error message.

**Comment by sekewei** [comment]
Just found that 'fairseq.data.data_utils_fast' module is available in 'pyx' format.  It requires the following build process for inplace access.

     ~/fairseq$  python setup.py build_ext --inplace

After the inplace build process, an .so shared object is generated for module import.

     ~/fairseq$ ls  fairseq/data/data_utils*
    fairseq/data/data_utils_fast.cpp
    fairseq/data/data_utils_fast.cpython-37m-x86_64-linux-gnu.so
    fairseq/data/data_utils_fast.pyx
    fairseq/data/data_utils.py

**Comment by ngoyal2707** [comment]
Yes, we recently introduced cython dependency to the fairseq code to make data loading faster. So if you have recently git pulled,  you will need to build the *.so files.

**Comment by ayushidalmia** [comment]
This is still happening in the master

**Comment by JoaTesseracto** [comment]
This is still happening to me. ¡Anyone with the same problem? What's the workaround?

**Comment by arpcode** [comment]
This is still happening, any workaround?

**Comment by chloe68** [comment]
It's happening to me too. Does anyone have the solution?

**Comment by LoganLiu66** [comment]
Still happening on data2vec audio infer.

**Comment by ogala8** [comment]
I had the same issue. Apparently upgrading tokenizers was helpful... From: https://stackoverflow.com/questions/68528187/cant-load-transformers-models/70832410#70832410?newreg=130314ccc1094a2cb6ec8ec1cd12228d

**Comment by VidushiVashishth** [comment]
The problem is still happening. It is happening on loading a model in google colab also: 

`import torch`
`roberta = torch.hub.load('pytorch/fairseq', 'roberta.large.mnli', force_reload=True)`

Error message

```7 frames
[~/.cache/torch/hub/pytorch_fairseq_main/fairseq/criterions/__init__.py](https://localhost:8080/#) in <module>
     16 
     17 
---> 18 (
     19     build_criterion_,
     20     register_criterion,

TypeError: cannot unpack non-iterable NoneType object

**Comment by deepak2107** [comment]
> hello was anyone able to find a solution , facing the same issue on google colab. 

TypeError                                 Traceback (most recent call last)
[<ipython-input-16-80b2e5f0892d>](https://localhost:8080/#) in <module>
      8 
      9 
---> 10 xlmr = torch.hub.load('pytorch/fairseq', 'xlmr.large')

7 frames
[~/.cache/torch/hub/pytorch_fairseq_main/fairseq/criterions/__init__.py](https://localhost:8080/#) in <module>
     16 
     17 
---> 18 (
     19     build_criterion_,
     20     register_criterion,

TypeError: cannot unpack non-iterable NoneType object
