### ISSUE TITLE
why did you choose [3,7,15,31,31,31,] as kernel size list of dynamic conv?

### ISSUE THREAD

**Issue by zhaoguangxiang** [pytorch/fairseq#1064]
what is the best kernel size list for 12 layer dynamic conv?

**Comment by zhaoguangxiang** [comment]
i have tried [3,3,7,7,15,15,31,31,31,31,31,31] with scaled initialization , and get bleu scores only 0.1 lower than the baseline.

**Comment by huihuifan** [comment]
Hello, we have not experimented for kernel sizes for 12 layer models. In our experiments, we found growing the kernel size as a bottleneck was helpful, but did not grow the model to 12 layers.
