### ISSUE TITLE
Pretrained RoBERTa model on BOOKS + WIKI

### ISSUE THREAD

**Issue by Michaelvll** [pytorch/fairseq#1065]
Hi,

Thank you for your great codebase. I am wondering if it is possible for you to release the pretrained RoBERTa (base and large) model on the BOOKS + WIKI (16G) dataset or the reimplementation of BERT that you mentioned in the paper.

**Comment by myleott** [comment]
You can download it here: https://dl.fbaipublicfiles.com/fairseq/models/roberta.large.bookswiki.100k.tar.gz

I didn't test it that closely with the latest code, so please first double-check that you get comparable results to those reported in the paper.

You should be able to load the model like so:
```python
from fairseq.models.roberta import RobertaModel
roberta = RobertaModel.from_pretrained('/path/to/roberta.large.bookswiki.100k', 'model.pt')
```

Note that it uses a slightly smaller dictionary, which contains a few hundred fewer tokens at the end. This shouldn't make a difference, just something to keep in mind in case you try to use the main roberta dictionary and have trouble loading the checkpoint.

**Comment by luofuli** [comment]
Can you release the RoBERTa **base** model trained on BOOKS + WIKI?
Or Can you provide scripts that can transfer a BERT TensorFlow checkpoint to fairseq Pytorch checkpoint?
