### ISSUE TITLE
CNN/Dailymail dataset encoding for roberta?

### ISSUE THREAD

**Issue by rush86999** [pytorch/fairseq#1067]
Hello,
 I m looking at a way to use roberta with the cnn/daily mail datset for summarization. I'm looking for guidance on processing this dataset. For example the dataset is in .stories format and gold summaries are not separated but part of the raw data. Using the standford core nlp tokenizer can separate these two parts from the data using @highlight' token but I m not sure how to do the same with bpe?  any suggestions?

**Comment by michaelauli** [comment]
The NLP tokenizer and BPE are likely to do different things in this case. You may want to use BPE processing after you applied a tokenizer.
