### ISSUE TITLE
simple question roberta large gpu requirements?

### ISSUE THREAD

**Issue by rush86999** [pytorch/fairseq#1069]
What minimum size ram for the gpu- (64gb) is required to train roberta large without running into any issues?

**Comment by jordiae** [comment]
> Sorry, are you asking for system memory (RAM) or gpu memory?
> For gpu memory, we have tested on 16 gb GPUs as well, you can reduce `--max-sentences` to minimum that can fit the GPU and increase `--update-freq` to keep the effective batch size to the desired value.

Can I ask what performance did you obtain with this configuration?
