### ISSUE TITLE
Error in fairseq-interactive command

### ISSUE THREAD

**Issue by PC09** [pytorch/fairseq#1077]
Hi , again I am facing a strange issue while running fairseq-interactive. I am running the following command-

cat test.bpe.hi-en.hi | fairseq-interactive data-bin/All_iicl_merged/ --task multilingual_translation --lang-pairs hi-en,bn-en,ml-en,te-en,ta-en,ur-en,en-hi,en-bn,en-ta,en-te,en-ml,en-ur --source-lang hi --target-lang en --path checkpoints/multilingual_transformer/checkpoint_best.pt --buffer-size 200 --batch-size 128 --beam 5 --remove-bpe=sentencepiece

It throws up an error-

Namespace(beam=5, buffer_size=200, cpu=False, criterion='cross_entropy', data='data-bin/All_iicl_merged/', dataset_impl='cached', decoder_langtok=False, diverse_beam_groups=-1, diverse_beam_strength=0.5, encoder_langtok=None, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, gen_subset='test', input='-', lang_pairs='hi-en,bn-en,ml-en,te-en,ta-en,ur-en,en-hi,en-bn,en-ta,en-te,en-ml,en-ur', lazy_load=False, left_pad_source='True', left_pad_target='False', lenpen=1, log_format=None, log_interval=1000, lr_scheduler='fixed', lr_shrink=0.1, match_source_len=False, max_len_a=0, max_len_b=200, max_sentences=128, max_source_positions=1024, max_target_positions=1024, max_tokens=None, memory_efficient_fp16=False, min_len=1, min_loss_scale=0.0001, model_overrides='{}', momentum=0.99, nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, no_repeat_ngram_size=0, num_shards=1, num_workers=0, optimizer='nag', path='checkpoints/multilingual_transformer/checkpoint_best.pt', prefix_size=0, print_alignment=False, quiet=False, raw_text=False, remove_bpe='sentencepiece', replace_unk=None, required_batch_size_multiple=8, results_path=None, sacrebleu=False, sampling=False, sampling_topk=-1, score_reference=False, seed=1, shard_id=0, skip_invalid_size_inputs_valid_test=False, source_lang='hi', target_lang='en', task='multilingual_translation', tbmf_wrapper=False, temperature=1.0, tensorboard_logdir='', threshold_loss_scale=None, unkpen=0, unnormalized=False, upsample_primary=1, user_dir=None, warmup_updates=0, weight_decay=0.0)
| [bn] dictionary: 31728 types
| [en] dictionary: 31728 types
| [hi] dictionary: 31728 types
| [ml] dictionary: 31728 types
| [ta] dictionary: 31728 types
| [te] dictionary: 31728 types
| [ur] dictionary: 31728 types
| loading model(s) from checkpoints/multilingual_transformer/checkpoint_best.pt
Traceback (most recent call last):
File "/home/sriram/anaconda3/envs/py3/bin/fairseq-interactive", line 10, in 
sys.exit(cli_main())
File "/home/sriram/anaconda3/envs/py3/lib/python3.7/site-packages/fairseq_cli/interactive.py", line 185, in cli_main
main(args)
File "/home/sriram/anaconda3/envs/py3/lib/python3.7/site-packages/fairseq_cli/interactive.py", line 83, in main
task=task,
File "/home/sriram/anaconda3/envs/py3/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 153, in load_model_ensemble
ensemble, args, _task = _load_model_ensemble(filenames, arg_overrides, task)
File "/home/sriram/anaconda3/envs/py3/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 171, in _load_model_ensemble
model = task.build_model(args)
File "/home/sriram/anaconda3/envs/py3/lib/python3.7/site-packages/fairseq/tasks/multilingual_translation.py", line 264, in build_model
check_args()
File "/home/sriram/anaconda3/envs/py3/lib/python3.7/site-packages/fairseq/tasks/multilingual_translation.py", line 261, in check_args
raise ValueError(' '.join(messages))
ValueError: --lang-pairs should include all the language pairs ['hi-en', 'bn-en', 'ml-en', 'te-en', 'ta-en', 'ur-en', 'en-hi', 'en-bn', 'en-ta', 'en-te', 'en-ml', 'en-ur'].

Even though I have specified the lang-pairs , its giving me this error. Please let me know a solution. Earlier the same command was working fine.

**Comment by PC09** [comment]
Thanks!. After upgrading to version 0.8, its working fine.

**Comment by rburraAMD** [comment]
Observing below UserWarning message with pytorch-translate .
root/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py:50: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
/root/.local/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py:120: UserWarning: cuDNN/MIOpen library not found. Check your LD_LIBRARY_PATH
  }.get(sys.platform, 'LD_LIBRARY_PATH')))
pytorch_translate/train.py:693: UserWarning: Trainer.get_meter is deprecated. Please use fairseq.metrics instead.
  meter = trainer.get_meter(k)
