### ISSUE TITLE
Roberta: what does Preprocess Step do? 

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#1081]
In many fine-tuning Roberta examples, first, the text gets encoded into tokens and converted into binary format.  Then run another script called **preprocess** which needed a given dictionary. What is this step for?

**Comment by shamanez** [comment]
what do you mean by remapping?

**Comment by militu** [comment]
@myleott, If we generate encoder.json, vocab.bpe for a new language, how can we generate the dict.txt file? 

Thank you.

**Comment by shamanez** [comment]
@sl-victormazzeo  any luck?

**Comment by niuzheng168** [comment]
@myleott  what's the purpose to remap BPE id with a fairseq dictionary?
