### ISSUE TITLE
will you provide evalution scitps for all glue tasks, such  as MRPC, MNLI,  for roberta

### ISSUE THREAD

**Issue by zhaoguangxiang** [pytorch/fairseq#1092]
roberta is a good job, but missing evalution code for all glue tasks in the directory.

**Comment by myleott** [comment]
All GLUE tasks are supported, please see the README here: https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.glue.md

You can preprocess any of the datasets using the name of the dataset, and following the appropriate training config.

**Comment by jiachangliu** [comment]
@myleott I think what he meant to ask if he is looking for code like the following. I tried to revise this code to evaluate MRPC, but it does not work. Could you provide a script to evaluate MRPC?

`from fairseq.models.roberta import RobertaModel

roberta = RobertaModel.from_pretrained(
    'checkpoints/',
    checkpoint_file='checkpoint_best.pt',
    data_name_or_path='RTE-bin'
)

label_fn = lambda label: roberta.task.label_dictionary.string(
    [label + roberta.task.label_dictionary.nspecial]
)
ncorrect, nsamples = 0, 0
roberta.cuda()
roberta.eval()
with open('glue_data/RTE/dev.tsv') as fin:
    fin.readline()
    for index, line in enumerate(fin):
        tokens = line.strip().split('\t')
        sent1, sent2, target = tokens[1], tokens[2], tokens[3]
        tokens = roberta.encode(sent1, sent2)
        prediction = roberta.predict('sentence_classification_head', tokens).argmax().item()
        prediction_label = label_fn(prediction)
        ncorrect += int(prediction_label == target)
        nsamples += 1
print('| Accuracy: ', float(ncorrect)/float(nsamples))`
