### ISSUE TITLE
When calculating the learned embeddings in the transformer   architecture , what is role of the parameter "offset_positions_by_padding" ?

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#1100]
[Please refer to the following line in transformer_sentence_encoder.py ](https://github.com/pytorch/fairseq/blob/master/fairseq/modules/transformer_sentence_encoder.py#L82)

**Comment by lematt1991** [comment]
Sorry for the late reply.  The relevant function is [`make_positions`](https://github.com/pytorch/fairseq/blob/master/fairseq/utils.py#L169).  Basically if we left pad a tensor, we don't want those padded values to contribute to the positional indices.  Consider the following example:

```Python
>>> import torch
>>> from fairseq import utils
>>> x = torch.ones(5, 5)
>>> x[:, 0] = -1
>>> x
tensor([[-1.,  1.,  1.,  1.,  1.],
        [-1.,  1.,  1.,  1.,  1.],
        [-1.,  1.,  1.,  1.,  1.],
        [-1.,  1.,  1.,  1.,  1.],
        [-1.,  1.,  1.,  1.,  1.]])
>>> utils.make_positions(x, -1)
tensor([[-1,  0,  1,  2,  3],
        [-1,  0,  1,  2,  3],
        [-1,  0,  1,  2,  3],
        [-1,  0,  1,  2,  3],
        [-1,  0,  1,  2,  3]])
```
