### ISSUE TITLE
SST-2 performance in ROBERTA paper

### ISSUE THREAD

**Issue by gaopengcuhk** [pytorch/fairseq#1101]
The SST-2 BERT-Large performance listed in ROBERTA paper is much lower then the performance listed in BERT original paper.

93.7 vs 94.9

Any explanation?

**Comment by ngoyal2707** [comment]
`94.9` is on test set from ensemble. `93.7` is on dev. (Table 6 https://arxiv.org/pdf/1810.04805.pdf)
