### ISSUE TITLE
Why abandon sequence longer than max_positions instead of truncate the sentence in ROBERTA Pretraining

### ISSUE THREAD

**Issue by gaopengcuhk** [pytorch/fairseq#1103]
As the name implies, in the ROBERTA Pretraining. All sentence longer than max_positions are abandoned. Have you tried the truncated sentence?

**Comment by myleott** [comment]
It's just an artifact of the dataloader. We assume that "sentences" (rows in the dataset) are shorter than max_positions, but of course "documents" (blocks of sentences, separated by blank lines) are allowed to contain many sentences and can be longer than max_positions.

You can easily add truncation behavior by adding a line similar to this to the MaskedLMTask:
https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/sentence_prediction.py#L132-L133

**Comment by gaopengcuhk** [comment]
Thank you for your reply.

Can you report the performance difference between this two approaches?
1. abandoning longer sentences
2. truncating longer sentences
