### ISSUE TITLE
bug in initialise the num_embedings

### ISSUE THREAD

**Issue by nichongjia** [pytorch/fairseq#1104]
In fairseq/models/fconv.py, it mentioned the FConvEncoder dictionary is optional. If I give the dictionary is None, then 

num_embeddings = len(dictionary)

will have errors.

**Comment by myleott** [comment]
`dictionary` is not optional:
https://github.com/pytorch/fairseq/blob/e75cff5f2c1d62f12dc911e0bf420025eb1a4e33/fairseq/models/fconv.py#L140-L143

Why do you think it's optional?

**Comment by huihuifan** [comment]
I'm closing this, it is not optional to have the dictionary.
