### ISSUE TITLE
Using sentencepiece tokenizer in RoBERTa pretraining regiment 

### ISSUE THREAD

**Issue by nitinnairk** [pytorch/fairseq#1105]
Would it be possible to use sentencepiece tokenizer in preprocessing the data?

**Comment by ngoyal2707** [comment]
Hey @nitinnairk it's definitely possible if you are pretraining from scratch. 
The released pretrained model used GPT2 bpe dictionary so unfortunately you can't use sentencepiece tokenizer with the released model.

**Comment by simonefrancia** [comment]
Is there an example to use sentencepiece tokenizer in preprocessing the data?
