### ISSUE TITLE
Pretrained translation models downloaded using torch.hub don't use GPU; generation is extremely slow

### ISSUE THREAD

**Issue by tholiao** [pytorch/fairseq#1107]
Generating translations using a pretrained torch hub model doesn't seem to use the GPU. 

I'm getting the model like so:
```python
model = torch.hub.load("pytorch/fairseq", "transformer.wmt16.en-de", checkpoint_file="model.pt",  tokenizer="moses", bpe="subword_nmt")
```

And I'm translating text in this way:
```python
with open(src_path, 'r') as src_file:
    for src_line in src_file:
        print(model.translate(src_line))
```

But nvidia-smi doesn't show any GPU utilization and generation is extremely slow (perhaps an order of magnitude slowdown). Is there a configuration flag or other option that I'm missing? 

I'm able to run pretrained models downloaded manually.

**Comment by myleott** [comment]
In this case `model` is an nn.Module that's loaded on CPU by default. You should call `model.cuda()`
