### ISSUE TITLE
Please clarify BLEU score for pre-trained Ng'19 model on newstest2017 en-de

### ISSUE THREAD

**Issue by tholiao** [pytorch/fairseq#1108]
The [provided pretrained Ng'19 model](https://github.com/pytorch/fairseq/tree/master/examples/translation) is an ensemble model, but the ablation table (figure 5) in *Facebook FAIR’s WMT19 News Translation Task Submission* doesn't report scores after +finetuning +ensemble on newstest2017 for en-de. Would you mind sharing the score? Thanks!

Also, is it the case that the scores reported for the baseline model is one in the pretrained ensemble (i.e. `model{i}.pt` for some `i`)?

**Comment by edunov** [comment]
We did not report scores after +finetuning +ensemble on newstest2017 because newstest2017 was used for finetuning, so reporting BLEU scores on it would be misleading.  

The baseline model is one of the pretrained model (most likely i=1)
