### ISSUE TITLE
Roberta: Finetuning RoBERTa on a custom classification task| Can we use multiple GPUs?

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#1109]

**Comment by ngoyal2707** [comment]
Yes, everything [here](https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.custom_classification.md#5-run-training) remains the same, just set `CUDA_VISIBLE_DEVICES` to available gpu `device_id` and adjust `lr` as per your new `bsz`
