### ISSUE TITLE
Anyway to use the trained model to translate on a raw text file?

### ISSUE THREAD

**Issue by getao** [pytorch/fairseq#111]
Hello! I noticed that current implementation supports translate a binaried file or the input from stdin. I wonder if there is any way to translate a raw text file because this setting is very common in practice.

Redirect is a workaround but it cannot support translating in a batch, leading to very slow inference for a large file.

**Comment by edunov** [comment]
You can pipe your file, something like this:

```
cat  file_you_want_to_translate.txt | python ./interactive.py $DATA --path path_to_checkpoint | tee output_file.txt
```

You may need to apply BPE first if your model was trained with BPE, in that case, you may also want to add --remove-bpe to the interactive.py

**Comment by edunov** [comment]
Sorry, missed your last sentence
Yes, I see there is a use case for large translation tasks. I'll check what can be done

**Comment by getao** [comment]
@edunov Thank you very much.

**Comment by edunov** [comment]
With the latest version of fairseq-py you should be able to use --only-source in preprocess.py to process monolingual data (you can make convert it into valid or test), example usage:

```
python ./preprocess.py --srcdict ~/iwslt14.tokenized.de-en.14000/dict.de.txt --only-source --validpref ~/fairseq-py/data/iwslt14.tokenized.de-en/test --destdir ~/tmp/ -s de -t en
```

You can then use generate.py on that processed set to generate efficiently (also you can use --num-shards and --shard-id to run the generation in parallel on multiple machines or multiple GPUs) 

Hope, that works for you. Please let me know if you encounter any issues.

**Comment by getao** [comment]
@edunov Thank you very much!

**Comment by huihuifan** [comment]
For solution b, you can do this by filling a target file with blank lines and then binarizing it with the source. What kind of changes would you want? This to be automatically done?

**Comment by myleott** [comment]
Re: option a (interactive.py), make sure to set `--buffer` so that it will read sentences into a buffer and batch them. This will make generation much much faster.

@huihuifan, I think we just need to repro that the `--only-source` option fails on master and then fix it. At least it used to work...

**Comment by ereday** [comment]
@edunov thanks for sharing a sample command for translating raw txt files. I tried it as follows:

` cat sample_data.txt`
```
My name is ereday .
I like cats .
Education is the passport to the future , for tomorrow belogns to those who prepare for it today .

```
Command to run: 

`cat ../sample_data.txt | python ./interactive.py --remove-bpe  --path ../wmt14.en-de.fconv-py/model.pt | tee output_file.txt`

However I am getting `interactive.py: error: the following arguments are required: data` error. 

I tried to provide it as follows:
`cat ../sample_data.txt | python ./interactive.py --data ../sample_data.txt --remove-bpe  --path ../wmt14.en-de.fconv-py/model.pt | tee output_file.txt`

I get : 
`interactive.py: error: unrecognized arguments: --data` error.

How can I use your suggestion for my case ?

**Comment by myleott** [comment]
You need to provide a path to a directory containing the dictionary (same as you gave during training). For example, if during training you had: `train.py data-bin/ (...)` then you’d do: `cat sample_data.txt | interactive.py data-bin/ (...)`

**Comment by ereday** [comment]
I didn't train the models. I just want to use a pre-trained model (shown [here](https://github.com/pytorch/fairseq/blob/a24880bd10f3c3101b3bc993947ef92a83f1ad4f/examples/translation/README.md#pre-trained-models)) to translate a small raw text file. Therefore, I don't have any data-bin/ directory. Is it the directory where the model and rawfile needs to be in ? Another question: Should I use any special format for raw-text file or just one example(sentence/paragraph) per line is enough?

**Comment by myleott** [comment]
Point it to the directory that contains dict.txt. All of the pretrained models should come with the dictionary.

Yes, one sentence per line, assuming you’ve tokenized it with Moses tokenizer (which is what was used in training).

**Comment by sicklife** [comment]
![image](https://user-images.githubusercontent.com/8018334/70585216-80840400-1bfe-11ea-9c8a-8dc502222e01.png)

add `--buffer-size ` option doesn't make the translation faster.

![image](https://user-images.githubusercontent.com/8018334/70585360-fd16e280-1bfe-11ea-896a-b8a3b7fe8163.png)

according to the source code of `interactive.py`, it seems adding the `buffer-size` arg only increase the batch length that  `make_batches` function return, but every sentence(sample) in the `batch` still have to iter through the `task.inference_step` function. And I don't think this is a real `batch`…………

**Comment by sangjeedondrub** [comment]
`buffer-size` needs to be larger than `batch-size`

```
cat raw.txt | python -m fairseq_cli.interactive $bindata \
    --path $model_path \
    --batch_size 128 --beam 5 --buffer-size 256  2>&1 | tee out.txt
```
