### ISSUE TITLE
Sentence Pair Classification on custom corpus

### ISSUE THREAD

**Issue by subhamkhemka** [pytorch/fairseq#1110]
Hi,

Thanks for releasing Roberta.

The example shows how to fine tune custom classification task using imdb corpus.

How can I fine tune roberta-mnli-large model on my own sentence pair corpus ?
In other words how do i use the roberta-mnli-large weights to further train on my own corpus?
Please help

Thanks

**Comment by ngoyal2707** [comment]
It's mostly going to be similar to steps described here: https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.glue.md 
Just that you will need `input0` and `input1` under your `data-bin/` directory. 

Let me know if you have more questions about this.

**Comment by subhamkhemka** [comment]
Hi @ngoyal2707 

I have followed the steps as specified, however get the following error :

`ValueError: Expected input batch_size (8) to match target batch_size (16).`
If I change the max_sentences to 16 then it expects target size 32 and so on.

Please help
