### ISSUE TITLE
Translation is very slow - only 3 words per second on GTX 1080.

### ISSUE THREAD

**Issue by Oxi84** [pytorch/fairseq#1112]
Hi,
I tried the translate german to english, but I have found it is very slow, around 2 sec per sentence. And I run it on GTX 1080, which is a quite fast card. I read that other gets 10 000 words per  second or more. 

I am I doing something wrong? I run Bert with cuda 10.0 and it works fine. Is there anything else I could do to speed it up. Around 1000 words per second would be good enough for me.
    
    import torch
    import fairseq
    import time
    de2en = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.de-en', checkpoint_file='model1.pt:model2.pt:model3.pt:model4.pt', tokenizer='moses', bpe='fastbpe')
	text_input = "Maschinelles Lernen ist großartig!"
	begin = time.time()
	text_de = en2de.translate(text_input)
	print("text_de",text_de)

**Comment by Oxi84** [comment]
I have found solution here - https://github.com/pytorch/fairseq/blob/master/examples/wmt19/README.md

**Comment by gvskalyan** [comment]
Since it is an ensemble model and you translating just one sentence you might not be able to see gaines on GPU.
If it is batched translation you will clearly see the difference atleast on a single model.

**Comment by Oxi84** [comment]
Thanks, its faster when use cuda add - around 1.5 sec per sentence, Is there simple way to do sentences in batch?  
There is an example in generate, but only for model in 14 and 17 and the new 2019 model has multiple files for model so I do not know how to use and pad these.

**Comment by gvskalyan** [comment]
You can use even model in 14 if it avaible in hub to load them [refer](https://github.com/pytorch/hub/blame/master/pytorch_fairseq_translation.md#L46)
While loading and using model from torch hub to [translate](https://github.com/pytorch/fairseq/blob/master/fairseq/hub_utils.py#L102) it is same as using generate script.
So both of them can be used interchangeably I suppose.

**Comment by tuhinjubcse** [comment]
@Oxi84 did you do anything to speed this up ??

**Comment by lematt1991** [comment]
Closing in favor of #1508
