### ISSUE TITLE
The performance 29.3 in table 2 is single model performance of ensemble performance? (Scaling neural machine translation

### ISSUE THREAD

**Issue by gaopengcuhk** [pytorch/fairseq#1113]
I run the big transformer according to scaling machine translation. However, I can only get 28.3 finally.

**Comment by huihuifan** [comment]
it is single model performance, what parameters are you using at generation time? how are you running the generation?

**Comment by myleott** [comment]
29.3 is a single model, but we apply checkpoint averaging (similar to Vaswani et al.) and also use the same decoding parameters that they did (`--beam 4 --lenpen 0.6`).

I recently added some more information about this here: https://github.com/pytorch/fairseq/tree/master/examples/scaling_nmt#4-evaluate
