### ISSUE TITLE
Not using GPU when training NMT model?

### ISSUE THREAD

**Issue by JJumSSu** [pytorch/fairseq#1117]
Hi, first of all, thank you for providing such a nice library. 

I'm currently trying to train NMT model from scratch using fairseq library.  I referred "https://github.com/pytorch/fairseq/blob/master/examples/translation/README.md" in training the transformer model on IWSLT German14 dataset. I managed to get it running, but it seems that my model is not training on GPU. I set CUDA_VISIBLE_DEVICES=0 and checked that the configuration output states "training on 1 GPU". But when I checked by the Linux command "nvidia-smi", nothing seems to be running on GPU. Did I do something wrong? (It takes 2.4 s/it when training on IWSLT14 German by using a single TitanXP, and I'm not sure it is fast or not.)

**Comment by myleott** [comment]
What is the output of this:
```bash
CUDA_VISIBLE_DEVICES=0 python -c 'import torch; print(torch.cuda.device_count())'
```

If it's not 1, then there's something wrong with your pytorch installation not being setup for GPU use.

**Comment by JJumSSu** [comment]
Yeap, it seems that my pytorch was not properly installed. I'll try to re-install it. Thanks!
