### ISSUE TITLE
Train accuracy is about 20% when fine tune Roberta

### ISSUE THREAD

**Issue by chiangyulun0914** [pytorch/fairseq#1121]
I follow the fine tune scripts on the github, and the train accuracy about commonsense task is about 20%. What's wrong that I don't notice ?

![image](https://user-images.githubusercontent.com/36063123/64592659-0cf41000-d3df-11e9-9408-036353054cbb.png)

**Comment by yuchenlin** [comment]
having the same problem here...

**Comment by yuchenlin** [comment]
Hi @myleott , is there any idea about it?  Thanks!
