### ISSUE TITLE
Roberta-base on SQuAD v2

### ISSUE THREAD

**Issue by adymaharana** [pytorch/fairseq#1132]
Hi,

Thanks for the great work on RoBERTa model! I am trying to run it on SQuAD version 2 dataset. I see results of the RoBERTa-large model finetuned on SQuAD reported in the paper, however its a bit difficult for me to replicate those results because of the lack of resources. I am running fine-tuning experiments for the base model though and wanted to know if you had any hyperparameter guidelines or results for the sake of comparison? Please let me know, it would be a great help! Thanks.

**Comment by myleott** [comment]
@yinhanliu

**Comment by myleott** [comment]
Closing in favor of #933
