### ISSUE TITLE
Runtime error - custom classification task

### ISSUE THREAD

**Issue by subhamkhemka** [pytorch/fairseq#1136]
Hi

I am training classification model with two questions.
I have created input0, input1 and label folder for the input in data-bin folder.

I have 3 labels [0,1,2]
Using the roberta.large.mnli/model.pt as path

TOTAL_NUM_UPDATES=200  
WARMUP_UPDATES=30    
LR=1e-05                
NUM_CLASSES=3
MAX_SENTENCES=4

Following command to execute
CUDA_VISIBLE_DEVICES=0 python train-dup-main.py semantic-bin/ \
    --restore-file $ROBERTA_PATH \
    --max-positions 512 \
    --max-sentences $MAX_SENTENCES \
    --max-tokens 100 \
    --task sentence_prediction \
    --reset-optimizer --reset-dataloader --reset-meters \
    --required-batch-size-multiple 1 \
    --init-token 0 --separator-token 2 \
    --arch roberta_large \
    --criterion sentence_prediction \
    --num-classes $NUM_CLASSES \
    --dropout 0.1 --attention-dropout 0.1 \
    --weight-decay 0.1 --optimizer adam --adam-betas "(0.9, 0.98)" --adam-eps 1e-06 \
    --clip-norm 0.0 \
    --lr-scheduler polynomial_decay --lr $LR --total-num-update $TOTAL_NUM_UPDATES --warmup-updates $WARMUP_UPDATES \
    --fp16 --fp16-init-scale 4 --threshold-loss-scale 1 --fp16-scale-window 128 \
    --max-epoch 10 \
    --find-unused-parameters \
    --best-checkpoint-metric accuracy --maximize-best-checkpoint-metric;

However while training getting following error :
`/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "train-dup-main.py", line 326, in <module>
    cli_main()
  File "train-dup-main.py", line 322, in cli_main
    main(args)
  File "train-dup-main.py", line 81, in main
    train(args, trainer, task, epoch_itr)
  File "train-dup-main.py", line 122, in train
    log_output = trainer.train_step(samples)
  File "/home/ubuntu/fairseq/fairseq/trainer.py", line 313, in train_step
    raise e
  File "/home/ubuntu/fairseq/fairseq/trainer.py", line 289, in train_step
    ignore_grad
  File "/home/ubuntu/fairseq/fairseq/tasks/fairseq_task.py", line 231, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/fairseq/fairseq/criterions/sentence_prediction.py", line 62, in forward
    'loss': utils.item(loss.data) if reduce else loss.data,
  File "/home/ubuntu/fairseq/fairseq/utils.py", line 219, in item
    return tensor.item()
RuntimeError: CUDA error: device-side assert triggered`

Please help

**Comment by huihuifan** [comment]
are you sure you only have 3 classes in the dataset? 

cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion t >= 0 && t < n_classesfailed.

see: "t >= 0 && t < n_classes" this part specifically in the error. Please check that

**Comment by subhamkhemka** [comment]
Yes there are only 3 classes

**Comment by huihuifan** [comment]
Hello, no problem. Glad you found your issue. It’s because when you add the
srcdict parameter, you are telling the code to binarize your dataset with
that specific fixed dictionary. This will introduce more than 3 labels,
causing the error in NLLCriterion. Hope that helps.
