### ISSUE TITLE
Error on unrecognized arguments --adam-betas

### ISSUE THREAD

**Issue by mortonjt** [pytorch/fairseq#1146]
I got this error when trying to run distributed training

`fairseq-train: error: unrecognized arguments: 0.98)'`

Below is the command

```
$(which fairseq-train) $DATA_DIR --fp16 \
    --task masked_lm --criterion masked_lm \
    --arch roberta_base --sample-break-mode complete --tokens-per-sample $TOKENS_PER_SAMPLE \
    --optimizer adam --adam-betas '(0.9, 0.98)' --adam-eps 1e-6 --clip-norm 0.0 \
    --lr-scheduler polynomial_decay --lr $PEAK_LR --warmup-updates $WARMUP_UPDATES --total-num-update $TOTAL_UPDATES \
    --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 \
    --max-sentences $MAX_SENTENCES --update-freq $UPDATE_FREQ \
    --max-update $TOTAL_UPDATES --log-format tqdm --log-interval 1 \
    --save-interval-updates 1 \
    --keep-interval-updates 3 \
    --tensorboard-logdir $TB_DIR \
    --save-dir $SAVE_DIR
```

The fix is actually easy, change `--adam-betas '(0.9, 0.98)'` -> --adam-betas '(0.9,0.98)' argparse must be parsing by spaces only.

Posting here just in case this hasn't already been encountered.

**Comment by myleott** [comment]
Hmm, as long as it's in quotes the spaces are fine on my system. But if removing the space is more portable, then it'd be great if you could submit a PR updating the README :)
