### ISSUE TITLE
Support for On The Fly Tokenization?

### ISSUE THREAD

**Issue by minstar** [pytorch/fairseq#1148]
Hi, I’m currently looking for a way to do tokenization on the fly. So eventually, I want raw text as an input for training and do tokenization while training. (Similar to subword regularization training)

All the examples say I should pre tokenize and build dictionary and binarized data forehand to do training. But in my situation, the tokenized result gets changed every epoch, this kind of process doesn’t fit.

Any suggestions? Or code that I can reference?

Thank you

**Comment by minstar** [comment]
https://fairseq.readthedocs.io/en/latest/command_line_tools.html

In this link, there is an option called ”bpe”both in fairseq-preprocess and fairseq-train. Is this option available? If yes, then there is no need to apply bpe to raw text before calling fairseq-preprocess?

**Comment by huihuifan** [comment]
you could modify the batching mechanism to read raw text and tokenize on the fly there (with your different tokenizers).

**Comment by minstar** [comment]
Thank you for quick and nice reply. Then I should use the option “dataset-impl” as raw and tokenize while training. Then should I re binarize given tokenized text during training? Before feeding the input to model?

**Comment by lematt1991** [comment]
I would follow [`IndexedRawTextDataset`](https://github.com/pytorch/fairseq/blob/master/fairseq/data/indexed_dataset.py#L230) as an example.  You should be able to just move the `dictionary.encode_line...` line into `__getitem__`.

**Comment by minstar** [comment]
@lematt1991 
Hi, Thanks to your helpful reply, I managed to get my model training with on the fly tokenization. 
Thank you so much for that.

I have just a small issue, which is during training, it occasionally skips some batch due to OOM issue. I didn't happen when I didn't apply training on the fly tokenization.

I presume this may be due to not exactly calculating IndexedRawTextDataset's variable "__sizes__", which is used to make batches according to sentences' size. I can't get this "__sizes__" exactly, becaue the tokenization happens during getitem as you mentioned. 

Any suggestion or other reasons for this OOM?

I even reduced the batch size, but still during training, it skips some bathes in training. (3~4? batches out of 3698)

**Comment by lematt1991** [comment]
How are you populating the [`sizes`](https://github.com/pytorch/fairseq/blob/master/fairseq/data/indexed_dataset.py#L252) attribute in your dataset class?  Is it based on number of characters?  This is going to be an inherent problem with on-the-fly tokenization as you won't know exactly how many tokens a sequence has up front when batching if performed.  Also, how are you specifying batchsize (`--max-tokens` or `--max-sentences`)?

**Comment by minstar** [comment]
@lematt1991 
Thank you for your prompt and such a nice reply.
I'm currently guessing the ```sizes``` attribute by pre tokenizing the given sentence with Sentencepiece(best segment result). Also during ```__getitem__```, I used sentencepiece's best segmented result as an on the fly tokenization method. I'm using the tokenization method which was used to calculate the size of given sentence, so I wonder why OOM happens in some batches. 
Also I specified --max-sentences as 64 which is lower than that of base configuration(base configuration was 128, or max-tokens 4000, I guess?)

Thank you!

**Comment by lematt1991** [comment]
It's hard to say without being able to look at the code.  You might try setting up the dataset interactively, and inspecting the `sizes` attribute to ensure that they are what you'd expect.  Something like:

```Python
from fairseq.data import IndexedRawTextDataset
ds = IndexedRawTextDataset(<path to dataset>)  # path to source or target side of training data
print(ds.sizes)
```

**Comment by minstar** [comment]
@lematt1991 
I solved the problem. As you mentioned, there was something wrong in getting ```sizes```. 
Thank you so much. Training with on the fly tokenization method works nicely, reproducing the result of the original one's. 
Thank you!!
