### ISSUE TITLE
Wrong instructions for storing system and reference translations in `examples/translation/README.md'

### ISSUE THREAD

**Issue by skeshaw** [pytorch/fairseq#1149]
In the [example usage](https://github.com/pytorch/fairseq/tree/master/examples/translation#example-usage-cli-tools) in README for translation tasks, wrong pattern seems to be passed.
Since system and reference translations start with the pattern `S-` and `T-`, respectively, that should be the only difference in the two commands. More specifically,
```
grep ^H /tmp/gen.out | cut -f3- > /tmp/gen.out.sys
```
should be replaced with
```
grep ^S /tmp/gen.out | cut -f2- > /tmp/gen.out.sys
```

**Comment by myleott** [comment]
S is "source", T is "target" and H is "hypothesis". So actually it is H that is the system translation. Sorry this should be better documented somewhere. If you'd like, please submit a PR updating the translation README indicating the mapping I just mentioned :)

**Comment by skeshaw** [comment]
My apologies for earlier. Quite an oversight on my part, hadn't really looked into the generated file. Will raise a PR later for the update that you mentioned.
Thanks.
