### ISSUE TITLE
RoBERTa:  multiprocessing_bpe_encoder.py and roberta.encode() give different outputs (?)

### ISSUE THREAD

**Issue by ypapanik** [pytorch/fairseq#1150]
Congratulations on you work and on publishing the roberta code, this means tons for a lot of people.
I am trying to do finetuning on a custom classification task and trying to put the pieces together. 
So, in order to do the finetuning I need to bpe encode the train and dev tests, which is done with 
https://github.com/pytorch/fairseq/blob/master/examples/roberta/multiprocessing_bpe_encoder.py
But then, when I do prediction with a finetuned model, the instructions say to use roberta.encode().
These two don't produce the same output. For instance if I give them the following sentence:

`two cases of severe delayed ENTITY_A related to the administration of intrathecal ( it ) combination chemotherapy including ENTITY_B ( ENTITY_B ) are presented.`
I get this encoding for the first method:
`[11545 2663 286 6049 11038 47353 9050 62 32 3519 284 262 3662 286 9913 26221 9948 357 340 1267 6087 34696 1390 47353 9050 62 33 357 47353 9050 62 33 1267 389 5545 13]`
and this with roberta.encode():
`tensor([    0,  7109,  1200,     9,  3814,  5943, 27329,  8662,  1215,   250,
         1330,     7,     5,   942,     9, 19567, 23872, 11762,    36,    24,
         4839,  4069, 17930,   217, 27329,  8662,  1215,   387,    36, 27329,
         8662,  1215,   387,  4839,    32,  2633,     4, 50118,     2])`
I understand as you explain the 0 and 2 tokens, but what happens with the rest? Shouldn't these two be identical, I mean don't we need to have the same encoding during training and prediction?
A hint: `multiprocess_bpe_encoder.py` uses this `from fairseq.data.encoders.gpt2_bpe import get_encoder` while roberta.encode() uses this: https://github.com/pytorch/fairseq/blob/0eaaf3551659de40dcb273b7a0a3272e50a6e38a/fairseq/models/roberta/hub_interface.py#L27

**Comment by myleott** [comment]
Ah, sorry this isn't clear in the documentation, but fairseq actually uses two layers of dictionaries.

The first is the GPT-2 BPE, which converts raw text into a string of numbers (the `11545 2663 286 6049 11038 47353 ...` sequence). Then fairseq internally remaps these using its own dictionary, which is what `roberta.encode` returns and what the model expects as input. This second remapping is what the `fairseq-preprocess` step in the README is doing: https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md#1-preprocess-the-data.
