### ISSUE TITLE
Two comments in lstm.py seem to be incorrect

### ISSUE THREAD

**Issue by vineetk1** [pytorch/fairseq#1154]
This issue is in the file lstm.py [https://github.com/pytorch/fairseq/blob/master/fairseq/models/lstm.py](url)

Seems to me that the comment `# x: bsz x output_embed_dim` in line 286 should be changed to `# x: bsz x source_embed_dim` because in Line 279 `self.input_proj = Linear(input_embed_dim, source_embed_dim, bias=bias)` the Linear layer converts input_embed_dim to source_embed_dim

If the comment on Line 286 is changed then it seems that the comment on Line 284 `# source_hids: srclen x bsz x output_embed_dim` should be changed to `# source_hids: srclen x bsz x source_embed_dim`

Question: Is output_embed_dim  equal to  source_embed_dim

**Comment by vineetk1** [comment]
Adding to the Issue, it would make sense to point out that `output_embed_dim` is the dimension of the context vector generated by Attention

**Comment by lematt1991** [comment]
Agreed, feel free to submit a PR!

**Comment by lematt1991** [comment]
It looks like `source_embed_dim` wasn't added until 9196c0b6544c916ef9f2178a9a45cc06d264db49, and the comments never got updated.

**Comment by vineetk1** [comment]
PR submitted.

**Comment by lematt1991** [comment]
Resolved with #1185.  Thanks!
