### ISSUE TITLE
whether the v0.7.2 can use --fp16 without the gpu type of V100？

### ISSUE THREAD

**Issue by jiezhangGt** [pytorch/fairseq#1157]
whether the v0.7.2 can use --fp16 without the gpu type of V100？I found that I can use others GPU to run with --fp16， and don't have any warning. what 's more, the wps is 7w+.

**Comment by huihuifan** [comment]
Sorry, can you please clarify your question for me? You are asking with the latest version 0.7.2 if you can use floating point 16 even if you don't have a GPU that supports floating point 16? I believe the use of fp16 is tied to your GPU, not the version of software.

**Comment by jiezhangGt** [comment]
> Sorry, can you please clarify your question for me? You are asking with the latest version 0.7.2 if you can use floating point 16 even if you don't have a GPU that supports floating point 16? I believe the use of fp16 is tied to your GPU, not the version of software.

Sorry, maybe I didn't describe my problem clearly. what I mean is when I training my translation model with nvidia's TITAN V GPU, and use ```--fp16```. I found that the fp16 seems to work, but in my mind, trainning with fp16 Only can be effective on nvidia's V100 GPU.

**Comment by ngoyal2707** [comment]
The `--fp16` support depends on the GPU capability. In your case, you seem to have `Titav V` which has compute capability of 7.0 and that seem to support `fp16` (https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#arithmetic-instructions)
