### ISSUE TITLE
OOM(CUDA) Issue when working with raw text during translation

### ISSUE THREAD

**Issue by JJumSSu** [pytorch/fairseq#1159]
Hi, Thanks for such a nice library you guys are providing.

I am currently changing the fairseq library's code to implement tokenization on the fly.

I preprocessed without changing the format into MMAPindexed dataset, but kept it raw. And then I removed "dict.encode_line()" part in indexed_dataset.py's IndexedRawTextdataset class, where originally this part changed the given text into indexed numbers. 

Since I want to do tokenization on the fly, I removed this part and modified LanguagePairDataset's "__getitem__ "part to transform given text into indexed numbers using tokenizer. After changing several issues, I managed to get it ruuning, but OOM issue happens.

![image](https://user-images.githubusercontent.com/39372342/65402026-c4891900-de06-11e9-9afe-b03ff5ee9c62.png)

It's trying to allocate 119.17 GiB, so I presume that this tokenization process is trying to change the whole data at once. I have no idea where to fix this. Any help?

**Comment by lematt1991** [comment]
I would try inspecting the tokenized samples to make sure they are what you'd expect first.  For example:

```Python
from fairseq.data import IndexedCachedDataset  # or change to the name of your modified class
ds = IndexedCachedDataset('data-bin/iwslt17/train.en-fr.en')  # or some path to one side of your training set
ds.prefetch(range(0, 10))  # if your dataset supports prefetching
print(ds[0])
```

This may help to uncover any bugs.  It's difficult to provide much advice without being able to see the code.  Hope this helps!

**Comment by JJumSSu** [comment]
I solved the problem. Thank you so much. @lematt1991

**Comment by ntsliyang** [comment]
@JJumSSu How did you solve the OOM issue? I got OOM issue whenever I tried to load train dataset in the training loop (and it takes a long time to load train dataset).
