### ISSUE TITLE
Loading embeddings (e.g. GloVe) to transformer networks

### ISSUE THREAD

**Issue by maliPX** [pytorch/fairseq#1161]
Hi,
could someone please show me a example of loading GloVe embeddings  to a transformer network based on the "Train a language model" example? 

I tried to load it with following command:

!fairseq-train \
    --task language_modeling \
    drive/My\ Drive/research/data-bin/wikitext-103 \
    --save-dir drive/My\ Drive/research/checkpoints/transformer_wikitext-103 \
    \
    --arch transformer \
    --max-update 286000 --max-lr 1.0 --t-mult 2 --lr-period-updates 270000 --lr-scheduler cosine --lr-shrink 0.75 \
    --warmup-updates 16000 --warmup-init-lr 1e-07 --min-lr 1e-09 --optimizer nag --lr 0.0001 --clip-norm 0.1 \
    --criterion adaptive_loss --max-tokens 3072 --update-freq 3 --tokens-per-sample 3072 --seed 1 \
    --sample-break-mode none --skip-invalid-size-inputs-valid-test --ddp-backend=no_c10d \
    \
    --encoder-embed-path drive/My\ Drive/research/embeddings/glove_embeddings_test.txt \
    --encoder-embed-dim 50 \
    --encoder-attention-heads 2 \
    --decoder-embed-path drive/My\ Drive/research/embeddings/glove_embeddings_test.txt \
    --decoder-embed-dim 50 \
    --decoder-attention-heads 2 \
    --no-token-positional-embeddings 

but i got this error:

Namespace(activation_dropout=0.0, activation_fn='relu', adaptive_input=False, adaptive_softmax_cutoff=None, adaptive_softmax_dropout=0, add_bos_token=False, arch='transformer', attention_dropout=0.0, best_checkpoint_metric='loss', bpe=None, bucket_cap_mb=25, clip_norm=0.1, cpu=False, criterion='adaptive_loss', curriculum=0, data='drive/My Drive/research/data-bin/wikitext-103', dataset_impl=None, ddp_backend='no_c10d', decoder_attention_heads=2, decoder_embed_dim=50, decoder_embed_path='drive/My Drive/research/embeddings/glove_embeddings_test.txt', decoder_ffn_embed_dim=2048, decoder_input_dim=50, decoder_layers=6, decoder_learned_pos=False, decoder_normalize_before=False, decoder_output_dim=50, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, dropout=0.1, encoder_attention_heads=2, encoder_embed_dim=50, encoder_embed_path='drive/My Drive/research/embeddings/glove_embeddings_test.txt', encoder_ffn_embed_dim=2048, encoder_layers=6, encoder_learned_pos=False, encoder_normalize_before=False, fast_stat_sync=False, find_unused_parameters=False, fix_batches_to_gpus=False, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, future_target=False, keep_interval_updates=-1, keep_last_epochs=-1, lazy_load=False, log_format=None, log_interval=1000, lr=[0.0001], lr_period_updates=270000.0, lr_scheduler='cosine', lr_shrink=0.75, max_epoch=0, max_lr=1.0, max_sentences=None, max_sentences_valid=None, max_target_positions=None, max_tokens=3072, max_tokens_valid=3072, max_update=286000, maximize_best_checkpoint_metric=False, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=1e-09, momentum=0.99, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_save=False, no_save_optimizer_state=False, no_token_positional_embeddings=True, num_workers=1, optimizer='nag', optimizer_overrides='{}', output_dictionary_size=-1, past_target=False, raw_text=False, required_batch_size_multiple=8, reset_dataloader=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', sample_break_mode='none', save_dir='drive/My Drive/research/checkpoints/transformer_wikitext-103', save_interval=1, save_interval_updates=0, seed=1, self_target=False, sentence_avg=False, share_all_embeddings=False, share_decoder_input_output_embed=False, skip_invalid_size_inputs_valid_test=True, t_mult=2.0, task='language_modeling', tbmf_wrapper=False, tensorboard_logdir='', threshold_loss_scale=None, tokenizer=None, tokens_per_sample=3072, train_subset='train', update_freq=[3], use_bmuf=False, user_dir=None, valid_subset='valid', validate_interval=1, warmup_init_lr=1e-07, warmup_updates=16000, weight_decay=0.0)
| dictionary: 69776 types
| loaded 3760 examples from: drive/My Drive/research/data-bin/wikitext-103/valid
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/content/fairseq/fairseq_cli/train.py", line 322, in cli_main
    main(args)
  File "/content/fairseq/fairseq_cli/train.py", line 51, in main
    model = task.build_model(args)
  File "/content/fairseq/fairseq/tasks/language_modeling.py", line 145, in build_model
    if target not in model.supported_targets:
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'TransformerModel' object has no attribute 'supported_targets'

**Comment by lematt1991** [comment]
I think the problem is that you are using `--arch transformer`, instead of `--transformer_lm`.  That said, we should probably provide a check that the model built is a subclass of `FairseqLanguageModel` when using the `language_modeling` task

**Comment by maliPX** [comment]
thans for your fst answer but with --transformer_lm i cant use decoder or encoder embeddings :( 

I got following error:

fairseq-train: error: unrecognized arguments: --encoder-embed-path ... --encoder-embed-dim 50

**Comment by lematt1991** [comment]
That's correct.  `transformer_lm` does not support pretrained embeddings.  If you'd like to use pretrained embeddings for LM, then you'll need to modify `transformer_lm` in the same way as `transformer`.
