### ISSUE TITLE
DataLoader worker (pid(s) 412512) exited unexpectedly in ptvsd

### ISSUE THREAD

**Issue by fuzihaofzh** [pytorch/fairseq#1173]
I debug fairseq with ptvsd. However, it encountered the following error:

```
DataLoader worker (pid(s) 412512) exited unexpectedly
```

After some investigation, I found that the data loader uses Multiprocessing which causes this problem. Setting `--num-workers` to 0 solves this problem. Is it possible to set the default value of `--num-workers` to 0? It has the same effect while avoiding errors in ptvsd.

**Comment by lematt1991** [comment]
No, it's much slower.  If you want to debug, you'll have to manually set `--num-workers` to 0.
