### ISSUE TITLE
multi-encoder

### ISSUE THREAD

**Issue by PersianNLPer** [pytorch/fairseq#1175]
Hello,
I took a quick look at the options of FairSeq and it seems to me that it doesn't support multi-encoder at the moment. Am I right? Is there any plan to add it to the codebase in near future?

Thank you very much,
Amin

**Comment by huihuifan** [comment]
By multi-encoder, do you mean multiple encoders? You can do this yourself- just define a new model function and be like "encoder1 = TransformerEncoder()", "encoder2 = TransformerEncoder" and you can look at the composite encoder defined in the self attention convolution model in the model directory

**Comment by PersianNLPer** [comment]
Thank you very much for the info. I am going to do it!
:-)
