### ISSUE TITLE
unable to use multiple GPUs while training for translation

### ISSUE THREAD

**Issue by aastha19** [pytorch/fairseq#1176]
Hi 

Please let me know how to use multiple GPUs for training.
using all the gpus results in  process 6 terminated with signal SIGKILL.

**Comment by huihuifan** [comment]
This is too vague, what command are you using and what error are you getting? Is there a stacktrace?

**Comment by aastha19** [comment]
Command used:
 python3.6 train.py data-bin-2cr --lr 0.8 --clip-norm 0.1 --dropout 0.2 --max-tokens 4000 --arch lstm --save-dir checkpoints/lstm_2cr
Stack Trace:
![image](https://user-images.githubusercontent.com/14852345/65658510-b7a63880-e045-11e9-9052-c44ea50c3e79.png)

**Comment by lematt1991** [comment]
If you are getting CUDA out of memory errors, you should reduce the size of your batch by setting `--max-tokens` to a smaller value.  `--max-tokens` specifies the batchsize for each worker, so adding another GPU won't solve you're problem.
