### ISSUE TITLE
faster way to translate using api

### ISSUE THREAD

**Issue by tuhinjubcse** [pytorch/fairseq#1178]
en2de = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.en-de', checkpoint_file='model1.pt:model2.pt:model3.pt:model4.pt',
tokenizer='moses', bpe='fastbpe')
en2de.translate("Machine learning is great!") # 'Maschinelles Lernen ist großartig!'

is there a batch api to make faster / possible way to use GPU to translate
what do i need to pass to make this faster . ? Its very slow

**Comment by PC09** [comment]
Yes it takes 2 mins to translate a single sentence. Is there a way to run it  in server mode to make it fast?

**Comment by lematt1991** [comment]
At the moment there is no support for batched translation.  If you are interested in translating a file full of sentences in an offline manner, I would suggest using `fairseq-interactive`, which will allow you to specify the entire file and will take care of batching for you (you will have to tokenize and BPE encode yourself though).  If you want to make translation faster through the torch hub interface, you'll need to use a smaller model.  The WMT19 ensemble is quite large, using `transformer.wmt19.en-de.single_model` should be much faster.

**Comment by lematt1991** [comment]
@PC09, you mean it takes 2 mins to load the model from disk and then translate a single sentence or it takes 2 mins to translate a single sentence after the model has already been loaded?

For me, it takes ~1sec:

```
>>> start = timeit.default_timer(); en2de.translate("Machine learning is great!"); print(timeit.default_timer() - start)
'Maschinelles Lernen ist großartig!'
1.1003945879638195


```

**Comment by PC09** [comment]
Yes loading the model was taking a long time. Translation takes place in seconds.

**Comment by lematt1991** [comment]
Yes, so you should load the model once and keep it in memory and then perform all of your translations.
