### ISSUE TITLE
Inference guide on RACE task

### ISSUE THREAD

**Issue by Damcy** [pytorch/fairseq#1181]
After fine-tuning on RACE task, how can I use the model to do inference on test dataset?
Is there a sample code for the inference procedure?

**Comment by lematt1991** [comment]
You can find how to do batched prediction [here](https://github.com/pytorch/fairseq/tree/master/examples/roberta#batched-prediction)

**Comment by Damcy** [comment]
Looks like RACE input format is diff with other dataset, ensemble method and truncate method.

**Comment by myleott** [comment]
There are a few options:
* During training you can set `--valid-subset valid,test,test1` and it will print results for valid, test and test1 during training.
* Alternatively you can use `fairseq-validate` to evaluate an existing finetuned model on a new dataset:
```
fairseq-validate RACE-mmap2-bin \
  --valid-subset test \
  --task sentence_ranking \
  --path checkpoint_best.pt \
  --max-sentences 1
```
You can also pass the `--save-predictions` option to save the predictions to a file.
