### ISSUE TITLE
Using multiple Models trained on different data sets simultaneously

### ISSUE THREAD

**Issue by aastha19** [pytorch/fairseq#1183]
I have an extremely large dataset, training a single model on the same is becoming very problematic and cumbersome.
Is it possible if have multiple model files that have been trained on different data sets (language pair remains the same) to be used together to translate a sentence?

**Comment by lematt1991** [comment]
Yes, you can ensemble models using the `generate` and `interactive` script by separating the model paths with a colon: `fairseq-generate --path <mdl1>:<mdl2>:...:<mdl_k> ...`

**Comment by aastha19** [comment]
But for using fairseq-generate or interactive, the path to data-bin is also required to be passed. In case of ensembling does that also have to be colon-separated or what?
