### ISSUE TITLE
Roberta example uses incorrect encoder.json

### ISSUE THREAD

**Issue by bmtm** [pytorch/fairseq#1189]
the documentation for roberta uses the gpt-2 encoder.json and bpe codes. eg: https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.custom_classification.md

I couldn't correctly tokenize my input and spent some time trying to figure out why results were poor. I found that the pretrained roberta.large model uses a slightly different encoder.json:
```

import torch
from fairseq.models.roberta import RobertaModel

roberta = RobertaModel.from_pretrained("roberta.large")
tokenized = roberta.encode("Jack and jill")
print(tokenized)
# tensor([    0, 20907,     8,  1236,  1873,     2])

from fairseq.data.encoders.gpt2_bpe import get_encoder
bpe = get_encoder("encoder.json", "vocab.bpe")
tokenized = bpe.encode("Jack and jill")
print(tokenized)
# [14295, 290, 474, 359]

# roberta-large-vocab.json from pytorch transformers
bpe = get_encoder("roberta-large-vocab.json", "vocab.bpe")
tokenized = bpe.encode("Jack and jill")
print(tokenized)
# [20907, 8, 1236, 1873]
```

I'm not sure if this is a bug, or if I'm doing something incorrectly?

**Comment by lematt1991** [comment]
This:

```Python
roberta = RobertaModel.from_pretrained("roberta.large")
tokenized = roberta.encode("Jack and jill")
print(tokenized)
# tensor([    0, 20907,     8,  1236,  1873,     2])
```
Is the result of BPE encoding *and* encoding using the dictionary (i.e. replacing BPE tokens with their corresponding dictionary indices).  If you do:

```Python
from fairseq.data.encoders.gpt2_bpe import get_encoder
bpe = get_encoder("encoder.json", "vocab.bpe")
bpe_encoded = bpe.encode("Jack and jill")
tokenized = roberta.task.source_dictionary.encode_line(' '.join(map(str, bpe_encoded)))
print(tokenized)
```

You should get the same result

**Comment by bmtm** [comment]
ah I see, that worked for me. Thanks for clearing things up!
