### ISSUE TITLE
If you are getting CUDA out of memory errors, you should reduce the size of your batch by setting `--max-tokens` to a smaller value.  `--max-tokens` specifies the batchsize for each worker, so adding another GPU won't solve you're problem.

### ISSUE THREAD

**Issue by aastha19** [pytorch/fairseq#1191]
If you are getting CUDA out of memory errors, you should reduce the size of your batch by setting `--max-tokens` to a smaller value.  `--max-tokens` specifies the batchsize for each worker, so adding another GPU won't solve you're problem.

_Originally posted by @lematt1991 in https://github.com/pytorch/fairseq/issues/1176#issuecomment-535508942_

**Comment by aastha19** [comment]
@lematt1991 as suggested by you 
assert sample_len <= max_tokens, f"sentence at index {idx} exceeds max_tokens limit!"
AssertionError: sentence at index 25683144 exceeds max_tokens limit!

What to do in this case?

**Comment by huihuifan** [comment]
it means that sentence is too long. You need to decide how you want to handle this- you can cut the sentence, increase max tokens, or skip it

**Comment by aastha19** [comment]
I cannot increase the max tokens otherwise it gives CUDA oom error. how can I skip these?

**Comment by lematt1991** [comment]
As described in the [docs](https://fairseq.readthedocs.io/en/latest/command_line_tools.html#Dataset%20and%20data%20loading) you can add the flag `--skip-invalid-sizes`
