### ISSUE TITLE
ensemble models using the `generate` and `interactive` 

### ISSUE THREAD

**Issue by aastha19** [pytorch/fairseq#1193]
Yes, you can ensemble models using the `generate` and `interactive` script by separating the model paths with a colon: `fairseq-generate --path <mdl1>:<mdl2>:...:<mdl_k> ...`

_Originally posted by @lematt1991 in https://github.com/pytorch/fairseq/issues/1183#issuecomment-535506957_

Data is also to be given, how is that supposed to be passed?

**Comment by lematt1991** [comment]
For `fairseq-interactive` the data directory is only necessary to give access to the dictionaries, so as long as all the models use the same dictionary, you can provide the data directory for any of the models.  For `fairseq-generate`, you will need to provide a directory with the dictionaries as well as a pre-precessed dataset that you'd like to generate.

**Comment by Fengxiaoxx** [comment]
Excuse me , in fairseq-generate ,do you know what approach is used for model ensemble?Average?or vote? Is there any way that we can specify the ensemble methods ourselves? Thanks!
