### ISSUE TITLE
can I use transformer_wmt_en_de to train WMT 14 EN-FR

### ISSUE THREAD

**Issue by shawnkx** [pytorch/fairseq#1198]
I want to train a transformer base model on WMT 14 EN-FR. Could I use transformer_wmt_en_de as the model architecture? Thanks!

**Comment by skeshaw** [comment]
I am sure you can, it's just the architecture. You don't need to worry whether you are using a different dataset, provided the data itself is preprocessed correctly.
I am myself using the `transformer_iwslt_de_en` architecture currently to train a Basque-English translation model and it works just fine, as it should.

**Comment by huihuifan** [comment]
thanks for the answer, @skeshaw is correct
