### ISSUE TITLE
RL for NMT during inference

### ISSUE THREAD

**Issue by ladler0320** [pytorch/fairseq#1203]
Hello,
Thanks a lot for the amazing toolkit!

Are there any guides on how to implement reinforcement learning for transformer-based NMT model?
It would be great if the model could be retrained **during inference**? (e.g. when user modifies/replaces suggested translation)

**Comment by myleott** [comment]
We do have some work in this area, for example our "Classical Structured Prediction Losses for Sequence to Sequence Learning" paper but the code for that is based on a very old branch of fairseq. We've attempted to update it to work with master, but have not been able to fully test it yet: https://github.com/pytorch/fairseq/pull/1083
