### ISSUE TITLE
Correct way to use `--replace-unk` and `--raw-text`?

### ISSUE THREAD

**Issue by arendu** [pytorch/fairseq#1204]
I have preprocessed my data (I have *.idx, *.bin files) but I'm not clear how to use these flags. Specifically, what is the argument for `--raw-text` when I use `--replace-unk`? 

For more context, I am using a pretrained model from [here](https://github.com/pytorch/fairseq/blob/master/examples/translation/README.md) which generates `<unk>` in the translated output. I want to generate sequences without `<unk>`.

**Comment by myleott** [comment]
Please check the updated documentation and reopen a new issue if this is still a problem, thanks!
