### ISSUE TITLE
windows roberta finetuning issue for the imdb example

### ISSUE THREAD

**Issue by jili5ms** [pytorch/fairseq#1205]
I was trying to follow "Finetuning RoBERTa on a custom classification task": https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.custom_classification.md

I had to change the following line in train.py otherwise it shows "AttributeError: module 'torch.distributed' has no attribute 'is_initialized'":
  main(args, init_distributed=**False**)

it seems torch distributed training doesn't support windows. Forcing init_distributed to False will lead to the following error: 
NameError: name '_get_default_group' is not defined

So my question is: is it possible to avoid using distributed training for the roberta imdb example?

**Comment by ngoyal2707** [comment]
What command are you running, the command mentioned in [section 5](https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.custom_classification.md#5-run-training) is running on 1 gpu only and it should by default not use [this](https://github.com/pytorch/fairseq/blob/master/train.py#L327) codepath which has `init_distributed=False`

**Comment by jili5ms** [comment]
Thanks for the quick response! After setting it to only one GPU, it runs with some warning about GPU OOM: 

```
| WARNING: ran out of memory with exception: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 11.00 GiB total capacity; 8.77 GiB already allocated; 10.32 MiB free; 38.80 MiB cached);
 Skipping batch
| WARNING: OOM in all workers, skipping update 
```
Looks like at the beginning of the training, something got loaded into GPU mem and takes most of it, leaving insufficient mem for training.
