### ISSUE TITLE
BLEU score from generate.py is cased BLEU or not?

### ISSUE THREAD

**Issue by shawnkx** [pytorch/fairseq#1206]
Hi,

Could anyone tell whether the BLEU score coming from the generate.py is cased BLEU or not?

And how could I output the translated sentence into a file?

Thanks!

**Comment by SunbowLiu** [comment]
1. cased

2. grep ^H output | cut -f3- > hyp

**Comment by alvations** [comment]
You should decode and output the translation into a file and use https://github.com/mjpost/sacreBLEU

**Comment by shawnkx** [comment]
Thanks!
