### ISSUE TITLE
fairseq-preprocess: ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by moyid** [pytorch/fairseq#1208]
I'm running fairseq-preprocess and ran into this error. The preprocessing was successful for some of my datasets, as you can see. (there is a mono and a para set of data, it failed on the para part). Also, I noticed that the number of workers decreased from 20 to 1.

Namespace(alignfile=None, cpu=False, criterion='cross_entropy', dataset_impl='cached', destdir='data//processed/', fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined
_dictionary=False, log_format=None, log_interval=1000, lr_scheduler='fixed', memory_efficient_fp16=False, min_loss_scale=0.0001, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=True, optimi
zer='nag', padding_factor=8, seed=1, source_lang='en', srcdict='data//mono//dict.en.txt', target_lang=None, task='cross_lingual_lm', tbmf_wrapper=False, tensorboard_logdir='', testpref=None, tgtdict=None,
 threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, trainpref='data//mono//train', user_dir=None, validpref='data//mono//valid', workers=20)
| [en] Dictionary: 40000 types
| [en] data//mono//train.en: 9565218 sents, 306125895 tokens, 2.77% replaced by <unk>
| [en] Dictionary: 40000 types
| [en] data//mono//valid.en: 434782 sents, 13904564 tokens, 2.77% replaced by <unk>
| Wrote preprocessed data to data//processed/
Namespace(alignfile=None, cpu=False, criterion='cross_entropy', dataset_impl='cached', destdir='data//processed/', fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined
_dictionary=False, log_format=None, log_interval=1000, lr_scheduler='fixed', memory_efficient_fp16=False, min_loss_scale=0.0001, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=True, optimizer='nag', padding_factor=8, seed=1, source_lang='zh', srcdict='data//mono//dict.zh.txt', target_lang=None, task='cross_lingual_lm', tbmf_wrapper=False, tensorboard_logdir='', testpref=None, tgtdict=None, threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, trainpref='data//mono//train', user_dir=None, validpref='data//mono//valid', workers=20)
| [zh] Dictionary: 40000 types
| [zh] data//mono//train.zh: 5832926 sents, 349297160 tokens, 0.523% replaced by <unk>
| [zh] Dictionary: 40000 types
| [zh] data//mono//valid.zh: 265133 sents, 15864130 tokens, 0.521% replaced by <unk>
| Wrote preprocessed data to data//processed/
Namespace(alignfile=None, cpu=False, criterion='cross_entropy', dataset_impl='cached', destdir='data//processed/', fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_format=None, log_interval=1000, lr_scheduler='fixed', memory_efficient_fp16=False, min_loss_scale=0.0001, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=False, optimizer='nag', padding_factor=8, seed=1, source_lang='en', srcdict='data//para//dict.en.txt', target_lang='zh', task='xmasked_seq2seq', tbmf_wrapper=False, tensorboard_logdir='', testpref=None, tgtdict='data//para//dict.zh.txt', threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, trainpref='data//para//train', user_dir='mass', validpref='data//para//valid', workers=1)
| [en] Dictionary: 40000 types
| [en] data//para//train.en: 21968347 sents, 575754902 tokens, 1.53% replaced by <unk>
| [en] Dictionary: 40000 types
Traceback (most recent call last):
  File "/opt/anaconda3/bin/fairseq-preprocess", line 10, in <module>
    sys.exit(cli_main())
  File "/opt/anaconda3/lib/python3.7/site-packages/fairseq_cli/preprocess.py", line 267, in cli_main
    main(args)
  File "/opt/anaconda3/lib/python3.7/site-packages/fairseq_cli/preprocess.py", line 185, in main
    make_all(args.source_lang, src_dict)
  File "/opt/anaconda3/lib/python3.7/site-packages/fairseq_cli/preprocess.py", line 179, in make_all
    make_dataset(vocab, validpref, outprefix, lang, num_workers=args.workers)
  File "/opt/anaconda3/lib/python3.7/site-packages/fairseq_cli/preprocess.py", line 171, in make_dataset
    make_binary_dataset(vocab, input_prefix, output_prefix, lang, num_workers)
  File "/opt/anaconda3/lib/python3.7/site-packages/fairseq_cli/preprocess.py", line 157, in make_binary_dataset
    100 * sum(replaced.values()) / n_seq_tok[1],
ZeroDivisionError: division by zero

**Comment by jiachangliu** [comment]
Hello @moyid , may I know how you solved the problem?

**Comment by duchuuabc** [comment]
Hello @moyid , I have the same problem as you, could you please share how you solved the problem ?

**Comment by CHELSEA234** [comment]
@moyid @jiachangliu @duchuuabc , Hello, could you tell how you guys solved this issue? Thank you.

**Comment by jiachangliu** [comment]
@CHELSEA234 This was a long time ago. I don't remember the exact problem I encountered clearly. You might need to wait for others to respond. Alternatively, you could post your own code and let others examine what goes wrong.

**Comment by duchuuabc** [comment]
Your dataset have some problems, just check it again. Good luck.

**Comment by kaivu1999** [comment]
Yes, I had the same error. 
A file in the dataset was empty.

Just by looking at the data, one can solve many such issues that occur.
