### ISSUE TITLE
Error when try to run distributed training

### ISSUE THREAD

**Issue by jalajthanakicactus** [pytorch/fairseq#1209]
Hi,

I am trying to run distributed training on 2 nodes with 8 GPUs each (K80) in total 16 GPUs. I'm using following NCCL as backend and along with that I'm using following command to execute the distributed training.
I have set two NCCL environment flag
```
$ export NCCL_SOCKET_IFNAME=ens3
$ export NCCL_DEBUG=INFO
```

On 1st node I'm executing the fairseq training command with following distributed training flags:

`PYTHONPATH=$FAIRSEQPY:$PYTHONPATH CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python3.6 $FAIRSEQPY/train.py <ALL other training specific flags>... --distributed-world-size 16 --distributed-rank 0 --distributed-backend "nccl" --distributed-init-method 'tcp://54.146.137.72:9001' --distributed-port 9001`

on 2nd node I'm executing the fairseq training command with following distributed training flags:

`PYTHONPATH=$FAIRSEQPY:$PYTHONPATH CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python3.6 $FAIRSEQPY/train.py <All other training specific flags> --distributed-world-size 16 --distributed-rank 8 --distributed-backend "nccl" --distributed-init-method 'tcp://54.146.137.72:9001' --distributed-port 9001 `

on second node I got the following error log.

`Traceback (most recent call last):
  File "/home/<user>/mlconvgec2018_2019_06_25_1/mlconvgec2018/software//fairseq-py/train.py", line 347, in <module>
    distributed_main(args)
  File "/home/<user>/mlconvgec20/18_2019_06_25_1/mlconvgec2018/software/fairseq-py/distributed_train.py", line 37, in main
    args.distributed_rank = distributed_utils.distributed_init(args)
  File "/home/<user>/mlconvgec2018_2019_06_25_1/mlconvgec2018/software/fairseq-py/fairseq/distributed_utils.py", line 28, in distributed_init
    world_size=args.distributed_world_size, rank=args.distributed_rank)
  File "/home/<user>/mlconvgec2018_2019_06_25_1/venv/lib/python3.6/site-packages/torch/distributed/__init__.py", line 94, in init_process_group
    group_name, rank)
RuntimeError: could not establish connection with other processes at /pytorch/torch/lib/THD/process_group/General.cpp:17`

NCCL version: 2.4.8
Torch Version: 1.1.0
CUDA version: 9.2

Is there something that I'm missing? 
Any help is much appreciated.

Thanks,

**Comment by ngoyal2707** [comment]
`pytorch / fairseq` related arguments look correct to me, specifically `--distributed-world-size`, `--distributed-rank` , `--distributed-init-method` and `--distributed-backend`. You should not need `--distributed-port` but that's okay to have. 

Are you confident about `ens3` network interface? maybe try out a stand along `pytorch` small model with distributed training on these 2 nodes cause I feel you probably have some error with network interface and it's unrelated to `fairseq`.

**Comment by jalajthanaki** [comment]
Hi @ngoyal2707 ,

Thanks for replying back. I have **ens3** by using `ifconfig` command. I was actually referring this documentation. I'm using AWS cloud platform. Right now I'm not using shared file system. I have copy of code and data on 2 nodes each node is having 8 GPUs. If this information help you to give me any further suggestion

**Comment by ngoyal2707** [comment]
Hey @jalajthanaki 

I would suggest these things is order:

1) As Pieter mentioned on PT forum, upgrade to PT 1.2.0, also in fairseq, we use CUDA10.0 so upgrade that also if possible.

2) Make sure the IP ` 54.146.137.72` is correct and machines can communicate to each other.

3) Write a standalone Pytorch DDP training code (examples here: https://pytorch.org/tutorials/intermediate/ddp_tutorial.html),  I don't think your issue is in `fairseq`.

**Comment by ngoyal2707** [comment]
Will close this issue due to inactivity

**Comment by jalajthanaki** [comment]
@ngoyal2707  thanks for the suggestion and I will try this and update my findings here
