### ISSUE TITLE
train phase we always skip invalid input by default.

### ISSUE THREAD

**Issue by aastha19** [pytorch/fairseq#1214]
`--skip-invalid-size-inputs-valid-test` only applies to `valid` and `test` phase as the name suggests.
For train phase we always skip invalid input by default.

_Originally posted by @ngoyal2707 in https://github.com/pytorch/fairseq/issues/1202#issuecomment-537118232_

As mentioned earlier it is not skipping the sentence by default. is there something that  can be done to avoid the assertion error.

**Comment by ngoyal2707** [comment]
As per your screenshot in #1202  you don't have any `AssertionError`, you are getting GPU OOM,
and you need to reduce `--max-sentences` to reduce batch size to fit in your GPU memory

**Comment by aastha19** [comment]
That comment is actually linked to another issue

https://github.com/pytorch/fairseq/issues/1191#issuecomment-535940389

This is the error i get when i reduce the token size to too low and if i increase it, it gives GPU OOM
