### ISSUE TITLE
use gpu for translate api

### ISSUE THREAD

**Issue by tuhinjubcse** [pytorch/fairseq#1217]
en2de = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.en-de', checkpoint_file='model1.pt:model2.pt:model3.pt:model4.pt',
tokenizer='moses', bpe='fastbpe')
en2de.translate("Machine learning is great!") # 'Maschinelles Lernen ist großartig!'

can i use gpu to accelerate this ? I already asked but dint get a response

**Comment by gvskalyan** [comment]
refer this please https://github.com/pytorch/fairseq/issues/1112
