### ISSUE TITLE
Locations of subword-nmt scripts change

### ISSUE THREAD

**Issue by kevin1kevin1k** [pytorch/fairseq#1218]
The package [subword-nmt](https://github.com/rsennrich/subword-nmt) is used/mentioned in the following:

- `prepare-iwslt14.sh`, `prepare-wmt14en2de.sh`, and `prepare-wmt14en2fr.sh` under [examples/translation/](https://github.com/pytorch/fairseq/tree/master/examples/translation)
- [fairseq/data/encoders/subword_nmt_bpe.py](https://github.com/pytorch/fairseq/blob/master/fairseq/data/encoders/subword_nmt_bpe.py)
- [docs/getting_started.rst](https://github.com/pytorch/fairseq/blob/master/docs/getting_started.rst)
- [examples/translation_moe/README.md](https://github.com/pytorch/fairseq/blob/master/examples/translation_moe/README.md) (actually the the one in this file can be removed)

Some scripts under `subword-nmt` have changed locations (though symbolic links are temporarily present in the original location), so the above files should also change accordingly.
(Currently only some DeprecationWarning show up, but errors will probably occur in the future.)

**Comment by gvskalyan** [comment]
Please Submit a Pull request pointing to the new files in subword-nmt.
@myleott why Sentencepiece is not being used for normal translation. Is it to help replicate the results in paper. Maybe add an extra arg to prepare scripts via sentencepiece?

**Comment by kevin1kevin1k** [comment]
@gvskalyan I've already created a PR #1219 earlier. Thanks!
