### ISSUE TITLE
 'TransformerModel' object has no attribute 'forward_decoder'

### ISSUE THREAD

**Issue by ebagdasa** [pytorch/fairseq#1222]
I follow the following tutorias: https://pytorch.org/hub/pytorch_fairseq_translation/#english-to-german-translation, https://github.com/pytorch/fairseq/tree/master/examples/translation/README.md 

and get error while trying to call translate on the model: `en2de.translate('Hello world!')`

 'TransformerModel' object has no attribute 'forward_decoder'

P.S. for README.md example, instead of `bpe='subword_nmt'` there should be `bpe='fastbpe'`.

**Comment by SpaceD0ge** [comment]
There is no forward_encoder in the TransformerLanguageModel class, just the usual forward function. So a temporary fix would look something like that:
```
from fairseq.models.transformer_lm import TransformerLanguageModel

def forward_encoder(self):
  return None

setattr(TransformerLanguageModel, 'forward_encoder', forward_encoder)
setattr(TransformerLanguageModel, 'forward_decoder', TransformerLanguageModel.forward)
```

**Comment by ebagdasa** [comment]
perfect, thanks.
