### ISSUE TITLE
generating sequence using language model

### ISSUE THREAD

**Issue by tagucci** [pytorch/fairseq#1223]
using `interactive.py` by [pre-trained language model on fairseq](https://github.com/pytorch/fairseq/tree/master/examples/language_model#pre-trained-models), I got generated sequence as below.
```
S-0     In this test ,
H-0     -2.1058778762817383     In this test , the researchers used a fluorescence microscope to measure the amount of terbium ions in the blood of the volunteers .
P-0     -8.1061 -12.5155 -25.0781 -0.0000 -0.0008 -0.1352 -0.0717 -0.0004 -1.5938 -0.5852 -0.0000 -0.0732 -0.0000 -0.6246 0.0000 -2.7639 -1.0158 -0.0004 -0.0004 -0.0111 -0.0049 -0.0009 -0.0633 -0.0015 0.0000
```

However, I want to make LM to generate sequences from given some tokens (ex. `In this test ,` in above) in a large-scale. `interactive.py` is so slow because LM model processes per sample.

Is there way to generate sequences from LM model by using mini-batch?
In this case, I assume input is a few tokens in each lines. 
```
In this test, 
Today I went
She was
```

I also tried `generate.py` and transformer language-model same as above, but it doesn't seem to work.
```
$ python generate.py ./adaptive_lm_gbw_huge/data-bin/ --path ./adaptive_lm_gbw_huge/model.pt --sampling --sampling-topk 10 --temperature 0.2 --beam 1 --no-repeat-ngram-size 3  --task language_modeling

| loaded 306688 examples from: ./adaptive_lm_gbw_huge/data-bin/test
| WARNING: 7907 samples have invalid sizes and will be skipped, max_positions=256, first few sample ids=[7906, 6056, 3835, 6495, 3129, 1900, 2065, 2821, 1232, 5719]
```

**Comment by alexeib** [comment]
you can use --buffer-size to read several sentences at a time in interactive.py (which will be evaluated in a batch) and you can also use --input to specify a file to use as input
