### ISSUE TITLE
Transformer will not work without positional embeddings

### ISSUE THREAD

**Issue by villmow** [pytorch/fairseq#1232]
See this line:

https://github.com/pytorch/fairseq/blob/33646ac9b7b720444416e2c18d1120d03b37e156/fairseq/models/transformer.py#L308

It will crash as `x` is undefined when positional_embeddings is None. Change it to:
```python
x = F.dropout(embed if self.embed_positions is None else x, p=self.dropout, training=self.
```

**Comment by myleott** [comment]
This has been fixed
