### ISSUE TITLE
Why beam=1 in the evaluation of translation_moe

### ISSUE THREAD

**Issue by bangann** [pytorch/fairseq#1235]
Hi,

I'm trying to reduplicate transformer_moe and I have a question on the evaluation. Why you use beam=1? If I'm right this means you only generate one candidate. But in this case, how could you calculate pairwise BLEU? Please correct me if I'm wrong. Thx!

> BPEROOT=examples/translation/subword-nmt/
BPE_CODE=examples/translation/wmt17_en_de/code
for EXPERT in $(seq 0 2); do \
    cat wmt14-en-de.extra_refs.tok \
    | grep ^S | cut -f 2 \
    | fairseq-interactive data-bin/wmt17_en_de \
        --path checkpoints/checkpoint_best.pt \
        --beam 1 \
        --bpe subword_nmt --bpe-codes $BPE_CODE \
        --buffer-size 500 --max-tokens 6000 \
        --task translation_moe \
        --method hMoElp --mean-pool-gating-network \
        --num-experts 3 \
        --gen-expert $EXPERT ; \
done > wmt14-en-de.extra_refs.tok.gen.3experts

**Comment by Andy5250** [comment]
I want to generate multiple hypotheses. Does anyone know how to do that?

**Comment by myleott** [comment]
We used `--beam 1` for K experts to be fairer to beam search. You can also use beam search, e.g., `--beam K --nbest K`, which will output all K-best hypotheses.
