### ISSUE TITLE
Can I customize the dictionary of a pre-trained transformer neural machine translation model?

### ISSUE THREAD

**Issue by moyid** [pytorch/fairseq#1241]
Faiseq has many pre-trained machine translations models available with SOTA performance, but it seems like they all need to be run with the dictionary they are trained with. The dictionaries sometimes can have less coverage for my data set (even BPE based ones), and sometimes miss important words as unknowns. What are the best ways to customize the pretrained models to a dictionary learned from my own data set? For example, some way to transfer learn, like unfreezing the encoder layers and retraining?

**Comment by myleott** [comment]
You could try freezing the encoder/decoder weights and just learning new embeddings. I know there's some other work in learning adapter layers, e.g., https://arxiv.org/abs/1909.08478

**Comment by NuwangaHerath** [comment]
> You could try freezing the encoder/decoder weights and just learning new embeddings. I know there's some other work in learning adapter layers, e.g., https://arxiv.org/abs/1909.08478, but I haven't tried this myself.

If we freeze the encoder and  decoder, is it create a new encoder layers and decoder layers it self while it also have frozen layers?
