### ISSUE TITLE
What is currently the best way to add a custom glossary to a neural machine translator that uses the transformer architecture?

### ISSUE THREAD

**Issue by moyid** [pytorch/fairseq#1242]
It's common to add a custom glossary or dictionary to a machine translator to ensure that terminology from a specific domain is correctly translated. For example, the term server should be translated differently when the document is about data centers, vs when the document is about restaurants.

With a transformer model, this is not very obvious to do, since words are not aligned 1:1. I've seen a couple of papers on this topic, but I'm not sure which would be the best one to use. One that I find particularly interesting is ["On The Alignment Problem In Multi-Head Attention-Based Neural Machine Translation"](https://www.aclweb.org/anthology/W18-6318.pdf). 

What are the best practices for this problem? Are there any solutions that are already implemented in pytorch or fairseq?

--To be clear this is different from my previous question about the BPE dictionaries. I am talking here about user-input dictionaries for domain specific vocabulary. 

Thank you!

Thank you!

**Comment by ladler0320** [comment]
Hi,
Thanks a lot for the amazing toolkit!

Is there any update about this issue? It would be really nice if there was a possibility to add a custom alignment dictionary for the translation task. 

Best regards,
Vitaliy

**Comment by blessu** [comment]
I'm also curious about this, but not sure if there is some update or suggestion @moyid @ladler0320 
Thanks a lot!

**Comment by kurtabela** [comment]
Are there any updates on this perhaps?
