### ISSUE TITLE
RoBERTa: XNLI results

### ISSUE THREAD

**Issue by sbmaruf** [pytorch/fairseq#1243]
Very impressive result on XNLI. Even it surpasses XLM+TLM models.
Is it possible to release the "TRANSLATE TEST" dataset of XNLI mentioned [here]("https://github.com/pytorch/fairseq/tree/master/examples/roberta#results").
Also for validation, did you used only the English validation dataset or language specific "TRANSLATE VALIDATION" dataset was also added with the English validation dataset?

**Comment by ngoyal2707** [comment]
The "TRANSLATE TEST" version of dataset was released with XNLI, you should be able to download it from https://github.com/facebookresearch/XNLI
Just English validation dataset was used for selecting hyperparam and best checkpoint (which is same as MNLI) and just evaluating on language specific "TRANSLATE-TEST" dataset
