### ISSUE TITLE
runtime error, speech recognition can't use multi GPU to train 

### ISSUE THREAD

**Issue by LeeYongHyeok** [pytorch/fairseq#1253]
Hello,

When I train speech recognition task on multi GPU, basically using Librispeech DB

I can't train over the 1 epoch, 834 updates.

The training looks like feezing.

Three GPU run 100% but the power is low watt about 45W/250W

I set the `--num-works` to "0".

How can i fix it?

**Comment by huihuifan** [comment]
@okhonko

**Comment by myleott** [comment]
Please reopen with more details about what commands you ran, environment, etc.
