### ISSUE TITLE
question about NCCL

### ISSUE THREAD

**Issue by nikos-rvnt** [pytorch/fairseq#1256]
Hello to all,

I was reading the requirements needed for installing fairseq and was wondering whether I really need to have Nvidia's NCCL installed or not in order to train fairseq models from scratch. My problem is that NCCL is not supported for Windows platforms.

**Comment by ngoyal2707** [comment]
@nikos-rvnt You only need NCCL if you are doing multi-gpu or multi-node training. You should be able to do single gpu training without NCCL

**Comment by nikos-rvnt** [comment]
Thank you for your answer. I will try it as you say.
