### ISSUE TITLE
Implement Reducing Transformer Depth on Demand With Structred Dropout 

### ISSUE THREAD

**Issue by gvskalyan** [pytorch/fairseq#1257]
Please consider implementing https://arxiv.org/pdf/1909.11556.pdf with a README.md in the examples to reproduce the results. @huihuifan

**Comment by huihuifan** [comment]
We are actively working on this and will release code and commands for reproduction very soon, then open source models soon afterwards. Thanks for your interest!

**Comment by gvskalyan** [comment]
https://github.com/pytorch/fairseq/commit/dabbef467692ef4ffb7de8a01235876bd7320a93 solves this

**Comment by gvskalyan** [comment]
Acoording to [this](https://github.com/pytorch/fairseq/blame/master/examples/layerdrop/README.md#L44) ran  --model-overrides "{'decoder_layers_to_keep':'0,2,4,6'}" for a transformer-base model while evaluating, but ran into below error.
RuntimeError: Error(s) in loading state_dict for TransformerModel:
        Missing key(s) in state_dict:

Also tried resuming training from layer-dropped out model, still the same error occurs @huihuifan .
Thanks.

**Comment by huihuifan** [comment]
hi @gvskalyan, does the error message say which keys in the state dict are missing?

**Comment by gvskalyan** [comment]
Sorry, it is evident that I have trained the transformer base, but am overriding only decoder layers but not encoder layers. Also it works only for same layers on both sides. Thanks.

**Comment by huihuifan** [comment]
thanks for raising this error, I will look into it on current master branch and get back to you.
