### ISSUE TITLE
Does not "next_epoch_itr(shuffle=True)" shuffle within each batch nor within the entire dataset?

### ISSUE THREAD

**Issue by mjeensung** [pytorch/fairseq#1258]
https://github.com/pytorch/fairseq/blob/b5f41f828b0ec9b67fa60aceb0778073d1b368b2/fairseq/data/iterators.py#L177

The comment above seems "next_epoch_itr(shuffle=True)" shuffles only between batches.
I just want to make sure that it doesn't shuffle data within each batch nor within the entire dataset.

Thank you in advance.

**Comment by ngoyal2707** [comment]
@mjeensung Yes that only shuffles batches. 
In `fairseq`, we shuffle dataset and create batches only once at initialization. And then at the start of each epoch the batches are shuffled. 
This was done for performance considerations.

**Comment by ChristineBasta** [comment]
@mjeensung what if I need to create batches each epoch, and set shuffle to False for the dataset and the iterator, how can I reach this?? I want at the beginning of each epoch, a new cal to ordered_indices of my dataset is called. However, I do not know how to achieve this.
