### ISSUE TITLE
training GPT2 model for language modelling

### ISSUE THREAD

**Issue by PC09** [pytorch/fairseq#1264]
Hi, in the examples I could find neural language model codes for pretraining transformers and BERT on our own data set. Is it available for GPT2 or will it be out soon?

**Comment by PC09** [comment]
Still waiting ,any update on this ?

**Comment by myleott** [comment]
Sure, please follow the instructions for language modeling: https://github.com/pytorch/fairseq/tree/master/examples/language_model

We define the GPT/GPT-2 model architectures here: https://github.com/pytorch/fairseq/blob/master/fairseq/models/transformer_lm.py#L246-L291
