### ISSUE TITLE
Improve memory efficiency of preprocess.py

### ISSUE THREAD

**Issue by PhilippeMarcotte** [pytorch/fairseq#1267]
I'm trying to preprocess a big parallelized corpus (200M sentences or 21 GB per file). For some reason, it is taking up all the available ram (64 GB). 

I tried preprocessing using mmap and lazy dataset implementation. There's probably something I'm not understanding in the preprocessing for it to take so much memory.

I'm also using 28 workers and joined dictionary. The other arguments have their default value.

**Comment by PhilippeMarcotte** [comment]
I've looked a bit at the binarize code. From what I understand, there is at most n_workers-1 line in memory at a time. However, for some reason, it actually accumulates in the ram instead of freeing it as it binarize the whole corpus.

I have a feeling that it is related to python not freeing the memory. If that is the case, the problem could probably be fixed by distributing smaller task to each process and using the maxtasksperchild arguments from [Pool](https://docs.python.org/3.7/library/multiprocessing.html#multiprocessing.pool.Pool).

**Comment by PhilippeMarcotte** [comment]
As a test, I did the following modification in preprocess.py:
```Diff
@@ -1,9 +1,10 @@
-offsets = Binarizer.find_offsets(input_file, num_workers)
+num_tasks = num_workers * 7
+offsets = Binarizer.find_offsets(input_file, num_tasks)
 pool = None
 if num_workers > 1:
-    pool = Pool(processes=num_workers - 1)
-    for worker_id in range(1, num_workers):
-        prefix = "{}{}".format(output_prefix, worker_id)
+    pool = Pool(processes=num_workers - 1, maxtasksperchild=1)
+    for task_id in range(1, num_tasks):
+        prefix = "{}{}".format(output_prefix, task_id)
         pool.apply_async(
             binarize,
             (
@@ -12,8 +13,8 @@
                 vocab,
                 prefix,
                 lang,
-                offsets[worker_id],
-                offsets[worker_id + 1]
+                offsets[task_id],
+                offsets[task_id + 1]
             ),
             callback=merge_result
         )
```

This seems to fix the ram issue. It still ramps up, but then goes down when the workers have reached their maximum number of task and get destroyed.

**Comment by LNdoremi** [comment]
Hello PhilippeMarcotte! Thanks for your great work! I have met the same problem with you which is the preprocesing process will take up ram increasingly. Your scripts help me to process large datesets successfully.
