### ISSUE TITLE
preprocess with fairseq

### ISSUE THREAD

**Issue by juliahane** [pytorch/fairseq#1269]
Hi
I have a hard time understanding the code, and documentations nor the code are not clear for me, I really appreciate your help on this question:
given this command, what is  "task" parameter in fairseq, what is --only_resouce option?
and where can I read a clear explanation of these in the codes.
thanks
 
fairseq-preprocess \
    --user-dir mass --only-source --task masked_s2s \
    --trainpref mono/train.txt --validpref mono/valid.txt --testpref mono/test.txt \
    --destdir processed --srcdict dict.txt --workers 60

**Comment by myleott** [comment]
You may want to check out the documentation for high-level usage information: https://fairseq.readthedocs.io/en/latest/

For more details you'll need to look into the code or other READMEs in the examples/ directory. Note that `--only-source` is required for language modeling: https://github.com/pytorch/fairseq/tree/master/examples/language_model
