### ISSUE TITLE
Registry the args in Transformer

### ISSUE THREAD

**Issue by lyzKF** [pytorch/fairseq#1273]
Hi, i am confused about the implement of Transformer on line 140.
```
# make sure all arguments are present in older models
base_architecture(args)
```
why? 
if i want to registry the "transformer_vaswani_wmt_en_de_big",  can i replace the ```base_architecture(args)``` with```transformer_vaswani_wmt_en_de_big(args)```?

@myleott 
looking forward to your reply，thank you !

**Comment by myleott** [comment]
We add this so that any arguments not specified in a given architecture will automatically inherit the default values. You can definitely replace it with `transformer_vaswani_wmt_en_de_big` when defining a new architecture if you'd like.
