### ISSUE TITLE
Using ResamplingDataset causes trouble with filtering to large samples

### ISSUE THREAD

**Issue by villmow** [pytorch/fairseq#1274]
Hi, thanks for the awesome library! 

**Problem**: I use the ResamplingDataset to downsample frequent examples in a custom task. After every epoch a subset of the full training data is selected for the next epoch. This selection affects the filtering by size of the samples which is implemented in `get_batch_iterator`. However after the filtered indices are calculated, `set_epoch` is called again (with an incremented epoch count)! This causes a resampling, which again invalidates the filtered indices! 

**What happens**:
1. I reset the `dataset_to_epoch_iter` to get a new iterator after each epoch.
2. `FairseqTask.get_batch_iterator` is called
3. Inside  `get_batch_iterator` the datasets `ResamplingDataset.set_epoch` is called, in which the resampling is implemented:
https://github.com/pytorch/fairseq/blob/b8d024e9b8c20058dd7282f1418ebef00bfb8974/fairseq/tasks/fairseq_task.py#L135-L136
4. The samples are filtered by size
https://github.com/pytorch/fairseq/blob/b8d024e9b8c20058dd7282f1418ebef00bfb8974/fairseq/tasks/fairseq_task.py#L138-L152
5. An EpochIterator is instantiated for which `next_epoch_itr` is called
https://github.com/pytorch/fairseq/blob/b8d024e9b8c20058dd7282f1418ebef00bfb8974/fairseq/tasks/fairseq_task.py#L155-L164
6. The trainer calls `next_epoch_itr` and inside of it the epoch counter is incremented and then `ResamplingDataset.set_epoch` is called again, which resamples the data (and thus the filtering indices are wrong).
https://github.com/pytorch/fairseq/blob/b8d024e9b8c20058dd7282f1418ebef00bfb8974/fairseq/data/iterators.py#L187-L191
7. This iterator is used and samples with wrong sizes are filtered.

I hope I could describe the issue understandable. As a quick fix for me I uncommented the `set_epoch` call in EpochBatchIterator, which I guess is not the right approach.

What is the correct way to handle the change of sizes after each epoch?

**Comment by cbaziotis** [comment]
I am training a model with the `multilingual_denoising` task, which uses the ResamplingDataset. Training crashes deterministically form me after the first epoch, which I think is because of this issue.

What happens is the after the first epoch, I get OOM exceptions and I have found that the reason is the `ntokens` in batches is random and usually larger than `args.max_tokens`.

**Comment by myleott** [comment]
I think this should have been fixed by aa79bb9c37b27e3f84e7a4e182175d3b50a79041

**Comment by myleott** [comment]
Please reopen if this is still an issue.
