### ISSUE TITLE
Support for character-based models

### ISSUE THREAD

**Issue by ethen8181** [pytorch/fairseq#1276]
Hi team,

More of a question rather than an issue. I saw the discussion from #438 that there was going to be support for custom tokenizer/dictionary, so wanted to check if this is a thing already, and how to go about achieving this? Is there a flag that we can specify from `fairseq-preprocess` perhaps? Thanks.

**Comment by myleott** [comment]
We still mostly expect tokenization to be handled outside of fairseq, but character tokenization should be fine. Just split your input into characters (with spaces between them) and use the standard fairseq-preprocess process.
