### ISSUE TITLE
Is it possible to load pretrained RoBERTa weight for the encoder in a seq2seq transformer model?

### ISSUE THREAD

**Issue by MichaelZhouwang** [pytorch/fairseq#1277]
Hi, I am recently trying to explore the effectiveness of using BERT pretrained weight to initialize the encoder of a transformer seq2seq model. I am wondering is there is any way to implement this in the fairseq library? Thanks for your help!

**Comment by f-lng** [comment]
I have the same question, according to https://arxiv.org/pdf/1907.12461.pdf this should work pretty well. 

According to https://github.com/pytorch/fairseq/blob/45e48ffbcd401a79e1ff4911bd8f81140e0c7f15/fairseq/models/roberta.py#L288 Roberta is a FairseqDecoder, which might be a problem. 

Any official solution for this?

**Comment by myleott** [comment]
Sure, you can modify your model to do this. Take a look at the stories generation model to see how they did this: https://github.com/pytorch/fairseq/blob/master/fairseq/models/fconv_self_att.py#L109-L127

**Comment by allanj** [comment]
@myleott If I want to initialize the encoder parameter with Roberta-base parameter. I'm actually using the [transformer](https://github.com/pytorch/fairseq/blob/master/fairseq/models/transformer.py) model, are the (hyper) parameters (e.g., size, number of layers) equivalent?
