### ISSUE TITLE
Finetuning on GLUE tasks

### ISSUE THREAD

**Issue by Arjunsankarlal** [pytorch/fairseq#1278]
Can you please direct me to the instructions where I can find the steps to finetune roberta model for downstream tasks ? I could only find preprocessing files. And commands [here](https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.glue.md) refers to which `train.py` file ?

**Comment by ngoyal2707** [comment]
https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.glue.md have some instructions

**Comment by ngoyal2707** [comment]
and you can find `train.py` in this github repo.

**Comment by JerrikEph** [comment]
where is the `train.py` file?
