### ISSUE TITLE
Does wav2vec work with different sampling rates?

### ISSUE THREAD

**Issue by rewreu** [pytorch/fairseq#1280]
Does wav2vec work with another sampling rate other than 16Khz? 
If so, does that mean the receptive field will change? In the paper, it says `The total receptive field of the context network is about 210 ms.` using 16Khz. If I use 32Khz, will the receptive field of the context network change to 105 ms?

**Comment by snard6** [comment]
@rewreu Yes. But the fairseq code will resample it to 16k for you.

**Comment by alexeib** [comment]
you can specify a different sample rate with --sample-rate argument. audio will be resampled (via simple interpolation, dont expect great results) for you to this sample rate. you can certainly use 32k if you want but then you might want to adjust the encoder architecture to keep 100hz rate, or else see if a different rate works well for you

**Comment by turian** [comment]
```
fairseq-hydra-train task.data=/home/ubuntu/surge.manifest/ --config-dir examples/wav2vec/config/pretraining --config-name wav2vec2_base_librispeech --sample-rate 44100
usage: fairseq-hydra-train [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}] [--package PACKAGE] [--run] [--multirun]
                           [--shell-completion] [--config-path CONFIG_PATH] [--config-name CONFIG_NAME] [--config-dir CONFIG_DIR] [--info]
                           [overrides [overrides ...]]
fairseq-hydra-train: error: unrecognized arguments: --sample-rate 44100
```
