### ISSUE TITLE
Example of LM doesnt work for custom trained model

### ISSUE THREAD

**Issue by PC09** [pytorch/fairseq#1283]
Hi,

I am trying to predict the words using transformer model trained on my own data.

I used the following command for training-
CUDA_VISIBLE_DEVICES=1 fairseq-train --task language_modeling data-bin/CM_data --save-dir checkpoints/transformer_CM_data --arch transformer_lm_wiki103 --max-update 286000 --max-lr 1.0 --t-mult 2 --lr-period-updates 270000 --lr-scheduler cosine --lr-shrink 0.75 --warmup-updates 16000 --warmup-init-lr 1e-07 --min-lr 1e-09 --optimizer nag --lr 0.0001 --clip-norm 0.1 --criterion adaptive_loss --max-tokens 1000 --update-freq 3 --tokens-per-sample 1000 --seed 1 --sample-break-mode none --skip-invalid-size-inputs-valid-test --ddp-backend=no_c10d 1>train_lm_CM.log 2>&1

when I am using the trained model for prediction with the below code, I am getting an error-

Code snippet-

from fairseq.models.transformer_lm import TransformerLanguageModel
custom_lm = TransformerLanguageModel.from_pretrained('/path/to/model/dir', 'checkpoint100.pt', tokenizer='moses', bpe='fastbpe')
custom_lm.sample('Barack Obama', beam=5)

Its giving me error-

loading archive file /workspace/test/fairseq-LM/fairseq-master/checkpoints/transformer_CM_data
| dictionary: 634704 types
Namespace(activation_dropout=0.1, activation_fn='relu', adaptive_input=True, adaptive_input_cutoff='20000,60000', adaptive_input_factor=4, adaptive_softmax_cutoff='20000,60000', adaptive_softmax_dropout=0.2, adaptive_softmax_factor=4, add_bos_token=False, arch='transformer_lm_wiki103', attention_dropout=0.1, best_checkpoint_metric='loss', bpe='fastbpe', bucket_cap_mb=25, char_embedder_highway_layers=2, character_embedding_dim=4, character_embeddings=False, character_filters='[(1, 64), (2, 128), (3, 192), (4, 256), (5, 256), (6, 256), (7, 256)]', clip_norm=0.1, cpu=False, criterion='adaptive_loss', curriculum=0, data='/workspace/test/fairseq-LM/fairseq-master/checkpoints/transformer_CM_data', dataset_impl=None, ddp_backend='no_c10d', decoder_attention_heads=8, decoder_embed_dim=1024, decoder_ffn_embed_dim=4096, decoder_input_dim=1024, decoder_layers=16, decoder_learned_pos=False, decoder_normalize_before=True, decoder_output_dim=1024, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, dropout=0.3, find_unused_parameters=False, fix_batches_to_gpus=False, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, future_target=False, keep_interval_updates=-1, keep_last_epochs=-1, lazy_load=False, log_format='simple', log_interval=1000, lr=[0.0001], lr_period_updates=270000.0, lr_scheduler='cosine', lr_shrink=0.75, max_epoch=0, max_lr=1.0, max_sentences=None, max_sentences_valid=None, max_target_positions=1000, max_tokens=1000, max_tokens_valid=1000, max_update=286000, maximize_best_checkpoint_metric=False, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=1e-09, momentum=0.99, moses_no_dash_splits=False, moses_no_escape=False, no_decoder_final_norm=True, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_save=False, no_save_optimizer_state=False, no_token_positional_embeddings=False, num_workers=1, optimizer='nag', optimizer_overrides='{}', output_dictionary_size=-1, past_target=False, raw_text=False, required_batch_size_multiple=8, reset_dataloader=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', sample_break_mode='none', save_dir='checkpoints/transformer_CM_data', save_interval=1, save_interval_updates=0, seed=1, self_target=False, sentence_avg=False, share_decoder_input_output_embed=False, skip_invalid_size_inputs_valid_test=True, t_mult=2.0, task='language_modeling', tbmf_wrapper=False, tensorboard_logdir='', threshold_loss_scale=None, tie_adaptive_proj=True, tie_adaptive_weights=True, tokenizer='moses', tokens_per_sample=1000, train_subset='train', update_freq=[3], use_bmuf=False, user_dir=None, valid_subset='valid', validate_interval=1, warmup_init_lr=1e-07, warmup_updates=16000, weight_decay=0.0)
File "test_lm.py", line 3, in <module>
    custom_lm = TransformerLanguageModel.from_pretrained('/workspace/test/fairseq-LM/fairseq-master/checkpoints/transformer_CM_data', 'checkpoint_best.pt',  tokenizer='moses', bpe='fastbpe')
  File "/workspace/test/fairseq-LM/fairseq-master/fairseq/models/fairseq_model.py", line 175, in from_pretrained
    return hub_utils.GeneratorHubInterface(x['args'], x['task'], x['models'])
  File "/workspace/test/fairseq-LM/fairseq-master/fairseq/hub_utils.py", line 93, in __init__
    self.bpe = encoders.build_bpe(args)
  File "/workspace/test/fairseq-LM/fairseq-master/fairseq/registry.py", line 41, in build_x
    return builder(args, *extra_args, **extra_kwargs)
  File "/workspace/test/fairseq-LM/fairseq-master/fairseq/data/encoders/fastbpe.py", line 21, in __init__
    if args.bpe_codes is None:
AttributeError: 'Namespace' object has no attribute 'bpe_codes'

I know the cause of the error as I didnt use BPE while training , so what changes should I make to the above code so that I can predict ?

TIA

**Comment by myleott** [comment]
With `bpe='fast_bpe'` you also need to specify `bpe_codes='/path/to/fast/bpe/codes'`
