### ISSUE TITLE
File not found when loading translation model due to operation system path

### ISSUE THREAD

**Issue by makcedward** [pytorch/fairseq#1285]
I am working on loading translation model while my env is Window 10 with PyTorch 1.3.0.  The issue occurs when loading the model with absolute path. 

I set the TORCH_HOME as "C:\\abc\hub\pytorch_fairseq_master". It load the model successfully while it cannot load BPE file because it points to "C:\\dict.en.txt". The issue comes from [here](https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/translation.py#L165) because it use ":" as delimiter. 

```
import os, torch
os.environ["TORCH_HOME"] = 'C:\\abc\'
torch.hub.list('pytorch/fairseq')  
en2de_ensemble = torch.hub.load(
    'pytorch/fairseq', 'transformer.wmt19.en-de',
    checkpoint_file='model1.pt',
    tokenizer='moses', bpe='subword_nmt')
```

Can you help to review whether it can be fixed in later release?

**Comment by edunov** [comment]
Can you use relative paths instead of absolute? 
Sorry, but neither of us here uses Windows and we don't have capacity to support it, you're welcome to submit a pull request if you have a fix.
