### ISSUE TITLE
Fail to load transformer.wmt18.en-de due to encoding

### ISSUE THREAD

**Issue by makcedward** [pytorch/fairseq#1287]
When loading translation model (e.g. 'transformer.wmt19.en-de'), found that the BPE codes include expected character and got the following exception.
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4703: character maps to <undefined>`

I guess it is related to [subword_nmt use utf-8](https://github.com/rsennrich/subword-nmt/blob/master/subword_nmt/apply_bpe.py#L338) natively. May you have any advise on it?

Sample Code
```
import torch
en2de_ensemble = torch.hub.load(
    'pytorch/fairseq', 'transformer.wmt18.en-de',
    checkpoint_file='wmt18.model1.pt',
    tokenizer='moses', bpe='subword_nmt')
```

**Comment by gunjanmimo** [comment]
may I work on this project?

**Comment by myleott** [comment]
Yes we use/expect utf-8 encoding throughout. You can usually adjust this via environment variables (LC_ALL and LANG)

**Comment by RenShuhuai-Andy** [comment]
> Yes we use/expect utf-8 encoding throughout. You can usually adjust this via environment variables (LC_ALL and LANG)

Hi~ I `export LANG=en_US.UTF-8; export LC_ALL=en_US.UTF-8`, but got the following error: `Error: invalid line 1 in BPE codes file: e n</w> 1423551864`.
The BPE file I used is downloaded from [transformer.wmt19.en-de](https://github.com/pytorch/fairseq/tree/master/examples/translation)
I found the [same issue in subword-nmt](https://github.com/rsennrich/subword-nmt/issues/76), but the method there didn't work for me. Can someone help me? @makcedward @myleott

**Comment by RenShuhuai-Andy** [comment]
> > Yes we use/expect utf-8 encoding throughout. You can usually adjust this via environment variables (LC_ALL and LANG)
> 
> Hi~ I `export LANG=en_US.UTF-8; export LC_ALL=en_US.UTF-8`, but got the following error: `Error: invalid line 1 in BPE codes file: e n</w> 1423551864`.
> The BPE file I used is downloaded from [transformer.wmt19.en-de](https://github.com/pytorch/fairseq/tree/master/examples/translation)
> I found the [same issue in subword-nmt](https://github.com/rsennrich/subword-nmt/issues/76), but the method there didn't work for me. Can someone help me? @makcedward @myleott

oh I have solved this problem: change `bpe='subword_nmt'` to `bpe='fastbpe'`
