### ISSUE TITLE
Issue with fb_pathmgr

### ISSUE THREAD

**Issue by hufuss** [pytorch/fairseq#1293]
Hello, 
I am running the interactive translation (via PyTorch Hub) example. 

When I run the command 
```en2de = torch.hub.load('pytorch/fairseq', 'transformer.wmt16.en-de', tokenizer='moses', bpe='subword_nmt')```

I am getting the following error:
```
File "torch/hub/pytorch_fairseq_master/fairseq/checkpoint_utils.py", line 140, in load_checkpoint_to_cpu
    from fairseq.fb_pathmgr import fb_pathmgr
ImportError: No module named 'fairseq.fb_pathmgr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.5/site-packages/torch/hub.py", line 363, in load
    model = entry(*args, **kwargs)
  File "torch/hub/pytorch_fairseq_master/fairseq/models/fairseq_model.py", line 172, in from_pretrained
    **kwargs,
  File "torch/hub/pytorch_fairseq_master/fairseq/hub_utils.py", line 54, in from_pretrained
    arg_overrides=kwargs,
  File "torch/hub/pytorch_fairseq_master/fairseq/checkpoint_utils.py", line 178, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "torch/hub/pytorch_fairseq_master/fairseq/checkpoint_utils.py", line 145, in load_checkpoint_to_cpu
    except (ModuleNotFoundError, ImportError):
NameError: name 'ModuleNotFoundError' is not defined
```

Can you please help me resolve this?

Thanks!

**Comment by echan00** [comment]
Same here, same error

**Comment by oceanwingworld** [comment]
same error

**Comment by myleott** [comment]
This should be fixed.

**Comment by yfeng21** [comment]
I'm still having this error with fairseq 0.9.0

**Comment by chrisdoyleIE** [comment]
same here

**Comment by NinaHristozovaTR** [comment]
And same here.

**Comment by LibertFan** [comment]
And same here.

**Comment by songwanguw** [comment]
Still have the issue

**Comment by murtuzamdahod** [comment]
I am having same issue

**Comment by murtuzamdahod** [comment]
I am having same issue. Anybody able to fix it or find a solution?

**Comment by neel04** [comment]
Same issue here @myleott

**Comment by JunjieHu** [comment]
I still have the same error @myleott  I got the repo a month ago, It was working fine a few days ago, but the program failed today, and I didn't pull the updates from the repo.

**Comment by JunjieHu** [comment]
Same issue @myleott

**Comment by alexcoca** [comment]
Same issue here too @myleott

**Comment by aadarshsingh191198** [comment]
I was getting this error while running the `generate.py` script. I simply used the latest stable version (0.10.2) of `fairseq` using `pip install -U fairseq` and the error vanished. 
PS: Earlier I had `fairseq v0.9.0` installed.

**Comment by fkjslee** [comment]
same error for both 0.8.0 and 0.10.0
