### ISSUE TITLE
BPE codes for NAT dataset

### ISSUE THREAD

**Issue by raymondhs** [pytorch/fairseq#1295]
Hello, I downloaded the NAT datasets listed in [here](https://github.com/pytorch/fairseq/tree/master/examples/nonautoregressive_translation). I noticed that the data was BPE-preprocessed, but the BPE codes were not in the zip file. Would it be possible to get the BPE codes also? I would like to try the model on some unseen data sets. Thank you!

**Comment by myleott** [comment]
@MultiPath @kahne can we share the BPE codes as well?

**Comment by MultiPath** [comment]
We have updated the datasets with BPE codes inside.
