### ISSUE TITLE
The latest commit is broken

### ISSUE THREAD

**Issue by guolinke** [pytorch/fairseq#1297]
Sync to the latest master branch (https://github.com/pytorch/fairseq/commit/5a2f76ede044b4904af9461e18253f2929cfc5a4 ) and find it cannot run.

error msg:

`ModuleNotFoundError: No module named 'fairseq.models.fb_tracing_transformer'`

https://github.com/pytorch/fairseq/blob/5a2f76ede044b4904af9461e18253f2929cfc5a4/fairseq/models/levenshtein_transformer.py#L19

**Comment by ngoyal2707** [comment]
Yes thanks for pointing, looking into it

**Comment by cndn** [comment]
A fix is landing. Sorry about that! If it's urgent plz comment out the line if you are not working with Levenshtein transformer.

**Comment by Eric-Wallace** [comment]
Fixed in latest commit.
