### ISSUE TITLE
How can I get sacreBLEU score with score.py script

### ISSUE THREAD

**Issue by weihChen** [pytorch/fairseq#1300]
Hello!
I want to get the sacreBLEU score for my transformer_base model and notice that there's an optional argument --sacrebleu for score.py
But I got a warning with it:

> WARNING:root:That's 100 lines that end in a tokenized period ('.')
WARNING:root:It looks like you forgot to detokenize your test data, which may hurt your score.
WARNING:root:If you insist your data is detokenized, or don't care, you can suppress this message with '--force'.

And I'm new to NLP&MT, it seems that I need to detokenize the data? I wonder what should I do to get the right result for sacreBLEU

**Comment by myleott** [comment]
Detokenization is not typically handled by fairseq. If you used the moses tokenizer then you can try detokenizing with sacremoses: https://github.com/alvations/sacremoses and manually feeding the detokenized output to the sacrebleu script.
