### ISSUE TITLE
Difference between transformer_iwslt_de_en, and transformer

### ISSUE THREAD

**Issue by JJumSSu** [pytorch/fairseq#1301]
Hi, thanks for the great library. 

I'm trying to train my NMT model from scratch. I'm trying to use transformer model as backbone, and I found out that in selecting among implemented architectures, there are many choices available. 

My question is what exactly is the difference between transformer_iwslt_de_en, and transformer, I assume, that both are "transformer-base" models, but difference lies in whether to tye parameters of encoder's and decoder's.(as for transformer_iwslt_de_en, yes)

Is it right? or any other major differences I should be aware of?
I couldn't find any documents explaining about it.

Thank you.

**Comment by zhaoguangxiang** [comment]
the key difference is the ffn hidden dim ,iwslt_de_en is 1024 and transformer is 2048

**Comment by huihuifan** [comment]
Yes, thanks for answering! You can see the transformer.py model code at the bottom the different predefined architectures.
