### ISSUE TITLE
RobertaModel.fill_mask() missing space

### ISSUE THREAD

**Issue by louismartin** [pytorch/fairseq#1306]
https://github.com/pytorch/fairseq/blob/5b086a0c17a16ed84285ce78017637d47fa50caa/fairseq/models/roberta/hub_interface.py#L174

When using sentencepiece, it seems that there is a missing space before the masked word in the output of fill_mask().
```
> roberta.fill_mask('My name is <mask>.', topk=1)
[('My name isJennifer.', 0.016039729118347168, 'Jennifer')] 
```

I don't know how to fixing without breaking other stuff.
The sentencepiece encoded sentence is: `▁My ▁n ame ▁is <mask> ▁ .`

**Comment by myleott** [comment]
This seems fixed in your Camembert model code? Please reopen if this is still an issue.
