### ISSUE TITLE
mismatch error when finetune

### ISSUE THREAD

**Issue by LiuYixian** [pytorch/fairseq#1313]

**Comment by LiuYixian** [comment]
I'm faced with the following error when finetuning CommonsenseQA with roberta.large

> Traceback (most recent call last):
>   File "/root/liuyx/fairseq/fairseq/trainer.py", line 184, in load_checkpoint
>     self.get_model().load_state_dict(state['model'], strict=True)
>   File "/root/liuyx/fairseq/fairseq/models/fairseq_model.py", line 69, in load_state_dict
>     return super().load_state_dict(state_dict, strict)
>   File "/root/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for RobertaModel:
> 	Missing key(s) in state_dict: "decoder.sentence_encoder.layers.0.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.0.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.0.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.0.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.0.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.0.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.1.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.1.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.1.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.1.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.1.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.1.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.2.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.2.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.2.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.2.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.2.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.2.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.3.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.3.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.3.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.3.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.3.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.3.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.4.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.4.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.4.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.4.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.4.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.4.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.5.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.5.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.5.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.5.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.5.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.5.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.6.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.6.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.6.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.6.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.6.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.6.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.7.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.7.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.7.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.7.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.7.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.7.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.8.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.8.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.8.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.8.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.8.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.8.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.9.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.9.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.9.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.9.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.9.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.9.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.10.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.10.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.10.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.10.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.10.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.10.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.11.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.11.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.11.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.11.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.11.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.11.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.12.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.12.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.12.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.12.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.12.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.12.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.13.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.13.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.13.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.13.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.13.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.13.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.14.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.14.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.14.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.14.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.14.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.14.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.15.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.15.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.15.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.15.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.15.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.15.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.16.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.16.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.16.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.16.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.16.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.16.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.17.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.17.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.17.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.17.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.17.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.17.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.18.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.18.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.18.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.18.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.18.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.18.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.19.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.19.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.19.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.19.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.19.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.19.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.20.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.20.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.20.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.20.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.20.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.20.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.21.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.21.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.21.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.21.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.21.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.21.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.22.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.22.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.22.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.22.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.22.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.22.self_attn.q_proj.bias", "decoder.sentence_encoder.layers.23.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.23.self_attn.k_proj.bias", "decoder.sentence_encoder.layers.23.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.23.self_attn.v_proj.bias", "decoder.sentence_encoder.layers.23.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.23.self_attn.q_proj.bias". 
> 	Unexpected key(s) in state_dict: "decoder.sentence_encoder.layers.0.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.0.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.1.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.1.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.2.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.2.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.3.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.3.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.4.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.4.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.5.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.5.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.6.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.6.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.7.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.7.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.8.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.8.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.9.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.9.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.10.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.10.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.11.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.11.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.12.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.12.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.13.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.13.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.14.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.14.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.15.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.15.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.16.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.16.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.17.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.17.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.18.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.18.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.19.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.19.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.20.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.20.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.21.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.21.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.22.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.22.self_attn.in_proj_bias", "decoder.sentence_encoder.layers.23.self_attn.in_proj_weight", "decoder.sentence_encoder.layers.23.self_attn.in_proj_bias". 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "train.py", line 343, in <module>
>     cli_main()
>   File "train.py", line 339, in cli_main
>     main(args)
>   File "train.py", line 81, in main
>     extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
>   File "/root/liuyx/fairseq/fairseq/checkpoint_utils.py", line 113, in load_checkpoint
>     reset_meters=args.reset_meters,
>   File "/root/liuyx/fairseq/fairseq/trainer.py", line 190, in load_checkpoint
>     'please ensure that the architectures match.'.format(filename)
> Exception: Cannot load model parameters from checkpoint models/model.pt; please ensure that the architectures match.

And I find 

> '# here, we convert in_proj_weight to individual q,k,v weights' 

in line 316 in 'fairseq/modules/multihead_attention.py'. I think that's why this problem occurs.

How to solve it? Thank you.

**Comment by sarahwie** [comment]
A temporary fix for me was re-installing fairseq from the commit before `fdf4c3e90`.
Have opened an issue (#1320 )

**Comment by myleott** [comment]
Fixed by f30fc7d71c93ecc28115b9eca2c2d680bd061d09
