### ISSUE TITLE
About alignment loss in Levenshtein Transformer

### ISSUE THREAD

**Issue by okgrammer** [pytorch/fairseq#1319]
Hi, would it be possible to integrate alignment loss in Levenshtein Transformer? May I confirm that it could be done by adding this part: https://github.com/pytorch/fairseq/blob/master/fairseq/criterions/label_smoothed_cross_entropy_with_alignment.py#L48-L56 into the forward method in nat_loss.py?

**Comment by MultiPath** [comment]
I think it is worthing exploring that.
