### ISSUE TITLE
How can I on the bi_trans_lm branch? 

### ISSUE THREAD

**Issue by karrynest** [pytorch/fairseq#1322]
There is an error: invalid choice: 'bi_transformer_lm_big'. 
Thanks!

**Comment by gvskalyan** [comment]
Only registered Architectures can be given as arguments such as [this](https://github.com/pytorch/fairseq/blob/master/fairseq/models/transformer_lm.py#L194).

You can specify your own architecture and register it via the specified annotation and import it before using it in your code.

**Comment by huihuifan** [comment]
hey, can you please try to use git to navigate to the right branch, e.g. "git checkout bi_trans_lm"
