### ISSUE TITLE
RoBERTa-large: RTE results in GLUE VS SuperGLUE

### ISSUE THREAD

**Issue by VictorSanh** [pytorch/fairseq#1332]
Hi,

It's not clear to me why the reported results for RTE with `roberta.large` [here on the README](https://github.com/pytorch/fairseq/tree/master/examples/roberta#results) are so different for GLUE (86.6) and SuperGLUE (89.5).
I might be missing something.
Is it because of the variance on 5 runs (median of 5 runs)?
As far as I understand, it's the same task, with the same data (modulo tsv vs jsonl).

Victor

**Comment by ngoyal2707** [comment]
Hey @VictorSanh, 
So for `GLUE` table, the reported results are without initializing from `MNLI` model to keep it consistent with how XLNet (SoTA on GLUE when we publish RoBERTa).
For `SuperGLUE`, they are with initializing from `MNLI` model to keep them consustent with Bert++ (SoTA on SG that time).
