### ISSUE TITLE
Early stopping based on BLEU

### ISSUE THREAD

**Issue by alrojo** [pytorch/fairseq#1336]
Training the default transformer model for [machine translation](https://github.com/pytorch/fairseq/tree/master/examples/translation#training-a-new-model).

How do I:
- Make early stopping based on BLEU scores (or similar metrics I define myself)
- Use a simpler tokenizer, such as space splitting `sentence.split(" ")`
- Set transformer architecture parameters (number of layers, hidden states, etc.)

Also, what do these numbers refer to: `wps 15165 | ups 4 | wpb 3586.843 | bsz 145.540`

**Comment by MortenSkovsted** [comment]
I am also very interested in early stopping, with user-defined metrics.
I hope to see a response.

**Comment by myleott** [comment]
Re: tokenization, fairseq always splits on space, we assume any other tokenization happens in preprocessing.

Re: adjusting transformer architecture parameters, please see the documentation: https://fairseq.readthedocs.io/en/latest/models.html#module-fairseq.models.transformer

Leaving the issue open for early stopping based on BLEU.

**Comment by myleott** [comment]
This is now available with the `--eval-bleu` option: 60fbf64f302a825eee77637a0b7de54fde38fb2c

You can also use `--best-checkpoint-metric bleu --maximize-best-checkpoint-metric`. See the example usage here: https://github.com/pytorch/fairseq/tree/master/examples/translation#iwslt14-german-to-english-transformer

**Comment by nikhiljaiswal** [comment]
@myleott In which fairseq-version is above functionality available. When I am trying to finetune M2M100 model, I am getting error as: 

KeyError: 'bleu'

when using following:

CUDA_VISIBLE_DEVICES=0,1,2,3 fairseq-train $path_2_data --ddp-backend=no_c10d --best-checkpoint-metric bleu --maximize-best-checkpoint-metric --max-tokens 2048  --no-epoch-checkpoints --finetune-from-model $pretrained_model --save-dir $checkpoint --task translation_multi_simple_epoch --encoder-normalize-before --langs 'af,am,ar,ast,az,ba,be,bg,bn,br,bs,ca,ceb,cs,cy,da,de,el,en,es,et,fa,ff,fi,fr,fy,ga,gd,gl,gu,ha,he,hi,hr,ht,hu,hy,id,ig,ilo,is,it,ja,jv,ka,kk,km,kn,ko,lb,lg,ln,lo,lt,lv,mg,mk,ml,mn,mr,ms,my,ne,nl,no,ns,oc,or,pa,pl,ps,pt,ro,ru,sd,si,sk,sl,so,sq,sr,ss,su,sv,sw,ta,th,tl,tn,tr,uk,ur,uz,vi,wo,xh,yi,yo,zh,zu' --lang-pairs $lang_pairs --decoder-normalize-before --sampling-method temperature --sampling-temperature 1.5 --encoder-langtok src --decoder-langtok --criterion label_smoothed_cross_entropy --label-smoothing 0.2 --optimizer adam --adam-eps 1e-06 --adam-betas '(0.9, 0.98)' --lr-scheduler inverse_sqrt --lr 3e-05 --warmup-updates 2500 --max-update 400000 --dropout 0.3 --attention-dropout 0.1 --weight-decay 0.0 --update-freq 2 --save-interval 1 --save-interval-updates 5000 --keep-interval-updates 10 --seed 222 --log-format simple --log-interval 2 --patience 5 --arch transformer_wmt_en_de_big --encoder-layers 24 --decoder-layers 24 --encoder-ffn-embed-dim 8192 --decoder-ffn-embed-dim 8192 --encoder-layerdrop 0.05 --decoder-layerdrop 0.05 --share-decoder-input-output-embed --share-all-embeddings --fixed-dictionary $fix_dict --fp16 --skip-invalid-size-inputs-valid-test


And when I am adding: --eval-bleu --eval-bleu-args --eval-bleu-detok --eval-bleu-remove-bpe 

I am getting the following error:

fairseq-train: error: unrecognized arguments: --eval-bleu --eval-bleu-args --eval-bleu-detok --eval-bleu-remove-bpe


Mine system information:
fairseq version: 0.10.2
torch: 1.10.1+cu113

My goal is to use BLEU as early stopping metric. I am unable to do so. Can you please guide me for the same. Thanks

**Comment by nikhiljaiswal** [comment]
@myleott @alrojo @MortenSkovsted @cordercorder @cbalioglu @alexeib  can you please help me in resolving my error. 
The details are mentioned above - https://github.com/facebookresearch/fairseq/issues/1336#issuecomment-1363923299
