### ISSUE TITLE
attn_mask is calculated but not used in encoder

### ISSUE THREAD

**Issue by fuzihaofzh** [pytorch/fairseq#1339]
https://github.com/pytorch/fairseq/blob/828c1ca7522278aa6c1eaf91fe0425b8f40dd832/fairseq/modules/transformer_layer.py#L87

attn_mask is calculated in encoder layer. But it hasn't been used. Why don't we send it directly into the self_attention layer? Is there any problem if we directly send it into the self_attention layer?

**Comment by felix-schneider** [comment]
I would also like to know why it is done that way, it just seems like a bug

**Comment by myleott** [comment]
It's not directly a bug for most use cases, but can be problematic if one tries to pass in this parameter. I'll work on refactoring it.
