### ISSUE TITLE
fp32 inference is faster than fp16, pytorch >= 1.2

### ISSUE THREAD

**Issue by mingruimingrui** [pytorch/fairseq#1343]
I'd like to leave an interesting nugget.

On pytorch==1.0, fp16 inference is faster than fp32 but on pytorch>=1.2,

On german news-test 2014

| Precision | Inference speed (sents/sec) | 
| --- | --- |
| fp32 | 324.16 |
| fp16 | 307.11 |

*german news-test 2014 was pre-sorted according to the number of tokens in each sentence before batching. This is to minimize the number of padding tokens required.

Environmental setup

CPU: Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
GPU: V100

CUDA==10.0 (conda)
cuDNN==7.6.3 (conda)

python==3.6
fairseq==0.8.0 (pip)
pytorch==1.3 (conda)

@myleott Could I check with you if these results are expected?

**Comment by myleott** [comment]
This is not expected.
