### ISSUE TITLE
A FAIRSEQ text summarization example: the abstractive approach with a Levenshtein transformer

### ISSUE THREAD

**Issue by sdll** [pytorch/fairseq#1347]
The [Levenshtein transformer](https://arxiv.org/pdf/1905.11006.pdf) paper reports 0.75+ improvements in ROUGE-L in the abstractive text summarization task on Gigaword over the baseline transformer.

![benchmarks](https://trello-attachments.s3.amazonaws.com/5d94bb7214117281c1eb2a91/5da7168588b68b5a9ab3d246/4173ea8cdb84f0d55f6acfd54dbb94d9/Screen_Shot_2019-10-16_at_4.12.31_PM.png)

The team of @fvadzim, @whiteRa2bit, @NickShatalov and I would love to reproduce the result as part of the intensive practicum organized by Yandex ([here](https://academy.yandex.ru/posts/yandeks-universitet-sirius-intensiv-po-mashinnomu-obucheniyu?fbclid=IwAR12btEkUFpeGdEuSbrb7uLfRMwjjddp9MCFVlMXPgcoiOAC5QvaMNT_SeI) is the description in Russian) and continue working on the PR after the event ends on November 16, trying the model out on the Russian news dataset and contributing the docs that explain the training procedure to FAIRSEQ.

## Proposal
Here is the plan of what we would love to contribute:

1. **Creating a new page on text summarization in [examples](https://github.com/pytorch/fairseq/tree/master/examples)**

	The first sentence in README mentions  summarization amongst others, but there is no complete description of how to achieve this, despite the fact that both the [Levenshtein transformer implementation](https://github.com/pytorch/fairseq/tree/master/examples/nonautoregressive_translation) and [`pay_less_attention_paper`](https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper) seem to have almost all of the necessary code to make it work.

2. **Making a new task for training the Levenshtein transformer for abstractive text summarization**

	The end goal would be to train the model on both English and Russian datasets.
	
## Questions

1. Could you please tell me whether there are any apparent roadblocks in the code itself you can see already that can prevent this plan from succeeding?
2. The paper uses a Transformer base as a teacher to obtain ROUGE-L of 33.81. The current implementation of NAT NMT also takes the teacher instead of oracle approach as well, so this should help us in setting the training up. Another training scheme that @justheuristic has mentioned in private communication is the one similar to the NMT refinement method introduced by @lena-voita, @rsennrich and @anvdev in [this paper](https://arxiv.org/pdf/1909.01383.pdf): the idea is to produce an extractive summary first, and then refine it with Leveshtein. Have you tested this idea? Sounds nice to include this variation in the comparison as well.
3. Seems that the current implementation is under active development at the moment, given a number of issues on SIGSEV in the multi-GPU environment:
 
   - https://github.com/pytorch/fairseq/issues/1305
   - https://github.com/pytorch/fairseq/issues/1308
   - https://github.com/pytorch/fairseq/issues/1346

    Are there any precautions on which commit of the repo to use in order to avoid these issues? Is the fix/major update coming soon?

**Comment by gvskalyan** [comment]
@myleott @edunov

**Comment by sdll** [comment]
The v2 of the paper is [out](https://arxiv.org/pdf/1905.11006.pdf). The base transformer performs better than expected, but Levenshtein still beats the base in speed, and provides comparable results for summarization:

![IMAGE 2019-11-11 11:23:37](https://user-images.githubusercontent.com/17913919/68572137-b609c600-0475-11ea-96cd-9c080c214957.jpg)

**Comment by huihuifan** [comment]
@kahne could you take a look at this?

**Comment by Cloudmersive** [comment]
@sdll Were you still planning to publish these to the repo?

**Comment by sdll** [comment]
No, sorry, I do not have the bandwidth now to brush up our results, but you can take a look [here](https://github.com/phramer/phramer/tree/master/sh/architectures/base_transformer) for the training scripts and [here](https://github.com/phramer/fairseq) for fairseq with the comet.ml support.
