### ISSUE TITLE
Extract word embeddings vector as text from pre-trained language model

### ISSUE THREAD

**Issue by pltrdy** [pytorch/fairseq#1351]
Hi,

I've been training a language model on some data, based on the [guidelines](https://github.com/pytorch/fairseq/blob/a0f75996b1e25c97149bcbc6aad7eed5601daab0/examples/language_model/README.md) (I report my exact command bellow), now I'd like to extract the word vectors as text e.g. `word dim0 dim1 ... dimN` one word per line.

I've been looking at the `.pt` files, which isn't super clear for me, in particular, I would have simple keys for the embedding weights (e.g. `decoder.embeddings: torch.Size([150000, 1024])`), instead, I get: 
```
decoder.embed_tokens.embeddings.0.0.weight: torch.Size([20000, 1024])
decoder.embed_tokens.embeddings.0.1.weight: torch.Size([1024, 1024])
decoder.embed_tokens.embeddings.1.0.weight: torch.Size([40000, 256])
decoder.embed_tokens.embeddings.1.1.weight: torch.Size([1024, 256])
decoder.embed_tokens.embeddings.2.0.weight: torch.Size([90000, 64])
decoder.embed_tokens.embeddings.2.1.weight: torch.Size([1024, 64])
```

Any suggestions?

----
LM Preprocessing + Training cmd:
```
preprocess(){
fairseq-preprocess \
    --only-source \
    --trainpref $data/$corpus.train \
    --validpref $data/$corpus.valid \
    --testpref $data/$corpus.test \
    --destdir $root \
    --nwordssrc 150000 \
    --workers 20
}

train(){
    fairseq-train $root \
        --save-dir $root \
        --task language_modeling \
        --sample-break-mode complete \
        --arch transformer_lm_wiki103 \
        --save-interval-updates 10000 \
        --max-update 586000 \
        --max-lr 1.0 \
        --t-mult 2 \ 
        --lr-period-updates 270000 \
        --lr-scheduler cosine \
        --lr-shrink 0.75 \
        --warmup-updates 16000 \
        --warmup-init-lr 1e-07 \
        --min-lr 1e-09 \
        --optimizer nag \
        --lr 0.0001 \
        --clip-norm 0.1 \
        --criterion adaptive_loss \
        --max-tokens 1024 \
        --update-freq 3 \ 
        --tokens-per-sample 1023 \
        --seed 1 \ 
        --skip-invalid-size-inputs-valid-test \
        --ddp-backend=no_c10d \
        --add-bos-token
}
```

**Comment by myleott** [comment]
This is because you trained the model with adaptive inputs. We've recently added an updated/simpler language model example command that you can use: https://github.com/pytorch/fairseq/tree/master/examples/language_model#2-train-a-language-model

This will result in a single embedding matrix.
