### ISSUE TITLE
Tensorboard logs AverageMeter.val instead of AverageMeter.avg

### ISSUE THREAD

**Issue by amrsharaf** [pytorch/fairseq#1353]
I noticed the values logged to tensorboard doesn't match the values printed in json format. I looked deeper and seems like this line should be modified to `stats[key].avg` instead of `stats[key].val`

https://github.com/pytorch/fairseq/blob/1d1e460d42486207f423ecfd8eabb26de1f09abf/fairseq/progress_bar.py#L279

**Comment by myleott** [comment]
This is deliberate since Tensorboard implements its own smoothing :/
