### ISSUE TITLE
Converting transformer-LM (GPT2) trained by fairseq to huggingface transformers

### ISSUE THREAD

**Issue by tagucci** [pytorch/fairseq#1354]
After training transformer-LM using fairseq (`--task language_modeling -- arch transformer_lm_gpt2_medium`), I want to use this transformer-LM (GPT2-medium) by [huggingface-transformers](https://github.com/huggingface/transformers).
How is is possible to convert fairseq gpt2 model to huggingface gpt2?

**Comment by myleott** [comment]
They have a script for converting RoBERTa checkpoints to the transformers library: https://github.com/huggingface/transformers/blob/master/transformers/convert_roberta_original_pytorch_checkpoint_to_pytorch.py

It'd be great to have something similar for language modeling. PRs welcome!

**Comment by usuyama** [comment]
It seems the script is removed from the master @myleott 
Found [the file](https://github.com/louismartin/transformers/blob/49cba6e5434d6ea8d0a54883ee0ed3635af1371d/transformers/convert_roberta_original_pytorch_checkpoint_to_pytorch.py) here but not sure if it still works.
Several related issues:
https://github.com/huggingface/transformers/issues/3129
https://github.com/huggingface/transformers/issues/1850

Would be great if there's updated scripts for converting fairseq <-> huggingface model weights / format.

**Comment by holyma** [comment]
@myleott how to convert model in huggingface transformers to fairseq ，eg [wav2vec-viet](https://huggingface.co/dragonSwing/wav2vec2-base-pretrain-vietnamese)
