### ISSUE TITLE
CommonsenseQA evaluate issue

### ISSUE THREAD

**Issue by csliangchen** [pytorch/fairseq#1355]
When I run your commonsense Evaluate script, the error like the screenshots: 
![image](https://user-images.githubusercontent.com/40766226/68383074-e577b480-018f-11ea-970e-564a44291bd3.png)
I saw 'q_proj','k_proj', so it maybe use the bert model instead of Roberta.  But i can't debug.
Please help.

**Comment by csliangchen** [comment]
I run this one:
![image](https://user-images.githubusercontent.com/40766226/68383650-0391e480-0191-11ea-9576-65fbc54c2076.png)

**Comment by huihuifan** [comment]
@ngoyal2707  ?

**Comment by myleott** [comment]
Ah this is because we renamed some of the parameters in multihead attention. It should work if you pull the latest version of fairseq, but if not then please reopen this issue.
