### ISSUE TITLE
Options to serve fairseq translation model?

### ISSUE THREAD

**Issue by echan00** [pytorch/fairseq#1356]
Curious to know what are the options to serve a translation model for inference (for production).   I see a few discussions on ONYX, but nothing solid and nothing official.  Neither do I find any information about exporting to other model formats that allow for serving.

**Comment by yohokuno** [comment]
I'm using flask for serving REST API and service-streamer for queueing requests and dispatching to multiple gpus as mini-batches.

**Comment by mohammedayub44** [comment]
Another option could be [Torchserve](https://pytorch.org/serve/), although it requires an instance of model class and cpu/gpu specific handler to process input batches.

**Comment by xsxiong** [comment]
> I'm using flask for serving REST API and service-streamer for queueing requests and dispatching to multiple gpus as mini-batches.

Hello, I also use gunicorn flask to build REST api but tps is low,How much can you reach? can you help me?
