### ISSUE TITLE
Translation predictions are short (cut off)

### ISSUE THREAD

**Issue by echan00** [pytorch/fairseq#1358]
For long source sentences, my target sentence predictions are cut off at the end. Is there a parameter I can change to extend this (during inference or training)? 

I see that `max_len_a=0, max_len_b=200` by default, changing to max_len_b=512 did not seem to help:

`python3 interactive.py     --path checkpoints/checkpoint_best.pt data-bin/tagatag     --beam 5 --source-lang en --target-lang zh     --bpe subword_nmt --bpe-codes data-bin/tagatag/code  --max-len-b=512`

**Comment by huihuifan** [comment]
for training, you need to set the max tokens limits. for evaluation you can set max len a and b

**Comment by echan00** [comment]
Hmmm. My training parameter was `--max-tokens=4000` 

I'm not seeing any difference in prediction sentence length when changing from `--max-len-b=200` to `--max-len-b=512`, what else could I inspect to determine the issue?
