### ISSUE TITLE
Fatal error: gradients are inconsistent between workers

### ISSUE THREAD

**Issue by LibertFan** [pytorch/fairseq#1359]
I met the above error while training roberta_base. Does anyone know the reason?

**Comment by huihuifan** [comment]
Possibly an issue with multiple GPU training, can you check that one GPU is not out of memory for example

**Comment by myleott** [comment]
Please try `--ddp-backend=no_c10d`

**Comment by memray** [comment]
@huihuifan @myleott I encountered the same issue and I think it's caused by OOM on some devices. This happens occasionally and unpredictably due to some weird inputs.  I wonder why it's not addressed like overflow exception by simply zero_grad and drop the current batch?

Thank you,
Rui
