### ISSUE TITLE
Is there any way to incrementally binarize a dataset?

### ISSUE THREAD

**Issue by getao** [pytorch/fairseq#1360]
Assume I have preprocessed (binarized) a very large dataset. If I want to add some new data to the previous dataset, now I have to preprocess all the data again, which takes much time.

Is there any way to incrementally process the dataset? So that I just need to preprocess the new data, and then add it to the preprocessed old data?

**Comment by myleott** [comment]
You can preprocess the new data separately. Thereafter you can train over the combined set by passing the combined data paths:
```
python train.py /path/to/data1:/path/to/data2 (...)
```

**Comment by tsingcoo** [comment]
👍
