### ISSUE TITLE
[QUESTION] XLM-RoBERTa for NER

### ISSUE THREAD

**Issue by loretoparisi** [pytorch/fairseq#1366]
It would be possible to provide an example of **NER** task for **XLM-RoBERTa**. We would like to reproduce NER results from the paper with CoNLL-2003 here:

<img width="472" alt="Schermata 2019-11-11 alle 16 47 53" src="https://user-images.githubusercontent.com/163333/68600574-0ea38800-04a3-11ea-9728-ea1306b2b0d3.png">

 and to run a fine tuning against a specific dataset.
Thanks

**Comment by huihuifan** [comment]
@kartikayk ?

**Comment by kartikayk** [comment]
@loretoparisi thanks for checking in! We'll share detailed pointers for how to fine-tune XLM-R on QA and NER tasks in PyText in a week or so.

**Comment by loretoparisi** [comment]
@kartikayk that's amazing! Thank you so much.

**Comment by myleott** [comment]
@kartikayk any update on this?

**Comment by kartikayk** [comment]
@myleott the code should be in the PyText repo after a PyText release tomorrow/Wednesday I believe. Will post a link here once its done.

**Comment by rnd2110** [comment]
@kartikayk  Any update on this? I am looking for examples on fine tuning XLM-Roberta for NER (or sequence tagging in general). Thanks!

**Comment by mohammadKhalifa** [comment]
@rnd2110 I created this [repo](https://github.com/mohammadKhalifa/xlm-roberta-ner) for this exact task. I hope it helps.

**Comment by rnd2110** [comment]
@mohammadKhalifa Thank you. This is so useful.

**Comment by bogolese** [comment]
> @rnd2110 Checkout my [code](https://github.com/mohammadKhalifa/xlm-roberta-ner) for this exact task. I hope it helps.

Thanks for this.  Your code requires fairseq, which requires GPUs.  Are you aware of a cpu-only approach for fine tuning?  My search has been fruitless so far.  :(

**Comment by rnd2110** [comment]
> Thanks for this. Your code requires fairseq, which requires GPUs. Are you aware of a cpu-only approach for fine tuning? My search has been fruitless so far. :(

You can still run the code on CPU. It will be slower though.
