### ISSUE TITLE
 RuntimeError: _thnn_conv2d_forward not supported on CPUType for Half

### ISSUE THREAD

**Issue by 943274923** [pytorch/fairseq#1368]
when I use fairseq to train a wav2vec model ,This error has occurred. “RuntimeError: _thnn_conv2d_forward not supported on CPUType for Half”

My use
python train.py ./w2 --save-dir ./w2vmodel --num-workers 6 --fp16 --max-update 400000 --save-interval 1 --no-epoch-checkpoints \
--arch wav2vec --task audio_pretraining --lr 1e-06 --min-lr 1e-09 --optimizer adam --max-lr 0.005 --lr-scheduler cosine \
--conv-feature-layers '[(512, 10, 5), (512, 8, 4), (512, 4, 2), (512, 4, 2), (512, 4, 2), (512, 1, 1), (512, 1, 1)]' \
--conv-aggregator-layers '[(512, 2, 1), (512, 3, 1), (512, 4, 1), (512, 5, 1), (512, 6, 1), (512, 7, 1), (512, 8, 1), (512, 9, 1), (512, 10, 1), (512, 11, 1), (512, 12, 1), (512, 13, 1)]' \
--skip-connections-agg --residual-scale 0.5 --log-compression --warmup-updates 500 --warmup-init-lr 1e-07 --criterion binary_cross_entropy --num-negatives 10 \
--max-sample-size 150000 --max-tokens 1500000 --skip-invalid-size-inputs-valid-test
 
ERROR log  is:
| model wav2vec, criterion BinaryCrossEntropyCriterion
| num. model params: 32537088 (num. trained: 32537088)
| training on 1 GPUs
| max tokens per GPU = 1500000 and max sentences per GPU = None
| no existing checkpoint found ./w2vmodel/checkpoint_last.pt
| loading train data for epoch 0
| epoch 001:   0%|                                                                                                                               | 0/224 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 343, in <module>
    cli_main()
  File "train.py", line 339, in cli_main
    main(args)
  File "train.py", line 92, in main
    train(args, trainer, task, epoch_itr)
  File "train.py", line 133, in train
    log_output = trainer.train_step(samples)
  File "/workspace/wav2letter/fairseq/fairseq/trainer.py", line 329, in train_step
    raise e
  File "/workspace/wav2letter/fairseq/fairseq/trainer.py", line 306, in train_step
    ignore_grad
  File "/workspace/wav2letter/fairseq/fairseq/tasks/fairseq_task.py", line 246, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/workspace/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/wav2letter/fairseq/fairseq/criterions/binary_cross_entropy.py", line 29, in forward
    net_output = model(**sample['net_input'])
  File "/workspace/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/wav2letter/fairseq/fairseq/models/wav2vec.py", line 175, in forward
    features = self.feature_extractor(source)
  File "/workspace/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/wav2letter/fairseq/fairseq/models/wav2vec.py", line 286, in forward
    x = conv(x)
  File "/workspace/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/workspace/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 202, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: _thnn_conv2d_forward not supported on CPUType for Half

**Comment by huihuifan** [comment]
What version of pytorch are you on? might be an environment issue, I can't repro

**Comment by cdyangbo** [comment]
I have same issue. torch1.3.1,cuda 10.1, python3.7.5, ubuntu 16.04, 2*geforce 1080ti.
ps. my other computer run it ok.

**Comment by cdyangbo** [comment]
When no use '--fp16',  it work, but too slow.  and nvidia-smi not display the cuda process.
| model wav2vec, criterion BinaryCrossEntropyCriterion
| num. model params: 32537088 (num. trained: 32537088)
| training on 1 GPUs
| max tokens per GPU = 500000 and max sentences per GPU = None
| no existing checkpoint found /media/sdb4t/en_wav2vec/checkpoint_last.pt
| loading train data for epoch 0
| epoch 001:   0%|                                    | 0/38479 [00:00<?, ?it/s]/usr/local/lib/python3.7/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
| epoch 001:   0%| | 1/38479 [00:11<123:51:35, 11.59s/it, loss=1.427, ppl=2.69, wps=32874, ups=0, wpb=423984.000, bsz=423984.000, num_updates=1, lr=1.00998e-05, g| epoch 001:   0%| | 2/38479 [00:24<127:00:23, 11.88s/it, loss=1.433, ppl=2.70, wps=42086, ups=0, wpb=476520.000, bsz=476520.000, num_updates=2, lr=2.00996e-05, gnor| epoch 001:   0%| | 3/38479 [00:37<130:54:57, 12.25s/it, loss=1.188, ppl=2.28, wps=42941, ups=0, wpb=508816.000, bsz=508816.000, num_updates=3, lr=3.00994e-05, gnorm=23.404, clip=0.667, oom=0.000, wall=39, train_wall=| epoch 001:   0%| | 4/38479 [00:51<137:17:04, 12.85s/it, loss=1.061, ppl=2.09, wps=42216, ups=0, wpb=527208.000, bsz=527208.000, num_updates=4, lr=4.00992e-05, gnorm=18.365, clip=0.500, oom=0.000, wall=53, train_wall=| epoch 001:   0%| | 5/38479 [01:06<143:13:09, 13.40s/it, loss=1.009, ppl=2.01, wps=41354, ups=0, wpb=536448.000, bsz=536448.000, num_updates=5, lr=5.0099e-05, gnorm=15.648, clip=0.400, oom=0.000, wall=68, train_wall=6| epoch 001:   0%| | 6/38479 [01:23<155:11:09, 14.52s/it, loss=0.979, ppl=1.97, wps=41943, ups=0, wpb=572176.000, bsz=572176.000, num_updates=6, lr=6.00988e-05, gnorm=13.849, clip=0.333, oom=0.000, wall=85, train_wall=| epoch 001:   0%| | 7/38479 [01:33<142:26:38, 13.33s/it, loss=0.968, ppl=1.96, wps=42129, ups=0, wpb=555833.143, bsz=555833.143, num_updates=7, lr=7.00986e-05, gnorm=12.645, clip=0.286, oom=0.000, wall=95, train_wall=| epoch 001:   0%| | 8/38479 [01:43<131:28:18, 12.30s/it, loss=0.953, ppl=1.94, wps=42258, ups=0, wpb=540012.000, bsz=540012.000, num_updates=8, lr=8.00984e-05, gnorm=11.878, clip=0.250, oom=0.000, wall=105, train_wall| epoch 001:   0%| | 9/38479 [01:55<130:12:08, 12.18s/it, loss=0.927, ppl=1.90, wps=42349, ups=0, wpb=536976.000, bsz=536976.000, num_updates=9, lr=9.00982e-05, gnorm=11.120, clip=0.222, oom=0.000, wall=117, train_wall| epoch 001:   0%| | 10/38479 [02:10<137:48:05, 12.90s/it, loss=0.892, ppl=1.86, wps=42347, ups=0, wpb=544896.000, bsz=544896.000, num_updates=10, lr=0.000100098, gnorm=10.775, clip=0.200, oom=0.000, wall=132, train_wa| epoch 001:   0%| | 11/38479 [02:27<152:43:11, 14.29s/it, loss=0.849, ppl=1.80, wps=42507, ups=0, wpb=564912.000, bsz=564912.000, num_updates=11, lr=0.000110098, gnorm=10.517, clip=0.182, oom=0.000, wall=149, train_wa| epoch 001:   0%| | 12/38479 [02:41<150:14:09, 14.06s/it, loss=0.830, ppl=1.78, wps=42668, ups=0, wpb=567732.000, bsz=567732.000, num_updates=12, lr=0.000120098, gnorm=10.974, clip=0.167, oom=0.000, wall=163, train_wa| epoch 001:   0%| | 13/38479 [02:52<140:40:19, 13.17s/it, loss=0.814, ppl=1.76, wps=42418, ups=0, wpb=557324.308, bsz=557324.308, num_updates=13, lr=0.000130097, gnorm=10.508, clip=0.154, oom=0.000, wall=174, train_wa| epoch 001:   0%| | 14/38479 [02:58<119:31:41, 11.19s/it, loss=0.807, ppl=1.75, wps=42313, ups=0, wpb=536160.429, bsz=536160.429, num_updates=14, lr=0.000140097, gnorm=10.175, clip=0.143, oom=0.000, wall=180, train_wa| epoch 001:   0%| | 15/38479 [03:13<128:59:30, 12.07s/it, loss=0.791, ppl=1.73, wps=42455, ups=0, wpb=542022.800, bsz=542022.800, num_updates=15, lr=0.000150097, gnorm=9.850, clip=0.133, oom=0.000, wall=194, train_wall=193] 

SO. I THINK TORCH NOT WORK IN GPU MODE.

**Comment by cdyangbo** [comment]
and torch.cuda.is_available() is False, so problem should be cuda driver.

**Comment by cdyangbo** [comment]
I Fix it with:
(1) uninstall nvidia driver and all cuda version.
(2）reinstall nvidia driver and cuda with 'cuda_10.1.105_418.39_linux.run' download from NVIDIA.
