### ISSUE TITLE
Error while finding module specification for 'fairseq.examples.roberta.multiprocessing_bpe_encoder' 

### ISSUE THREAD

**Issue by mukta3396** [pytorch/fairseq#1374]
Installed the roberta model to pre-train on my own data
1 - pip install git+https://github.com/pytorch/fairseq.git
2 - !for SPLIT in train dev test; do \
    python -m fairseq.examples.roberta.multiprocessing_bpe_encoder \
        --encoder-json gpt2_bpe/encoder.json \
        --vocab-bpe gpt2_bpe/vocab.bpe \
        --inputs snli_1.0/snli_1.0_${SPLIT}.jsonl \
        --outputs snli_1.0/snli_1.0/opt_snli_${SPLIT}.bpe \
        --keep-empty \
        --workers 60; \
done

However I get the following error: 
/usr/bin/python3: Error while finding module specification for 'fairseq.examples.roberta.multiprocessing_bpe_encoder' (ModuleNotFoundError: No module named 'fairseq.examples')

Why does the setup file not install subdirectories?

**Comment by myleott** [comment]
We don't install the examples directory via pip. Please clone the source directly:
```
git clone https://github.com/pytorch/fairseq.git
python -m fairseq.examples.roberta.multiprocessing_bpe_encoder (...)
```
