### ISSUE TITLE
Tokenization of BART

### ISSUE THREAD

**Issue by memray** [pytorch/fairseq#1377]
Hi!

The paper mentions that `Documents are tokenized with the same byte-pair encoding
as GPT-2`. I check the tokenization of released BART and compare it with both GPT-2 and RoBERTa of huggingface, and RoBERTa has the same output. Is it safe to directly use the huggingface RoBERTa tokenizer for BART?

Thanks,
Rui

**Comment by ngoyal2707** [comment]
Yes, you can use HF RoBERTa tokenizer.
