### ISSUE TITLE
Roberta Paper discrepancy with LR

### ISSUE THREAD

**Issue by Eric-Wallace** [pytorch/fairseq#1378]
In the RoBERTa readme (README.pretraining.md), it reports peak LR = `0.0005` when using batch size 2048, but the paper reports `0.0007`. There is a similar discrepancy for batch size 8192 in the readme's table and in the paper.

Just wondering what the recommended setting is, thanks.

**Comment by myleott** [comment]
The values reported in the paper are correct. In general, higher learning rates are preferable, but stability with higher learning rates is somewhat dataset dependent, so we recommended slightly more conservative values in the README.

I'd suggest starting with the values recommended in the README, ensure they are stable, and then try slightly larger values if possible.

**Comment by Eric-Wallace** [comment]
Thanks a bunch @myleott!!
