### ISSUE TITLE
positional attention in nonautoregressive_transformer

### ISSUE THREAD

**Issue by JackHorse** [pytorch/fairseq#1380]
Hi，

thank you for releasing the code about nonautoregressive_transformer.

but why I can‘t find the positional attention in decoder as described in the paper [Non-Autoregressive Neural Machine Translation (Gu et al., 2017)](https://arxiv.org/abs/1711.02281) ?

**Comment by MultiPath** [comment]
Hi, we only implemented the simplest version of the nonautoregressive model which does not use any special module described in the original paper. 
I can push a new PR to implement the positional attention and fertility later.

**Comment by JackHorse** [comment]
All right!

Thanks for your prompt reply.

**Comment by SkyAndCloud** [comment]
@MultiPath Hi, I want to know when will you commit the PR?

**Comment by MultiPath** [comment]
@SkyAndCloud Hi, I currently did not have bandwidth to re-implement this part. Maybe in January.

**Comment by wangwang110** [comment]
> @SkyAndCloud Hi, I currently did not have bandwidth to re-implement this part. Maybe in January.

Any new developments？

**Comment by wangwang110** [comment]
> @SkyAndCloud Hi, I currently did not have bandwidth to re-implement this part. Maybe in January.

Any new developments？

**Comment by wangwang110** [comment]
@MultiPath   Any new developments for re-implement NAT？

**Comment by SkyAndCloud** [comment]
@wangwang110 Hi, I have not found the update since then.
