### ISSUE TITLE
No module named 'fairseq.models'

### ISSUE THREAD

**Issue by mukta3396** [pytorch/fairseq#1382]
I pretrained the Roberta Model using my own dataset. The training was completed and I received message "saved checkpoint checkpoints/checkpoint_best.pt".
Now as I try to load the model with the following lines of code:
from fairseq.models.roberta import RobertaModel
roberta = RobertaModel.from_pretrained('checkpoints', 'checkpoint_best.pt', '../data-bin/wikitext-103')
assert isinstance(roberta.model, torch.nn.Module)

I get error: No module named 'fairseq.models'

What needs to be done?

**Comment by myleott** [comment]
You need to either be in the `fairseq/` directory or install your local fairseq checkout with:
```
cd /path/to/fairseq
pip install --editable .
```

**Comment by bharath-kumarn** [comment]
hindien_1  | Traceback (most recent call last):
hindien_1  |   File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
hindien_1  |     self.run()
hindien_1  |   File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
hindien_1  |     self._target(*self._args, **self._kwargs)
hindien_1  |   File "/usr/local/lib/python3.6/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
hindien_1  |     target(sockets=sockets)
hindien_1  |   File "/usr/local/lib/python3.6/site-packages/uvicorn/server.py", line 48, in run
hindien_1  |     loop.run_until_complete(self.serve(sockets=sockets))
hindien_1  |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
hindien_1  |     return future.result()
hindien_1  |   File "/usr/local/lib/python3.6/site-packages/uvicorn/server.py", line 55, in serve
hindien_1  |     config.load()
hindien_1  |   File "/usr/local/lib/python3.6/site-packages/uvicorn/config.py", line 308, in load
hindien_1  |     self.loaded_app = import_from_string(self.app)
hindien_1  |   File "/usr/local/lib/python3.6/site-packages/uvicorn/importer.py", line 23, in import_from_string
hindien_1  |     raise exc from None
hindien_1  |   File "/usr/local/lib/python3.6/site-packages/uvicorn/importer.py", line 20, in import_from_string
hindien_1  |     module = importlib.import_module(module_str)
hindien_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
hindien_1  |     return _bootstrap._gcd_import(name[level:], package, level)
hindien_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
hindien_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
hindien_1  |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
hindien_1  |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
hindien_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
hindien_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
hindien_1  |   File "./main.py", line 2, in <module>
hindien_1  |     from fairseq.models.roberta import RobertaModel
hindien_1  | ModuleNotFoundError: No module named 'fairseq.models'

**Comment by IsSeck** [comment]
I had a similar issue that was solved using the command `pip install fairseq`
