### ISSUE TITLE
Can I train a translation model using data from another task?

### ISSUE THREAD

**Issue by wiany11** [pytorch/fairseq#1387]
I want to do dual translation so I built two models like the following:
```
model, _ = task.build_model(args)
model_r, _ = task_r.build_model(args_r)  # translatio in reverse direction
```

After I modified `fairseq.data.language_pair_dataset.collate` to fetch backward translation samples as well, I fed them to two models like:
```
def train_step(self, sample, model, model_r, criterion, optimizer, ignore_grad=False):
    ...
    loss_f, sample_size_f, logging_output_f = criterion(model, sample['forward'])
    loss_r, sample_size_r, logging_output_r = criterion(model_r, sample['reverse'])
    ...
```

`loss_r` is , however, computed as `nan`...
More precisely tensors were getting more and more `nan` values while computing attentions in decoding process.
`TransformerDecoderLayer.self_attn : MultiheadAttention` generates `nan`s...

Fairseq is too well-packaged so I cannot clearly get all the inter-class dependencies, especially between task and model. 
Can you give me an advice for dual translation?

Thank you.

**Comment by wiany11** [comment]
\

**Comment by cbaziotis** [comment]
Hi, I am training a model based on the `semisupervised_translation` task that uses on-the-fly backtranslation, and I am facing a similar problem with `nan`s. I noticed that after the first 100 iterations or so I start to get nan's Did you solve your problem and if yes what did you do?

**Comment by kkeleve** [comment]
> I want to do dual translation so I built two models like the following:
> 
> ```
> model, _ = task.build_model(args)
> model_r, _ = task_r.build_model(args_r)  # translatio in reverse direction
> ```
> 
> After I modified `fairseq.data.language_pair_dataset.collate` to fetch backward translation samples as well, I fed them to two models like:
> 
> ```
> def train_step(self, sample, model, model_r, criterion, optimizer, ignore_grad=False):
>     ...
>     loss_f, sample_size_f, logging_output_f = criterion(model, sample['forward'])
>     loss_r, sample_size_r, logging_output_r = criterion(model_r, sample['reverse'])
>     ...
> ```
> 
> `loss_r` is , however, computed as `nan`... More precisely tensors were getting more and more `nan` values while computing attentions in decoding process. `TransformerDecoderLayer.self_attn : MultiheadAttention` generates `nan`s...
> 
> Fairseq is too well-packaged so I cannot clearly get all the inter-class dependencies, especially between task and model. Can you give me an advice for dual translation?
> 
> Thank you.

Hello, I am also trying to implement dual translation based on fairseq, do you have any progress on this issue?
