### ISSUE TITLE
Is it possible to get the output of the Transformer/Semi-Supervised Translation encoder

### ISSUE THREAD

**Issue by ajesujoba** [pytorch/fairseq#1392]
I am working on a Semi supervised machine translation(using Transformer) task and it is important I get the output of the topmost encoder to compare and pick the probable language pairs[as I don't parallel pairs already] that is I am doing "Online Parallel pair extraction". Any idea on how to get the encoder outputs Using fairseq?

**Comment by huihuifan** [comment]
the decoder accesses the encoder output to attend over it, so you can access it there
