### ISSUE TITLE
Documentation suggests to build and install cuda kernels twice

### ISSUE THREAD

**Issue by mingruimingrui** [pytorch/fairseq#1395]
In the [Pay Less Attention](https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper) readme, it is suggested to the reader to build and install the cuda kernels for lightconv and dynamic conv twice

```# to install lightconv
cd fairseq/modules/lightconv_layer
python cuda_function_gen.py
python setup.py install

# to install dynamicconv
cd fairseq/modules/dynamicconv_layer
python cuda_function_gen.py
python setup.py install
```

then 

```# to install lightconv
python fairseq/modules/lightconv_layer/cuda_function_gen.py
python fairseq/modules/lightconv_layer/setup.py install

# to install dynamicconv
python fairseq/modules/dynamicconv_layer/cuda_function_gen.py
python fairseq/modules/dynamicconv_layer/setup.py install
```

Could I understand why the cuda kernels have to be built and installed twice?

> I'm not referring to building the 2 libraries separately! I get that bit! https://github.com/pytorch/fairseq/issues/1344

On a side note, wouldn't it be better practice to place the kernels into the [`fairseq/clib`](https://github.com/pytorch/fairseq/tree/master/fairseq/clib) folder and have `setup.py` build everything?

**Comment by GeorgeS2019** [comment]
can someone share how to do the cuda compile in this context in Windows 10?

**Comment by myleott** [comment]
Fixed the documentation issue. Closing this Issue and will resurrect #1405 to discuss how to build the cuda kernels on Windows.
