### ISSUE TITLE
Pretrainig Roberta for a Different Language than English, Using own data 

### ISSUE THREAD

**Issue by ceatlinar** [pytorch/fairseq#1398]
Could someone help me with how to follow this guide https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md to pretrain roberta for Turkish language. I tried a turkish dataset and did all the rest instructions same as in guide but I guess some of the files are English related. So which steps I should skip or maybe add in order to pretrain a model for Turkish language. I am quite new wiith the topic so a clear set of intructions would be great.
Thanks in advance

**Comment by huihuifan** [comment]
The readme provides examples for training your own dataset. If you have specific errors, please post those, this is a bit too vague

**Comment by ceatlinar** [comment]
Hi @huihuifan  you are right. Actually I am going to close the issue with a reference to this #https://github.com/pytorch/fairseq/issues/1417  issue I opened and was answered. I believe it might be helpful for those search for a similar problem.

**Comment by huihuifan** [comment]
Thanks @ceatlinar !
