### ISSUE TITLE
Cannot find callable bart.large.cnn in hubconf

### ISSUE THREAD

**Issue by Colanim** [pytorch/fairseq#1400]
Trying to load CNN/DM finetuned BART from hub :

```python
import torch
bart = torch.hub.load("pytorch/fairseq", "bart.large.cnn")
```

give following error :

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.local/lib/python3.6/site-packages/torch/hub.py", line 361, in load
    entry = _load_entry_from_hubconf(hub_module, model)
  File "/home/me/.local/lib/python3.6/site-packages/torch/hub.py", line 239, in _load_entry_from_hubconf
    raise RuntimeError('Cannot find callable {} in hubconf'.format(model))
**RuntimeError: Cannot find callable bart.large.cnn in hubconf**

---

I believe it's not from my side because I can load `bart.large` and `bart.large.mnli` without problem. Only `bart.large.cnn` does not work.

@ngoyal2707 @yinhanliu

**Comment by Colanim** [comment]
Current workaround is to download the model as described in the [README](https://github.com/pytorch/fairseq/tree/master/examples/bart#load-bart-for-pytorch-10-or-custom-models) :

```
# Download bart.large model
wget https://dl.fbaipublicfiles.com/fairseq/models/bart.large.cnn.tar.gz
tar -xzvf bart.large.cnn.tar.gz

# Load the model in fairseq
from fairseq.models.bart import BARTModel
bart = BARTModel.from_pretrained('/path/to/bart.large.cnn', checkpoint_file='model.pt')
bart.eval()  # disable dropout (or leave in train mode to finetune)
```

**Comment by ngoyal2707** [comment]
hmm that's weird, looking, thanks for reporting and yes, please use the work-around in the meantime.

**Comment by ngoyal2707** [comment]
This seems to be some issue with pytorch hub cache. Can you please delete `~/.cache/torch` and try again? It worked for me with that
