### ISSUE TITLE
Custom best-checkpoint-metric?

### ISSUE THREAD

**Issue by patrickphatnguyen** [pytorch/fairseq#1402]
Hello, I noticed that there's an argument named "best-checkpoint-metric". However, the options (as far as I see) are only accuracy and loss, what if I want to choose f1-score for eval? Thank you!

**Comment by huihuifan** [comment]
Sorry, this is not implemented. Please submit a PR if you would like to add this feature!

**Comment by sajastu** [comment]
Hi @huihuifan,

Any update on this? I want to use RG metrics for picking the best checkpoint in the validation step, but it doesn't seem there's RG implemented to this end. Can I implement it myself or is there any already implemented one?
