### ISSUE TITLE
Fatal error (gradients are inconsistent between workers) on reproducing Levenshtein Transformer, and lower training speed after restoring

### ISSUE THREAD

**Issue by wsdexy** [pytorch/fairseq#1404]
Hi,

I'm trying to reprodce the wmt 14 en-de results of Levenshtein Transformer in the example 'Non-autoregressive Neural Machine Translation (NAT)' with follwing cli-command:
`fairseq-train \
$levt_dir/data-bin/wmt14_en_de_distill \
--save-dir $levt_dir/checkpoints \
--ddp-backend=no_c10d \
--task translation_lev \
--criterion nat_loss \
--arch levenshtein_transformer \
--noise random_delete \
--share-all-embeddings \
--optimizer adam --adam-betas '(0.9,0.98)' \
--lr 0.0005 --lr-scheduler inverse_sqrt \
--min-lr '1e-09' --warmup-updates 10000 \
--warmup-init-lr '1e-07' --label-smoothing 0.1 \
--dropout 0.3 --weight-decay 0.01 \
--decoder-learned-pos \
--encoder-learned-pos \
--apply-bert-init \
--log-format 'simple' --log-interval 1 \
--fixed-validation-seed 7 \
--max-tokens 15800 \
--save-interval-updates 5000 \
--max-update 350000 \
--source-lang en \
--target-lang de \
--fp16 \
--num-workers 4`

the hardware is one machine with 4 Turing GPU(24G memory each).
During training the wps(I assume sub-words per second?) is about 100k/s, and GPU-Util is about 90% with full power consumption (all four of them) , but I got the error at Epoch 12:
`AssertionError: Fatal error: gradients are inconsistent between workers `

then I use this command to restore training:
`fairseq-train \
$levt_dir/data-bin/wmt14_en_de_distill \
--save-dir $levt_dir/checkpoints \
--ddp-backend=no_c10d \
--task translation_lev \
--criterion nat_loss \
--arch levenshtein_transformer \
--noise random_delete \
--share-all-embeddings \
--optimizer adam --adam-betas '(0.9,0.98)' \
--lr 0.0005 --lr-scheduler inverse_sqrt \
--min-lr '1e-09' --warmup-updates 10000 \
--warmup-init-lr '1e-07' --label-smoothing 0.1 \
--dropout 0.3 --weight-decay 0.01 \
--decoder-learned-pos \
--encoder-learned-pos \
--apply-bert-init \
--log-format 'simple' --log-interval 1 \
--fixed-validation-seed 7 \
--max-tokens 15800 \
--save-interval-updates 5000 \
--max-update 350000 \
--source-lang en \
--target-lang de \
--fp16 \
--num-workers 4 \
--restore-file $levt_dir/checkpoints/checkpoint_last.pt`

after resotring, the wps is down to only 10k/s, and GPU-Util in `nvidia-smi` is reported as bellow:
![image](https://user-images.githubusercontent.com/17593203/69234682-b1a68100-0bca-11ea-88ae-f4931103119b.png)
I have to reboot the machine so that wps is back to 100k/s.

But, those problems always happen even before finishing ONE EPOCH after restoring.

Any suggestions?
Thanks.

**Comment by ShunchiZhang** [comment]
How do you resolve it in the end?
