### ISSUE TITLE
Trouble building Light/DynamicConv CUDA kernels on Windows

### ISSUE THREAD

**Issue by GeorgeS2019** [pytorch/fairseq#1405]
I know this is against the conditions for support, some of us are just simply stubborn. 

Having this Tag may just help us gather and share our challenges.

**Comment by GeorgeS2019** [comment]
I like to get feedback who have tried to compile the cuda part in windows

https://github.com/pytorch/fairseq/issues/1395

**Comment by myleott** [comment]
Created the windows label :)

**Comment by GeorgeS2019** [comment]
@myleott 
Can you please check if this is problem specific to Windows platform? I do not have this problem with WSL  (Windows Subsystems Linux; Ubuntu18) within Windows 10.

**Comment by GeorgeS2019** [comment]
@myleott 
This is VERY important for Windows, Cuda for **Pay Less Attention**

For me, it seems this paper, especially the dynamic version, deserves more elaboration so others can evaluate HOW EXACTLY LESS ATTENTION WINS!!!!
https://github.com/pytorch/fairseq/issues/1395#issuecomment-555981905

**Comment by GeorgeS2019** [comment]
Related [issue ](https://github.com/pytorch/fairseq/issues/2996)

**Comment by GeorgeS2019** [comment]
[Relevant issue on CPP/CUDA extension on a window system](https://github.com/pytorch/pytorch/issues/11004)

**Comment by GeorgeS2019** [comment]
@myleott  making progress in getting the CUDA kernels to compile in Windows.
