### ISSUE TITLE
e.g. fairseq-train-script.py install during "pip install --editable ." suggestion please

### ISSUE THREAD

**Issue by GeorgeS2019** [pytorch/fairseq#1409]
I have no problem running 
`pip install --editable .`

![image](https://user-images.githubusercontent.com/49812372/69278416-99426080-0be2-11ea-883d-07ecade0a1f3.png)

However, this leads to non-working e.g. fairseq-train.exe 
Running fairseq-train.exe leads to calling the local source code faireq\fairseq-cli\train.py 
Which then looks for ..\train.py of the fairseq root directory

Using pip install fairseq
only the fairseq-train.exe are installed without the fairseq-train-script.py

Any suggestion?

**Comment by wiany11** [comment]
Can't you run your local source code?

**Comment by GeorgeS2019** [comment]
@wiany11 Yes, I can do python (local) fairseq-generate.py

But I hope to get feedback what I did wrong by doing 
pip install --editable .

Where can I change to get the right  e.g. fairseq-generate.exe  install. Thanks.
