### ISSUE TITLE
Right way to initialize only encoder/decoder weights from a pre-trained model

### ISSUE THREAD

**Issue by lemmonation** [pytorch/fairseq#1410]
I have trained a Transformer model, and I want to initialize a new Transformer model with ONLY the encoder or decoder weights of the old model, and keep its parameters fixed while training. I have tried the following method but it didn't work.

Refers to #1196 , I have tried to add the following codes in the `upgrade_state_dict_named` in the `TransformerEncoder` class:
```
def upgrade_state_dict_named(self, state_dict, name):
        # my codes
        if self.random_init_only_encoder:
            for k in self.state_dict().keys():
                here_key = 'encoder.' + k
                if here_key in state_dict.keys():
                    state_dict[here_key] = self.state_dict()[k]

        """Upgrade a (possibly old) state dict for new versions of fairseq."""
        if isinstance(self.embed_positions, SinusoidalPositionalEmbedding):
            weights_key = '{}.embed_positions.weights'.format(name)
            if weights_key in state_dict:
                del state_dict[weights_key]
            state_dict['{}.embed_positions._float_tensor'.format(name)] = torch.FloatTensor(1)
        for i in range(len(self.layers)):
            # update layer norms
            self.layers[i].upgrade_state_dict_named(state_dict, "{}.layers.{}".format(name, i))

        version_key = '{}.version'.format(name)
        if utils.item(state_dict.get(version_key, torch.Tensor([1]))[0]) < 2:
            # earlier checkpoints did not normalize after the stack of layers
            self.layer_norm = None
            self.normalize = False
            state_dict[version_key] = torch.Tensor([1])

        return state_dict
```
And similar codes are added to the `upgrade_state_dict_named` function in the `TransformerDecoder` class.
And to keep its parameter fixed, I added few lines at the end of the `build_model` function of `TransformerModel` class:
```
 @classmethod
    def build_model(cls, args, task):
        """Origin codes."""
        encoder = cls.build_encoder(args, src_dict, encoder_embed_tokens)
        decoder = cls.build_decoder(args, tgt_dict, decoder_embed_tokens)

        if args.random_init_only_encoder:
            for param in decoder.parameters():
                param.requires_grad = False
        if args.random_init_only_decoder:
            for param in encoder.parameters():
                param.requires_grad = False

        return TransformerModel(encoder, decoder)
```
where random_init_only_encoder/decoder indicates that initialize the encoder/decoder randomly while initialize the other component by the old model.

But the above codes didn't work. The trained model produced random translation results with 0 BLEU score. Therefore I open this issue hoping to find the right way to achieve that.

**Comment by yukiyakiZ** [comment]
Have the same problem. Any help would be appreciated.

**Comment by jppgks** [comment]
I used the method from #705 and modified `trainer.py`:

```python
# self.get_model().load_state_dict(state["model"], strict=True, args=self.args)
self.get_model().encoder = load_pretrained_component_from_model(self.get_model().encoder, filename)
```

**Comment by fenimi** [comment]
Please how can I use both decoder and encoder weights with a new language pair? I'm still a bit confused on how to do this?

**Comment by mahendraphd** [comment]
There is a mismatch in the size of the tensors. How to initialize encoder decoder/decoder weights with pre-trained model, just want to initialize the common weights.  How to do that?
