### ISSUE TITLE
Fine-tuning XLM-R 

### ISSUE THREAD

**Issue by anhnt170489** [pytorch/fairseq#1415]
Excuse me, my question is about how we create the samples of more than 2 sentences while fine-tuning XLM-R, should it be: 
['CLS'] sent1 + sent2 ['SEP'] 
or 
['CLS'] sent1 ['SEP'] sent2 ['SEP']
or
['CLS'] sent 1 ['SEP']['SEP'] sent 2['SEP']

Thank you.

**Comment by myleott** [comment]
It follows the RoBERTa setup, so should be:
```<s> d e f </s> </s> 1 2 3 </s>```

More details are given here: https://github.com/pytorch/fairseq/blob/master/fairseq/models/roberta/hub_interface.py#L36-L62

**Comment by swethathomas** [comment]
Hi! I just wanted to know if  fine tuning XLM-R is similar to finetuning Roberta?
