### ISSUE TITLE
Training roberta on external dataset for NLI task in medical domain. 

### ISSUE THREAD

**Issue by mukta3396** [pytorch/fairseq#1416]
I am trying to use the pre-trained roberta model and train it over a medical dataset for the purpose of NLI.  I tuned the roberta base model with my dataset. How do I proceed with the classification task. I have checkpoint_best.pt file generated at the end of the training process.

For multiNLI we have roberta.predict('mnli',tokens)
What do I have to do in the above case where I have fine-tuned the roberta base model?

**Comment by myleott** [comment]
If you used the `sentence_prediction` task as described in the [README](https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.custom_classification.md#5-run-training), then you can do:
```
from fairseq.models.roberta import RobertaModel
roberta = RobertaModel.from_pretrained('/path/to/checkpoints', checkpoint_file='checkpoint_best.pt')
roberta.predict('sentence_classification_head', tokens)
```

**Comment by mukta3396** [comment]
In the training process described for sentence_prediction, what should the 'sentence_classification_head' be? 
How do I set my own customised tag. I want to do a 3 class classification (NLI on clinical data)

**Comment by myleott** [comment]
`sentence_classification_head` is created automatically by the `sentence_prediction` task: https://github.com/pytorch/fairseq/blob/5349052aae4ec1350822c894fbb6be350dff61a0/fairseq/tasks/sentence_prediction.py#L210-L213
