### ISSUE TITLE
Custom Classification

### ISSUE THREAD

**Issue by mukta3396** [pytorch/fairseq#1419]
In the training process described for sentence_prediction, what should the 'sentence_classification_head' be?
How do I set my own customised tag. I want to do a 3 class classification (NLI on clinical data)

**Comment by myleott** [comment]
You might take a look at the tutorial here: https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.custom_classification.md

You can then try setting `--task sentence_prediction --num-classes 3`. The `sentence_classification_head` is created automatically by the task: https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/sentence_prediction.py#L210-L213
