### ISSUE TITLE
How can  develop a seq2seq + attention generative model with fairseq fastly?

### ISSUE THREAD

**Issue by Deep1994** [pytorch/fairseq#1420]
Hi, I want to use fairseq to develop a generative model which has simple seq2seq + attention architecture, how can I dio it qucikly?

Thanks!

**Comment by myleott** [comment]
Please look at the English-to-German translation example: https://github.com/pytorch/fairseq/tree/master/examples/translation#iwslt14-german-to-english-transformer

It implements a seq2seq + attention Transformer model. You can easily swap out the source and target datasets with custom data.
