### ISSUE TITLE
How to load checkpoint to pretrained roberta

### ISSUE THREAD

**Issue by nrdeshpande97** [pytorch/fairseq#1421]
I pretrained the roberta model for senetence_prediction task and save the checkpoint_best.pt file generated into my drive.
How do I reload this file into roberta model in order to make predictions?
The checkpoints folder is lost when the runtime restarts

**Comment by myleott** [comment]
You'll need to create a new checkpoints directory and copy the dictionary file for the RoBERTa model, as well as your new `checkpoint_best.pt`. Then you can do:
```
from fairseq.models.roberta import RobertaModel
roberta = RobertaModel.from_pretrained('/path/to/checkpoints', checkpoint_file='checkpoint_best.pt')
roberta.eval()
tokens = roberta.encode('Hello world')
roberta.predict('sentence_classification_head', tokens)
```

Please also see the instructions here: https://github.com/pytorch/fairseq/tree/master/examples/roberta#load-roberta-for-pytorch-10-or-custom-models
