### ISSUE TITLE
Can I use the translation functionality for low resource language?

### ISSUE THREAD

**Issue by shreyapandit** [pytorch/fairseq#1422]
I have parallel data available for a low resource language: EN-Latin pairs.

I was wondering if I could use any of the [examples](https://github.com/pytorch/fairseq/tree/master/examples) provided for translation. but re-train them for scratch for a low resource setting? 

Thanks, I am new to firseq and any help would be appreciated.

**Comment by myleott** [comment]
Yes, I recommend starting with the IWSLT example: https://github.com/pytorch/fairseq/tree/master/examples/translation#iwslt14-german-to-english-transformer

You should be able to then modify your data to fit in the same format and train a custom model.
