### ISSUE TITLE
load_archive_file() removes original file

### ISSUE THREAD

**Issue by louismartin** [pytorch/fairseq#1425]
https://github.com/pytorch/fairseq/blob/baa8ce119d56939c751ca81f6d0ddbab6feefb66/fairseq/file_utils.py#L82

I use `file_utils.load_archive_file('my_file.tar.gz')` and the method replace `my_file.tar.gz` by its extracted content as a folder.
This behaviour causes problems because I use this compressed file as an archive for other purposes and it should stay untouched.

Is there a way to change this behaviour?

**Comment by myleott** [comment]
Sure, please submit a PR :) You can either add a kwarg to control removing the resolved_archive_file, or you can infer whether to remove or not based on whether `resolved_archive_file == archive_file`.
