### ISSUE TITLE
The bpe files for RoBERTa

### ISSUE THREAD

**Issue by gpengzhi** [pytorch/fairseq#1432]
In the RoBERTa example, the standard `GPT2` vocabulary files `encoder.json` (https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/encoder.json) and `vocab.bpe` (https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/vocab.bpe) are used. However, these files are different from the vocabulary files `encoder.json` (https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-vocab.json) and `vocab.bpe` (https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-merges.txt) used in `huggingface/transformers`.  The special tokens, such as `<s>`, `<pad>`, ..., are included in their vocabulary files, and these special tokens are not included in the standard `GPT2` vocabulary files. I am wondering why such a difference exists.

Thanks a lot!

**Comment by myleott** [comment]
The fairseq version first encodes with the GPT-2 BPE then with the fairseq dictionary. The latter includes some special symbols, such as <s>, <pad>, etc. I believe the HF version combines these into a single vocabulary.
