### ISSUE TITLE
Possible to reverse engineer BPE (bpecodes)?

### ISSUE THREAD

**Issue by GeorgeS2019** [pytorch/fairseq#1433]
It seems many users here are blocked from further validation and asking for the missing BPE not attached with the provided Pre-trained models [[LightConv Chinese-English](https://github.com/pytorch/fairseq/blob/master/examples/pay_less_attention_paper/README.md)].
- [How to use translation pre-trained model without bpecodes?](https://github.com/pytorch/fairseq/issues/1052#issue-483737037)

**Comment by myleott** [comment]
The BPE codes are now available in a new set of archives with a .tar.gz extension. I've also updated the README with a bunch of additional usage instructions via torch.hub: https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper#example-usage-torchhub

**Comment by GeorgeS2019** [comment]
@myleott  do you have link where e.g. pay_less_attention zh-en model can be exported to ONNX?

**Comment by myleott** [comment]
I don't have any experience with ONNX, so can't help you. What error do you get when you try to export these models? https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper#pre-trained-models
