### ISSUE TITLE
AttributeError: module 'torch.utils.data' has no attribute 'IterableDataset'

### ISSUE THREAD

**Issue by lyjzsyzlt** [pytorch/fairseq#1437]
when i perform script 
```import torch
torch.hub.list('pytorch/fairseq')
```
it apperared the error 'AttributeError: module 'torch.utils.data' has no attribute 'IterableDataset'' in 'fairseq/data/fairseq_dataset.py'

**Comment by damyana79** [comment]
I ran into the same issue today when I installed the newest version of pytorch with anaconda. After I tried a new installation with pip the problem was solved. Maybe you can try it

**Comment by lyjzsyzlt** [comment]
> I ran into the same issue today when I installed the newest version of pytorch with anaconda. After I tried a new installation with pip the problem was solved. Maybe you can try it

it didn't work yet, my torch version is 1.1.0, python version is 3.6, it's too old?

**Comment by damyana79** [comment]
I had the problem with python 3.7 and pytorch 1.3. installed with anaconda. It seems the version distributed there was not fixed. The version distributed with pip was OK.
I found the error message commented on the pytorch github issues:
https://github.com/pytorch/pytorch/issues/27820

It is closed there now and the issue reporter seems to use pytorch 1.2
I think you could try to install a newer pytorch version (1.2 or 1.3) with pip and try with it. If you don't want to uninstall your old version, you could create a new virtual environment and if it works work with it for your current project

**Comment by lematt1991** [comment]
If you are still having problems, you should post an issue in pytorch's repo.

**Comment by jalajthanaki** [comment]
Hi Team,
I'm using fairseq-master and PyTorch 1.5 version and I'm facing the same issue while running interactive.py script for my inference. Did anyone resolved this issue?

**Comment by ManavR123** [comment]
I am also having the same issue and it was working fine just under a month ago

**Comment by genbei** [comment]
I used fairseq0.6.0, and I also encountered this problem

**Comment by shuoyangd** [comment]
I'm experiencing the same problem and for the moment running the script from fairseq root directory works for me. Seems like it's a python import issue.

**Comment by WinnieHAN** [comment]
Try PyTorch 1.6 version. In my machine, it's solved.
