### ISSUE TITLE
Pre-train and fine tuning data sets have slightly different vocabularies. How to co-preprocess?

### ISSUE THREAD

**Issue by galphag** [pytorch/fairseq#144]
Pre-train and fine-tuning data sets have slightly different vocabularies.

I tried the following naive steps. 
1. Preprocess pre-train data
2. Pre-train
3. Preprocess fine tuning data
4. Restore-file
5. RuntimeError: The expected size of the tensor (3252) must match the existing size (2741) at non-singleton dimension 0

I am wondering how to co-preprocess pre-train and fine-tuning data, so that they could share the same vocabulary? For example, may I use preprocess.py to make a merged dictionary, while keeping the pre-trained and fine-tuning data as individual binaries?

**Comment by edunov** [comment]
How exactly do you preprocess these datasets? 

In case of preprocess.py there are --srcdict and --tgtdict options that you need to set for the second dataset, that will force it to re-use dictionaries generated for the first data set.

However, if you also apply BPE encoding, you also need to make sure you share same "code" file for both first and second dataset.

**Comment by gitmcdull** [comment]
Thanks a lot for your prompt reply. --srcdict and --tgtdict do work.

As the fine-tuning vocabulary is bigger than the pre-trained one, the extra words won't be trained in fine-tuning by default. Right? 

Do I have to write some codes to extend the vocabulary so that the extra words in fine-tuning data set can be trained together?

**Comment by edunov** [comment]
right, words that don't exist in the dictionary will be replaced with "unk" tokens. 

Extending vocabulary for an already trained model is not easy. What you can do instead is generate joined dictionary. You'll need to combine both pre-train and fine-tune datasets into one, run preprocess.py on it, get dictionaries for this joined dataset. And then you can run preprocess.py two more times for the pre-train and fine-tune datasets separately, this time with --srcdict and --tgtdict options pointing to the joined dictionaries.  

Of course, all this can be coded in preprocess.py to save time, but it can as well be done manually.
