### ISSUE TITLE
translation from pretrained XLM-R

### ISSUE THREAD

**Issue by mumuchang** [pytorch/fairseq#1440]
Hi, may I ask  is it possible to do XLM-R base finetuning on 16g GPU for translation task? I got CUDA out of memory runtime error when I tried to finetune.

**Comment by lematt1991** [comment]
I would try reducing the batchsize by setting `--max-tokens` to a smaller value.

**Comment by khalafawyy** [comment]
@mumuchang I am curious as to how you fine-tuned XLM-R for translation since it is an encoder-only model.

**Comment by mohammadKhalifa** [comment]
@mumuchang I am curious as to how you fine-tuned XLM-R for translation. I am trying to do something similar.
