### ISSUE TITLE
fairseq-interactive, special characters with whitespace?

### ISSUE THREAD

**Issue by JJumSSu** [pytorch/fairseq#1446]
Hi I'm currently using Fairseq for testing my method. I trained my transformer model with text preprocessed by sentencepiece unigram language model on IWSLT17dataset and achieved good performance.

I'm trying to conduct my experiment on WMT14 EN -> DE, however my generated sentences have special characters with whitespace.

![image](https://user-images.githubusercontent.com/39372342/69931576-2488f380-150b-11ea-8654-57020f2dfc70.png)

so when I run Sacrebleu, the warning message pops up. 

![image](https://user-images.githubusercontent.com/39372342/69931601-3a96b400-150b-11ea-86d1-a6fc3c9bd86a.png)

Is it something wrong with my trained model? or just something wrong with decoding process?

My command for generating "sys" file is as follow:
![image](https://user-images.githubusercontent.com/39372342/69931775-d58f8e00-150b-11ea-840e-a45a1cfef80e.png)

Thank you

**Comment by lematt1991** [comment]
You should use something like moses to tokenize/detokenize your text.  For example:

`<translation-script> | <path-to-moses>/scripts/tokenizer/detokenizer.perl -l de -q > iwslt17.test.en-de.de.sys`
