### ISSUE TITLE
A Question about wmt14-ende test data

### ISSUE THREAD

**Issue by StillKeepTry** [pytorch/fairseq#145]
Hi, I am confused about the test set. When i use the dataset preprocess script to download and tokenize corpus, i find the newstest2014 that this model use contains 3003 sentences. But there also exists another widely used newstest2014 ([the link](https://nlp.stanford.edu/projects/nmt/data/wmt14.en-de/newstest2014.en)), and it contains 2737 sentences. So i want to check the result of ConvS2S is based on which dataset? And will it produce the same result on these different test set.

**Comment by edunov** [comment]
There is indeed two versions of this dataset, the one that comes from Stanford is preprocessed and filtered and the one that comes from WMT is not. In my experience, the difference is very small. 
I believe, in the original ConvS2S paper, Stanford's version was used. But now we use WMT's version to be consistent with other papers.
