### ISSUE TITLE
Train the Non-autoregressive model

### ISSUE THREAD

**Issue by JackHorse** [pytorch/fairseq#1458]
Hi，

If I want train the NAT model as describe  in [Non-Autoregressive Neural Machine Translation (Gu et al., 2017),](https://arxiv.org/abs/1711.02281)，why we don't use "--src-embedding-copy" in the scripts ?

Thank you!

**Comment by lematt1991** [comment]
CC @kahne

**Comment by MultiPath** [comment]
Hi @JackHorse  we did not find it useful as we have more knowledge about how to optimize transformers and it is cleaner compared to other models

**Comment by JackHorse** [comment]
Thank you for your reply ！
