### ISSUE TITLE
How to  define my own model based on the fairseq？where am i supposed to change the code

### ISSUE THREAD

**Issue by hischen** [pytorch/fairseq#1459]
I wanna to define my own translation model, like changing the embedding,architecture,loss based the fairseq. Where  am i supposed to modify the code? thanks

**Comment by lematt1991** [comment]
It depends on the type of change you'd like to make.  If you'd like to to update the number of layers in a transformer for example, there are parameters you can change (`--encoder-layers`/`--decoder-layers`).  Take a look at the docs [here](https://fairseq.readthedocs.io/en/latest/).
