### ISSUE TITLE
How can we choose the different "arch" before training the language models?

### ISSUE THREAD

**Issue by miradel51** [pytorch/fairseq#1460]
I need to train the LM both for source and target side by using single monolingual data of source of target dataset respectively.

The error occurs "AssertionError: cannot specify cutoff larger than vocab size".

Our dictionary size is 16968, the cutoff boundary is ('20000,60000') in the transformer_lm.py file, then we set them ('15000,60000') the error still could not be fixed.

After that, we have chosen the different "--arch" such as "transformer_lm_wiki103", "transformer_lm_big", "transformer_lm_gpt", "base_lm_architecture", "transformer_lm_baevski_gbw", "transformer_lm_baevski_wiki103" and "base_lm_architecture", we have faced various errors.

**Comment by myleott** [comment]
If your vocab is only 16k, then you can't have the cutoff be larger than 16k (yours is 20k-60k). Please lower the cutoff values.

Alternatively you can use a different architecture that doesn't include adaptive inputs. This is a simple one that should work okay:
```
fairseq-train --task language_modeling \
  data-bin/wikitext-103 \
  --save-dir checkpoints/transformer_wikitext-103 \
  --arch transformer_lm --share-decoder-input-output-embed \
  --dropout 0.1 \
  --optimizer adam --adam-betas '(0.9, 0.98)' --weight-decay 0.01 --clip-norm 0.0 \
  --lr 0.0005 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07 \
  --tokens-per-sample 512 --sample-break-mode none \
  --max-tokens 2048 --update-freq 16 \
  --fp16 \
  --max-update 50000
```

**Comment by liiutengbo** [comment]
@myleott  ,hello,  can you achieve the score of wiki-103 dataset 18.7 ppl? There is something wrong with my replication .
