### ISSUE TITLE
Subword Dictionary has no attribute bos_Index

### ISSUE THREAD

**Issue by spprabhu** [pytorch/fairseq#1464]
Hi I am Trying to implement the Levenshtein Transformer ,However I am getting the following error
File "/home/ubuntu/miniconda3/envs/mmt/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/home/ubuntu/fs/fairseq/fairseq_cli/train.py", line 333, in cli_main
    main(args)
  File "/home/ubuntu/fs/fairseq/fairseq_cli/train.py", line 51, in main
    model = task.build_model(args)
  File "/home/ubuntu/fs/fairseq/fairseq/tasks/fairseq_task.py", line 185, in build_model
    return models.build_model(args, self)
  File "/home/ubuntu/fs/fairseq/fairseq/models/__init__.py", line 48, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
  File "/home/ubuntu/fs/fairseq/fairseq/models/transformer.py", line 218, in build_model
    decoder = cls.build_decoder(args, tgt_dict, decoder_embed_tokens)
  File "/home/ubuntu/fs/fairseq/fairseq/models/levenshtein_transformer.py", line 338, in build_decoder
    decoder = LevenshteinTransformerDecoder(args, tgt_dict, embed_tokens)
  File "/home/ubuntu/fs/fairseq/fairseq/models/levenshtein_transformer.py", line 546, in __init__
    self.bos = dictionary.bos()
  File "/home/ubuntu/fs/fairseq/fairseq/data/dictionary.py", line 163, in bos
    return self.bos_index
AttributeError: 'SubwordDictionary' object has no attribute 'bos_index'

What do you make of this and how to solve or circumvent it.

**Comment by lematt1991** [comment]
Can you provide the full command that you used to train

**Comment by spprabhu** [comment]
Sure, THis is the full command
create en it ../../benchmarks/anonymous_en__it/train -e levenshtein --train-steps 1000 --fp16 --ddp-backend=no_c10d          --criterion nat_loss     --arch levenshtein_transformer       --optimizer adam --adam-betas '(0.9,0.98)'     --lr 0.0005 --lr-scheduler inverse_sqrt     --min-lr '1e-09' --warmup-updates 10000     --warmup-init-lr '1e-07' --label-smoothing 0.1     --dropout 0.3 --weight-decay 0.01     --decoder-learned-pos     --encoder-learned-pos     --apply-bert-init     --log-format 'simple' --log-interval 100     --fixed-validation-seed 7     --max-tokens 8000     --save-interval-updates 10000    --train-steps 1000

**Comment by lematt1991** [comment]
CC @kahne

**Comment by spprabhu** [comment]
Sure, THis is the full command
create en it ../../benchmarks/anonymous_en__it/train -e levenshtein --train-steps 1000 --fp16 --ddp-backend=no_c10d --criterion nat_loss --arch levenshtein_transformer --optimizer adam --adam-betas '(0.9,0.98)' --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr '1e-09' --warmup-updates 10000 --warmup-init-lr '1e-07' --label-smoothing 0.1 --dropout 0.3 --weight-decay 0.01 --decoder-learned-pos --encoder-learned-pos --apply-bert-init --log-format 'simple' --log-interval 100 --fixed-validation-seed 7 --max-tokens 8000 --save-interval-updates 10000 --train-steps 1000 @kahne

**Comment by spprabhu** [comment]
Hi Any Updates.

**Comment by kahne** [comment]
Hi @spprabhu ! It seems you defined `SubwordDictionary` but `bos_idx` is not defined. You need to add it to the dictionary in the constructor like how it's done in [`Dictionary`](https://github.com/pytorch/fairseq/blob/master/fairseq/data/dictionary.py#L32).

**Comment by spprabhu** [comment]
Hi @kahne I haven't made any changes I am using the default levenshtien transformer code availiable in fairseq repo and the above issue still persists.

**Comment by spprabhu** [comment]
Can you please pinpoint at the exact line and share the updated code snippet.

**Comment by lematt1991** [comment]
Which version of fairseq are you using?  Can you provide a commit hash?  In the current version of master (commit 742ce49bfcc9b4b6e57ccd5c0d8cf62c40df49fa), `SubwordDictionary` does not exist.

```Bash
[~/fairseq] grep -I -R "SubwordDictionary" *
[~/fairseq] 
```

**Comment by spprabhu** [comment]
Hi I am using Fairseq 0.8.However I am not able to find the commit hash with the command you have sent.

**Comment by lematt1991** [comment]
It looks like v 0.8 corresponds to ffffe04ea12679bdc12fbbafdc6406dd3e6c9943.  I also don't see any occurrences of `SubwordDictionary` anywhere in the repo there.  I'm also confused about the command that you provided:

```
../../benchmarks/anonymous_en__it/train -e levenshtein --train-steps 1000 --fp16 --ddp-backend=no_c10d --criterion nat_loss --arch levenshtein_transformer --optimizer adam --adam-betas '(0.9,0.98)' --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr '1e-09' --warmup-updates 10000 --warmup-init-lr '1e-07' --label-smoothing 0.1 --dropout 0.3 --weight-decay 0.01 --decoder-learned-pos --encoder-learned-pos --apply-bert-init --log-format 'simple' --log-interval 100 --fixed-validation-seed 7 --max-tokens 8000 --save-interval-updates 10000 --train-steps 1000
```
Is `../../benchmarks/anonymous_en__it/train` an alias for `fairseq-train`?  What is `-e` doing?  I don't see this as a flag anywhere either.

**Comment by spprabhu** [comment]
No it's just an address where the dataset is there and yes it's an alias
for training.

**Comment by spprabhu** [comment]
-e is just the name of the engine @lematt1991 @kahne

**Comment by kahne** [comment]
@spprabhu I think you are using a customized version of fairseq (`-e` and `SubwordDictionary ` are not parts of pytorch/fairseq). We need to know what your code is like before we can really help you with debugging.

**Comment by lematt1991** [comment]
Yes, this seems to not be a fairseq issue as `SubwordDictionary` does not belong to fairseq.
