### ISSUE TITLE
Can wav2vec vectors be converted back to audio?

### ISSUE THREAD

**Issue by shamoons** [pytorch/fairseq#1468]
Assuming I train some dataset and get a bunch of vectors, can those vectors then be converted back to audio?

**Comment by lematt1991** [comment]
CC @alexeib

**Comment by caesar-one** [comment]
I'm interested too

**Comment by alexeib** [comment]
i dont think you can do this algorithmically. you can try to train another network that maps wav2vec features -> audio, i would be interested to see whether and how that works. we have not tried it.

**Comment by shamoons** [comment]
I’m happy to give it a shot. Will any data work? Librispeech perhaps?

**Comment by shamoons** [comment]
I wonder if there's a paper in this if I get it to work :-). Or even if I get it to NOT work.

**Comment by alexeib** [comment]
you can certainly try librispeech. many tts models learn logmel -> audio mapping (e.g. tacotron), so that would be a good starting point to look at

**Comment by shamoons** [comment]
I'm trying to work on this and what I've done is create the data set from audio to features (400 samples to 512-dimensional vector). I have the LibriSpeech `train-clean-100` dataset chunked out this way. I'm then applying a few `Conv1d` layers (kernel size of 1) all the way through to 2 linear layers at the end. It's producing some results, but still not clean. I'm wondering what I'm missing to make it really fully restored?

**Comment by yt605155624** [comment]
mark
