### ISSUE TITLE
fairseq-preprocess: command not found

### ISSUE THREAD

**Issue by ceatlinar** [pytorch/fairseq#1472]
I have used 'pip install --editable .' to install fairseq-preprocess and it ends with no error. Yet when I run the command it still gives command not found error. And I can see that the file is under 

> /.local/bin

directory. I dont know why I am getting the error.
Can someone who knows help?

**Comment by GeorgeS2019** [comment]
[FYI](https://github.com/pytorch/fairseq/issues/1409#issue-526219610)

**Comment by lematt1991** [comment]
@ceatlinar are you on windows?

**Comment by ceatlinar** [comment]
Hi. No I am on Google cloud instance, a Linux one. The problem was about the path, I corrected it and therefore closing the issue. Thankss @lematt1991

**Comment by sidsimhadrifromcostco** [comment]
Were you ever able to find a solution for this?
