### ISSUE TITLE
Use additional features in encoder at training and inference time 

### ISSUE THREAD

**Issue by dpanshu** [pytorch/fairseq#1478]
Hi, 

I am trying to run a MT model with providing source tokens and their POS & NER tag info in encoder. 

I have tokenized data in 4 files : 
- Source tokens : My name is XYZ
- POS tokens : PRP NN VB PRP
- NER tokens : O O O B-PERSON
- Target tokens : Je m'appelle XYZ

I would like to feed the first 3 files as input, 

However, cannot find a way for it to be read by fairseq-preprocess, and then readable by any architecture. 

Any pointers are appreciated. 
Thanks.

**Comment by lematt1991** [comment]
Yes, currently there is no support for this, unfortunately.  You could do this by creating a new dataset (following `IndexedRawTextDataset` would probably be easiest.), and then you would also need to modify the collate function inside of [`language_pair_dataset.py`](https://github.com/pytorch/fairseq/blob/master/fairseq/data/language_pair_dataset.py#L12).

**Comment by hokkaido** [comment]
@lematt1991 While this is true, there are currently quite a lot of assumptions in the entire entire code base about what will be passed around and what not. I recently tried to integrate additional tokens, a pointer generator mechanism and so on and found a lot of places where it just breaks down. For instance, in interactive.py you restrict the sample properties before passing it to the inference step.
