### ISSUE TITLE
How to preprocess when only having source test data?

### ISSUE THREAD

**Issue by Nickeilf** [pytorch/fairseq#1480]
What is the best practice when I have both src-tgt data for training and validation set but only the source test data?

I tried preprocess the train+valid first and then preprocess test set with **only-source** flag. But during test time, when I run generate.py the test set cannot be found (since no tgt data provided).

`FileNotFoundError: Dataset not found: test (data-bin)`

Maybe interactive.py instead?

**Comment by lematt1991** [comment]
Yes, you should do `interactive.py` instead.

**Comment by ManavR123** [comment]
I don't think this is an ideal solution, but I found that you can generate a dummy target file and use that instead. You will get really bad Bleu scores but the model shouldn't change as long as you aren't fine-tuning with that dummy data
