### ISSUE TITLE
NCCL error when using DynamicConv Models

### ISSUE THREAD

**Issue by Meso272** [pytorch/fairseq#1482]
I’m trying to do train with the DynamicConv models, and errors occured when I run the following command as the instruction in https://github.com/pytorch/fairseq/blob/master/examples/pay_less_attention_paper/README.md:
python -m torch.distributed.launch --nproc_per_node 4 $(which fairseq-train) \
    data-bin/wmt16_en_de_bpe32k  --log-interval 100 --no-progress-bar \
    --max-update 30000 --share-all-embeddings --optimizer adam \
    --adam-betas '(0.9, 0.98)' --clip-norm 0.0 --weight-decay 0.0 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --min-lr 1e-09 --update-freq 16 --attention-dropout 0.1 --keep-last-epochs 10 \
    --ddp-backend=no_c10d --max-tokens 3584 \
    --lr-scheduler cosine --warmup-init-lr 1e-7 --warmup-updates 10000 \
    --lr-shrink 1 --max-lr 0.001 --lr 1e-7 --min-lr 1e-9 --warmup-init-lr 1e-07 \
    --t-mult 1 --lr-period-updates 20000 \
    --arch lightconv_wmt_en_de_big --save-dir $SAVE \
    --dropout 0.3 --attention-dropout 0.1 --weight-dropout 0.1 \
    --encoder-glu 1 --decoder-glu 1 

The errors includes:
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/../c10d/NCCLUtils.hpp:48, invalid argument

and

RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:400, unhandled system error

My machine has 4 TESLA P100 GPUs, and is with CUDA10.1 and NCCL 2.5.6. I've installed the Memory-Efficient CUDA Kernels provided by yours. So, I have the following questions:

1. Why did these errors occur?
2. What does the parameter --nproc_per_node mean in the command? In the instruction to train on a machine with 8 GPUS, the value of it is given as 8, so is it right to change it to 4 for my 4 GPUs machine?
3. I do not know how to test if the program works on single GPU.

Supplement:
After adding the --distributed-no-spawn parameter, the command works on one of my machine. But when I tested on another machine, another error occured:
The subprocess ....... died with <Signals.SIGSEGV: 11>.
I'd like to know how to deal with this error.

**Comment by myleott** [comment]
Please test on a single GPU first. You can do that with the `CUDA_VISIBLE_DEVICES` environment variable, which specifies a comma-separated list of GPU ids to use:

So to train on GPU #0:
```
CUDA_VISIBLE_DEVICES=0 fairseq-train (...)
```

Also, on a single node there's no need for torch.distributed.launch. By default fairseq will use all visible GPUs on the system.

**Comment by Meso272** [comment]
> Please test on a single GPU first. You can do that with the `CUDA_VISIBLE_DEVICES` environment variable, which specifies a comma-separated list of GPU ids to use:
> 
> So to train on GPU #0:
> 
> ```
> CUDA_VISIBLE_DEVICES=0 fairseq-train (...)
> ```
> 
> Also, on a single node there's no need for torch.distributed.launch. By default fairseq will use all visible GPUs on the system.

Thanks for your reply. Now the situation is that the multi-GPU training with one node can work on one of my machines, but the subprocesses died with SIGSEGV on another machine.
I'd like to figure out what can cause SIGSEGV in training. Is it relevant to the environment configuration?

**Comment by myleott** [comment]
If it's working for you on one machine but not another, then it's probably an environment/configuration issue on your machine. In general we can only help resolve issues that are directly related to fairseq. Please try reinstalling NCCL/PyTorch and see if that helps.
