### ISSUE TITLE
Inconsistency in returned inner_states between TransformerEncoder and Decoder

### ISSUE THREAD

**Issue by astariul** [pytorch/fairseq#1483]
In the implementation of Transformer, I'm having trouble understanding why the encoder last layer state is updated after layer normalization :

https://github.com/pytorch/fairseq/blob/4c0d432ec74e0737c5132cde18182ce3f94599c0/fairseq/models/transformer.py#L410-L413

But in the case of the decoder, the layer normalization is not saved in the last layer state :

https://github.com/pytorch/fairseq/blob/4c0d432ec74e0737c5132cde18182ce3f94599c0/fairseq/models/transformer.py#L699-L700 

As far as I understood, following line should be added to have consistent behavior with encoder :
```
inner_states[-1] = x
```

**Comment by Colanim** [comment]
Another inconsistency between decoder and encoder is the inner states. In encoder, inner states does not include embeddings but in decoder those are grouped together.
