### ISSUE TITLE
Return attention in TransformerEncoderLayer

### ISSUE THREAD

**Issue by astariul** [pytorch/fairseq#1484]
In Transformer **decoder**, attention is computed and returned, allowing user to access it later :

https://github.com/pytorch/fairseq/blob/828c1ca7522278aa6c1eaf91fe0425b8f40dd832/fairseq/modules/transformer_layer.py#L239

However in Transformer **encoder**, attention is ignored :

https://github.com/pytorch/fairseq/blob/828c1ca7522278aa6c1eaf91fe0425b8f40dd832/fairseq/modules/transformer_layer.py#L95

Therefore we cannot access it later.

---

**Is there any reason why encoder's attention is not returned ?**  
I think it would be possible to add `encoder_attn` to :

https://github.com/pytorch/fairseq/blob/4c0d432ec74e0737c5132cde18182ce3f94599c0/fairseq/models/transformer.py#L298-L303

**Comment by Colanim** [comment]
Maybe related to #1339 ?

**Comment by myleott** [comment]
Generally we avoid computing or storing variables unless they are needed, it saves memory as well. Please feel free to submit a PR.

**Comment by myleott** [comment]
Related to #1531
