### ISSUE TITLE
Return self-attention in TransformerDecoderLayer

### ISSUE THREAD

**Issue by astariul** [pytorch/fairseq#1485]
From the `forward` pass of the Transformer Decoder Layer :

https://github.com/pytorch/fairseq/blob/828c1ca7522278aa6c1eaf91fe0425b8f40dd832/fairseq/modules/transformer_layer.py#L188-L293

`attn` is used to store self-attention as well as encoder-attention. `attn` is over-written by encoder-attention, so only the encoder-attention is returned (self-attention seems to be lost ?).

**How can I access the self-attention of Transformer Decoder ?**

**Comment by myleott** [comment]
Yep, it'd be better to expose both, please feel free to submit a PR!

**Comment by myleott** [comment]
Related to #1531
