### ISSUE TITLE
Dimensions for WAV2VEC for downstream tasks

### ISSUE THREAD

**Issue by happypanda5** [pytorch/fairseq#1486]
Please help me with the output dimensions for wav2vec. 

For **0.5 second** of audio, the output dimensions are **[1x512x48]**
For **1 second** of audio, the output dimensions are **[1x512x98]**
For **2 second** of audio, the output dimensions are **[1x512x198]**
For **3 second** of audio, the output dimensions are **[1x512x298]**

**Am I correct to say that the stride length of features is approx. 10ms?**

Can we increase the stride length? say, we get a [1x512] vector every second?

**Comment by JinmingZhao** [comment]
@myleott   how to use the wav2vec for downstream tasks, such as emotion recognition, speaker recognition?

Thank you very much!
