### ISSUE TITLE
broken xlmr.large.tar.gz file

### ISSUE THREAD

**Issue by rlebret** [pytorch/fairseq#1487]
Hi,

It seems that there is a problem with the new XLM-R large archive available from: https://dl.fbaipublicfiles.com/fairseq/models/xlmr.large.tar.gz
It returns a file of size 1.1GB and there is a gzip error when uncompressing the file. 

Best,
Rémi

**Comment by stefan-it** [comment]
I could extract it with `tar -xf xlmr.large.tar.gz`, so the `.gz` extension is a bit misleading 😅

**Comment by myleott** [comment]
@ngoyal2707

**Comment by ngoyal2707** [comment]
Thanks for flagging, sorry about the wrong format. It's fixed now.

**Comment by rlebret** [comment]
Thanks for the update.
Out of curiosity, how do you explain that xlmr.large.v0 model size was 5.3GB while xlmr.large.v1 is now 1.1GB? In the meantime, the size of xlmr.base remains the same (2.6GB).

**Comment by myleott** [comment]
This was because the v0 checkpoints mistakenly included the optimizer state, which tripled the file size. Similarly the xlmr.base release also had optimizer states, which we've now removed.
