### ISSUE TITLE
Could you give me your en-de's train set and  valid set?

### ISSUE THREAD

**Issue by travel-go** [pytorch/fairseq#149]
Hello,I want to reproduce your en-de's result .but I find your valid set is split from train set.
Could you give me your en-de's train set and valid set.
Thank you for your reply.

**Comment by myleott** [comment]
This script will split the train and valid set for you: https://github.com/pytorch/fairseq/blob/master/data/prepare-wmt14en2de.sh.

**Comment by travel-go** [comment]
Thank you for your reply!
