### ISSUE TITLE
question about distributed_utils.all_gather_list

### ISSUE THREAD

**Issue by chynphh** [pytorch/fairseq#1491]
In function `distributed_utils.all_gather_list(data, group, max_size)` , why `assert max_size < 255*256
`？
If this is necessary, is there any way for me to use a larger size of logging_output ?

**Comment by myleott** [comment]
Interestingly enough someone just submitted a change that generalizes this :) It should be merged soon.

**Comment by chynphh** [comment]
@myleott  any link of this submitted change?
By the way，Is it possible to use BLEU as the validation metric in the future?

**Comment by myleott** [comment]
https://github.com/pytorch/fairseq/pull/1499/files#diff-cc468b704bc1fc2e0ae7ee926e2c289b

**Comment by myleott** [comment]
Merged here: https://github.com/pytorch/fairseq/commit/29d7182447c4120057c116eb22c06d1d909eb3a1

**Comment by chynphh** [comment]
thanks.
