### ISSUE TITLE
Error when running Fairseq generate on Trained Levenshtien Model

### ISSUE THREAD

**Issue by spprabhu** [pytorch/fairseq#1492]
| [en] dictionary: 39840 types
| [de] dictionary: 39840 types
| loaded 3003 examples from: data-bin/wmt17_en_de_distill/test.en-de.en
| loaded 3003 examples from: data-bin/wmt17_en_de_distill/test.en-de.de
| data-bin/wmt17_en_de_distill test en-de 3003 examples
| loading model(s) from checkpoints/checkpoint_1_2000.pt
  0%|                                                                                                                                         | 0/12 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/fairseq-generate", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')()
  File "/home/ubuntu/fairseq/fairseq_cli/generate.py", line 199, in cli_main
    main(args)
  File "/home/ubuntu/fairseq/fairseq_cli/generate.py", line 104, in main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/home/ubuntu/fairseq/fairseq/tasks/fairseq_task.py", line 265, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/fairseq/fairseq/sequence_generator.py", line 113, in generate
    return self._generate(model, sample, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/fairseq/fairseq/sequence_generator.py", line 295, in _generate
    tokens[:, :step + 1], encoder_outs, temperature=self.temperature,
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/fairseq/fairseq/sequence_generator.py", line 553, in forward_decoder
    temperature=temperature,
  File "/home/ubuntu/fairseq/fairseq/sequence_generator.py", line 584, in _decode_one
    tokens, encoder_out=encoder_out, incremental_state=self.incremental_states[model],
  File "/home/ubuntu/fairseq/fairseq/models/nat/levenshtein_transformer.py", line 405, in forward_decoder
    output_tokens = decoder_out.output_tokens
AttributeError: 'Tensor' object has no attribute 'output_tokens'

**Comment by spprabhu** [comment]
I am using a Distill dataset

**Comment by myleott** [comment]
What command did you use for generation?

**Comment by spprabhu** [comment]
I used the same command mentioned as it is
fairseq-generate data-bin/wmt17_en_de_distill --path checkpoints/checkpoint_10_200000.pt --beam 1 --remove-bpe.

However I am using Fairseq 0.9

**Comment by spprabhu** [comment]
Getting the same error with fairseq 0.8


loading model(s) from checkpoints/checkpoint_10_160000.pt
  0%|                                                                                                                                         | 0/12 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/fairseq-generate", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')()
  File "/home/ubuntu/fs/fairseq/fairseq_cli/generate.py", line 199, in cli_main
    main(args)
  File "/home/ubuntu/fs/fairseq/fairseq_cli/generate.py", line 104, in main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/home/ubuntu/fs/fairseq/fairseq/tasks/fairseq_task.py", line 265, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/fs/fairseq/fairseq/sequence_generator.py", line 113, in generate
    return self._generate(model, sample, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/fs/fairseq/fairseq/sequence_generator.py", line 295, in _generate
    tokens[:, :step + 1], encoder_outs, temperature=self.temperature,
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/fs/fairseq/fairseq/sequence_generator.py", line 553, in forward_decoder
    temperature=temperature,
  File "/home/ubuntu/fs/fairseq/fairseq/sequence_generator.py", line 584, in _decode_one
    tokens, encoder_out=encoder_out, incremental_state=self.incremental_states[model],
  File "/home/ubuntu/fs/fairseq/fairseq/models/levenshtein_transformer.py", line 414, in forward_decoder
    output_tokens = decoder_out.output_tokens
AttributeError: 'Tensor' object has no attribute 'output_tokens'

**Comment by spprabhu** [comment]
Trained the same command just changed the checkpoint

**Comment by spprabhu** [comment]
I am using Torch 1.3.1

**Comment by spprabhu** [comment]
The error starts in grad_mode in torch from here

  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/fs/fairseq/fairseq/sequence_generator.py", line 113, in generate
    return self._generate(model, sample, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/fs/fairseq/fairseq/sequence_generator.py", line 295, in _generate
    tokens[:, :step + 1], encoder_outs, temperature=self.temperature,
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)

**Comment by spprabhu** [comment]
Getting the same error on Insertion Transformer Model as well.
Using the same Distilled Dataset and pytorch 1.3.1  and Fairseq 0.9 and python 3.7

 [en] dictionary: 39840 types
| [de] dictionary: 39840 types
| loaded 3003 examples from: data-bin/wmt17_en_de_distill/test.en-de.en
| loaded 3003 examples from: data-bin/wmt17_en_de_distill/test.en-de.de
| data-bin/wmt17_en_de_distill test en-de 3003 examples
| loading model(s) from checkpoints/it/checkpoint_best.pt
  0%|                                                                                                                                         | 0/12 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/fairseq-generate", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')()
  File "/home/ubuntu/fairseq/fairseq_cli/generate.py", line 199, in cli_main
    main(args)
  File "/home/ubuntu/fairseq/fairseq_cli/generate.py", line 104, in main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/home/ubuntu/fairseq/fairseq/tasks/fairseq_task.py", line 265, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/fairseq/fairseq/sequence_generator.py", line 113, in generate
    return self._generate(model, sample, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/fairseq/fairseq/sequence_generator.py", line 295, in _generate
    tokens[:, :step + 1], encoder_outs, temperature=self.temperature,
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/fairseq/fairseq/sequence_generator.py", line 553, in forward_decoder
    temperature=temperature,
  File "/home/ubuntu/fairseq/fairseq/sequence_generator.py", line 584, in _decode_one
    tokens, encoder_out=encoder_out, incremental_state=self.incremental_states[model],
  File "/home/ubuntu/fairseq/fairseq/models/nat/insertion_transformer.py", line 175, in forward_decoder
    output_tokens = decoder_out.output_tokens
AttributeError: 'Tensor' object has no attribute 'output_tokens'

**Comment by myleott** [comment]
For Levenshtein Transformer don't you need to pass `--task translation_lev`? See here: https://github.com/pytorch/fairseq/tree/master/examples/nonautoregressive_translation#translate

**Comment by spprabhu** [comment]
Thanks.

Here are my results.SInce It was giving overloading error I had to train it with FP-16.
I am using single V100 GPU.

 Translated 3003 sentences (84362 tokens) in 10.6s (284.14 sentences/s, 7982.36 tokens/s)                                                                          
| Generate test with beam=1: BLEU4 = 23.87, 56.5/29.9/17.7/10.9 (BP=1.000, ratio=1.000, syslen=64537, reflen=64506).

Any Reasons for BLEU Score not matching.My Training stoppped at 250000. (i GUESS ITS BECAUSE OF FP-16 AND LITTLE LESS STEPS 250K)
I am just using WMT 17 En-De Dataset for training.I am not using the Teacher Rescore.

Also should I use WMT14 ( Both Distilled and Base) to achieve same results.

Also can you share ideal Hyperparameter values for training both on single and 8 V100 GPUs.
What is the max token size that should I apply when using Single GPU so that I don't face overloading issues.

**Comment by spprabhu** [comment]
Thanks.

Here are my results.SInce It was giving overloading error I had to train it with FP-16.
I am using single V100 GPU.

Translated 3003 sentences (84362 tokens) in 10.6s (284.14 sentences/s, 7982.36 tokens/s)
| Generate test with beam=1: BLEU4 = 23.87, 56.5/29.9/17.7/10.9 (BP=1.000, ratio=1.000, syslen=64537, reflen=64506).

Any Reasons for BLEU Score not matching.My Training stoppped at 250000. (i GUESS ITS BECAUSE OF FP-16 AND LITTLE LESS STEPS 250K)
I am just using WMT 17 En-De Dataset for training.I am not using the Teacher Rescore.

Also should I use WMT14 ( Both Distilled and Base) to achieve same results.

Also can you share ideal Hyperparameter values for training both on single and 8 V100 GPUs.
What is the max token size that should I apply when using Single GPU so that I don't face overloading issues. @myleott @kahne

**Comment by spprabhu** [comment]
Also which algorithm should I use for WMT En-De KNowledge Distillation.
1.Alexander Rush and Kim or any other.

If you already have WMT14 En-De Distilled Dataset can you please share that.

The Distilled dataset in fairseq availiable for download is WMT17.
@myleott @kahne

**Comment by MultiPath** [comment]
@spprabhu  The distilled datasets are already in the example https://github.com/pytorch/fairseq/tree/master/examples/nonautoregressive_translation

The distillation is done by running beam-search on the training data.

**Comment by MultiPath** [comment]
@spprabhu  Can you share your training and decoding command?

**Comment by spprabhu** [comment]
@MultiPath 
Its the distilled dataset for WMT17 right.I am currently using the same for training.
If I am not wrong I will need to use Plain version of WMT 17 so that they both share the same voacabulary.If I use WMT 16 or 14 results are gonna differ.

**Comment by spprabhu** [comment]
Here is my training and decoding command.I am just using WMT17 Distilled Dataset which is there in downloads.The thing is I am using the Distilled Dataset as well as fp-16 since without fp-16 on single GPU there is issue of overloading.Kindly please suggest the apt max Token size for use on SIngle as well as 8 GPU.

/fairseq$ fairseq-train     data-bin/wmt17_en_de_distill     --save-dir checkpoints     --ddp-backend=no_c10d     --task translation_lev     --criterion nat_loss     --arch insertion_transformer     --noise random_delete     --share-all-embeddings     --optimizer adam --adam-betas '(0.9,0.98)'     --lr 0.0005 --lr-scheduler inverse_sqrt     --min-lr '1e-09' --warmup-updates 10000     --warmup-init-lr '1e-07' --label-smoothing 0.1     --dropout 0.3 --weight-decay 0.01     --decoder-learned-pos     --encoder-learned-pos     --apply-bert-init     --log-format 'simple' --log-interval 100     --fixed-validation-seed 7     --max-tokens 8000     --save-interval-updates 10000  --fp16


Generation Command
fairseq-generate     data-bin/wmt17_en_de_distill     --gen-subset test     --task translation_lev     --path checkpoints/checkpoint_best.pt     --iter-decode-max-iter 9     --iter-decode-eos-penalty 0     --beam 1 --remove-bpe     --print-step .
@myleott @MultiPath @kahne

**Comment by spprabhu** [comment]
Also what is the ideal number of workers that should I use when binarizing the dataset

**Comment by spprabhu** [comment]
Also which command should I use for Binarizing the Dataset.
Currently I am using Eng-de WMT14.
Should I use the WMT16 Script used in Scaling NMT.

**Comment by spprabhu** [comment]
Can you share the exact script for binarization.I have downloaded both the preprocessed datasets

**Comment by spprabhu** [comment]
This are the commands that I have used for Binarization:

fairseq-preprocess --source-lang en --target-lang de     --trainpref $TEXT/train.en-de --validpref $TEXT/valid.en-de     --joined-dictionary     --destdir data-bin/dis    --workers 20 --joined-dictionary

I hope I haven't Forgotten to add any hyperparameter.

I am going to train this 2 new Binarized datasets with above mentioned Training command in previous message.

If I need to make any changes ,please do say.

**Comment by spprabhu** [comment]
Also can anyone tell how to use the 
1. Weight sharing
2. Early Exit
3.Roll on 
Policy of levenshtien Transformer.

Is it already availiable or will it need changes in code .If already present what should I do.
@myleott @MultiPath @kahne

**Comment by spprabhu** [comment]
Sorry Its Rollin POlicy

**Comment by spprabhu** [comment]
Has anyone tried using the Scale NMT papers autoregressive weights as Teacher Rescorer.What were the results when used in Levenshtien.Did it further improve the accuracy.
@myleott @MultiPath @kahne

**Comment by MultiPath** [comment]
> @MultiPath
> Its the distilled dataset for WMT17 right.I am currently using the same for training.
> If I am not wrong I will need to use Plain version of WMT 17 so that they both share the same voacabulary.If I use WMT 16 or 14 results are gonna differ.

Hi, @spprabhu  I don't understand what you are talking about. What do you mean WMT17 or 16 or 14? I think the dataset provided in the example are WMT14.

> Here is my training and decoding command.I am just using WMT17 Distilled Dataset which is there in downloads.The thing is I am using the Distilled Dataset as well as fp-16 since without fp-16 on single GPU there is issue of overloading.Kindly please suggest the apt max Token size for use on SIngle as well as 8 GPU.

To achieve the best performance, you need a larger batch-size. So either you need to run it on 8 GPUs or you should use something like ``--update-freq 8``


> Also what is the ideal number of workers that should I use when binarizing the dataset

The number of workers in binarizing does not matter. It only affects the binarizing speed.


> * Weight sharing
There are commands of  ``--no-share-discriminator``, ``--no-share-maskpredictor``, ``--share-discriminator-maskpredictor`` in the model. 
Here, "discriminator" means "the pass for deleting words", and "maskpredictor" means "the pass for inserting placeholders". **Please read the code first.**

> * Early Exit
There is a command named ``--early-exit`` and in default it is "6,6,6". **Please read the code first.**

>   3.Roll-in policy 
I don't understand what you are referring to. The current code does not contain post-editing yet.


> Has anyone tried using the Scale NMT papers autoregressive weights as Teacher Rescorer.What were the results when used in Levenshtien.Did it further improve the accuracy.
I tried the winner system of WMT19 on En-De before and the answer is NO. 
If the teacher gets too strong, the performance will get worse. We also analyze the effects of distillation in https://arxiv.org/abs/1911.02727

Best,

**Comment by spprabhu** [comment]
So should I use the default command mentioned for levenshtien on 8 GPUs ,will it give me desired result.

ALso Should I trained my Distilled Dataset with Base Transformer to gain those checkpoints.or Should I train my Distilled Dataset with any other model.
@myleott @MultiPath @kahne

**Comment by spprabhu** [comment]
If I am not wrong have to use this command when using the teacher rescorer  right

fairseq-generate \
    data-bin/wmt14_en_de_distill \
    --gen-subset test \
    --task translation_lev \
    --path checkpoints/checkpoint_best.pt:at_checkpoints/checkpoint_best.pt \
    --iter-decode-max-iter 9 \
    --iter-decode-eos-penalty 0 \
    --iter-decode-with-beam 9 \
    --iter-decode-with-external-reranker \
    --beam 1 --remove-bpe \
    --print-step \
    --batch-size 100

**Comment by spprabhu** [comment]
So according to paper .
We train both models on wmt14 ( Levenshtien and Base) and then just use the checkpoints of base during generate command for Levenshtien.

I don't understand the need here for Distilled dataset.

**Comment by spprabhu** [comment]
If I use WMT14 for levenshtien I will need AR model of Base Transformer for checkpoints.SInce Vaswani used WMT14.
If I use WMT17 for levenshtien I will need AR model of Base Transformer for checkpoints trained on WMT17.

Similarly for WMT16 and others .
Is that Correct.

Again what is the need for Distilled Dataset then.
@myleott @MultiPath @kahne

**Comment by spprabhu** [comment]
Ok Finally Got it.
We use checkpoints of both Base Transformer and Levenshtien But use Distilled Dataset of Base.

I wish the Readme file could have stated it explicitly.
Also Different versions of Datasets for Download to original and Distill make it more confusing.
@myleott @MultiPath @kahne

**Comment by spprabhu** [comment]
So practically we need to train 2 models with same original dataset and use Distillation on one where we used Base Transformer.Phew....
@myleott @MultiPath @kahne

**Comment by spprabhu** [comment]
Hey can you please suggest appropriate hyperparameters for training on 4 GPUs,with both normal and FP-16 Version.

Also what would be the parameters if I am using SIngle GPU and FP-16 to achieve same accuracy,should they be same as Base or should they be changed.

**Comment by spprabhu** [comment]
Hey can you please suggest appropriate hyperparameters for training on 4 GPUs,with both normal and FP-16 Version.

Also what would be the parameters if I am using SIngle GPU and FP-16 to achieve same accuracy,should they be same as Base or should they be changed.
@myleott @MultiPath @kahne

**Comment by myleott** [comment]
Please open a separate Issue for each distinct question, following the new Issue templates. Closing for now.
