### ISSUE TITLE
mask current time step

### ISSUE THREAD

**Issue by ehsan-soe** [pytorch/fairseq#1495]

**Comment by ehsan-soe** [comment]
I just realized that in the ```SingleHeadAttention``` the current time step is also masked (unlike attention paper where only future times are masked)
This will lead to mask being 0 everywhere and filled by ```-inf```. And the ```softmax``` would be ```nan```.
Doesn't this problematic?

**Comment by huihuifan** [comment]
For the stories paper, we always used self-attention with the zero vector as well, so if the model did not want to attend to any timesteps it would attend to the zero vector.
