### ISSUE TITLE
Train model for specific translation like Spanish to Russian...

### ISSUE THREAD

**Issue by amiya-mandal** [pytorch/fairseq#1498]
hi,
I have successfully replicate the translation model for en->fn and en->de, working great. But now want to create costume model like es->ru. I came across one thing that model are dedicate to specific language pair like  En-De (lightconv_wmt_en_de_big) or En-Fr (lightconv_wmt_en_fr_big) or vice-versa.
So if i want es-ru translation model so what should I follow cause I cant able to find any docs, after data processing.
And lightconv have
- lightconv
- lightconv_iwslt_de_en
- lightconv_wmt_en_de
- lightconv_wmt_en_de_big
- lightconv_wmt_en_fr_big
- lightconv_wmt_zh_en_big
- lightconv_lm
- lightconv_lm_gbw

So dedicated model are optimize for some language pair.
so what model should i use for translation for es->ru

**Comment by lematt1991** [comment]
i don't know that any of us have experimented with this language pair.  You'll need to try for yourself and see what works best.

**Comment by amiya-mandal** [comment]
hi @lematt1991,
let's take an example 
is there any difference between lightconv_iwslt_de_en, lightconv and lightconv_wmt_en_de in their architecture ??

**Comment by liiutengbo** [comment]
Is there a standard configuration for language model for transformer_lm_wiki103,the official config can not replicate the result 18.7,but I can use the model to inference,and get the score.And my parameters num is 247.2M, but the offical model is 246.9M.
