### ISSUE TITLE
XLM-R License 

### ISSUE THREAD

**Issue by ikergarcia1996** [pytorch/fairseq#1507]
XLM-R model has been released in different repositories (fairseq, Pytext and XLM) each one with a different license (MIT, BSD and Attribution-NonCommercial 4.0). The license in this repository says: "fairseq(-py) is MIT-licensed. **The license applies to the pre-trained models as well**". Does this also applies to the XLM-R model and weights?

Thanks!

**Comment by myleott** [comment]
I can't speak to the other repositories, but yes the MIT license applies for all fairseq code + models.
