### ISSUE TITLE
BART Summary length

### ISSUE THREAD

**Issue by jmamou** [pytorch/fairseq#1513]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
Hi
I am trying to play with the length of the generated summary. It seems that there are several parameters relevant to the length in bart.sample(): min_len, max_len_a, max_len_b.
Am I correct?
I have played with different values max_len_a, but I get the same summary for different values of max_len_a.
Thanks

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
As you note there are three flags: min_len, max_len_a and max_len_b. The final output size will be constrained by these:
```
min_len <= output_len <= (max_len_a * input_len) + max_len_b
```

The default value for `max_len_b` is 200, so you probably want to increase that. You can also increase `min_len` if you want to force the model to generate longer outputs.

Finally you can try adjust `lenpen`. Values > 1 encourage the model to produce longer outputs, so you can try `lenpen=1.5`.
