### ISSUE TITLE
How to evaluate RACE dataset

### ISSUE THREAD

**Issue by 644943** [pytorch/fairseq#1534]
Please tell me the way to evaluate RACE dataset

**Comment by myleott** [comment]
There are a few options:
* During training you can set `--valid-subset valid,test,test1` and it will print results for valid, test and test1 during training.
* Alternatively you can use `fairseq-validate` to evaluate an existing finetuned model on a new dataset:
```
fairseq-validate RACE-mmap2-bin \
  --valid-subset test \
  --task sentence_ranking \
  --path checkpoint_best.pt \
  --max-sentences 1
```
You can also pass the `--save-predictions` option to save the predictions to a file.
