### ISSUE TITLE
Add lexical constraints in decoding

### ISSUE THREAD

**Issue by erip** [pytorch/fairseq#1536]
### Motivation

Guiding decoding toward certain outputs in seq2seq tasks is particularly desireable in some use cases (e.g., standardizing translations or text rewriting); this feature is currently unavailable in fairseq.

### Pitch

The ability to provide an optional glossary which indicates a desireable target given a source token to `fairseq-generate` which would then be used in decoding would fill this gap. 

### Alternatives

N/A

### Additional context

See [this paper](https://arxiv.org/abs/1804.06609) for the implementation details; Sockeye currently implements this algorithm [docs](https://awslabs.github.io/sockeye/inference.html#lexical-constraints). h/t @mjpost

**Comment by erip** [comment]
This might be a better issue for `pytorch_translate`, but thought I might include it here. Let me know if it should move!

**Comment by hadyelsahar** [comment]
+1 for this, I have previously Implemented using Faireseq a hacky version of Matt Post's constraint decoding above. I will be willing to help implementing this. 

Some questions:
- What would be the best way to provide those constraints. in sockeye they provide them tab separated in the input file . Should we keep that?

- shall i keep asking questions here if needed?

**Comment by erip** [comment]
@hadyelsahar I think asking questions here is super reasonable. My 2cc is that a global constraints file (e.g., a glossary/termbase) would be a great way to provide the constraints as some simple file type -- TSV? CSV?

The way I envision this happening is...

A user has source and target files for train, validation, and test. `fairseq-preprocess` will train BPE -- once BPE has been trained, this could be applied to a user's provided  constraints file (and should happen if `--lexical-constraints` is provided). The train, valid, test, dicts, and constraints would then appear in the `dest_dir`. 

@myleott @mjpost does this seem reasonable?

**Comment by hadyelsahar** [comment]
> My 2cc is that a global constraints file (e.g., a glossary/termbase) would be a great way to provide the constraints as some simple file type -- TSV? CSV?

For simplification I opt more to fwd the prob processing the termbase to the user and ask the user to directly provide list of phrases to appear for each test example in a tsv file. Like this we can handle more scenarios than MT where there isn't  a direct word alignment between inputs and outputs. LM & Img captioning for example.  

Given that we will handle only "phrases to appear" type constraints. I am happy with the rest of the proposal.

**Comment by myleott** [comment]
Merged in bd1b35d9b7cb21b2e7c17201d831c17560265b67
