### ISSUE TITLE
RoBERTa - Separator Discrepancy

### ISSUE THREAD

**Issue by eladsegal** [pytorch/fairseq#1537]
In the sentence prediction task, there's the following behavior:
- For a single sentence, a separator token is not used
- For a pair of sentences, a single separator token is used between them  

This is the code that is used in the fine-tuning examples, for example GLUE as specified in https://github.com/pytorch/fairseq/blob/7e4c1a4b6a40d0c6cde638dc2c7f2eeb459bc7fb/examples/roberta/README.glue.md:
https://github.com/pytorch/fairseq/blob/7e4c1a4b6a40d0c6cde638dc2c7f2eeb459bc7fb/fairseq/tasks/sentence_prediction.py#L130-L136

However, RoBERTa's hub interface is used for inference (https://github.com/pytorch/fairseq/blob/7e4c1a4b6a40d0c6cde638dc2c7f2eeb459bc7fb/examples/roberta/README.glue.md#inference-on-glue-task).
In the hub interface, there's the following behavior:
- For a single sentence, a separator token is added at the end of it
- For a pair of sentences, two separator tokens are used between them, and another at the end of the second  

https://github.com/pytorch/fairseq/blob/7e4c1a4b6a40d0c6cde638dc2c7f2eeb459bc7fb/fairseq/models/roberta/hub_interface.py#L57-L60

My questions are:
- What is the reason for the discrepancy in separator usage?
- Was roberta.large.mnli fine-tuned using the hub interface separator style, or was it trained exactly as specified in https://github.com/pytorch/fairseq/blob/7e4c1a4b6a40d0c6cde638dc2c7f2eeb459bc7fb/examples/roberta/README.glue.md#finetuning-roberta-on-glue-tasks, hence with a single separator?

**Comment by Colanim** [comment]
By default :

https://github.com/pytorch/fairseq/blob/7e4c1a4b6a40d0c6cde638dc2c7f2eeb459bc7fb/fairseq/models/roberta/hub_interface.py#L36

`no_separator=False`

Therefore there is only one separator.

---

But I'm also curious why would anyone use `no_separator=True` ?

**Comment by eladsegal** [comment]
> By default :
> 
> https://github.com/pytorch/fairseq/blob/7e4c1a4b6a40d0c6cde638dc2c7f2eeb459bc7fb/fairseq/models/roberta/hub_interface.py#L36
> 
> `no_separator=False`
> 
> Therefore there is only one separator.
> 
> But I'm also curious why would anyone use `no_separator=True` ?

The default behavior of the hub interface results in two separators between sentences. If the glad

**Comment by Colanim** [comment]
Oups sorry, my bad, I was looking at BART implementation of Hub interface :

https://github.com/pytorch/fairseq/blob/7e4c1a4b6a40d0c6cde638dc2c7f2eeb459bc7fb/fairseq/models/bart/hub_interface.py#L44

**Comment by myleott** [comment]
Does this comment explain things: https://github.com/pytorch/fairseq/blob/7e4c1a4b6a40d0c6cde638dc2c7f2eeb459bc7fb/fairseq/models/roberta/hub_interface.py#L40

Basically we use the same symbol for end of sentence (EOS) and separator. So for a single sentence task there’s a single EOS at the end, and for sentence pairs we have two EOS between sentences and one at the end.

**Comment by eladsegal** [comment]
Thanks! I wasn't aware of the insertion of the EOS token by the dataloader.

For anyone else who wondered where it happens:
https://github.com/pytorch/fairseq/blob/7e4c1a4b6a40d0c6cde638dc2c7f2eeb459bc7fb/preprocess.py#L303-L304
which eventually gets to
https://github.com/pytorch/fairseq/blob/7e4c1a4b6a40d0c6cde638dc2c7f2eeb459bc7fb/fairseq/data/dictionary.py#L284-L285
in `encode_line`.
