### ISSUE TITLE
XLM-R: pre-processing steps

### ISSUE THREAD

**Issue by stefan-it** [pytorch/fairseq#1540]
Hi,

I'm very interested in the pre-processing steps for training a RoBERTa/XLM-R model from scratch 😅

# BPE with `sentencepiece`

Could you provide the `spm_train` command that was used to create the `sentencepiece` model. Interesting part would be the `--control_symbols` (and their order), `--unk_piece` and `--pad_piece`. 

# BPE encoder

In my understanding, the next part after `spm_train` is the following:

```bash
 cat {train,dev,test}.txt | spm_encode --model=<model_file> --output_format=piece > {train,dev,test}.bpe
```

I would do that step with train, validation and test dataset. Is that correct?

# `fairseq` preprocessing

```
fairseq-preprocess \
    --only-source \
    --trainpref train.bpe \
    --validpref valid.bpe \
    --testpref test.bpe \
    --destdir output \
    --workers 60
```

Are these the correct pre-processing steps? 

My aim is to convert a trained model with the 🤗/Transformers and use it for various NLP tasks, so the correct tokenization/sentence piece model is one crucial part 😅

Thanks many in advance!

**Comment by ngoyal2707** [comment]
Hey,

1) Yes, so we follow the same process as `XLM` paper for training SPM model. The SPM model was trained only on subsample of data.  As the whole data seemed too big to train SPM model and we saw that subsample of data was good representative of vocab. While subsampling, we up/down sample language based on the probability formula mentioned in the paper with smoothing value of `0.7`.
Rest all arg are default, so `<unk>` and `<pad>`.

2) Yes exactly.

3) That's exactly correct.


There were no other language specific tokenization or segmentation.
