### ISSUE TITLE
--context-window flag in eval_lm

### ISSUE THREAD

**Issue by agokrani** [pytorch/fairseq#1541]
## ❓ Questions and Help
I am using following command to evaluate my language model 

fairseq-eval-lm /content/data \
    --path /content/checkpoints/checkpoint_best.pt \
    --sample-break-mode complete --max-tokens 4800 --context-window 1024
with  --context-window value 1024 it loads all the examples that are available in test file. The total number of examples in test file are 3805
However as soon as I change the value of --context-window parameter to 0 it says 598 examples in the test file. I do not understand how context-window parameter affects the number of examples getting loaded for evaluation?  
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
When using `--sample-break-mode=complete` it will concatenate lines from the dataset until it reaches `--tokens-per-sample`, which might result in a fewer number of samples ("examples") than you expect.

For example suppose your data looks like:
```
a b c </s>
d e f g </s>
```

If you use `--sample-break-mode=complete --tokens-per-sample=512` you'll only have a single input example:
```
example 1: a b c </s> d e f g </s>
```

If you instead use `--sample-break-mode=eos` you'll have two examples:
```
example 1: a b c </s>
example 2: d e f g </s>
```

When you use a large value of `--context-window`, it also decreases the `--tokens-per-sample` ([see code here](https://github.com/pytorch/fairseq/blob/master/eval_lm.py#L73)). So with `--context-window 1024` you'd get two examples but the second example will contain some additional context that's not scored:
```
example 1:  a b c </s>
           |----------|   <-- count perplexity of this
example 2: a b c </s> d e f g </s>
                     |------------|    <-- count perplexity of this
```
