### ISSUE TITLE
Invalid syntax when running the pre-processing script

### ISSUE THREAD

**Issue by ajesujoba** [pytorch/fairseq#1547]
I am trying to execute one of the translation examples in the files, the IWSLT'14 German to English (Transformer) specifically.  Running the codes using the command lines below:

` python preprocess.py --source-lang de --target-lang en     --trainpref examples/translation/iwslt14.tokenized.de-en/train --validpref examples/translation/iwslt14.tokenized.de-en/valid --testpref examples/translation/iwslt14.tokenized.de-en/test     --destdir data-bin/iwslt14.tokenized.de-en 
`

returns the following error:

`File "preprocess.py", line 293
    print("{} {}".format(src_dict[k], tgt_dict[v]), file=f)
                                                        ^
SyntaxError: invalid syntax`

![preprocess_error](https://user-images.githubusercontent.com/12751379/71427013-26317b80-26b3-11ea-8496-96ffaaaca6aa.PNG)

What am I doing wrongly?

**Comment by myleott** [comment]
What version of Python are you using? Fairseq requires Python >= 3.6.

**Comment by ajesujoba** [comment]
Oh! that's true I already fixed that. Thanks. 
But I now have a new error
`AttributeError: module 'torch.utils.data' has no attribute 'IterableDataset'`

![error2](https://user-images.githubusercontent.com/12751379/71451796-32820b00-277d-11ea-9f15-4ad3ba39d77c.PNG)

**Comment by myleott** [comment]
We also require PyTorch 1.3: https://pytorch.org/docs/master/data.html#torch.utils.data.IterableDataset
