### ISSUE TITLE
❓ Incremental decoding is not used in beam search ?

### ISSUE THREAD

**Issue by Colanim** [pytorch/fairseq#1549]
## ❓ Questions and Help

In the beam search code, incremental decoding seems to not be used :

https://github.com/pytorch/fairseq/blob/3b53962cd7a42d08bcc7c07f4f858b55bf9bbdad/fairseq/sequence_generator.py#L295-L297

(No state is passed to the decoder)

**Why incremental decoding is not used ?**

---

It seems to be used in the naive implementation :

https://github.com/pytorch/fairseq/blob/20bbbdc068dabef1a3a4689dd5a9ccffcc8297c5/fairseq/sequence_generator.py#L176

**Comment by myleott** [comment]
Sorry it's not very clear from the code, but actually `model` here is an `EnsembleModel` instance, so `forward_decoder` calls into these functions which do pass incremental state:
https://github.com/pytorch/fairseq/blob/3b53962cd7a42d08bcc7c07f4f858b55bf9bbdad/fairseq/sequence_generator.py#L545-L599
