### ISSUE TITLE
'NoneType' object has no attribute 'sizes'

### ISSUE THREAD

**Issue by ehsankf** [pytorch/fairseq#1550]
In fairseq/tasks/translation.py

I get this error
srcbert_datasets, srcbert_datasets.sizes, berttokenizer,
AttributeError: 'NoneType' object has no attribute 'sizes'

**Comment by myleott** [comment]
What command, what version of pytorch, fairseq, etc? Can you please open a new issue using the provided template?

**Comment by ishanisri** [comment]
Hi, I am getting this same error while running the command -
`python generate.py data-bin/wmt14.en-de.newstest2014  \
  --path data-bin/wmt14.en-de.fconv-py/model.pt \
  --beam 5 --batch-size 128 --remove-bpe | tee /tmp/gen.out`. 
  pytorch == 1.4.0
fairseq == 0.6.2
