### ISSUE TITLE
How to generate my own distillation dataset on Levenshtien Transformer

### ISSUE THREAD

**Issue by zhaoxv** [pytorch/fairseq#1554]
## What is your question?
About the Levenshtien Transformer, I want to experiment with my own dataset，but it needs distillation dataset for this experiment.

So how can I generate my own distillation dataset?

And what is the specific process？

and when I run "fairseq-train...", there is a error:
Segmentation fault.How to tackle it?

**Comment by MultiPath** [comment]
Hi @zhaoxv 

It should be the same as running ``generate.py``with a pretrained autoregressive model by passing ``--gen-subset train``.

**Comment by zhaoxv** [comment]
Ok.thanks for your reply.

**Comment by zhaoxv** [comment]
when I run "fairseq-train...", there is an error:
**Segmentation fault.**
How to tackle it?

**Comment by lematt1991** [comment]
Please post the full command that you used to launch the job as well as a full stack trace of the error you are getting.

**Comment by MultiPath** [comment]
> when I run "fairseq-train...", there is an error:
> **Segmentation fault.**
> How to tackle it?

Did you compile all the C++ files? Try running ```python setup.py build_ext --inplace```

**Comment by zhaoxv** [comment]
Hi @MultiPath 
After running “`generate.py`with a pretrained autoregressive model by passing `--gen-subset train`”, where is the distillation dataset stored？
I cannot find it.

**Comment by zhaoxv** [comment]
Hi @lematt1991 **The command is:**
"fairseq-train data-bin/wmt17_en_de --save-dir checkpoints1 --ddp-backend=no_c10d --task translation_lev --criterion nat_loss --arch levenshtein_transformer --noise random_delete --share-all-embeddings --optimizer adam --adam-betas '(0.9,0.98)' --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr '1e-09' --warmup-updates 1000 --warmup-init-lr '1e-07' --label-smoothing 0.1 --dropout 0.3 --weight-decay 0.01 --decoder-learned-pos --encoder-learned-pos --apply-bert-init --log-format 'simple' --log-interval 10 --fixed-validation-seed 7 --max-tokens 800 --save-interval-updates 100 --max-update 300"
**The error is:**
| model levenshtein_transformer, criterion LabelSmoothedDualImitationCriterion
| num. model params: 65850368 (num. trained: 65850368)
| training on 1 GPUs
| max tokens per GPU = 800 and max sentences per GPU = None
| no existing checkpoint found checkpoints1/checkpoint_last.pt
| loading train data for epoch 0
| loaded 3961179 examples from: data-bin/wmt17_en_de/train.en-de.en
| loaded 3961179 examples from: data-bin/wmt17_en_de/train.en-de.de
| data-bin/wmt17_en_de train en-de 3961179 examples
Segmentation fault

**Comment by zhaoxv** [comment]
@MultiPath @lematt1991

**Comment by lematt1991** [comment]
> Did you compile all the C++ files? Try running `python setup.py build_ext --inplace`

**Comment by Ir1d** [comment]
@zhaoxv @MultiPath could you please share how to generate a new distillation dataset after training the teacher models?

I tried `fairseq-generate data-bin/wmt17_en_de_joined --path checkpoints/transformer_vaswani_wmt_en_de_big/checkpoint_best.pt --batch-size 128 --beam 5 --remove-bpe --gen-subset train --results-path data-bin/wmt17_en_de_distill` but after 20 hours and in the end it told me `CUDA out of memory`. No result was generated in anywhere..

**Comment by Ir1d** [comment]
Hi I reduced the batch-size and there's no CUDA error, but after the script there's still no result. Could you help me out?
