### ISSUE TITLE
How large is the gpu memory required in the training and fine-tuning process in BART paper?

### ISSUE THREAD

**Issue by RoderickGu** [pytorch/fairseq#1557]

**Comment by Colanim** [comment]
For finetuning :

From the [README](https://github.com/pytorch/fairseq/blob/master/examples/bart/README.cnn.md#4-fine-tuning-on-cnn-dm-summarization-task) :

> Above is expected to run on 1 node with 8 32gb-V100. Expected training time is about 5 hours. Training time can be reduced with distributed training on 4 nodes and --update-freq 1.

---

For pretraining, the authors didn't release the procedure yet.

**Comment by lematt1991** [comment]
Please follow the issue templates.
