### ISSUE TITLE
What's the evaluation metric for each dataset on GLUE of RoBERTa?

### ISSUE THREAD

**Issue by luofuli** [pytorch/fairseq#1561]
Hi,

I have a question about the results of RoBERTa on GLUE. 
According to [GLUE leaderboard](https://gluebenchmark.com/tasks), there are two different metrics for `MRPC`, `STS `and `QQP`.  Which evaluation metric do you use to compute the results of these datasets shown in the RoBERTa paper and [this page](https://github.com/pytorch/fairseq/tree/master/examples/roberta)? 

I try to figure out this problem via the alignment of the ensemble results of RoBERTa on test set at Table 5 in the paper and [GLUE leaderboard RoBERTa](https://gluebenchmark.com/leaderboard/). And I find their evaluation metrics are as follows:
-  `STS`: **Pearson**
- `MRPC`: **F1**: 
- `QQP`: Accuracy

However, this conflicts with some related papers such as [ELECTRA](https://openreview.net/pdf?id=r1xMH1BtvB). [ELECTRA](https://openreview.net/pdf?id=r1xMH1BtvB) directly copies your results shown in the RoBERTa paper and said that their evaluation metrics (in the Section 3.1) are as follows:

- `STS`: **Spearman**
- `MRPC`: **Accuracy**
- `QQP`: Accuracy

To conclude, I just wonder which metric is used on each dataset for GLUE in the RoBERTa paper.

**Comment by lematt1991** [comment]
CC @myleott @ngoyal2707

**Comment by ngoyal2707** [comment]
Following are the metrics used for the 3 tasks you mentioned:

- `STS`: `Pearson`
- `MRPC`: `ACC`
- `QQP`: `ACC`

**Comment by luofuli** [comment]
However, in the Table 5 of [the RoBERTa paper](https://arxiv.org/pdf/1907.11692.pdf), `MRPC ` obtains `92.3` on the test set.  And according to the [glue leaderboard](https://gluebenchmark.com/submission/JuLiHrAkS9VSQRh1W6TJ9V9SOu23/-Lk5ZrckAabWVeQBoxrA), this score is `F1`, not the accuracy (Acc). @ngoyal2707 

![image](https://user-images.githubusercontent.com/13479945/72134949-4c982c00-33c0-11ea-94ea-18e65f4476ac.png)

**Comment by ngoyal2707** [comment]
@luofuli good catch. I think, it's a mistake in our manuscript where we are reporting `Acc` for `dev` and `F1` for `test`. 
The system are still comparable as all systems report the same measures. But we will update the next version to make it clear.

Thanks!

**Comment by luofuli** [comment]
Thank you very much.
