### ISSUE TITLE
Is there  a  configuration for PTB

### ISSUE THREAD

**Issue by liiutengbo** [pytorch/fairseq#1567]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by lematt1991** [comment]
Please fill out the template
