### ISSUE TITLE
Pretraining RoBERTa base with LayerDrop

### ISSUE THREAD

**Issue by formiel** [pytorch/fairseq#1571]
Hi @huihuifan , 

Thank you for publishing the code of your [Layer Drop paper](https://openreview.net/forum?id=SylO2yStDr&noteId=SylO2yStDr)!

I run into the following error when training RoBERTa base on WikiText-103 dataset (following the tutorial [here](https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md)). 

```
File "/home/user/fairseq/fairseq/distributed_utils.py", line 181, in all_gather_list
    'Unable to unpickle data from other workers. all_gather_list requires all '
Exception: Unable to unpickle data from other workers. all_gather_list requires all 
workers to enter the function together, so this error usually indicates that the 
workers have fallen out of sync somehow. Workers can fall out of sync if one of 
them runs out of memory, or if there are other conditions in your training script 
that can cause one worker to finish an epoch while other workers are still iterating
over their portions of the data.
```
I used the following command to launch the pretraining on a single machine with 2 GPUs. There's no such problem when I set the argument `encoder-layerdrop` to 0.0 or remove it.
```
python fairseq_cli/train.py $DATA_DIR \
    --task masked_lm --criterion masked_lm \
    --arch roberta_base --sample-break-mode complete --tokens-per-sample $TOKENS_PER_SAMPLE \
    --optimizer adam --adam-betas '(0.9,0.98)' --adam-eps 1e-6 --clip-norm 0.0 \
    --lr-scheduler polynomial_decay --lr $PEAK_LR --warmup-updates $WARMUP_UPDATES --total-num-update $TOTAL_UPDATES \
    --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 \
    --max-sentences $MAX_SENTENCES --update-freq $UPDATE_FREQ \
    --max-update $TOTAL_UPDATES --log-format simple --log-interval 1 \
    --save-dir checkpoints/${EXP_NAME} \
    --encoder-layerdrop 0.2
```

I already checked the memory usage and the model just used up to half of the available memory.

Could you please help me on this issue?

Thank you in advance for your help!

**Comment by huihuifan** [comment]
hi, thanks for raising the issue. can you try adding the parameter
--ddp-backend no_c10d 

thanks!

**Comment by formiel** [comment]
I added the parameters `--ddp-backend no_c10d` and there's no error now. Thanks so much for your quick reply!

**Comment by huihuifan** [comment]
no problem! if anyone stumbles upon this issue later, the reason is because when using layerdrop, some of the parameters are not used (the layers that are dropped, specifically) so they do not receive gradient. this can cause issues in distributed training

**Comment by formiel** [comment]
Thanks for your clear explanation! I also tried setting the flag `--find-unused-parameters` instead of using `ddp-backend no_c10d` and found that there's a slow down in `wps` (from 23k with `no_c10d` to around 22k with `c10d` backend).
