### ISSUE TITLE
xlmr.large : Is it possible to find sentence similarity between 2 languages?

### ISSUE THREAD

**Issue by chiragsanghvi10** [pytorch/fairseq#1573]
Hi,

How can I find similarity score between two different languages?
### Example, 
> Sentence 1 (English)
> Sentence 2 (Hindi )
> Similarity score between 0 and 1.

Using `xlmr.large`

Best regards,
Chirag Sanghvi

**Comment by lematt1991** [comment]
I'm not sure this is an intended use case of XLM.  I would suggest using something like [LASER](https://github.com/facebookresearch/LASER)
