### ISSUE TITLE
The language model inference for wikitext-103 

### ISSUE THREAD

**Issue by liiutengbo** [pytorch/fairseq#1578]
I have trained a language model for wikitext-103 with your offical configuration.
training parameters:
 fairseq-train --task language_modeling data-bin/wikitext-103 \
  --save-dir checkpoints/transformer_wikitext-103 --arch transformer_lm_wiki103 \
  --max-update 286000 --max-lr 1.0 --t-mult 2 --lr-period-updates 270000 --lr-scheduler cosine --lr-shrink 0.75 \
  --warmup-updates 16000 --warmup-init-lr 1e-07 --min-lr 1e-09 --optimizer nag --lr 0.0001 --clip-norm 0.1 \
  --criterion adaptive_loss --max-tokens 1640--update-freq 5--tokens-per-sample 3072 --seed 1 \
  --sample-break-mode none --skip-invalid-size-inputs-valid-test --ddp-backend=no_c10d

my train device is TITAN V 8 GPU,and the best model size is 1.4G, and your official model size is 1.4G. But when I  inference with your model,  I can run on the GPU without out of memory with your inference parameters(max-tokens 3072,context-windows 2560 softmax-batch 1024), but my model can not inference, although I lower the max-token to 2048,1024 .
what is the problem?

**Comment by lematt1991** [comment]
Please follow the issue templates.
