### ISSUE TITLE
Weights for RoBERTa finetuned on SQuAD

### ISSUE THREAD

**Issue by OlegPlatonov** [pytorch/fairseq#1579]
## 🚀 Feature Request
Release model weights for RoBERTa finetuned on SQuAD.

### Motivation

SQuAD is one of the most popular datasets for evaluating NLU models. Models trained on SQuAD can be useful for various real-world tasks.

### Pitch

Could you please release pre-trained model weights for RoBERTa (base and large) finetuned on SQuAD?

### Alternatives

Provide scripts for finetuning RoBERTa on SQuAD ( #933 ).

### Additional context

NA

**Comment by phosseini** [comment]
Any update?!
