### ISSUE TITLE
question on multi-gpu / multiprocessing

### ISSUE THREAD

**Issue by vince62s** [pytorch/fairseq#158]
guys,
I am trying to undertstand how the sync between processes work.
is this happening here?
https://github.com/pytorch/fairseq/blob/d3795d6cd1c66ac05dc0f4861ce69ab4680bff3d/fairseq/trainer.py#L154

I am trying to figure out what prevent one worker (if it goes much faster than the other one) to step into teh next epoch when others are still in the previous one;

not sure I am clear enough.

**Comment by myleott** [comment]
The flow is roughly:
1. Each workers does forward independently
2. Workers synchronize stats (e.g., sample sizes, logging outputs, etc.)
3. Workers do backward independently
4. Gradients are synchronized via all-reduce: https://github.com/pytorch/fairseq/blob/d3795d6cd1c66ac05dc0f4861ce69ab4680bff3d/fairseq/trainer.py#L185
5. Workers take an optimization step independently (they all have identical gradients after the all-reduce)

**Comment by vince62s** [comment]
Okay, thanks, I think I got it, except one poitn.
When one process finishes earlier and thus destroy all data in memory, how does the other process can gather the grads with all_reduce_and_rescale ?

**Comment by myleott** [comment]
All-reduce is blocking, so workers can only continue after the communication is done.

**Comment by vince62s** [comment]
okay thank.
