### ISSUE TITLE
The condition statement judging bos may be wrong in LanguagePairDataset?

### ISSUE THREAD

**Issue by YongfeiYan** [pytorch/fairseq#1581]
When judging whether bos is added to source in [https://github.com/pytorch/fairseq/blob/master/fairseq/data/language_pair_dataset.py#L200](https://github.com/pytorch/fairseq/blob/master/fairseq/data/language_pair_dataset.py#L200)
, `if self.src[index][-1] != bos:`should be `self.src[index][0] != bos:`?

**Comment by lematt1991** [comment]
Please follow the issue templates
