### ISSUE TITLE
Generation results are printed to the console even when a results path is provided

### ISSUE THREAD

**Issue by erip** [pytorch/fairseq#1585]
## 🐛 Bug

Results aren't written to `args.result_path` in `fairseq-generate` when specified.

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

Assuming a model has been trained...

1. Run cmd `fairseq-generate data-bin --path checkpoints/checkpoint_best.pt --results-path out/`

2. See results printed to screen and observe empty `out/` 

#### Code sample

N/A

### Expected behavior

I expect generation results to be written to some file within the directory specified by `--results-path`

### Environment

- fairseq Version (e.g., 1.0 or master): 0.9.0

- PyTorch Version (e.g., 1.0): 1.3.1

- OS (e.g., Linux): any

- How you installed fairseq (`pip`, source): `pip`

- Build command you used (if compiling from source):

- Python version: 3.7

- CUDA/cuDNN version: N/A

- GPU models and configuration: N/A

- Any other relevant information:

**Comment by zeeshansayyed** [comment]
@erip Do you know what solved it? I too seem to facing the same problem.

**Comment by erip** [comment]
Install from master. I introduced a PR long ago that addressed this issue, but it's not linked for some reason.

**Comment by zeeshansayyed** [comment]
Thanks. That worked. Do you think it will be released with the next release?
