### ISSUE TITLE
Results aren't written to `args.results_path` in `fairseq-generate` when specified.

### ISSUE THREAD

**Issue by erip** [pytorch/fairseq#1586]
## 🐛 Bug

Results aren't written to `args.results_path` in `fairseq-generate` when specified.

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

Assuming a model has been trained...

1. Run cmd `fairseq-generate data-bin --path checkpoints/checkpoint_best.pt --results-path out/`

2. See results printed to screen and observe empty `out/`

### Expected behavior

I expect generation results to be written to some file within the directory specified by `--results-path`

### Environment

 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Windows (but doesn't matter)
 - How you installed fairseq (`pip`, source): `pip`
 - Build command you used (if compiling from source): n/a
 - Python version: 3.7.x
 - CUDA/cuDNN version: n/a
 - GPU models and configuration: n/a
 - Any other relevant information: n/a

### Additional context

See that `results_path` is unused in [`generate.py`](https://github.com/pytorch/fairseq/blob/master/generate.py).

**Comment by myleott** [comment]
Apparently this was only implemented for the speech recognition code, but it wasn’t documented as such. We should add support for this in the main generate.py as well. 

In the mean time you can simply redirect stdout to a file: `fairseq-generate (...) > results.out`
