### ISSUE TITLE
--ddp-backend=no_c10d vs --ddp-backend=c10d

### ISSUE THREAD

**Issue by kellymarchisio** [pytorch/fairseq#1588]
Should I expect a qualitative/quantitative difference in my results between using --ddp-backend=no_c10d vs --ddp-backend=c10d for training, besides a training speedup?  I've been using c10d, but just saw the warning that says "NOTE: you may get better performance with: --ddp-backend=no_c10d".  I'd like to try no_c10d, but cannot if it'll make my experiments not comparable with previous ones where I used --ddp-backend=c10d

 - fairseq Version (e.g., 1.0 or master): master (as of September)
 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source 
 - Python version: 3.7.4
 - CUDA/cuDNN version: 9.1
 - GPU models and configuration: GeForce GTX 1080

**Comment by myleott** [comment]
Sorry, “performance” is a bit overloaded. It just affects speed, not the end model.

We should update the documentation/note to make this clearer.
