### ISSUE TITLE
AttributeError: 'Variable' object has no attribute 'conv_tbc'

### ISSUE THREAD

**Issue by yangsuxia** [pytorch/fairseq#159]
The latest code:
When I run the train.py script，i receive the error that " AttributeError: 'Variable' object has no attribute 'conv_tbc' ".
Do you know why?

Looking forward to your reply.
Thanks you.

**Comment by yangsuxia** [comment]
Yes, the pytorch version is wrong. Mine is 0.2.0, but the requirement is 0.4.0.

Thanks！

**Comment by huihuifan** [comment]
Great! Glad you figured that out.
