### ISSUE TITLE
when I use "fairseq-train..." on levenshtein_transformer, the error happens: segmentation fault

### ISSUE THREAD

**Issue by zhaoxv** [pytorch/fairseq#1590]
"| num. model params: 65850368 (num. trained: 65850368)
| training on 1 GPUs
| max tokens per GPU = 4096 and max sentences per GPU = None
| no existing checkpoint found checkpoints/checkpoint_last.pt
| loading train data for epoch 0
| loaded 3961179 examples from: data-bin/wmt14_en_de/train.en-de.en
| loaded 3961179 examples from: data-bin/wmt14_en_de/train.en-de.de
| data-bin/wmt14_en_de train en-de 3961179 examples
Segmentation fault"
![Uploading image.png…]()

**Comment by myleott** [comment]
Probably libnat didn’t build properly. Can you read try the command here and see what you get: https://github.com/pytorch/fairseq/issues/1346#issuecomment-566562039
