### ISSUE TITLE
What are functions of perl $CLEAN line  in the pre-processing shellscript prepare-iwslt14.sh?

### ISSUE THREAD

**Issue by ajesujoba** [pytorch/fairseq#1592]
I am sorry I am asking this question. 

On the line 65 of the prepare-iwslt14.sh in the translation example, the script there is written as 

`perl $CLEAN -ratio 1.5 $tmp/train.tags.$lang.tok $src $tgt $tmp/train.tags.$lang.clean 1 175`

What is the reason for passing `$src` and `$tgt` as parameters?
Just to confirm, does the function iteratively(internallz) perform the clean operation based on the two parameters (which are the languages) with the files already created in 62?

**Comment by lematt1991** [comment]
> What is the reason for passing $src and $tgt as parameters?

Because those are the expected parameters of `clean-corpus-n.perl`.

You can find more information from the [source](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/training/clean-corpus-n.perl) or [here](http://www.statmt.org/moses/?n=FactoredTraining.PrepareTraining)
