### ISSUE TITLE
Where can I find the collected dataset of r/WritingPrompts ?

### ISSUE THREAD

**Issue by bepierre** [pytorch/fairseq#160]
Hey!

I just read your "Hierarchical Neural Story Generation" paper and from my understanding it is redirecting to this repo for the collected dataset. Do you know how I could get access to it?

Thanks!

**Comment by huihuifan** [comment]
Hi Pierre, we are working on releasing the dataset with the code, and it will be in this repo. Could you send me an email for the dataset for now?

**Comment by bepierre** [comment]
thank you!! I sent you a mail

**Comment by Hannabrahman** [comment]
Hi, is the dataset released? If not is it possible that I get it somehow?

**Comment by huihuifan** [comment]
see https://github.com/pytorch/fairseq/examples and then the stories page,
then you can download the data.

**Comment by venneladondapati** [comment]
Hi, the link you attached is getting redirected to some error page. Can you please provide me with the dataset?
