### ISSUE TITLE
Inference Scripts for Non-Autoregressive models

### ISSUE THREAD

**Issue by Tiiiger** [pytorch/fairseq#1600]
hi @MultiPath,

Thank you very much for implementing so many models in `faiirseq` and providing the training [scripts](https://github.com/pytorch/fairseq/blob/master/examples/nonautoregressive_translation/scripts.md). 

I wonder whether the reimplemented NAT models such as Mask-Predict and NAT-CRF can reproduce the reported performance in the original papers? Can you also provide the evaluation commands (inference scripts) for these models?

Many thanks in advance : )

**Comment by MultiPath** [comment]
Hi, the inference scripts are basically very similar to each other.
I will create a README for inferencing all these models recently.

Best,
