### ISSUE TITLE
out of memory for sharded data

### ISSUE THREAD

**Issue by zherowolf** [pytorch/fairseq#1609]
fairseq: 0.9.0
pytorch: 1.2
hardware: 128G memory, 4 * 32G V100 gpus
dataset :  two sharded data with each 50M pairs,  so that I need reload dataset each epoch.
The question is: after each reload, I found the memory increases and after several epochs I catch the exception with out of memory. Is that a bug?  some hyperparamters I missed. 
Thanks ,guys.

**Comment by zherowolf** [comment]
got it. closing now.

**Comment by nomadlx** [comment]
How did you solve the problem? I had the same problem.
