### ISSUE TITLE
Get the Encoder output without the trainer object?

### ISSUE THREAD

**Issue by ajesujoba** [pytorch/fairseq#1613]
How do I get the `EncoderOut ` using the `model` object gotten from the `model = task.build_model(args)` for transformer most especially?
 
The `.build_model(args)` in transformer.py returns ` cls(args, encoder, decoder)`. For Transformer, there is a class `TransformerEncoder(FairseqEncoder)` which returns the following:

`
return EncoderOut
(
            encoder_out=x,  # T x B x C
            encoder_padding_mask=encoder_padding_mask,  # B x T
            encoder_embedding=encoder_embedding,  # B x T x C
            encoder_states=encoder_states,  # List[T x B x C]
     )
`

I need to get the `EncoderOut `using `model`. I am afraid using just ` model.encoder.forward()` wont work in this case. Please I need to get the `encoder_out` and `encoder_embedding`. Thanks!

Please kindly confirm that I am right with the following, B = Batch size, T = number of samples, C = embedding_dim

**Comment by myleott** [comment]
It should be fine to call `model.encoder` directly. You can see how `model.forward` is implemented here: https://github.com/pytorch/fairseq/blob/7201ebc57ec9bff916ecd2e72b4f1e02ffa74f66/fairseq/models/fairseq_model.py#L200-L225

**Comment by ajesujoba** [comment]
Thanks for your response. Sorry I'm asking too much questions. 

In the case of embeddings, this `model.encoder.forward_embedding()` should work right?

**Comment by myleott** [comment]
Yes, I meant that the implementation for `model.forward` is very simple. It just calls `self.encoder` followed by `self.decoder`, so you can easily call `model.encoder` and it will work.

Similarly `model.encoder.forward_embedding` should be fine to call as well.

**Comment by ajesujoba** [comment]
Ok! Thank you very much. 

Finally, I discovered the `lstm.py` class did not implement the `.forward_embedding` method, but the `self.forward()` method in the lstm.py returns a dictionary of the form:

`return {
            'encoder_out': (x, final_hiddens, final_cells),
            'encoder_padding_mask': encoder_padding_mask if encoder_padding_mask.any() else None
        }` where `x` is the embedding.

Is there a way to identify the generic architecture of the model(Transformer/LSTM) in use, such that with an IF statement I can get the embeddings and encoder output of the different model:

`if (model.arch == 'Transformer'):  
       self.encoder.forward(....)
       self.encoder.forward_embedding(....)
elif (model.arch == 'LSTM'):  args.arch 
       self.encoder.forward(....) #returns embedding and encoder output in a dictionary tuple
`
Using `args.arch` could have worked but I discovered the architecture are too specific .e.g. `transformer_wmt_en_de_big`

Thanks! Thanks!! Thanks!!!

**Comment by myleott** [comment]
> Is there a way to identify the generic architecture of the model(Transformer/LSTM)

Not really. Fairseq tries not to make many assumptions about the encoder/decoder format, so there's no specified interface for these things.

> Using args.arch could have worked but I discovered the architecture are too specific .e.g. transformer_wmt_en_de_big

You can do something like this:
```python
>>> from fairseq.models import ARCH_MODEL_REGISTRY
>>> print(ARCH_MODEL_REGISTRY['transformer_wmt_en_de_big'])
<class 'fairseq.models.transformer.TransformerModel'>
```

**Comment by ajesujoba** [comment]
Hi @myleott , In a multi-GPU setting, `model.encoder.forward_embedding(..)` seems to return the output of the encoder `n-number` of times. Where `n` is the number of GPUs that is in use. Is my observation right? Is the implementation right?
