### ISSUE TITLE
BART pretraining instructions

### ISSUE THREAD

**Issue by swapbagal1** [pytorch/fairseq#1614]
Hi, Is there any pretrained BART model for Japanese? If not, could you please explain the procedure to train new BART model for Japanese data from scratch?

**Comment by myleott** [comment]
@swapbagal1, we don't have a Japanese BART model currently. Also, in the future please follow the issue templates :)

@ngoyal2707, would you be able to add a doc explaining how to pretrain BART?

**Comment by bcmi220** [comment]
also waiting for the doc explaining how to pretrain BART

**Comment by JohnasSolomon** [comment]
Is there any update on how to pretrain BART?

**Comment by villmow** [comment]
Bumb, instructions would be nice!

**Comment by MichaelZhouwang** [comment]
Is there any plan on releasing instruction about how to pretrain BART?

**Comment by vikrant97** [comment]
Is there any update on how to pretrain BART?

**Comment by xiaolingzang** [comment]
id there any  instruction about how to pretrain BART?

**Comment by alphadl** [comment]
Is there any update on how to pretrain BART?

**Comment by alphadl** [comment]
@xiaolingzang @vikrant97 @michaelauli Please refer https://github.com/huggingface/transformers/issues/5096#issuecomment-645860271

**Comment by yuye2133** [comment]
> @xiaolingzang @vikrant97 @michaelauli Please refer [huggingface/transformers#5096 (comment)](https://github.com/huggingface/transformers/issues/5096#issuecomment-645860271)

您好，请问下，在用这个方法对中文做预训练的时候，发现decoder预测的全都是结束符"<T>"，这是怎么回事啊，开始试了直接用BartForConditionalGeneration前向计算的loss，decoder预测的全是"[PAD]"，然后修改了loss的计算方法，取消了[PAD]位置的loss计算，就出现了decoer全是结束符”<T>“

**Comment by reemalyami** [comment]
is there any updates on pre-training BART? I want to train on another language to do classification all I can find for BART pre-training is on the generation task.

**Comment by jc-hou** [comment]
This is my script for training bart. Still under development, but maybe you can try and adapt it to your need.
https://github.com/jc-hou/train_bart_from_scratch

**Comment by mohammadKhalifa** [comment]
Can't we do this using the denoising task?

**Comment by aliaraabi** [comment]
Still no updates on pre-training BART?

**Comment by prajdabre** [comment]
If anyone wants to train their MBART model then feel free to use this.
https://github.com/prajdabre/yanmtt

Contributions are welcome!

**Comment by JiyangZhang** [comment]
Is there any plan on releasing instruction about how to pretrain BART?

**Comment by sarubi** [comment]
Is there any update on how to pre-train BART/mBART from scratch?

**Comment by prajdabre** [comment]
@sarubi @JiyangZhang  in case you are interested, I implemented it on top of huggingface https://github.com/prajdabre/yanmtt

**Comment by tarudesu** [comment]
any updates?

**Comment by frankang** [comment]
This is the pretraining script given by the author (and improved by [BramVanroy](https://github.com/BramVanroy))
From https://github.com/facebookresearch/fairseq/issues/1899#issuecomment-1237329475
```
python train.py $DATA --fp16 --mask 0.3 --tokens-per-sample 512 --total-num-update 500000 --max-update 500000 --warmup-updates 10000 --task denoising --save-interval 1 --arch bart_base --optimizer adam --lr-scheduler polynomial_decay --lr 0.0004 --dropout 0.1 --criterion cross_entropy --max-tokens 3200 --weight-decay 0.01 --attention-dropout 0.1 --share-all-embeddings --clip-norm 0.1 --skip-invalid-size-inputs-valid-test --log-format json --log-interval 1000 --save-interval-updates 5000 --keep-interval-updates 1 --update-freq 4 --seed 4 --distributed-world-size 256 --distributed-port 54187 --no-epoch-checkpoints --mask-length span-poisson --replace-length 1 --encoder-learned-pos --decoder-learned-pos --rotate 0.0 --mask-random 0.1 --permute-sentences 1 --insert 0.0 --poisson-lambda 3.5 --dataset-impl mmap --bpe gpt2 --num-workers 4
```
