### ISSUE TITLE
how to revise the prepare-wmt14en2de.sh to gain the WMT14 trainig data

### ISSUE THREAD

**Issue by zhao1402072392** [pytorch/fairseq#1623]
how to revise the code to gain the WMT14 trainig data,please:)

**Comment by myleott** [comment]
Just pass the `--icml17` flag to the prepare script and it should produce WMT14 training data. This is also explained a bit here: https://github.com/pytorch/fairseq/blob/master/examples/translation/README.md#wmt14-english-to-german-convolutional
