### ISSUE TITLE
Finetuning BART for generation tasks

### ISSUE THREAD

**Issue by tuhinjubcse** [pytorch/fairseq#1624]
#### What is your question?
Hi
I am planning to use BART for a sequence generation task. I saw the CNN-DM finetuning README, but was just wondering if there is anything different for a general seq2seq generation task ( sentence A-->sentence B ) or we should follow?
Any help will be appreciated.

Especially the tokenization part

https://github.com/pytorch/fairseq/blob/master/examples/bart/README.cnn.md

wget -N 'https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/encoder.json'
wget -N 'https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/vocab.bpe'
wget -N 'https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/dict.txt'

for SPLIT in train val
do
  for LANG in source target
  do
    python -m examples.roberta.multiprocessing_bpe_encoder \
    --encoder-json encoder.json \
    --vocab-bpe vocab.bpe \
    --inputs "cnn_dm/$SPLIT.$LANG" \
    --outputs "cnn_dm/$SPLIT.bpe.$LANG" \
    --workers 60 \
    --keep-empty;
  done
done

It seems the inputs should be
cnn_dm/train.source
cnn_dm/train.target

What should  these files contain what ?? Can someone please explain ??

1) Follow instructions here to download and process into data-files with non-tokenized cased samples.
What does this mean ??

https://github.com/abisee/cnn-dailymail converts its into bin file already

This is not clear at all

**Comment by swethmandava** [comment]
they contain just text. Use 
`python make_datafiles.py /path/to/cnn/stories /path/to/dailymail/stories`
to generate cnn_dm folder
