### ISSUE TITLE
BERT/Roberta MULTITASKING

### ISSUE THREAD

**Issue by muhammadfahid51** [pytorch/fairseq#1625]
Hello there!
This is related to R&D on my behalf. 
Is there a way that we can fine tune BERT for multitasks at the the same time, What I mean is 
One BERT/Roberta model in a single pytorch/keras model is fine-tuned for two or more tasks say
1. Sentiment Analysis
2. Question Answering 
3. English to German Translation
and so on

**Comment by myleott** [comment]
We have some multitasking support in an internal branch. I can work on cleaning it up and releasing it.

**Comment by mohammadKhalifa** [comment]
@myleott any progress on that?

**Comment by jayargo** [comment]
@myleott sorry to ping you. We are interested in this as well. 

I noticed a recent issue along similar lines here : https://github.com/pytorch/fairseq/issues/3156

Before heading down the road suggested in 3156, wanted to check if 
(1) there's any chance you'll be releasing the multitasking support from your internal branch
(2) if not, can you outline the approach you took so we can implement it (assuming different from 3156)?

Thanks!!
