### ISSUE TITLE
Wav2Vec for genre classification: training with mp3 audio snippets

### ISSUE THREAD

**Issue by GiorgioBarnabo** [pytorch/fairseq#1636]
Hi everybody,

I am kind of new to the fairseq world and I would need some help to start using the Wav2Vec model. In particular, I am trying to fine-tuning the Wav2Vec pre-trained model with 8000 mp3 files taken from the Free Music Archive.
Is this possible or they must be converted into wav format? Is there any code available that I could reuse to learn how to use the model? The few lines I found the the Wav2Vec folder did not help me much! 
I am working in a CoLab environment.

Thank you very much.
Any help will be greatly appreciated.

Giorgio

**Comment by lematt1991** [comment]
You should follow [this](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec) example for setting up Wav2Vec

**Comment by zhang-jr** [comment]
Hi, Giorgio

I have the same problem. In my enviroment, the soundfile.info(), in wav2vec_manifest.py, is not compatible with '.mp3'. Instead, I use ``frames = len(lidrosa.load(fname, sr=None)[0])`` to replace ``frames = soundfile.info(fname).frames`` in line 48.

Hope this can help you.
