### ISSUE TITLE
Create Sentence from Tensor

### ISSUE THREAD

**Issue by ajesujoba** [pytorch/fairseq#1637]
I have an a sentence as tensor in  fairseq, 
`tensor([1829,   3,    3,    3, 6046,    3,    4,    3,    3, 6421, 6001,    3,
           3,    3,    5, 6157,   23, 5392,    3, 6046,    3,    3,  460,    4,
        6203,  105,    3,    3,    3,    3,    3,    3,    3,    4, 5572,    3,
        5392,    3,    4,    3,    3,    3,    3,    4,    3,    3, 4692,    3,
           3,    3,    5,    2])`
Can I generate this actual sentence in fairseq, given the dictionary?

**Comment by sc16s2w** [comment]
hi, do you know how to solve it now?
