### ISSUE TITLE
Pre-train on small RoBERTa

### ISSUE THREAD

**Issue by aditya-malte** [pytorch/fairseq#1645]
Hello,
My query is in relation to the tutorial available at:
https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md

As visible, we can only pretrain(from scratch) on the "base" model's architecture.
Can I perform pretraining on a SMALL RoBERTa model (eg. 3 layers), instead of the base model.
If yes, please let me know how to do the same.
Thanks

**Comment by myleott** [comment]
You can override the configuration on the command line. Here are the defaults: https://github.com/pytorch/fairseq/blob/master/fairseq/models/roberta/model.py#L378-L417

For example, `--arch roberta_base --encoder-layers 3` will use the roberta base config, except with 3 layers instead of 12

**Comment by aditya-malte** [comment]
Thank you very much!
