### ISSUE TITLE
the impact of  max-tokens 

### ISSUE THREAD

**Issue by travel-go** [pytorch/fairseq#165]
Hello,I want to ask  you about the impact of max-token on the experiment.
Is the bigger the max-token, the better?(the same as batch size?)

Then,I want to continue the experiment, but if max-token is set to a different number, it will have a big impact on the experimental results?For example, before it was 6000, then set to 4000.

**Comment by travel-go** [comment]
oh,Thank you @myleott.I have trouble you many times and I am very grateful

**Comment by TaniyaHaghighi20** [comment]
can you tell me about the usage of --max-tokens and --sample-break mode complete-doc? I read somewhere that using --sample-break mode complete-doc helps with separating the text at empty lines, so by doing this samples are going to have different lengths right? if the answer is yes, how should we choose --max-tokens? I'm using journal abstracts separated by empty lines as the training set and have no idea what the value of max-tokens should be. also, what will be the final batch size?
