### ISSUE TITLE
Clarification regarding RoBERTa input processing

### ISSUE THREAD

**Issue by chitwansaharia** [pytorch/fairseq#1654]
I have a doubt regarding input representation for RoBERTa. According to the paper, BERT uses the following format. 
`[CLS] x1 x2 .. xn [SEP] y1 y2 y3 ... yn [EOS]`, hence it doesn't put `[SEP]` between sentences. It only puts `[SEP]` between the two segments. Now, in RoBERTa (FULL-SENTENCES mode), where we have no concept of two different segments, do we use `[SEP]` token in between each sentence ? 

And during fine-tuning on pair-wise classification task, where do we place the `[SEP]` tokens.

**Comment by myleott** [comment]
The input format looks like this during finetuning: https://github.com/pytorch/fairseq/blob/c2671c1720bf86d1e793832bd9417f9e857820a0/fairseq/models/roberta/hub_interface.py#L36-L45

During pretraining, with FULL-SENTENCES we allow inputs to cross document boundaries, and use an extra `</s>` between documents. From the paper: "Inputs may cross document boundaries. When we reach the end of one document, we begin sampling sentences from the next document and add an extra separator token between documents."

During pretraining, with the DOC-SENTENCES format, we do not allow inputs to cross document boundaries so you are correct that the model never sees two "</s> </s>" during pretraining. In finetuning we still use the same format as above, but in practice this doesn't cause a problem.

**Comment by wugh** [comment]
> The input format looks like this during finetuning:
> 
> https://github.com/pytorch/fairseq/blob/c2671c1720bf86d1e793832bd9417f9e857820a0/fairseq/models/roberta/hub_interface.py#L36-L45
> 
> During pretraining, with FULL-SENTENCES we allow inputs to cross document boundaries, and use an extra `</s>` between documents. From the paper: "Inputs may cross document boundaries. When we reach the end of one document, we begin sampling sentences from the next document and add an extra separator token between documents."
> 
> During pretraining, with the DOC-SENTENCES format, we do not allow inputs to cross document boundaries so you are correct that the model never sees two " " during pretraining. In finetuning we still use the same format as above, but in practice this doesn't cause a problem.

So in FULL-SENTENCES setting ` </s> ` only use when we across document? where I can get some  pretraining sample data? or can you give some example or code
