### ISSUE TITLE
ASR models and modules in examples

### ISSUE THREAD

**Issue by mgaido91** [pytorch/fairseq#1656]
I am wondering why the code for ASR has been released in the example section, rather than as normal tasks/models. Any reason for that? Does this imply something about its maintenance? Thanks.

**Comment by myleott** [comment]
Good question. The team working on it just wanted a little more isolation from the text-focused tasks/models. We may move more things to examples in the future as well.

**Comment by mgaido91** [comment]
Thanks for your answer @myleott. What if we have an `extensions` section then, rather than having these things in `examples`?
