### ISSUE TITLE
making sure some words aren't broken by subword tokenizer 

### ISSUE THREAD

**Issue by tuhinjubcse** [pytorch/fairseq#1657]
Hi
I have some words like ["\<A0>" , "\<A1>" , "\</s>"] which I do not want to be broken into subwords [ < , A, 0 , >] rather treated as whole words <A0> 

The current code and bpe encoder I believe breaks it 
Is there a way to prevent ?
I added the new words in  encoder.json , what should I add in the dict.txt
and do I need to change anything in the dict.txt ?

Any help is appreciated

**Comment by tuhinjubcse** [comment]
@myleott  @ngoyal2707

**Comment by lematt1991** [comment]
Please follow the issue template.
