### ISSUE TITLE
BART: TransformerEncoder vs TransformerSentenceEncoder

### ISSUE THREAD

**Issue by sshleifer** [pytorch/fairseq#1660]
Hi!
I’m working on porting BART to the transformers repo's API and was interested in whether the reasons for using TransformerEncoder instead of TransformerSentenceEncoder (which Roberta uses).  I read the code for both and there are some differences, but they seem mostly aesthetic. 
Thanks in advance!

**Comment by ngoyal2707** [comment]
Both of them should be similar specially with BART's arguments. I would still suggest maybe check the output of converted and original model to be sure of subtle differences like embedding_scaling, layer_norm and residual connection position.

**Comment by sshleifer** [comment]
Do you know why attn_mask is not passed to self.self_attn after https://github.com/pytorch/fairseq/blob/4e48c4ae5da48a5f70c969c16793e55e12db3c81/fairseq/modules/transformer_layer.py#L84

Thats the only difference I see.

**Comment by xu-song** [comment]
what about refactor TransformerSentenceEncoder as BertEncoder
