### ISSUE TITLE
Story Generation: Why can't the provided model produce stories as good as the results given?

### ISSUE THREAD

**Issue by Mhzzzzz** [pytorch/fairseq#1665]
#1469 ## What is your question?

I tried to generate stories with the provided models. I followed the command at README.md. But the stories I generated are of poor quality. Let me give you an example:

S-8782	[ WP ] Make a creation myth
H-8782	-1.0844866037368774	I had been in a great place , and I was a proud man . He was a great man and a good man , but he was the best man I had ever met . <newline> <newline> I was a good man , and he was great . I was always the best man , but he was a great man . He was good at what I did , but he was good at how I did . He was great at that . <newline> <newline> I was proud to be him , and he was proud to be a good man . I would never know what he was like , I would never know . <newline> <newline> I was proud to be his good man . He was the best man in the world . He was good at that . <newline> <newline> I was proud to be a good man . <newline> <newline> The first time I saw him , I was proud to be his bad man . I was proud to be a good man , but I knew that I was proud to be a good man .

#### Code

fairseq-generate data-bin/writingPrompts \
    --path models/fusion_checkpoint.pt \
    --batch-size 32 \
    --beam 1 \
    --sampling \
    --sampling-topk 10 \
    --temperature 0.8 \
    --nbest 1 \
    --max-len-a 10 \
    --max-len-b 200 \
    --model-overrides "{'pretrained_checkpoint':'models/pretrained_checkpoint.pt'}"

#### What's your environment?

 - fairseq Version: 0.4.0
 - PyTorch Version: 1.0.0
 - OS: Linux
 - How you installed fairseq: pip
 - Python version: 3.6.2
 - CUDA/cuDNN version: 8.0/7.6.5

**Comment by huihuifan** [comment]
thanks for your question, indeed not every story is good. The pretrained model we provide was trained with convolutional seq2seq, which is no longer the state of the art architecture (Transformer) and we have seen a lot of advancements in generation now with pretraining. It would be interesting to visit these on the story generation dataset. For this specific example, I recommend trying with a more specific or longer prompt, as this gives the model more to condition upon.
