### ISSUE TITLE
Serialization of Machine Translation Models to ONNX

### ISSUE THREAD

**Issue by bes-dev** [pytorch/fairseq#1669]
Hi,
I try to convert MT models (from WMT 2019) to ONNX, but I catch a lot of problems during this process. I experimented with a single_model pipeline.

I try to export Encoder and Decoder models separately.
**TransformerEncoder.**
The main problem with Encoder is that torch.onnx.export(...) can't work with NoneType arguments. But some arguments of TransformerEncoder get as a NoneType by default for a single model (for example, cls_input has a None type for single_model mode). To work around it, I removed all arguments with None type from interfaces. After, I apply prepare_to_onnx_export_(...) for all modules of TransformerEncoder recursively. After that model can be serialized to ONNX, but some nodes of the graph have a custom type (Aten), so, this model can't be executed using onnxruntime, TensorRT, OpenVINO etc.

**TransformerDecoder.**
Decoder has the same problems with NoneType arguments.
But after when we apply the same workarounds as in Encoder model and try to convert to ONNX, we get some errors:

* "UserWarning: ONNX export failed on ATen operator triu because torch.onnx.symbolic_opset9.triu does not exist".
This error related to TransformerDecoder.buffered_future_mask(...) function.

* "RuntimeError: Unsupported: ONNX export of Slice with dynamic inputs. DynamicSlice is a deprecated experimental op. Please use statically allocated variables or export to a higher opset version.". 
And I can't to find which module throws this error (trace broke after decoder call).

So, and I can't move forward with thуs errors. Does anybody have a positive experience in export fairseq models to ONNX?

**Comment by frankang** [comment]
it looks like you will need to export through the ATen fallback. see https://github.com/pytorch/fairseq/issues/283#issuecomment-444981538

you can also try onnx exporting on the the pytorch/translate project.

**Comment by suyuzhang** [comment]
Hi @bes-dev,
Do you export the translation model to onnx successfully?

**Comment by JohannaOm** [comment]
I have the same problem when exporting bert from pytorch to onnx. Does anyone have an idea how to fix it?

**Comment by JohannaOm** [comment]
@suyuzhang torch.onnx._export(a, b, c, opset_version=10) worked for me

**Comment by RubensZimbres** [comment]
This worked for me:

`torch.onnx.export(trained_model,
(dummy_input,dummy_input,mask1,mask2 ,"./onnx1.onnx", opset_version=10,verbose=True,
                       operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)`

**Comment by WQtong** [comment]
> This worked for me:
> 
> `torch.onnx.export(trained_model, (dummy_input,dummy_input,mask1,mask2) ,"./onnx1.onnx", opset_version=10,verbose=True, operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)`

Hi, I am struggling with exporting fairseq trained translation model to ONNX. Can you please clarify what is your dummy_input 1 and 2 here? I'm assuming original input is the text

**Comment by WQtong** [comment]
> @suyuzhang torch.onnx._export(a, b, c, opset_version=10) worked for me

Hi, I am struggling with exporting fairseq trained translation model to ONNX. Can you please clarify how to define your dummy input?
