### ISSUE TITLE
Error in command : pip install -r requirements.txt

### ISSUE THREAD

**Issue by sankuniu** [pytorch/fairseq#167]
I am sorry that when I run this command, the error shows that "Could not open requirements file: [Errno 2] No such file or Document: 'requirements.txt'" , Can anybody help me? Thank you!

**Comment by myleott** [comment]
This is the file: https://github.com/pytorch/fairseq/blob/master/requirements.txt.

You can try running `pip install cffi numpy torch tqdm` directly instead.

**Comment by sankuniu** [comment]
Thank you very much！
Besides that,  you'd better run this command under the ~/pytorch.
z@z-MS-7A69:~/pytorch$ pip install -r requirements.txt
Requirement already satisfied: pyyaml in /home/z/anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (3.12)
Requirement already satisfied: typing in /home/z/anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (3.6.2)
