### ISSUE TITLE
-bash: fairseq-interactive: command not found

### ISSUE THREAD

**Issue by fenimi** [pytorch/fairseq#1674]
## 🐛

I'm getting this error: 
 fairseq-interactive: command not found.

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run '> MODEL_DIR=wmt14.en-fr.fconv-py
> fairseq-interactive \
    --path $MODEL_DIR/model.pt $MODEL_DIR \
    --beam 5 --source-lang en --target-lang fr \
    --tokenizer moses \
    --bpe subword_nmt --bpe-codes $MODEL_DIR/bpecodes'
2. See error

### Environment

 - fairseq Version (e.g., 1.0 or master): fairseq-master
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux): server
 - How you installed fairseq (`pip`, source): cloned github
 - Build command you used (if compiling from source):
 - Python version: 3
 - CUDA/cuDNN version: 
 - GPU models and configuration:
 - Any other relevant information:

**Comment by erip** [comment]
What does `python -c "import fairseq"` yield?

**Comment by pipibjc** [comment]
@fenimi, did you install fairseq through pip like [1]? Just cloning github repository won't install `fairseq-interactive` interface.

[1] https://github.com/pytorch/fairseq#requirements-and-installation

**Comment by Hadik123** [comment]
Hello, I have the same issue when installing everything accordingly it shows the same error. As a first thing I have used 
pip install fairscale. And based on comment from @erip I am getting:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/content/fairseq/fairseq/__init__.py", line 21, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/content/fairseq/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/content/fairseq/fairseq/distributed/fully_sharded_data_parallel.py", line 15, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/content/fairseq/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/content/fairseq/fairseq/dataclass/configs.py", line 12, in <module>
    from omegaconf import II, MISSING
ModuleNotFoundError: No module named 'omegaconf'
