### ISSUE TITLE
Releasing mBART

### ISSUE THREAD

**Issue by stephanpeitz** [pytorch/fairseq#1676]
Hi Fairseq team,

are you plaining to release mBART25 described in [(Liu et al., arXiv 2020)](https://arxiv.org/pdf/2001.08210v2.pdf)?

Cheers,
Stephan

**Comment by pipibjc** [comment]
Duplicate of #1670

**Comment by hamediramin** [comment]
Yes would love to see what happens here

**Comment by yinhanliu** [comment]
https://github.com/pytorch/fairseq/commit/5e79322b3a4a9e9a11525377d3dda7ac520b921c

**Comment by yinhanliu** [comment]
@hamediramin  @stephanpeitz @pipibjc  It is opensourced here https://github.com/pytorch/fairseq/tree/master/examples/mbart

**Comment by stephanpeitz** [comment]
Thanks for letting us know!
