### ISSUE TITLE
special token breaks after tokenization

### ISSUE THREAD

**Issue by Atomu2014** [pytorch/fairseq#1680]
#### What is your question?

I'm using wmt19.en2de and wmt19.de2en pre-trained translation models to translate my corpus 

I get some results like:
(1). '1 <unk> 10'
(2). 'if you don &apos;t believe me , see for yourself .'

When I evaluate the results to obtain some scores, I find some special tokens are not recognized. Here are the step-by-step tokenization results:
(1)
input:
1 <unk> 10
moses:
1 &@@ lt@@ ; unk &gt; 10
indexed string:
1 &@@ lt@@ ; unk &gt; 10

(2)
input:
if you don &apos;t believe me , see for yourself .
moses:
if you don &amp; ap@@ os ; t believe me , see for yourself .
indexed string:
if you don &amp; ap@@ os ; t believe me , see for yourself .

It seems these models depend on MosesTokenizer, which will break special tokens like '<unk>' and '&apos;' into pieces before indexing with language dictionaries.

I think this is wired since these models cannot recognize their outputs. I wonder if there are or there will be some quick fixes to this small issue.

**Comment by myleott** [comment]
How are you loading the model and running Moses tokenizer and BPE? Are you using the hub interface or something else?

**Comment by Atomu2014** [comment]
Hi,

My code is based on fairseq-interactive, which uses "TranslationTask" to load model and process input.

(1) load model (wmt19.en-de.single)
```
from fairseq import checkpoint_utils, utils
task = TranslationTask.setup_task(args)
models, _model_args = checkpoint_utils.load_model_ensemble(
      args.path.split(os.pathsep),
      arg_overrides=eval(args.model_overrides),
      task=task,
)
```

(2) process source & target language examples for scoring
```
from fairseq.data import encoders
# tokenizer = moses
tokenizer = encoders.build_tokenizer(args)
# bpe = fastbpe
bpe = encoders.build_bpe(args)

def encode_fn(x):
    # replace html tokens, e.g., &apos; -> '
    # x = clean_web_text(x)
    if tokenizer is not None:
      x = tokenizer.encode(x)
    if bpe is not None:
      x = bpe.encode(x)
    # recover <unk>
    # x = x.replace('&@@ lt@@ ; unk &gt;', '<unk>')
    return x

def make_batches(src_lines, tar_lines):
    src_tokens = []
    tar_tokens = []
    for src_str, tar_str in zip(src_lines, tar_lines):
      src_tokens.append(task.source_dictionary.encode_line(
        encode_fn(src_str), add_if_not_exist=False
      ).long())
      tar_tokens.append(task.target_dictionary.encode_line(
        encode_fn(tar_str), add_if_not_exist=False
      ).long())
```

Code:
[fairseq_tasks.zip](https://github.com/pytorch/fairseq/files/4177566/fairseq_tasks.zip)

Command:
python nmt.py
