### ISSUE TITLE
BART attn_mask unused

### ISSUE THREAD

**Issue by sshleifer** [pytorch/fairseq#1682]
Does anyone know why `attn_mask` is not passed to `self.self_attn` after https://github.com/pytorch/fairseq/blob/4e48c4ae5da48a5f70c969c16793e55e12db3c81/fairseq/modules/transformer_layer.py#L84?

**Comment by myleott** [comment]
It's a bug, but not a major one since this parameter isn't usually passed in. See #1339. We had a fix but it didn't get merged... I'll merge one now.
