### ISSUE TITLE
conv_tbc

### ISSUE THREAD

**Issue by Johnzdh** [pytorch/fairseq#169]
I'm wondering why not just using Conv1d instead of conv_tbc？I saw you answered Conv1d was slower, but why? 
Thanks!

**Comment by myleott** [comment]
The input shape for Conv1d is batch x channels x time, which would require a transpose since the rest of the network operates with time x batch x channel tensors. conv_tbc takes time x batch x channel input directly.

**Comment by Johnzdh** [comment]
Is this the only difference?

**Comment by Johnzdh** [comment]
@myleott  Is this the only difference?

**Comment by myleott** [comment]
Yep, that's the only difference.
