### ISSUE TITLE
How do we expose fairseq translation model to be used by client ?

### ISSUE THREAD

**Issue by aj7tesh** [pytorch/fairseq#1694]
I could not find any smarter way to expose fairseq model for translation. Generate and interactive.py doesnt seem to of much help when lets say when to deploy it as a server

**Comment by lematt1991** [comment]
I would recommend using the torch hub.  [Here](https://github.com/pytorch/fairseq/tree/master/examples/translation#example-usage-torchhub) is an example of how to load both one of our released models, as well as loading a custom model that you've trained.  Hope this helps!

**Comment by erip** [comment]
There is no open-source torch hub, though, is there?

**Comment by lematt1991** [comment]
There is.  The link I provided gives an example of how to use it (or maybe I don't understand your question).

**Comment by erip** [comment]
I mean a torch hub that I can deploy on my own hardware. Some folks can't upload their models to arbitrary web services. :smile:

**Comment by lematt1991** [comment]
Sure, but you can load a local checkpoint (as the second example I linked shows).  The reason I suggest using this is it wraps up tokenization, BPE encoding, model forward pass, decoding, and converting back to a string all in a single function call.
