### ISSUE TITLE
Dynamic prediction/translation

### ISSUE THREAD

**Issue by aj7tesh** [pytorch/fairseq#1698]
Is it possible to dynamically change the output of a translation (in an interactive fashion)? For example:
lets say I have one input sentence "I love English."
Lets say my model give translation of this sentence as "W1W2W3W4" (here W1,W2,W3,W4 are words/tokens in the sequence predicted by machine translation model)
Lets say I think in place of W2 some word W5 should be there. Can I give suggestion or recommendation based upon probability that after W1 (W2,W5,W6 can come) and if I choose W6 then again I can say in the third position W3 or W7 or W8 etc. can come based on probability.

**Comment by lematt1991** [comment]
No, this is not available in fairseq.  If you'd like to modify/play around with the output probabilities in some customized way, modifying the `lprobs` [here](https://github.com/pytorch/fairseq/blob/master/fairseq/sequence_generator.py#L278) is probably the best place to do it.

**Comment by aj7tesh** [comment]
@lematt1991 Actually I wish to generate the new output if I change a token. Lets say if my model fives w1w2w3w4w5 as the original output. Then it might be possible that while decoding if I replace w3 with some w7 then I might get some output as w1w2w7w8w9w10 . How can Ii experiment this thing?
