### ISSUE TITLE
the problem of attn_scores and avg_attn_socres

### ISSUE THREAD

**Issue by travel-go** [pytorch/fairseq#170]
Hello,In the last page of your paper, you showed your intention score in the form of some pictures.I also draw some pictures about attention scores. when I use attn_scores as my attention scores on every layers, the pictures is very strange.Then I use avg_attn_scores as my attention scores,it will be better,but it cannot exhibit a linear alignment,it looks disorganized.
Should I use avg_attn_socres as my attention score?
Why the picture used attn_scores so strange like it focus on one word or few words
this your code
            if attention is not None:
                x = self._transpose_if_training(x, incremental_state)

                x, attn_scores = attention(x, target_embedding, (encoder_a, encoder_b),i)
                attn_scores_ = attn_scores / num_attn_layers

                if avg_attn_scores is None:
                    avg_attn_scores = attn_scores
                else:
                    avg_attn_scores.add_(attn_scores)

**Comment by huihuifan** [comment]
What task are you training on? The attention is not necessarily linearly aligned for all tasks. What model are you training?

**Comment by travel-go** [comment]
I am using a parallel corpus from Chinese into English.Then when the attention picture drawed,I load the best model.
I see you used the parallel corpus of de-en.
Should I use avg_attn_socres as my attention score?
Why the picture used attn_scores so strange like it focus on one word or few words?
