### ISSUE TITLE
Enable per-token classification in RoBERTa

### ISSUE THREAD

**Issue by prihoda** [pytorch/fairseq#1708]
## 🚀 Feature Request
Enable per-token classification in RoBERTa (also called "sentence tagging" or "sequence tagging" in the original BERT paper)

### Motivation
Currently, you can only classify whole sentences using RoBERTA. There are many usecases for wanting to classify each input token.

### Pitch
Add `--classify-per-token` or similar flag to `sentence_prediction` task and ensure that the classification head and `sentence_prediction` loss can handle processing all tokens.
-- edit: Settled on creating separate `sequence_tagging` task and criterion

### Alternatives
Using the translation task and a different architecture.

### Additional context
https://arxiv.org/abs/1810.04805 (search "tagging")

**Comment by myleott** [comment]
A sequence tagging task would be helpful. I'd prefer not to complicate the existing sentence_prediction.py task, but please feel free to copy/paste into sequence_tagging.py and adapt as needed.

**Comment by prihoda** [comment]
Cool, so there should be a `sequence_tagging` task and `sequence_tagging` criterion?

**Comment by prihoda** [comment]
@myleott I updated the PR accordingly: https://github.com/pytorch/fairseq/pull/1709

**Comment by apyspo** [comment]
Hi, can we use [#1709](https://github.com/pytorch/fairseq/pull/1709), since this feature not merged yet and closed.
I really need this feature (token level classification) for my thesis on target based sentiment analysis.
