### ISSUE TITLE
Is option `--iter-decode-with-external-reranker` available for fairseq-interactive?

### ISSUE THREAD

**Issue by TingxunShi** [pytorch/fairseq#1715]
### What is your question?

From the document it seems there is an option `--iter-decode-with-external-reranker`, shared by fairseq-generate and fairseq-interactive. But when I ran the command with it, I was prompted the option is not available. 

```
fairseq-interactive: error: unrecognized arguments: --iter-decode-with-external-reranker
```

My task is `translation` and the model architecture is transformer big. Command is copied as below

My question is:

1. Is this option available for translation task and fairseq-interactive command?
2. If not, how do I rerank the translation results according to a trained LM model automatically? (Of course I can use `nbest` to generate several possible candidate translations then use a trained LM model to score them, but I wonder whether there is a simpler way)

### What's your command?

```
fairseq-interactive data_bin/ \
  --input src.txt \
  --source-lang zh \
  --target-lang en \
  --path mt_ckpt/checkpoint_best.pt:lm_ckpt/checkpoint_best.pt \
  --batch-size 64 --buffer-size 128 --beam 10  \
  --iter-decode-with-external-reranker 
```

### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.9
 - PyTorch Version (e.g., 1.0): 1.3
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.3
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: tesla V100 32G
 - Any other relevant information:

**Comment by myleott** [comment]
That option is only relevant for the `translation_lev` task. We should update the CLI to only expose it in that case...

More details here: https://github.com/pytorch/fairseq/tree/master/examples/nonautoregressive_translation

**Comment by TingxunShi** [comment]
So per my understanding, for normal `translation` task, I need to generate several candidates and manually invoke a LM model to score them, no simpler ways?

**Comment by myleott** [comment]
You can look at this example for reranking: https://github.com/pytorch/fairseq/tree/master/examples/noisychannel

**Comment by TingxunShi** [comment]
OK, thanks for the help!

**Comment by myleott** [comment]
Keeping this open to track moving the `--iter-decode-*` options into the corresponding task.
