### ISSUE TITLE
In the vocab of bart.bpe.bpe.decoder,  what does Ġ mean for those words prefixed with 'Ġ'?

### ISSUE THREAD

**Issue by v381654729** [pytorch/fairseq#1716]
#### What is your question?

In the vocab of bart.bpe.bpe.decoder,  what does Ġ mean for those words prefixed with 'Ġ'?

#### Code

    keywords = { "checkpoint_file" : "model.pt"}
    bart = BARTModel.from_pretrained(config_translation_zh_en.bart_english_directory,   **keywords )
    # bart.bpe.bpe.decoder is a dict, and it contains many 'strange' words like 'Ġthe' 'Ġand' 'Ġof' and also many normal words like 'playing' 'bound' etc. 
![image](https://user-images.githubusercontent.com/43415394/74647258-52024680-51b6-11ea-97dd-4631e0404d17.png)

bart.bpe.bpe.decoder is a dict, and it contains many 'strange' words like 'Ġthe' 'Ġand' 'Ġof' and also many normal words like 'playing' 'bound' etc. At first glance, words prefixed with Ġ seem to be complete words and words not prefixed with Ġ are incomplete words (like BertTokenizer's ##-prefixed words ) like 'ing' 'th' and ''re'. However, a high proportion of words not prefixed with Ġ seem not incomplete words, like frequency, relation, etc. 

#### Question

What does Ġ mean for those words prefixed with 'Ġ'?  And how does the tokenizer of BART tokenize with the set of 50265-word vocabulary (bart.task.source_dictionary, 50257 (integer) words of which map to bart.bpe.bpe.decoder)? I haven't found documentations on the Internet or in the codes.

**Comment by dungtn** [comment]
I'm having the same question. Further debugging `fairseq.data.encoders.gpt2_bpe_utils` showed that the 'Ġ' prefix was caused by a leading space when split the sentence using `re.findall(...)`. In particular, the word 'friends' and '[space]friends' will be encoded differently by BPE, the later with 'Ġ' prefix. 

I wonder if this is a bug or a feature? And why?

**Comment by lematt1991** [comment]
CC @myleott @ngoyal2707

**Comment by Borchmann** [comment]
It's the encoded space character.

**Comment by myleott** [comment]
Yep, @Borchmann is correct, this corresponding to spaces in the byte-level BPE.
