### ISSUE TITLE
Create a conda recipe

### ISSUE THREAD

**Issue by erip** [pytorch/fairseq#1717]
## 🚀 Feature Request

`fairseq` should be available from the pytorch conda channel.

### Motivation

In order to install fairseq currently, a C++ compiler with loads of native dependencies and linked libraries is a requirement.  This is a heavy dependency in some runtimes.

### Pitch

A conda recipe for `fairseq` should be created which targets the three big umbrella runtimes: `linux`, `os x`, and `win64`. These artifacts should have CPU and GPU versions for all supported pythons to mirror [other pytorch conda artifacts](https://anaconda.org/pytorch/).

### Alternatives

fairseq could be made available through pypi with precompiled `.whl`s to avoid fiddliness of compiling from source.

**Comment by lematt1991** [comment]
I agree this would be great

> In order to install fairseq currently, a C++ compiler with loads of native dependencies and linked libraries is a requirement. This is a heavy dependency in some runtimes.

Are there really loads of C++ dependencies?  I think all of our non-python code should be pretty self-contained.

**Comment by erip** [comment]
Sorry, I meant system dependencies (i.e., a compiler). Not literal package dependencies
