### ISSUE TITLE
Should `apply_sparse_mask` in multihead_attention be a no-op?

### ISSUE THREAD

**Issue by jayded** [pytorch/fairseq#1719]
### Before asking:   
1. search the issues.   
2. search the docs.    

I couldn't find any mention of `apply_sparse_mask` in https://github.com/pytorch/fairseq/issues?utf8=%E2%9C%93&q=apply_sparse_mask

#### What is your question?

Should `apply_sparse_mask` in `multihead_attention.py` (https://github.com/pytorch/fairseq/blob/master/fairseq/modules/multihead_attention.py#L429) be a no-op?

I also don't understand why this masking method is needed at all.

#### Code

```
    def apply_sparse_mask(attn_weights, tgt_len: int, src_len: int, bsz: int):
        return attn_weights
```

#### What have you tried?
Searching the docs and issues.

#### What's your environment?

 - fairseq Version master
 - PyTorch Version 1.4 (N/A)
 - OS (e.g., Linux): ubuntu 18.04
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): `python setup.py build_ext --inplace`
 - Python version: 3.6.10 (Anaconda)
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: 2080TI/1080TI
 - Any other relevant information:

**Comment by myleott** [comment]
It's just a hook to modify the attention weights, since we have a few internal users who extend MultiheadAttention.

But in general the MHA interface has gotten very messy... I'm working on replacing it with a cleaner one soon.

**Comment by isVoid** [comment]
> But in general the MHA interface has gotten very messy... I'm working on replacing it with a cleaner one soon.

Do you have an estimated time when this will get replaced? Thanks.
