### ISSUE TITLE
How to pre-train the bert-base model？ 

### ISSUE THREAD

**Issue by playing-code** [pytorch/fairseq#1723]
## ❓ Questions and Help
I did not find an example to reproduce pre-training bert model, including data processing and model training. Can you provide a script?

**Comment by myleott** [comment]
We provide instructions for pretraining roberta-base, which is very similar to bert: https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md

We don't plan to provide instructions for pretraining bert.
