### ISSUE TITLE
some tutorial about distillation dataset

### ISSUE THREAD

**Issue by hljjjmssyh** [pytorch/fairseq#1736]
Hi!
Now, I am focusing on the non-autoregressive model for translation. I want to distill some other datasets. I have trained a teacher model using Transformer. But I don't know how to save the generated data. Could you give me some suggestions?

**Comment by myleott** [comment]
@MultiPath

**Comment by Ir1d** [comment]
I tried `fairseq-generate data-bin/wmt17_en_de_joined --path checkpoints/transformer_vaswani_wmt_en_de_big/checkpoint_best.pt --batch-size 64 --beam 5 --remove-bpe --gen-subset train --results-path data-bin/wmt17_en_de_distill` but no result file was generated in anywhere..
Have you found out how to generate the distillation dataset?
