### ISSUE TITLE
What are the supposed keys in the extra_state dictionary in the save_checkpoint() method?

### ISSUE THREAD

**Issue by ajesujoba** [pytorch/fairseq#1737]
I am trying to save a checkpoint using the `save_checkpoint()`, in the function signature given as `save_checkpoint(self, filename, extra_state):` there is a `extra_state`. Is there a way to get this(dictionary) from a trainer object? I found out that from ` def load_checkpoint()` the following `extra_state["metrics"]` and `extra_state["train_iterator"]["epoch"]` which means `metric `and `train_iterator` are keys in the `extra_state` dictionary. Is there a place the keys were defined? Are `metric `and `train_iterator` just the keys needed?

**Comment by myleott** [comment]
The main entry point for saving/loading checkpoints in train.py is checkpoint_utils.save_checkpoint/load_checkpoint. These call into trainer.save_checkpoint, but also populate extra_state with the state of the training iterator.

The relevant code is here: https://github.com/pytorch/fairseq/blob/master/fairseq/checkpoint_utils.py#L23-L158
