### ISSUE TITLE
How can we save the prediction results on valid during training?

### ISSUE THREAD

**Issue by yuchenlin** [pytorch/fairseq#1738]
### Before asking:   
1. search the issues.   
done
2. search the docs.    
donee

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
This isn't supported currently, but if you wanted you could modify `valid_step` and `reduce_metrics` in the relevant Task to do this.

It's not directly comparable, but you can see how we compute validation BLEU for the translation task to see how to do this: https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/translation.py#L266-L316

**Comment by villmow** [comment]
https://github.com/pytorch/fairseq/blob/adb5b9c71f7ef4fe2f258e0da102d819ab9920ef/fairseq/tasks/translation.py#L368

At this line the first sample of a batch is logged and printed. Couldn't you just print or log everything into a specific file at this point?

**Comment by villmow** [comment]
Just hijacking this issue for a related question/bug!

I use the validation with BLEU on my own task (sub-class of translation, only loading a different dataset) and consistently get lower bleu scores for validation during training (~14), than I get when I run fairseq-generate on the same task and validation dataset (~23). 

Any idea on that @myleott , or should I open a new issue?

**Comment by myleott** [comment]
> Any idea on that @myleott , or should I open a new issue?

New issue please?
