### ISSUE TITLE
Batch generation of  sentences with different lengths!

### ISSUE THREAD

**Issue by mali-nuist** [pytorch/fairseq#174]
I want to use batch generation to decrease the inference time. 
 So I used the collate_tokens method to transform sentences to ids and added pad to left to short sentences to make them  in same length during inference just like the training time. 
And then executed the translator.generate to translate the batch sentences with different lengths . The program works normal but the translations result is bad and quiet different from single sentence translation

My Question is that the fairseq seems  supporting the batch inference of different size sentences[ **training period allows different lengths sentences in one batch, though the training corpus had been sorted**],   why the result is so bad ? Do i need to train the model without sorting the training data ? Or, it should works but just because i made some mistakes, resulting the bad results ? Or, i should not use the batch in inference ... thanks ...

**Comment by myleott** [comment]
It's a bit complicated to make this work, but it is implemented in a forthcoming update to fairseq! Stay tuned!

**Comment by mali-nuist** [comment]
thanks
