### ISSUE TITLE
Fairseq mult-GPU training fails when we train with two data loaders.

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#1746]
I have a task where I need to load data from two data loaders. For that, I initialized another iterator and use the Zip function to extract data from both iterators. It works 100% fine on a single GPU setting. But when it comes to multi-GPU there are lost of issues like data extraction is not stable.

**Comment by myleott** [comment]
Can you please clarify what issues you're seeing? And also clarify what exactly you're doing? Having multiple data loaders should be fine, assuming you're doing it at the Dataset level.

If you're trying to create multiple EpochBatchIterator objects, then you need to be careful about boundary conditions when the number of batches doesn't evenly divide the number of GPUs. I'd recommend doing this at the Dataset level and to use a single EpochBatchIterator.

**Comment by myleott** [comment]
I think you're looking for RoundRobinZipDatasets: https://github.com/pytorch/fairseq/blob/master/fairseq/data/round_robin_zip_datasets.py

This will zip multiple FairseqDataset objects and repeat the shorter one to match the length of the longest one.

**Comment by shamanez** [comment]
Thank a lot.

Actually , there are several errors. Sometimes the program just stops without showing any further improvement. 

"If you're trying to create multiple EpochBatchIterator objects, then you need to be careful about boundary conditions when the number of batches doesn't evenly divide the number of GPUs. "

Yes this is the problem I guess. When getting data from each iterator it gets very unstable.

**Comment by shamanez** [comment]
Is there any example use of this round_robbin_zip wrapper?

**Comment by myleott** [comment]
Take a look at the multilingual_translation task.

We first create separate datasets for each language pair and wrap this in RoundRobbinZipDatasets: https://github.com/pytorch/fairseq/blob/3ba384cc6c58a139f0ccfbc4e7f183e7c4dfd839/fairseq/tasks/multilingual_translation.py#L216-L222

Then in train_step, `sample` will be a dictionary containing each batch keyed accordingly: https://github.com/pytorch/fairseq/blob/3ba384cc6c58a139f0ccfbc4e7f183e7c4dfd839/fairseq/tasks/multilingual_translation.py#L265-L282

**Comment by shamanez** [comment]
Thanks a lot.

**Comment by shamanez** [comment]
@myleott  Is that ok if I send data from both data sets to the model at the same time.  Especially for the following [line](https://github.com/pytorch/fairseq/blob/3ba384cc6c58a139f0ccfbc4e7f183e7c4dfd839/fairseq/tasks/multilingual_translation.py#L270). 

My idea is not to use a for loop but check whether the batches from both datasets present and then sending it to the network.
