### ISSUE TITLE
Reduce buffer size

### ISSUE THREAD

**Issue by antoajayraj** [pytorch/fairseq#175]
Hi,
why is the buffer_size set to 10MB ? Can that be increased and is there any implication with the same

def all_reduce_and_rescale_tensors(tensors, rescale_denom, buffer_size=10485760):
    """All-reduce and rescale tensors in chunks of the specified size.

**Comment by myleott** [comment]
You can increase it. It will cause more memory usage for the buffer, but may be slightly faster. We've reworked this a bit in a forthcoming fairseq update, and set the buffer size to the number of model params automatically (i.e., there's only a single all-reduce call per update).

**Comment by antoajayraj** [comment]
thanks for the info @myleott
