### ISSUE TITLE
How can I finetune XLM-R for neural machine translation between the same language(Catalan to Catalan-with different grammar structure))?

### ISSUE THREAD

**Issue by JohnasSolomon** [pytorch/fairseq#1751]
Can I use XLM-R to do something similar to https://www.guru99.com/seq2seq-model.html
(encoder-decoder architecture or any other way that perform good in small dataset - around 1000)
For example:
**Input**: He sells food(in Catalan)
**Output**: Food he sells(in Catalan)

**Comment by lematt1991** [comment]
Please follow the issue templates.
