### ISSUE TITLE
Processing CNN/DM dataset

### ISSUE THREAD

**Issue by lioutasb** [pytorch/fairseq#1753]
I'm trying to reproduce the results from the [Lightweight convolution paper ](https://arxiv.org/pdf/1901.10430.pdf) on the abstractive summarization. I'm looking for a script or the steps to process the CNN/DM dataset with Fairseq. I tried to google it but I wasn't able to find any information on how to preprocess the data. The raw data contain multi-sentence summaries so I'm not sure how I'm supposed to handle them and let the decoder generate all of them.

Any help is appreciated.

**Comment by sseol11** [comment]
Hi @lioutasb, I have same problem. Do you solve this?
