### ISSUE TITLE
Preprocessing when fine tune mBART

### ISSUE THREAD

**Issue by xinyuzhao** [pytorch/fairseq#1756]
## ❓ Questions and Help

From the paper, it seems that for both training and inference we need to append `language id` after each input sentence. Is this true? Do we need to add this before doing BPE?

**Comment by yinhanliu** [comment]
@xinyuzhao Yes, it is True.  The language id is added in the code (in fairseq/task/denoising). BPE was done before running the code. The answer to your question is no. We don't need to add this before BPE.
