### ISSUE TITLE
Bart: Expected Rouge Score

### ISSUE THREAD

**Issue by sshleifer** [pytorch/fairseq#1765]
I ran bart.sample on the whole cnn_dm/test.source, then `stanford-corenlp-3.9.2-models.jar` to tokenize, then files2rouge and got 
0.21074 (95%-conf.int. 0.20822 - 0.21314)

the README says "expected output: (ROUGE-2 Average_F: 0.21238)"

Were there any evaluation preprocessing steps that aren't in the README that contributed to that result? Leading spaces/etc? I don't think the stanford tokenizer has changed much since the version 3.7.2 used in the README.

This is obviously a very minor discrepancy, so let me know if this is expected behavior.

Thanks in Advance!

**Comment by yinhanliu** [comment]
Did you follow the data processing in the linked Issue in readme?

**Comment by yinhanliu** [comment]
em.... I see your number. there Is actually another trick to make the number higher.
https://github.com/pytorch/fairseq/blob/c699eb054e2782e2ae4e1d85d1fff5a724dc5c0e/fairseq/sequence_generator.py#L280
add two lines 1) force the first generated token to be bos 2) force the second token to not be bos.
