### ISSUE TITLE
sequence_scorer.py documentation question

### ISSUE THREAD

**Issue by zhenduow** [pytorch/fairseq#1768]
I see in sequence_scorer.py that the hypo['score'] is computed using the target index. Is hypo['score'] the average log probability of the target/reference token in each decoder step?

**Comment by myleott** [comment]
Yes exactly

**Comment by zhenduow** [comment]
> Yes exactly

Thank you! It's a good feature to have!

**Comment by zhenduow** [comment]
Hi, I find that the scores are incredibly high (with > -0.01 avg log probability for every summarization on CNN/daily dataset). 

That makes me confused. Is the score the probabilities of the model's own generation or the target/gold reference? (I believe it actually computes the probability of the model's own generation.) 

As you answered, it should compute the other. The sequence_scorer.py also uses variable 'orig_target', which implies that some sort of generation reference is used as a target for that purpose. But the whole inference code snippet (see below) for text summarization does not seem to have any source of the gold reference as input.  Is this a sign that fairseq handles each nlg task dataset differently? Or am I missing something?

the bart evaluation code snippet:
`bart = torch.hub.load('pytorch/fairseq', 'bart.large.cnn')
bart.cuda()
bart.eval()
bart.half()
count = 1
bsz = 32
with open('test.source') as source, open('test.hypo', 'w') as fout:
    sline = source.readline().strip()
    slines = [sline]
    for sline in source:
        if count % bsz == 0:
            with torch.no_grad():
                hypotheses_batch = bart.sample(slines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)

            for hypothesis in hypotheses_batch:
                fout.write(hypothesis + '\n')
                fout.flush()
            slines = []

        slines.append(sline.strip())
        count += 1
    if slines != []:
        hypotheses_batch = bart.sample(slines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)
        for hypothesis in hypotheses_batch:
            fout.write(hypothesis + '\n')
            fout.flush()`

So, essentially, I am wondering if fairseq gives the probabilities of the gold reference tokens instead of the model's own generations.

**Comment by myleott** [comment]
Oh, you said sequence_scorer.py originally :) sequence_scorer.py gives the score of the target/reference.

But above you're using `bart.sample`, which calls into sequence_generator.py. sequence_generator.py will produce model outputs and give you the scores of those.

**Comment by zhenduow** [comment]
> Oh, you said sequence_scorer.py originally :) sequence_scorer.py gives the score of the target/reference.
> 
> But above you're using `bart.sample`, which calls into sequence_generator.py. sequence_generator.py will produce model outputs and give you the scores of those.

Yes, I figured out and called the functions accordingly. Thank you very much!

**Comment by yuchenlin** [comment]
Hi @zhenduow and @myleott , 

Thanks for the discussion. I was wondering what would be an example like, if we want to score the references of a fine-tuned BART model? 

Like you have talked about, `bart.sample` calls `sequence_generator.py`, is there something like `bart.score` which calls `sequence_scorer.py`?

**Comment by sh2439** [comment]
Hi @zhenduow 
Do you happen to remember how to modify the script to output the probability of the sentence? Thanks a lot!
