### ISSUE TITLE
vq-wav2vec pretrained parameter counts

### ISSUE THREAD

**Issue by david-macleod** [pytorch/fairseq#1771]
## 📚 Documentation

The vq-wav2vec README.md states the following parameter counts for the pre-trained models:

vq-wav2vec K-means = **321**M
Roberta on K-means codes = **1006**M

However when I load the models I get **33**M and **105**M respectively by running `sum(x.numel() for x in model.parameters())`. Is this a typo in the docs or is my method for counting parameters incorrect?

Thanks

**Comment by erip** [comment]
Technically you should only add `x.numel()` if `x.requires_grad`, but that would filter your number of parameters further.

**Comment by shamanez** [comment]
I also checked , the roberta model they use is similar to small BERT architecture  with 12 players.

**Comment by alexeib** [comment]
sorry, those are not parameters, that the size of the checkpoints in megabytes. my bad, ill update it soon

**Comment by shamanez** [comment]
@alexeib ,

Can you please clarify this question too. 

https://github.com/pytorch/fairseq/issues/1793
