### ISSUE TITLE
Some help

### ISSUE THREAD

**Issue by tuhinjubcse** [pytorch/fairseq#1772]
| WARNING: 42318 samples have invalid sizes and will be skipped, max_positions=(1024, 1024), first few sample ids=[34357, 67457, 50709, 72949, 133395, 15358, 47438, 193356, 10477, 179217]

https://github.com/pytorch/fairseq/blob/master/fairseq/data/data_utils.py#L193

I ensured from the bpe file that i chop source and target entries greater than 1024 for both since
max_positions=(1024, 1024) still getting this warning. Not sure why ?

Is there anyway I can still have these  42318 but limit their size to 1024 , 1024 if either of the dimensions exceed 

Environment
fairseq Version (e.g., 1.0 or master): 0.9.0
PyTorch Version (e.g., 1.0) 1.3.1
OS (e.g., Linux): Linux
How you installed fairseq (pip, source):
Build command you used (if compiling from source):
Python version: 3.7.3
CUDA/cuDNN version: 10.1.243
GPU models and configuration: RTX 2080 ( 4 gpus)

**Comment by tuhinjubcse** [comment]
@myleott @ngoyal2707

**Comment by myleott** [comment]
> I ensured from the bpe file that i chop source and target entries greater than 1024

Note that fairseq will append an end-of-sentence symbol, so if doing this in preprocessing then you need to truncate at 1023.

> Is there anyway I can still have these 42318 but limit their size to 1024 , 1024 if either of the dimensions exceed

There is an option called `--truncate-source` that should work, but seems it's only implemented for the source side: https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/translation.py#L177-L178

You could extend it to work on the target side too...

**Comment by tuhinjubcse** [comment]
Hi
Myle

I added this. Thanks for your help and seems to resolve now , however , i constantly get OOM

| OOM: Ran out of memory with exception: CUDA out of memory. Tried to allocate 198.00 MiB (GPU 0; 10.76 GiB total capacity; 9.69 GiB already allocated; 145.12 MiB free; 407.50 MiB cached)
| WARNING: attempting to recover from OOM in forward/backward pass

I changed UPDATE_FREQ=1 still same issue persists
Any way to bypass the OOM, i understand batch size depends on MAX_TOKENS and  UPDATE_FREQ 

When I give  MAX_TOKENS < 1024 , it again gives me the "samples have invalid sizes and will be skipped"  
Under such situations whats the best way to handle this ?

**Comment by myleott** [comment]
`--update-freq` will accumulate gradients by doing multiple forward/backward passes, so shouldn’t affect memory usage.

`--max-tokens` controls the max batch size per GPU, so lowering that can avoid OOM.

There’s also `--max-source-positions` and `--max-target-positions`, which control the maximum sequence length and default to 1024. You can adjust these, but it probably won’t help. If you have sentences that are very long (>1000 tokens), but you can only fit at most 1000 tokens, then fairseq will have to filter those examples that are too long, which is the warning you’re seeing.

I’m curious why you’re running out of memory though. How many parameters are in your model? It should be logged right after the model is printed.

**Comment by tuhinjubcse** [comment]
| model bart_large, criterion LabelSmoothedCrossEntropyCriterion
| num. model params: **406290432** (num. trained: 406290432)
| training on 1 GPUs
| max tokens per GPU = 1024 and max sentences per GPU = None

**Comment by tuhinjubcse** [comment]
@myleott  , then fairseq will have to filter those examples that are too long, which is the warning you’re seeing ,

Re this: how bout not filter them but I chop off the length, that way I can still learn something meaningful from those sentences.

I could not do --max-source-positions and --max-target-positions less than 1024 for BART as it gave me size inconsistencies, since BART large is 1024 features so it probably expects it for dimension homogeneity

**Comment by myleott** [comment]
Which task are you using? While you can't adjust `--max-source-positions` or `--max-target-positions`, since those are used to initialize the BART positional embeddings, you can manually tell the batch generator (TokenBlockDataset) to generate smaller batches by editing:
https://github.com/pytorch/fairseq/blob/adb5b9c71f7ef4fe2f258e0da102d819ab9920ef/fairseq/tasks/denoising.py#L130-L138

If you change the `self.args.tokens_per_sample - 2` line to something smaller, then it will generate smaller token blocks.

**Comment by sajastu** [comment]
@myleott Same here. I switched on single GPU as to your suggestion, but still, I'm getting `| OOM: Ran out of memory with exception: CUDA out of memory.`. I guess the default `--max-source-positions` is `1024` in BART model. And with regard to the readme for CNN/DM, I first used `--max-tokens 2048. Have been playing around with `--max-tokens` to the lowest number I have tried (`768`), but still I'm getting stuck in this error. Do you have any suggestion? Also, would you please elaborate on the differences between `--max-tokens` and `--max-source-positions`? 

**Note** my input documents are reasonably long (the introduction part of scientific papers).
