### ISSUE TITLE
Error preprocessing multi-lang translation: prepare-iwslt17-multilingual.sh

### ISSUE THREAD

**Issue by kaiidams** [pytorch/fairseq#1777]
## 🐛 Bug

`bash prepare-iwslt17-multilingual.sh` fails with errors.

```
FileNotFoundError: [Errno 2] No such file or directory: './iwslt17.de_fr.en.bpe16k/valid.fr-en.fr'
```

### To Reproduce

```
cd examples/translation
bash prepare-iwslt17-multilingual.sh
```

#### Code sample

Did not change fairseq code

### Expected behavior

The script should succeed without error

### Environment

 - fairseq Version (e.g., 1.0 or master): master (commit cb2dc414c692d7de283bec4e4f9c923a66205792)
 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): `pip install --editable .`
 - Python version: 3.7.5
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: NVIDIA K80
 - Any other relevant information:

### Additional context

The script produces files named such as `valid0.fr-en.fr`, `valid1.fr-en.fr`, ..., however later the script expects `valid.fr-en.fr` without an index number. 
The change is by the commit 1da061f37f444e492f9cd9c7d058e35dcbf4d2c3.

**Comment by kaiidams** [comment]
```diff
diff --git a/examples/translation/prepare-iwslt17-multilingual.sh b/examples/translation/prepare-iwslt17-multilingual.sh
index ce28481..d21e2bb 100644
--- a/examples/translation/prepare-iwslt17-multilingual.sh
+++ b/examples/translation/prepare-iwslt17-multilingual.sh
@@ -86,6 +86,8 @@ echo "pre-processing valid data..."
 for ((i=0;i<${#SRCS[@]};++i)); do
     SRC=${SRCS[i]}
     VALID_SET=(${VALID_SETS[i]})
+    rm -f "$DATA/valid.${SRC}-${TGT}.${SRC}"
+    rm -f "$DATA/valid.${SRC}-${TGT}.${TGT}"
     for ((j=0;j<${#VALID_SET[@]};++j)); do
         FILE=${VALID_SET[j]}
         for LANG in "$SRC" "$TGT"; do
@@ -93,7 +95,7 @@ for ((i=0;i<${#SRCS[@]};++i)); do
                 | sed -e 's/<seg id="[0-9]*">\s*//g' \
                 | sed -e 's/\s*<\/seg>\s*//g' \
                 | sed -e "s/\’/\'/g" \
-                > "$DATA/valid${j}.${SRC}-${TGT}.${LANG}"
+                >> "$DATA/valid.${SRC}-${TGT}.${LANG}"
         done
     done
```

**Comment by myleott** [comment]
Do you mind submitting a PR with a fix?

I think the idea is to produce separate validation sets rather than combining them all into one. So probably these lines need to change to loop over each validation set: https://github.com/pytorch/fairseq/blob/adb5b9c71f7ef4fe2f258e0da102d819ab9920ef/examples/translation/prepare-iwslt17-multilingual.sh#L124-L125

**Comment by kaiidams** [comment]
@myleott Thanks. I updated the script to loop over the valid files. As we have multiple valid files, we need to run `fairseq-preprocess` like below. I can also update `README.md`, but I want to make sure this is what you think it should be.

```
fairseq-preprocess --source-lang de --target-lang en \
    --trainpref $TEXT/train.bpe.de-en \
    --validpref $TEXT/valid0.bpe.de-en,$TEXT/valid1.bpe.de-en,$TEXT/valid2.bpe.de-en,$TEXT/valid3.bpe.de-en,$TEXT/valid4.bpe.de-en,$TEXT/valid5.bpe.de-en \
    --joined-dictionary \
    --destdir data-bin/iwslt17.de_fr.en.bpe16k \
    --workers 10
```

**Comment by myleott** [comment]
Yes that looks perfect, please update the README as well.
