### ISSUE TITLE
Do you plan to add Google's T5 model?

### ISSUE THREAD

**Issue by tomekd** [pytorch/fairseq#1778]
## 🚀 Feature Request
[T5](https://arxiv.org/abs/1910.10683) model is one of the most promising s2s pre-trained models now. Do you have any plans to add it to fairseq? 

### Motivation

T5 achieves the best scores on the [SuperGLUE](https://super.gluebenchmark.com/leaderboard) benchmark, so it would be nice to have it.

### Alternatives

I have started implementing this basing on the huggingface implementation. It is  not hard, but I would like to avoid potential duplication of work.

**Comment by myleott** [comment]
I recently added a huggingface/transformers submodule with the hope of adding wrappers around the various models implemented there (XLNet, ALBERT, T5), but only added GPT-2 at first: https://github.com/pytorch/fairseq/blob/master/fairseq/models/huggingface/hf_gpt2.py

We’d love a PR adding T5 :) I guess you would just need to add the model wrapper and modify the existing denoising task.
