### ISSUE TITLE
fairseq-preprocess should provide an option to train BPE and encode data

### ISSUE THREAD

**Issue by erip** [pytorch/fairseq#1779]
## 🚀 Feature Request

Users have had issues in the past with misunderstanding `fairseq-preprocess` to train and apply BPE if a pretrained model isn't provided. 

### Motivation

When training models, having manual steps outside of `fairseq` is cumbersome. It would be desirable to bundle this into preprocessing instead of requiring the user to follow an additional pre-preprocessing step.

### Pitch

BPE encoders in fairseq should provide the option to train BPE if a pretrained model/vocab pair isn't provided at runtime. This training would require BPE library-specific flags to be passed in, but that's a relatively small lift. Once these BPE models are available (through training or being provided directly), they should be applied to the data splits.

### Alternatives

Continue BPE'ing before using fairseq.

### Additional context

#1080

**Comment by stefan-it** [comment]
Are you going to use the Hugging Face [Tokenizers library](https://github.com/huggingface/tokenizers) for that?

It's also possible to traing a GPT-2-compatible vocab with it 🤗

**Comment by erip** [comment]
That's one implementation option if this issue is entertained. It certainly makes sense, but it's probably better to think about the interface first.

**Comment by Miopas** [comment]
> Are you going to use the Hugging Face [Tokenizers library](https://github.com/huggingface/tokenizers) for that?
> 
> It's also possible to traing a GPT-2-compatible vocab with it 🤗

I am also looking for this solution, and I have already tried huggingface. The huggingface tokenizer outputs a json result like:
```
"Ġte":542,"ep":543,"Ġhas":544,"ap":545,"ĠðŁĺ":546
```

but I found in the pre-trained GPT-2 json file, the word pieces are like:
```
"\u0120run": 1057, "\u0120:": 1058, "\u0120ter": 1059
```

Do these two both work for the fairseq code?
