### ISSUE TITLE
Problem importing logging/metrics

### ISSUE THREAD

**Issue by marmg** [pytorch/fairseq#1786]
## 🐛 Bug

I'm trying to run BART Fine Tuning example, but code fails when importing logging module. Changing the line 

```from fairseq.logging import meters, metrics, progress_bar```

to 

```from fairseq import meters, metrics, progress_bar```

Fails while importing metrics, but meters and progress_bar are imported without any problem.

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Execute:
```from fairseq.logging import metrics``` 
Raise:
```ModuleNotFoundError: No module named 'fairseq.logging'```
Or
```from fairseq import metrics``` 
Raise:
```ImportError: cannot import name 'metrics' ```
Or
Execute train.py

### Expected behavior

Module metrics to be imported

### Environment

 - fairseq Version (e.g., 1.0 or master): fairseq==0.9.0 | master
 - PyTorch Version (e.g., 1.0): torch==1.4.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip install from master branch
 - Build command you used (if compiling from source): pip install
 - Python version: 3.6.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Tesla K80
 - Any other relevant information: None

**Comment by myleott** [comment]
Are you on master?

**Comment by marmg** [comment]
I am

**Comment by myleott** [comment]
I'm not able to reproduce this. Can you confirm the output of these commands:

1) `python -c 'from fairseq import logging'`
2) `pip show fairseq | grep Location`

If the first command raises an exception, then you're probably on fairseq 0.9.0 instead of master. Make sure you clone from source and run `pip install --editable .`.
