### ISSUE TITLE
Steps to download and extract a dataset prints an error

### ISSUE THREAD

**Issue by sharpsy** [pytorch/fairseq#179]
In the `fairseq/examples/stories/README.md` there is an example how to download and extract the dataset:
`curl https://s3.amazonaws.com/fairseq-py/data/writingPrompts.tar.gz | tar xvjf -`

This line, when executed in the shell prints an error:
```
bzip2: (stdin) is not a bzip2 file.
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
curl: (23) Failed writing body (2422 != 16360)
```

This should probably be:
`curl https://s3.amazonaws.com/fairseq-py/data/writingPrompts.tar.gz | tar xvzf -`
[note the `z` (gzip) instead of `j` (bzip2)]

**Comment by huihuifan** [comment]
Hm, the command to tar xvjf works for me :-/

**Comment by myleott** [comment]
It doesn't work for me either:
```
$ wget https://s3.amazonaws.com/fairseq-py/data/writingPrompts.tar.gz
$ tar -xjvf writingPrompts.tar.gz
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by huihuifan** [comment]
Ok, I'll add the fix @sharpsy suggested. Thanks!

**Comment by huihuifan** [comment]
Fixed in https://github.com/pytorch/fairseq/commit/a8f0b75259b5720fdd16ebdc4e0117e425cfd833
