### ISSUE TITLE
NameError: name '_tensorboard_writers' is not defined

### ISSUE THREAD

**Issue by Cathy-t** [pytorch/fairseq#1794]
When I try to run the transformer example
#### Code
torch.hub.list('pytorch/fairseq')  
en2de = torch.hub.load('pytorch/fairseq', 'transformer.wmt16.en-de', tokenizer='moses', bpe='subword_nmt')
en2de.eval()  # disable dropout
assert isinstance(en2de.models[0], TransformerModel)

en2de.translate('Hello world!')

en2de.translate(['Hello world!', 'The cat sat on the mat.'])

something wrong occured:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/cat/PycharmProjects/test_pro/text_dispose/fairseq/fairseq/logging/progress_bar.py", line 299, in _close_writers
    for w in _tensorboard_writers.values():
NameError: name '_tensorboard_writers' is not defined

#### My environment
 - fairseq Version (master)
 - PyTorch Version (1.4.0)
 - OS ( Linux)
 - Installed fairseq by source
 - Python version: 3.7

Could someone help me ?

**Comment by katherine-atwell** [comment]
Hello! I'm having the same issue
