### ISSUE TITLE
lprobs and probs same in top-k

### ISSUE THREAD

**Issue by tuhinjubcse** [pytorch/fairseq#1796]
#### What is your question?

I was trying to edit the code in top-k sampling I have a use case where I need to add a scoring function to log probability 

![image](https://user-images.githubusercontent.com/3104771/76150805-346d2200-607c-11ea-9e81-4d0a7d2142d6.png)

Here for top-k 
https://github.com/pytorch/fairseq/blob/master/fairseq/search.py#L228

```
elif self.sampling_topk > 0:
            # only sample from top-k candidates
            lprobs, top_indices = lprobs.topk(self.sampling_topk)
            probs = lprobs.exp_()

```

lprobs and probs are different though after loop becomes same
![image](https://user-images.githubusercontent.com/3104771/76150987-d6413e80-607d-11ea-8388-ce5ec6411a2b.png)

![image](https://user-images.githubusercontent.com/3104771/76150996-ea853b80-607d-11ea-8160-9d0ed247c44e.png)

Maybe you guys can look into this ? We can bypass by putting a hack of again taking log but lprobs and probs should not be same according to my expectations

#### What's your environment?

Environment
- fairseq Version (e.g., 1.0 or master): 0.9.0
- PyTorch Version (e.g., 1.0) 1.3.1
- OS (e.g., Linux): Linux
- How you installed fairseq (pip, source):
- Build command you used (if compiling from source):
- Python version: 3.7.3
- CUDA/cuDNN version: 10.1.243
- GPU models and configuration: RTX 2080 ( 4 gpus)

**Comment by tuhinjubcse** [comment]
@myleott

**Comment by myleott** [comment]
`probs = lprobs.exp_()` is an in-place operation, so it will cause `lprobs` to be identical to `probs`.

It's a minor memory-efficiency thing, so you can just replace it with `probs = lprobs.exp()` and it should work as you expect.
