### ISSUE TITLE
Add BART-XSUM to TorchHub

### ISSUE THREAD

**Issue by aced125** [pytorch/fairseq#1800]
## 🚀 Feature Request
Please could we add BART finetuned on X-SUM (https://dl.fbaipublicfiles.com/fairseq/models/bart.large.xsum.tar.gz) to torch hub?

### Motivation

For extending the model in a more user-friendly way.

### Alternatives

Loading manually, which means processing the dataset as well.

**Comment by ngoyal2707** [comment]
sure, will do soon.

**Comment by ngoyal2707** [comment]
done

**Comment by aced125** [comment]
Thank you.
