### ISSUE TITLE
Sentence prediction with `roberta.large`

### ISSUE THREAD

**Issue by farid-fari** [pytorch/fairseq#1801]
I am trying to get RoBERTa to predict the next sentence from previous text (NSP in GLUE for example).

## Code

    from fairseq.models.roberta import RobertaModel
    roberta = RobertaModel.from_pretrained('roberta.large/', checkpoint_file='model.pt')
    roberta.eval()
    tokens = roberta.predict('sentence_prediction', tokens)
    # KeyError: 'sentence_prediction'

There seems to be no method of the model that is adapted, I therefore tried with the CLI as well:

    fairseq-interactive --task sentence_prediction --path roberta.large/ test
    # AssertionError: Must set --num-classes

I don't understand what `num_classes` refers to in the context of this context, and when I set it to any positive integer it just says that `test/input0/dict.txt` does not exist. When I copy the dictionary from `roberta.large` over there, it complains that `test/label/dict.txt` does not exist.

I therefore understood there needs to be some preprocessing, so I tried:

    fairseq-preprocess --task sentence_prediction --srcdict ./roberta.large/dict.txt
    # TypeError: load_dictionary() missing 1 required positional argument: 'filename'

Which seems like a bug in the CLI code to me.

At the very least, I would say documentation for this `sentence_prediction` task is desperately required.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): `pip`
 - Python version: 3.8.2
 - CUDA/cuDNN version: N/A (cpu)

**Comment by myleott** [comment]
The `roberta.large` checkpoint doesn't have a trained classification head, you have to finetune it first: https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.custom_classification.md

You can try using the `roberta.large.mnli` model which has an `mnli` head: https://github.com/pytorch/fairseq/tree/master/examples/roberta#use-roberta-for-sentence-pair-classification-tasks

**Comment by farid-fari** [comment]
> The `roberta.large` checkpoint doesn't have a trained classification head, you have to finetune it first

I don't want a classification head though, I want sentence prediction. I'd like for it to be able to complete a sentence, for example if the input is "I am feeling hungry so" then it will output " I shall eat a banana."

If I understood correctly the first link will tell me how to train a classification head, but would that mean that it would classify over the whole vocabulary (and the predicted class is the next word)?

The second one seems to be sentence pair classification but for some predefined MNLI classes, which I don't think is related to sentence prediction?

What I'm looking for is more like the `<mask>` replacement, except that instead of replacing a mask with one word, it should replace it with a whole sentence.

**Comment by myleott** [comment]
Unfortunately that's not really supported with masked language models like roberta. You could try something like:
```
I am feeling hungry so <mask> <mask> <mask> <mask>
```

But then you'd need to search over the various combinations of replacements for the `<mask>` tokens.

I think you're looking for a standard (not masked) language model. We have some of those here: https://github.com/pytorch/fairseq/tree/master/examples/language_model#example-usage

**Comment by farid-fari** [comment]
That last link is exactly what I was looking for, thanks! I thought RoBERTa would be capable of this as well.
