### ISSUE TITLE
Why does padding_idx differ from padding_value in LSTMEncoder?

### ISSUE THREAD

**Issue by MichalTurski** [pytorch/fairseq#1807]
Class `LSTMEncoder` has two fields: `padding_idx` and `padding_value`. First one comes from dictionary, which is passed to `__init()__`, second one is explicitly passed to the same function. Isn't it redundance? Shouldn't padding value come come only from dictionary and be consistent with it?

**Comment by myleott** [comment]
Good call, I'll fix this.
