### ISSUE TITLE
Model Defaults are Ignored 

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [pytorch/fairseq#181]
For the fconv_self_att_wp model it has lines like,

args.multihead_self_attention_nheads = getattr(args, 'multihead_self_attention_nheads', 4)

These lines don't currently have an effect as the related parse arguments have a default value so getattr will find those attributes as the default value. Removing the defaults also wouldn't be enough as when parsing occurs for a flag that's missing without a default, a value is still given (None). One way to fix this is remove the defaults for these, and then check if they're None. It'd then require that all of them are always set up in the code related to register_model_architecture (technically the ones that aren't set at the bottom can keep their default value, but that sounds like an easy way of later introducing a bug).

Another issue in the way those hyperparameters are set up if the flag encoder_embed_dim is missing and argparse didn't bother to give it a value, the line for setting encoder_embed_dim would still do nothing because base_architecture is called first and would have already filled it in. This is easier to fix (just move base_architecture to the bottom).

Aside: The paper involving this model mentions the usage of downsampling while currently downsamples default parse value is False and the fconv_self_att_wp doesn't set that args value to True.

I can make a pull request for all of these changes if they sound fine. While I've only focused on fconv_self_att_wp, I think this issue of ignoring defaults used in the function for registering the model also applies to the the other registered models based on their way of dealing with hyper parameters looking the same (I didn't actually test it though).

**Comment by myleott** [comment]
Yep, base_architecture should be called at the bottom of the function; we made a few last-minute changes before the open source release, and I believe this bug was among them.

@huihuifan, what do you think?

**Comment by alexeib** [comment]
re: getattr, another option might be to specify default=argparse.SUPPRESS on each argument. actually we may have this same problem in other models as well

**Comment by myleott** [comment]
We already do argparse.SUPPRESS :)
https://github.com/pytorch/fairseq/blob/388c520be21752cacb9fe3b1712038f32e0e9a5f/fairseq/options.py#L76-L78

**Comment by hmc-cs-mdrissi** [comment]
Suppress takes care of the None issue. It doesn't work for the ones that have defaults though. For example, multihead_self_attention_nheads, has a default so this line,

 args.multihead_self_attention_nheads = getattr(args, 'multihead_self_attention_nheads', 4)

remains not helpful. I guess the easier way then is just not giving those defaults.

**Comment by huihuifan** [comment]
Yeah sure, I like these suggestions. Feel free to make a PR :) thank you!

**Comment by myleott** [comment]
Fixed by #211, thanks!
