### ISSUE TITLE
invalid literal for int() with base 10 error when using GPT-2 translator

### ISSUE THREAD

**Issue by Aydyou** [pytorch/fairseq#1817]
I am running the following code:

torch.hub.list('pytorch/fairseq')

en2de = torch.hub.load('pytorch/fairseq', 'transformer.wmt16.en-de', tokenizer='moses', bpe='gpt2')
en2de.eval()  

assert isinstance(en2de.models[0], fairseq.models.transformer.TransformerModel)

en2de.cpu()

en2de.translate('I am here')

Which is the same translation code on the translation section. I'm getting the following error:

~/.cache\torch\hub\pytorch_fairseq_master\fairseq\hub_utils.py in translate(self, sentences, beam, verbose, **kwargs)
    124 
    125     def translate(self, sentences: List[str], beam: int = 5, verbose: bool = False, **kwargs) -> List[str]:
--> 126         return self.sample(sentences, beam, verbose, **kwargs)
    127 
    128     def sample(self, sentences: List[str], beam: int = 1, verbose: bool = False, **kwargs) -> List[str]:

~/.cache\torch\hub\pytorch_fairseq_master\fairseq\hub_utils.py in sample(self, sentences, beam, verbose, **kwargs)
    128     def sample(self, sentences: List[str], beam: int = 1, verbose: bool = False, **kwargs) -> List[str]:
    129         if isinstance(sentences, str):
--> 130             return self.sample([sentences], beam=beam, verbose=verbose, **kwargs)[0]
    131         tokenized_sentences = [self.encode(sentence) for sentence in sentences]
    132         batched_hypos = self.generate(tokenized_sentences, beam, verbose, **kwargs)

~/.cache\torch\hub\pytorch_fairseq_master\fairseq\hub_utils.py in sample(self, sentences, beam, verbose, **kwargs)
    131         tokenized_sentences = [self.encode(sentence) for sentence in sentences]
    132         batched_hypos = self.generate(tokenized_sentences, beam, verbose, **kwargs)
--> 133         return [self.decode(hypos[0]['tokens']) for hypos in batched_hypos]
    134 
    135     def score(self, sentences: List[str], **kwargs):

~/.cache\torch\hub\pytorch_fairseq_master\fairseq\hub_utils.py in <listcomp>(.0)
    131         tokenized_sentences = [self.encode(sentence) for sentence in sentences]
    132         batched_hypos = self.generate(tokenized_sentences, beam, verbose, **kwargs)
--> 133         return [self.decode(hypos[0]['tokens']) for hypos in batched_hypos]
    134 
    135     def score(self, sentences: List[str], **kwargs):

~/.cache\torch\hub\pytorch_fairseq_master\fairseq\hub_utils.py in decode(self, tokens)
    197     def decode(self, tokens: torch.LongTensor) -> str:
    198         sentence = self.string(tokens)
--> 199         sentence = self.remove_bpe(sentence)
    200         return self.detokenize(sentence)
    201 

~/.cache\torch\hub\pytorch_fairseq_master\fairseq\hub_utils.py in remove_bpe(self, sentence)
    217     def remove_bpe(self, sentence: str) -> str:
    218         if self.bpe is not None:
--> 219             sentence = self.bpe.decode(sentence)
    220         return sentence
    221 

~/.cache\torch\hub\pytorch_fairseq_master\fairseq\data\encoders\gpt2_bpe.py in decode(self, x)
     43         return self.bpe.decode([
     44             int(tok) if tok not in {'<unk>', '<mask>'} else tok
---> 45             for tok in x.split()
     46         ])
     47 

~/.cache\torch\hub\pytorch_fairseq_master\fairseq\data\encoders\gpt2_bpe.py in <listcomp>(.0)
     43         return self.bpe.decode([
     44             int(tok) if tok not in {'<unk>', '<mask>'} else tok
---> 45             for tok in x.split()
     46         ])
     47 

ValueError: invalid literal for int() with base 10: 'Gäste'

**Comment by myleott** [comment]
You need to use `bpe='subword_nmt'` for that model, please see the README: https://github.com/pytorch/fairseq/tree/master/examples/translation#example-usage-torchhub

**Comment by Aydyou** [comment]
With subword_nmt I get exactly the following error mentioned here:
https://github.com/pytorch/fairseq/issues/961

codec can't decode byte 0x93

**Comment by myleott** [comment]
`subword_nmt` is the right one to use.

Is this Windows by any chance? You probably need to adjust your locale to UTF-8. Try this: https://dev.to/methane/python-use-utf-8-mode-on-windows-212i
