### ISSUE TITLE
Scaling the --update-freq param with different number of GPUs (Edunov et al. 2018)

### ISSUE THREAD

**Issue by nicolasspring** [pytorch/fairseq#1818]
Great to see there is now code provided to reproduce the results of Edunov et al. 2018. I was however wondering about this remark in steps 2 and 3:

> Note: the above command assumes 8 GPUs. Adjust `--update-freq` if you have a different number of GPUs.

When using 8 GPUs, is the effective batch size 8 times the 3584 tokens of the `--max-tokens` parameter? And would the correct course of action be increasing `--update-freq` if you use fewer than 8 GPUs?

In [the paper](https://arxiv.org/pdf/1808.09381.pdf) in section 4.2, the training was described as 30k updates on 16 GPUs, but the command in the example is for a training on 8 GPUs with `--update-freq 16`. Do those settings in the repo reflect those in the paper?

Thanks in advance!

**Comment by myleott** [comment]
The large scale results were done on 128 GPUs (Section 5.6). `--update-freq=16` accumulates 16 batches on each GPU, thus simulating training on 16*8=128 GPUs.

> When using 8 GPUs, is the effective batch size 8 times the 3584 tokens of the --max-tokens parameter? And would the correct course of action be increasing --update-freq if you use fewer than 8 GPUs?

Yes, exactly. If you train on 4 GPUs then use `--update-freq=32`.
