### ISSUE TITLE
Is there any option to get translation results into new file on generation?

### ISSUE THREAD

**Issue by SoonmoKwon** [pytorch/fairseq#1820]
### Before asking:   
1. search the issues. 
done  
2. search the docs.    
done

#### What is your question?

I trained a new model from my dataset and conducted generation. It is very useful to calculate bleu score directly.
However, I want to evaluate my model using METEOR and analyze its result qualitatively. For the purpose, i need an output file containing translation results from my test data.
Is there any option to save it on command-line tools?

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0. 9. 0
 - PyTorch Version (e.g., 1.0) 1. 3. 1
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3. 6. 9
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: GTX 1080
 - Any other relevant information:

**Comment by myleott** [comment]
I think `--results-file` should work: https://github.com/pytorch/fairseq/blob/b65a85b692544e36f9e83ada91cf4ef529791c69/fairseq/options.py#L474-L475

**Comment by lorelupo** [comment]
Hi,
Is this the fastest way to evaluate generation with different scores other than BLEU (METEOR, TER, etc.) ?
