### ISSUE TITLE
Reproducing mBART results for Arabic->Engllish

### ISSUE THREAD

**Issue by aagohary** [pytorch/fairseq#1841]
## ❓ Questions and Help

I am trying to fine-tune the mBART model to reproduce the arabic -> english results reported in table 2 in the paper.  So far I am only getting a BLEU score of 28.8 while the paper reports 37.6.

In terms of the fine-tuning dataset, I used the TED parallel data that were available for training in IWSLT'17 combined with the available dev and test splits in IWSLT 2011-2015. The total number of training examples was 230k. I am not sure what data I am missing to get to the 250k used in the paper.

It would be really helpful if you could share the preprocessing and fine-tuning scripts you used for all language pairs or at least those used for arabic -> english.

I used the same hyper-parameter values as in the provided en->ro tutorial.
```  
    SRC=ar
    TGT=en
    MODEL=${cc25_pretrain}/sentence.bpe.model
    ${SPM} --model=${MODEL} < ${DATA}/${TRAIN}.${SRC} > ${DATA}/${TRAIN}.spm.${SRC} &
    ${SPM} --model=${MODEL} < ${DATA}/${TRAIN}.${TGT} > ${DATA}/${TRAIN}.spm.${TGT} &
    ${SPM} --model=${MODEL} < ${DATA}/${VALID}.${SRC} > ${DATA}/${VALID}.spm.${SRC} &
    ${SPM} --model=${MODEL} < ${DATA}/${VALID}.${TGT} > ${DATA}/${VALID}.spm.${TGT} &
    ${SPM} --model=${MODEL} < ${DATA}/${TEST}.${SRC} > ${DATA}/${TEST}.spm.${SRC} &
    ${SPM} --model=${MODEL} < ${DATA}/${TEST}.${TGT} > ${DATA}/${TEST}.spm.${TGT} &
```

```
    DICT=${cc25_pretrain}/dict.txt
     python preprocess.py \
            --source-lang ${SRC} \
            --target-lang ${TGT} \
            --trainpref ${DATA}/${TRAIN}.spm \
            --validpref ${DATA}/${VALID}.spm \
            --testpref ${DATA}/${TEST}.spm  \
            --destdir ${DEST} \
            --thresholdtgt 0 \
            --thresholdsrc 0 \
            --srcdict ${DICT} \
            --tgtdict ${DICT} \
            --workers 70
```

```
PRETRAIN=${cc25_pretrain}/model.pt
langs=ar_AR,cs_CZ,de_DE,en_XX,es_XX,et_EE,fi_FI,fr_XX,gu_IN,hi_IN,it_IT,ja_XX,kk_KZ,ko_KR,lt_LT,lv_LV,my_MM,ne_NP,nl_XX,ro_RO,ru_RU,si_LK,tr_TR,vi_VN,zh_CN
python train.py $DEST  --encoder-normalize-before --decoder-normalize-before  --arch
 mbart_large --task translation_from_pretrained_bart  --source-lang ar --target-lang en --criterion 
label_smoothed_cross_entropy --label-smoothing 0.2  --dataset-impl mmap --optimizer adam --
adam-eps 1e-06 --adam-betas '(0.9, 0.98)' --lr-scheduler polynomial_decay --lr 3e-05 --min-lr -1 
--warmup-updates 2500 --total-num-update 200000 --dropout 0.3 --attention-dropout 0.1  --
weight-decay 0.0 --max-tokens 128 --update-freq 2 --save-interval 1 --save-interval-updates 
5000 --keep-interval-updates 10 --no-epoch-checkpoints --seed 222 --log-format simple --log-
interval 2 --reset-optimizer --reset-meters --reset-dataloader --reset-lr-scheduler --restore-file 
$PRETRAIN --langs $langs --layernorm-embedding  --ddp-backend no_c10d --save-dir 
$MODEL_SAVE_DIR --memory-efficient-fp16 --distributed-world-size 1
```

The only changes I made are setting --max-tokens to 128 instead of 1024 and using --memory-efficient-fp16 to fit things in my GPU memory.

And here is my evaluation script

```
python generate.py $DEST  --path ${MODEL_SAVE_DIR}/${model}  --task 
translation_from_pretrained_bart --gen-subset ${subset} -t en -s ar --bpe 'sentencepiece' --
sentencepiece-vocab ${cc25_pretrain}/sentence.bpe.model --sacrebleu  --remove-bpe 
'sentencepiece' --max-sentences 32 --langs $langs --beam 5 > $PREDICTIONS_DIR/ar_en

grep ^H $PREDICTIONS_DIR/ar_en | cut -f3- > $PREDICTIONS_DIR/${subset}.hyp
grep ^T $PREDICTIONS_DIR/ar_en | cut -f2- > $PREDICTIONS_DIR/${subset}.ref

sacrebleu -tok 'none' -s 'none' $PREDICTIONS_DIR/${subset}.ref < $PREDICTIONS_DIR/${subset}.hyp

```

Thanks.

**Comment by ngoyal2707** [comment]
cc: @MultiPath

**Comment by gvskalyan** [comment]
Hi @aagohary ,

I am trying to to fine-tune mBART on a language of dataset size 0.7 Million, I use the same command as you i.e., modified the existing to ` --memory-efficient-fp16 --max-tokens 128`, but still I am unable to train due to CUDA out of memory error.

Trained even on a single GPU.
Using 8 Geforce RTX 2080ti (11 GB RAM).

Can you please confirm the above RAM would be sufficient to fine-tune it, other than the training data size I do not see any diff across the two.
Even if your GPU has above 11 GB can you inform the max memory it occupies while training.

Thanks.

**Comment by aagohary** [comment]
I am using a single GeForce GTX 1080 Ti GPU which also has 11GB of memory.

**Comment by gvskalyan** [comment]
Hi, Does your GPU support fp16 training, can you provide the output of this 
`torch.cuda.get_device_capability(0)[0]`

Also in the train command does target-lang need to be `en` or `en_XX` as in the langs variable, in order to properly finetune since it is pretrained using particular lang-id?

**Comment by hischen** [comment]
> Hi, Does your GPU support fp16 training, can you provide the output of this
> `torch.cuda.get_device_capability(0)[0]`
> 
> Also in the train command does target-lang need to be `en` or `en_XX` as in the langs variable, in order to properly finetune since it is pretrained using particular lang-id?



> Hi @aagohary ,
> 
> I am trying to to fine-tune mBART on a language of dataset size 0.7 Million, I use the same command as you i.e., modified the existing to ` --memory-efficient-fp16 --max-tokens 128`, but still I am unable to train due to CUDA out of memory error.
> 
> Trained even on a single GPU.
> Using 8 Geforce RTX 2080ti (11 GB RAM).
> 
> Can you please confirm the above RAM would be sufficient to fine-tune it, other than the training data size I do not see any diff across the two.
> Even if your GPU has above 11 GB can you inform the max memory it occupies while training.
> 
> Thanks.

Hey,gvskalyan. Sorry to be a  bother. I met the same error that  CUDA out of memory when I  fine-tune mBART on wmt16 en-ro dataset. I fune-tune  on a single GPU RTX2080TI (11 GB RAM).
Have you solved the error so far? Thanks.

**Comment by gvskalyan** [comment]
Hi @hischen , I have not solved this .
But there are few things left to try,

1) As per [this](https://twitter.com/sam_shleifer/status/1244655378303983616) maybe even mBART memory would have been reduced which makes it easier to load and fine-tune. Transformers library [has](https://github.com/huggingface/transformers/blob/master/docs/source/pretrained_models.rst) mBART en-ro pre-trained from fairseq.

2) try gradient checkpointing as mentioned in issue no 1936

**Comment by bkj** [comment]
Does anyone know whether anything in particular needs to be done to account for Arabic being written right-to-left, while most of the other languages in the mBART corpus are written left-to-right?  Does the sentencepiece tokenization need to be flipped?  Do the self-attention masks need to be flipped?

Thanks!
