### ISSUE TITLE
Fairseq requires PyTorch >= 1.4

### ISSUE THREAD

**Issue by villmow** [pytorch/fairseq#1843]
## 🐛 Bug

Fairseq needs pytorch >= 1.4 at least since this commit https://github.com/pytorch/fairseq/commit/3335de5f441ee1b3824e16dcd98db620e40beaba . The following line requires this, as `nn.GELU` was added in 1.4 to Pytorch (I think the functional GELU was released a little earlier):
https://github.com/pytorch/fairseq/blob/476606fc1631b7c87873d3e314e61dae8f25a751/fairseq/modules/gumbel_vector_quantizer.py#L21

[Link PyTorch 1.4.0 Release Notes](https://github.com/pytorch/pytorch/releases/tag/v1.4.0)

### To Reproduce

1. Clone fairseq with pytorch 1.2.1 installed (the README says at least 1.2.)
2. Run translation example

### Expected behavior

Either update the docs that fairseq requires PyTorch 1.4.0 or use functional API in `gumbel_vector_quantizer` to keep backwards compatibility.
 
### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.2.1
 - OS (e.g., Linux): linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): pip install -e .
 - Python version: 3.7
 - CUDA/cuDNN version: 10.0 (thats why PyTorch 1.2.1)

**Comment by myleott** [comment]
Thanks, we will update the docs.
