### ISSUE TITLE
How to run multi node distribution training using srun

### ISSUE THREAD

**Issue by gaopengcuhk** [pytorch/fairseq#1855]
## 📚 Documentation

srun --gres=gpu:8 --ntasks=16 --ntasks-per-node=8 fairseq-train

Can you share the command to run multi-node training with srun. The code above want to run 16 GPU on 2 node with each node 8 GPU.

Thanks!

**Comment by myleott** [comment]
Generally you just need to set `--distributed-port` and `--ntasks-per-node 1`. Something like this should work:
```
srun --nodes 2 --gres=gpu:8 --ntasks-per-node 1 fairseq-train --distributed-port 12345 --no-save --disable-validation --task dummy_masked_lm --arch dummy_model --optimizer sgd --lr 1e-4 --max-sentences 8 --tokens-per-sample 512 --dataset-size 10000 --max-epoch 1 --dict-size 49995 --log-interval 10
```
