### ISSUE TITLE
mBART with CCMatrix

### ISSUE THREAD

**Issue by JohannesTK** [pytorch/fairseq#1856]
Hi,

Thank you for open-sourcing mBART! 🤗

I couldn't help but wonder if you are planning to train mBART with [CCMatrix](https://github.com/facebookresearch/LASER/tree/master/tasks/CCMatrix) as well?

Thanks & stay healthy.

**Comment by ngoyal2707** [comment]
That's a good question, this is currently under exploration. Training with noisy mined data is somewhat complex specially for low resource languages but we are exploring this direction. 

Unfortunately I can't give any timelines here as there are many unknowns but if find this direction to be fruitful, we will definitely open-source the code and model like other projects.
