### ISSUE TITLE
Special tokens to pre-trained BART model

### ISSUE THREAD

**Issue by loretoparisi** [pytorch/fairseq#1867]
#### What is your question?
Is it possibile to add special tokens to the pre-trained BART model? My text has `<s>` as sequence separator for sentences. I would like that the encoder will handle it as a whole token, otherwise the model will break it in codes and learn like `<s` or `s>` etc.

**Comment by tuhinjubcse** [comment]
What I did was take their dict.txt and see entries from encoder.json which has count 0 ,take any such entry and replace it with the special token <s>

Also add a line that if token in <s> it should not do bpe split
https://github.com/pytorch/fairseq/blob/master/fairseq/data/encoders/gpt2_bpe_utils.py#L66


```
class Encoder:

    def __init__(self, encoder, bpe_merges, errors='replace'):
        self.encoder = encoder
        self.decoder = {v:k for k,v in self.encoder.items()}
        self.errors = errors # how to handle errors in decoding
        self.byte_encoder = bytes_to_unicode()
        self.byte_decoder = {v:k for k, v in self.byte_encoder.items()}
        self.bpe_ranks = dict(zip(bpe_merges, range(len(bpe_merges))))
        self.cache = {}

        try:
            import regex as re
            self.re = re
        except ImportError:
            raise ImportError('Please install regex with: pip install regex')

        # Should haved added re.IGNORECASE so BPE merges can happen for capitalized versions of contractions
        self.pat = self.re.compile(r"""'s|'t|'re|'ve|'m|<A0>|<EOT>| <EOT>|<V>|<A1>|<A2>| <A0>|<P>| <P>|<A1>| <A1>| <A2>| <V>| </s>|</s>|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+""")

    def bpe(self, token):
        if token in ['<A0>','<A1>','<A2>','<V>','</s>','<P>','<EOT>','\u0120<A0>','\u0120<A1>','\u0120<A2>','\u0120<V>','\u0120</s>','\u0120<P>','\u0120<EOT>']:
            #print("inside bpe",token)
            return token

```

**Comment by Asaw2019** [comment]
> What I did was take their dict.txt and see entries from encoder.json which has count 0 ,take any such entry and replace it with the special token . Also, add a line that if token in it should not do bpe split
> ![image](https://user-images.githubusercontent.com/3104771/77219248-247c2600-6af1-11ea-9847-7f502853e931.png)

Please, guide me to build encoder.json for other language.
