### ISSUE TITLE
How do I keep pre-training mBART?

### ISSUE THREAD

**Issue by moyid** [pytorch/fairseq#1870]
Can you provide the script I can use to keep pretraining mBART? For example if I want to do more pretraining on one language, or to add a new language?

Thank you!

**Comment by SunbowLiu** [comment]
> Can you provide the script I can use to keep pretraining mBART? For example if I want to do more pretraining on one language, or to add a new language?
> 
> Thank you!

Hello,

Have you got some updates?

**Comment by firdota** [comment]
> > Can you provide the script I can use to keep pretraining mBART? For example if I want to do more pretraining on one language, or to add a new language?
> > Thank you!
> 
> Hello,
> 
> Have you got some updates?

hello, have you got any progress?
