### ISSUE TITLE
prepare-iwslt14.sh: chars are replaced with @. Why?

### ISSUE THREAD

**Issue by leocaprio** [pytorch/fairseq#1872]
## ❓ Questions and Help

After running the script [prepare-iwslt14.sh](https://github.com/pytorch/fairseq/blob/master/examples/translation/prepare-iwslt14.sh) the resulting files contain many `@` symbols. The file _valid.en_ begins like this:

``` 
it had two@@ -@@ to-@@ three-@@ to-@@ 400 times the toxic lo@@ ads ever allowed by the ep@@ a .
often what j@@ ams us up is se@@ wa@@ ge .
what do you do when you have this sort of disrup@@ ted flow ?
stephen pal@@ um@@ b@@ i : following the mer@@ cur@@ y tra@@ il
```

Is this really the correct behavior?

#### What's your environment?

 - fairseq: 0.9.0
 - PyTorch: 1.4.0
 - OS: Ubuntu 18.04
 - How you installed fairseq: pip

**Comment by Guitaricet** [comment]
This is called BPE-tokenization. It splits infrequent words into more frequent tokens. @@ is used to show when multiple tokens are a part of the same word.

For example:
antidisestablishmentarianism -> anti@@ dis@@ est@@ ablishment@@ arism
