### ISSUE TITLE
how to do document-level translation with mbart

### ISSUE THREAD

**Issue by moyid** [pytorch/fairseq#1876]
how do I do document level translation with fairseq? For example, in the paper for mBART, document level translation is mentioned. Is there a document level task in Fairseq? Is there specific input format, for example to denote document boundary?

Thank you!

**Comment by clang88** [comment]
I am wondering the same thing. Is there any specific input format for fine-tuning mBART on document-level with Fairseq? Or should the whole document essentially be put into a single line?

**Comment by lorelupo** [comment]
bump

**Comment by lorelupo** [comment]
Authors provide a partial answer in https://github.com/pytorch/fairseq/issues/1884#issuecomment-615950668, although the full procedure remains undocumented.
