### ISSUE TITLE
Improve  the translate api for TransformerModel

### ISSUE THREAD

**Issue by tonylekhtman** [pytorch/fairseq#1877]
## 🚀 Feature Request
When using verbose mode on the TransformerModel translate method I'd like to get the full response to the api call and not just printed to console.

### Motivation
I want to present my users with all the translation options and alignment of the sentence to the source sentence so they would be able to choose the best translation and return to the source translation words if something is not clear.

### Pitch

`from fairseq.models.transformer import TransformerModel
zh2en = TransformerModel.from_pretrained(
  '/path/to/checkpoints',
  checkpoint_file='checkpoint_best.pt',
  data_name_or_path='data-bin/wmt17_zh_en_full',
  bpe='subword_nmt',
  bpe_codes='data-bin/wmt17_zh_en_full/zh.code'
)
zh2en.translate('你好 世界')

{'translation': ''Hello World' , 'more options': ['Helo world', 'Helllo werld'] 'alignment': '0-0 1-1'}`

### Alternatives

return the raw text that is printed to console and let the client parse it.

### Additional context
I took the usage example from here:
https://github.com/pytorch/fairseq/tree/master/examples/translation#example-usage-torchhub

**Comment by villmow** [comment]
You could use the output of `generate` (which contains all the hypos and alignments). See  `sample` - which is called by `translate` - for how to preprocess your input:

https://github.com/pytorch/fairseq/blob/4d2efae84dc4eaf8c66625ab6af0fdc4aa794da0/fairseq/hub_utils.py#L128-L133

**Comment by mohammedayub44** [comment]
Additionally, how to get `nbest` translations using this python API ? 
I tried passing parameter `nbest` it did not help. CLI version works fine.

![image](https://user-images.githubusercontent.com/7122670/89952207-d3351600-dbfa-11ea-8e6d-bb0f1665aa9f.png)

Thanks!
