### ISSUE TITLE
Production with fairseq, translation

### ISSUE THREAD

**Issue by alrojo** [pytorch/fairseq#1879]
#### What is your question?
I want to port my trained model to production. It seems the CLI is not a good option as I want to avoid having to reload my model. So I am testing the `from_pretrained` python functions provided in hub_utils, but I cannot seem to make it work.

#### Code
Given a model trained with sentencepiece, I execute the following file `run.py` inside the fairseq root

```
from fairseq.models.transformer import TransformerModel
de2en = TransformerModel.from_pretrained(
  'checkpoints/transformer/',
  checkpoint_file='checkpoint_best.pt',
  data_name_or_path='data-bin/de-en/',
  bpe='sentencepiece',
  bpe_codes='examples/translation/de-en/sentencepiece.bpe.model'
)
print(de2en.translate('du bist ein ferd'))
```

this results in the following error
```
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    bpe_codes='examples/translation/de-en/sentencepiece.bpe.model'
  File "/home/ubuntu/fairseq/fairseq/models/fairseq_model.py", line 221, in from_pretrained
    return hub_utils.GeneratorHubInterface(x["args"], x["task"], x["models"])
  File "/home/ubuntu/fairseq/fairseq/hub_utils.py", line 112, in __init__
    self.bpe = encoders.build_bpe(args)
  File "/home/ubuntu/fairseq/fairseq/registry.py", line 41, in build_x
    return builder(args, *extra_args, **extra_kwargs)
  File "/home/ubuntu/fairseq/fairseq/data/encoders/sentencepiece_bpe.py", line 21, in __init__
    vocab = file_utils.cached_path(args.sentencepiece_vocab)
AttributeError: 'Namespace' object has no attribute 'sentencepiece_vocab'
```

#### What have you tried?
I have tried giving it various paths for the sentencepiece, but nothing works. I can't seem to figure exactly how `hub_utils` functions.

#### What's your environment?

 - fairseq 0.9
 - PyTorch 1.5
 - OS ubuntu 18.04
 - How you installed fairseq (`pip`, source): source, about a week ago
 - Build command you used (if compiling from source): same as official readme
 - Python version: 3.7.4
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: p3.2 instance on amazon
 - Any other relevant information:

**Comment by kkaiser** [comment]
`bpe_codes` takes a file that must be in the same directory as specified in the first argument
```
from fairseq.models.transformer import TransformerModel
de2en = TransformerModel.from_pretrained(
  'checkpoints/transformer/',
  checkpoint_file='checkpoint_best.pt',
  data_name_or_path='data-bin/de-en/',
  bpe='sentencepiece',
  bpe_codes='sentencepiece.bpe.model'
)
print(de2en.translate('du bist ein ferd'))
```

path to file: `checkpoints/transformer/sentencepiece.bpe.model`

**Comment by alrojo** [comment]
Thank you, this solved the issue.
