### ISSUE TITLE
Print Alignment in hub_utils not working

### ISSUE THREAD

**Issue by tonylekhtman** [pytorch/fairseq#1880]
## 🐛 Bug

I can't use the print_alignment option when using the TransformerModel translate option.
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

```
from fairseq.models.transformer import TransformerModel
zh2en = TransformerModel.from_pretrained(
  '/path/to/checkpoints',
  checkpoint_file='checkpoint_best.pt',
  data_name_or_path='data-bin/wmt17_zh_en_full',
  bpe='subword_nmt',
  bpe_codes='data-bin/wmt17_zh_en_full/zh.code'
)
zh2en.translate('你好 世界', verbose=True,print_alignment=True)
```

#### Code sample
```
from fairseq.models.transformer import TransformerModel
zh2en = TransformerModel.from_pretrained(
  '/path/to/checkpoints',
  checkpoint_file='checkpoint_best.pt',
  data_name_or_path='data-bin/wmt17_zh_en_full',
  bpe='subword_nmt',
  bpe_codes='data-bin/wmt17_zh_en_full/zh.code'
)
zh2en.translate('你好 世界', verbose=True,print_alignment=True)
```

### Expected behavior

I want it to print the alignment row to console just as the fairseq-generate script does.

### Environment

 - fairseq 0.9
 - PyTorch 1.4
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip
 - Python version: 3.6.8
 - CUDA/cuDNN version: cuda 10.1

**Comment by lhk** [comment]
huh, I've just stumbled upon the exact same problem.
I would like to use alignments and searched in the codebase on how to get them.

I found this:
https://github.com/pytorch/fairseq/blob/42f65d65776327598a2d3ded2e92e5818c70a125/fairseq/hub_utils.py#L186

It looks like alignments should be printed if both `verbose` and `print_alignment` are set to `True`.

So I tried the following sample code:
```
import torch

en2fr = torch.hub.load('pytorch/fairseq', 'transformer.wmt14.en-fr', tokenizer='moses', bpe='subword_nmt')
fr = en2fr.translate('Hello world!', beam=5, verbose=True, print_alignment=True)
```

and it produces the error message:
`AttributeError: 'list' object has no attribute 'int'`

**Comment by lhk** [comment]
After some more browsing of the codebase, I made a workaround. Rewrite the last line of the sample method like this:

```
    def sample(self, sentences: List[str], beam: int = 1, verbose: bool = False, **kwargs) -> List[str]:
        if isinstance(sentences, str):
            return self.sample([sentences], beam=beam, verbose=verbose, **kwargs)[0]
        tokenized_sentences = [self.encode(sentence) for sentence in sentences]
        batched_hypos = self.generate(tokenized_sentences, beam, verbose, **kwargs)
        return list(zip([self.decode(hypos[0]['tokens']) for hypos in batched_hypos], [hypos[0]['alignment'] for hypos in batched_hypos]))
```

and it will return both the translation and the alignment.

Here is the line of code to be edited as a permalink:
https://github.com/pytorch/fairseq/blob/42f65d65776327598a2d3ded2e92e5818c70a125/fairseq/hub_utils.py#L133

Please note though that this will still only work if you pass in `print_alignment=True` as one of the `kwargs`.

**Comment by tonylekhtman** [comment]
From what i see the problematic line is:
https://github.com/pytorch/fairseq/blob/42f65d65776327598a2d3ded2e92e5818c70a125/fairseq/hub_utils.py#L188

it should instead be:
 ' '.join(['{}-{}'.format(src_idx, tgt_idx) for src_idx, tgt_idx in hypo['alignment'])

**Comment by tonylekhtman** [comment]
Any updates? Can I help?
