### ISSUE TITLE
Has the released pretrained mBART model been pretrained on document level texts?

### ISSUE THREAD

**Issue by moyid** [pytorch/fairseq#1884]
The paper for mbart: https://arxiv.org/pdf/2001.08210.pdf describes document level translation, does the released pretrained model include document level pretraining?

**Comment by ngoyal2707** [comment]
@moyid yes the pretraining included document-level input. In our pretrained data, we know the document boundaries and while pretraining `mBART`, we used `complete-doc` mode [here](https://github.com/pytorch/fairseq/blob/master/fairseq/data/token_block_dataset.py#L25) where instances won't cross document boundary.
