### ISSUE TITLE
VQ-wav2vec : Should we fine tune the BERT model in down-streaming tasks  ?

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#1898]
In the VQ-wav2vec paper, authors have performed several tasks on embeddings generated from BERT architectures by inputting the discretized audio.  It is not clear that whether they finetuned the BERT base models or just kept is frozen and only used it to extract embeddings.

**Comment by huihuifan** [comment]
@alexeib

**Comment by alexeib** [comment]
in vq-wav2vec paper we keep the model frozen - we actually extract features and dump them to disk because the model is pytorch in python and wav2letter is in c++

but see one of our follow up papers where we fine-tune bert directly and obtain better results: https://arxiv.org/abs/1911.03912

**Comment by karthik19967829** [comment]
Hey @shamanez @alexeib it will be great if you can point me to the VQ-wav2vec BERT model

**Comment by alexeib** [comment]
have you checked here: https://github.com/pytorch/fairseq/tree/master/examples/wav2vec#pre-trained-models-2
