### ISSUE TITLE
vq-wav2vec RoBERTa extract all features or just final layer?

### ISSUE THREAD

**Issue by david-macleod** [pytorch/fairseq#1900]
#### What is your question?

To get the results achieved in the vq-wav2vec paper were the features extracted from all layers of the RoBERTa model or just the final layer i.e. was return_all_hidden set to True or False? `roberta.extract_features(tokens, return_all_hiddens=True)`

Many thanks

**Comment by huihuifan** [comment]
@alexeib

**Comment by alexeib** [comment]
we only use features from the final layer
