### ISSUE TITLE
Using RoBERTa to fill sub-word masks

### ISSUE THREAD

**Issue by chrisjbryant** [pytorch/fairseq#1906]
Quick question: How does RoBERTa as a masked language model handle rare word mask filling?

Context: In original BERT, if you want to predict a token that consists of multiple word pieces, you need multiple masks; e.g. 
```
He works diligently .
He works [MASK] [MASK] [MASK] .
He works di ##ligent ##ly .
```
Is the same true for RoBERTa? I know RoBERTa uses BPE instead of word pieces, but do we still need to know how many sub-words constitute a complete word?

**Comment by huihuifan** [comment]
Yes, it should be the same as original BERT, though RoBERTa and BERT use different subwords schemes.
