### ISSUE TITLE
MBART evaluation: can't find WMT paths

### ISSUE THREAD

**Issue by sshleifer** [pytorch/fairseq#1907]
Hey,
I was trying to get started playing with mbart, and don't understand two things: 
- what is `path_2_data` should be in this command?
https://github.com/pytorch/fairseq/blob/5e79322b3a4a9e9a11525377d3dda7ac520b921c/examples/mbart/README.md#L80
- what the "Set tokenizer here" refers to in the wmt-16 scripts.

Would be happy to write detailed steps if you guys could point me in the right direction.

Thanks in Advance!

**Comment by sshleifer** [comment]
Another clue:

```
from fairseq import tasks
args = torch.load(mbart_en_ro/model.pt', map_location='cpu')['args']
task = tasks.setup_task(args)
```
gives
```python
FileNotFoundError: [Errno 2] No such file or directory: '/private/home/jgu/data-bin/cc25_finetune//en_XX-ro_RO-wmt_raw/dict.en_XX.txt'
```

suggesting that path2dat is something like `'en_XX-ro_RO-wmt_raw/dict.en_XX.txt'` and all I need is to figure out where to get/make that data. Help much appreciated!

**Comment by Bachstelze** [comment]
Yes, you need the preprocessed data which you want to translate.
Have a look here: https://github.com/pytorch/fairseq/issues/1758

**Comment by huihuifan** [comment]
@ngoyal2707 @yinhanliu

**Comment by yinhanliu** [comment]
I think this is solved.

**Comment by sshleifer** [comment]
I solved through the huggingface nlp package and posted the result to S3:

You can get the data with:
```bash
wget https://s3.amazonaws.com/datasets.huggingface.co/translation/wmt_en_ro.tar.gz
tar -xzvf wmt_en_ro.tar.gz
export ENRO_DIR=${PWD}/wmt_en_ro
```
