### ISSUE TITLE
Bilingual Translation in Fairseq

### ISSUE THREAD

**Issue by ajesujoba** [pytorch/fairseq#1921]
I am trying to train a Multilingual MT between two languages, English(En) and German(De). It is expected to be a Bilingual (Bidrectional) training. 

Can I do it without using the following command: `task multilingual_translation --lang-pairs de-en,en-de`? This requires that I have two copies of the training data? Or can I achieve the training without the multiple copies ?

**Comment by Alex-Fabbri** [comment]
I think you can just preprocess the data for one direction and then follow the naming conventions and use symbolic links for the other direction, to avoid two copies of the data.

**Comment by Alex-Fabbri** [comment]
I think you can just preprocess the data in one direction and follow the naming conventions and create symbolic links for the other direction, to avoid duplicating the data.
