### ISSUE TITLE
wav2vec : can we use pretrained wav2vec model to extract features from audio sampled with less sampling rates (12K)?

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#1931]
I have set of audios that are sampled at 12K **not 16K**. Since wa2vec has retained on 16K audio, is that ok if I use wav2vec to extract features from 12K audios?

**Comment by sgxthsat2019** [comment]
Hi，
can you share me how you deal with this problem? I just have 8k audios and the wav2vec model doesn't work well.
Thanks a lot!

**Comment by sgxthsat2019** [comment]
@alexeib

**Comment by alexeib** [comment]
you will need to resample your 12k/8k audio to 16k before you can use the wav2vec model. this is not something we've tested so its not clear how well it will work, though. let us know!

**Comment by sgxthsat2019** [comment]
> you will need to resample your 12k/8k audio to 16k before you can use the wav2vec model. this is not something we've tested so its not clear how well it will work, though. let us know!

I use Pushto, not English data, to train an ASR model. The 8k audio with wav2vec feature doesn't work well. I'm checking the reason for the bad performance. 
Can you give me some advisement on finetuning the wav2vec model using NOT-English data and/or NOT-16k audio data? In my case, I use 8k Pushto data.
By the way, wav2vec model work very well on English data! I'm so appreciate your work!
Thanks a lot~ @alexeib

**Comment by alexeib** [comment]
the feature encoder is designed for 16k sample rate. if you pre-train your model on 8k data you may want to change the feature encoder architecture such that strides and receptive field remains the same as it would be for 16k

**Comment by sgxthsat2019** [comment]
> the feature encoder is designed for 16k sample rate. if you pre-train your model on 8k data you may want to change the feature encoder architecture such that strides and receptive field remains the same as it would be for 16k

OK, I will have a try. Thank you so much~

**Comment by m-wiesner** [comment]
As far as I can tell, the resampling is done with 

F.interpolate(x.view(1, 1, -1), scale_factor=factor).squeeze()

with the default interpolation mode ('nearest'). Maybe this doesn't ultimately matter, but it seems less than ideal. Switching it to one of the other interpolation options would probably be better. The best would be to use torchaudio which does sincinterpolation or librosa maybe?

**Comment by dcshapiro** [comment]
Tried on 8k audio upsampled to 16k... It did not work well at all. The model hears the sounds and guesses words with those sounds, but it is almost 100% wrong on which words it selects. Oh well. I guess retraining from scratch is the way to go if you want to inference on 8k audio....
