### ISSUE TITLE
How to generate translation using multiple GPUs?

### ISSUE THREAD

**Issue by SunbowLiu** [pytorch/fairseq#1937]
Hi, 
Right now I use --num-shards and --shard-id to generate multiple files by multiple gpus, and then concat the results to model multiple gpu decoding.
Is there any more convenient way?
Thank you very much!

**Comment by huihuifan** [comment]
Unfortunately, this is the current solution. If you have an improvement, please make a pull request!

**Comment by narfanar** [comment]
It would be great something like a world size parameter could be set that automatically set the num-shards and such flags appropriately then concat the results automatically on output (and remove the shards). I'll look into but am not that versed in the codebase so could take a while.

**Comment by mahdiabavisani** [comment]
how do you concat the results from the multiple generated predictions to keep the order similar to the original file?
