### ISSUE TITLE
Question on Scaling Machine Translation Evaluation remove-bpe command

### ISSUE THREAD

**Issue by gaopengcuhk** [pytorch/fairseq#1939]
fairseq-generate \
    data-bin/wmt16_en_de_bpe32k \
    --path checkpoint.avg5.pt \
    --beam 4 --lenpen 0.6 --remove-bpe

When I drop the --remove-bpe, the BLEU score will increase a lot. Can you give any explanation?

**Comment by LividWo** [comment]
same here. But I think this is expected? Since the model is trained to generate subwords instead of words.

**Comment by myleott** [comment]
Yes, it will generate subwords, for example: `He@@ llo Worl@@ d`. If you don’t remove the BPE continuation markers, this would give you an incorrect (larger) BLEU score.
