### ISSUE TITLE
AssertionError: assert high > 1

### ISSUE THREAD

**Issue by luweishuang** [pytorch/fairseq#1945]
i use aishell_v2 dataset to training wav2vec model,  commamnd line: python train.py examples/wav2vec --save-dir examples/wav2vec/aishell2_models --num-workers 6 --fp16 --max-update 400000 --save-interval 1 --arch wav2vec --task audio_pretraining --lr 1e-06 --min-lr 1e-09 --optimizer adam --max-lr 0.005 --lr-scheduler cosine --conv-feature-layers "[(512, 10, 5), (512, 8, 4), (512, 4, 2), (512, 4, 2), (512, 4, 2), (512, 1, 1), (512, 1, 1)]" --conv-aggregator-layers "[(512, 2, 1), (512, 3, 1), (512, 4, 1), (512, 5, 1), (512, 6, 1), (512, 7, 1), (512, 8, 1), (512, 9, 1), (512, 10, 1), (512, 11, 1), (512, 12, 1), (512, 13, 1)]" --skip-connections-agg --residual-scale 0.5 --log-compression --warmup-updates 500 --warmup-init-lr 1e-07 --criterion binary_cross_entropy --num-negatives 10 --max-sample-size 150000 --max-tokens 1500000 --skip-invalid-size-inputs-valid-test

and it always report assertionError when running to "epoch 001:   3%| | 1291/47874 [20:33<12:10:38,  1.06it/s, loss=0.724954, wps=8.37628e+18, ups=1.07, wTraceback (most recent call last):"

**Comment by caesar-one** [comment]
@luweishuang with `python train.py...` which file are you executing with command line? Where is the file located in the repo?

**Comment by huihuifan** [comment]
Hello, can you provide additional detail here? What assertion error is being hit?
