### ISSUE TITLE
Difference in dimensions of attention in test decoder and the actual decoder.

### ISSUE THREAD

**Issue by singh-hrituraj** [pytorch/fairseq#195]
Hi
I noticed that the order of dimensions of the `avg_attn` which is returned in the `SequenceGenerator._decode()` by the functions from `tests/utils.py` and `fcov.py` is different.

While the attention function in fconv.py returns the dimensions as (batch_size, decoder_outputs, encoder_outputs), the one in the test_util.py returns it as (batch_size, encoder_outputs, decoder_outputs).

It is either that or I am highly mistaken.

The line in test/utils.py :
[https://github.com/pytorch/fairseq/blob/3feaccf3580459bf56dbc649de6444c055af5d56/tests/utils.py#L156](url)

The line in fcov.py :
[https://github.com/pytorch/fairseq/blob/3feaccf3580459bf56dbc649de6444c055af5d56/fairseq/models/fconv.py#L315](url)

**Comment by myleott** [comment]
Good catch, fconv.py and SequenceGenerator are correct, the unit test is wrong. Fix here: #197
