### ISSUE TITLE
`@register_model_architecture` does not register model as expected.

### ISSUE THREAD

**Issue by rawkintrevo** [pytorch/fairseq#1952]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

When following https://fairseq.readthedocs.io/en/latest/tutorial_simple_lstm.html we register a model with `@register_model_architecture(...` however when we run 

```
fairseq-train data-bin/test01 \
  --arch my_model \
```

yields: 

`fairseq-train: error: argument --arch/-a: invalid choice: 'my_model' `

#### Code sample

following the tutorial is a sufficient code sample.

### Expected behavior

We expected `my_model` to be an available architecture

### Environment

 - fairseq Version (0.8.0):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed fairseq (`pip`, source): pip (I think?)
 - Python version: 3.6
 - CUDA/cuDNN version: not applicable
 - GPU models and configuration:
 - Any other relevant information:

**Comment by rawkintrevo** [comment]
I expect by the lack of other issues on this either 
1. I have missed some obvious step
2. No one ever registers their own models

Most likely 1.

**Comment by rawkintrevo** [comment]
As expected, I missed an obvious step- 

namely, that the file muse exist in `fairseq/models/*`

Closing and sorry for bothering you.

**Comment by forestnoobie** [comment]
Can you specify the part that you missed? 
I am facing the same error and I can't find the part about that the file must exist in a
certain directory

**Comment by rawkintrevo** [comment]
Wherever your fairseq is installed, there is a directory called models. You need to put your code in that directory. 

It's in this file: https://github.com/pytorch/fairseq/blob/master/docs/tutorial_classifying_names.rst

Do a Ctrl+F for `fairseq/models` and you'll see the part.

**Comment by TingxunShi** [comment]
I don't think it's necessary to put your files into `fairseq/model`. fairseq provides an argument named `--user-dir` to indicate your own directory. However, the most important thing is if you feed in this argument, the directory you point to should have a `__init__.py`. You can check [MASS](https://github.com/microsoft/MASS/tree/master/MASS-supNMT/mass) as this is a superb example
