### ISSUE TITLE
fairseq-generate on train dataset generate non english sentence

### ISSUE THREAD

**Issue by gaopengcuhk** [pytorch/fairseq#1961]
I generate sentence from train dataset after training en-de transfomre model using the following command.

fairseq-generate \
    data-bin/wmt16_en_de_bpe32k \
    --path checkpoint.avg5.pt \
    --beam 4 --lenpen 0.6 -- --gen-subset train

However, I find many weird source sentence do not below to english. 

S-4391595	ल@@ ा@@ ग@@ ो@@ स@@ - ह@@ ा@@ ल@@ ह@@ ी@@ म@@ े@@ ं@@ न@@ ा@@ इ@@ ज@@ ी@@ र@@ ि@@ य@@ ा@@ क@@ ी@@ र@@ ा@@ ज@@ ध@@ ा@@ न@@ ी , अ@@ ब@@ ु@@ ज@@ ा@@ म@@ े@@ ं@@ र@@ े@@ स ् त@@ र@@ ा@@ ं@@ म@@ े@@ ं , र@@ ा@@ त@@ क@@ े@@ ख@@ ा@@ न@@ े@@ क@@ े@@ स@@ म@@ य@@ म@@ ै@@ ं@@ न@@ े@@ ए@@ क@@ ब@@ े@@ म@@ े@@ ल@@ ज@@ ो@@ ड ़ ी@@ द@@ े@@ ख@@ ी । आ@@ द@@ म@@ ी@@ क@@ ी@@ उ@@ म ् र@@ क@@ म@@ -@@ स@@ े@@ -@@ क@@ म@@ 60 स@@ ा@@ ल क@@ ी ल@@ ग@@ र@@ ह@@ ी@@ थ@@ ी , ल@@ े@@ क@@ ि@@ न@@ उ@@ स@@ न@@ े त@@ ं@@ ग@@ ज@@ ी@@ न ् स@@ औ@@ र ब@@ ि@@ न@@ ा ब@@ ा@@ ज@@ <unk> व@@ ा@@ ल@@ ी@@ त@@ ं@@ ग@@ ट@@ ॉ@@ प@@ प@@ ह@@ न@@ ी ह@@ ु@@ ई थ@@ ी , उ@@ स@@ क@@ े@@ ग@@ ल@@ े@@ म@@ े@@ ं@@ स@@ ो@@ न@@ े@@ क@@ ी@@ ल@@ ं@@ ब@@ ी@@ च@@ े@@ न@@ थ@@ ी@@ औ@@ र@@ आ@@ ँ@@ ख@@ ो@@ ं@@ प@@ र@@ क@@ ा@@ ल@@ ा@@ च@@ श ् म@@ ा@@ थ@@ ा , ह@@ ा@@ ल@@ ा@@ ँ@@ क@@ ि@@ व@@ ह@@ श@@ ा@@ म@@ क@@ ा@@ आ@@ ठ@@ ब@@ ज@@ े क@@ े ब@@ ा@@ द@@ क@@ ा@@ स@@ म@@ य@@ थ@@ ा । उ@@ स@@ क@@ ी@@ स@@ ं@@ ग@@ ि@@ न@@ ी , ज@@ ो@@ 22 स@@ ा@@ ल@@ स@@ े@@ ब@@ ड ़ ी@@ न@@ ह@@ ी@@ ं@@ ल@@ ग@@ र@@ ह@@ ी@@ थ@@ ी , अ@@ प@@ न@@ े@@ त@@ ी@@ न@@ द@@ ो@@ स ् त@@ ो@@ ं@@ क@@ े@@ स@@ ा@@ थ@@ फ@@ ु@@ द@@ क क@@ र उ@@ स@@ क@@ े प@@ ी@@ छ@@ े ज@@ ा@@ ख@@ ड ़ ी ह@@ ु@@ <unk> थ@@ ी । व@@ ह@@ उ@@ स@@ े उ@@ न@@ क@@ ी@@ ब@@ ा@@ त@@ च@@ ी@@ त@@ म@@ े@@ ं@@ श@@ ा@@ म@@ ि@@ ल@@ क@@ र@@ न@@ े@@ क@@ ी@@ क@@ ो@@ श@@ ि@@ श@@ क@@ र@@ र@@ ह@@ ी@@ थ@@ ी , य@@ ह@@ ा@@ ँ@@ त@@ क@@ क@@ ि@@ व@@ ह@@ क@@ भ@@ ी@@ -@@ क@@ भ@@ ी@@ उ@@ स@@ क@@ ा@@ च@@ ु@@ ं@@ ब@@ न@@ ल@@ े@@ न@@ े@@ क@@ े@@ ल@@ ि@@ ए@@ <unk> ु@@ क@@ भ@@ ी@@ ज@@ ा@@ त@@ ी@@ थ@@ ी , ल@@ े@@ क@@ ि@@ न@@ ब@@ ु@@ <unk> ी@@ -@@ स@@ ी@@ म@@ ु@@ स ् क@@ ा@@ न@@ उ@@ स@@ क@@ े@@ अ@@ म@@ ी@@ र@@ अ@@ ध@@ े@@ ड ़ प ् र@@ े@@ म@@ ी@@ क@@ ी@@ ब@@ ढ ़ त@@ ी@@ ब@@ े@@ च@@ ै@@ न@@ ी@@ क@@ ो@@ छ@@ ि@@ प@@ ा@@ न@@ ह@@ ी@@ ं@@ प@@ ा@@ र@@ ह@@ ी@@ थ@@ ी ।
T-4391595	LA@@ G@@ OS – Bei einem Abend@@ ess@@ ens in einem Restaurant in Nig@@ eri@@ as Hauptstadt A@@ bu@@ ja habe ich ein ung@@ lei@@ ches Paar beobachtet . Der Mann war mindestens 60 Jahre alt , hatte aber enge Je@@ ans und ein hau@@ ten@@ ges , är@@ mel@@ loses Hem@@ d an und trug dazu eine di@@ cke Gold@@ kette und eine dunk@@ le Sonnen@@ bri@@ lle , obwohl es nach acht Uhr abends war .
H-4391595	-3.7127748814730803	Aber wir sind nicht nur ein G@@ lied - wir sind nicht nur ein G@@ lied , sondern auch ein G@@ lied in der wirtschaftlichen Entwicklung , wir sind auch nicht in der Lage , M@@ aul@@ - und K@@ lau@@ en@@ seu@@ che zu bekämpfen .
P-4391595	-1.7054 -3.1111 -1.6422 -0.8140 -0.0720 -0.5041 -0.8917 -2.9632 -2.9660 -0.1125 -0.1343 -1.0052 -0.8590 -0.0960 -0.2773 -0.1504 -0.5922 -0.7822 -0.2483 -0.1530 -0.7925 -0.0440 -1.2770 -0.3416 -4.0124 -0.2932 -0.1715 -0.4507 -0.1658 -0.5294 -0.3495 -3.2479 -0.1096 -0.0359 -0.1280 -2.9383 -0.9334 -0.4903 -0.1379 -0.0603 -0.0660 -0.1297 -0.0096 -0.1079 -0.7617 -0.4751 -0.1831 -0.5606

S-4391601	स ् व@@ ा@@ स ् थ ् य@@ -@@ द@@ े@@ ख@@ भ@@ ा@@ ल@@ क@@ े@@ म@@ ा@@ म@@ ल@@ े@@ म@@ े@@ ं , घ@@ ा@@ न@@ ा@@ क@@ ी@@ m@@ P@@ edi@@ gre@@ e न@@ े@@ ट@@ व@@ र ् क@@ - न@@ क@@ ल@@ ी@@ द@@ व@@ ा@@ ओ@@ ं@@ क@@ ा@@ प@@ त@@ ा@@ ल@@ ग@@ ा@@ न@@ े@@ क@@ े@@ ल@@ ि@@ ए@@ म@@ ो@@ ब@@ ा@@ इ@@ ल@@ श@@ ॉ@@ र ् ट@@ क@@ ो@@ ड@@ प ् र@@ ण@@ ा@@ ल@@ ी@@ ल@@ ा@@ ग@@ ू@@ क@@ र@@ न@@ े@@ व@@ ा@@ ल@@ ी@@ प@@ ह@@ ल@@ ी@@ क@@ ं@@ प@@ न@@ ी@@ ह@@ ै , ज@@ ि@@ न@@ क@@ े क@@ ा@@ र@@ ण@@ द@@ ु@@ न@@ ि@@ य@@ ा@@ भ@@ र@@ म@@ े@@ ं@@ ह@@ र@@ र@@ ो@@ ज ़ औ@@ स@@ त@@ न@@ 2@@ ,000 ल@@ ो@@ ग@@ ो@@ ं@@ क@@ ी@@ म@@ ृ@@ त ् य@@ ु@@ ह@@ ो@@ त@@ ी@@ ह@@ ै । ब@@ ु@@ न@@ ि@@ य@@ ा@@ द@@ ी@@ म@@ ो@@ ब@@ ा@@ इ@@ ल@@ फ@@ ो@@ न@@ क@@ ा@@ इ@@ स ् त@@ े@@ म@@ ा@@ ल@@ क@@ र@@ क@@ े , ल@@ ो@@ ग@@ त@@ ु@@ र@@ ं@@ त@@ - औ@@ र@@ ब@@ ि@@ न@@ ा@@ क@@ ि@@ स@@ ी@@ ख ़ र ् च@@ क@@ े@@ - ज@@ ा@@ ँ@@ च क@@ र@@ स@@ क@@ त@@ े@@ ह@@ ै@@ ं@@ क@@ ि@@ क@@ ो@@ <unk> द@@ व@@ ा@@ अ@@ स@@ ल@@ ी@@ ह@@ ै@@ य@@ ा@@ न@@ ह@@ ी@@ ं । इ@@ स@@ ी@@ त@@ र@@ ह , भ@@ ा@@ र@@ त@@ म@@ े@@ ं@@ व@@ ि@@ क@@ स@@ ि@@ त@@ ए@@ ं@@ ब ् र@@ े@@ स श@@ ि@@ श@@ <unk> व@@ ा@@ र ् म@@ र क@@ ी@@ ल@@ ा@@ ग@@ त@@ - अ@@ म@@ े@@ र@@ ि@@ क@@ ा@@ म@@ े@@ ं@@ 2@@ ,000 ड@@ ॉ@@ ल@@ र म@@ े@@ ं म@@ ि@@ ल@@ न@@ े@@ व@@ ा@@ ल@@ े प@@ ा@@ र@@ ं@@ प@@ र@@ ि@@ क@@ इ@@ न ् क ् य@@ ू@@ ब@@ े@@ ट@@ र@@ क@@ ी क@@ ी@@ त@@ ु@@ ल@@ न@@ ा@@ म@@ े@@ ं -@@ ल@@ ग@@ भ@@ ग@@ 200 ड@@ ॉ@@ ल@@ र@@ ह@@ ै@@ - ज@@ ि@@ स@@ स@@ े@@ ज@@ न ् म@@ क@@ े@@ स@@ म@@ य@@ क@@ म@@ व@@ ज ़ न@@ व@@ ा@@ ल@@ े@@ औ@@ र@@ स@@ म@@ य@@ स@@ े@@ प@@ ू@@ र ् व@@ ज@@ न ् म@@ ल@@ े@@ न@@ े@@ व@@ ा@@ ल@@ े@@ ल@@ ा@@ ख@@ ो@@ ं@@ ब@@ च ् च@@ ो@@ ं@@ क@@ ी@@ इ@@ स@@ ज@@ ी@@ व@@ न@@ -@@ र@@ क ् ष@@ क@@ स@@ ं@@ स@@ ा@@ ध@@ न@@ त@@ क@@ प@@ ह@@ ु@@ ँ@@ च@@ ह@@ ो@@ ज@@ ा@@ त@@ ी@@ ह@@ ै ।
T-4391601	Im Zusammenhang mit dem Gesundheitswesen wäre da das m@@ P@@ edi@@ gre@@ e Network in Gh@@ ana zu nennen : das erste Unternehmen , das mobile Kurz@@ co@@ des@@ ysteme einsetzt , um gefäl@@ schte Medikamente zu erkennen , die jeden Tag weltweit 2000 Todes@@ fälle verursachen . Jeder kann sofort - und gratis - mit einem normalen Mobiltelef@@ on nach@@ prüfen , ob ein bestimmtes Medik@@ ament echt ist oder nicht .
H-4391601	-3.8712744364735463	Das Gesundheitswesen und der Kampf gegen den Terrorismus in den nächsten Jahren , die Vern@@ etzung der P@@ edi@@ gre@@ e in den nächsten Jahren , die Bereitstellung von Sach@@ leistungen in Form von Sach@@ leistungen - die Bereitstellung von Sach@@ leistungen für Frauen und Männer in den Entwicklungsländern .
P-4391601	-0.8614 -2.3518 -0.1736 -1.2391 -3.4382 -0.1897 -0.0998 -1.4418 -2.3481 -0.3356 -0.8404 -1.0472 -0.2648 -1.2862 -0.5729 -0.0660 -0.8487 -0.2653 -0.0161 -0.0750 -1.1453 -0.8455 -0.7186 -3.2845 -0.1909 -1.0683 -0.4768 -0.2078 -0.0798 -1.5222 -0.4404 -1.0715 -1.4971 -0.1499 -0.6643 -0.2220 -1.0540 -0.3776 -0.5157 -0.1163 -0.0389 -0.2071 -0.3982 -1.6960 -0.3295 -0.9710 -0.1561 -0.5086 -0.3247 -2.7148 -0.2083

**Comment by gaopengcuhk** [comment]
It seems like the original En-De WMT dataset contain some arabic and russian language as a nosie?

**Comment by myleott** [comment]
Yes, the WMT training datasets often contain some noise. If you want to help tackle this problem, there's a shared task on filtering parallel datasets: http://www.statmt.org/wmt20/parallel-corpus-filtering.html
