### ISSUE TITLE
Convert list of sentences to IndexedRawTextDataset

### ISSUE THREAD

**Issue by ajesujoba** [pytorch/fairseq#1965]
Does fairseq currently have a method to convert a list of sentences/string to `IndexedRawTextDataset `? From the code,  `IndexedRawTextDataset ` reads the sentences from a file.

I actually want to create `monolingual dataset` from the list of sentences, is there a way to get that done directly without going through the `IndexedRawTextDataset ` route?

**Comment by myleott** [comment]
You can use `fairseq-preprocess --only-source` to binarize the text (similar to what's used for binarizing language modeling text) and then in the code use `data_utils.load_indexed_dataset` to get the appropriate IndexedDataset instance.

**Comment by ajesujoba** [comment]
Hi, the explanation you gave implies that I have the text/sentences in a file, which is not what is happening in my case. A different process is generating the list of sentences and the sentences are not written to file.

**Comment by myleott** [comment]
Ah, you can create a MonolingualDataset with any object that implements the `torch.utils.data.Dataset` interface. So `MonolingualDataset(your_list_of_tensors, ...)` should work. No need to use IndexedRawTextDataset (which is focused on files).
