### ISSUE TITLE
What is the best practice to finetune a bilingual MT model with multiple languese? Preprossesing is matter, because the languages and the dictionaries are different! 

### ISSUE THREAD

**Issue by fahimeh-saleh** [pytorch/fairseq#1974]
## 👉 [Please follow one of these issue templates](https://github.com/pytorch/fairseq/issues/new/choose) 👈

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by huihuifan** [comment]
Please follow the issue templates and provide additional detail
