### ISSUE TITLE
Reproduce WMT en-de results @ "Scaling NMT"

### ISSUE THREAD

**Issue by marshmallow111** [pytorch/fairseq#1976]
Hi there,

I'm trying to reproduce results from Scaling NMT on WMT en-de dataset. Currently, I followed the tutorial and changed the LR to 0.001 and update-freq to 32/16, and enabled c_10d DDP backend. 

I trained the model on 4 V100s for 40k steps (update-freq=32), and I got 28.56 BLEU score with an average of the last 5 checkpoints (beam=4, lenpen=0.6), while the paper reported 29.3. I also got around 28.57 when I trained with 8 V100s for 40k steps (update-freq=16).

My validation perplexity seems to not change much from a while ago and is around 4.22 at the end of 40k steps. My training perplexity is around 4.3-4.4. I'm using pytorch 1.4.0,  python 3.6 and nvcc version 10.0.

What is the expected # of training steps, and final training perplexity? Does fairseq-generate by default use compound splitting? 

Do you have any suggestions on how to reproduce the results? Thanks in advance!!

**Comment by huihuifan** [comment]
Are you averaging checkpoints and adding compound splitting? Please follow the readme here: https://github.com/pytorch/fairseq/tree/master/examples/scaling_nmt

**Comment by myleott** [comment]
For en-de, we trained for 70 epochs or ~24k steps using the large batch size.

Our final train perplexity was 4.71 and valid perplexity was 4.19. So it seems like you may have trained a bit longer than we did. Can you share the training log?

> Does fairseq-generate by default use compound splitting?

No, you need to apply this manually using the instructions @huihuifan shared above.

**Comment by marshmallow111** [comment]
@huihuifan  @myleott  Thanks for the reply! 

It seems that If I use the following script (as suggested by @huihuifan), I'm able to get 29.1 BLEU!

A follow-up question:
If I follow the following instruction, does it include compound splitting or do I have to use tensor2tensor script? Does it use multi-bleu.perl? 

```
fairseq-generate data-bin/wmt16_en_de_bpe32k --path checkpoint.pt --batch-size 64 --beam 4  --lenpen 0.6 --remove-bpe --gen-subset test > raw_result
GEN=raw_result

SYS=$GEN.sys
REF=$GEN.ref

grep ^H $GEN | cut -f3- | perl -ple 's{(\S)-(\S)}{$1 ##AT##-##AT## $2}g' > $SYS
grep ^T $GEN | cut -f2- | perl -ple 's{(\S)-(\S)}{$1 ##AT##-##AT## $2}g' > $REF
python score.py --sys $SYS --ref $REF
```

**Comment by tholiao** [comment]
@marshmallow111, if you wish to use the full bag of tricks from Vaswani17, you'll want to convert quotes as well. See https://github.com/tensorflow/tensor2tensor/issues/317#issuecomment-380970191 . I am not sure whether this was used for Ott18 (@myleott ?)

As for reporting scores, compound splitting has been used in several papers since Vaswani17 to facilitate accurate comparisons - BLEU is markedly lower without this adjustment. My personal suggestion would be to report fully detokenized BLEU (i.e., without compound splitting) using SacreBLEU (pass `--sacrebleu` to score.py) with the SacreBLEU signature in addition to customized / nonstandard scoring.

**Comment by yongchanghao** [comment]
I trained my model using stansford wmt14 en-de data, and found that the data have already been compound-splitted. Should I still use the `compound_split_bleu.sh` to yield the BLEU score?

**Comment by zml24** [comment]
Hi, I trained Transformer Base using 8 V100 for 30k steps but result in 26.95, can you help me figure out what the wrong is?
```
export DATA_DIR=/mnt/workplace/data-bin
export ARCH=$2
export DATA=wmt16_en_de_bpe32k
export CKT_DIR=/mnt/workplace/checkpoints/$DATA/$ARCH

python -m torch.distributed.launch --nproc_per_node=8 --master_port $PORT $(which fairseq-train) \
    $DATA_DIR/$DATA \
    --seed 42 \
    --arch transformer --share-all-embeddings \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 5.0 \
    --lr 0.0005 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07 \
    --dropout 0.3 --weight-decay 0.0 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --max-tokens 5120 --update-freq 16 \
    --log-interval 1000 --save-interval 1000000 --save-interval-updates 1000 \
    --no-progress-bar --num-workers 8 \
    --ddp-backend no_c10d \
    --save-dir $CKT_DIR --max-update 30000 \
    --fp16

python scripts/average_checkpoints.py \
    --inputs $CKT_DIR \
    --num-update-checkpoints 10 \
    --output $CKT_DIR/checkpoint.avg10.pt

fairseq-generate \
    $DATA_DIR/$DATA \
    --path $CKT_DIR/checkpoint.avg10.pt \
    --beam 4 --lenpen 0.6 --remove-bpe > gen.out

bash scripts/compound_split_bleu.sh gen.out
```
And the result is 
```
Namespace(ignore_case=False, order=4, ref='gen.out.ref', sacrebleu=False, sentence_bleu=False, sys='gen.out.sys')
BLEU4 = 26.95, 58.2/32.6/20.6/13.5 (BP=1.000, ratio=1.017, syslen=65592, reflen=64496)
```

**Comment by zml24** [comment]
I also tried to change the `max_tokens` to 3584 and `update_freq` to 1, and train the model for ~250k steps, but the bleu score is still 26.97.
