### ISSUE TITLE
Windows install error 

### ISSUE THREAD

**Issue by MrLee66** [pytorch/fairseq#1982]
#### What is your question?
Windows install fairseq failed,  ERROR: Failed building wheel for mecab-python3.So who can help me ,thanks a lot.
#### Code
Building wheels for collected packages: mecab-python3
  Building wheel for mecab-python3 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\softwares\anconda\envs\FairSeqTrain\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lhx18\\AppData\\Local\\Temp\\pip-install-8yh4itws\\mecab-python3\\setup.py'"'"'; __file__='"'"'C:\\Users\\lhx18\\AppData\\Local\\Temp\\pip-install-8yh4itws\\mecab-python3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\lhx18\AppData\Local\Temp\pip-wheel-eohox3gr'
       cwd: C:\Users\lhx18\AppData\Local\Temp\pip-install-8yh4itws\mecab-python3\
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\MeCab
  copying src\MeCab\__init__.py -> build\lib.win-amd64-3.6\MeCab
  running build_ext
  error: [WinError 2] system can't find specific file。
  ERROR: Failed building wheel for mecab-python3
  Running setup.py clean for mecab-python3
  ----------------------------------------
   

#### What's your environment?
windows 10
ancoanda
python3.6.5
pip install -e .

**Comment by yuyan2do** [comment]
Only sarcrebleu require install **mecab-python3**, which cause error when build in windows. Remove it from setup.py unblock me build this project. 

Remove this line. https://github.com/pytorch/fairseq/blob/v0.9.0/setup.py#L141
