### ISSUE TITLE
Sampling from GeneratorHubInterface does not generate anything

### ISSUE THREAD

**Issue by noe** [pytorch/fairseq#1983]
## 🐛 Bug

When calling function `sample` from `hub_utils.GeneratorHubInterface`, as specified in the [language modeling readme](https://github.com/pytorch/fairseq/tree/master/examples/language_model), the result is always the same prefix passed as argument to the function, with no extra tokens sampled from the LM.

Internally, the problem is that, when the sentence is converted to token IDs, the EOS token ID is added. When the model is presented with a prefix that "has already ended", it just generates another EOS and finishes.

### To Reproduce

Just follow the code to sample from an LM from the [language modeling readme](https://github.com/pytorch/fairseq/tree/master/examples/language_model).

#### Code sample

```
from fairseq.models.transformer_lm import TransformerLanguageModel
custom_lm = TransformerLanguageModel.from_pretrained('/path/to/model/dir', 'checkpoint100.pt')
custom_lm.sample('Barack Obama', beam=1)
```

### Expected behavior

The returned sampled sentences have more tokens apart from the ones already supplied as argument to `sample`.

### Environment

 - fairseq Version: master:
 - PyTorch Version: 1.4.0
 - OS: Ubuntu 16.04.2 LTS
 - How you installed fairseq: from source
 - Python version: 3.7.4
 - CUDA/cuDNN version: none
 - GPU models and configuration: none

**Comment by noe** [comment]
I would be happy to provide a PR.

**Comment by bcmi220** [comment]
same issue

**Comment by xuanqing94** [comment]
I got a similar issue here, I copied the code from template: https://github.com/pytorch/fairseq/tree/master/examples/language_model
```
lm.sample('Barack Obama', sampling=True, sampling_topk=10, temperature=0.9)
>>> "Barack Obama"
```
It won't generate any longer sentence except 'Barack Obama'.

**Comment by myleott** [comment]
Ah, thanks for flagging. I mistakenly broke this in 7c0ab23d14882d77ae5017ee71085925c5c03373.

Will submit a fix shortly.
