### ISSUE TITLE
checkpoint_utils.py: move os.makedirs() from load_checkpoint() to save_checkpoint()

### ISSUE THREAD

**Issue by rronan** [pytorch/fairseq#1986]
Hello,

In the current implementation ```fairseq.checkpoint_utils```, the directory ```args.save_dir``` is created in ```load_checkpoint()```  instead of ```save_checkpoint()```:

https://github.com/pytorch/fairseq/blob/master/fairseq/checkpoint_utils.py#L123

Is there any reason for this? The reasons why I would have it in ```save_checkpoint()``` are: 
1. If I  train model from scratch, I don't want ```args.save_dir``` to be created at the very beginning of the run (where ```load_checkpoint()``` would typically be called). I'd rather create it just before saving the checkpoint to avoid having an empty folder left if the run exists between ```load_checkpoint()``` and ```save_checkpoint()```.
2. if calling ```save_checkpoint()``` without having called ```load_checkpoint()``` first, it might raise a ```FileNotFoundError```.  I actually never was in that situation but it's a guess.

If you agree with this I can make a PR.

**Comment by alexeib** [comment]
i dont think there is any particular reason - please feel free to submit a pr to change this behavior
