### ISSUE TITLE
fairseq & R : A new package?

### ISSUE THREAD

**Issue by lbocken** [pytorch/fairseq#1989]
Hello everyone, I would like to use fairseq in or with R… What are your best advices? Could it be possible to build a specific R package ? How to begin? Thank you very much for your help !

**Comment by noe** [comment]
Have you tried an R package called [`reticulate`](https://cran.r-project.org/web/packages/reticulate/)? It allows you to call Python stuff from R. It is maintained by RStudio themselves. You can find out more in [their web page](https://rstudio.github.io/reticulate/).

**Comment by lbocken** [comment]
I will look into that... I’m just in the beginning of the project and it would be great to benefit from all of your advices to avoid lost of time… Thank you very much for your help !

**Comment by huihuifan** [comment]
We currently do not have plans to support fairseq within R.
