### ISSUE TITLE
Assertion Error in preprocessing of FAIR Sequence-to-Sequence Toolkit for Story Generation

### ISSUE THREAD

**Issue by ottj** [pytorch/fairseq#199]
when I run 
$ TEXT=examples/stories/writingPrompts
$ python preprocess.py --source-lang wp_source --target-lang wp_target \
  --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test \
  --destdir data-bin/writingPrompts --thresholdtgt 10 --thresholdsrc 10

I get an AssertionError:
Traceback (most recent call last):
  File "preprocess.py", line 201, in <module>
    main(args)
  File "preprocess.py", line 101, in main
    padding_factor=args.padding_factor,
  File "/home/username/workspace/benchmarking-tools/fairseq/fairseq/data/dictionary.py", line 137, in finalize
    assert len(new_count) == self.nspecial or min(new_count[self.nspecial:]) >= threshold
AssertionError

Upon inspection i see that min(new_count[self.nspecial:]) is 0

**Comment by myleott** [comment]
You can remove that assert, it's unnecessary. Fixed in #200.
