### ISSUE TITLE
Pre-processing Script

### ISSUE THREAD

**Issue by JustCunn** [pytorch/fairseq#1990]
I know this isn’t really an issue, more just a question. I’m relatively new to all this, but in the docs, for the example pre-processing, a script called ‘prepare-iwslt14.sh’ is called. I’ve looked into it but I want to ask, is it necessary to have shell scripts like these, and if so why?

I’d appreciate it if anyone could help me with this.

For info:
 - fairseq Version: 0.9
 - PyTorch Version: 1.4.0
 - OS: Ubuntu (Linux)

**Comment by erip** [comment]
What's necessary for good performance is to tokenize and byte-pair encoder your inputs. Because `fairseq-preprocess` doesn't perform this for you, something will have to. The most convenient way to do this in an experiment is with scripts like `prepare-iwslt14.sh`.

**Comment by JustCunn** [comment]
Yeah, It’s just different coming from something like OpenNMT-py that does have some options to do pre-processing like that. Thanks very much for clearing that up!

**Comment by erip** [comment]
PRs are welcome. 😄

**Comment by huihuifan** [comment]
Thanks @erip for answering! Yes, usually we preprocess the data with a separate script, though you can link it together with your training. The prepare-iwslt script also downloads data, I believe.

**Comment by JustCunn** [comment]
Just while I have this thread, instead of opening a new one because I think the two issues might be related, but after training, when using Fairseq-generate, I enter `—batch-size 128` But it tells me that `--max-sentences/--batch-size cannot be larger than --buffer-size' print(args) `. It only works with a batch size of 0. I don’t know if this is affecting my translation quality or not. Could it have been pre-processed wrong?

**Comment by myleott** [comment]
You're probably using `fairseq-interactive`, right? In that case, `--buffer-size` controls how many lines are read before generation happens. So just set `buffer-size=2000` and it should be fine. It will read 2000 lines and construct batches of size 128 out of it.

**Comment by JustCunn** [comment]
Yeah it must’ve been an issue like that. Whatever it was, it’s gone now, so that’s all good. Thanks for that though!
