### ISSUE TITLE
How to measure the FLOPS for Neural Machine Translation

### ISSUE THREAD

**Issue by gaopengcuhk** [pytorch/fairseq#2000]
As the title implies, is there anyway to evaluate the FLOPs for NMT?

**Comment by huihuifan** [comment]
Currently, we do not have a nice inbuilt way to handle this, but we would really be interested in this feature!

**Comment by myleott** [comment]
Unfortunately I think this is too difficult to do in a general way, so we won't be able to support it as a native fairseq feature.

That said, I've used this before and it works great: http://www.bnikolic.co.uk/blog/python/flops/2019/10/01/pytorch-count-flops.html. The only downside is that it can be a pain to setup PAPI on some environments.

There's also [THOP](https://github.com/Lyken17/pytorch-OpCounter), but you'll need to define the FLOPs manually for a few layers (e.g., multi-head attention).

**Comment by gaopengcuhk** [comment]
Thank you for your response.
I want to know how to define the flops for sequence generation problem? Sequence generation FLOPS depends on the generated sequence which will be higher for longer sentence.

**Comment by myleott** [comment]
I'd recommend measuring FLOPs for an average-length source and target sequence.

**Comment by gaopengcuhk** [comment]
I will calculate the total Multiplication and addition number of transformer on TEST dataset as a FLOPs evaludation. 

Do you think this is reasonable?

**Comment by gaopengcuhk** [comment]
Also, I will setup Beam Search Size as 1.
