### ISSUE TITLE
Explanation of Extra Embeddings after generation from Dict

### ISSUE THREAD

**Issue by reachtarunhere** [pytorch/fairseq#2004]
### What is your question?

Hi! I am trying to extract word embeddings and do some analysis on a transformer model I trained. Compared to the srcdict used to generate the emeddings the 'encoder.embed_tokens.weight' seems to have 4 more tokens. Can someone confirm if these extra or special tokens are at the end, beginning or somewhere else. Also, is the order of the srcdict maintained when initializing the embedding matrix.

Thanks!

**Comment by huihuifan** [comment]
Hello, the source dict models special tokens in the dictionary, such as unk and start of sentence. The order is maintained and they are always appended at the beginning. You can see the tokens added if you check the dictionary.py file.

**Comment by reachtarunhere** [comment]
Thanks I got my thing to work :)

**Comment by huihuifan** [comment]
fantastic!
