### ISSUE TITLE
En-Fr result in scaling neural machine translation have compound spliting or not?

### ISSUE THREAD

**Issue by gaopengcuhk** [pytorch/fairseq#2009]
As the name implies, the En-Fr BLEU in Scaling Neural Machine Translation have compound splitting or not?

**Comment by huihuifan** [comment]
@edunov ?

**Comment by myleott** [comment]
We include both results in the paper.

We report 43.2 BLEU with compound splitting. The compound splitting is built-in to the [preprocessing script](https://github.com/pytorch/fairseq/blob/master/examples/translation/prepare-wmt14en2fr.sh#L89)).

We also report 41.4 detokenized BLEU without compound splitting, using sacrebleu. We use the Moses detokenizer.

**Comment by gaopengcuhk** [comment]
bash scripts/compound_split_bleu.sh wmt16_gen.txt

Can I use compound split bleu on En-Fr?

**Comment by myleott** [comment]
No, don't use the `compound_split_bleu.sh` script for En-Fr. The underlying data already has compound splitting built-in. The BLEU score output from `fairseq-generate (...) --remove-bpe` can be reported directly as the compount-split BLEU score.
