### ISSUE TITLE
cannot import name 'libnat_cuda' from 'fairseq' (fairseq-master/fairseq/__init__.py)... fall back to CPU version

### ISSUE THREAD

**Issue by zhangxinlu16** [pytorch/fairseq#2010]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### Code
When I trying to train a new model for machine translation, always have the following errors. I try to change the  version of fairseq but it is still not work. 

   

cannot import name 'libnat_cuda' from 'fairseq' (/home/fairseq-master/fairseq/__init__.py)... fall back to CPU version
cannot import name 'libnat_cuda' from 'fairseq' (/home/fairseq-master/fairseq/__init__.py)... fall back to CPU version
cannot import name 'libnat_cuda' from 'fairseq' (/home/fairseq-master/fairseq/__init__.py)... fall back to CPU version
#### What's your environment?

 - fairseq Version (e.g., 0.9 or master):
 - PyTorch Version (e.g., 1.4)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):source
 - Build command you used (if compiling from source):
 - Python version:3.7.7
 - CUDA/cuDNN version:10.0
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ljw870202** [comment]
u should compiling from source like 'python setup.py build_ext --inplace',after build there exists libnat_cuda.cpython-37m-x86_64-linux-gnu.so in fairseq source folder.

**Comment by zhangxinlu16** [comment]
> python setup.py build_ext --inplace

Thanks, but how to build libnat_cuda.cpython-37m-x86_64-linux-gnu.so？

**Comment by zhangxinlu16** [comment]
> u should compiling from source like 'python setup.py build_ext --inplace',after build there exists libnat_cuda.cpython-37m-x86_64-linux-gnu.so in fairseq source folder.

After compiling from source, I only get libbleu.cpython-37m-x86_64-linux-gnu.so and libnat.cpython-37m-x86_64-linux-gnu.so. I can find libnat_cuda.cpython-37m-x86_64-linux-gnu.so. Is there anything wrong with me？

**Comment by zhangxinlu16** [comment]
> u should compiling from source like 'python setup.py build_ext --inplace',after build there exists libnat_cuda.cpython-37m-x86_64-linux-gnu.so in fairseq source folder.

After compiling from source, I only get libbleu.cpython-37m-x86_64-linux-gnu.so and libnat.cpython-37m-x86_64-linux-gnu.so. I can‘t find libnat_cuda.cpython-37m-x86_64-linux-gnu.so. Is there anything wrong with me？

**Comment by Ir1d** [comment]
I'm having same error: "cannot import name libnat_cuda".
I've run "python setup.py build_ext --inplace" already. and I can find the file `build/lib.linux-x86_64-3.6/fairseq/libnat.cpython-36m-x86_64-linux-gnu.so`

**Comment by Ir1d** [comment]
Be sure to set CUDA_HOME in env : https://github.com/pytorch/fairseq/blob/master/setup.py#L82

**Comment by zhangxinlu16** [comment]
> Be sure to set CUDA_HOME in env : https://github.com/pytorch/fairseq/blob/master/setup.py#L82

I set CUDA_HOME in os.environ, but it's still not work. How did you set it up?

**Comment by Ir1d** [comment]
`export CUDA_HOME = xxx` the `xxx` folder contains some version.txt.
Then run setup.py again, you'll see there's a line saying libnat_cuda was built.

**Comment by zhangxinlu16** [comment]
> `export CUDA_HOME = xxx` the `xxx` folder contains some version.txt.
> Then run setup.py again, you'll see there's a line saying libnat_cuda was built.

Thanks, I have solved it!

**Comment by dmortem** [comment]
Hi,

I hope to run lev_transformer on a cpu-only machine. I installed libnat, and there is a "linnet.cpython-36m-darwin.so' in the fairseq source folder. But I met the problem of "cannot import name 'libnat_cuda'... fall back to CPU version", how can I solve it? Thanks!

**Comment by wentinghome** [comment]
> `export CUDA_HOME = xxx` the `xxx` folder contains some version.txt.
> Then run setup.py again, you'll see there's a line saying libnat_cuda was built.

Hi Dejia,

I got a problem while trying to set the CUDA_HOME. I install cuda through conda using `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch` from Pytorch https://pytorch.org/. I'm wondering if you could suggest where to find the cuda_home path under this setting?  Thanks!

**Comment by aritzzz** [comment]
> > `export CUDA_HOME = xxx` the `xxx` folder contains some version.txt.
> > Then run setup.py again, you'll see there's a line saying libnat_cuda was built.
> 
> Thanks, I have solved it!

Hey zhangxinlu16,
Where did you add this export CUDA_HOME line? I added it in .bashrc but I am still getting this error?

**Comment by wangpeng138375** [comment]
I also had this problem， my pytorch versin is 1.5.1 and cuda version is 9.2 . I can't get file like 'libnat_cuda.cpython-36m-x86_64-linux-gnu.so' even I set CUDA_HOME under newest fairseq.

**Comment by wangpeng138375** [comment]
I solve that with "sudo -E pip  install --editable ./" which make sure "sudo" uses CUDA_HOME environment variables

**Comment by QzzIsCoding** [comment]
> > `export CUDA_HOME = xxx` the `xxx` folder contains some version.txt.
> > Then run setup.py again, you'll see there's a line saying libnat_cuda was built.
> 
> Thanks, I have solved it!

hi, how did u solve the problem?

**Comment by RamoramaInteractive** [comment]
I only get _alignment_train_cpu_binding.cpython-37m-x86_64-linux-gnu.so_ . Why?

On the Tesla server I have CUDA 10.2

After `export CUDA_HOME=/usr/local/cuda` I still receive

> cannot import name 'libnat_cuda' from 'fairseq' (/home/fairseq/fairseq/__init__.py)... fall back to CPU version

**Comment by conan1024hao** [comment]
@Ir1d 
I solved it by `python setup.py build_ext`, no `--inplace`

**Comment by EchoDreamer** [comment]
> I only get _alignment_train_cpu_binding.cpython-37m-x86_64-linux-gnu.so_ . Why?
> 
> On the Tesla server I have CUDA 10.2
> 
> After `export CUDA_HOME=/usr/local/cuda` I still receive
> 
> > cannot import name 'libnat_cuda' from 'fairseq' (/home/fairseq/fairseq/**init**.py)... fall back to CPU version

same with you

**Comment by kyoto7250** [comment]
I had the same problem, so I reinstalled the torch corresponding to the CUDA platform.
(I tried other methods I came up with, but I could not get good results...)

My workflow is this.
```bash
# force-install
pip3 install torch --force-reinstall --index-url https://download.pytorch.org/whl/cu118

# use: https://github.com/facebookresearch/fairseq/blob/e16e44c658495ab3d704e25cf0b8c2c3eef6a476/setup.py#L105
export CUDA_HOME='/usr/local/cuda-11.8'

# build and I could get `alignment_train_cuda_binding.cpython-38-x86_64-linux-gnu.so` 
python3 setup.py build_ext --inplace
```
