### ISSUE TITLE
Replace apex.FusedLayerNorm by PyTorch core FusedLayerNorm

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/fairseq#2012]
Fairseq still [uses](https://github.com/pytorch/fairseq/blob/master/fairseq/modules/layer_norm.py) apex.FusedLayerNorm. However, https://github.com/pytorch/pytorch/pull/27634 merged FusedLayerNorm in core PyTorch. I propose usage of core PyTorch LayerNorm as the first choice

**Comment by myleott** [comment]
I measured the performance on PyTorch 1.5 and torch.nn.LayerNorm is still slower than apex.FusedLayerNorm for shapes typical in NLP models.

It seems they didn't really test it on typical NLP shapes in https://github.com/pytorch/pytorch/pull/27634.

Benchmark script: https://gist.github.com/myleott/071da5c68c884b750ca4ec81dc414183
Output on a V100 using PyTorch 1.5:
```
upstream layernorm 1.519
apex layernorm 0.975
upstream half layernorm 1.069
apex half layernorm 0.580
```
