### ISSUE TITLE
How to save model output from fairseq-generate?

### ISSUE THREAD

**Issue by skurzhanskyi** [pytorch/fairseq#2015]
I just follow the tutorial and stuck on this command:
```
fairseq-generate data-bin/iwslt14.tokenized.de-en \
    --path checkpoints/fconv/checkpoint_best.pt \
    --batch-size 128 --beam 5
```
How can I save model output on test part of my data? I spent a solid amount of time, but didn't find the answer. I found `--results-path` argument, but for some reason, it doesn't work for me and save data in a strange format, like `H- ...`.  Is there just to save the model output (predictions) on particular data?
Sorry, if this question is obvious, but I didn't find anything in docs.

**Comment by Alex-Fabbri** [comment]
You can just grep what's in your --results-path file to get the output. Otherwise afaik there isn't a way to get just the outputs. 

grep ^T output.txt | cut -f2-  > target.txt
grep ^H output.txt | cut -f3-  > hypotheses.txt

**Comment by myleott** [comment]
Yep, @Alex-Fabbri is right!

**Comment by skurzhanskyi** [comment]
Thanks for the swift answer

**Comment by NikhilPr95** [comment]
It would be great if there was a way to specify an output file on the command line. Currently I am facing issues because the console I am printing to does not have the necessary fonts.

**Comment by Jiahao004** [comment]
how could I save the output to shards?
