### ISSUE TITLE
What does the args in decoder layer ,e.g., 'prev_attn_state', 'prev_conv_state', use for? I have not found any usage of this args.

### ISSUE THREAD

**Issue by luogen1996** [pytorch/fairseq#2017]
for example, in LightConvDecoderLayer, there are some args which is set to `None` . I have not found  where these  args are assigned some values: 
```
    def forward(self, x, encoder_out, encoder_padding_mask, incremental_state,
                prev_conv_state=None, prev_attn_state=None, conv_mask=None,
                conv_padding_mask=None):
```

**Comment by lematt1991** [comment]
You're right, this does in fact seem to be unused.  I also can't find any use of it searching through the commit history.  Maybe @myleott knows?  Either way, it seems it can probably be removed.

**Comment by myleott** [comment]
Looks like this is used in pytorch/translate for ONNX export compatibility. That project is being deprecated and the team is migrating to fairseq with a plan to use TorchScript instead of ONNX. We can remove these options once the migration is complete :)

**Comment by lcxywfe** [comment]
@myleott Hi, I'm new to fairseq, I just want to ask, why used ```argparse.Namespace``` here to pass the args? Not dict or *args
