### ISSUE TITLE
The right process to properly train the NAT models with fairseq

### ISSUE THREAD

**Issue by alphadl** [pytorch/fairseq#2019]
Recently, when I training [NAT models](https://github.com/pytorch/fairseq/blob/master/examples/nonautoregressive_translation/scripts.md) with fairseq, I encountered many problems, such as segment fault, CUDA_error etc., I checked a lot of issues, but found that there is no right solution under the master branch. 

After kinds of exploration, I finally installed it correctly. You can reproduce it with following script, and I kindly suggest that the author could add this in the NAT readme file:

```
git clone https://github.com/pytorch/fairseq.git && cd fairseq
git reset --hard 5d7a81099462e9f19715ce5fa37c03816a750e12
conda install gcc_linux-64 gxx_linux-64
pip install torch && pip install cython
python setup.py build_ext --inplace
```

**Comment by lematt1991** [comment]
Do you have an open issue regarding the seg fault/CUDA errors that you observed?  The proper solution is to get these issues resolved, rather than to update the docs telling people to checkout a specific commit.
