### ISSUE TITLE
How to Preprocess Files for fine tuning XLM-R?

### ISSUE THREAD

**Issue by swethathomas** [pytorch/fairseq#2025]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by lematt1991** [comment]
The [checkpoint files](https://github.com/pytorch/fairseq/blob/master/examples/xlmr/README.md#pre-trained-models) contain sentencepiece models as well as the dictionaries.  You should apply the sentencepiece model to your text, and then use fairseq-preprocess with the provided dictionaries.
