### ISSUE TITLE
How to control the randomness of BART summary output?

### ISSUE THREAD

**Issue by aliasneo1** [pytorch/fairseq#2034]
Currently BART model trained on CNN dataset  is producing random nouns which are not actually present in the actual input text in certain instances. Is there a way to control the degree of randomness of the output ? (something similar like temperature parameter in GPT-2 model)

**Comment by lematt1991** [comment]
Can you be more specific.  What command are you running?  What is the output that you are seeing?  Please follow the issue templates.

**Comment by aliasneo1** [comment]
@lematt1991  When I am generating summaries using CNN model, some of generated summaries had proper nouns like New York Times etc.. which are not actually present in the input text.

Is there way to control the model's output randomness (mostly in the abstractive part) like temperature parameter in GPT-2?

I am using typical prediction code as given below.


import torch
from fairseq.models.bart import BARTModel
bart = torch.hub.load('pytorch/fairseq', 'bart.large.cnn')
bart.cuda() #for enabling gpu

bsz = 18 # BatchSize
count=1
with open('/input') as source, open('/output', 'w') as fout:
    sline = source.readline().strip()
    slines = [sline]
    for sline in source:
        print()
        print(sline[0:100])
        if count % bsz == 0: 
            with torch.no_grad():
                hypotheses_batch = bart.sample(slines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)
            for hypothesis in hypotheses_batch:
                fout.write(hypothesis + '\n') # every 32th sample, write the hypothesis of the batch
                fout.flush()
            slines = [] # empty the batch, once prediction is done
        slines.append(sline.strip()) # fill the batch
        print(count)
        count += 1
    if slines != []:
        hypotheses_batch = bart.sample(slines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)
        for hypothesis in hypotheses_batch:
            fout.write(hypothesis + '\n')
            fout.flush()

**Comment by lematt1991** [comment]
You can add specify a `temperature` parameter when you call `bart.sample`.  [Here](https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/fairseq_task.py#L300-L309) is the set of parameters that will get forwarded to the sequence generator when calling `sample`.

**Comment by SarikGhazarian** [comment]
@lematt1991 in order to get multiple independently sampled outputs what is the required parameter? I provided sampling_topk >0  (or sampling_topp>0) but the build_generator function only returns one output.
