### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/train.de'

### ISSUE THREAD

**Issue by redionxhepa** [pytorch/fairseq#2039]
I am trying to preprocess the IWSLT 2014 (German-English) dataset using the code provided in the documentation,namely in https://fairseq.readthedocs.io/en/latest/getting_started.html#training-a-new-model.
So I type the following :
%cd "/content/gdrive/My Drive/Colab Notebooks/fairseq"
%cd examples/translation/
!bash prepare-iwslt14.sh
!cd ../..
!TEXT=examples/translation/iwslt14.tokenized.de-en
!fairseq-preprocess --source-lang de --target-lang en \
    --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test \
    --destdir data-bin/iwslt14.tokenized.de-en

And the error that I get is as follows: 

2020-04-21 19:11:44 | INFO | fairseq_cli.preprocess | Namespace(align_suffix=None, alignfile=None, all_gather_list_size=16384, bpe=None, checkpoint_suffix='', cpu=False, criterion='cross_entropy', dataset_impl='mmap', destdir='data-bin/iwslt14.tokenized.de-en', empty_cache_freq=0, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_format=None, log_interval=100, lr_scheduler='fixed', memory_efficient_fp16=False, min_loss_scale=0.0001, model_parallel_size=1, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=False, optimizer='nag', padding_factor=8, seed=1, source_lang='de', srcdict=None, target_lang='en', task='translation', tensorboard_logdir='', testpref='/test', tgtdict=None, threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, tokenizer=None, trainpref='/train', user_dir=None, validpref='/valid', workers=1)
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-preprocess", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-preprocess')()
  File "/content/gdrive/My Drive/Colab Notebooks/fairseq/fairseq_cli/preprocess.py", line 360, in cli_main
    main(args)
  File "/content/gdrive/My Drive/Colab Notebooks/fairseq/fairseq_cli/preprocess.py", line 95, in main
    src_dict = build_dictionary([train_path(args.source_lang)], src=True)
  File "/content/gdrive/My Drive/Colab Notebooks/fairseq/fairseq_cli/preprocess.py", line 66, in build_dictionary
    padding_factor=args.padding_factor,
  File "/content/gdrive/My Drive/Colab Notebooks/fairseq/fairseq/tasks/fairseq_task.py", line 67, in build_dictionary
    filename, d, tokenizer.tokenize_line, workers
  File "/content/gdrive/My Drive/Colab Notebooks/fairseq/fairseq/data/dictionary.py", line 347, in add_file_to_dictionary
    filename, tokenize, dict.eos_word
  File "/content/gdrive/My Drive/Colab Notebooks/fairseq/fairseq/data/dictionary.py", line 306, in _add_file_to_dictionary_single_worker
    with open(PathManager.get_local_path(filename), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/train.de'

Apparently, the /train.de data seems to be missing which I don't get it why .
I am using  fairseq locally within a Colab  Notebook file.

Bests

**Comment by lematt1991** [comment]
I think the problem is that your `TRAIN` env variable is no longer live when you run `fairseq-preprocess`, although hard to say for sure, I'm not really familiar with colab.  Try doing:

```
! TEXT=examples/translation/iwslt14.tokenized.de-en fairseq-preprocess --source-lang de --target-lang en
--trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test
--destdir data-bin/iwslt14.tokenized.de-en
```

**Comment by redionxhepa** [comment]
I tried to subsitute "Text" variable everywhere the same issue persists.The thing is that this command seems to run and after some time it encounters this issue.So it comes until this stage and then it gets the error above.Maybe there is some issue with the "iwslt14.tokenized.de-en " file,I don't know.
".........
orig/de-en/IWSLT14.TED.tst2012.de-en.en.xml iwslt14.tokenized.de-en/tmp/IWSLT14.TED.tst2012.de-en.en
Tokenizer Version 1.1
Language: en
Number of threads: 8

orig/de-en/IWSLT14.TEDX.dev2012.de-en.en.xml iwslt14.tokenized.de-en/tmp/IWSLT14.TEDX.dev2012.de-en.en
Tokenizer Version 1.1
Language: en
Number of threads: 8

creating train, valid, test...
learn_bpe.py on iwslt14.tokenized.de-en/tmp/train.en-de...
apply_bpe.py to train.de...
apply_bpe.py to valid.de...
apply_bpe.py to test.de...
apply_bpe.py to train.en...
apply_bpe.py to valid.en...
apply_bpe.py to test.en... "

**Comment by lematt1991** [comment]
I'm confused, is the problem you are having with `prepare-iwslt14.sh` or with the `fairseq-preprocess` command?  The first error you posted comes from fairseq-preprocess, but the second log you posted comes from `prepare-iwslt14.sh`.  If `prepare-iwslt14.sh` completes successfully you should have the following files:

```
iwslt14.tokenized.de-en$ ls
code  test.de  test.en  tmp  train.de  train.en  valid.de  valid.en
```

**Comment by redionxhepa** [comment]
Yeah you are right the second log comes from prepare-iwslt14.sh(I thought the command as a whole previously). The problem lies with fairseq preprocess command, unfortunately!.

**Comment by lematt1991** [comment]
Did the `prepare-iwslt14.sh` command finish without errors?  I.e. do you have all the files that I listed in my last comment, and are those files non-empty?

**Comment by redionxhepa** [comment]
Yeah sir the prepare-iwslt14.sh command finished without errors and all the files you listed are there and non-empty.So for sure the issue lies at the preprocess command.Thanks !

**Comment by lematt1991** [comment]
If the error that you are seeing is `FileNotFoundError: [Errno 2] No such file or directory: '/train.de'`, then you are not calling the command correctly.  As you can see the `TEXT` env variable is empty, it should be `examples/translation/iwslt14.tokenized.de-en/train.de`, but the `examples/translation/iwslt14.tokenized.de-en` is getting lost when you call it.  There is not an issue with `prepare-iwslt14.sh`

**Comment by redionxhepa** [comment]
If the issue would be with the TEXT env variable wouldn't be enough to just replace it everywhere where "TEXT" is written and type instead the full directory ? If yes, I tried to do that still the same issue.

**Comment by lematt1991** [comment]
So just to be clear, you are running:

```
fairseq-preprocess --source-lang de --target-lang en
--trainpref examples/translation/iwslt14.tokenized.de-en/train --validpref examples/translation/iwslt14.tokenized.de-en/valid --testpref examples/translation/iwslt14.tokenized.de-en/test
--destdir data-bin/iwslt14.tokenized.de-en
```

And you are still seeing the error `FileNotFoundError: [Errno 2] No such file or directory: '/train.de'`.

**Comment by redionxhepa** [comment]
Yeah I did that and I got the same issue.But I found out where the problem is .I changed the directory just before the preprocess command the main directory where "fairseq" is and it worked.Anyways thanks a lot.So I think  the issue is  with "!cd ../.." which is in the documentation and I don't know what it is doing.Again thanks a lot for your fast responses.Nice job !

**Comment by liku-amare** [comment]
> I think the problem is that your `TEXT` env variable is no longer live when you run `fairseq-preprocess`, although hard to say for sure, I'm not really familiar with colab. Try doing:
> 
> ```
> ! TEXT=examples/translation/iwslt14.tokenized.de-en fairseq-preprocess --source-lang de --target-lang en
> --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test
> --destdir data-bin/iwslt14.tokenized.de-en
> ```

Indeed, $TEXT env variable was no longer available when running the preprocess command. I replaced the $TEXT entries with the value of TEXT, and it worked fine. I was also running the code from the fairseq translation example.
