### ISSUE TITLE
 spm_train and spm_encode: command not found

### ISSUE THREAD

**Issue by zqs01** [pytorch/fairseq#2041]
Merge all train packs into one
Merge train text
dictionary: data/lang_char/train_100_unigram5000_units.txt
Dictionary preparation
./examples/speech_recognition/datasets/prepare-librispeech.sh: line 71: spm_train: command not found
./examples/speech_recognition/datasets/prepare-librispeech.sh: line 72: spm_encode: command not found
3 data/lang_char/train_100_unigram5000_units.txt
Prepare train and test jsons
usage: asr_prep_json.py [-h] --audio-dirs AUDIO_DIRS [AUDIO_DIRS ...] --labels
                        LABELS --spm-model SPM_MODEL --dictionary DICTIONARY
                        [--audio-format {flac,wav}] --output OUTPUT

Hello everyone, I install fairseq by source files, when I run 
 ` ./examples/speech_recognition/datasets/prepare-librispeech.sh /home/yfchen/zhu/data/librispeech/ /home/yfchen/zhu/data/process_libri`, it show above error. How can I fix this problem, thank you in anvance.

**Comment by lematt1991** [comment]
Did you install sentencepiece like the instructions say?

**Comment by zqs01** [comment]
I have solved this problem, thank you!

**Comment by zqs01** [comment]
I have solved this problem, thank you!

**Comment by sooftware** [comment]
I faced the same problem. How'd you figure it out?

**Comment by SeunghyunSEO** [comment]
> I faced the same problem. How'd you figure it out?

@sooftware 
holy moly, everywhere sooftwhere

**Comment by sooftware** [comment]
@SeunghyunSEO LoL!! I changed the code above a little and organized it here.  
https://github.com/sooftware/KoSpeech/tree/master/dataset/libri

**Comment by Cuihao1208** [comment]
replace "spm_train" to "python ${fairseq_root}/scripts/spm_train.py" and 
replace "spm_encode" to "python ${fairseq_root}/scripts/spm_encode.py"  can solve this problem.
