### ISSUE TITLE
'multilingual_denoising' task not supported

### ISSUE THREAD

**Issue by mcggood** [pytorch/fairseq#2045]
## 🐛 Bug

When I load bart large model. (multi-lang-bart in fact)
bart = BARTModel.from_pretrained('PATH', checkpoint_file='model.pt')
I got this error
KeyError: 'multilingual_denoising'

While in the model file. in args, task='multilingual_denoising'. this task seems not supported by fairseq.
### To Reproduce

bart = BARTModel.from_pretrained('PATH', checkpoint_file='model.pt')

**Comment by lematt1991** [comment]
What command did you use to train `model.pt`?  Also, please provide the full trace of the error you are seeing.

**Comment by mcggood** [comment]
I don't use command. I don't train. I just want to load multi language mbart pretrained model.
bart = BARTModel.from_pretrained('PATH', checkpoint_file='model.pt')
the "PATH" is the files containing dict.txt, model.pt, sentence.bpe.model
