### ISSUE TITLE
TokenBlockDataset weird left padding with eos

### ISSUE THREAD

**Issue by agadetsky** [pytorch/fairseq#2047]
## 🐛 Bug

In `__getitem__` of `TokenBlockDataset`' if `self.targets` are `True` and `s=0` (beginning of sequence) then method always left pads `source` with `eos` token and this is weird.

### Expected behavior

Expected padding is with `bos` token.

**Comment by lematt1991** [comment]
Do you have a reproducible code example?

**Comment by agadetsky** [comment]
@lematt1991 

Download data (it is just sentences line by line) and unzip in `fairseq/examples/language_model/starwars`
[starwars.zip](https://github.com/pytorch/fairseq/files/4523081/starwars.zip)

From root fairseq directory prepare data with:
```
TEXT=examples/language_model/starwars
fairseq-preprocess \
    --only-source \
    --trainpref $TEXT/starwars.train.tokens \
    --validpref $TEXT/starwars.valid.tokens \
    --testpref $TEXT/starwars.test.tokens \
    --destdir data-bin/starwars \
    --workers 20
```

Change `fairseq/tasks/fairseq_task.py` with 
[fairseq_task.py.zip](https://github.com/pytorch/fairseq/files/4523111/fairseq_task.py.zip) (I just added printing samples to `train_step`)

Run language modeling task with:
```
fairseq-train data-bin/starwars/ \
    --task language_modeling \
    --arch lstm_lm \
    --max-sentences 4 \
    --sample-break-mode eos
```

And you will get:
```
SRC
</s> Fear leads to anger . <pad> <pad> <pad> <pad>
</s> Luke I am your father . <pad> <pad> <pad>
</s> Always pass on what you have learned . <pad>
</s> Fear is the path to the dark side .
TGT
Fear leads to anger . </s> <pad> <pad> <pad> <pad>
Luke I am your father . </s> <pad> <pad> <pad>
Always pass on what you have learned . </s> <pad>
Fear is the path to the dark side . </s>
```

`TGT` sequences are ok, but `SRC` are left padded with `eos` token which is weird (I expected padding with `bos` token).

**Comment by myleott** [comment]
For language modeling, you want to predict the next word conditioned on the previous word. But when predicting the very first word, there’s no input token to condition on, so we just pretend an eos to the source.

**Comment by agadetsky** [comment]
@myleott yes, I understand all the pipeline for language modeling, but for me adding eos in the beginning of the sequence is counter intuitive and wrong, better to add bos token.

**Comment by myleott** [comment]
Ah this is somewhat legacy behavior to use eos everywhere. Originally we only had eos, but later added bos, so it’s not used everywhere yet.
