### ISSUE TITLE
Using roberta for fake news detection

### ISSUE THREAD

**Issue by aeh1307** [pytorch/fairseq#2054]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by aeh1307** [comment]
Hi, we want to use roberta for fake news detection. Is it possible to use roberta for prediction only, and not having to train the model ourselves? If that is the case, which pretrained model do you recommend for classifying whether a text is fake news or not?

**Comment by lematt1991** [comment]
> Is it possible to use roberta for prediction only, and not having to train the model ourselves?

I'm not sure, but I would be surprised if the model works for your task out of the box.  Usually some kind of finetuning is required.
