### ISSUE TITLE
different language speech can transfer learning in wav2vec or vq-wav2vec?

### ISSUE THREAD

**Issue by luweishuang** [pytorch/fairseq#2069]
I want to train a wav2vec or  vq-wav2vec in chinese speech, and only english pretrained models are supported.  I want to know can I directly finetuning the english pretrained wav2vec model or vq-wav2vec model in chinese speech or I need to train from scratch using chiniese speech

**Comment by lematt1991** [comment]
I would recommend training from scratch using Chinese speech

**Comment by luweishuang** [comment]
@lematt1991 I think wav2vec just like mfcc or fbank and it should be multi-language, so I uesd the provided wav2vec_large model directly to my chinese speechs and use am model in wav2letter to train the am modle. the result seems to not bad, at least better than myself trained chinese-wav2vec model.

**Comment by yardenkarny** [comment]
Hi,

I read about your work of using a pre-trained model and fine-tune it to other low resource languages.
Is there any news of multilingual pre-trained wav2vec models that can be downloaded or will be in the near future?
thanks,

Yarden
