### ISSUE TITLE
Absolute path in pre-trained story generation model?

### ISSUE THREAD

**Issue by amrsharaf** [pytorch/fairseq#207]
I'm trying to generate some sample stories using the pre-trained story generation model that has been uploaded to the repo few hours ago (CC: @huihuifan) . It seems like the model has a hard-coded absolute path that's causing a problem in generation: 

> python generate.py data-bin/writingPrompts --path pretrained_models/stories/checkpoint.pt --batch-size 32 --beam 1 --sampling --sampling-topk 10 --sampling-temperature 0.8 -
-nbest 1
Namespace(beam=1, cpu=False, data='data-bin/writingPrompts', gen_subset='test', left_pad_source='True', left_pad_target='False', lenpen=1, log_format=None, log_interval=1000
, max_len_a=0, max_len_b=200, max_sentences=32, max_source_positions=1024, max_target_positions=1024, max_tokens=None, min_len=1, nbest=1, no_beamable_mm=False, no_early_sto
p=False, no_progress_bar=False, num_shards=1, path='pretrained_models/stories/checkpoint.pt', prefix_size=0, quiet=False, raw_text=False, remove_bpe=None, replace_unk=None,
sampling=True, sampling_temperature=0.8, sampling_topk=10, score_reference=False, seed=1, shard_id=0, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lan
g=None, task='translation', unkpen=0, unnormalized=False)
| [wp_source] dictionary: 19025 types
| [wp_target] dictionary: 112832 types
| data-bin/writingPrompts test 15138 examples
| loading model(s) from pretrained_models/stories/checkpoint.pt
| Loading pretrained model
Traceback (most recent call last):
  File "generate.py", line 157, in <module>
    main(args)
  File "generate.py", line 41, in main
    models, _ = utils.load_ensemble_for_inference(args.path.split(':'), task)
  File "/home/t-amshar/fairseq/fairseq/utils.py", line 156, in load_ensemble_for_inference
    model = task.build_model(args)
  File "/home/t-amshar/fairseq/fairseq/tasks/fairseq_task.py", line 43, in build_model
    return models.build_model(args, self)
  File "/home/t-amshar/fairseq/fairseq/models/__init__.py", line 25, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
  File "/home/t-amshar/fairseq/fairseq/models/fconv_self_att.py", line 88, in build_model
    task=task,
  File "/home/t-amshar/fairseq/fairseq/utils.py", line 145, in load_ensemble_for_inference
    raise IOError('Model file not found: {}'.format(filename))
OSError: Model file not found: /checkpoint/angelafan/wp_open_source/checkpoint_best.pt
Makefile:121: recipe for target 'generate' failed
make: *** [generate] Error 1

Any idea how to fix this?

**Comment by amrsharaf** [comment]
I looked more into this, the problem is that the following pre-trained model is missing: 

> /checkpoint/angelafan/wp_open_source/checkpoint_best.pt

@huihuifan could you please upload this model? I think I can just override the `pretrained_checkpoint ` command line flag with the new path for the pre-trained model.

**Comment by huihuifan** [comment]
I thought the pretrained model was in the bzip file with the fusion model. I've added it now, and a way to specify the path for the pretrained model at decoding time in the latest commit by adding a model-overrides argument for generate.py (see stories readme, but the issue is the fusion model saves the pretrained checkpoint path in its state dict, which is automatically loaded at generation time, so the pretrained checkpoint path is hardcoded to what it was at training time for the fusion model).

**Comment by bepierre** [comment]
Now I get this error with the new bzip file:

```
RuntimeError: Error(s) in loading state_dict for FConvModelSelfAtt:
	While copying the parameter named "decoder.embed_tokens.weight", whose dimensions in the model are torch.Size([112832, 256]) and whose dimensions in the checkpoint are torch.Size([104960, 256]).
	While copying the parameter named "decoder.fc3.weight", whose dimensions in the model are torch.Size([112832, 256]) and whose dimensions in the checkpoint are torch.Size([104960, 256]).
	While copying the parameter named "decoder.fc3.bias", whose dimensions in the model are torch.Size([112832]) and whose dimensions in the checkpoint are torch.Size([104960]).
```
