### ISSUE TITLE
Has anyone tried this quantization method on Regression model?

### ISSUE THREAD

**Issue by JiachuanDENG** [pytorch/fairseq#2071]
Has anyone tried this quantization method on regression model? I can only find experiments are done on classification problems in the paper. I'm wondering if the quantization method can also be used in regression problems without much performance decrease.

**Comment by myleott** [comment]
@huihuifan have you tried regression tasks or have an intuition about if they’d work similarly to classification tasks?

**Comment by huihuifan** [comment]
Thanks for the question! We did not try regression tasks, but I would expect the quantization method to work. int8 quantization in particular has been used in various regression tasks, and our method is a straightforward modification to simulate this at training time so the model is more robust to the effect of quantization at testing

**Comment by JiachuanDENG** [comment]
> Thanks for the question! We did not try regression tasks, but I would expect the quantization method to work. int8 quantization in particular has been used in various regression tasks, and our method is a straightforward modification to simulate this at training time so the model is more robust to the effect of quantization at testing

@huihuifan  Thanks for your reply, it's interesting that most of the papers talking about quantization methods are focusing on classification tasks rather than regression tasks. Do you have any paper lists about quantization methods that they have done experiments on regression tasks? That would be a great help!

**Comment by huihuifan** [comment]
@pierrestock would you have some references?

**Comment by rameshkunasi** [comment]
If any example code available please share
