### ISSUE TITLE
Reproducing the provided distillation data set.

### ISSUE THREAD

**Issue by forestnoobie** [pytorch/fairseq#2072]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
Hello, I have some question about reproducing the distillation data provided in [here](https://github.com/pytorch/fairseq/blob/master/examples/nonautoregressive_translation/README.md#download)
I am trying to reproduce the distillation data and reproduce the (Zhou et al., 2019) paper so I can test other things. In the paper the data was distilled using base transformer which has 65M parameters. 

1. Could you tell me which base transformer model is used for making the provided distillation data? I have tried the transformer_wmt_en_de architecture but the number of parameter was quite different with the paper (86M and 65M). 
2. If it is possible, may I ask for the fairseq-generate code to reproduce the distillation set? I have looked several issues before but I could get the clue to make my own dataset.

Thank You, for making such great package.
#### Code

```
bash prepare-wmt14en2de.sh --icml17  /

cd ../..

TEXT=examples/translation/wmt14_en_de

fairseq-preprocess \
    --source-lang en --target-lang de \
    --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test \
    --destdir data-bin/wmt14_en_de --thresholdtgt 0 --thresholdsrc 0 \
    --workers 20

fairseq-train \
    data-bin/wmt14_en_de \
    --arch transformer_wmt_en_de --share-decoder-input-output-embed \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
    --dropout 0.3 --weight-decay 0.0001 --save-dir 'transformer_checkpoints'\
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 \
    --eval-bleu \
    --eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}' \
    --eval-bleu-detok moses \
    --eval-bleu-remove-bpe \
    --eval-bleu-print-samples \
    --best-checkpoint-metric bleu --maximize-best-checkpoint-metric

```

#### What have you tried?

I have tried the transformer_wmt_en_de architecture.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.4.0) : 1.4.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): Source
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: V100
 - Any other relevant information:

**Comment by Ir1d** [comment]
neither can I generate a distillation set that works, my student model always get validation ppl larger than 1e4

**Comment by myleott** [comment]
@MultiPath
