### ISSUE TITLE
Early stopping (patience) isn't only based on epochs

### ISSUE THREAD

**Issue by DarrenCook** [pytorch/fairseq#2080]
## 🐛 Bug

Maybe not a bug; I could just be misunderstanding the code.

I was looking at `should_stop_early(args, valid_loss)` in https://github.com/pytorch/fairseq/blob/master/fairseq_cli/train.py
It works by incrementing `should_stop_early.num_runs` if valid_loss has not improved since the last time `should_stop_early()` was called.

If `--validate-interval` is higher than 1, it might take more than `patience` epochs before that happens. The documentation on the `patience` arg points this out.

`should_stop_early()` is called after `train()` in the epoch loop in `main()` (in train.py). BUT, it is also called from inside `train()`, within this loop:

```
for samples in progress:
    ...
    valid_losses = validate_and_save(args, trainer, task, epoch_itr, valid_subsets)
    if should_stop_early(args, valid_losses[0]) or num_updates >= max_update:
        break
```

Does this mean that it could increment `should_stop_early.num_runs` multiple times during a single epoch? And, if so, is this by design or is it undesirable?

References: https://github.com/pytorch/fairseq/pull/904 (the code has changed since that original implementation) and https://github.com/pytorch/fairseq/issues/1580#issuecomment-571160463

**Comment by myleott** [comment]
Good call. We intend to do it based on number of validation runs, rather than epochs. I’ll update the docs for the patience arg.
