### ISSUE TITLE
Example for --user-dir

### ISSUE THREAD

**Issue by AlanHassen** [pytorch/fairseq#2081]
Can anyone provide a working --user-dir example? If I follow the documentation (https://fairseq.readthedocs.io/en/latest/overview.html?highlight=user-dir#overview), I only get a _ValueError: Cannot register duplicate model architecture (seq2seqCustom)_.

The model file:
```
@register_model('seq2seq')
class seq2seq(FairseqEncoderDecoderModel):
```

The __init__.py:
```
from fairseq.models import register_model_architecture
from fsrc.models.fairseq.architectures import seq2seq

@register_model_architecture('seq2seq', 'seq2seqCustom')
def seq2seqCustom(args):
    seq2seq(args)
```

Am I missing something here?

**Comment by myleott** [comment]
Here's an example: https://github.com/pytorch/fairseq/tree/master/examples/translation_moe. The commands there point to `--user-dir examples/translation_moe/src`.

If you're still having trouble, can you share more details about your directory structure?

**Comment by AlanHassen** [comment]
Thanks for the fast reply 👍 
Is there a problem, if I install fairseq in editable mode with the user-directory?

I followed the example but fairseq is not able to resolve the model (I tried the absolut path as well...):

```
--user-dir src/models/fairseq/custom_models 
--arch seq2seq
```

src/models/fairseq/custom_models/init.py:
`from . import *  # noqa`

src/models/fairseq/custom_models/seq2seq.py:
```
@register_model('seq2seq')
class seq2seq(FairseqEncoderDecoderModel):
```

**Comment by myleott** [comment]
> Is there a problem, if I install fairseq in editable mode with the user-directory?

I'm not sure what you mean? It's fine to do `pip install --editable .` in the fairseq directory. But your user directory should be located elsewhere (i.e., outside of the fairseq repo).

**Comment by AlanHassen** [comment]
Ah, I found my mistake. I assumed that its enough to just register the model for a basic setup and register_model_architecture is just needed when additional architectures with the same model are wanted.

Thanks for the help!

**Comment by ffanccybear** [comment]
So, how did you fix it?

**Comment by EricLina** [comment]
+1,how did you fix it ? Use the absolute path?
