### ISSUE TITLE
Using denoising_dataset script for mBart datasets

### ISSUE THREAD

**Issue by shola-lawal** [pytorch/fairseq#2082]
Hi,

I am hoping to use the denoising_dataset python script found [here](https://github.com/pytorch/fairseq/blob/6563407fcb84be52a5cf0e2e64f9230b97271e59/fairseq/data/denoising_dataset.py) to implement the noising function described in [Multilingual Denoising Pre-training for Neural Machine Translation](https://arxiv.org/abs/2001.08210) 

My qestions are:
1. What good or default settings should be used for all the parameters in the script as described in the paper above?
2. How could I use my own dataset instead of the FairseqDataset?
3. In lines 136 to 150, the Poisson distribution, could you kindly explain why the 128 was included in the range?

Thanks in advance to your response.

**Comment by myleott** [comment]
cc @ngoyal2707 @yinhanliu

**Comment by Qnlp** [comment]
@shola-lawal Do you have find dataset which mentioned in XLM-R/ MBART ? for example , CC-25 and CC-NEWS.
