### ISSUE TITLE
Japense-English translation, pre-trained models?

### ISSUE THREAD

**Issue by cabhijith** [pytorch/fairseq#2086]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
Hi, 
I was interested in Japanese-english translation. Are there any pre-trained models for the same in fairseq? The only one I think I can use is ```mbart.CC25```, but does that have to be fine-tuned or can I use it directly?

**Comment by Ahmad-noborders** [comment]
hi @cabhijith  [here](http://www.kecl.ntt.co.jp/icl/lirg/jparacrawl/
) is pretrained model of Japanese -English and English -Japanese trained on fairseq. they also have docker image. but i am trying to run it using python . 


hope it helps

**Comment by cabhijith** [comment]
Thank You @Ahmad-noborders . Yup, I'll try to port it to Python too.

**Comment by cabhijith** [comment]
If possible, please do share the Python port.

**Comment by cabhijith** [comment]
@Ahmad-noborders If possible, please do share the python code for the same. Thanks!

**Comment by Ahmad-noborders** [comment]
simply use `from fairseq.models.transformer import TransformerModel
zh2en = TransformerModel.from_pretrained(
  '/path/to/checkpoints',
  checkpoint_file='checkpoint_best.pt',
  data_name_or_path='data-bin/wmt17_zh_en_full',
  bpe='subword_nmt',
  bpe_codes='data-bin/wmt17_zh_en_full/zh.code'
)
zh2en.translate('你好 世界')
# 'Hello World'`
this and replace path and model file name accordingly. make your own BPE file

**Comment by cabhijith** [comment]
Thanks!

**Comment by SAC04** [comment]
hi, I'am new to python. can anyone explain what would in place of "path/to/checkpoint".

**Comment by lsisoft** [comment]
For people that wonder where the code that @Ahmad-noborders wrote, I found parts of it here:
https://huggingface.co/spaces/sriramelango/Social_Classification_Public/blob/main/fairseq/examples/translation/README.md
