### ISSUE TITLE
Overflow detected, (34, 'Numerical result out of range') and KeyError: 'train_wall' 

### ISSUE THREAD

**Issue by Nagoudi** [pytorch/fairseq#2089]
## ❓ Questions and Help

Hello, 

I'm trying to train MT model with Fairseq using fconv architecture  (see my cmd below) with 4 GPU. 

` fairseq-train data-bin/Data_Input.tokenized.ar-es  --source-lang ar   --target-lang es --lr 0.25 --clip-norm 0.1 --dropout 0.2 --max-tokens 4000 --arch fconv --save-dir checkpoints/fconv-ar-es.sub
 `

However, I got the following error: 

```
| model fconv, criterion CrossEntropyCriterion
| num. model params: 106628512 (num. trained: 106628512)
| training on 4 GPUs
| max tokens per GPU = 4000 and max sentences per GPU = None
| no existing checkpoint found checkpoints/Bench-fconv-es-ar.sub/checkpoint_last.pt
| loading train data for epoch 0
| loaded 19183829 examples from: data-bin/data_ar-es.tokenized.ar-es/train.ar-es.es
| loaded 19183829 examples from: data-bin/data_ar-es.tokenized.ar-es/train.ar-es.ar
| data-bin/data_ar-es.tokenized.ar-es train es-ar 19183829 examples
| NOTICE: your device may support faster training with --fp16
| epoch 001:    999 / 23251 loss=10.301, ppl=1261.84, wps=46216, ups=3.42, wpb=13527.4, bsz=830, num_updates=1000, lr=0.25, gnorm=7.54, clip=100, oom=0, train_wall=296, wall=565
| WARNING: overflow detected, (34, 'Numerical result out of range')
Traceback (most recent call last):
  File "/home/negda23/ENV/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/scratch/negda23/fairseq/fairseq_cli/train.py", line 288, in cli_main
    nprocs=args.distributed_world_size,
  File "/home/negda23/ENV/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/negda23/ENV/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/negda23/ENV/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/scratch/negda23/fairseq/fairseq_cli/train.py", line 255, in distributed_main
    main(args, init_distributed=True)
  File "/scratch/negda23/fairseq/fairseq_cli/train.py", line 90, in main
    train(args, trainer, task, epoch_itr)
  File "/scratch/negda23/fairseq/fairseq_cli/train.py", line 154, in train
    log_output = trainer.train_step(samples)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.7.4/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/scratch/negda23/fairseq/fairseq/trainer.py", line 414, in train_step
    metrics.log_stop_time("train_wall")
  File "/scratch/negda23/fairseq/fairseq/metrics.py", line 173, in log_stop_time
    agg[key].stop(weight)
KeyError: 'train_wall'

```

Any suggestions are welcome!!
Thanks

**Comment by myleott** [comment]
Hmm, the real exception seems to be the `Numerical result out of range` issue. That indicates some kind of numerical underflow, but it's really not clear where that's happening or why. Unfortunately we've reused OverflowError for FP16 training, so the stack trace is caught and lost :/ Can you try commenting out [this block](https://github.com/pytorch/fairseq/blob/89d18af12792442f8ce5df86027aaa3f908240ec/fairseq/trainer.py#L446-L450), rerunning, and posting the real stack trace?

Re: the KeyError, what version of fairseq are you using? This error happened in some corner cases, but should have been fixed in master in mid-February.

**Comment by Nagoudi** [comment]
Hi @myleott ,

Thanks for your reply, 
I'll try your recommendation and keep you posted.

**Comment by Nagoudi** [comment]
Hi @myleott again, 

**Note** I used the last version of Fairseq
I commented the [block](https://github.com/pytorch/fairseq/blob/89d18af12792442f8ce5df86027aaa3f908240ec/fairseq/trainer.py#L446-L450), 
Run agin the cmd, I got the same error:
`Num of GPU : 4
| distributed init (rank 0): tcp://localhost:15391
| distributed init (rank 1): tcp://localhost:15391
| initialized host cdr2597.int.cedar.computecanada.ca as rank 1
| distributed init (rank 3): tcp://localhost:15391
| initialized host cdr2597.int.cedar.computecanada.ca as rank 3
| distributed init (rank 2): tcp://localhost:15391
| initialized host cdr2597.int.cedar.computecanada.ca as rank 2
| initialized host cdr2597.int.cedar.computecanada.ca as rank 0
Namespace(all_gather_list_size=16384, arch='fconv', best_checkpoint_metric='loss', bpe=None, bucket_cap_mb=25, clip_norm=0.1, cpu=False, criterion='cross_entropy', curriculum=0, data='data-bin/data_ar-es.tokenized.ar-es', dataset_impl=None, ddp_backend='c10d', decoder_attention='True', decoder_embed_dim=512, decoder_embed_path=None, decoder_layers='[(512, 3)] * 20', decoder_out_embed_dim=256, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method='tcp://localhost:15391', distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=4, dropout=0.2, empty_cache_freq=0, encoder_embed_dim=512, encoder_embed_path=None, encoder_layers='[(512, 3)] * 20', fast_stat_sync=False, find_unused_parameters=False, fix_batches_to_gpus=False, fixed_validation_seed=None, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, keep_interval_updates=-1, keep_last_epochs=-1, left_pad_source='True', left_pad_target='False', load_alignments=False, log_format=None, log_interval=1000, lr=[0.25], lr_scheduler='fixed', lr_shrink=0.1, max_epoch=0, max_sentences=None, max_sentences_valid=None, max_source_positions=1024, max_target_positions=1024, max_tokens=1000, max_tokens_valid=1000, max_update=0, maximize_best_checkpoint_metric=False, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=-1, momentum=0.99, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_save=False, no_save_optimizer_state=False, num_workers=1, optimizer='nag', optimizer_overrides='{}', patience=-1, required_batch_size_multiple=8, reset_dataloader=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', save_dir='checkpoints/Bench-fconv-es-ar.sub', save_interval=1, save_interval_updates=0, seed=1, sentence_avg=False, share_input_output_embed=False, skip_invalid_size_inputs_valid_test=False, source_lang='es', target_lang='ar', task='translation', tensorboard_logdir='', threshold_loss_scale=None, tokenizer=None, train_subset='train', truncate_source=False, update_freq=[1], upsample_primary=1, use_bmuf=False, user_dir=None, valid_subset='valid', validate_interval=1, warmup_updates=0, weight_decay=0.0)
| [es] dictionary: 16224 types
| [ar] dictionary: 29648 types
| loaded 2397979 examples from: data-bin/data_ar-es.tokenized.ar-es/valid.ar-es.es
| loaded 2397979 examples from: data-bin/data_ar-es.tokenized.ar-es/valid.ar-es.ar
| data-bin/data_ar-es.tokenized.ar-es valid es-ar 2397979 examples
FConvModel(
  (encoder): FConvEncoder(
    (embed_tokens): Embedding(16224, 512, padding_idx=1)
    (embed_positions): LearnedPositionalEmbedding(1024, 512, padding_idx=1)
    (fc1): Linear(in_features=512, out_features=512, bias=True)
    (projections): ModuleList(
      (0): None
      (1): None
      (2): None
      (3): None
      (4): None
      (5): None
      (6): None
      (7): None
      (8): None
      (9): None
      (10): None
      (11): None
      (12): None
      (13): None
      (14): None
      (15): None
      (16): None
      (17): None
      (18): None
      (19): None
    )
    (convolutions): ModuleList(
      (0): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (1): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (2): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (3): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (4): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (5): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (6): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (7): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (8): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (9): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (10): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (11): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (12): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (13): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (14): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (15): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (16): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (17): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (18): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
      (19): ConvTBC(512, 1024, kernel_size=(3,), padding=(1,))
    )
    (fc2): Linear(in_features=512, out_features=512, bias=True)
  )
  (decoder): FConvDecoder(
    (embed_tokens): Embedding(29648, 512, padding_idx=1)
    (embed_positions): LearnedPositionalEmbedding(1024, 512, padding_idx=1)
    (fc1): Linear(in_features=512, out_features=512, bias=True)
    (projections): ModuleList(
      (0): None
      (1): None
      (2): None
      (3): None
      (4): None
      (5): None
      (6): None
      (7): None
      (8): None
      (9): None
      (10): None
      (11): None
      (12): None
      (13): None
      (14): None
      (15): None
      (16): None
      (17): None
      (18): None
      (19): None
    )
    (convolutions): ModuleList(
      (0): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (1): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (2): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (3): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (4): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (5): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (6): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (7): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (8): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (9): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (10): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (11): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (12): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (13): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (14): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (15): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (16): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (17): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (18): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
      (19): LinearizedConvolution(512, 1024, kernel_size=(3,), padding=(2,))
    )
    (attention): ModuleList(
      (0): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (1): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (2): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (3): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (4): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (5): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (6): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (7): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (8): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (9): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (10): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (11): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (12): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (13): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (14): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (15): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (16): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (17): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (18): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (19): AttentionLayer(
        (in_projection): Linear(in_features=512, out_features=512, bias=True)
        (out_projection): Linear(in_features=512, out_features=512, bias=True)
      )
    )
    (fc2): Linear(in_features=512, out_features=256, bias=True)
    (fc3): Linear(in_features=256, out_features=29648, bias=True)
  )
)
| model fconv, criterion CrossEntropyCriterion
| num. model params: 106628512 (num. trained: 106628512)
| training on 4 GPUs
| max tokens per GPU = 1000 and max sentences per GPU = None
| no existing checkpoint found checkpoints/Bench-fconv-es-ar.sub/checkpoint_last.pt
| loading train data for epoch 0
| loaded 19183829 examples from: data-bin/data_ar-es.tokenized.ar-es/train.ar-es.es
| loaded 19183829 examples from: data-bin/data_ar-es.tokenized.ar-es/train.ar-es.ar
| data-bin/data_ar-es.tokenized.ar-es train es-ar 19183829 examples
| NOTICE: your device may support faster training with --fp16
| epoch 001:    999 / 106048 loss=10.439, ppl=1387.88, wps=14132.1, ups=4.74, wpb=2983.6, bsz=185.2, num_updates=1000, lr=0.25, gnorm=4.515, clip=100, oom=0, train_wall=246, wall=506
| epoch 001:   1999 / 106048 loss=9.875, ppl=938.761, wps=13502.1, ups=4.54, wpb=2972.7, bsz=181.3, num_updates=2000, lr=0.25, gnorm=44.985, clip=100, oom=0, train_wall=465, wall=735
| WARNING: overflow detected, (34, 'Numerical result out of range')
Traceback (most recent call last):
  File "/home/negda23/ENV/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/scratch/negda23/fairseq/fairseq_cli/train.py", line 288, in cli_main
    nprocs=args.distributed_world_size,
  File "/home/negda23/ENV/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/negda23/ENV/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/negda23/ENV/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/scratch/negda23/fairseq/fairseq_cli/train.py", line 255, in distributed_main
    main(args, init_distributed=True)
  File "/scratch/negda23/fairseq/fairseq_cli/train.py", line 90, in main
    train(args, trainer, task, epoch_itr)
  File "/scratch/negda23/fairseq/fairseq_cli/train.py", line 154, in train
    log_output = trainer.train_step(samples)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.7.4/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/scratch/negda23/fairseq/fairseq/trainer.py", line 414, in train_step
    metrics.log_stop_time("train_wall")
  File "/scratch/negda23/fairseq/fairseq/metrics.py", line 173, in log_stop_time
    agg[key].stop(weight)
KeyError: 'train_wall'
`

**Comment by myleott** [comment]
Are you sure you're on the latest version? In your stack trace I see `metrics.log_stop_time("train_wall")` at line 414 in trainer.py, but this is on line 487 on master: https://github.com/pytorch/fairseq/blob/6209d7d6b2c41fccb01e00671261be80ba86029a/fairseq/trainer.py#L487

**Comment by Nagoudi** [comment]
Hi @myleott 

Ok, I'll double-check the version and keep you posted.

Thanks!!
