### ISSUE TITLE
When using the pre-trained Model for story generation.

### ISSUE THREAD

**Issue by bepierre** [pytorch/fairseq#209]
When running `interactive.py` for example it loads the model an then tries to load the pretrained model (because of the fusion training) which exits with error:

`OSError: Model file not found: /checkpoint/angelafan/wp_open_source/checkpoint_best.pt`

Is there anyway to fix this? Or maybe also make the pretrained model available?

**Comment by bepierre** [comment]
Same issue than #207. So I'll go ahead and close this one

**Comment by huihuifan** [comment]
addressed in #207. Thanks for raising the issue.

**Comment by bepierre** [comment]
Now I get following error with new bzip file:

```
RuntimeError: Error(s) in loading state_dict for FConvModelSelfAtt:
	While copying the parameter named "decoder.embed_tokens.weight", whose dimensions in the model are torch.Size([112832, 256]) and whose dimensions in the checkpoint are torch.Size([104960, 256]).
	While copying the parameter named "decoder.fc3.weight", whose dimensions in the model are torch.Size([112832, 256]) and whose dimensions in the checkpoint are torch.Size([104960, 256]).
	While copying the parameter named "decoder.fc3.bias", whose dimensions in the model are torch.Size([112832]) and whose dimensions in the checkpoint are torch.Size([104960]).

```

**Comment by huihuifan** [comment]
cannot repro

```
cd fairseq-py
git pull 
wget https://s3.amazonaws.com/fairseq-py/models/stories_checkpoint.tar.bz2
tar xvjf stories_checkpoint.tar.bz2
# unpacks it into models folder
python generate.py data-bin/writingPrompts --target-lang wp_target --source-lang wp_source --path models/fusion_checkpoint.pt --batch-size 32 --beam 1 --sampling --sampling-topk 10 --sampling-temperature 0.8 --nbest 1 --model-overrides "{'pretrained_checkpoint':'models/pretrained_checkpoint.pt'}"
```

please make sure you're providing the path to the right models and you've binarized the dataset with the same number of tokens as my pretrained model vocabulary. If you load your own checkpoint, your vocabulary may not be the same.

**Comment by bepierre** [comment]
Ok, it probably has to do with the data binarization then. Thanks!

**Comment by bckim92** [comment]
@bepierre Hello, I got the same RunTimeError as yours. How did you solve it?

**Comment by huihuifan** [comment]
https://github.com/pytorch/fairseq/issues/216  may help if your vocabulary is off.
