### ISSUE TITLE
sequence_scorer.py additional documentation information (using with Bart)

### ISSUE THREAD

**Issue by seraphinatarrant** [pytorch/fairseq#2091]
As far as I understand from a quick code read and from #1768, if I want to get the scores of a sequence or set of sequences, _without_ generating, I should use the SequenceScorer class. 

However, [line 56](https://github.com/pytorch/fairseq/blob/b31849aa9282755bbb9eecd9384b2e0fc2b9c0a1/fairseq/sequence_scorer.py#L56) calls `model.forward` with an unpacked dictionary of `net_inputs`, which in the case of bart expects 3 required args, `src_tokens`, `src_lengths`, and `prev_output_tokens`. 

This is confusing to me though, since the sequence_scorer also uses `target`. Which based on the docstring, I'd presume would be the sequence to be scored. 
But if so `prev_output_tokens` seems not relevant, but I cannot decode without some value for that.

And `target` actually never goes through the forward, which has made me think that `prev_output_tokens` is maybe supposed to be the set of generated hypotheses...in which case what is target?

Other than the dosctring there are very few comments, so it's hard for me to even tell what the shape of these variables is supposed to be.

Other details:
I'm building a SequenceScorer by calling `_build_generator` with `score_reference = True`.
If there's another way that's more straightforward to score a sequence though, let me know! I basically just want language model scores for a batch of sequences.

Thanks very much!

**Comment by seraphinatarrant** [comment]
@myleott you seem to answer a bunch of these - can you clarify what 'target' vs. 'prev_output_tokens' ought to be?

**Comment by myleott** [comment]
prev_output_tokens is a shifted version of target, which is used for teacher forcing. We don't directly give the target to the model, but do include it in the sample so that the criterion can use it to compute the loss.

There's a discussion about other subtleties for BART here: https://github.com/pytorch/fairseq/issues/1389
