### ISSUE TITLE
roberta finetuning example minor bug 

### ISSUE THREAD

**Issue by kubapok** [pytorch/fairseq#2101]
## 📚 Documentation
Hi,

I think here:

https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.custom_classification.md

should be:

`pred = label_fn(roberta.predict('imdb_head', tokens).argmax()`

instead of 

`pred = label_fn(roberta.predict('imdb_head', tokens).argmax().item())`

at the bottom two lines.

**Comment by myleott** [comment]
I believe `.argmax()` returns a tensor, so calling `.item()` should be fine... do you get an error?

**Comment by kubapok** [comment]
@myleott  
What you write is true. But `label_fn` requires tensor, because `roberta.task.label_dictionary.string` requires tensor. 

I got error. when I change the line as described, it worked.

**Comment by myleott** [comment]
Ah, you're right, this was due to a recent change in `Dictionary.string`, I'll submit a fix

**Comment by myleott** [comment]
Fixed in 9a718e29855713a51877237b2dcc25e39c234c82
