### ISSUE TITLE
About Noisy channel reranking, empty file error

### ISSUE THREAD

**Issue by ElliottYan** [pytorch/fairseq#2108]
## 🐛 Bug

Hi, I'm trying to reproduce the result of noisy channel reranking using my mac (without cuda environment). But some empty file error happens.

I follow the exact instructions stated here. https://github.com/pytorch/fairseq/tree/be86e7ebefb21f694b190487b789f4e61132fc13/examples/noisychannel

The following error happens.
![image](https://user-images.githubusercontent.com/10862038/81393556-25c1ea80-9153-11ea-8f3b-64a2d99b2c1c.png)

I have no idea what's going on. Could somebody help me here? Thx

### Environment

 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version (e.g., 1.0) 1.5.0
 - OS (e.g., Linux): MacOSX
 - How you installed fairseq (`pip`, source): sourcec
 - Build command you used (if compiling from source): pip install --editable .
 - Python version: 3.7
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by Bachstelze** [comment]
Could you reproduce the results?
