### ISSUE TITLE
How to preprocess for multilingual denoising (mBART) or MLM (XLM)

### ISSUE THREAD

**Issue by cbaziotis** [pytorch/fairseq#2110]
I want to train mBART from scratch on my own monolingual data from various languages. All I could find is the [example](https://github.com/pytorch/fairseq/blob/master/examples/mbart/README.md) of how to fine-tune mBART on a given language-pair.

Can you please provide an example of how to preprocess and train mBART from scratch?

**Update**
Here is what I have done so far:
1) **Tokenization**. First I train a sentencepiece model on the concatenation of all the monolingual data, and I tokenize each split with it. I also convert the spm `.vocab` file to a fairseq `dict.txt` based on [this](https://github.com/pytorch/fairseq/issues/459#issuecomment-458593467) comment.
```
# train SPM
spm_train --input=train.en,train.de --character_coverage=1 --model_prefix=mbart.ende --model_type=unigram --vocab_size=$vocab

# Encode EN data
spm_encode --model=mbart.ende.model --output_format=piece <train.en >train.spm.en
spm_encode --model=mbart.ende.model --output_format=piece <dev.en   >dev.spm.en
spm_encode --model=mbart.ende.model --output_format=piece <test.en  >test.spm.en

# Encode DE data
spm_encode --model=mbart.ende.model --output_format=piece <train.de >train.spm.de
spm_encode --model=mbart.ende.model --output_format=piece <dev.de   >dev.spm.de
spm_encode --model=mbart.ende.model --output_format=piece <test.de  >test.spm.de

# Convert sentencepiece vocab to fairseq format
cut -f1 mbart.ende.vocab | tail -n +4 | sed "s/$/ 100/g" > mbart.ende.dict.txt
```

2) **Preprocessing**. then preprocess each dataset _separately_ similar to how we do for language modelling using the common dict.txt. I am not sure about this step.
```
SRC_PATH=path_to_en_de_monolingual_data
DEST_PATH=path_with_binarized_mbart_data
DICT_PATH=rtd.ende.dict.txt

for lang in en de
do
  fairseq-preprocess \
      --only-source \
      --trainpref $SRC_PATH/train.spm.$lang \
      --validpref $SRC_PATH/dev.spm.$lang \
      --testpref $SRC_PATH/test.spm.$lang \
      --destdir $DEST_PATH/$lang \
      --srcdict $DICT_PATH \
      --workers 10
done
``` 

3) **Training**. Assuming that the first two steps are correct, how do I use `fairseq_train` for the `multilingual_denoising` task?

**Comment by rajarsheem** [comment]
I am not very sure here, but when you create the files ```train.spm.en``` and ```train.spm.de```, isn't the model going to assume they are a translation pair where they are source and target respectively?

**Comment by felixkreuk** [comment]
Hi @cbaziotis I was wondering about the same thing. Did you manage to get the multilingual denoising working for you? Thanks.

**Comment by cbaziotis** [comment]
> Hi @cbaziotis I was wondering about the same thing. Did you manage to get the multilingual denoising working for you? Thanks.

Hi @felixkreuk, I put in this [gist](https://gist.github.com/cbaziotis/8047f2077f1fad74709c7f82d87893a5) the preprocessing script that I used for this [paper](https://aclanthology.org/2021.findings-acl.261/), in which I retrained mBART (and variants) on my own data. You can ignore the particular details (data paths etc), and just focus on the logic of the script. I hope it helps. 

I will share the full code once I find the time to refactor the project (hopefully soon).

**Comment by arjunkoneru** [comment]
Hello @cbaziotis, I am trying to implement mBART as well for the past few hours! It would be very helpful if you can give me some advice. If you pre-process with your code, you would get a folder $PROC_PATH/$lg(1 or 2) and inside that you have files such as valid.$lg-None.$lg.idx, valid.$lg-None.$lg.bin (for train as well). 

When I train on multilingual denoising task, i get the following error from this [code](https://github.com/pytorch/fairseq/blob/f34abcf2b64d8659bae7d3eb2e0caf80cf1d6e7d/fairseq/tasks/multilingual_denoising.py#L144) 
`FileNotFoundError: Dataset not found: valid (data-bin/mbart/kn/valid) `

I am confused about what this file should be?
