### ISSUE TITLE
issues about finetune on mBART models

### ISSUE THREAD

**Issue by fansiawang** [pytorch/fairseq#2119]
## ❓ Questions and Help
Thanks for releasing the mbart models! Referring to [#1758 ](https://github.com/pytorch/fairseq/issues/1758) I reproduced the same results, which is basically close to the results of the paper. Therefore, I use my own data (Japanese-Korean) to fine-tune on the pre-trained model mbart.cc25. Compared with the results of binglingual （baseline: 6.01 BLEU-SBP), finetune has improved by 2.64 points (fintune: 9.65 BLEU-SBP). It seems that this work is effective, but I still have the following questions, I hope to be answered.

#### What is your question?
1. The size of the pre-trained model is **5.7G**, the size of the model after finetuning on mBART is **6.9G** (use my own ja-ko data), and the officially provided finetune en-ro model is **2.3G**. I wonder why is the size difference between these 3 models so large? Did you use any additional operations in finetune?

2. Because the pre-trained vocabulary is very large, the model size is very large, and the training and inference speed is very slow. Is there any way to speed up the training and inference speed? And how to reduce the size of the finetune model?

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):latest github
 - PyTorch Version (e.g., 1.0):1.5.0
 - OS (e.g., Linux):CentOS 7.2
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):pip install --editable .
 - Python version:3.7.3
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: 1080Ti
 - Any other relevant information:

**Comment by mjpost** [comment]
Regarding your first point, it's likely these large models contain the Adam optimizer states. You can remove them with [this script](https://gist.github.com/mjpost/b03346afbaf8cff367f82e8dceb48fc7).

**Comment by fansiawang** [comment]
Thank you for your replying.  Removing Adam optimizer states can certainly reduce the model size, but it can only be inferenced, not finetune. I will try to cut the original dictionary to finetune on GPU.
