### ISSUE TITLE
Inference => RuntimeError: index out of range: Tried to access index 300 out of table with 299 

### ISSUE THREAD

**Issue by AhmedTElthakeb** [pytorch/fairseq#2123]
**Task:**
Inference for librispeech

**Command:** 
python examples/speech_recognition/infer.py /home/ahmed/projects/speech_data/librispeech_final --task speech_recognition --max-tokens 250000 --nbest 1 --path model_lib/checkpoint_best_run1.pt --beam 20 --results-path results_dir --batch-size 20 --gen-subset test-clean --user-dir examples/speech_recognition/

**Error:**
RuntimeError: index out of range: Tried to access index 300 out of table with 299 rows. at /opt/conda/conda-bld/pytorch_1579022027550/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418

**Comment by myleott** [comment]
@okhonko, can you take a look?

**Comment by AhmedTElthakeb** [comment]
While debugging i notice that the dimension of **active_bbsz_idx** suddenly changes from 320 (16*20) to 300 (15*20) and this is when the error happens.
**In: fairseq/fairseq/sequence_generator.py**
![image](https://user-images.githubusercontent.com/38337765/81860274-62a72c00-951b-11ea-8e22-8e6b94ef4df9.png)

**Output:**
------------------------
torch.Size([16, 20])
torch.Size([16, 40])
torch.Size([16, 20])
torch.Size([320])
------------------------
torch.Size([16, 20])
torch.Size([15, 40])
torch.Size([15, 20])
torch.Size([300])

I am still not sure why this happens!

**Comment by liangzhenlin123** [comment]
@AhmedTElthakeb @myleott Hi, do u find a solution for this issue? When inference (use the infer.py in examples/speech_recognition), I got a similar exception when the bzs greater than 1. It seems good when bsz fixed with 1, while it is really slow.... almost cost half an hour for my computer to finished all Aishell's test corpus.

**Comment by okhonko** [comment]
@AhmedTElthakeb I apologize for the delayed reply.
I was able to obtain the model which replicate the bug you mentioned. I am working on the fix now.
