### ISSUE TITLE
Fine-tune BART for translation task on my own dataset

### ISSUE THREAD

**Issue by rathorevipul28** [pytorch/fairseq#2125]
#### Can I fine-tune BART model for translation task on my custom dataset using the same (preprocessing and training) instructions as given for CNN/DM ? Will the same BPE processing and binarizing dataset intructions work here as well or those were specific only for CNN/DM ?

**Comment by myleott** [comment]
@ngoyal2707

**Comment by karin0018** [comment]
> ## ❓ Questions and Help
> #### Can I fine-tune BART model for translation task on my custom dataset using the same (preprocessing and training) instructions as given for CNN/DM ? Will the same BPE processing and binarizing dataset intructions work here as well or those were specific only for CNN/DM ?

hi, I have the same question, did you solve it?
