### ISSUE TITLE
why should i binarize the source and target for the Translation task in Fairseq?

### ISSUE THREAD

**Issue by lyzKF** [pytorch/fairseq#2126]
### Before asking:   
why should i binarize the source and target for the Translation task in Fairseq?  can i use the raw sentence? if so,  how should i do it

thank you!

**Comment by myleott** [comment]
The `fairseq-preprocess` command generates the dictionary file and by default binarizes the dataset, which makes it faster to load and can sometimes make it take less space on disk too. It's highly recommended to binarize the data.

If you prefer, you can instead use raw text by passing `--dataset-impl=raw` to both `fairseq-preprocess` and `fairseq-train`. You still need to run `fairseq-preprocess`, but it will use the raw text.

**Comment by lyzKF** [comment]
Thank you!!!
if each line of my source and target dateset  is ids (not raw words), can i still set ```dataset-impl=cache``` to binarize the source and target ? 
the ids are the index of word in Dictionary.

**Comment by dhar7** [comment]
> The `fairseq-preprocess` command generates the dictionary file and by default binarizes the dataset, which makes it faster to load and can sometimes make it take less space on disk too. It's highly recommended to binarize the data.
> 
> If you prefer, you can instead use raw text by passing `--dataset-impl=raw` to both `fairseq-preprocess` and `fairseq-train`. You still need to run `fairseq-preprocess`, but it will use the raw text.

Thank you for your cleear explanation . But every time I use 'fairseq-preprocess' it gives me a error like:
FileNotFoundError: [Errno 2] No such file or directory: 'wmt14_en_de/train.bert.en'
But before this eroor , dictionary for both languages used to be created successfully .
May I request  a solution for this problem ?

**Comment by lalopark** [comment]
What exactly is it binarizing the data into? key and value (as in dictionary)?
