### ISSUE TITLE
wav2vec loading audio file for evaluation

### ISSUE THREAD

**Issue by erba994** [pytorch/fairseq#2128]
in line:
`wav_input_16khz = torch.randn(1,10000)`

if I want to use a real file, in which format/time the audio should be feed to wav2vec to evaluate the model? it keeps throwing me this error `Expected 3-dimensional input for 3-dimensional weight [512, 1, 10], but got 2-dimensional input of size [212893, 1] instead`

**Comment by erba994** [comment]
solved

**Comment by shamoons** [comment]
Can you please share how @erba994 ?
