### ISSUE TITLE
[Quant-noise] Why p of ActivationQuantizer is set to 0

### ISSUE THREAD

**Issue by ChunhuanLin** [pytorch/fairseq#2131]
#### What is your question?
I find that p of ActivationQuantizer is [always set to 0](https://github.com/pytorch/fairseq/blob/6209d7d6b2c41fccb01e00671261be80ba86029a/fairseq/modules/quantization/scalar/utils.py#L61), which means no noise will be added to activation, why are you doing this? Is it necessary? 

#### Code
        a_q = ActivationQuantizer(quantized_module, p=0, bits=bits, method="histogram")
   

#### What's your environment?

 - fairseq Version (master):
 - PyTorch Version (1.5)

**Comment by myleott** [comment]
@huihuifan

**Comment by huihuifan** [comment]
Thanks for the interest. It is not specifically necessary, but we thought it was simpler as we did not robustly test activation quantization for all models.
