### ISSUE TITLE
[Quant-noise] Why reset quantization parameters frequently?

### ISSUE THREAD

**Issue by ChunhuanLin** [pytorch/fairseq#2132]
#### What is your question?
Quantization parameters, such as scale and zero_point, are [reset](https://github.com/pytorch/fairseq/blob/6209d7d6b2c41fccb01e00671261be80ba86029a/fairseq/modules/quantization/scalar/modules/qact.py#L51) frequently. What's the reason?
#### Code
            # update parameters every 1000 iterations
            if self.counter % self.update_step == 0:
                self.scale = None
                self.zero_point = None
            self.counter += 1
   

 - fairseq Version (master):
 - PyTorch Version (1.5)

**Comment by myleott** [comment]
@huihuifan

**Comment by huihuifan** [comment]
Hello, for the specific 1000 iterations, there was no detailed reason why we needed to update at this frequency. But we didn't want to not reset as the model may change.
