### ISSUE TITLE
wmt19 Text generator Length 

### ISSUE THREAD

**Issue by AdaUchendu** [pytorch/fairseq#2134]
## ❓ Questions and Help
Is it possible to specify length of texts to be generated with the sample function in the wmt19 Language model? Using the arguments tokens and length does not force the generator to generate texts of a defined length, given the prompt.

#### Code
(1) en_lm.sample('Barack Obama', beam=1, sampling=True, sampling_topk=100, temperature=0.8, 
     verbose=True,tokens=500, length=500, min_sentences=500)
(2) en_lm.sample("Machine learning is ", sampling=True, temperature=0.8, verbose=True

(1) and (2) generate texts of similar length suggesting that the length argument is not being used during generation. 

   

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
You can pass max_len_a and max_len_b: https://github.com/pytorch/fairseq/blob/11345a7608a6b73feb53046f6c0eef3dc4d3fc08/fairseq/sequence_generator.py#L43
