### ISSUE TITLE
Save last checkpoint before validation

### ISSUE THREAD

**Issue by villmow** [pytorch/fairseq#2140]
## 🚀 Feature Request
At least a couple of times I started a training and the model crashed after an epoch during validation (because of OOM or just because I write shitty code). All of these times I wished that the epoch checkpoint was saved before validation, to restart training from the next epoch (and discarding that one validation run).

### Pitch

Save epoch checkpoint (`checkpoint_last.pt`) before validation. 
Maybe update it after validation with stats.

**Comment by myleott** [comment]
Fixed in 145bc9de1278414812b2aef837be9ca0e9c1aebc
