### ISSUE TITLE
stats[args.best_checkpoint_metric] -> KeyError: 'loss'

### ISSUE THREAD

**Issue by cyk1337** [pytorch/fairseq#2141]
## ❓ Questions and Help
Hi, I would like to transfer one of my code built with official **fairseq 0.9.0** installed with pip to master source code branch. But the error occurs when I run the training code. It said `loss` does not exist in the keys of `stats`. But this runs without bugs in the installed pip version.

Could anyone please explain how to define or manipulate the `stats` dict here? 

Many thanks )

#### Code
```bash
  File "/home/c/Cpt/fair/fairseq_cli/train.py", line 204, in train
    valid_losses = validate_and_save(args, trainer, task, epoch_itr, valid_subsets)
  File "/home/c/Cpt/fair/fairseq_cli/train.py", line 246, in validate_and_save
    valid_losses = validate(args, trainer, task, epoch_itr, valid_subsets)
  File "/home/c/Cpt/fair/fairseq_cli/train.py", line 308, in validate
    valid_losses.append(stats[args.best_checkpoint_metric])
KeyError: 'loss'
```

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): CentOS 7 / Ubuntu 16.04 LST
 - How you installed fairseq (`pip`, source): source
 - Python version: 3.7
 - CUDA/cuDNN version:10.1
 - GPU models and configuration:V100

**Comment by cyk1337** [comment]
Anyone has better debug advice for pip-installed version rather than command line? Thanks

**Comment by myleott** [comment]
Are you using a custom criterion? Can you share the training command?

**Comment by cyk1337** [comment]
> Are you using a custom criterion? Can you share the training command?

Yes, a custom criterion is applied. The command line for training is:
```
# This command is supplemented on master branch after inplace build
python main.py \
  --restore-file  ckpt/step-xxx.pt \
  --save-dir ckpt \
  --user-dir task \
  --arch default-arch \
  --optimizer adam \
  --adam-betas "(0.9,0.999)" \
  --reset-optimizer \
  --lr 5e-6 \
  --weight-decay 0.0001 \
  --criterion custom_criterion \
  --dropout 0.3 \
  --max-epoch 24 \
  --max-sentences 5 \
  --max-source-positions 100 \
  --embed-dim 512 \
  --tokenizer moses \
  --bpe subword_nmt \
  --bpe-codes output/codes.txt \
  --beam 5 \
  --num-workers 2
``

where `main.py` is defined as:

```python
from fairseq_cli.train import *
cli_main()
```

Meanwhile, following alternative command for pip-installed fairseq could work smoothly:
```bash
python -m fairseq_cli.train \
  --restore-file  ckpt/step-xxx.pt \
  --save-dir ckpt \
  --user-dir task \
  --arch default-arch \
  --optimizer adam \
  --adam-betas "(0.9,0.999)" \
  --reset-optimizer \
  --lr 5e-6 \
  --weight-decay 0.0001 \
  --criterion custom_criterion \
  --dropout 0.3 \
  --max-epoch 24 \
  --max-sentences 5 \
  --max-source-positions 100 \
  --embed-dim 512 \
  --tokenizer moses \
  --bpe subword_nmt \
  --bpe-codes output/codes.txt \
  --beam 5 \
  --num-workers 2
```

**Comment by myleott** [comment]
Your custom criterion needs to log a "loss" scalar in `reduce_metrics`, like this: https://github.com/pytorch/fairseq/blob/master/fairseq/criterions/cross_entropy.py#L59

I'll add a more helpful error message in this case though.
