### ISSUE TITLE
Training with Fairseq 0.7.2 version is too slow and not converging well compare to previous Fairseq version

### ISSUE THREAD

**Issue by jalajthanaki** [pytorch/fairseq#2142]
## ❓ Questions and Help

Hi Fairseq team,
I was using Fairseq version 0.5.0 version previously for NLP task. My aim to upgrade Fairseq version without impacting the accuracy of my NLP task. Recently I'm trying to upgrade my Fairseq version from Fairseq 0.5.0 to Fairseq 0.7.2. 

#### What is your question?
I noticed following points when I am training using Fairseq 0.7.2

1. Training is very slow. Earlier with Fairseq 0.5.0 model converge during 22 to 25 epoch. With Fairseq 0.7.2 version,  training went till 50 epochs and still the loss is comparatively higher than then Fairseq 0.5.0 model training.
2. The another problem is training is not getting stop by itself. We need to stop it manually. Why that is the case? This is [the similar GitHub issue](https://github.com/pytorch/fairseq/issues/1348) I can found but according to me the solution provided there is not best one. 
3. I knew during the release of Fairseq 0.7.0, Fairseq team mentioned about some breaking changes in the release note. I wanted to understand this slowness in training and problem in convergence of the model is due to this breaking changes? 
4. Is there any  bench-marking has been done for this Fairseq-0.7.X version for various NLP tasks?

Please help me with the direction and pointer. If anything more needed from myside then please do let me know.

### Before asking:   
1. I have search if anyone else is facing the similar kind of issue but there is no information on that.

#### What have you tried?
I have tried my experiment with Fairseq 0.5.0 and Fairseq 0.6.2 version. I can get the similar result for Fairseq 0.5.0 and Fairseq 0.6.2. I'm aware that Fairseq 0.7.2 went under drastic changes so I want help from the Fairseq community why the new version (Fairseq 0.7.2) is failing in convergence and getting the similar accuracy which I was getting with Fairseq 0.5.0 version. 

#### What's your environment?

 - fairseq Version = 0.7.2
 - PyTorch Version =torch==1.2.0+cu92
 - OS (e.g., Linux): Ubuntu 18.04 LTS
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source): NA
 - Python version: 3.6.8
 - CUDA/cuDNN version: 9.2
 - GPU models and configuration: Tesla V100
 - Any other relevant information: NA

**Comment by myleott** [comment]
Are you able to use a newer version of fairseq and pytorch? The latest version of fairseq is 0.9.0, but actually it's quite behind master, so ideally you could use fairseq master. Similarly the latest version of pytorch is 1.5.0.

That said, looking through it there shouldn't have been any speed regressions or issues with convergence in fairseq 0.7.2. To further debug we'd need more information about what you ran, the dataset, training logs, etc.

**Comment by jalajthanaki** [comment]
Hi @myleott ,

Thanks you so much for getting back on this issue and providing the suggestion of using fairseq master with Pytorch 1.5 version. I will defiantly try this and see if the slowness in training will exist or not. Get back to this same thread.

**What do I mean by slowness in training?**
1. With Fairseq 0.5 version the model can converge at around 25 epochs vs with Fairseq 0.7.2
    version the model is converging at around 50 epochs
2. With Fairseq 0.5 version training is automatically stopped when validation loss is not decreasing 
    anymore but that is not the case with Fairseq 0.7.2 that is what I observed. I have manually stop 
    training at 50 epochs based on my training log and after referring to the validation loss. I will soon 
    provide the training log so that Fairseq team can look into this issue.

**What is the effect on accuracy?**
With Fairseq 0.7.2, I can observe the 1% of decrement in accuracy compare to Fairseq 0.5.0. 
I'm exploring translation task using Fairseq so for this type of NLP tasks all the above pointers are expected?

**Comment by myleott** [comment]
What training command did you run? Can you share the logs?

We only added early stopping based on validation loss in a recent version of fairseq, so it should not have early stopped training in either fairseq 0.5.0 or 0.7.2.

**Comment by jalajthanaki** [comment]
Thanks @myleott  for answering those question. 

Thing that I have noticed is this: 

- Training with Fairseq 0.5 can automatically stopped but that is not case with fairseq 0.7.2 to fairseq 0.9.0 version. 

Slowness: 

- Fairseq 0.9 and Fairseq-master are little bit faster.  (Not as fast as fairseq 0.5)

Here are the sample of my log file when I'm using fairseq-master and pytorch 1.5 
`2020-05-28 11:20:39 | INFO | valid | epoch 0xx | valid on 'valid' subset | loss 0.6xx | ppl 1.xx | wps 129347 | wpb 3713.9 | bsz 127.8 | num_updates 2.47338e+06 | best_loss 0.6xx
2020-05-28 11:20:50 | INFO | train | epoch 0xx | loss 0.7xx | ppl 1.x | wps 37882.2 | ups 9.42 | wpb 4022.1 | bsz 128 | num_updates 2.47338e+06 |
2020-05-28 11:20:55 | INFO | train_inner | epoch 0xx:     20 / 70668 loss=0.7xx, ppl=1.xx, wps=13712.6, ups=3.4, wpb=4036.8, bsz=127, num_updates=2.4734e+06
2020-05-28 11:21:05 | INFO | train_inner | epoch 0xx:    120 / 70668 loss=0.7xx, ppl=1.xx, wps=38931, ups=9.45, wpb=4120.6, bsz=128, num_updates=2.4735e+06
2020-05-28 11:21:15 | INFO | train_inner | epoch 0xx:    220 / 70668 loss=0.7xx, ppl=1.xx, wps=37897.7, ups=9.82, wpb=3859, bsz=128, num_updates=2.4736e+06`


**The next/other issue I have came across is this:**
 when I'm trying to run the interactive.py script I got following error 
`AttributeError: module 'torch.utils.data' has no attribute 'IterableDataset'`

Does this belong to fairseq or should I raise the issue on PyTorch forums?

**Comment by jalajthanaki** [comment]
Hi 
> The next/other issue I have came across is this:
when I'm trying to run the interactive.py script I got following error
AttributeError: module 'torch.utils.data' has no attribute 'IterableDataset'

I have resolved this issue. Basically I have old version of PyTorch and my script is considering it. When I have upgraded the PyTorch version my script runs smoothly.

I'm closing this issue for now. I will reopen it if I will encounter the slowness in training with fairseq 0.9 again with my future experiments.

Thanks,
Jalaj

**Comment by genbei** [comment]
> 感谢@myleott 回答了这些问题。
> 
> 我注意到的是：
> 
> * Fairseq 0.5的培训可以自动停止，但Fairseq 0.7.2到Fairseq 0.9.0版本的情况并非如此。
> 
> 缓慢：
> 
> * Fairseq 0.9和Fairseq-master快一点。（不如fairseq 0.5快）
> 
> **我遇到的下一个/其他问题是：**
> 当我尝试运行Interactive.py脚本时，出现以下错误
> `AttributeError: module 'torch.utils.data' has no attribute 'IterableDataset'`
> 
> 这是属于fairseq还是我应该在PyTorch论坛上提出问题？我正在使用fairseq-master和PyTorch 1.5

`AttributeError: module 'torch.utils.data' has no attribute 'IterableDataset'`
How did you solve this problem? I used torch0.4.1 and fairseq0.6.0.
