### ISSUE TITLE
Using custom modules for data throws `ModuleNotFouldError`

### ISSUE THREAD

**Issue by Tetratrio** [pytorch/fairseq#2143]
## 🐛 Bug

Problems using plug-ins loaded from user directory when training on multiple GPUs without specifying --distributed-no-spawn.

This problem started appearing first once I started using custom datasets and batch iterators, before that there was no problem using my custom model as a plug-in.

The error I get is:
```
ModuleNotFouldError: No module named 'src'
```
which is thrown after dataloading is complete and training is about to start.

### To Reproduce
I created a gist with the files used to reproduce the error
https://gist.github.com/Tetratrio/730ad11aa79288324445f38a8b3c7b39

The following script builds the docker image, downloads and preprocesses the data and copies the "dummy" source code into the image.
```
for FILE in __init__.py Dockerfile data.sh train.sh; do \
    wget https://gist.githubusercontent.com/Tetratrio/730ad11aa79288324445f38a8b3c7b39/raw/2114880544d587dc63a014fe3d6bfcf5b32f172e/$FILE;
done

sudo docker build -t reproduce -f Dockerfile .
```

Now just run the container
```
sudo docker run --gpus all --ipc=host -it --rm reproduce /bin/bash train.sh
```

#### Code sample
This is the code I used to reproduce the error. I put this code in the `__init__.py` file inside the directory `src/`.
```
from fairseq.tasks import register_task
from fairseq.tasks.masked_lm import MaskedLMTask
from fairseq.data import FairseqDataset


class CustomDataset(FairseqDataset):

    def __init__(self, dataset):
        self._dataset = dataset

    def __getattr__(self, name):
        if name.startswith('_'):
            raise AttributeError
        return getattr(self._dataset, name)

    def __len__(self):
        return len(self._dataset)

    def __getitem__(self, index):
        return self._dataset[index]

    def num_tokens(self, index):
        return self._dataset.num_tokens(index)

    def size(self, index):
        return self._dataset.size(index)


@register_task('my_task')
class MyTask(MaskedLMTask):

    def load_dataset(self, split, epoch=1, combine=False, **kwargs):
        """Load a given dataset split.
        Args:
            split (str): name of the split (e.g., train, valid, test)
        """
        super().load_dataset(split, epoch=epoch, combine=combine, **kwargs)
        self.datasets[split] = CustomDataset(self.datasets[split])
```

### Expected behavior

It should work?

### Environment

Please see the [Dockerfile](https://gist.githubusercontent.com/Tetratrio/730ad11aa79288324445f38a8b3c7b39/raw/2114880544d587dc63a014fe3d6bfcf5b32f172e/Dockerfile)

### Workaround

The easiest and quickest workaround I found which does not require changing any of your custom code is to copy the user-dir into fairseq and add an import statement to the end of the `__init__.py` file in fairseq.

If I have a custom user-dir called `my_module/` I would just run
```
cp -r path/to/my_module path/to/fairseq_repo/fairseq/my_module
echo "from . import my_module" >> path/to/fairseq_repo/fairseq/__init__.py
```

**Comment by Tetratrio** [comment]
Maybe worth adding the workaround to the docs? Somewhere under here
https://github.com/pytorch/fairseq/blob/803c0a6d11fcca6dcff8b8d0a4170338b15b26ff/docs/overview.rst#L51

The workaround is documented in another repo
https://github.com/microsoft/MASS/tree/master/MASS-summarization#other-questions

**Comment by myleott** [comment]
Thanks for the detailed repro! I have a fix and will merge it shortly.

**Comment by myleott** [comment]
This should be fixed now.
