### ISSUE TITLE
Get score of sentence using transformer model

### ISSUE THREAD

**Issue by AlexandderGorodetski** [pytorch/fairseq#2145]
Hello,

I have trained transformer model using wiki data.

Following model was created "checkpoint_best.pt"

I would like to use this model to get score of input sentence.

I found following example https://github.com/pytorch/fairseq/blob/master/examples/language_model/README.md

But in this example the model is loaded from git using following command:
en_lm = torch.hub.load('pytorch/fairseq', 'transformer_lm.wmt19.en', tokenizer='moses', bpe='fastbpe')

I need similar command to load my model "checkpoint_best.pt"

Actually I am not sure if model "checkpoint_best.pt" can be loaded by pytorch, and I guess that this model should be converted somehow to pytorch format.

Could you help me please. And could you point me please to the relevant manuals about issues like this.

Thanks,
AlexG.

**Comment by myleott** [comment]
Later in the README it has instructions for custom models:
```python
# The same interface can be used with custom models as well
from fairseq.models.transformer_lm import TransformerLanguageModel
custom_lm = TransformerLanguageModel.from_pretrained('/path/to/model/dir', 'checkpoint100.pt', tokenizer='moses', bpe='fastbpe')
custom_lm.sample('Barack Obama', beam=5)
# "Barack Obama (...)"
```
