### ISSUE TITLE
layernorm_extra in mbart

### ISSUE THREAD

**Issue by moussaKam** [pytorch/fairseq#2146]
#### What is your question?

Hi,

In  args namespace of mBART25 we can find the following parameter: layernorm_extra=True

What is exactly this parameter about? I can't find it anywhere in the source code.

**Comment by Tixierae** [comment]
Hi, I have the same question. Thanks in advance for your help!

**Comment by ngoyal2707** [comment]
It got renamed to this: https://github.com/pytorch/fairseq/blob/master/fairseq/models/bart/model.py#L289
