### ISSUE TITLE
Can not install 'pip install --editable .'

### ISSUE THREAD

**Issue by sohailhaider** [pytorch/fairseq#2152]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### Screenshot
https://pasteboard.co/J95Frhr.png

#### What have you tried?
using Python2.7 but didnt work.

#### What's your environment?

 - fairseq Version (master): master
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): pip install --editable .
 - Python version: 3.6

**Comment by myleott** [comment]
This seems like something is wrong with your environment, not directly related to fairseq.

Your screenshot doesn't show the actual exception, but in general I'd recommend setting up a fresh environment using Anaconda or miniconda: https://docs.conda.io/en/latest/miniconda.html. Once that's setup you can install pytorch using conda and subsequently fairseq using `pip install --editable .`.
