### ISSUE TITLE
"Note that ASG loss currently doesn't do well with word-pieces"

### ISSUE THREAD

**Issue by SeanNaren** [pytorch/fairseq#2155]
Hey guys, thanks for this awesome library!

I was reading the documentation for the ASG Criterion [here](https://github.com/pytorch/fairseq/blob/master/examples/speech_recognition/README.md#training-librispeech-data-wav2letter-style-convglu--asg-loss) and it mentions "that ASG loss currently doesn't do well with word-pieces". Is there any more details that can be given here or references?

**Comment by lunixbochs** [comment]
ASG loss requires a matrix of `NTOKEN x NTOKEN`. With english letters, that's about 29 x 29, or 841 elements. With 10,000 word pieces, that's 100 million. It's really slow or impossible to train a matrix like that, and it's also mostly useless as most of the cells should be near zero. Basically ASG makes a lot of sense for small letter token vocabs, and no sense at all for large word vocabs.

**Comment by SeanNaren** [comment]
@lunixbochs thanks :)
