### ISSUE TITLE
How to load custom models that contains multiple files

### ISSUE THREAD

**Issue by Oxi84** [pytorch/fairseq#2160]
I tried multiple ways, particularly for RU EN Model 2019 that has 4 files names model1.pt, model2.pt and more. I checked the code and do not see how to load multiple files. Could you help and add to the manual as i guess many people have the same problem. 

     from fairseq.models.transformer import TransformerModel
     zh2en = TransformerModel.from_pretrained(
      '/path/to/checkpoints',
      checkpoint_file='checkpoint_1.pt  checkpoint_2.pt checkpoint_3.pt ',
      data_name_or_path='data-bin/wmt17_zh_en_full',
      bpe='subword_nmt',
      bpe_codes='data-bin/wmt17_zh_en_full/zh.code'
    )
    zh2en.translate('你好 世界')
    # 'Hello World'

**Comment by myleott** [comment]
Thanks, I just updated the README with more detailed instructions, but you need to separate the model checkpoints with `:`, like this:
```python
 zh2en = TransformerModel.from_pretrained(
  '/path/to/checkpoints',
  checkpoint_file='checkpoint_1.pt:checkpoint_2.pt:checkpoint_3.pt',
  data_name_or_path='data-bin/wmt17_zh_en_full',
  bpe='subword_nmt',
  bpe_codes='data-bin/wmt17_zh_en_full/zh.code'
)
```
