### ISSUE TITLE
[Quant-noise] How to properly load the quantized model?

### ISSUE THREAD

**Issue by bdropuljic** [pytorch/fairseq#2161]
#### What is your question?

Hi, I successfully quantized your pretrained roberta-base model during 3 epochs of fine tuning. I saved the quantized model after each epoch. Now, I would like to load the model with the classic procedure (RobertaModel.from_pretrained) but I receive the error when trying to load the state_dict. Error is copy-pasted under the Code section. What should I do to properly load the model? Thanks.

#### Code

from fairseq.models.roberta import RobertaModel
roberta = RobertaModel.from_pretrained(
       	args.modeldir,
       	checkpoint_file = 'checkpoint' + args.epoch + '.pt',
        data_name_or_path = args.datadir
    )

Error:

RuntimeError: Error(s) in loading state_dict for RobertaModel:
	Missing key(s) in state_dict: "decoder.sentence_encoder.embed_tokens.weight", "decoder.sentence_encoder.layers.0.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.0.self_attn.v_proj.weight", "decoder.sentence_encoder.layers.0.self_attn.q_proj.weight", "decoder.sentence_encoder.layers.0.self_attn.out_proj.weight", "decoder.sentence_encoder.layers.0.fc1.weight", "decoder.sentence_encoder.layers.0.fc2.weight", "decoder.sentence_encoder.layers.1.self_attn.k_proj.weight", "decoder.sentence_encoder.layers.1.self_attn.v_proj.weight",
...
"decoder.sentence_encoder.layers.11.self_attn.out_proj.weight", "decoder.sentence_encoder.layers.11.fc1.weight", "decoder.sentence_encoder.layers.11.fc2.weight".
	Unexpected key(s) in state_dict: "decoder.sentence_encoder.embed_tokens.centroids", "decoder.sentence_encoder.embed_tokens.assignments", "decoder.sentence_encoder.embed_tokens.counts", "decoder.sentence_encoder.layers.0.self_attn.k_proj.centroids", "decoder.sentence_encoder.layers.0.self_attn.k_proj.assignments", "decoder.sentence_encoder.layers.0.self_attn.k_proj.counts", "decoder.sentence_encoder.layers.0.self_attn.v_proj.centroids", "decoder.sentence_encoder.layers.0.self_attn.v_proj.assignments", "decoder.sentence_encoder.layers.0.self_attn.v_proj.counts", "decoder.sentence_encoder.layers.0.self_attn.q_proj.centroids", "decoder.sentence_encoder.layers.0.self_attn.q_proj.assignments", "decoder.sentence_encoder.layers.0.self_attn.q_proj.counts", "decoder.sentence_encoder.layers.0.self_attn.out_proj.centroids", "decoder.sentence_encoder.layers.0.self_attn.out_proj.assignments", "decoder.sentence_encoder.layers.0.self_attn.out_proj.counts", "decoder.sentence_encoder.layers.0.fc1.centroids", "decoder.sentence_encoder.layers.0.fc1.assignments",
...
"decoder.sentence_encoder.layers.11.fc1.assignments", "decoder.sentence_encoder.layers.11.fc1.counts", "decoder.sentence_encoder.layers.11.fc2.centroids", "decoder.sentence_encoder.layers.11.fc2.assignments", "decoder.sentence_encoder.layers.11.fc2.counts".

#### What's your environment?

 - fairseq Version (master)
 - PyTorch Version (1.5)
 - OS (Linux)
 - How you installed fairseq (source)
 - Python version: 3.7.7
 - CUDA version: 10.1

**Comment by huihuifan** [comment]
Thanks for opening this issue - I will look into this issue. We did not previously use the RobertaModel.from_pretrained method to load the Roberta Model, so likely there is some incompatibility in the state dict that you are seeing.

**Comment by bdropuljic** [comment]
Thanks for helping me. It doesn't have to be the RobertaModel.from_pretrained method necessarily. I started with it because I successfully loaded a non-quantized fine tuned model with it before. I also tried several other approaches but always failed with the same error during the load_state_dict phase. If you can recommend some other approach for loading the quantized fine tuned model, I would be very happy to use it :)

**Comment by jahutwb** [comment]
I've done it. I mean load quantized model, but I doubt it was done properly, but it worked.
Look here #2232

**Comment by bdropuljic** [comment]
Thanks @jahutwb ! I also succeed by simulating the quantization process during the model loading, which changed the model architecture :) It's not an elegant solution but it works..
