### ISSUE TITLE
Lazy GroupedIterator for less spiky dataloading

### ISSUE THREAD

**Issue by Tetratrio** [pytorch/fairseq#2168]
## 🚀 Feature Request
Allow for the chunks returned by [GroupedIterator](https://github.com/pytorch/fairseq/blob/9f25ffb02ab54a443ba181f732d5dcc00db7bea8/fairseq/data/iterators.py#L351) to not require all data be fetched beforehand.

### Motivation

Right now, when not using large commercial training setups, a high value for update frequency is required when training networks using similar batch sizes as was used in the papers (because of limited memory and/or number of GPUs).

Currently, the same number of data fetches from the epoch iterator is performed as the value of the `update_freq` argument before the training step is started. When each batch contains large amounts of data or the preprocessing requires much computational resources I ran into issues where there was a delay caused by dataloading in-between training steps.

This can be solved by setting `--data-buffer-size` to a value larger or equal to the sum of update frequency and number of data workers. However, this will still create a large 'spike' in dataloading hardware usage (be it loading from disc or heavy preprocessing).
It does work but after doing some testing with a lazy GroupedIterator (detailed below) I found dataloading to be much smoother where the spikes in hardware usage at the start of each training step were gone (smoothed out over the entire training step). This seems like a more robust way of loading the data.

### Pitch

Here is an example of how one could create a lazy chunk without breaking current training code. This still defaults to using the current way of chunking unless `lazy` is set to `True`.
```python
class GroupedIterator(CountingIterator):
    """Wrapper around an iterable that returns groups (chunks) of items.
    Args:
        iterable (iterable): iterable to wrap
        chunk_size (int): size of each chunk
    Attributes:
        n (int): number of elements consumed from this iterator
    """

    def __init__(self, iterable, chunk_size, lazy=False):
        if lazy:
            itr = _lazy_chunk_iterator(iterable, chunk_size)
        else:
            itr = _chunk_iterator(iterable, chunk_size)
        super().__init__(
            itr,
            start=int(math.ceil(getattr(iterable, 'n', 0) / float(chunk_size))),
            total=int(math.ceil(len(iterable) / float(chunk_size))),
        )
        self.chunk_size = chunk_size

        
class LazyChunk:
    
    def __init__(self, itr, chunk_size):
        self.itr = itr
        self.n = chunk_size
        self._n_processed = 0
        self._cache = {}
        
    def __len__(self):
        return self.n
        
    def __getitem__(self, index):
        while self._n_processed <= index:
            self._cache[self._n_processed] = next(self.itr)
            self._n_processed += 1
        return self._cache[index]
    
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

            
def _lazy_chunk_iterator(itr, chunk_size):
    remaining = len(itr)
    chunk = None
    while remaining:
        if chunk is not None:
            for _ in chunk:
                pass
        chunk = LazyChunk(itr, min(chunk_size, remaining))
        remaining -= min(chunk_size, remaining)
        yield chunk

        
def _chunk_iterator(itr, chunk_size):
    chunk = []
    for x in itr:
        chunk.append(x)
        if len(chunk) == chunk_size:
            yield chunk
            chunk = []
    if len(chunk) > 0:
        yield chunk
```

**Comment by myleott** [comment]
Merged in 14ee059a36092a4216ec38601ca32be11383eecb
