### ISSUE TITLE
oom occurs when using too many training pairs?

### ISSUE THREAD

**Issue by zherowolf** [pytorch/fairseq#217]
Hi, @myleott  Thanks for your great work on transformer with pytorch.
I have encounter with a oom problems when I try to train a translation model with more training pairs , like tens of millions or more.
I think the problem occurs because the training pairs will be read into memory at first. 
Did you train a model with ~100 millions pairs of sentences ?
It's OK with ~10 millions pairs of sentences.

By the way , I run with 4 V100 GPUs and the memory is 64G. the total training pairs ( binaried with preprocess.py) are about 15G.
but while loading datasets, the memory is almost fully occupied.

**Comment by zherowolf** [comment]
I can run with changing class IndexedDataset to IndexedInMemoryDataSet when loading dataset splits ,But the training goes much slower.
Did you have some other advice ?
Thx.

**Comment by zherowolf** [comment]
I tried using IndexedDataset and setting num_workers > 1, errors occured showing:
daemonic processes are not allowed to have children.
I will try to preprocess chunks of the data and report later.

**Comment by edunov** [comment]
I'm working on a permanent solution meanwhile, you can use IndexedDataset instead of IndexedInMemoryDataset.

**Comment by SinghJasdeep** [comment]
Thanks edunov! 

Where would I make this change? 

It seems like the default is IndexedDataset in preprocess.py?

(line 118) 
ds = indexed_dataset.IndexedDatasetBuilder(dataset_dest_path(output_prefix, lang, 'bin'))

**Comment by myleott** [comment]
I think you would change this to IndexedDataset: https://github.com/pytorch/fairseq/blob/6381cc977fa909bd53c8915a18684e49b3507332/fairseq/tasks/translation.py#L117. It shouldn't be necessary to change preprocess.py

**Comment by myleott** [comment]
You should be able to use `--fix-batches-to-gpus` (introduced in 90f52a1) to fix this.
