### ISSUE TITLE
How to get an attention matrix when we evaluate the transformer model on translation task?

### ISSUE THREAD

**Issue by gtshs2** [pytorch/fairseq#2171]
I have an experiment with the Transformer model on the IWSLT14 dataset.
On the evaluation step, I want to analyze the attention weights for each head. 

I found the alignment matrix in generate.py, but it is hard to figure out the attention matrix for each head.
I also found that hypo['attention'] gives some attention matrix similar to hypo['alignment']
https://github.com/pytorch/fairseq/blob/9f25ffb02ab54a443ba181f732d5dcc00db7bea8/fairseq_cli/generate.py#L192

1) How can we interpret the hypo['attention'] matrix? it doesn't seem to correspond to the hypo['alignment']

2) How can we get an attention matrix for each head on the evaluation step?
I want to get the attention matrix one of the below.
A. Last decoder layers' attention matrix
B. Averaged attention matrix
C. Each decoder layer's attention matrix)

**Comment by guyazov** [comment]
Did you find an answer fro that?

**Comment by jamfly** [comment]
does anyone find a proper solution on it?
