### ISSUE TITLE
error: could not create 'fairseq.egg-info': Permission denied

### ISSUE THREAD

**Issue by ttambe** [pytorch/fairseq#218]
Hi,

I get "_could not create 'fairseq.egg-info': Permission denied_" error when running "python setup.py install". Any insights on how to fix this?

ttambe@acc35:/group/vlsiarch/ttambe/models/fseq/fairseq$ sudo python setup.py install
running install
running bdist_egg
running egg_info
creating fairseq.egg-info
error: could not create 'fairseq.egg-info': Permission denied
ttambe@acc35:/group/vlsiarch/ttambe/models/fseq/fairseq$

Thanks,

**Comment by myleott** [comment]
This seems like a permissions issue in your source directory. Please try something like this: https://stackoverflow.com/a/43898861
