### ISSUE TITLE
RuntimeError: "mul_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by AlexandderGorodetski** [pytorch/fairseq#2181]
Hello,

I am trying to train a LM transformer according to the following example.

https://github.com/pytorch/fairseq/blob/master/examples/language_model/README.md

I got following error when running fairseq-train

RuntimeError: "mul_cpu" not implemented for 'Half'

Could you help please.

Thanks,
AlexG.

**Comment by AlexandderGorodetski** [comment]
This problem can be occurred if CUDA driver was not updated. To update CUDA driver on ubuntu look into
https://docs.nvidia.com/datacenter/tesla/tesla-installation-notes/index.html#ubuntu-lts

**Comment by alphadl** [comment]
maybe you can degrade your torch version, e.g., from 1.5 to 1.4, which works for me. @AlexandderGorodetski
