### ISSUE TITLE
Why RoBERTa inherited from FairseqDecoder

### ISSUE THREAD

**Issue by xu-song** [pytorch/fairseq#2186]
#### What is your question?

RoBERTa is a sentence encoder model, why inherited from `FairseqDecoder`

#### Code

https://github.com/pytorch/fairseq/blob/145bc9de1278414812b2aef837be9ca0e9c1aebc/fairseq/models/roberta/model.py#L264-L276

**Comment by myleott** [comment]
Good point, it seems we can extend FairseqEncoderModel instead. I'll submit a fix
