### ISSUE TITLE
Training with Quantization Noise for Extreme Model Compression - Vision Results

### ISSUE THREAD

**Issue by thimabru1010** [pytorch/fairseq#2191]
When there will be available to reproduce vision results in paper?

**Comment by myleott** [comment]
The vision experiments from that paper were done in [ClassyVision](https://github.com/facebookresearch/ClassyVision) (see Section 8.1). I'm not aware of any immediate plans to reimplement those experiments in fairseq.

**Comment by thimabru1010** [comment]
Where exactly are these experiments? Can't find section 8.1 under ClassyVision.
