### ISSUE TITLE
vq-wav2vec roberta data cropping

### ISSUE THREAD

**Issue by david-macleod** [pytorch/fairseq#2197]
## What is your question?
I noticed in the paper 

> The batch size is 10, and we crop a random section of 150k frames for each example (approximately 9.3 seconds for 16kHz sampling rate).

Is this specific to the vqwav2vec training or does it also apply to **roberta** training? i.e. were inputs cropped to a standard length prior to tokenisation for roberta training or were full files from the librispeech dataset trained on regardless of length?

If the inputs were cropped, does that mean the files < 9.3 seconds were dropped from training, or padded to that fixed length?

Many thanks

**Comment by david-macleod** [comment]
cc @alexeib

**Comment by alexeib** [comment]
it is specific to audio pre-training only. samples are not cropped for roberta training
