### ISSUE TITLE
Possibly wrong link of roberta base model with layerdrop ？

### ISSUE THREAD

**Issue by zhuango** [pytorch/fairseq#2206]
## 📚 Documentation

I am reproducing the roberta base model with layerdrop. I found that the link of the model published on the layerdrop [readme page](https://github.com/pytorch/fairseq/tree/8e48f45aa469bbff85613520ffc161c0850e4744/examples/layerdrop) is not accessible. Is the https://dl.fbaipublicfiles.com/fairseq/models/roberta_layerdrop.base.qnli.tar.gz the wrong link? Because I can just download roberta base mode with layerdrop from https://dl.fbaipublicfiles.com/fairseq/models/roberta_layerdrop.base.tar.gz . Just want to make sure the correct model link. Thanks.

![image](https://user-images.githubusercontent.com/5491519/83712667-db9c2e00-a658-11ea-9707-0f6c53bda4b8.png)

**Comment by huihuifan** [comment]
Ah yes thank you for identifying this! I will update the link.

**Comment by zhuango** [comment]
Thanks.
