### ISSUE TITLE
Is the first target token ignored? (`translation` task w/ `bart.base` arch)

### ISSUE THREAD

**Issue by pltrdy** [pytorch/fairseq#2209]
Hi,

## Task: kind of 2 variables classification `x -> y0, y1`
I've been experimenting with BART models, and as preliminary experiments wanted to train a model to produce, from a text source (from CNN/DM dataset), two kinds of tokens, having 10 values each.

For simplicity, the first tokens takes values from `A` to `J` and second token from `a` to `j` and typically represents features of the sources that as been calculated during preprocessing.

My target typically looks like:
```
E f
I d
B d
C a
[...]
```

I run BPE preprocessing, binarization and training exactly like: https://github.com/pytorch/fairseq/blob/master/examples/bart/README.summarization.md the only difference is the model size (`bart.base` with following change: 6 heads, 3 layers, for both encoder and decoder). 

**NOTE: I'm not finetuning here, I'm training from scratch (I tried finetuning but went back to the simplest task to debug)**

## Problem: inference only output one token (instead of two)
In this task token prediction isn't trivial. However, there's not much variance in the target:
* always 2 tokens
* first token always in `[A, J]`
* second token always in `[a, j]`

when running inference (w/ beam in [1, 4], min_len=1), the model only predicts the *second* token, i.e. the lowercase one. I don't understand why.
I've been checking manually the dataset, examples are like: `tensor([717, 856,   2])`, there is 2 tokens + EOS which make sense to me, I even checked token ids, all is correct, but still, even after multiple epochs, only 1 token is predicted.

Using `min_len=3` to force 2 token (+EOS) only makes the model repeat the predicted token, not generate the other one.

 
Am I missing something (I guess I do..)?

**Comment by jxhe** [comment]
Hi, I am not completely sure about this, but seems relevant to #1517 to me. Basically at fine-tuning there is no <bos> token prepended to the target sequence but the BART decoding assumes there is one and forces the first predicted token to be always <bos>:

https://github.com/pytorch/fairseq/blob/d37529ed234ea9173ed35f6797a51a85378ecfca/fairseq/models/bart/hub_interface.py#L123

There is no prefix_tokens for a normal translation task.

**Comment by zhuochunli** [comment]
> Hi,
> 
> ## Task: kind of 2 variables classification `x -> y0, y1`
> I've been experimenting with BART models, and as preliminary experiments wanted to train a model to produce, from a text source (from CNN/DM dataset), two kinds of tokens, having 10 values each.
> 
> For simplicity, the first tokens takes values from `A` to `J` and second token from `a` to `j` and typically represents features of the sources that as been calculated during preprocessing.
> 
> My target typically looks like:
> 
> ```
> E f
> I d
> B d
> C a
> [...]
> ```
> 
> I run BPE preprocessing, binarization and training exactly like: https://github.com/pytorch/fairseq/blob/master/examples/bart/README.summarization.md the only difference is the model size (`bart.base` with following change: 6 heads, 3 layers, for both encoder and decoder).
> 
> **NOTE: I'm not finetuning here, I'm training from scratch (I tried finetuning but went back to the simplest task to debug)**
> 
> ## Problem: inference only output one token (instead of two)
> In this task token prediction isn't trivial. However, there's not much variance in the target:
> 
> * always 2 tokens
> * first token always in `[A, J]`
> * second token always in `[a, j]`
> 
> when running inference (w/ beam in [1, 4], min_len=1), the model only predicts the _second_ token, i.e. the lowercase one. I don't understand why. I've been checking manually the dataset, examples are like: `tensor([717, 856, 2])`, there is 2 tokens + EOS which make sense to me, I even checked token ids, all is correct, but still, even after multiple epochs, only 1 token is predicted.
> 
> Using `min_len=3` to force 2 token (+EOS) only makes the model repeat the predicted token, not generate the other one.
> 
> Am I missing something (I guess I do..)?

Hi, I encounter the same problem, and the BART output seems also ignore my first token. Did you solve this problem? Thank you!

**Comment by zhuochunli** [comment]
Hi, I think I got a solution for my problem that missing the first token in BART inference output. You can set the prefix_tokens=None to tell the model don't take the first output token as BOS.
[bart/fairseq/models/bart/guided_hub_interface.py](https://github.com/facebookresearch/fairseq/blob/d37529ed234ea9173ed35f6797a51a85378ecfca/fairseq/models/bart/hub_interface.py#L123)
