### ISSUE TITLE
problem with --sampling?

### ISSUE THREAD

**Issue by hhexiy** [pytorch/fairseq#221]
Hi, I was using `--sampling` during generation (a lstm seq2seq model) but the results seem off. In particular, `--sampling --sampling-temperature 0.000001 --beam 1 --nbest 1` should be almost the same as argmax, i.e. `--beam 1 --nbest 1`, but the two results are very different.

**Comment by edunov** [comment]
@hhexiy do you use interactive.py or generate.py? I think interactive.py doesn't pass sampling temperature through to the generator. Let me submit a fix. 
Also, we seems to have some numerical issues with such low temperatures, --sampling-temperature 0.1 should work though.
