### ISSUE TITLE
why move_eos_to_beginning not move_bos_to_beginning

### ISSUE THREAD

**Issue by xu-song** [pytorch/fairseq#2215]
#### What is your question?

bos is usually added at begining of sentence.
However in this implementation, eos is added as start of sentence.

#### Code

  
https://github.com/pytorch/fairseq/blob/ea092c2aa697eb7c362447e663922d2dfe2f6da1/fairseq/data/language_pair_dataset.py#L68-L75

https://github.com/pytorch/fairseq/blob/ea092c2aa697eb7c362447e663922d2dfe2f6da1/fairseq/data/language_pair_dataset.py#L24-L28

**Comment by lemuria-wchen** [comment]
I think this is just for convinence, since pre-process will automatally add </s> in each example, so in this function move_eos_to_beginning parameter can move </s> to the beginning if set true, but i still think it will be more elegant if we can add  <s> in the start and remove </s> in the end.
