### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by samin9796** [pytorch/fairseq#2216]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
I am getting zero divison error. I have 48500000 sentences in my corpus and I am trying to build a language model. 
#### Code
 
This is the training command.
>  /data/ahnaf/fairseq_folder/fairseq$ python3 train.py /data/ahnaf/fairseq_folder/models/dest --save-dir /data/ahnaf/fairseq_folder/models/decoder/convlm_models/word_14B 
--task=language_modeling --arch=fconv_lm --memory-efficient-fp16 
--max-epoch=48 --optimizer=nag --lr=0.5 --lr-scheduler=fixed --decoder-embed-dim=128 --clip-norm=0.1 
--decoder-layers='[(512, 5)] + [(128, 1, 0), (128, 5, 0), (512, 1, 3)] * 3 + [(512, 1, 0), (512, 5, 0), (1024, 1, 3)] * 3 + [(512, 1, 0), (512, 5, 0), (1024, 1, 3)] * 6 + [(1024, 1, 0), (1024, 5, 0), (2048, 1, 3)]' --dropout=0.1 --weight-decay=1e-07 
--max-tokens=1024 --tokens-per-sample=1024 --sample-break-mode=none --criterion=adaptive_loss --adaptive-softmax-cutoff='100,500,2000' --seed=42 --log-format=json --log-interval=100 --save-interval-updates=10000 --keep-interval-updates=10 --ddp-backend="no_c10d" --distributed-world-size=4 > /data/ahnaf/fairseq_folder/models/decoder/convlm_models/word_14B/train.log

Log output:

> /data/ahnaf/fairseq_folder/fairseq/fairseq/tasks/fairseq_task.py:391: UserWarning: ntokens not found in Criterion logging outputs, cannot log wpb or wps
  "ntokens not found in Criterion logging outputs, cannot log wpb or wps"
/data/ahnaf/fairseq_folder/fairseq/fairseq/tasks/fairseq_task.py:391: UserWarning: ntokens not found in Criterion logging outputs, cannot log wpb or wps
  "ntokens not found in Criterion logging outputs, cannot log wpb or wps"
/data/ahnaf/fairseq_folder/fairseq/fairseq/tasks/fairseq_task.py:400: UserWarning: nsentences not found in Criterion logging outputs, cannot log bsz
  "nsentences not found in Criterion logging outputs, cannot log bsz"
/data/ahnaf/fairseq_folder/fairseq/fairseq/tasks/fairseq_task.py:400: UserWarning: nsentences not found in Criterion logging outputs, cannot log bsz
  "nsentences not found in Criterion logging outputs, cannot log bsz"
/data/ahnaf/fairseq_folder/fairseq/fairseq/tasks/fairseq_task.py:391: UserWarning: ntokens not found in Criterion logging outputs, cannot log wpb or wps
  "ntokens not found in Criterion logging outputs, cannot log wpb or wps"
/data/ahnaf/fairseq_folder/fairseq/fairseq/tasks/fairseq_task.py:400: UserWarning: nsentences not found in Criterion logging outputs, cannot log bsz
  "nsentences not found in Criterion logging outputs, cannot log bsz"
/data/ahnaf/fairseq_folder/fairseq/fairseq/tasks/fairseq_task.py:391: UserWarning: ntokens not found in Criterion logging outputs, cannot log wpb or wps
  "ntokens not found in Criterion logging outputs, cannot log wpb or wps"
/data/ahnaf/fairseq_folder/fairseq/fairseq/tasks/fairseq_task.py:400: UserWarning: nsentences not found in Criterion logging outputs, cannot log bsz
  "nsentences not found in Criterion logging outputs, cannot log bsz"
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cli_main()
  File "/data/ahnaf/fairseq_folder/fairseq/fairseq_cli/train.py", line 365, in cli_main
    nprocs=args.distributed_world_size,
  File "/home/shafkat/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/shafkat/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

> -- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/shafkat/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data/ahnaf/fairseq_folder/fairseq/fairseq_cli/train.py", line 333, in distributed_main
    main(args, init_distributed=True)
  File "/data/ahnaf/fairseq_folder/fairseq/fairseq_cli/train.py", line 120, in main
    valid_losses, should_stop = train(args, trainer, task, epoch_itr)
  File "/home/shafkat/anaconda3/envs/fairseq/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/data/ahnaf/fairseq_folder/fairseq/fairseq_cli/train.py", line 206, in train
    log_output = trainer.train_step(samples)
  File "/home/shafkat/anaconda3/envs/fairseq/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/data/ahnaf/fairseq_folder/fairseq/fairseq/trainer.py", line 536, in train_step
    logging_outputs, sample_size, grad_norm,
  File "/data/ahnaf/fairseq_folder/fairseq/fairseq/trainer.py", line 893, in _reduce_and_log_stats
    self.task.reduce_metrics(logging_outputs, self.get_criterion())
  File "/data/ahnaf/fairseq_folder/fairseq/fairseq/tasks/fairseq_task.py", line 406, in reduce_metrics
    criterion.__class__.reduce_metrics(logging_outputs)
  File "/data/ahnaf/fairseq_folder/fairseq/fairseq/criterions/adaptive_loss.py", line 87, in reduce_metrics
    metrics.log_scalar('loss', loss_sum / sample_size / math.log(2), sample_size, round=3)
ZeroDivisionError: division by zero
 

#### What have you tried?
Changing different token per sample , max token and number of GPU for training.
#### What's your environment?

 - fairseq Version (e.g., master):
 - PyTorch Version (e.g., 1.4)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:3.6
 - CUDA/cuDNN version:10.0
 - GPU models and configuration: nvidia GTX 1080Ti 8 GPUs, each one 11GB
 - Any other relevant information:

**Comment by narfanar** [comment]
`reduce_metrics` and numerous other functions expect logging_outputs to have type `List[dict]` which is a list of dicts from logging variable to log value.

But _actually_ the logging_outputs are being put in a `List[Dict[str, dict]]`. It looks like:

```py
    [
		{
			"<lang>": { "log_var": log_val },
			"<lang2>" { ... },
		},
		{ ... },
		...
	]
```

**Comment by Bachstelze** [comment]
Do you know since which commit this internal API is broken?
