### ISSUE TITLE
Size Mismatch error when training translation_from_pretrained_xlm

### ISSUE THREAD

**Issue by ajesujoba** [pytorch/fairseq#2218]
I have trained XLM in fairseq and have got the best checkpoint. Now I need to train translation_from_pretrained_xlm model using the XLM checkpoint. When I tried running the script I got a `RuntimeError: Error(s) in loading state_dict for TransformerEncoderFromPretrainedXLM: `

My training script:
`CUDA_VISIBLE_DEVICES=0 python3 train.py /raid/data/alabi/data/XLM/mono/fairseq_processed2   --arch transformer
_from_pretrained_xlm --share-decoder-input-output-embed  --pretrained-xlm-checkpoint checkpoints/mlm1/checkpoint_best.pt --optimizer adam --adam-betas '(0.9, 0.98)' --c
lip-norm 0.0 --task translation_from_pretrained_xlm --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.3 --weight-decay 0.0001  --criterion label_s
moothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-learned-pos  --decoder-learned-pos`

The Error Log
![xlm](https://user-images.githubusercontent.com/12751379/83965769-704f9780-a8b6-11ea-8a49-4cb840ef5dce.PNG)

The script for training the XLM
`CUDA_VISIBLE_DEVICES=3 python3 train.py --task cross_lingual_lm /raid/data/alabi/data/XLM/mono/fairseq_processed  --save-dir checkpoints/mlm1 --max-update 2400000 --save-interval 1 --no-epoch-checkpoints --arch xlm_base --optimizer adam --lr-scheduler reduce_lr_on_plateau --lr-shrink 0.5 --lr 0.0001 --min-lr 1e-09 --dropout 0.1 --criterion legacy_masked_lm_loss --max-tokens 2048 --tokens-per-sample 256 --attention-dropout 0.1  --seed 0 --masked-lm-only --monolingual-langs 'de,hsb' --num-segment 2 --ddp-backend=no_c10d --num-workers 10  | tee train_xlm_de_hsb1.log`

How do I resolve this?

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.4.0)
 - OS (e.g., Linux): Linux
 - Python version: 3.7

**Comment by Bachstelze** [comment]
Have you tried to set the embedding dimensions for XLM-R?
```
    --decoder-embed-dim 1024 --encoder-embed-dim 1024 \
    --decoder-ffn-embed-dim 1024 --encoder-ffn-embed-dim 1024 \
```

**Comment by ajesujoba** [comment]
@Bachstelze, you mean when training the XLM-R, I should include those parameters as I have below:

`
CUDA_VISIBLE_DEVICES=3 python3 train.py --task cross_lingual_lm /raid/data/alabi/data/XLM/mono/fairseq_processed  --save-dir checkpoints/mlm1 --max-update 2400000 --save-interval 1 --no-epoch-checkpoints --arch xlm_base --optimizer adam --lr-scheduler reduce_lr_on_plateau --lr-shrink 0.5 --lr 0.0001 --min-lr 1e-09 --dropout 0.1 --criterion legacy_masked_lm_loss --max-tokens 2048 --tokens-per-sample 256 --attention-dropout 0.1  --seed 0 --masked-lm-only --monolingual-langs 'de,hsb' --num-segment 2 --ddp-backend=no_c10d --num-workers 10 **--decoder-embed-dim 1024 --encoder-embed-dim 1024  --decoder-ffn-embed-dim 1024 --encoder-ffn-embed-dim 1024**  | tee train_xlm_de_hsb1.log   

`

**Comment by Bachstelze** [comment]
Yes, what is the output? I can't evaluate the other parameters.

**Comment by ajesujoba** [comment]
@Bachstelze , the current output:
![xlm_2](https://user-images.githubusercontent.com/12751379/84039462-8f772380-a9a1-11ea-9425-d707cd066c4b.PNG)

**Comment by Bachstelze** [comment]
Which example do want to reproduce? The training parameters are different to Roberta. If you want to pretrain for a bilingual translation then i would consider pretraining with MASS (or mBART if the scripts are available).

**Comment by ajesujoba** [comment]
Actually, I'm not reproducing any example,
My idea was just to train XLM on two languages, German and Sorbian and do a translation task with the XLM. 

So to train the XLM I used the script below based on the document from fairseq:
`CUDA_VISIBLE_DEVICES=1 python3 train.py --task cross_lingual_lm /raid/data/alabi/data/XLM/mono/fairseq_processed --save-dir checkpoints/mlm1 --max-update 2400000 --save-interval 1 --no-epoch-checkpoints --arch xlm_base --optimizer adam --lr-scheduler reduce_lr_on_plateau --lr-shrink 0.5 --lr 0.0001 --min-lr 1e-09 --dropout 0.1 --criterion legacy_masked_lm_loss --max-tokens 2048 --tokens-per-sample 256 --attention-dropout 0.1 --seed 0 --masked-lm-only --monolingual-langs 'de,hsb' --num-segment 2 --ddp-backend=no_c10d --num-workers 10  | tee train_xlm_de_hsb1.log`

and then train the translation task using :
`CUDA_VISIBLE_DEVICES=1 python3 train.py /raid/data/alabi/data/XLM/mono/fairseq_processed2   --arch transformer_from_pretrained_xlm --share-decoder-input-output-embed  --pretrained-xlm-checkpoint checkpoints/mlm1/checkpoint_best.pt --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 --task translation_from_pretrained_xlm --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.3 --weight-decay 0.0001  --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --encoder-learned-pos  --decoder-learned-pos
`
There was no documentation for the translation task however.

**Comment by huihuifan** [comment]
Your seq2seq model is a different size than your pretrained XLM, most likely in the hidden dimension. Can you try setting those parameter sizes?
