### ISSUE TITLE
Extract embedding from NMT, apply some transformation, use it back to finetune 

### ISSUE THREAD

**Issue by nishaahmed** [pytorch/fairseq#2219]
## ❓ Questions and Help

Following the instructions at https://github.com/pytorch/fairseq/tree/master/examples/translation, I have trained an NMT model. Now i'd like to extract the embeddings of the model, apply some transformations,  and use it back to fine-tune the previously trained NMT model. Can you please tell me how to achieve this?

**Comment by jiahaosuda** [comment]
> ## ❓ Questions and Help
> Following the instructions at https://github.com/pytorch/fairseq/tree/master/examples/translation, I have trained an NMT model. Now i'd like to extract the embeddings of the model, apply some transformations, and use it back to fine-tune the previously trained NMT model. Can you please tell me how to achieve this?

Hi, i also want to extract the embeddings of the model. Have you extracted the embeddings successfully? Could you please share the script whit me?
