### ISSUE TITLE
How to use unk replace ?

### ISSUE THREAD

**Issue by KelleyYin** [pytorch/fairseq#222]
Hi,
In translation decoding , I need to get the word alignment file when using unk replace function. Can you give a script ?

**Comment by edunov** [comment]
It is here: https://github.com/pytorch/fairseq/blob/master/scripts/build_sym_alignment.py
We don't really use it for MT anymore, because BPE handles unknown words way better. Is there any reason you don't use BPE encoding and need unk replacement?

**Comment by KelleyYin** [comment]
@edunov Yes, you are right.
However, we don't use bpe for Chinese&English corpus in general .
I found that t[he OpenNMT](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translation.py#L44),supported by HarvardNLP, directly regard word of the max attention scores as Unk replacement.

**Comment by myleott** [comment]
Have you looked at training sentence piece models? https://github.com/google/sentencepiece

If you prefer unknown replacement based on the attention scores, we print the max attention alignment in the output of generate.py. It should be pretty trivial to do the substitution in postprocessing.

**Comment by KelleyYin** [comment]
Thank you for your reply!
I want to use both BPE and Unk replacement to handle unknown words.
In the first, I need to use build_sym_alignment.py script to generate alignment file . However, I'm not sure whether to use the data after bpe or the data before bpe to generate alignment file .
Then, does preprocess.py need to add the alignment file?
Thanks！

**Comment by lengockyquang** [comment]
> Have you looked at training sentence piece models? https://github.com/google/sentencepiece
> 
> If you prefer unknown replacement based on the attention scores, we print the max attention alignment in the output of generate.py. It should be straightforward to do the substitution in postprocessing.

Hi, i know this issue had been closed, but can you give me more detail how to use replace-unk more clearly ?
