### ISSUE TITLE
mBART: Fine-tuning on an unseen language

### ISSUE THREAD

**Issue by ddaspit** [pytorch/fairseq#2223]
#### What is your question?
In the paper "Multilingual Denoising Pre-training for Neural Machine Translation", there is mention of fine-tuning on languages that are not in the pre-trained model. The fine-tuning example in the mBART README is on languages that are in the pre-trained model (en and ro). Is it possible to fine-tune on an unseen language either on the source-side or target-side? The pre-trained model will not contain an embedding vector for the unseen language symbol. Is there anything special that needs to be done to support fine-tuning on an unseen language?

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.5
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): pip install --editable ./
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Nvidia RTX 2070
 - Any other relevant information:

**Comment by fahimeh-saleh** [comment]
I have the same issue! any help?

**Comment by sumanthd17** [comment]
Any update on this?

**Comment by fnangle** [comment]
Need help too！

**Comment by mahmoudtarek1871997** [comment]
same issue. help!!!!

**Comment by evelynkyl** [comment]
same issue! appreciate any help on this!
