### ISSUE TITLE
'fairseq-train' does not appear to train

### ISSUE THREAD

**Issue by JustCunn** [pytorch/fairseq#2224]
#### What is your question?
I have been using Fairseq for a while now to train NMT models without a problem on Colab. Recently, I have moved to a High-End computer network cluster and have been using Fairseq there. This could be a problem with the cluster, but I just wanted to ask to see if anyone experienced the issue here.
So, I initiate `fairseq-train` like normal and have the following settings:
```
#!/bin/bash

fairseq-train data-bin-full_corp/MayNMT \
    --cpu --arch transformer\
    --optimizer adam --clip-norm 0.1 \
    --lr 5e-4 --lr-scheduler inverse_sqrt\
    --dropout 0.2\
    --max-tokens 4096 --save-dir checkpoints/full_tran
```
About the `--cpu` flag, I'm using a CPU because as of right now, I only have access to the cpu version of PyTorch on the cluster. Whether that is a problem, I don't know.
The following is the output:

```
| model transformer, criterion CrossEntropyCriterion
| num. model params: 59244544 (num. trained: 59244544)
| training on 1 GPUs
| max tokens per GPU = 4096 and max sentences per GPU = None
| no existing checkpoint found checkpoints/full_tran/checkpoint_last.pt
| loading train data for epoch 0
| loaded 813393 examples from: data-bin-full_corp/MayNMT/train.en-ga.en
| loaded 813393 examples from: data-bin-full_corp/MayNMT/train.en-ga.ga
| data-bin-full_corp/MayNMT train en-ga 813393 examples
```
And it will run on the specified amount of time (30mins in this case for a test) and it won't go past that. It doesn't throw an error, it just sits there and doesn't train anything. No checkpoints are logged.

 - fairseq Version: 0.9.0
 - PyTorch Version: 1.5.0 (cpu)
 - OS: Linux
 - How you installed fairseq: Unfortunately, I can't install libraries on the cluster myself
 - Python version: 3.7.7
 - Any other relevant information: If the CPU model is relevant - Intel Xeon Gold 6148 (Skylake)

**Comment by myleott** [comment]
I suspect it's just too slow to train on CPU, so you're not even getting to the first log output. Please try `--log-format simple --log-interval 1`.

Unfortunately, training on CPU is really only practical for unit tests (and that's the only reason we support CPU training).

**Comment by JustCunn** [comment]
Ok thanks. Was just making sure it wasn't a deeper issue that we'd have to sort out, but knowing that everything is more than likely is working is good. I'll definitely be moving to the GPU version as soon as.
