### ISSUE TITLE
How to ensemble Fairseq models?

### ISSUE THREAD

**Issue by MaggieMeow** [pytorch/fairseq#223]
Parts of the code suggests that generate.py can generate sequences based on multiple models. 

https://github.com/pytorch/fairseq/blob/30ef667d40b9b34ca9caa43706a89b57531f19a7/generate.py#L41

Could you please kindly suggest an example of this usage, if possible?

Thanks!

**Comment by myleott** [comment]
Yes, if you pass `--path model1.pt:model2.pt` it will ensemble model1 and model2 for generation. Note that ensembling this way loads both models into memory, so it may be necessary to do ensemble generation on CPU with the `--cpu` flag (e.g., if the models are too big to store multiple of them in GPU memory).

**Comment by MaggieMeow** [comment]
I see. Thanks a lot!

**Comment by MaggieMeow** [comment]
@myleott I couldn't ensemble two models from two different architectures, e.g. a LSTM and a transformer. It trows a runtime error: Error(s) in loading state_dict for LSTMModel. Any workarounds to get the ensemble to work for models from 2 different architectures?

Thanks!

**Comment by huihuifan** [comment]
closing, merged into master. thanks!
