### ISSUE TITLE
Help with using Pointer-Generator for abstractive summarization

### ISSUE THREAD

**Issue by griff4692** [pytorch/fairseq#2233]
#### What have you tried?

I have seen this [issue](https://github.com/pytorch/fairseq/issues/311), but wondering how it was resolved (if there is a way that doesn't involve changing the source code)

**Comment by mohammadKhalifa** [comment]
@griff4692 Any luck getting this to work?

**Comment by xcfcode** [comment]
Maybe https://github.com/zhawe01/fairseq-gec will help you.
