### ISSUE TITLE
[QuantNoise] QuantNoise convertion for custom / own model outside of fairseq?

### ISSUE THREAD

**Issue by Oskop** [pytorch/fairseq#2236]
Will pytorch release code to convert custom model using quant-noise? especially on digital speech processing, for example, ForwardTacotron.

**Comment by huihuifan** [comment]
Thanks for the interest. We are investigating the possibility. In the meantime, we have an "integration with your own code" section of our ReadMe: https://github.com/pytorch/fairseq/tree/master/examples/quant_noise
