### ISSUE TITLE
Refactor LSTM model

### ISSUE THREAD

**Issue by mingruimingrui** [pytorch/fairseq#2237]
## 🚀 Feature Request
update LSTM Encoder/Decoder module to be more compatible with the rest of the package.

### Motivation
Transformers and convs are great! But their power mostly comes in the form of the encoders.

A suggestion would be to mix and match encoder and decoder arch. Eg. Dynamic conv encoder + RNN decoder. That way the speed and const memory nature of RNN decoder can be used in conjunction with the performance of the conv encoder.

**Comment by myleott** [comment]
This would be nice, PRs welcome!

**Comment by mingruimingrui** [comment]
Here's a brief update. I'm still running a few experiments to figure out the best way to do this (prioritizing performance to speed tradeoff).

Experiments are on wmt14-en-de comparing untokenized BLEU. (Tokenized BLEU (without segmenting compound words) for baseline is 28.6 which is about the results reported by Vaswani et al.)
The encoder uses the same settings (6 layers, normalize before etc...) throughout.

## Architecture comparison
![image](https://user-images.githubusercontent.com/18568364/85695067-4695cd80-b70a-11ea-9b7f-f8366f7dcb1d.png)

## Decoder layer comparison
![image](https://user-images.githubusercontent.com/18568364/85695077-48f82780-b70a-11ea-87ad-8a35b4ffebf3.png)
