### ISSUE TITLE
how to make a fairseq based server just like tf-serving

### ISSUE THREAD

**Issue by naginoa** [pytorch/fairseq#2239]
Hi, I have some trouble when I finished my fairseq-based translation baseline. The trouble is that how to how to make a fairseq based server just like tf-serving. My target task is to offer a web translation service. Thanks!

**Comment by Bachstelze** [comment]
We could build a service based on other interfaces like:
https://github.com/Helsinki-NLP/OPUS-MT
https://github.com/ymoslem/OpenNMT-GUI

**Comment by mohammedayub44** [comment]
Did anyone happen to try [Torchserve](https://pytorch.org/serve/) ?
