### ISSUE TITLE
How to set batch size when fine-tunning BART?

### ISSUE THREAD

**Issue by JJJJane** [pytorch/fairseq#2240]
#### What is your question?
When I fine-tune BART.large on my server, OOM issue occurs. So I intend to reduce batch_size to enable training. So I would like to know how to set batch size when fine-tunning BART. Thanks!!
#### What's your environment?

 - fairseq Version (0.7.2)
 - PyTorch Version (1.5.0)
 - OS (Linux):
 - How you installed fairseq: pip
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration:

**Comment by shamanez** [comment]
You have to change the **--max-tokens** parameter.  Basically, it says the number of maximum tokens that can consist of a batch of training data. The default is 2048. 

But remember that, BART has dynamic batching, which means it can select examples of different sequence lengths.

**Comment by JJJJane** [comment]
Okay, Thanks!
