### ISSUE TITLE
BART: why BART doesn't use a BOS (binning of the sentence ) token in the training phase?

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#2244]
I am going through the code of the BART, I found that there is no BOS token for the input. What if I train with BOS token appended?

**Comment by alexeib** [comment]
please try and report back!

**Comment by shamanez** [comment]
Hi, I finetuned BART with CNN daily mail by appending the BOS token and it works fine. This allows us to explore and compare the encoder sequence representation with decoder seqence representation.

**Comment by Junpliu** [comment]
> Hi, I finetuned BART with CNN daily mail by appending the BOS token and it works fine. Thanks a lot.

Hi, when I reading here( https://github.com/pytorch/fairseq/blob/master/fairseq/data/language_pair_dataset.py#L336 ), I can't figure out the original proper way to add "bos" and "eos" when inputing into encoder/docoder, what I think is as follows:

source:   This is an example of source. </s>
target:    This is an example of target. </s>

That is, at this line of code, we only need to keep eos existing. Am I right? Thanks!
