### ISSUE TITLE
Any performance comparison between pre-norm and post-norm for Transformer on Machine Translation

### ISSUE THREAD

**Issue by gaopengcuhk** [pytorch/fairseq#2246]
As the name implies, can you provide any performance comparison between pre-norm and post-norm performance comparison using a transformer on Machine Translation Dataset?

**Comment by Bachstelze** [comment]
What is the pre-norm and post-norm?

**Comment by SunbowLiu** [comment]
> As the name implies, can you provide any performance comparison between pre-norm and post-norm performance comparison using a transformer on Machine Translation Dataset?

You can refer to the ACL2019 paper https://arxiv.org/abs/1906.01787, which is based on fairseq.

**Comment by Bachstelze** [comment]
Have a look at https://github.com/wangqiangneu/dlcl to reproduce the results.
