### ISSUE TITLE
Does anyone reproduce "Convolutional Sequence to Sequence Learning" on WMT'14 ENDE datasets ？

### ISSUE THREAD

**Issue by cocaer** [pytorch/fairseq#225]
Hi.......Does anyone reproduce "Convolutional Sequence to Sequence Learning"  result on WMT'14 ENDE datasets ?Can  training parameters be shared?Thanks in advance.

**Comment by myleott** [comment]
Yes, please follow the README here to reproduce the Convolutional Sequence to Sequence Learning (ICML17) results: https://github.com/pytorch/fairseq/tree/master/examples/translation#prepare-wmt14en2desh
