### ISSUE TITLE
Replace the TransformerEncoder with Pre-trained Roberta Encoder

### ISSUE THREAD

**Issue by allanj** [pytorch/fairseq#2259]
#### What is your question?
After replacing the TransformerEncoder with pre-trained Roberta Encoder, I got this error during generation.  (Training has no error)
```bash
File "/opt/tiger/projects/cloze_test/fairseq/fairseq/sequence_generator.py", line 788, in reorder_encoder_out
    model.encoder.reorder_encoder_out(encoder_outs[i], new_order)
  File "/opt/tiger/projects/cloze_test/fairseq/fairseq/models/fairseq_encoder.py", line 75, in reorder_encoder_out
    raise NotImplementedError
```
I think the RobertaEncoder does not implement the `reorder_encoder_out` function. Is it a bug or something that I can set to ignore?
#### Code

   

Here is how I do to replace the transformer encoder.  Basically, I did some revision to the [transformer](https://github.com/pytorch/fairseq/blob/master/fairseq/models/transformer.py) example in `fariseq/models/transforme.py`. 

I replace the `build_encoder` function with code below:
```python
@classmethod
    def build_encoder(cls, args, src_dict, embed_tokens):
        roberta = RobertaModel.from_pretrained('fairseq_models/roberta.base', checkpoint_file='model.pt')
        cls.padding_idx = roberta.model.encoder.dictionary.pad()
        return roberta.model.encoder
        # return TransformerEncoder(args, src_dict, embed_tokens)
```
The forward function is replaced as:
```python
def forward(...):
>>>> ORIGINAL CODE
    # encoder_out = self.encoder(
    #     src_tokens, src_lengths=src_lengths, return_all_hiddens=return_all_hiddens
    # )
<<<<< REPLACED CODE BELOW
    x, _ = self.encoder.extract_features(src_tokens)
    encoder_padding_mask = src_tokens.eq(self.padding_idx)
    encoder_out = EncoderOut(encoder_out=x.permute(1, 0, 2), encoder_padding_mask=encoder_padding_mask)
```
That's all I change.

#### What have you tried?
Currently thinking to add a reorder function, but not sure if that's the correct way to do so.
This is the only issue I can find: https://github.com/pytorch/fairseq/issues/1277 But I don't understand how exactly they do that.

#### What's your environment?

 - fairseq Version: master
 - PyTorch Version: 1.5.0
 - OS : Ubuntu
 - How you installed fairseq (source): pip install --editable .
 - Python version: 3.6.10
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: V100

**Comment by smile0925** [comment]
Hi! 
I want to know that if you  finally achieve it successfully. I recently wanted to use RoBERTA as an encoder and decoder for sequence generation tasks. I would be very appreciated if you could tell me how you replace the TransformerEncoder with Pre-trained Roberta Encoder.

**Comment by allanj** [comment]
I switch to use the HuggingFace library and it seems easier for me.
I managed to use BART or encoder-decoder framework in the HuggingFace transformers library.

**Comment by smile0925** [comment]
Thanks for your your suggestions, I will try to use  encoder-decoder framework in the HuggingFace transformers library.
