### ISSUE TITLE
[XLM-R] How to find Hausa in CC-100

### ISSUE THREAD

**Issue by donglixp** [pytorch/fairseq#2262]
#### What is your question?

Thanks for your contribution to the community. I am wondering whether the ccnet contains the `Hausa` language (ISO id: ha/hau)? Because in [the xlm-r paper](https://arxiv.org/pdf/1911.02116.pdf), Table 6 mentioned that Hausa was included in CC-100. However, I didn't find the language code of `Hausa` (ISO id: ha/hau) in the dumped files of [CCNet](https://github.com/facebookresearch/cc_net).  @ngoyal2707

**Comment by lematt1991** [comment]
This is really more of an issue with the `cc_net` repo, but did you try installing and running `python -m cc_net mine -l ha`?

**Comment by donglixp** [comment]
@lematt1991  Thanks! The issue has been resolved in the CCNet repo. https://github.com/facebookresearch/cc_net/issues/9
