### ISSUE TITLE
Logging Losses for Loss Curves

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [pytorch/fairseq#227]
Is there any convenient way to currently get loss curves after training a fairseq model? The default logging output of tqdm isn't the most convenient to extract from and while the json output you can make loss curves from isn't written to any file. I know I could do output redirection, but since other things also get printed to screen you still wouldn't get a simple json file.

If there isn't an easy way I'm not noticing, I was thinking of adding an option to put the logs in a file and then just add a small visualization script that reads from a log file and then generates loss curves. Would that be wanted as a pull request?

**Comment by alexeib** [comment]
sure, that would be nice. another idea we have been thinking about (but haven't gotten to yet) is integration with tensorboard and/or visdom

**Comment by myleott** [comment]
I usually do `--log-format json`, redirect to a file, and then when I want plain json do `grep "^{" train.log`. If you want just training output (no validation) then you can do: `grep "^{" train.log | grep -v valid`.

I generally avoid having options that write output to files -- it's too easy for this kind of output to get separated from the main log output, which contains important debug info, such as the args that the script was run with. It's also usually redundant and complicates the code :/

**Comment by hmc-cs-mdrissi** [comment]
Grepping that way is simple enough to cover my need, so I have less desire to actually tweak the logging code to write to files unless someone else wants it.

**Comment by noe** [comment]
With the addition of the `--user-dir` flag, now it's easy to implement a _plugin_ that does so. I just did that: https://github.com/noe/fairseq-tensorboard

**Comment by myleott** [comment]
This is awesome! We're working on a major refactoring of logging currently, with the aim of adding more native tensorboard support and simplifying the various logging code scattered throughout the code, but your solution is a really clean way of doing this in the interim :)
