### ISSUE TITLE
Roberta: Outputs after BPE encoding step and Pre-processing (Binarize) steps

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#2278]
In the fine-tuning steps of Roberta and BART, we first encode raw text into tokens using **roberta.multiprocessing_bpe_encoder**. Then we run **fairseq-preprocess** to binarize the data. Finally, we feed the tokens to the model using the binarized file in the training process. 

But, when I check the tokens I get for a given sentence using BPE encoding and binarized files are not similar to each other. Why is that?

**Comment by lematt1991** [comment]
Can you post some examples of the inconsistencies?  Thanks!

**Comment by shamanez** [comment]
Hi @lematt1991 ,

Thank you for your help.  Please go through the following example to understand the issue.


**The input Sentence** 

"What?!?? Why are people saying this is "mind blowing?" Just face it the ending is on of the worst endings in the history of cinematography! 4 left and the whole world has ended! Not to mention the character 9 was a idiot the whole time he got everyone killed. 1 was right the whole time, if he sacrificed 9 then non of this would have happened. People giving there lives for a stupid cause and for what?... to make it rain? I admit the movie had it's parts, and the whole concept was fascinating. But a lot of it was clichés one after another. And did anybody else get this feeling that this is a lot like "Lord of The Rings?" Characters died for stupid reasons, there was almost no character development, and honestly ask yourself is it good to have only four guys left in the world; its pointless and stupid. It was one of the shortest movies I've ever seen, and thank god! How is robots turning against humans creative in any way! It's been done like a hundred times! This movie is really stupid, go see a movie that's worth watching like Star Trek, The Hangover, or Inglorious Basterds, those were good movies!"


**Tokens I get after running  examples.roberta.multiprocessing_bpe_encoder**

'2061 12248 3548 4162 389 661 2282 428 318 366 10155 19280 1701 2329 1986 340 262 7464 318 319 286 262 5290 38168 287 262 2106 286 13483 45501 0 604 1364 290 262 2187 995 468 4444 0 1892 284 3068 262 2095 860 373 257 22324 262 2187 640 339 1392 2506 2923 13 352 373 826 262 2187 640 11 611 339 27445 860 788 1729 286 428 561 423 3022 13 4380 3501 612 3160 329 257 8531 2728 290 329 644 30 986 284 787 340 6290 30 314 9159 262 3807 550 340 338 3354 11 290 262 2187 3721 373 13899 13 887 257 1256 286 340 373 35478 20954 530 706 1194 13 843 750 9599 2073 651 428 4203 326 428 318 257 1256 588 366 22438 286 383 26028 1701 26813 3724 329 8531 3840 11 612 373 2048 645 2095 2478 11 290 12698 1265 3511 318 340 922 284 423 691 1440 3730 1364 287 262 995 26 663 27158 290 8531 13 632 373 530 286 262 35581 6918 314 1053 1683 1775 11 290 5875 5770 0 1374 318 14193 6225 1028 5384 7325 287 597 835 0 632 338 587 1760 588 257 3470 1661 0 770 3807 318 1107 8531 11 467 766 257 3807 326 338 2861 4964 588 2907 12338 11 383 24300 2502 11 393 17589 4685 699 347 1603 9310 11 883 547 922 6918 0'

**The output I get in the training phase (after fairseq-preprocess )**

**After  print(sample['net_input']['src_tokens'])**

tensor([[    0,  2264, 17516, 28749,  2612,    32,    82,   584,    42,    16,
            22, 28583, 13897,  1917,  1801,   652,    24,     5,  3558,    16,
            15,     9,     5,  2373, 41677,    11,     5,   750,     9, 18535,
         34226,   328,   204,   314,     8,     5,  1086,   232,    34,  1249,
           328,  1491,     7,  4521,     5,  2048,   361,    21,    10, 30603,
             5,  1086,    86,    37,   300,   961,   848,     4,   112,    21,
           235,     5,  1086,    86,     6,   114,    37, 26936,   361,   172,
           786,     9,    42,    74,    33,  1102,     4,  1806,  1311,    89,
          1074,    13,    10, 12103,  1303,     8,    13,    99,   116,   734,
             7,   146,    24,  1895,   116,    38,  8109,     5,  1569,    56,
            24,    18,  1667,     6,     8,     5,  1086,  4286,    21, 12509,
             4,   125,    10,   319,     9,    24,    21, 43848,  5739,    65,
            71,   277,     4,   178,   222,  5670,  1493,   120,    42,  2157,
            14,    42,    16,    10,   319,   101,    22, 37565,     9,    20,
         32106,  1917, 44217,   962,    13, 12103,  2188,     6,    89,    21,
           818,   117,  2048,   709,     6,     8, 10728,  1394,  2512,    16,
            24,   205,     7,    33,   129,   237,  1669,   314,    11,     5,
           232,   131,    63, 31321,     8, 12103,     4,    85,    21,    65,
             9,     5, 28617,  4133,    38,   348,   655,   450,     6,     8,
          3392,  9069,   328,  1336,    16, 12129,  3408,   136,  5868,  3904,
            11,   143,   169,   328,    85,    18,    57,   626,   101,    10,
          6317,   498,   328,   152,  1569,    16,   269, 12103,     6,   213,
           192,    10,  1569,    14,    18,   966,  2494,   101,  2141, 20351,
             6,    20, 12403,  2137,     6,    50, 11996, 10159,  6514,   163,
          8831, 11622,     6,   167,    58,   205,  4133,   328,     2]],
       device='cuda:0')


So does fairseq-preprocess again assign tokens to its own dictionary?
