### ISSUE TITLE
Is there any suggestion to visualize the RoBERTa? It might be much helpful to understand what's going on inside the model.

### ISSUE THREAD

**Issue by 14H034160212** [pytorch/fairseq#2281]
## ❓ Questions and Help

Is there any suggestion to visualize the RoBERTa? It might be much helpful to understand what's going on inside the model.

I have used RoBERTa in my text classification problem by using the script from fairseq (https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.custom_classification.md), but I am curious about what's going on inside the RoBERTa. For example, how attention works inside the model? Any suggestion or visualization tool to help to understand the model will be much appreciated.

Thank you so much.

**Comment by 14H034160212** [comment]
I think I have found a great tool to visualize the RoBERTa (https://github.com/jessevig/bertviz/blob/master/head_view_roberta.ipynb). If you have any other recommendation, please leave the link. Many thanks.

**Comment by lematt1991** [comment]
You could also take a look at https://github.com/facebookresearch/vizseq

**Comment by 14H034160212** [comment]
> You could also take a look at https://github.com/facebookresearch/vizseq

Thank you so much. Another great work about the analysis of BERT's attention is from this paper.
Paper: https://arxiv.org/pdf/1906.04341.pdf
Code: https://github.com/clarkkev/attention-analysis
