### ISSUE TITLE
Does fairseq support other pre-training language models like BERT, GPT, ELMO?

### ISSUE THREAD

**Issue by 14H034160212** [pytorch/fairseq#2282]
## ❓ Questions and Help

Does fairseq support other pre-training language models like BERT, GPT, ELMO?

Thank you so much.

**Comment by lematt1991** [comment]
Is there a particular model you're looking for?  There are other language models, ex: roberta, xlmr, bart, mbart, etc.

**Comment by 14H034160212** [comment]
Yes, does any format required for the model? Like in the official example, the form of roberta model is model.pt. So, if I want to use BERT or ELMO, shall I transfer the model firstly to the "model.pt" format and then run the script? Thank you so much.

**Comment by 14H034160212** [comment]
> Is there a particular model you're looking for? There are other language models, ex: roberta, xlmr, bart, mbart, etc.

Yes, does any format required for the model? Like in the official example, the form of roberta model is like model.pt. So, if I want to use BERT or ELMO, shall I transfer the model firstly to the "model.pt" format and then run the script? Thank you so much.

**Comment by myleott** [comment]
Please take a look at the examples here: https://github.com/pytorch/fairseq/tree/master/examples

We don't have ELMo implemented, RoBERTa is similar to BERT, and you can train GPT-like models following the instructions here: https://github.com/pytorch/fairseq/tree/master/examples/language_model

**Comment by 14H034160212** [comment]
> Please take a look at the examples here: https://github.com/pytorch/fairseq/tree/master/examples
> 
> We don't have ELMo implemented, RoBERTa is similar to BERT, and you can train GPT-like models following the instructions here: https://github.com/pytorch/fairseq/tree/master/examples/language_model

Thanks for your comment!
