### ISSUE TITLE
UnicodeEncodeError with fairseq-generate on Devanagari characters

### ISSUE THREAD

**Issue by TovlyDeutsch** [pytorch/fairseq#2287]
## 🐛 Bug

A `UnicodeEncodeError` is raised when trying to translate source text with Devanagari (presumably any Unicode) text with `fairseq-generate`. The error is raised [this line](https://github.com/pytorch/fairseq/blob/894ae64858b62927d849c0fbc05e8f55d680a4f1/fairseq_cli/generate.py#L33)  of fairseq_cli/generate.py: `with open(output_path, 'w', buffering=1) as h:`. It can be fixed by just adding a `encoding = 'utf-8'` to the `open` call. The PR #460 addressed this issue for a bunch of other call sites of `open`, but not this one (perhaps it didn't exist at the time). That PR also mentions inconsistencies between platforms, therefore I think this is just an issue on Windows. I'm happy to make a PR if this is the right fix.

### To Reproduce

1. Run "fairseq-generate ..." with a source language that contains Devanagari characters

### Expected behavior

No error is raised.

### Environment

 - fairseq Version: master
 - PyTorch Version: 1.4.0
 - OS: Windows
 - How you installed fairseq : `pip install git+https://github.com/pytorch/fairseq`
 - Python version: 3.6.8
 - CUDA/cuDNN version: 10.2

**Comment by lematt1991** [comment]
Yes, it looks like that line was added after the PR that you mentioned.  Feel free to submit a new PR with a fix.  Thanks!

**Comment by myleott** [comment]
Merged in ffecb4e3496379edf5ecae1483df5b7e0886c264.
