### ISSUE TITLE
Question about how to install libnat correctly on a cpu-only machine

### ISSUE THREAD

**Issue by dmortem** [pytorch/fairseq#2301]
Hi,

I hope to run lev_transformer on a cpu-only machine. After I install libnat on my machine, I met the error of "cannot import name 'libnat_cuda'... fall back to cpu version". How to solve it? Thanks!

**Comment by nomadlx** [comment]
I met to the same problem, and the answer of the same problem in history does not apply to me. 
How did you solve it?
