### ISSUE TITLE
Text Classification with XLM Roberta

### ISSUE THREAD

**Issue by Srj** [pytorch/fairseq#2302]
After extracting last layer features using this line of code 

`last_layer_features = xlmr.extract_features(zh_tokens)`

Will the following line extract feature for text classification? 

`out = last_layer_features[:,0] #out is the feature for text classification that will be passed to a classifier.`

**Comment by lematt1991** [comment]
Yep, that's what the [classification heads](https://github.com/pytorch/fairseq/blob/master/fairseq/models/roberta/model.py#L273) do

**Comment by charlesfufu** [comment]
> Yep, that's what the [classification heads](https://github.com/pytorch/fairseq/blob/master/fairseq/models/roberta/model.py#L273) do

why ''last_layer_features = xlmr.extract_features(zh_tokens)'' just jump to the function of ''fairseq.models.roberta.hub_interface.RobertaHubInterface.extract_features'' ?
what the difference between ''fairseq.models.roberta.model.RobertaEncoder.extract_features'' and ''fairseq.models.roberta.hub_interface.RobertaHubInterface.extract_features'' ?
