### ISSUE TITLE
Add '--truncate-source' flag to 'multilingual_translation' task

### ISSUE THREAD

**Issue by jesgim** [pytorch/fairseq#2307]
It'd be nice to incorporate the '--truncate-source' flag to the 'multilingual_translation' task.

The '--truncate-source' flag already exists in the base 'translation' task.

Not sure why it was not incorporated into the 'multilingual_translation' task, but the change looks pretty straightforward, since the latter borrows the dataset creation method from the former:

from fairseq.tasks.translation import load_langpair_dataset

### Environment

 - fairseq Version: master

**Comment by lematt1991** [comment]
Sounds reasonable to me.  Feel free to submit a PR.
