### ISSUE TITLE
How to fine-tune a pre-trained en-de model on new data?

### ISSUE THREAD

**Issue by krieya** [pytorch/fairseq#2309]
#### What is your question?

I have a pre-trained en-de model (checkpoint) with the architecture `transformer_wmt_en_de`. Now I want to fine-tune it on a new set of parallel data, how should I do it?

Based on my understanding, I should process the new data using the same `srcdict` and `tgtdict` as in the pre-trained model, use `--restore-file` to load my best checkpoint, and the same architecture `transformer_wmt_en_de` to start train (fine-tune) it, is this the right step? Is there anything I should add additionally? 

Thank you in advance for any response!!

**Comment by myleott** [comment]
That sounds correct. You might also need to add `--reset-dataloader` and optionally use some of the other options here: https://github.com/pytorch/fairseq/blob/master/fairseq/options.py#L468-L475.
