### ISSUE TITLE
error building setup.py

### ISSUE THREAD

**Issue by pranjali97** [pytorch/fairseq#231]
python setup.py build
running build
running build_py
generating /tmp/tmp1mlfw60c/_temporal_convolution_tbc.c
setting the current directory to '/tmp/tmp1mlfw60c'
running build_ext
building '_temporal_convolution_tbc' extension
creating home
creating home/basmatkarpranjali
creating home/basmatkarpranjali/cnn_gec
creating home/basmatkarpranjali/cnn_gec/mlconvgec2018
creating home/basmatkarpranjali/cnn_gec/mlconvgec2018/software
creating home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py
creating home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq
creating home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq/clib
creating home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc
gcc -pthread -B /home/basmatkarpranjali/anaconda3/envs/myenv/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/basmatkarpranjali/anaconda3/envs/myenv/include/python3.6m -c _temporal_convolution_tbc.c -o ./_temporal_convolution_tbc.o -std=c++11
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
gcc -pthread -B /home/basmatkarpranjali/anaconda3/envs/myenv/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/basmatkarpranjali/anaconda3/envs/myenv/include/python3.6m -c /home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp -o ./home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-std=c99’ is valid for C/ObjC but not for C++
/home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp: In function ‘void TemporalConvolutionTBC_forward(const char*, void*, void*, void*, void*)’:
/home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:70:37: error: no matching function for call to ‘addmm_out(int, at::Tensor&, int, at::Tensor&, at::Tensor&, at::Tensor&)’
       at::addmm_out(1, O, 1, I, W, O);
                                     ^
In file included from /home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/ATen.h:13:0,
                 from /home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:12:
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1621:24: note: candidate: at::Tensor& at::addmm_out(at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, at::Scalar, at::Scalar)
 static inline Tensor & addmm_out(Tensor & result, const Tensor & self, const Tensor & mat1, const Tensor & mat2, Scalar beta, Scalar alpha) {
                        ^~~~~~~~~
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1621:24: note:   no known conversion for argument 1 from ‘int’ to ‘at::Tensor&’
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1627:24: note: candidate: at::Tensor& at::addmm_out(at::Tensor&, const at::Tensor&, at::SparseTensor, const at::Tensor&, at::Scalar, at::Scalar)
 static inline Tensor & addmm_out(Tensor & result, const Tensor & self, SparseTensor mat1, const Tensor & mat2, Scalar beta, Scalar alpha) {
                        ^~~~~~~~~
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1627:24: note:   no known conversion for argument 1 from ‘int’ to ‘at::Tensor&’
/home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp: In function ‘void TemporalConvolutionTBC_backward(const char*, void*, void*, void*, void*, void*, void*)’:
/home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:111:52: error: no matching function for call to ‘addmm_out(int, at::Tensor&, int, at::Tensor&, at::Tensor, at::Tensor&)’
       at::addmm_out(1, dI, 1, dO, weight[k].t(), dI);
                                                    ^
In file included from /home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/ATen.h:13:0,
                 from /home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:12:
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1621:24: note: candidate: at::Tensor& at::addmm_out(at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, at::Scalar, at::Scalar)
 static inline Tensor & addmm_out(Tensor & result, const Tensor & self, const Tensor & mat1, const Tensor & mat2, Scalar beta, Scalar alpha) {
                        ^~~~~~~~~
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1621:24: note:   no known conversion for argument 1 from ‘int’ to ‘at::Tensor&’
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1627:24: note: candidate: at::Tensor& at::addmm_out(at::Tensor&, const at::Tensor&, at::SparseTensor, const at::Tensor&, at::Scalar, at::Scalar)
 static inline Tensor & addmm_out(Tensor & result, const Tensor & self, SparseTensor mat1, const Tensor & mat2, Scalar beta, Scalar alpha) {
                        ^~~~~~~~~
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1627:24: note:   no known conversion for argument 1 from ‘int’ to ‘at::Tensor&’
/home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:124:40: error: no matching function for call to ‘addmm_out(int, at::Tensor&, int, at::Tensor&, at::Tensor&, at::Tensor&)’
       at::addmm_out(1, dW, 1, I, dO, dW);
                                        ^
In file included from /home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/ATen.h:13:0,
                 from /home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:12:
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1621:24: note: candidate: at::Tensor& at::addmm_out(at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, at::Scalar, at::Scalar)
 static inline Tensor & addmm_out(Tensor & result, const Tensor & self, const Tensor & mat1, const Tensor & mat2, Scalar beta, Scalar alpha) {
                        ^~~~~~~~~
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1621:24: note:   no known conversion for argument 1 from ‘int’ to ‘at::Tensor&’
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1627:24: note: candidate: at::Tensor& at::addmm_out(at::Tensor&, const at::Tensor&, at::SparseTensor, const at::Tensor&, at::Scalar, at::Scalar)
 static inline Tensor & addmm_out(Tensor & result, const Tensor & self, SparseTensor mat1, const Tensor & mat2, Scalar beta, Scalar alpha) {
                        ^~~~~~~~~
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1627:24: note:   no known conversion for argument 1 from ‘int’ to ‘at::Tensor&’
/home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:129:28: error: no matching function for call to ‘sum_out(at::Tensor&, int, at::Tensor&)’
   at::sum_out(tmp, 0, dBias);
                            ^
In file included from /home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/ATen.h:13:0,
                 from /home/basmatkarpranjali/cnn_gec/mlconvgec2018/software/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:12:
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:3538:24: note: candidate: at::Tensor& at::sum_out(at::Tensor&, const at::Tensor&, int64_t, bool, at::ScalarType)
 static inline Tensor & sum_out(Tensor & result, const Tensor & self, int64_t dim, bool keepdim, ScalarType dtype) {
                        ^~~~~~~
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:3538:24: note:   candidate expects 5 arguments, 3 provided
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:3541:24: note: candidate: at::Tensor& at::sum_out(at::Tensor&, const at::Tensor&, int64_t, bool)
 static inline Tensor & sum_out(Tensor & result, const Tensor & self, int64_t dim, bool keepdim) {
                        ^~~~~~~
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:3541:24: note:   no known conversion for argument 2 from ‘int’ to ‘const at::Tensor&’
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:3544:24: note: candidate: at::Tensor& at::sum_out(at::Tensor&, const at::Tensor&, int64_t, at::ScalarType)
 static inline Tensor & sum_out(Tensor & result, const Tensor & self, int64_t dim, ScalarType dtype) {
                        ^~~~~~~
/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:3544:24: note:   candidate expects 4 arguments, 3 provided
Traceback (most recent call last):
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/setuptools/command/build_ext.py", 
line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/command/build_ext.py", line 533, in bu
ild_extension
    depends=ext.depends)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/unixccompiler.py", line 120, in _compi
le
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    'build_py': build_py_hook,
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/setuptools/__init__.py", line 129,
 in setup
    return distutils.core.setup(**attrs)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    conv_tbc.build()
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line
 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line
 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in
 recompile
    compiler_verbose, debug)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in 
compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/basmatkarpranjali/anaconda3/envs/myenv/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in 
_build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1

**Comment by myleott** [comment]
What version of pytorch are you using? We require >= 0.4.0

**Comment by pranjali97** [comment]
@myleott pytorch version is 0.4.1.
Is there a specific CUDA and GCC requirement ?

**Comment by myleott** [comment]
It looks like you're using an old version of fairseq, back when we still had a custom temporal_convolution_tbc.cpp module. This code was removed a while ago: #66. If you update your fairseq then installation should succeed. If not, please reopen this task.
