### ISSUE TITLE
Why fairseq uses sum reduction by default in MLM and sentence_prediction ?

### ISSUE THREAD

**Issue by captainjtx** [pytorch/fairseq#2310]
I noticed that https://github.com/pytorch/fairseq/blob/master/fairseq/criterions/masked_lm.py and https://github.com/pytorch/fairseq/blob/master/fairseq/criterions/sentence_prediction.py used sum reduction by default. Is there a particular reason for doing this ? For example, to favor longer sentence or for loss scaling ? Seems that hugging face uses default in pytorch which is mean reduction.

**Comment by lematt1991** [comment]
The gradients eventually [get divided](https://github.com/pytorch/fairseq/blob/master/fairseq/trainer.py#L490) by the `sample_size`, which in this case is the [number of masked tokens](https://github.com/pytorch/fairseq/blob/master/fairseq/criterions/masked_lm.py#L34).

**Comment by captainjtx** [comment]
Thanks for the clarification, also just found out :)
