### ISSUE TITLE
Possible training of transformer model with model parallelism?

### ISSUE THREAD

**Issue by thies1006** [pytorch/fairseq#2312]
I tried out to train the transformer_lm model with model parallelism and it worked out fine. Is it also possible to run the transformer seq2seq model with model parallelism (code in the same directory fairseq/model_parallel/models)?

**Comment by myleott** [comment]
Yes, it should work, we just don't have an "example" for it. Please try it out and let us know how it goes! :)

**Comment by thies1006** [comment]
Thanks! 

I was a bit unsettled yesterday, because the code seems to lack the block with @register_model_architecture. So I added this block like in the transformer_lm example (using base_architecture instead of base_lm_architecture). I also had to match the vocabulary size with the number of GPUs (has to be divisible). I am running now the translation script from the examples (German-English) adding the relevant options (distributed-world-size, model-parallel-size, memory-efficient-fp16, num-workers). I did not change the criterion. I see the GPUs working and translations from the evaluation step look fine, so I guess it is working. 

Just in case there is something wrong with what I did please comment.
Amazing work guys. :)
