### ISSUE TITLE
Typo in wav2vec example README.md

### ISSUE THREAD

**Issue by zyzisyz** [pytorch/fairseq#2314]
## 📚 wav2vec examples Doc Improvements

hi, 

I find a Documentation typo in `fairseq/examples/wav2vec/README.md` 

the **Prepare training data manifest** command script has an error.

the error command script in [line 35](https://github.com/pytorch/fairseq/blame/master/examples/wav2vec/README.md#L33) is
```
$ python scripts/wav2vec_manifest.py /path/to/waves --dest /manifest/path --ext wav
```

which is different from the command in [line 89](https://github.com/pytorch/fairseq/blame/master/examples/wav2vec/README.md#L89), and `fairseq/scripts/wav2vec_manifest.py` does not exist, so I think the right command should be

```
$ python examples/wav2vec/wav2vec_manifest.py /path/to/waves --dest /manifest/path --ext wav
```

**Comment by myleott** [comment]
Fixed in ffecb4e3496379edf5ecae1483df5b7e0886c264.
