### ISSUE TITLE
Reproduce Levenshtein Transformer's APE result?

### ISSUE THREAD

**Issue by zerocstaker** [pytorch/fairseq#2315]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
Hi I tried to implement the APE task for the Levenshtein Transformer, but I wasn't able to get similar improvement from the do-nothing case. Here is what I did:
1. Create a new dataset class that includes mt.
2. Allow initialization with mt as output during decoding
3. I also tried allowing training from noise-injected mt sentence to pe for finetuning, but doesn't seem to help much.

Using the official data, I got a Do-Nothing score 63.03/24.05 (BLEU/TER).
I then trained a translation model using the 4M dataset, and fine-tuned it on the combined set of 500K and PBMT official dataset (upsampled 10 times). Using the translation model trained on 4M directly (the zero-shot setting), I was able to get 60.44/26.73, which seems to be similar as the result in the paper. However, after fine-tuning, I was only able to get 64.82/24.31, which is only a little gain from the Do-Nothing case instead of 70.1/19.2 described in the paper.
I tried using an autoregressive transformer and able to get 71.57/18.41, and so I suspect there is something wrong with my finetuning steps. How was the finetuning done for Levenshtein transformer? 

#### Code

   

All my changes can be found in my fork of fairseq ([https://github.com/zerocstaker/constrained_ape](https://github.com/zerocstaker/constrained_ape)).

Training pretrain translation:
```
TRAIN_DIR=data/binaries/4M

fairseq-train \
    $TRAIN_DIR \
    --save-dir checkpoints/4M \
    --ddp-backend=no_c10d \
    --task ape_lev \
    --criterion nat_loss \
    --arch levenshtein_transformer \
    --noise random_delete \
    --share-all-embeddings \
    --optimizer adam --adam-betas '(0.9,0.98)' \
    --lr 0.0005 --lr-scheduler inverse_sqrt \
    --min-lr '1e-09' --warmup-updates 10000 \
    --warmup-init-lr '1e-07' --label-smoothing 0.1 \
    --dropout 0.3 --weight-decay 0.01 \
    --decoder-learned-pos \
    --encoder-learned-pos \
    --apply-bert-init \
    --fixed-validation-seed 7 \
    --max-tokens 8000 --update-freq 8 \
    --save-interval-updates 10000 --no-epoch-checkpoints \
    --max-update 300000 --source-lang src --target-lang pe --fp16 \
    --num-workers 16
```

Finetuning code:
```
TRAIN_DIR=data/binaries/500K_PBMT

fairseq-train \
    $TRAIN_DIR \
    --save-dir checkpoints/4M_ft_PBMT_mt \
    --ddp-backend=no_c10d \
    --task ape_lev \
    --criterion nat_loss \
    --arch levenshtein_transformer \
    --noise random_delete \
    --share-all-embeddings \
    --optimizer adam --adam-betas '(0.9,0.98)' \
    --lr 0.0005 --lr-scheduler inverse_sqrt \
    --min-lr '1e-09' --warmup-updates 10000 \
    --warmup-init-lr '1e-07' --label-smoothing 0.1 \
    --dropout 0.3 --weight-decay 0.01 \
    --decoder-learned-pos \
    --encoder-learned-pos \
    --apply-bert-init \
    --fixed-validation-seed 7 \
    --max-tokens 8000 --update-freq 8 \
    --save-interval-updates 10000 --no-epoch-checkpoints \
    --max-update 300000 --source-lang src --target-lang pe --fp16 \
    --num-workers 16 --mt-as-prev-target \
    --restore-file checkpoints/4M/checkpoint_best.pt \
    --reset-lr-scheduler --reset-optimizer --reset-dataloader --reset-meters
```

#### What have you tried?
- Creating new classes that adds the extension
- Compared to an autoregressive model

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version (e.g., 1.0) 0.7.6
 - OS (e.g., Linux): Linux 
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): pip install --editable ./ , then python setup.py build_ext --inplace
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Tesla V100
 - Any other relevant information:

**Comment by myleott** [comment]
@MultiPath

**Comment by nedo0shki** [comment]
@zerocstaker Hi, Have you got an answer to this question? I cannot understand the experiment setting (dataset and prev_target used in each of do-nothing, zero-shot, and fine-tuned) described in the paper.

**Comment by zerocstaker** [comment]
@nedo0shki Hey, I didn't get any response on my question unfortunately. However, I think I can sort of answer your questions as they are related to high-level idea rather than more than the actual implementation.

For APE, do-nothing is the baseline where you do not pass anything into the model and just evaluate your results using the original mt sentence. So given the triplet (src, mt , pe) you just calculate BLEU and TER using mt and pe.

Zero-shot is using the LevT that is trained on MT, where you feed in the _src_ sentence and initialize the _prev_target_ with an empty string and let the decoder to fill up the sentence to hopefully create the target sentence. During evaluation on the APE, what you do is you still feed in _src_, but you initialize the _prev_target_ with _mt_. Essentially, you give the model a head start by giving it a possible output to the sentence already but with some systematic errors the APE model should fix. And so the decoder's task is not to start from an empty string but sort of doing the last couple steps of decoding (assuming after some initial steps the decoder produces the _mt_ sentence).

Fine-tuning is using the MT pre-trained model and then train on the APE task, where during training, you do the thing I was talking about for evaluating in the zero-shot case. You initialize the prev_target with _mt_ and let the model only learn the behavior to fix the given sentence instead of generating from scratch. I am not sure if this is what they are doing really, as there is no code for the ape task. I tried to code it up, but I couldn't get the performance they showed.

**Comment by nedo0shki** [comment]
@zerocstaker Thank you very much for your detailed explanation. One thing that I find different between the learning paradigm described in the paper and your implementation is that you pass a corrupted version of the mt as a prev target to the forward function while in the paper they say that they randomly use one of a corrupted version of the original target (pe in this case) or non-empty y0 which would be mt. In general, I don't see the implementation of using of both adversary and random policies to construct the roll-in policy.
