### ISSUE TITLE
--sentencepiece-vocab flag is actually for sentencepiece model

### ISSUE THREAD

**Issue by TovlyDeutsch** [pytorch/fairseq#2319]
## 📚 --sentencepiece-vocab flag requires a sentencepiece model

The `--sentencepiece-vocab` flag defined in `fairseq/data/encoders/sentencepiece_bpe.py` seems to require a path to a sentencepiece model rather than vocabulary. If you try to load a sentencpiece vocabulary (and presumably anything that isn't a sentencepiece model) you get an error like the one below. Ideally, this flag would be changed to `--sentencepiece-model` but I understand that this would break existing code. Instead, maybe a comment could be added to the file and docs indicating the discrepancy.

### Adding this flag to the docs
I see that the docs [specifying the cli flags ](https://fairseq.readthedocs.io/en/latest/command_line_tools.html)is generated automatically here: https://github.com/pytorch/fairseq/blob/master/docs/command_line_tools.rst. Is there a way to include the arguments added programatically via the `add_args` methods (like in `sentencepiece_bpe.py`) and is this desired?

### Error:
`File "/Users/user/anaconda3/lib/python3.6/site-packages/sentencepiece.py", line 118, in Load
return _sentencepiece.SentencePieceProcessor_Load(self, filename)
RuntimeError: Internal: /Users/travis/build/google/sentencepiece/src/sentencepiece_processor.cc(73) [model_proto->ParseFromArray(serialized.data(), serialized.size())]`

**Comment by myleott** [comment]
Fixed in ffecb4e3496379edf5ecae1483df5b7e0886c264.
