### ISSUE TITLE
Error about plasma: Could not connect to socket

### ISSUE THREAD

**Issue by Miopas** [pytorch/fairseq#2321]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
I am working on training a language model from scratch using Roberta-base. The training data is about 75G, and after loading data for 1 hour, it threw the error `OSError: Could not connect to socket /tmp/tmpxs1wb0fr`. 

#### Code
Here is my experiment setup:
```
TOTAL_UPDATES=845000   # Total number of training steps
WARMUP_UPDATES=42500    # Warmup the learning rate over this many updates
PEAK_LR=0.0007          # Peak learning rate, adjust as needed
TOKENS_PER_SAMPLE=128  # Max sequence length
MAX_POSITIONS=128     # Num. positional embeddings (usually same as above)
MAX_SENTENCES=64      # Number of sequences per batch (batch size)
UPDATE_FREQ=16          # Increase the batch size 16x

DATA_DIR=data-bin/my-data

fairseq-train --fp16 $DATA_DIR \
    --task masked_lm --criterion masked_lm \
    --seed 42 \
    --arch roberta_base --tokens-per-sample $TOKENS_PER_SAMPLE \
    --optimizer adam --adam-betas '(0.9,0.98)' --adam-eps 1e-6 --clip-norm 0.0 \
    --lr-scheduler polynomial_decay --lr $PEAK_LR --warmup-updates $WARMUP_UPDATES --total-num-update $TOTAL_UPDATES \
    --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 \
    --max-sentences $MAX_SENTENCES --update-freq $UPDATE_FREQ \
    --max-update $TOTAL_UPDATES --log-format simple --log-interval 1 \
    --skip-invalid-size-inputs-valid-test \
    --num-workers 60 \
    --sample-break-mode complete \
    --shorten-method truncate
```

#### What have you tried?
I tried the followings:

1) Used a smaller dataset about 630M, and reduced `MAX_SENTENCES` as `2`.  It worked. But when I switched the data to the original one (75g), again the same error happened.

2) Changed the path that connected to plasma client, like `self.path = '/my_abosulut_path/' + self._server_tmp.name`, in the file `fairseq/data/plasma_utils.py`. It didn't work.

3) I also monitored the usage of CPU memory (by `free -h`)and GPU memory (by `nvidia-smi`). None of them was exceeded during the training.

4) I ran the command line instruction `ipcs` during training constantly, but I didn't see any IPC there.

I don't have much experience on IPC programming. I would appreciate it if anyone could suggest other things that I could check.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): `pip install --editable ./`
 - Build command you used (if compiling from source):
 - Python version: 1.5.0+cu101
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Tesla V100, 8x32G
 - Any other relevant information:

**Comment by myleott** [comment]
With Plasma we use shared memory to avoid pickling redundant copies of the dataset. I suspect you're running out of shared memory. Please try some of the suggestions discussed here, particularly the `ulimit -c unlimited` suggestion: https://github.com/ray-project/ray/issues/7932

**Comment by Miopas** [comment]
> With Plasma we use shared memory to avoid pickling redundant copies of the dataset. I suspect you're running out of shared memory. Please try some of the suggestions discussed here, particularly the `ulimit -c unlimited` suggestion: [ray-project/ray#7932](https://github.com/ray-project/ray/issues/7932)

@myleott  Thanks for your response. I tried what you suggested but it didn't work. 

Besides, I added some logs in the code `plasma_utils.py` as the following:
```
    def start_server(self):
        if self.plasma is None or self._server is not None:
            return
        assert self.object_id is None
        assert self.path is None
        self._server_tmp = tempfile.NamedTemporaryFile()
        self.path = self._server_tmp.name
        **logger.info('start plasma sever at path [{}]'.format(self.path))**
        self._server = subprocess.Popen([
            'plasma_store',
            '-m', str(int(1.05 * self.array.nbytes)),
            '-s', self.path,
        ])

    @property
    def client(self):
        if self._client is None:
            assert self.path is not None
            self._client = self.plasma.connect(self.path)
            **logger.info('connect plasma client at path [{}]'.format(self.path))**
        return self._client
```

And when training the model, the log is as below:
```
2020-07-14 17:03:03 | INFO | fairseq.optim.adam | using FusedAdam
2020-07-14 17:03:05 | INFO | fairseq.data.plasma_utils | start plasma sever at path [/tmp/tmpaxdhww7j]
2020-07-14 17:03:09 | INFO | fairseq.data.plasma_utils | connect plasma client at path [/tmp/tmpaxdhww7j]
2020-07-14 17:03:10 | INFO | fairseq.data.plasma_utils | start plasma sever at path [/tmp/tmpuo8vzg9g]
2020-07-14 17:03:14 | INFO | fairseq.data.plasma_utils | connect plasma client at path [/tmp/tmpuo8vzg9g]
2020-07-14 17:03:16 | INFO | fairseq.data.plasma_utils | start plasma sever at path [/tmp/tmpmtgzfses]
2020-07-14 17:03:19 | INFO | fairseq.data.plasma_utils | connect plasma client at path [/tmp/tmpmtgzfses]
```
It seems that it got stuck after connecting to three clients. Do you have any idea about what configuration might be related?

**Comment by myleott** [comment]
Hmm, I'm not sure what's happening. One solution to unblock you is that `$DATA_DIR` can be a colon-separated list of data directories. Each directory will be iterated over as an "epoch", so you can shard you data into 5 data directories and then do:
```bash
fairseq-train --fp16 data-bin/my-data1:data-bin/my-data2:data-bin/my-data3:...
```
This should be more robust.

**Comment by Miopas** [comment]
> Hmm, I'm not sure what's happening. One solution to unblock you is that `$DATA_DIR` can be a colon-separated list of data directories. Each directory will be iterated over as an "epoch", so you can shard you data into 5 data directories and then do:
> 
> ```shell
> fairseq-train --fp16 data-bin/my-data1:data-bin/my-data2:data-bin/my-data3:...
> ```
> 
> This should be more robust.

Sounds good! I will have a try. Since this is not related to the plasma issue anymore, I am gonna close this issue. Thanks for your help!
