### ISSUE TITLE
Convert the pretrained model weight to tensorflow

### ISSUE THREAD

**Issue by wentinghome** [pytorch/fairseq#2322]
### Motivation

Convert the checkpoint weight to TensorFlow. So I can load the model weight directly and fine-tune on TensorFlow model.

### Pitch

Is the model has the same model weight as hugging face BERT structure? Can I use this to convert the weight?
https://github.com/huggingface/transformers/pull/620/files

### Additional context

Thanks.

**Comment by myleott** [comment]
I haven't used that script before, but I have used the [convert_roberta_original_pytorch_checkpoint_to_pytorch.py](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_roberta_original_pytorch_checkpoint_to_pytorch.py) script and it works well to make a fairseq checkpoint compatible with huggingface.

Once it's converted to huggingface format, I expect you can then convert it to tensorflow, but I haven't tried this. Please report back if you try it and it works!

**Comment by usuyama** [comment]
related blog: "Porting fairseq wmt19 translation system to transformers" by @stas00
https://huggingface.co/blog/porting-fsmt

Might be able to convert fairseq BERT weights to huggingface following similar steps.
