### ISSUE TITLE
ROBERTA BASE - TPU v3-8

### ISSUE THREAD

**Issue by Mistobaan** [pytorch/fairseq#2324]
I need some help in training a model on the TPU v3-8 with fairseq:

- I am fine tuning a roberta model on a custom domain vocabulary of 2**16 elements.
- I am using the pytorch-nightly version

The script I am using is:
```
TOTAL_UPDATES=500000    # Total number of training steps
WARMUP_UPDATES=24000    # Warmup the learning rate over this many updates
PEAK_LR=0.0006          # Peak learning rate, adjust as needed
TOKENS_PER_SAMPLE=512   # Max sequence length
UPDATE_FREQ=16           # Increase the batch size 16x (total in device)
MAX_SENTENCES=16        # Number of sequences per batch (batch size) (16 * 8) (how many per device)

export TPU_NAME=fabrizio-vs-roberta-us-central1-a-tpu-v3-8

python training/scripts/xla_dist.py \
  --tpu=$TPU_NAME \
  --conda-env=torch-xla-nightly \
  --vm fabrizio-vs-roberta-us-central1-a-n1-standard-32-torch-xla \
  --env TOKENIZERS_PARALLELISM=$TOKENIZERS_PARALLELISM \
  -- \
  python $HOME/fairseq/train.py \
    ${BINARY_DATA_DIR} \
    --save-interval=1 \
    --task masked_lm \
    --criterion masked_lm \
    --arch=roberta_base \
    --sample-break-mode complete \
    --tokens-per-sample $TOKENS_PER_SAMPLE \
    --optimizer adam \
    --adam-betas '(0.9,0.98)' \
    --adam-eps 1e-6 \
    --clip-norm 0.0 \
    --lr-scheduler polynomial_decay \
    --lr $PEAK_LR \
    --warmup-updates $WARMUP_UPDATES \
    --total-num-update $TOTAL_UPDATES \
    --dropout 0.1 \
    --attention-dropout 0.1 \
    --weight-decay 0.01 \
    --update-freq $UPDATE_FREQ \
    --max-sentences $MAX_SENTENCES \
    --max-update $TOTAL_UPDATES \
    --log-format tqdm \
    --num-workers 32 \
    --distributed-world-size 8 \
    --tpu 
```

I had to change the xla_dist to make it run:
```
      xrt_server_config = [
          'tpu_worker;{worker_idx};{worker_ip}:{worker_port}'.format(
              worker_idx=idx,
              worker_ip=service_worker.get_internal_ip(),
              worker_port=service_worker.get_port()) for idx, service_worker in
```
changed `c_tpu_worker` to `tpu_worker`. 

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
master
 - PyTorch Version (e.g., 1.0)
'1.7.0a0+4b4184f'

# Questions:
- Is this the right approach to train a custom model?
- is there any way to introspect the system? i.e. using https://cloud.google.com/tpu/docs/cloud-tpu-tools?
- UPDATE_FREQ and MAX_SENTENCES is very confusing. Is MAX_SENTENCE the amount of BPE tokens sent to a single core in the TPU? In Roberta's paper's they mention 8k batch size. How do you achieve that? (with a 32k vocab as original)

![image](https://user-images.githubusercontent.com/112599/87341776-0488cc00-c4ff-11ea-9cf0-5f5d00003afa.png)

**Comment by myleott** [comment]
We are still working on adding proper documentation for TPU support, but generally TPUs struggle with dynamic shapes, so you may want to set `--sample-break-mode=none`, which will use full blocks of 512 tokens.

> UPDATE_FREQ and MAX_SENTENCES is very confusing. Is MAX_SENTENCE the amount of BPE tokens sent to a single core in the TPU? In Roberta's paper's they mention 8k batch size. How do you achieve that? (with a 32k vocab as original)

There's a few things:
- The context length (typically 512 tokens for BERT/RoBERTa) is controlled by `--tokens-per-sample`.
- Then there's the batch size per device, i.e., how many tokens you have per TPU core. If you set `--max-sentences=8`, then you'll have 8 "sentences" per TPU core, where each "sentence" is a block of 512 tokens. You can instead set `--max-tokens=4096`, which would be equivalent.
- Finally there's the total batch size across all devices. This is typically `num_devices * max_sentences * update_freq`. In the RoBERTa paper we used a total batch size of 8192 sentences. If you're training on a v3-256 (i.e., 256 devices) with `--max-sentences=8`, then you'd have a total batch size of 2048 "sentences". You could then simulate the 8K batch size by setting `--update-freq=4`, which would accumulate 4 batches per TPU core before doing each update, giving a total batch size of 8192.
