### ISSUE TITLE
Tree MT models

### ISSUE THREAD

**Issue by JustCunn** [pytorch/fairseq#2326]
Hi,

I am researching into a NMT model where the source language is parsed to a constituency/dependency tree. Of course, I can't just feed a normal model my trees and expect it to know how to handle them. I've tried researching into how to construct such a model that can take in trees and generate a string output in the target language, but unfortunately I'm learning all this myself, so I don't have access to all NMT resources and knowledge. After reading papers and books I am still left confused?

I just wanted to ask here to see if there was such support for a tree model on Fairseq? If not, if anyone had any resources about it so I could help in developing such a model for Fairseq it would be much appreciated.

Regards,
Justin

**Comment by roeeaharoni** [comment]
You can try to linearize the trees into strings, e.g.
https://www.aclweb.org/anthology/P17-2021/

**Comment by JustCunn** [comment]
Thanks very much for that, looks promising and will definitely try it out!
