### ISSUE TITLE
Document missing?

### ISSUE THREAD

**Issue by butsugiri** [pytorch/fairseq#2330]
## 📚 Documentation

It seems that some documents are missing from the Web: https://fairseq.readthedocs.io/en/latest/command_line_tools.html
![image](https://user-images.githubusercontent.com/6701836/87521519-73ad1e80-c6bf-11ea-8bce-294dfd1ad9e3.png)

Is this change intentional?

**Comment by myleott** [comment]
Thanks for reporting, it's fixed now :)

**Comment by butsugiri** [comment]
Thank you for quick fix 👍
