### ISSUE TITLE
Could your add an input parameter to the lr_scheduler.reduce_lr_on_plateau?

### ISSUE THREAD

**Issue by mp5088643** [pytorch/fairseq#2337]
## 🚀 Feature Request
Add an input parameter patience in this package

### Motivation

torch.optim.lr_scheduler.ReduceLROnPlateau has a parameter patience. Sometimes it may be necessary for training.  It is troublesome to directly modify the source code, hoping to provide a way to input  this arg.

**Comment by myleott** [comment]
Added in 8fdf0800daf80b767dac5f6e17822d55edfc5395
