### ISSUE TITLE
BART : Is there a tutorial for pre-training BART on your own dataset ?

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#2344]
Thanks!

**Comment by orena1** [comment]
@myleott ? thanks

**Comment by jasonwu0731** [comment]
Same question here. Appreciate if there is a guide.

**Comment by tomsherborne** [comment]
@shamanez @jasonwu0731 I can't confirm everything that I am trying is 100% correct but I think I've pieced together a procedure for retraining BART on a new dataset. The data processing mostly comes from [here](https://github.com/pytorch/fairseq/blob/master/examples/bart/README.summarization.md). I made Gists for [preprocessing](https://gist.github.com/tomsherborne/ab1a5a28f9d843cf633d6f7843e96a63) and [training](https://gist.github.com/tomsherborne/ab1a5a28f9d843cf633d6f7843e96a63). Let me know if this is helpful or if you have improvements!

**Comment by PrettyPrettyMeng** [comment]
Same problem here. It would be great if there is one.

**Comment by shamanez** [comment]
@tomsherborne  Amazing! Actually I also have taken initial steps. But still, I am not sure about in what percentage that we need to use different pretext denoising tasks.

Let's do this!

**Comment by shamanez** [comment]
@tomsherborne  

can you please share the script for denoising task.

I am thinking of adding the denoising part in the data loading step.


Similar to token making in [RoBERTa script](https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/masked_lm.py#L132).

**Comment by shamanez** [comment]
yeah, it would be vert useful.
