### ISSUE TITLE
is fix_lua_indexing related to lua?

### ISSUE THREAD

**Issue by xu-song** [pytorch/fairseq#2345]
## 📚 Documentation

Is the parameter `fix_lua_indexing` designed for `lua`?

I didn't see the connection with lua, although it may be initially created for lua TorchNet.

https://github.com/pytorch/fairseq/blob/698e3b91ffa832c286c48035bdff78238b0de8ae/fairseq/data/indexed_dataset.py#L110-L117

**Comment by myleott** [comment]
Yes, it's a legacy data format relating to the [original Lua version of fairseq](https://github.com/facebookresearch/fairseq), which used 1-based indexing. The flag adjusts it to work in the PyTorch version of fairseq, which uses 0-based indexing.
