### ISSUE TITLE
Need help on training the data for machine translation.

### ISSUE THREAD

**Issue by nag0811** [pytorch/fairseq#2346]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
I am little new to this area. Can you please guide me to train the model using our data? I wanted to perform machine translation. For this I have my own data both input and target. Please guide me with an example if possible w. Will I be able to perform speach recognisation using fairseq?

Thanks
Nagaraju
#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
I recommend following the instructions here first: https://github.com/pytorch/fairseq/tree/master/examples/translation#iwslt14-german-to-english-transformer.

After you have reproduced the IWSLT de-en translation results, it should be easier to replace the data with your own data and train a new system.
