### ISSUE TITLE
Loading model parallel Megatron weights for fine-tuning

### ISSUE THREAD

**Issue by rakeshchada** [pytorch/fairseq#2351]
#### What is your question?
Hello. Is there a way to load weights of a model that was trained in model parallel fashion? (eg:- loading Megatron weights that are provided [here](https://github.com/pytorch/fairseq/tree/master/examples/megatron_11b)). The weights are split across 8 parts. Hence, the regular way of providing "--restore_file" argument doesn't work. The use-case here is to fine-tune the model.

#### What have you tried?
I've tried modifying the checkpoint loading code a bit to load each part's weights separately on each GPU but that creates a different exception as now some of the parameter shapes start to differ. The original Megatron-LM does provide [a script to merge partitions](https://github.com/NVIDIA/Megatron-LM/blob/master/tools/merge_mp_partitions.py) to a single model file. But this merging might make sense to do for evaluation but not for fine-tuning.

So, any pointers on how to load megatron model parallel weights for fine-tuning are appreciated. Thank you.

**Comment by ngoyal2707** [comment]
the `--restore-file` should still work as we add suffix here: https://github.com/pytorch/fairseq/blob/master/fairseq/checkpoint_utils.py#L126

I might have only tested it for continued pretraining (and not finetuning, although they are almost same thing). can you please try naming the checkpoint as `checkpoint_last-model_part-x.pt`? Let me know how it goes.

**Comment by rakeshchada** [comment]
@ngoyal2707 That doesn't seem to work either. I get the same error:
```
-- Process 7 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/fairseq/fairseq/trainer.py", line 257, in load_checkpoint
    state["model"], strict=True, args=self.args
  File "/home/ubuntu/fairseq/fairseq/models/fairseq_model.py", line 93, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ModelParallelTransformerLanguageModel:
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([6400, 3072]) from checkpoint, the shape in current model istorch.Size([29345, 3072]).
        size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([6400, 3072]) from checkpoint, the shape in current model is torch.Size([29345, 3072]).
```

This is the command that I execute:

```
MODEL_PATH=checkpoint_last.pt
fairseq-train $DATA_PATH \
  --restore-file $MODEL_PATH  \
  --save-dir . \
  --distributed-world-size 8  \
  --memory-efficient-fp16 \
  --num-workers 2 \
  --model-parallel-size 8 \
  --criterion vocab_parallel_cross_entropy \
  --task language_modeling \
  --sample-break-mode none \
  --tokens-per-sample 1024 \
  --arch transformer_lm_megatron_11b \
  --share-decoder-input-output-embed \
  --optimizer adam --adam-betas "(0.9, 0.98)" --adam-eps 1e-08 --clip-norm 0.0 \
  --lr-scheduler inverse_sqrt --lr 0.00015 \
  --warmup-updates 3000 --weight-decay 0.01 \
  --dropout 0.1 --attention-dropout 0.1 \
  --max-sentences 2 \
  --max-update 300000;
```
The error is probably indicating that the code's trying to load a "part" of the model's weights into the "full" model definition and hence the parameter mismatch?

**Comment by ngoyal2707** [comment]
Awesome, great job at debugging this.

Yes, I'd definitely appreciate the PR. Feel free to create one and assign me as reviewer.
