### ISSUE TITLE
fairseq-generate not printing score

### ISSUE THREAD

**Issue by FadyEssam** [pytorch/fairseq#2355]
https://github.com/pytorch/fairseq/blob/93f5128509278f425afb6bcf0da574c0af0e0c16/fairseq/bleu.py#L58

I think **.format()** should be added to the return line as the latest sacrebleu.corpus_bleu() now returns an object not a string

**Comment by DhruvaBansal00** [comment]
We are held up because of this as well. When are you planning on pushing this change?
