### ISSUE TITLE
What the subword model is in XLM-R ?

### ISSUE THREAD

**Issue by MGithubGA** [pytorch/fairseq#2359]
Hi,

I am wondering what subword model is used in XLM-R.
In the paper, it writes `using Sentence Piece (Kudo and Richardson, 2018) with a unigram language model`, but the subword model file I downloaded is named as `sentencepiece.bpe.model`.

So what the subword model is actually used in XLM-R? Does the `bpe` shown in the filename mean the subword model is a bee model trained by spm_train?

**Comment by mani-rai** [comment]
XLM-R seems a mess. The code doesn't seems to follow the paper.
