### ISSUE TITLE
Missing Details on Training Data of RoBERTa

### ISSUE THREAD

**Issue by maximilianreimer** [pytorch/fairseq#2364]
Hi, 

I would like to use the RoBERTa as a comparison model for my own. In order to be able to do an apples-to-apples comparison, I would like to replicate exactly the training procedure used for RoBERTa including using the same data and same pre-processing. 

Unfortunately, I couldn't find all the details needed to do that. Could you please provide more details on that or tell me where to find that information? Especially for the Wikipedia Dataset, it is very unclear which dump (Date) and which preprocessing you used. 

Thank you very much!

**Comment by myleott** [comment]
Unfortunately it's almost impossible to reproduce the exact dataset used, because the Books corpus is likely to be very different :/

Re: Wikipedia, I will try to get more details about the dump date/preprocessing steps and share back any info I can.

**Comment by theactiveone** [comment]
- Books corpus: oh bad, but good to know!
- Wikipedia: That would be very great! Thank you very much.

**Comment by myleott** [comment]
For Wikipedia, according to @jingfeidu, we accessed this link from BERT's github page around December 2018: https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2

Re: Books corpus, I wasn't aware huggingface was distributed that, nice :) I just downloaded it. It's a bit bigger than ours (4.4GB vs. 4.2GB), but also seems like it's been lowercased and tokenized.

**Comment by theactiveone** [comment]
Thanks! That's already really helpful. Could provide just a little bit more details and the preprocessing you guys applied to Wikipedia?
