### ISSUE TITLE
A question of GRU aggregator of wav2vec1.0

### ISSUE THREAD

**Issue by zz12375** [pytorch/fairseq#2377]
Hi, team!
I am working on using wav2vec1.0 (fairseq0.9.0 version) to do my speech representation experiments. while, when i was checking the code lines of **fairseq/models/wav2vec.py**, I found it was confusing when **definiting a GRU aggregator**.

#### What is your question?
GRU aggregator is not definited **with batch_first=True**, which is needed as your batch data is organized as shape  [N, ...]， or did I missed something?

Seems the newest branch (**master**) also has this problem.

#### Code
**v0.9.0/fairseq/models/wav2vec.py line: 131**
![image](https://user-images.githubusercontent.com/29814033/88522268-b6101d00-d028-11ea-9579-ff13115077c5.png)

#### My environment

 - fairseq Version 0.9.0
 - PyTorch Version 1.2.0
 - OS Linux
 - Python version: 3.7
 - CUDA/cuDNN version: 10.2

**Comment by alexeib** [comment]
this might be a bug, we don't really use the gru aggregator anymore. thanks for flagging, will fix at some point (also PRs welcome)
