### ISSUE TITLE
size mismatch for encoder.embed_tokens.weight

### ISSUE THREAD

**Issue by dmoham1476** [pytorch/fairseq#238]
I am trying to run translation with the pretrained model - wmt14.en-fr.fconv-py (downloaded from wmt14.v2.en-fr.fconv-py.tar.bz2)

python interactive.py  --path $MODEL_DIR/model.pt $MODEL_DIR  --beam 5 --source-lang fr --target-lang en

I get this error - it seems it is a dimension mismatch with the checkpoint. Is there a different checkpoint I need to use?

RuntimeError: Error(s) in loading state_dict for FConvModel:
        size mismatch for encoder.embed_tokens.weight: copying a param of torch.Size([43807, 768]) from checkpoint, where the shape is torch.Size([43771, 768]) in current model.

**Comment by myleott** [comment]
That pretrained model is for English (source) -> French (target) translation, whereas you've swapped it to use a French source and English target. Please try `--source-lang en --target-lang fr`.

**Comment by dmoham1476** [comment]
Apologize, thank you
