### ISSUE TITLE
Bug about `grad norm`

### ISSUE THREAD

**Issue by xx-zhou16** [pytorch/fairseq#2384]
## 🐛 Bug

Same with issue #1529 and #515. 

### To Reproduce

Same with issue #1529 and #515.

### Expected behavior

As above, training with `--fp16` will cause `FloatingPointError: Minimum loss scale reached (0.0001)`  during some random epoch.     
So I check the code about this.   
In `fairseq/optim/fp16_optimizer.py:133L`,   
https://github.com/pytorch/fairseq/blob/108bb2560b1ec01524ba723bc7c69186875afa0a/fairseq/optim/fp16_optimizer.py#L133-L142
Here the program detects whether `grad_norm` is overflow or not.   
And in `fairseq/utils.py:283L`,   
https://github.com/pytorch/fairseq/blob/108bb2560b1ec01524ba723bc7c69186875afa0a/fairseq/utils.py#L283-L317
Here is how it computes the `grad_norm`.   
Specifically, the `grad_norm` is computed in the following way:  
https://github.com/pytorch/fairseq/blob/108bb2560b1ec01524ba723bc7c69186875afa0a/fairseq/utils.py#L305-L307
It is just the L2-norm of all gradients.    
For example, L2-norm of `[1., 2., 3.]` is just `sqrt(1.**2 + 2.**2 + 3.**2)`,  there is nothing like averaging or takeing the maximum.     
So when my model has a large number of params (in other words, my model is big), it definitely will incur very large `grad_norm`, so it will lead to overflowing every iteration, and then the loss scale will go down every iteration as well. Finally, it will lead to the error shown in issue #1529 and #515 .     
It is weird. Could anyone please explain why using L2-norm?   
I think the correct way to compute `grad_norm` is using L-infinity norm, which is the maximum of the absolute value of all gradients.     

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: CUDA10.1
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
This is the same logic used by default in [PyTorch's `clip_grad_norm_`](https://pytorch.org/docs/master/_modules/torch/nn/utils/clip_grad.html#clip_grad_norm_), but you bring up a good point that for very large models we should consider a different solution (L-infinity norm seems reasonable).
