### ISSUE TITLE
Combine outputs of bidirectional encoder

### ISSUE THREAD

**Issue by tangbinh** [pytorch/fairseq#239]
It seems to me that the `view` method in the following function incorrectly mixes the outputs of different samples in a batch. In other words, I expect that `combine_bidir(outs)[:, 0, :].contiguous().view(-1)` to be exactly the same as `outs[:, 0, :].contiguous().view(-1)`. I tested the function with some random tensors and couldn't confirm it. Please let me know if something is wrong with my reasoning. Thank you.

https://github.com/pytorch/fairseq/blob/f7f2dd01ea141cc3303d6735e0fdcf8402b1557b/fairseq/models/lstm.py#L222-L231

**Comment by myleott** [comment]
Good catch, thank you! I've submitted a fix (#249), if you could please double-check it. I've also launched some training runs with bidir vs. unidir for comparison.
