### ISSUE TITLE
Get current epoch number in the model's forward pass

### ISSUE THREAD

**Issue by LividWo** [pytorch/fairseq#2396]
#### What is your question?

Would it be possible to get current epoch number during model forwarding?
The reason I ask is that I want to freeze part of the model in the first K epoch of training. 

#### Code
I am thinking of achieving the goal as below, the only problem remain is to get the epoch number.
```python
class TransformerEncoder():
  def forward(input):
    if current_epoch < 5:
       with torch.no_grad():
           x=model_operation_1(input)
    else:
        x=model_operation_1(input)
    x2=model_operation_2(x, input)
    return x2
```

#### What have you tried?

I understand that we can get the epoch number during training loops using 'epoch_itr.epoch'. 
But I want to get this number in the model forwarding.

One possible solution is to pass current epoch number as parameters all the way from trainer->criterion->model.
But I am wondering is there any better solutions? So that I don't have to change the input for all models/criterions.

#### What's your environment?

 - fairseq Version:  master
 - PyTorch Version: 1.5

**Comment by FadedCosine** [comment]
So, how did you solve this problem?
