### ISSUE TITLE
fairseq-train: error: unrecognized arguments: --tpu

### ISSUE THREAD

**Issue by vsistla** [pytorch/fairseq#2397]
## 🐛 Bug

When I am running fairseq-train to train a Roberta base model (https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md#1-preprocess-the-data), on cloud TPU using --tpu option it, I get this error. 

### To Reproduce
run this as shell script

script.sh is 
```

TOTAL_UPDATES=125000    # Total number of training steps
WARMUP_UPDATES=10000    # Warmup the learning rate over this many updates
PEAK_LR=0.0005          # Peak learning rate, adjust as needed
TOKENS_PER_SAMPLE=512   # Max sequence length
MAX_POSITIONS=512       # Num. positional embeddings (usually same as above)
MAX_SENTENCES=16        # Number of sequences per batch (batch size)
UPDATE_FREQ=64          # Increase the batch size 16x
MKL_THREADING_LAYER=GNU
DATA_DIR=data-bin/wikitext-103
fairseq-train $DATA_DIR \
    --task masked_lm --criterion masked_lm \
    --arch roberta_base --sample-break-mode complete --tokens-per-sample $TOKENS_PER_SAMPLE \
    --optimizer adam --adam-betas '(0.9,0.98)' --adam-eps 1e-6 --clip-norm 0.0 \
    --lr-scheduler polynomial_decay --lr $PEAK_LR --warmup-updates $WARMUP_UPDATES --total-num-update $TOTAL_UPDATES \
    --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 \
    --max-sentences $MAX_SENTENCES --update-freq $UPDATE_FREQ \
    --max-update $TOTAL_UPDATES --log-format simple --log-interval 1 \
    --valid-subset=valid \
    --train-subset=train \
    --save-dir=${HOME}/checkpoints \
    --max-epoch=1 \
    --num-workers 16 \
    --tpu \
    --skip-invalid-size-inputs-valid-test

```
Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 
`$ sh ./script.sh`

2. See error

fairseq-train: error: unrecognized arguments: --tpu

fairseq documentation - https://fairseq.readthedocs.io/en/latest/command_line_tools.html?highlight=train#fairseq-train clearly lists out --tpu as an option/argument for fairseq-train

### Environment

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
Did you clone the latest fairseq source (master) or are you using the pip release (0.9.0)? TPU support is only available on master currently.

**Comment by vsistla** [comment]
@myleott I have used the pip release - that explains. I will revisit this once again with the master version. Thank you for checking into this.
