### ISSUE TITLE
Constrained Decoding

### ISSUE THREAD

**Issue by patelrajnath** [pytorch/fairseq#241]
Any plans of adding lexically constrained decoding?

**Comment by myleott** [comment]
None that I know of :) Do you mean something like this?: https://arxiv.org/abs/1704.07138

**Comment by patelrajnath** [comment]
yes! a better version of the same is published in this- https://arxiv.org/abs/1804.06609.

**Comment by myleott** [comment]
Ah right, I remember that paper. Let's keep this open in case someone has spare cycles to implement it. Likewise, please feel free to implement and submit a PR.

I have a slightly cleaned-up version of the beam search code that I'll be merging soon that should make it easier to add new search algorithms. For example, we'll be soon adding Diverse Beam Search: https://arxiv.org/abs/1610.02424.

**Comment by nicolabertoldi** [comment]
@patelrajnath, @myleott 
I would be also very interested to a smart implementation of the forced/constrained decoding.

But as a first step, I would like to compute the attention scores between a given sentence pair (input, output), with the final goal of extracting the alignment between the two sentences.

Is there anyone working on this topic?
Or could you please give me any suggestion?

The generation of the alignment given the input and output sentence pair is strictly associated to the training process, right? Is it better to work on the training procedure and extract the attention from them?

**Comment by huihuifan** [comment]
I have recently added generation code that implements a constrained decoding mechanism commonly used in summarization- preventing repetition of a given ngram size. This will be added soon. It could be a starting point for the implementation of "ngrams to include" as described in the above linked papers.

To address alignment- a potential starting point would be to look at sentence simplification models where complex and simple sentences are trained to be aligned. Or perhaps unsupervised NMT.

**Comment by howlinghuffy** [comment]
@myleott @huihuifan have either of your beam search modifications been merged yet? I’m keen to see if I can help accelerate the constrained decoder implementation

**Comment by huihuifan** [comment]
Thanks, we love pull requests. Yes, ngram constraint is here: https://github.com/pytorch/fairseq/blob/master/fairseq/sequence_generator.py#L347

**Comment by myleott** [comment]
Closing in favor of #1536.
