### ISSUE TITLE
Is fairseq supported on windows?

### ISSUE THREAD

**Issue by nag0811** [pytorch/fairseq#2411]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
Is fairseq is supported on Windows 10 now? I would like to use it for machine translations and speech recognition on windows machines.  Please help me out. 

Thanks
Nagaraju
#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux): Windows 10
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
I don't have access to a Windows machine to test with, so am not sure. The github unit tests show some failure on Windows, but I think that's just something related to installation. Please feel free to try it out and let us know how it goes!

**Comment by detrin** [comment]
Wheels for Windows would be still much appreciated
