### ISSUE TITLE
Minimum GPU size for training Roberta

### ISSUE THREAD

**Issue by spacewalk01** [pytorch/fairseq#2415]
I am trying to fine-tune the pre-trained Roberta from fairseq for commonsenseQA data. I am running it on CPU (with 20 cores) but it took almost 12 hours to train the model for one step. If its default training step is 3000 (num of training epochs), then it will take 1500 days to complete the training. So, I decided to use GPU instead but I only have a GPU with 4gb memory and I got out of memory error when I use cuda. My question is what is the recommended(minimum) GPU size for fine-tuning(training) Roberta? And what GPU device would you recommend? Thank you in advance.

**Comment by Ayod-A** [comment]
I'd like to know the requirements as well
