### ISSUE TITLE
Roberta CUDA out of memory + very slow training time

### ISSUE THREAD

**Issue by Skylixia** [pytorch/fairseq#2417]
## ❓ Questions and Help

I am training a Roberta model with the following command:

```
TOTAL_UPDATES=125000    # Total number of training steps
WARMUP_UPDATES=10000    # Warmup the learning rate over this many updates
PEAK_LR=0.0005          # Peak learning rate, adjust as needed
TOKENS_PER_SAMPLE=512   # Max sequence length
MAX_POSITIONS=512       # Num. positional embeddings (usually same as above)
MAX_SENTENCES=8        # Number of sequences per batch (batch size)
UPDATE_FREQ=32          # Increase the batch size 16x

DATA_DIR=/data-bin/data

fairseq-train $DATA_DIR \ #FP32: f16 not supported
    --task masked_lm --criterion masked_lm \
    --arch roberta_base --sample-break-mode complete --tokens-per-sample $TOKENS_PER_SAMPLE \
    --optimizer adam --adam-betas '(0.9,0.98)' --adam-eps 1e-6 --clip-norm 0.0 \
    --lr-scheduler polynomial_decay --lr $PEAK_LR --warmup-updates $WARMUP_UPDATES --total-num-update $TOTAL_UPDATES \
    --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 \
    --max-sentences $MAX_SENTENCES --update-freq $UPDATE_FREQ \
    --max-update $TOTAL_UPDATES --log-format simple --log-interval 1 \
    --mask-whole-words 
```

I have the following CUDA 11.0 environment: 
2020-08-03 12:33:22 | INFO | fairseq.utils | rank   0: capabilities =  3.7  ; total memory = 11.173 GB ; name = Tesla K80                               
2020-08-03 12:33:22 | INFO | fairseq.utils | ***********************CUDA enviroments for all 1 workers***********************
2020-08-03 12:33:22 | INFO | fairseq_cli.train | training on 1 devices (GPUs/TPUs)

I am training on just 1.9GB data
In 30 min, I only reached epoch 001:   37 / 3729 
Then after some time I have a CUDA out of memory error:

2020-08-03 13:07:27 | WARNING | fairseq.trainer | OOM: Ran out of memory with exception: CUDA out of memory. Tried to allocate 122.00 MiB (GPU 0; 11.17 GiB total capacity; 8.26 GiB already allocated; 64.44 MiB free; 10.74 GiB reserved in total by PyTorch)

What can I do to avoid out of memory issues and complete the training in a reasonable time frame (I would like it to not exceed 1 week) ?

**Comment by batselem** [comment]
same problem: 

2020-08-05 01:00:46 | WARNING | fairseq.trainer | OOM: Ran out of memory with exception: CUDA out of memory. Tried to allocate 198.00 MiB (GPU 0; 10.91 GiB total capacity; 3.91 GiB already allocated; 181.50 MiB free; 3.95 GiB reserved in total by PyTorch)

|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 9            |        cudaMalloc retries: 10        |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |    2814 MB |    4174 MB |  130343 MB |  127528 MB |
|       from large pool |    2712 MB |    4071 MB |  121629 MB |  118916 MB |
|       from small pool |     102 MB |     386 MB |    8713 MB |    8611 MB |
|---------------------------------------------------------------------------|
| Active memory         |    2814 MB |    4174 MB |  130343 MB |  127528 MB |
|       from large pool |    2712 MB |    4071 MB |  121629 MB |  118916 MB |
|       from small pool |     102 MB |     386 MB |    8713 MB |    8611 MB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |    4208 MB |    4210 MB |   30390 MB |   26182 MB |
|       from large pool |    4082 MB |    4082 MB |   28418 MB |   24336 MB |
|       from small pool |     126 MB |     390 MB |    1972 MB |    1846 MB |
|---------------------------------------------------------------------------|
| Non-releasable memory |   23561 KB |  300367 KB |   55550 MB |   55527 MB |
|       from large pool |   19752 KB |  247072 KB |   43987 MB |   43968 MB |
|       from small pool |    3809 KB |   93092 KB |   11562 MB |   11559 MB |
|---------------------------------------------------------------------------|
| Allocations           |    2747    |    3247    |  148219    |  145472    |
|       from large pool |     295    |     443    |   13363    |   13068    |
|       from small pool |    2452    |    2951    |  134856    |  132404    |
|---------------------------------------------------------------------------|
| Active allocs         |    2747    |    3247    |  148219    |  145472    |
|       from large pool |     295    |     443    |   13363    |   13068    |
|       from small pool |    2452    |    2951    |  134856    |  132404    |
|---------------------------------------------------------------------------|
| GPU reserved segments |     266    |     393    |    2296    |    2030    |
|       from large pool |     203    |     203    |    1310    |    1107    |
|       from small pool |      63    |     195    |     986    |     923    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |      19    |     271    |   75393    |   75374    |
|       from large pool |       7    |      38    |    7830    |    7823    |
|       from small pool |      12    |     247    |   67563    |   67551    |
|===========================================================================|

**Comment by monologue1107** [comment]
the same problem
