### ISSUE TITLE
Typo in wav2vec readme

### ISSUE THREAD

**Issue by zhang-jr** [pytorch/fairseq#2418]
Hello,

In **Train a wav2vec model**, the command line should be ``--skip-invalid-size-inputs-valid-test`` not ``---skip-invalid-size-inputs-valid-test``.

Additionally, it suggests applying ``librosa`` instead of ``soundfile`` to support other kinds of wav format.

**Comment by alexeib** [comment]
thanks, i'll look at some point, also PRs welcome!
