### ISSUE TITLE
About beam-search training scheme of paper Seq2Seq Learning as Beam-Search Optimization

### ISSUE THREAD

**Issue by cnrpman** [pytorch/fairseq#242]
I noticed that the model from [_Wiseman and Rush (2016): Sequence-to-Sequence Learning as Beam-Search Optimization_ ](https://arxiv.org/abs/1606.02960) was mentioned in the Readme file and was provided by LSTM configuration `lstm_wiseman_iwslt_de_en`. Is there any implementation for the beam-search training scheme introduced by the paper above in the repo?

**Comment by myleott** [comment]
Unfortunately we only have the LSTM model implemented, not the beam search optimization part. We do have sequence-level training implemented in the classic_seqlevel branch [1], based on this paper [2] where we found it competitive with beam search optimization.

[1] https://github.com/pytorch/fairseq/tree/classic_seqlevel
[2] [Edunov et al. (2018): Classical Structured Prediction Losses for Sequence to Sequence Learning](https://arxiv.org/abs/1711.04956)

**Comment by cnrpman** [comment]
Thank you so much!
