### ISSUE TITLE
Missing libbleu for hub tests 

### ISSUE THREAD

**Issue by ailzhang** [pytorch/fairseq#2425]
We're seeing missing libbleu.so in hub nightly tests. Could someone help take a look? 
https://app.circleci.com/pipelines/github/pytorch/hub/513/workflows/e1425a52-73f0-475a-a74e-1d5f27019e12/jobs/741
Thanks!

**Comment by myleott** [comment]
Fixed by 6f9ed78059f67ce0bbc107f513064a931f551392
