### ISSUE TITLE
Problem with serializing quantized MT model

### ISSUE THREAD

**Issue by jahutwb** [pytorch/fairseq#2439]
Following tips from #1993 and https://github.com/pytorch/fairseq/commit/d0ccc3e02e1a9015d05cade8dfc61896948275c7
I updated PyTorch to 1.6 and I managed to serialize to TorchScript iwslt14 MT model form translation example, and even run it on the device, but I faced with a problem trying to serialize quantized model

```
RuntimeError:
Module 'PQEmbedding' has no attribute 'weight'
(This attribute exists on the Python module, but it's an @property method. @property methods aree file a feature request on Github):
  File "/data/home/j.borkowski/fairseq/fairseq/modules/quantization/pq/modules/qemb.py", line 70
    def forward(self, input):
        return F.embedding(
            input, self.weight, self.padding_idx, self.max_norm,
                   ~~~~~~~~~~~ <--- HERE
            self.norm_type, self.scale_grad_by_freq, self.sparse)
```  

Is there any way to fix that problem, and serialize quantized model?

**Comment by ksopyla** [comment]
@jahutwb can you provide some source sample of how did you serialize the iwslt14 MT model?

**Comment by jahutwb** [comment]
Unfortunately, I do not have access to this code anymore, but in general it looked like
@erip writes in #1993

 ```
 $ cat test.py
 #!/usr/bin/env python
 
 import torch
 
 from fairseq.sequence_generator import SequenceGenerator
 from fairseq.models.transformer import TransformerModel
 from fairseq.data import Dictionary
 
 if __name__ == "__main__":
     tgt_dict = Dictionary.load(open('dict.fr.txt'))
     model = TransformerModel.from_pretrained('.', 'model.pt', '.', bpe='subword_nmt', bpe_vocab='bpecodes')
 
     generator = SequenceGenerator(model.models, tgt_dict)
 
     scripted_gen = torch.jit.script(generator)
     scripted_gen.save('generator.pt')

**Comment by erip** [comment]
To be honest, this seems like a reasonable thing to clean up and add to the `scripts/` directory in a PR.

**Comment by WilliamTambellini** [comment]
@erip  snippet does nt seem to work anymore:
https://github.com/facebookresearch/fairseq/issues/4459
