### ISSUE TITLE
mBART finetuning for custom dataset.

### ISSUE THREAD

**Issue by kr-sundaram** [pytorch/fairseq#2443]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
I would like to finetune mBART pretrained model for machine translation task on DE --> EN parallel dataset, but receiving error while trying to generate translation.
 
#### Code
**1. Pre-processing:**
`!fairseq-preprocess  
--source-lang de_DE   
--target-lang en_XX   
--trainpref '/content/drive/My Drive/mBART/data/train.spm'   
--validpref '/content/drive/My Drive/mBART/data/valid.spm'   
--testpref '/content/drive/My Drive/mBART/data/test.spm'     
--destdir '/content/drive/My Drive/mBART/output'             
--thresholdtgt 0   
--thresholdsrc 0   
--srcdict '/content/drive/My Drive/mBART/data/dict.txt'  
--tgtdict '/content/drive/My Drive/mBART/data/dict.txt'  
--workers 70  `

**2. Finetuning of pre-trained model**
`!fairseq-train '/content/drive/My Drive/mBART/output'   
--encoder-normalize-before --decoder-normalize-before   
--arch mbart_large --layernorm-embedding                
--task translation_from_pretrained_bart                 
--source-lang de --target-lang en               
--criterion label_smoothed_cross_entropy --label-smoothing 0.2   
--optimizer adam --adam-eps 1e-06 --adam-betas '(0.9, 0.98)'     
--lr-scheduler polynomial_decay --lr 3e-05 --min-lr -1 --warmup-updates 2500 --total-num-update 40000  
--dropout 0.3 --attention-dropout 0.1 --weight-decay 0.0         
--max-tokens 1024 --update-freq 2          
--save-interval 1 --save-interval-updates 5000 --keep-interval-updates 10 --no-epoch-checkpoints   
--seed 222 --log-format simple --log-interval 2           
--restore-file '/content/drive/My Drive/mBART/model.pt'   
--reset-optimizer --reset-meters --reset-dataloader --reset-lr-scheduler        
--langs 'ar_AR,cs_CZ,de_DE,en_XX,es_XX,et_EE,fi_FI,fr_XX,gu_IN,hi_IN,it_IT,ja_XX,kk_KZ,ko_KR,lt_LT,lv_LV,my_MM,ne_NP,nl_XX,ro_RO,ru_RU,si_LK,tr_TR,vi_VN,zh_CN'   
--ddp-backend no_c10d`

**3. Translation generation**
`!fairseq-generate '/content/drive/My Drive/mBART/output/'  
--path '/content/drive/My Drive/mBART/model.pt'   
--task translation_from_pretrained_bart           
--gen-subset test      
-t en_XX -s de_DE            
--bpe 'sentencepiece'  
--sentencepiece-model '/content/drive/My Drive/mBART/mbart.cc25/sentence.bpe.model' 
--sacrebleu --remove-bpe 'sentencepiece'  
--max-sentences 32   
--langs de_DE,en_XX`

#### What have you tried?
I tried two ways in order to generate translation.
1. Do the pruning of large pre-trained model in order to trim the model, and then fine-tune the trimmed model with my dataset.  
2. Directly fine-tune the large pre-trained model with my dataset.

**My Issue**
I used the below commands to generate the translated text as i was not sure which is a correct one and received error for all of them. All parameters of these commands are same except `--langs`. Command-a, and b gave the produces same error whether command c gives some more additional information in addition to command a see below for more understanding:

**1. Do pruning and then finetune :**
a. 
> !fairseq-generate '/content/drive/My Drive/mBART/output/'  
> --path '/content/drive/My Drive/mBART/model.pt'   
> --task translation_from_pretrained_bart           
> --gen-subset test      
> -t en -s de            
> --bpe 'sentencepiece'  
> --sentencepiece-model '/content/drive/My Drive/mBART/mbart.cc25/sentence.bpe.model' 
> --sacrebleu --remove-bpe 'sentencepiece'  
> --max-sentences 32   
> --langs ar_AR,cs_CZ,de_DE,en_XX,es_XX,et_EE,fi_FI,fr_XX,gu_IN,hi_IN,it_IT,ja_XX,kk_KZ,ko_KR,lt_LT,lv_LV,my_MM,ne_NP,nl_XX,ro_RO,ru_RU,si_LK,tr_TR,vi_VN,zh_CN > de_en

**Error received**

> `Traceback (most recent call last):
  File "/usr/local/bin/fairseq-generate", line 8, in <module>
    sys.exit(cli_main())
  File "/usr/local/lib/python3.6/dist-packages/fairseq_cli/generate.py", line 281, in cli_main
    main(args)
  File "/usr/local/lib/python3.6/dist-packages/fairseq_cli/generate.py", line 38, in main
    return _main(args, sys.stdout)
  File "/usr/local/lib/python3.6/dist-packages/fairseq_cli/generate.py", line 87, in _main
    suffix=getattr(args, "checkpoint_suffix", ""),
  File "/usr/local/lib/python3.6/dist-packages/fairseq/checkpoint_utils.py", line 192, in load_model_ensemble
    filenames, arg_overrides, task, strict, suffix,
  File "/usr/local/lib/python3.6/dist-packages/fairseq/checkpoint_utils.py", line 213, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, args=args)
  File "/usr/local/lib/python3.6/dist-packages/fairseq/models/fairseq_model.py", line 93, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BARTModel:
	Unexpected key(s) in state_dict: "encoder.layernorm_embedding.weight", "encoder.layernorm_embedding.bias", "decoder.layernorm_embedding.weight", "decoder.layernorm_embedding.bias". `

b. 
`!fairseq-generate '/content/drive/My Drive/mBART/output/'  
--path '/content/drive/My Drive/mBART/model.pt'   
--task translation_from_pretrained_bart           
--gen-subset test      
-t en -s de            
--bpe 'sentencepiece'  
--sentencepiece-model '/content/drive/My Drive/mBART/mbart.cc25/sentence.bpe.model' 
--sacrebleu --remove-bpe 'sentencepiece'  
--max-sentences 32   
--langs ar_AR,cs_CZ,de_DE,en_XX,es_XX,et_EE,fi_FI,fr_XX,gu_IN,hi_IN,it_IT,ja_XX,kk_KZ,ko_KR,lt_LT,lv_LV,my_MM,ne_NP,nl_XX,ro_RO,ru_RU,si_LK,tr_TR,vi_VN,zh_CN`

**Error received same as what i got after executing command-a**

c. 
`!fairseq-generate '/content/drive/My Drive/mBART/output/'  
--path '/content/drive/My Drive/mBART/model.pt'   
--task translation_from_pretrained_bart           
--gen-subset test      
-t en -s de            
--bpe 'sentencepiece'  
--sentencepiece-model '/content/drive/My Drive/mBART/mbart.cc25/sentence.bpe.model' 
--sacrebleu --remove-bpe 'sentencepiece'  
--max-sentences 32   
--langs de_en`

**Error is same as stated for command-a but, this time, with having some has more additional information than what i got after execution of command-a&b.**

```
RuntimeError: Error(s) in loading state_dict for BARTModel:
	Unexpected key(s) in state_dict: "encoder.layernorm_embedding.weight", "encoder.layernorm_embedding.bias", "decoder.layernorm_embedding.weight", "decoder.layernorm_embedding.bias". 
	**size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([23536, 1024]) from checkpoint, the shape in current model is torch.Size([23512, 1024]).
	size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([23536, 1024]) from checkpoint, the shape in current model is torch.Size([23512, 1024]).
	size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([23536, 1024]) from checkpoint, the shape in current model is torch.Size([23512, 1024]).
```

**2. Received the below error when directly tried to generate the translations using pre-trained model without pruning.**
```
RuntimeError: Error(s) in loading state_dict for BARTModel:
	Unexpected key(s) in state_dict: "encoder.layernorm_embedding.weight", "encoder.layernorm_embedding.bias", "decoder.layernorm_embedding.weight", "decoder.layernorm_embedding.bias". 
	size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([250027, 1024]) from checkpoint, the shape in current model is torch.Size([250004, 1024]).
	size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([250027, 1024]) from checkpoint, the shape in current model is torch.Size([250004, 1024]).
	size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([250027, 1024]) from checkpoint, the shape in current model is torch.Size([250004, 1024]).
```

**Can you help me understanding the issue and rectify it and what parameter value should be used for `--langs` for my usecase  to generate translation of test set? 
These errors seems to be confusing, as the size mismatch error is occuring and torch.size differs when we change the `--langs`. Kindly help me out!**

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master) :  Github masters branch
 - PyTorch Version (e.g., 1.0) : 
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by thpun** [comment]
If you are using the pretrained model (without pruning), always use `--langs ar_AR,cs_CZ,de_DE,en_XX,es_XX,et_EE,fi_FI,fr_XX,gu_IN,hi_IN,it_IT,ja_XX,kk_KZ,ko_KR,lt_LT,lv_LV,my_MM,ne_NP,nl_XX,ro_RO,ru_RU,si_LK,tr_TR,vi_VN,zh_CN`, as said in its code (but not in mBART README.)

https://github.com/pytorch/fairseq/blob/0bb7bc3777b880c282df794fb7edb56d7280449b/fairseq/tasks/translation_from_pretrained_bart.py#L42-L47

Given that you pruned the model, if language embeddings are not pruned, just keep specifying all 25 langs in `--langs`. But if you pruned language embeddings, then only specify those not pruned.

And in your command a & b, are you trying to generate translation with pretrained model? Referring to https://github.com/pytorch/fairseq/issues/1758#issuecomment-608968139, the author said "the pretrained model is a de-noising model, it will copy src to tgt, it never learned translation". If insist to run translation on pretrained model, may refer to https://github.com/pytorch/fairseq/issues/1758#issuecomment-611648086 which provides a script to add the missing state keys to the model

**Comment by kr-sundaram** [comment]
Thanks for the help!!

```
!fairseq-generate '/content/drive/My Drive/mBART/output/'  \
--path '/content/drive/My Drive/mBART/mbart.cc25/model.pt'   \
--task translation_from_pretrained_bart           \
--gen-subset test      \
-t en_XX -s de_DE            \
--bpe 'sentencepiece'  \
--sentencepiece-model '/content/drive/My Drive/mBART/mbart.cc25/sentence.bpe.model' \
--sacrebleu --remove-bpe 'sentencepiece'  \
--max-sentences 32   \
--langs de_DE_en_XX
```

**Error received**
```
2020-08-07 10:07:40 | INFO | fairseq.tasks.translation | [de_DE] dictionary: 250027 types
2020-08-07 10:07:40 | INFO | fairseq.tasks.translation | [en_XX] dictionary: 250027 types
2020-08-07 10:07:40 | INFO | fairseq.data.data_utils | loaded 8414 examples from: /content/drive/My Drive/mBART/output/test.de_DE-en_XX.de_DE
2020-08-07 10:07:40 | INFO | fairseq.data.data_utils | loaded 8414 examples from: /content/drive/My Drive/mBART/output/test.de_DE-en_XX.en_XX
2020-08-07 10:07:40 | INFO | fairseq.tasks.translation | /content/drive/My Drive/mBART/output/ test de_DE-en_XX 8414 examples
2020-08-07 10:07:40 | INFO | fairseq_cli.generate | loading model(s) from /content/drive/My Drive/mBART/mbart.cc25/model.pt
2020-08-07 10:09:33 | INFO | fairseq.models.bart.model | Adding extra language embeddings not found in pretrained model for continued pretraining of MBART on new set of languages.
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-generate", line 8, in <module>
    sys.exit(cli_main())
  File "/usr/local/lib/python3.6/dist-packages/fairseq_cli/generate.py", line 281, in cli_main
    main(args)
  File "/usr/local/lib/python3.6/dist-packages/fairseq_cli/generate.py", line 38, in main
    return _main(args, sys.stdout)
  File "/usr/local/lib/python3.6/dist-packages/fairseq_cli/generate.py", line 87, in _main
    suffix=getattr(args, "checkpoint_suffix", ""),
  File "/usr/local/lib/python3.6/dist-packages/fairseq/checkpoint_utils.py", line 192, in load_model_ensemble
    filenames, arg_overrides, task, strict, suffix,
  File "/usr/local/lib/python3.6/dist-packages/fairseq/checkpoint_utils.py", line 213, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, args=args)
  File "/usr/local/lib/python3.6/dist-packages/fairseq/models/fairseq_model.py", line 93, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BARTModel:
	Unexpected key(s) in state_dict: "encoder.layernorm_embedding.weight", "encoder.layernorm_embedding.bias", "decoder.layernorm_embedding.weight", "decoder.layernorm_embedding.bias". 
	size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([250027, 1024]) from checkpoint, the shape in current model is torch.Size([250028, 1024]).
```

I gone through the #1758 and added the language code in dict.txt using below code as suggested there, but still it seems there is one parameter missing.
```
for code in [ar_AR] [cs_CZ] [de_DE] [en_XX] [es_XX] [et_EE] [fi_FI] [fr_XX] [gu_IN] [hi_IN] [it_IT] [ja_XX] [kk_KZ] [ko_KR] [lt_LT] [lv_LV] [my_MM] [ne_NP] [nl_XX] [ro_RO] [ru_RU] [si_LK] [tr_TR] [vi_VN] [zh_CN] "<mask>"; do
    echo "$code 1" >> cc25_pretrain/dict.txt
done
```

when i give `--langs ar_AR,cs_CZ,de_DE,en_XX,es_XX,et_EE,fi_FI,fr_XX,gu_IN,hi_IN,it_IT,ja_XX,kk_KZ,ko_KR,lt_LT,lv_LV,my_MM,ne_NP,nl_XX,ro_RO,ru_RU,si_LK,tr_TR,vi_VN,zh_CN`, it doesn't work at all, i don't know where i am doing wrong.

**Comment by thpun** [comment]
The pretrained model does not have `encoder.layernorm_embedding.weight`, `encoder.layernorm_embedding.bias`, `decoder.layernorm_embedding.weight` and `decoder.layernorm_embedding.bias` in `state_dict`. So you cannot run `fairseq-generate/fairseq-interactive` on it without fine-tuning.

And for the line `size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([250027, 1024]) from checkpoint, the shape in current model is torch.Size([250028, 1024]).`, `shape torch.Size([250027, 1024]) from checkpoint` means it is the size in pretrained model while `shape in current model is torch.Size([250028, 1024])` means the size of model constructed based on the command.
So its more like the model got one more parameter instead of missing.

And i dont think you need to add lang tokens & mask token to dictionary manually coz when loading translation from pretrained bart task, the language tokens and mask token are added to the dictionary during init.
https://github.com/pytorch/fairseq/blob/0bb7bc3777b880c282df794fb7edb56d7280449b/fairseq/tasks/translation_from_pretrained_bart.py#L53-L59

**Comment by kr-sundaram** [comment]
Thanks @thpun!!

With your kind help and support i was able execute `fairseq-generate`, but i am receiving errors for `fairseq-interative`. Below is the command i used to run interactive:

**Fairseq-generate command**
```
LANGS='ar_AR,cs_CZ,de_DE,en_XX,es_XX,et_EE,fi_FI,fr_XX,gu_IN,hi_IN,it_IT,ja_XX,kk_KZ,ko_KR,lt_LT,lv_LV,my_MM,ne_NP,nl_XX,ro_RO,ru_RU,si_LK,tr_TR,vi_VN,zh_CN'

!fairseq-generate '/content/drive/My Drive/mBART/output/' 
--path '/content/drive/My Drive/mBART/model_ckpt/checkpoint_best.pt' 
--task translation_from_pretrained_bart 
--gen-subset test 
-s de_DE 
-t en_XX 
--remove-bpe sentencepiece 
--sacrebleu 
--max-sentences 32 
--langs $LANGS > results
```

**Fairseq-Interactive command**
```
!fairseq-interactive  '/content/drive/My Drive/mBART/output' 
    --path '/content/drive/My Drive/mBART/model_ckpt/checkpoint_best.pt'  
    --beam 5 --source-lang de_DE --target-lang en_XX 
    --bpe sentencepiece --sentencepiece-model '/content/drive/My Drive/mBART/mbart.cc25/sentence.bpe.model'
```

**Error received as below**
```
RuntimeError: Error(s) in loading state_dict for BARTModel:
	size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([22312, 1024]) from checkpoint, the shape in current model is torch.Size([22286, 1024]).
	size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([22312, 1024]) from checkpoint, the shape in current model is torch.Size([22286, 1024]).
	size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([22312, 1024]) from checkpoint, the shape in current model is torch.Size([22286, 1024]).
```


Kindly let mw know if i am doing something wrong.

**Comment by thpun** [comment]
You need to also specify `--task translation_from_pretrained_bart` & `--langs $LANGS` in `fairseq-interactive`.

**Comment by kr-sundaram** [comment]
Thanks! that helped me. :)

I am not able to understand the result file that has been generated after executing fairseq-generate file. could you please help me understanding this. I only got like S --> 'source', T --> 'target', H and D are something related to translation. but dont know why these two are same. **Could you please help me understanding this ? What are these numbers referring to which corresponds to H, D, and P?**

```
S-13810	das ist nicht wenig.[de_DE]
T-13810	that is no small thing.
H-13810	-0.6389964818954468	that is not little.
D-13810	-0.6389964818954468	that is not little.
P-13810	-0.6303 -0.3500 -0.2928 -2.2815 -0.4783 -0.2176 -0.2224
```
