### ISSUE TITLE
Unsafe round in ctc criterion logging

### ISSUE THREAD

**Issue by Squire-tomsk** [pytorch/fairseq#2446]
## 🐛 Bug

This lambda https://github.com/pytorch/fairseq/blob/0bb7bc3777b880c282df794fb7edb56d7280449b/fairseq/criterions/ctc.py#L221 throws `TypeError: type Tensor doesn't define __round__ method` if AverageMeter.sum returns torch.Tensor. 

Replacing `round` to `safe_round` from https://github.com/pytorch/fairseq/blob/0bb7bc3777b880c282df794fb7edb56d7280449b/fairseq/logging/meters.py#L53 solve it.

### To Reproduce

Run

```
python fairseq/train.py 
/data/librispeech/train-clean-100-manifest
--distributed-world-size 2 
--save-dir <path to save dir> --fp16
--post-process letter --valid-subset valid 
--no-epoch-checkpoints 
--best-checkpoint-metric wer --num-workers 12
--max-update 80000 --sentence-avg
--task audio_pretraining --arch wav2vec_ctc 
--w2v-path wav2vec/wav2vec_2_small/wav2vec_small.pt
--labels ltr --apply-mask --mask-selection static
--mask-other 0 --mask-length 10 --mask-prob 0.5 --layerdrop 0.1
--mask-channel-selection static --mask-channel-other 0 
--mask-channel-length 64 --mask-channel-prob 0.5 --zero-infinity
--feature-grad-mult 0.0 --freeze-finetune-updates 10000 
--validate-after-updates 10000 --optimizer adam
--adam-betas '(0.9, 0.98)' --adam-eps 1e-08 --lr 2e-05
--lr-scheduler tri_stage --warmup-steps 8000 --hold-steps 32000
--decay-steps 40000 --final-lr-scale 0.05 --final-dropout 0.0 
--dropout 0.0 --activation-dropout 0.1 --criterion ctc
--attention-dropout 0.0 --max-tokens 1280000 --seed 2337
--log-format json --log-interval 1 --ddp-backend no_c10d
```

### Expected behavior

No `TypeError` in CtcCriterion.reduce_metrics if AverageMeter.sum returns torch.Tensor. 

### Environment

 - fairseq Version: Master
 - PyTorch Version: 1.6.0
 - OS: Linux
 - How you installed fairseq: Source
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration:

**Comment by myleott** [comment]
Fixed in 983163494663e24b611f1ba8d5d47a3edc00e2e5
