### ISSUE TITLE
A mistake in the documentation: 'Tutorial  Simple LSTM'

### ISSUE THREAD

**Issue by elevenofji** [pytorch/fairseq#2449]
the 'lstm' layer in 'SimpleEncoder' should set 'batch_first' True ,right?

**Comment by Huzaib** [comment]
Which file are you talking about?

**Comment by myleott** [comment]
I think you're right, will submit a fix

**Comment by myleott** [comment]
Fixed in 983163494663e24b611f1ba8d5d47a3edc00e2e5
