### ISSUE TITLE
Looking for the best solution to handling CPU memory cost when loading a very large training set

### ISSUE THREAD

**Issue by getao** [pytorch/fairseq#2452]
Hello,

I'm trying to train a model with a very large training set and confronting the cpu memory issue (oom). I checked the previous issues and solutions. They are basically the following 3 ways:

1) lazy load
2) mmap indexed dataset
3) sharding 

I tried lazy load but it looks not so promising to significantly reduce the memory cost; for mmap indexed dataset, it seems that it needs to load all the data first for "warming up". The sharing solution looks the most suitable for our case but I can't find the examples or detailed introduction for the feature in fairseq.

Is my understanding correct? If so, could anyone provide the ways to use the sharding feature in fairseq to facilitate handling large dataset?

Thanks

**Comment by myleott** [comment]
Sharding is the most flexible. You can simply pass a colon-separated list of data-bin paths and each one will be iterated over as a separate "epoch".

So if you do `fairseq-train data-bin1:data-bin2:data-bin3 (...)` then the first epoch will loop over data-bin1, the second epoch over data-bin2, third epoch over data-bin3, fourth epoch over data-bin1 again, etc.
