### ISSUE TITLE
Output of generate for LevT

### ISSUE THREAD

**Issue by aritzzz** [pytorch/fairseq#2453]
``T-368	I think that it should be in the school library because if it is possible, then everyone is happy and adults and children can talk. People want to read “manga” in the library. My friends said to me that “I want to read manga in the library.” Then I thought, “Me too.”
H-368	-2.274385690689087	I think that should should in in in school want want school want want to want want
D-368	-2.274385690689087	I think that should should in in in school want want school want want to want want
P-368	0.0000 -0.1273 -0.2680 -0.7848 -0.8135 -1.5424 -1.8979 -2.3356 -3.4206 -3.0096 -3.2159 -3.0636 -3.6891 -3.1828 -3.5199 -4.2248 -3.9852 -4.1323 0.0000``

How to interpret the results of generate as obtained by LevT. What are H, D, P, and the numbers?

**Comment by myleott** [comment]
`H` is the *hypothesis* (i.e., the system output). The first number is the average log probability of the output.
`D` is the hypothesis after detokenization (if `--tokenizer` or `--bpe` are provided)
`P` is the log probability of each token in the hypothesis
