### ISSUE TITLE
Order of Vocabulary Mapping from Dictionary to Embedding Matrix

### ISSUE THREAD

**Issue by vyraun** [pytorch/fairseq#2454]
Hi, is the "order" of mapping of vocabulary elements from dictionary to the embedding matrix done on the basis of frequency? i.e. If I extract the embedding matrix: after the first 4 special tokens, do the rest of the embedings correspond to the tokens in the dictionary (which are already sorted by frequency) _in the same order_? I am using joint BPE vocab as in here: https://github.com/pytorch/fairseq/blob/master/examples/translation/prepare-iwslt14.sh .

**Comment by myleott** [comment]
Yes, generally the dictionary order (and therefore embedding matrix order) correspond to the token frequency in the training set.
