### ISSUE TITLE
Unclear role of `args` parameter to `build_*` methods of `FairseqTask`

### ISSUE THREAD

**Issue by munael** [pytorch/fairseq#2456]
## 📚 Documentation

Not a typo or an obvious bug. I'm genuinely confused as their role and so can't make a PR yet :T

Here: ttps://fairseq.readthedocs.io/en/latest/tasks.html#fairseq.tasks.FairseqTask

We see args (after parsing and preparing) passed to `FairseqTask`, which saves them to `self`.

Then `args` is again passed to every `build_*` method, like `build_model`.

At first glance, this seems to be to account for cases where a task chooses to store only its task-specific args, not criterion or model args.

But an internal task `MultilingualTranslationTask`:

https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/multilingual_translation.py#L244-L251

Checks the stored `self.args` against the passed `args`, which is again confusing. Is this for evaluation time? So at the first training, both `args` and `self.args` are the same, but on job resumption or evaluation `self.args` is loaded from savefile while `args` is live?

**Comment by myleott** [comment]
> Is this for evaluation time? So at the first training, both args and self.args are the same, but on job resumption or evaluation self.args is loaded from savefile while args is live?

Yes, exactly. There's a bit more context in the commit that introduced the `check_args` function you referenced: https://github.com/pytorch/fairseq/commit/9c3bb5c6d6c7d6442a28ccb8a81b2fc4e5782ace
