### ISSUE TITLE
Getting error while running 

### ISSUE THREAD

**Issue by MrityunjoyS** [pytorch/fairseq#2457]
python libri_labels.py /home/mrityunjoy/audio_file/ --output-dir /home/mrityunjoy/audio_file/wav2vec/ --output-name split

File "libri_labels.py", line 37
    trans_path = f"{parts[-2]}-{parts[-1]}.trans.txt"
                                                    ^
SyntaxError: invalid syntax

While running the above command getting below error, please help

**Comment by myleott** [comment]
That line uses the f-string syntax introduced in Python 3.6, so you'll likely need to upgrade your Python installation.
