### ISSUE TITLE
Customize command-line tool args?

### ISSUE THREAD

**Issue by ylmeng** [pytorch/fairseq#2461]
The command-line tools such as fairseq-train are handy, but it is very difficult to find a clean way to add my own args (args that are not listed).
I could modify the options.py file directly to allow my own args to be passed in. However, it would be much better if the program can accept any new args directly, or allow users to add them in a separate file.

**Comment by myleott** [comment]
We already allow new arguments to be added via user-supplied tasks, criterions, models, optimizers, etc. What kind of other arguments are you envisioning?

**Comment by ylmeng** [comment]
Sorry, I just realized the --user-dir option can probably meet my needs.

However, there is one thing I am not completely sure by looking at the example. If I want a command-line arg to alter a model attribute ("model.something") during inference (fairseq-interactive). It is not clear to me how to do that.
I know I can pass args to customized tasks, but I am not sure if it works on models loaded from checkpoints.

**Comment by ylmeng** [comment]
> Sorry, I just realized the --user-dir option can probably meet my needs.
> 
> However, there is one thing I am not completely sure by looking at the example. If I want a command-line arg to alter a model attribute ("model.something") during inference (fairseq-interactive). It is not clear to me how to do that.
> I know I can pass args to customized tasks, but I am not sure if it works on models loaded from checkpoints.

OK I see I can use --model-overrides from fairseq-interactive. My bad. But I hope there can be a comprehensive example in the tutorials.
