### ISSUE TITLE
Need code to use pretrained model inn wav2vec 2.0

### ISSUE THREAD

**Issue by MrityunjoyS** [pytorch/fairseq#2463]
I'v downloaded  pre-trained  "Wav2Vec 2.0 Base | No finetuning | Librispeech "  model. But it's in '.pt' format, and there is no documentation/code of how to run it. Need suggestions regarding that.

**Comment by alexeib** [comment]
you cant actually do anything interesting that i know of with a pre-trained model except use it to fine-tune on some labeled dataset. theres a sample command showing how to do finetuning in the docs
