### ISSUE TITLE
what is the score in wav2vec 2.0?

### ISSUE THREAD

**Issue by NatSp** [pytorch/fairseq#2467]
Hello,

I was wondering what is the score that the wav2vec 2.0 inference is returning? And if it is possible to use to it get the confidence probability for the predicted sequence?

Thank you

**Comment by alexeib** [comment]
the score depends on what kind of inference you are doing. in general it is some combination of emission log prob for that particular timestep, and weighted language model score. in theory you could use relative ranking of scores as a confidence measure (not probability) but i have not tried it
