### ISSUE TITLE
TorchScript'ed SinusoidalPositionalEmbedding fails during torch.onnx.export and graph lowering

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/fairseq#2468]
Because it resets/recomputes module attributes (`weights`) in the `forward` method and SetAttr is not supported in run-time:
- in https://github.com/pytorch/fairseq/blob/89a2a0c/fairseq/modules/sinusoidal_positional_embedding.py#L73
- in https://github.com/pytorch/fairseq/blob/89a2a0c/fairseq/modules/sinusoidal_positional_embedding.py#L76

Repro code:
```python3
import torch
from fairseq.modules import SinusoidalPositionalEmbedding

model = SinusoidalPositionalEmbedding(32, 0)
dummy_input = [torch.tensor([[10]], dtype=torch.long)]
example_outputs = [model(*dummy_input)]
model = torch.jit.script(model)
torch.onnx.export(model, dummy_input, 'test.onnx', example_outputs=example_outputs)
```
Error:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 350, in _model_to_graph
    method_graph, params = torch._C._jit_pass_lower_graph(graph, model._c)

RuntimeError: 
temporary: the only valid use of a module is looking up an attribute but found  = prim::SetAttr[name="weights"](%self, %72)
```

**Comment by myleott** [comment]
Interesting, any suggestions on how to fix this?

**Comment by vadimkantorov** [comment]
Huggingface model of maintaining incremental state is more friendly to scripting: they explicitly always return the inccremental state

**Comment by myleott** [comment]
Yep, we definitely plan to move in that direction. But this isn't related to incremental state, right?

This is because we expand the positional weights dynamically based on the input shape. I guess we should just set a max size and raise an exception if the input is larger than that.

**Comment by vadimkantorov** [comment]
I mixed it up, but incremental state is also a problem: because it modifies the passed dictionary, and this is not picked by either tracing or scripting

About caching of positional embeddings, it may be worth supporting explicit precomputation in constructor (with some max-size) to avoid re-computing at forward time. Or allowing the user to pass these as argument, so that the user can control how positional embeddings are computed. I think that's what huggingface does

**Comment by vadimkantorov** [comment]
Also, ONNX export of scripted models is extremely limited now:https://github.com/pytorch/pytorch/issues/42914

This makes ONNX export of beam search and existing models quite hard. It may be possible via mixing of tracing of encoder + decoder + scripting of beam search or manual construction of ONNX graph (via Loop/Scan constructs with maximum-decoded-length), but it's not easy

**Comment by vadimkantorov** [comment]
> This is because we expand the positional weights dynamically based on the input shape. I guess we should just set a max size and raise an exception if the input is larger than that.

Yep, this should work!

**Comment by vadimkantorov** [comment]
probably it's still there!

**Comment by vadimkantorov** [comment]
there is a minimal repro in the OP, one should be able to check it easily

**Comment by BowenBao** [comment]
~~Reopen,~~ prints error in latest PyTorch
```
ValueError: args contained 3 None's after flattening. When exporting a ScriptModule or ScriptFunction, no args may be None because that breaks type propagation.
```

Edit: not in PyTorch repo, doesn't have permission to reopen..
