### ISSUE TITLE
A checkpoint should always be triggered when stopping criteria triger

### ISSUE THREAD

**Issue by narfanar** [pytorch/fairseq#2470]
## 🚀 Feature Request
Currently, when stopping criteria trigger (e.g. `--max-updates`) a checkpoint is not triggered. This is generally fine, but somewhat surprising if, say, at some point in between two save points, early stopping criteria are triggered. The last point in training should be given a chance at validation and saving.

This can be a dedicated `model_last.pt` file, for example. Written only when training has decided to end.

### Motivation

Allow debugging or continuing training from the actual end point of training.

### Pitch

Two possibilities:
1. Right before terminating training, force an evaluation of the current model as a potential checkpoint candidate.
2. Always, right before terminating training, save the current model in a dedicated checkpoint file. E.g. `model_last.pt`.

### Alternatives

Not sure.

### Additional context

N/A

**Comment by alexeib** [comment]
what makes you think this is the case?
```
    # Stopping conditions
    max_update = args.max_update or math.inf
    should_stop = (
        should_stop_early(args, valid_losses[0])
        or trainer.get_num_updates() >= max_update
        or (
            args.stop_time_hours > 0
            and trainer.cumulative_training_time() / (60 * 60) > args.stop_time_hours
        )
    )

    # Save checkpoint
    if do_save or should_stop:
        logger.info("begin save checkpoint")
        checkpoint_utils.save_checkpoint(args, trainer, epoch_itr, valid_losses[0])
```
