### ISSUE TITLE
How to get a model.pt for pretrained Roberta

### ISSUE THREAD

**Issue by Skylixia** [pytorch/fairseq#2472]
## ❓ Questions and Help

Hello, I trained my own Roberta model following these [steps](https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md). I would like to convert it to be usable with hugging face transformers (this can be done with this [function](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_roberta_original_pytorch_checkpoint_to_pytorch.py)). 
However, after the training I have the checkpoint directory with all checkpoints saved (with checkpoint_best.pt/checkpoint_last.pt and earlier steps) but not a model.pt. It something normally found in this directory, how can I generate such a file ? 
Thank you !

**Comment by myleott** [comment]
You can use checkpoint_best.pt or checkpoint_last.pt. We manually rename them to model.pt before releasing model checkpoints, but any checkpoint file can be used. The huggingface script should work with any of them as well.
