### ISSUE TITLE
what is the data_name_or_path parameter for?

### ISSUE THREAD

**Issue by bhomass** [pytorch/fairseq#2474]
In the CNN inference code, you set up the bart object with 
bart = BARTModel.from_pretrained(
    'checkpoints/',
    checkpoint_file='checkpoint_best.pt',
    data_name_or_path='cnn_dm-bin'
)
what is the data_name_or_path parameter for? It is pointing to the cnn_dm-bin directory. I understand that's where the binarized training data is stored. Why would you need them for inference?

It matters because it is not clear how to translate this for the XSum case. There is no instruction for creating equivalent binary files for XSum.

**Comment by myleott** [comment]
It's for loading the dictionary files. It's not necessary for that directory to actually contain training data.
