### ISSUE TITLE
AttributeError: 'BLEU' object has no attribute 'format'

### ISSUE THREAD

**Issue by thpun** [pytorch/fairseq#2475]
## 🐛 Bug

When running `fairseq-generate`, it failed to output BLEU score.

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd
```
CUDA_VISIBLE_DEVICES=0 fairseq-generate \
--path=$MODEL $DATA \
--task translation_multi_simple_epoch \
--encoder-langtok 'src' --decoder-langtok \
--gen-subset test \
-t $TGT -s $SRC \
--lang-dict "$lang_list" --lang-pairs "$lang_pairs" \
--bpe 'sentencepiece' --sentencepiece-model models/mbart.cc25/sentence.bpe.model \
--remove-bpe 'sentencepiece' \
--sacrebleu --fp16 --max-sentences 64
```
2. See error
```
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/workspace/fairseq/fairseq_cli/generate.py", line 281, in cli_main
    main(args)
  File "/workspace/fairseq/fairseq_cli/generate.py", line 38, in main
    return _main(args, sys.stdout)
  File "/workspace/fairseq/fairseq_cli/generate.py", line 272, in _main
    'Generate {} with beam={}: {}'.format(args.gen_subset, args.beam, scorer.result_string()),
  File "/workspace/fairseq/fairseq/scoring/bleu.py", line 63, in result_string
    return self.sacrebleu.corpus_bleu(self.sys, [self.ref]).format()
AttributeError: 'BLEU' object has no attribute 'format'
```

### Expected behavior

It is expected that the BLEU score is printed at the end of `fairseq-generate`, as in previous versions of fairseq.

### Environment

 - fairseq Version (e.g., 1.0 or master): master, commit 4c55744ec4cb26749cf2cf8dac89942f26ce4bd2
 - PyTorch Version (e.g., 1.0) `1.5.0a0+8f84ded`
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): `pip install --editable .`
 - Python version: 3.6.9
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: V100

**Comment by myleott** [comment]
Ah, you're probably using an old version of sacrebleu. Please update with `pip install --upgrade sacrebleu`. We will merge a backward compatible fix soon.
