### ISSUE TITLE
Finetuned mBART model for Spanish-English produces lengthy incorrect results for short inputs

### ISSUE THREAD

**Issue by mohammedayub44** [pytorch/fairseq#2476]
## ❓ Questions and Help

Hi,

I have mBART model that was finetuned on Spanish to English custom data set with lengthy sentences (avg sentence length of about 25 words.) Its working well for long sentences (both on custom data set and general sentences.) However when I type shorts sentences (like 2-3 word ) as inputs , its giving me strange incorrect prediction in a different language.

Here is one for simple spanish input `Dame comida.` (meaning `Give me food` ) , which gives incorrect results: 

![image](https://user-images.githubusercontent.com/7122670/90094068-fe9f2a00-dcfa-11ea-85a8-ec2bd91e7e96.png)

However, long sentences work(like more that 10 words): 
e.g. `No me gusta mucho el sushi, pero soy fanática de la comida tailandesa.` meaning `I don't really like sushi, but I am a fan of Thai food.`

![image](https://user-images.githubusercontent.com/7122670/90094273-7d946280-dcfb-11ea-9fa3-e7da8c2474d7.png)

I played around with several parameters `--unkpen`, `--max-len-a`, `--max-len-b` and `--match-source-len` etc. But I still could not get rid of the incorrect language predictions.

Is there any way I could troubleshoot what has gone wrong in the model ? Has the model overfitted too much on long sentences that it cannot handle simple short sentences like the one above ? Is there a way to fix this with out retraining the model again ?

Appreciate any help !

Thanks

**Comment by fahimeh-saleh** [comment]
I have the same problem! It seems mBART doesn't work well for the dataset with short sentences! Can you please help @yinhanliu?

**Comment by mohammedayub44** [comment]
@fahimeh-saleh  Did you happen to get it for the same language pair (Spanish-English) ?
It works fine for English-Spanish. Only in Spanish to English model I see this discrepancy. But, I'm guessing it happens in general from what you say.

Note: I created two model, one for each direction (En-->Es and Es-->En) , by just interchanging the source and target parameters with the same command.
