### ISSUE TITLE
Translation doesn't use sampling temperature param

### ISSUE THREAD

**Issue by hughbzhang** [pytorch/fairseq#248]
I noticed that when I'm generating translations using sampling instead of beam search, that the temperature param doesn't seem to do anything. Looking at generate.py SequenceGenerator is called as follows:

```
translator = SequenceGenerator(
            models, task.target_dictionary, beam_size=args.beam,
            stop_early=(not args.no_early_stop), normalize_scores=(not args.unnormalized),
            len_penalty=args.lenpen, unk_penalty=args.unkpen,
            sampling=args.sampling, sampling_topk=args.sampling_topk, minlen=args.min_len,
        )
```

Sampling temperature thus seems not passed in and will always defaults to 1.0, which is fixed if I add ```sampling_temperature=args.sampling_temperature``` to the function call.

Is this the correct way to sample with translations?

**Comment by myleott** [comment]
Yep, if you add the kwarg it will work as expected. We fixed this internally already, I'll merge the fix here shortly.

**Comment by hughbzhang** [comment]
Cool thanks for the fix!
