### ISSUE TITLE
suggested_ed2_path in libnat

### ISSUE THREAD

**Issue by rajevv** [pytorch/fairseq#2481]
Congrats on the great work on Levenshtein Transformer. I am really intrigued by the work and trying to understand the paper and the implementation. 
Could you help me in understanding what the suggested_ed2_path function is and what does it returns?

I am looking to understand the description of the learning algorithm in the paper (especially expert policy implementation). Could you please give some heads up in the code to understand the learning algorithm in the appendix of the paper?

**Comment by myleott** [comment]
@MultiPath @kahne

**Comment by conan1024hao** [comment]
Have you figured it out?
