### ISSUE TITLE
BART: Can you please let me know how to calculate ROUGE-score metrics ?

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#2484]
What are the steps that I should follow to get ROUGE scores for BART that has fine-tunned on CNN/DM?

**Comment by shamanez** [comment]
Sorry I saw it in the Readme.

**Comment by kaushal0494** [comment]
Hi @shamanez,  which readme file you referred? I am facing the same problem.

**Comment by shamanez** [comment]
The main Readme file.

**Comment by kaushal0494** [comment]
Hey, @shamanez thank you for your reply.  Are you talking about this file: https://github.com/pytorch/fairseq/tree/master/examples/bart#evaluating-the-bartlargecnn-model

**Comment by shamanez** [comment]
Yes, it is.
https://www.github.com/pytorch/fairseq/tree/master/examples%2Fbart%2FREADME.md

**Comment by kaushal0494** [comment]
Thank you @shamanez !
