### ISSUE TITLE
How to get '.ltr' file ?

### ISSUE THREAD

**Issue by MrityunjoyS** [pytorch/fairseq#2485]
python3 train.py /path/ --save-dir /path/model_exportdir1 --fp16 --post-process letter --valid-subset valid --no-epoch-checkpoints --best-checkpoint-metric wer --num-workers 4 --max-update 80000 --sentence-avg --task audio_pretraining --arch wav2vec_ctc --w2v-path /path/wav2vec_small_10m.pt --labels ltr --apply-mask --mask-selection static --mask-other 0 --mask-length 10 --mask-prob 0.5 --layerdrop 0.1 --mask-channel-selection static --mask-channel-other 0 --mask-channel-length 64 --mask-channel-prob 0.5 --zero-infinity --feature-grad-mult 0.0 --freeze-finetune-updates 10000 --validate-after-updates 10000 --optimizer adam --adam-betas '(0.9, 0.98)' --adam-eps 1e-08 --lr 2e-05 --lr-scheduler tri_stage --warmup-steps 8000 --hold-steps 32000 --decay-steps 40000 --final-lr-scale 0.05 --final-dropout 0.0 --dropout 0.0 --activation-dropout 0.1 --criterion ctc --attention-dropout 0.0 --max-tokens 1280000 --seed 2337 --log-format json --log-interval 500 --ddp-backend no_c10d

Running this above command and getting below error :-

File "/path/fairseq-master/fairseq/tasks/audio_pretraining.py", line 110, in load_dataset
    with open(label_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/path/valid.ltr

Can anyone suggest what'd this '.ltr' file and how to create it ?

**Comment by zqs01** [comment]
I also want to solve this question.

**Comment by MrityunjoyS** [comment]
I did one thing, just copying the '.ltr.txt' file created from manifest file to '.ltr' file and was able to finetune using Librispeech model. Although I don't know if it's correct or not

**Comment by alexeib** [comment]
yeah sorry, you can just rename the files that "libri_labels.py" outputs to .wrd and .ltr respectively to use the .ltr as letter targets. i'll update the script when i get a chance

**Comment by MrityunjoyS** [comment]
Thank you @alexeib
