### ISSUE TITLE
mask-whole-words training tokenize wordpiece

### ISSUE THREAD

**Issue by Skylixia** [pytorch/fairseq#2494]
Hello, 

I trained a Roberta model with --mask-whole-words. However, the tokenizer seem to do word piece and not whole words. 
I loaded the tokenizer and model with the transformers library to fill masks but I want to do this with whole word tokenization. 
Any idea why I'm getting word pieces ?

Thank you

**Comment by myleott** [comment]
Correct, when training with `--mask-whole-words` it still uses word piece tokenization, but will mask out multiple word pieces when necessary to mask a whole word.

For example, suppose your sentence is `"Testing masking whole words"`
which gets split into word pieces `['Testing', ' mask', 'ing', ' whole', ' words']`.
When you train with `--mask-whole-words` it will only replace "mask" and "ing" together,
so you'll get `['Testing', '<mask>', '<mask>', ' whole', ' words']`
