### ISSUE TITLE
Need to extract feature from best_checkpoints of wav2vec2.0 model.

### ISSUE THREAD

**Issue by MrityunjoyS** [pytorch/fairseq#2495]
PYTHONPATH=/path/to/fairseq python examples/wav2vec/wav2vec_featurize.py --input /path/to/task/waves --output /path/to/output \
--model /model/path/checkpoint_best.pt --split train valid test

Using this for Extracting embeddings from the downstream task data, using the checkpoints recived after finetuning wav2vec 2.0 model.

PYTHONPATH=/home/mrityunjoy/fairseq-master/  python3 examples/wav2vec/wav2vec_featurize.py --input /home/mrityunjoy/audio_file/LibriSpeech/dev-clean/ --output /home/mrityunjoy/audio_file/wav2vec/tmp/ \
> --model /home/mrityunjoy/model_exportdir1/checkpoint_best.pt --split train valid test
**Traceback (most recent call last):
  File "examples/wav2vec/wav2vec_featurize.py", line 223, in <module>
    use_feat=args.use_feat,
  File "examples/wav2vec/wav2vec_featurize.py", line 137, in __init__
    self.model = Prediction(self.model_fname, gpu)
  File "examples/wav2vec/wav2vec_featurize.py", line 88, in __init__
    self.model = PretrainedWav2VecModel(fname).cuda(gpu)
  File "examples/wav2vec/wav2vec_featurize.py", line 43, in __init__
    model.load_state_dict(checkpoint["model"])
  File "/home/mrityunjoy/fairseq-master/fairseq/models/fairseq_model.py", line 93, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/mrityunjoy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Wav2VecModel:
	Missing key(s) in state_dict:"feature_extractor.conv_layers.0.0.weight", "feature_extractor.conv_layers.0.2.weight", "feature_extractor.conv_layers.0.2.bias", "feature_extractor.conv_layers.1.0.weight", "feature_extractor.conv_layers.1.2.weight", "feature_extractor.conv_layers.1.2.bias", "feature_extractor.conv_layers.2.0.weight", "feature_extractor.conv_layers.2.2.weight", "feature_extractor.conv_layers.2.2.bias", "feature_extractor.conv_layers.3.0.weight", "feature_extractor.conv_layers.3.2.weight", "feature_extractor.conv_layers.3.2.bias", "feature_extractor.conv_layers.4.0.weight", "feature_extractor.conv_layers.4.2.weight", "feature_extractor.conv_layers.4.2.bias", "feature_aggregator.conv_layers.0.1.weight", "feature_aggregator.conv_layers.0.1.bias", "feature_aggregator.conv_layers.0.3.weight", "feature_aggregator.conv_layers.0.3.bias", "feature_aggregator.conv_layers.1.1.weight", "feature_aggregator.conv_layers.1.1.bias", "feature_aggregator.conv_layers.1.3.weight", "feature_aggregator.conv_layers.1.3.bias", "feature_aggregator.conv_layers.2.1.weight", "feature_aggregator.conv_layers.2.1.bias", "feature_aggregator.conv_layers.2.3.weight", "feature_aggregator.conv_layers.2.3.bias", "feature_aggregator.conv_layers.3.1.weight", "feature_aggregator.conv_layers.3.1.bias", "feature_aggregator.conv_layers.3.3.weight", "feature_aggregator.conv_layers.3.3.bias", "feature_aggregator.conv_layers.4.1.weight", "feature_aggregator.conv_layers.4.1.bias", "feature_aggregator.conv_layers.4.3.weight", "feature_aggregator.conv_layers.4.3.bias", "feature_aggregator.conv_layers.5.1.weight", "feature_aggregator.conv_layers.5.1.bias", "feature_aggregator.conv_layers.5.3.weight", "feature_aggregator.conv_layers.5.3.bias", "feature_aggregator.conv_layers.6.1.weight", "feature_aggregator.conv_layers.6.1.bias", "feature_aggregator.conv_layers.6.3.weight", "feature_aggregator.conv_layers.6.3.bias", "feature_aggregator.conv_layers.7.1.weight", "feature_aggregator.conv_layers.7.1.bias", "feature_aggregator.conv_layers.7.3.weight", "feature_aggregator.conv_layers.7.3.bias", "feature_aggregator.conv_layers.8.1.weight", "feature_aggregator.conv_layers.8.1.bias", "feature_aggregator.conv_layers.8.3.weight", "feature_aggregator.conv_layers.8.3.bias", "wav2vec_predictions.project_to_steps.weight", "wav2vec_predictions.project_to_steps.bias". 
	Unexpected key(s) in state_dict: "w2v_encoder.w2v_model.mask_emb", "w2v_encoder.w2v_model.feature_extractor.conv_layers.0.0.weight", "w2v_encoder.w2v_model.feature_extractor.conv_layers.0.2.weight", "w2v_encoder.w2v_model.feature_extractor.conv_layers.0.2.bias", "w2v_encoder.w2v_model.feature_extractor.conv_layers.1.0.weight", "w2v_encoder.w2v_model.feature_extractor.conv_layers.2.0.weight", "w2v_encoder.w2v_model.feature_extractor.conv_layers.3.0.weight", "w2v_encoder.w2v_model.feature_extractor.conv_layers.4.0.weight", "w2v_encoder.w2v_model.feature_extractor.conv_layers.5.0.weight", "w2v_encoder.w2v_model.feature_extractor.conv_layers.6.0.weight", "w2v_encoder.w2v_model.post_extract_proj.weight", "w2v_encoder.w2v_model.post_extract_proj.bias", "w2v_encoder.w2v_model.encoder.pos_conv.0.bias", "w2v_encoder.w2v_model.encoder.pos_conv.0.weight_g", "w2v_encoder.w2v_model.encoder.pos_conv.0.weight_v", "w2v_encoder.w2v_model.encoder.layers.0.self_attn.k_proj.weight", "w2v_encoder.w2v_model.encoder.layers.0.self_attn.k_proj.bias", "w2v_encoder.w2v_model.encoder.layers.0.self_attn.v_proj.weight", "w2v_encoder.w2v_model.encoder.layers.0.self_attn.v_proj.bias", "w2v_encoder.w2v_model.encoder.layers.0.self_attn.q_proj.weight", "w2v_encoder.w2v_model.encoder.layers.0.self_attn.q_proj.bias", "w2v_encoder.w2v_model.encoder.layers.0.self_attn.out_proj.weight", "w2v_encoder.w2v_model.encoder.layers.0.self_attn.out_proj.bias", "w2v_encoder.w2v_model.encoder.layers.0.self_attn_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.0.self_attn_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.0.fc1.weight", "w2v_encoder.w2v_model.encoder.layers.0.fc1.bias", "w2v_encoder.w2v_model.encoder.layers.0.fc2.weight", "w2v_encoder.w2v_model.encoder.layers.0.fc2.bias", "w2v_encoder.w2v_model.encoder.layers.0.final_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.0.final_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.1.self_attn.k_proj.weight", "w2v_encoder.w2v_model.encoder.layers.1.self_attn.k_proj.bias", "w2v_encoder.w2v_model.encoder.layers.1.self_attn.v_proj.weight", "w2v_encoder.w2v_model.encoder.layers.1.self_attn.v_proj.bias", "w2v_encoder.w2v_model.encoder.layers.1.self_attn.q_proj.weight", "w2v_encoder.w2v_model.encoder.layers.1.self_attn.q_proj.bias", "w2v_encoder.w2v_model.encoder.layers.1.self_attn.out_proj.weight", "w2v_encoder.w2v_model.encoder.layers.1.self_attn.out_proj.bias", "w2v_encoder.w2v_model.encoder.layers.1.self_attn_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.1.self_attn_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.1.fc1.weight", "w2v_encoder.w2v_model.encoder.layers.1.fc1.bias", "w2v_encoder.w2v_model.encoder.layers.1.fc2.weight", "w2v_encoder.w2v_model.encoder.layers.1.fc2.bias", "w2v_encoder.w2v_model.encoder.layers.1.final_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.1.final_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.2.self_attn.k_proj.weight", "w2v_encoder.w2v_model.encoder.layers.2.self_attn.k_proj.bias", "w2v_encoder.w2v_model.encoder.layers.2.self_attn.v_proj.weight", "w2v_encoder.w2v_model.encoder.layers.2.self_attn.v_proj.bias", "w2v_encoder.w2v_model.encoder.layers.2.self_attn.q_proj.weight", "w2v_encoder.w2v_model.encoder.layers.2.self_attn.q_proj.bias", "w2v_encoder.w2v_model.encoder.layers.2.self_attn.out_proj.weight", "w2v_encoder.w2v_model.encoder.layers.2.self_attn.out_proj.bias", "w2v_encoder.w2v_model.encoder.layers.2.self_attn_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.2.self_attn_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.2.fc1.weight", "w2v_encoder.w2v_model.encoder.layers.2.fc1.bias", "w2v_encoder.w2v_model.encoder.layers.2.fc2.weight", "w2v_encoder.w2v_model.encoder.layers.2.fc2.bias", "w2v_encoder.w2v_model.encoder.layers.2.final_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.2.final_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.3.self_attn.k_proj.weight", "w2v_encoder.w2v_model.encoder.layers.3.self_attn.k_proj.bias", "w2v_encoder.w2v_model.encoder.layers.3.self_attn.v_proj.weight", "w2v_encoder.w2v_model.encoder.layers.3.self_attn.v_proj.bias", "w2v_encoder.w2v_model.encoder.layers.3.self_attn.q_proj.weight", "w2v_encoder.w2v_model.encoder.layers.3.self_attn.q_proj.bias", "w2v_encoder.w2v_model.encoder.layers.3.self_attn.out_proj.weight", "w2v_encoder.w2v_model.encoder.layers.3.self_attn.out_proj.bias", "w2v_encoder.w2v_model.encoder.layers.3.self_attn_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.3.self_attn_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.3.fc1.weight", "w2v_encoder.w2v_model.encoder.layers.3.fc1.bias", "w2v_encoder.w2v_model.encoder.layers.3.fc2.weight", "w2v_encoder.w2v_model.encoder.layers.3.fc2.bias", "w2v_encoder.w2v_model.encoder.layers.3.final_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.3.final_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.4.self_attn.k_proj.weight", "w2v_encoder.w2v_model.encoder.layers.4.self_attn.k_proj.bias", "w2v_encoder.w2v_model.encoder.layers.4.self_attn.v_proj.weight", "w2v_encoder.w2v_model.encoder.layers.4.self_attn.v_proj.bias", "w2v_encoder.w2v_model.encoder.layers.4.self_attn.q_proj.weight", "w2v_encoder.w2v_model.encoder.layers.4.self_attn.q_proj.bias", "w2v_encoder.w2v_model.encoder.layers.4.self_attn.out_proj.weight", "w2v_encoder.w2v_model.encoder.layers.4.self_attn.out_proj.bias", "w2v_encoder.w2v_model.encoder.layers.4.self_attn_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.4.self_attn_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.4.fc1.weight", "w2v_encoder.w2v_model.encoder.layers.4.fc1.bias", "w2v_encoder.w2v_model.encoder.layers.4.fc2.weight", "w2v_encoder.w2v_model.encoder.layers.4.fc2.bias", "w2v_encoder.w2v_model.encoder.layers.4.final_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.4.final_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.5.self_attn.k_proj.weight", "w2v_encoder.w2v_model.encoder.layers.5.self_attn.k_proj.bias", "w2v_encoder.w2v_model.encoder.layers.5.self_attn.v_proj.weight", "w2v_encoder.w2v_model.encoder.layers.5.self_attn.v_proj.bias", "w2v_encoder.w2v_model.encoder.layers.5.self_attn.q_proj.weight", "w2v_encoder.w2v_model.encoder.layers.5.self_attn.q_proj.bias", "w2v_encoder.w2v_model.encoder.layers.5.self_attn.out_proj.weight", "w2v_encoder.w2v_model.encoder.layers.5.self_attn.out_proj.bias", "w2v_encoder.w2v_model.encoder.layers.5.self_attn_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.5.self_attn_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.5.fc1.weight", "w2v_encoder.w2v_model.encoder.layers.5.fc1.bias", "w2v_encoder.w2v_model.encoder.layers.5.fc2.weight", "w2v_encoder.w2v_model.encoder.layers.5.fc2.bias", "w2v_encoder.w2v_model.encoder.layers.5.final_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.5.final_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.6.self_attn.k_proj.weight", "w2v_encoder.w2v_model.encoder.layers.6.self_attn.k_proj.bias", "w2v_encoder.w2v_model.encoder.layers.6.self_attn.v_proj.weight", "w2v_encoder.w2v_model.encoder.layers.6.self_attn.v_proj.bias", "w2v_encoder.w2v_model.encoder.layers.6.self_attn.q_proj.weight", "w2v_encoder.w2v_model.encoder.layers.6.self_attn.q_proj.bias", "w2v_encoder.w2v_model.encoder.layers.6.self_attn.out_proj.weight", "w2v_encoder.w2v_model.encoder.layers.6.self_attn.out_proj.bias", "w2v_encoder.w2v_model.encoder.layers.6.self_attn_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.6.self_attn_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.6.fc1.weight", "w2v_encoder.w2v_model.encoder.layers.6.fc1.bias", "w2v_encoder.w2v_model.encoder.layers.6.fc2.weight", "w2v_encoder.w2v_model.encoder.layers.6.fc2.bias", "w2v_encoder.w2v_model.encoder.layers.6.final_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.6.final_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.7.self_attn.k_proj.weight", "w2v_encoder.w2v_model.encoder.layers.7.self_attn.k_proj.bias", "w2v_encoder.w2v_model.encoder.layers.7.self_attn.v_proj.weight", "w2v_encoder.w2v_model.encoder.layers.7.self_attn.v_proj.bias", "w2v_encoder.w2v_model.encoder.layers.7.self_attn.q_proj.weight", "w2v_encoder.w2v_model.encoder.layers.7.self_attn.q_proj.bias", "w2v_encoder.w2v_model.encoder.layers.7.self_attn.out_proj.weight", "w2v_encoder.w2v_model.encoder.layers.7.self_attn.out_proj.bias", "w2v_encoder.w2v_model.encoder.layers.7.self_attn_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.7.self_attn_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.7.fc1.weight", "w2v_encoder.w2v_model.encoder.layers.7.fc1.bias", "w2v_encoder.w2v_model.encoder.layers.7.fc2.weight", "w2v_encoder.w2v_model.encoder.layers.7.fc2.bias", "w2v_encoder.w2v_model.encoder.layers.7.final_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.7.final_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.8.self_attn.k_proj.weight", "w2v_encoder.w2v_model.encoder.layers.8.self_attn.k_proj.bias", "w2v_encoder.w2v_model.encoder.layers.8.self_attn.v_proj.weight", "w2v_encoder.w2v_model.encoder.layers.8.self_attn.v_proj.bias", "w2v_encoder.w2v_model.encoder.layers.8.self_attn.q_proj.weight", "w2v_encoder.w2v_model.encoder.layers.8.self_attn.q_proj.bias", "w2v_encoder.w2v_model.encoder.layers.8.self_attn.out_proj.weight", "w2v_encoder.w2v_model.encoder.layers.8.self_attn.out_proj.bias", "w2v_encoder.w2v_model.encoder.layers.8.self_attn_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.8.self_attn_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.8.fc1.weight", "w2v_encoder.w2v_model.encoder.layers.8.fc1.bias", "w2v_encoder.w2v_model.encoder.layers.8.fc2.weight", "w2v_encoder.w2v_model.encoder.layers.8.fc2.bias", "w2v_encoder.w2v_model.encoder.layers.8.final_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.8.final_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.9.self_attn.k_proj.weight", "w2v_encoder.w2v_model.encoder.layers.9.self_attn.k_proj.bias", "w2v_encoder.w2v_model.encoder.layers.9.self_attn.v_proj.weight", "w2v_encoder.w2v_model.encoder.layers.9.self_attn.v_proj.bias", "w2v_encoder.w2v_model.encoder.layers.9.self_attn.q_proj.weight", "w2v_encoder.w2v_model.encoder.layers.9.self_attn.q_proj.bias", "w2v_encoder.w2v_model.encoder.layers.9.self_attn.out_proj.weight", "w2v_encoder.w2v_model.encoder.layers.9.self_attn.out_proj.bias", "w2v_encoder.w2v_model.encoder.layers.9.self_attn_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.9.self_attn_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.9.fc1.weight", "w2v_encoder.w2v_model.encoder.layers.9.fc1.bias", "w2v_encoder.w2v_model.encoder.layers.9.fc2.weight", "w2v_encoder.w2v_model.encoder.layers.9.fc2.bias", "w2v_encoder.w2v_model.encoder.layers.9.final_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.9.final_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.10.self_attn.k_proj.weight", "w2v_encoder.w2v_model.encoder.layers.10.self_attn.k_proj.bias", "w2v_encoder.w2v_model.encoder.layers.10.self_attn.v_proj.weight", "w2v_encoder.w2v_model.encoder.layers.10.self_attn.v_proj.bias", "w2v_encoder.w2v_model.encoder.layers.10.self_attn.q_proj.weight", "w2v_encoder.w2v_model.encoder.layers.10.self_attn.q_proj.bias", "w2v_encoder.w2v_model.encoder.layers.10.self_attn.out_proj.weight", "w2v_encoder.w2v_model.encoder.layers.10.self_attn.out_proj.bias", "w2v_encoder.w2v_model.encoder.layers.10.self_attn_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.10.self_attn_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.10.fc1.weight", "w2v_encoder.w2v_model.encoder.layers.10.fc1.bias", "w2v_encoder.w2v_model.encoder.layers.10.fc2.weight", "w2v_encoder.w2v_model.encoder.layers.10.fc2.bias", "w2v_encoder.w2v_model.encoder.layers.10.final_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.10.final_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.11.self_attn.k_proj.weight", "w2v_encoder.w2v_model.encoder.layers.11.self_attn.k_proj.bias", "w2v_encoder.w2v_model.encoder.layers.11.self_attn.v_proj.weight", "w2v_encoder.w2v_model.encoder.layers.11.self_attn.v_proj.bias", "w2v_encoder.w2v_model.encoder.layers.11.self_attn.q_proj.weight", "w2v_encoder.w2v_model.encoder.layers.11.self_attn.q_proj.bias", "w2v_encoder.w2v_model.encoder.layers.11.self_attn.out_proj.weight", "w2v_encoder.w2v_model.encoder.layers.11.self_attn.out_proj.bias", "w2v_encoder.w2v_model.encoder.layers.11.self_attn_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.11.self_attn_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layers.11.fc1.weight", "w2v_encoder.w2v_model.encoder.layers.11.fc1.bias", "w2v_encoder.w2v_model.encoder.layers.11.fc2.weight", "w2v_encoder.w2v_model.encoder.layers.11.fc2.bias", "w2v_encoder.w2v_model.encoder.layers.11.final_layer_norm.weight", "w2v_encoder.w2v_model.encoder.layers.11.final_layer_norm.bias", "w2v_encoder.w2v_model.encoder.layer_norm.weight", "w2v_encoder.w2v_model.encoder.layer_norm.bias", "w2v_encoder.w2v_model.layer_norm.weight", "w2v_encoder.w2v_model.layer_norm.bias", "w2v_encoder.proj.weight", "w2v_encoder.proj.bias".**

What changes need to be done to avoid facing this issue ?

**Comment by alexeib** [comment]
wav2vec-featurize works with wav2vec 1.0, not 2.0. We do not have a script for wav2vec 2.0 but you should be able to modify the original one to build a new model and extract features from it relatively easily.

you will need to change how the model is built (so it builds a Wav2vec2Model), and also how the model is invoked (you will want to call "extract_features()"

**Comment by edmilsonmorais** [comment]
Hi alexeib, I have trained and fine tunned a wav2vec 2.0 model and I am trying to load it and to extract features with it to train a downstream task.  In order to doing the following modifications:
1) from fairseq.models.wav2vec.wav2vec2 import Wav2Vec2Model
2) Using only this command  "z = model.feature_extractor(wav_input_16khz)". I am not using this command  "c = model.feature_aggregator(z)"  because it looks like that wav2vec 2.0 models do not support feature_aggregator ...
3) I am loading the model using the strict=False FLAG:  "model.load_state_dict(cp['model'],strict=False)".  If I do not use this FLAG (strict=False) I always get the following message: "RuntimeError: Error(s) in loading state_dict for Wav2Vec2Model:"  

Following (1), (2) e (3) I am able the get the features, however, after training my downstream task using such features, the results are really bad.  Please, do you know what is wrong?

**Comment by alexeib** [comment]
we dont use features for training downstream tasks with this model, we finetune the model directly on the task (the only one we've tested is asr/phoneme classification). i havent actually tried to extract features and use them with wav2vec 2.0 (unlike what we did previously with wav2vec 1.0).

if you want "feature aggregator" features, you can just do model.eval(); model.forward(your_input, mask=False, features_only=True). Let me know if this works better!

**Comment by Adportas** [comment]
I have the same task and made the following changes based on yours thread, but I get the error below the changes posted, please can you give me an orientation on how to solve it, I don't have much experience in Python language, thanks.

    _def __init__(self, fname):
        super().__init__()

        checkpoint = torch.load(fname)
        self.args = checkpoint["args"]
        #model = Wav2VecModel.build_model(self.args, None)
        model = Wav2Vec2Model.build_model(self.args, None)
        #model.load_state_dict(checkpoint["model"])
        model.load_state_dict(checkpoint["model"], strict=False)
        model.eval()

        self.model = model

    def forward(self, x):
        with torch.no_grad():
            z = self.model.feature_extractor(x)
            if isinstance(z, tuple):
                z = z[0]
            #c = self.model.feature_aggregator(z)
            self.model.eval()
            c = self.model.forward(z, mask=False, features_only=True)
        return z, c_


**RuntimeError: Expected 3-dimensional input for 3-dimensional weight 512 1 10, but got 4-dimensional input of size [1, 1, 512, 880] instead**

**Comment by alexeib** [comment]
you dont need to manually extract features if you are just going to pass result into model.forward() anyway
suppose x is one dimensional vector containing your audio, then you can just do 
```
return self.model.forward(x.unsqueeze(0), mask=False, features_only=True)
```

**Comment by Adportas** [comment]
I kept it very simple but it didn't work, I probably didn't get it right. I am trying to pass some wav files to h5context files for a speech language training in wav2letter, using the new wav2vec model filename wav2vec2_vox_960h.pt, but apparently it is necessary to adapt the wav2vec_featurize.py script to wav2vec2 to be able to do it, for That is why I am adapting the code, but I am not really familiar with it, this is the error that it throws in case you can give me some advice, thanks

    _def __init__(self, fname):
        super().__init__()

        checkpoint = torch.load(fname)
        self.args = checkpoint["args"]
        model = Wav2Vec2Model.build_model(self.args, None)
        model.load_state_dict(checkpoint["model"], strict=False)
        model.eval()

        self.model = model

    def forward(self, x):
        return self.model.forward(x.unsqueeze(0), mask=False, features_only=True)_

**RuntimeError: Expected 3-dimensional input for 3-dimensional weight 512 1 10, but got 4-dimensional input of size [1, 1, 1, 141150] instead**

**Comment by alexeib** [comment]
what is the shape of x?

btw if you guys are extracting features from this model, you may want to try to extract features from various transformer layers, not just the last one. for example we found that features from middle layers most correspond to things like phones, as opposed to features from the last layer

**Comment by Adportas** [comment]
I add print(x.shape) to the _def forward(self, x):_ of the **wav2vec_featurize.py** included in **fairseq** source code and get that:

**torch.Size([1, 141150])**

**Comment by alexeib** [comment]
ok, then try again without the unsqueeze(0) part. the model expects input in shape of BxC where b is batch and c is 1d waveform signal

**Comment by Adportas** [comment]
After removing unsqueeze (0) the following error occurs in the **Prediction class** of the **wav2vec_featurize.py** included in **fairseq** source code

**Writing Features...
torch.Size([1, 141150])
Traceback (most recent call last):
  File "wav2vec_featurize.py", line 242, in <module>
    writer.write_features()
  File "wav2vec_featurize.py", line 211, in write_features
    z, c = self.model(wav)
  File "wav2vec_featurize.py", line 107, in __call__
    return z.squeeze(0).cpu().numpy(), c.squeeze(0).cpu().numpy()
AttributeError: 'str' object has no attribute 'squeeze'**

The class is not modified

_class Prediction():
    """ Lightweight wrapper around a fairspeech embedding model """

    def __init__(self, fname, gpu=0):
        self.gpu = gpu
        self.model = PretrainedWav2VecModel(fname).cuda(gpu)

    def __call__(self, x):
        x = torch.from_numpy(x).float().cuda(self.gpu)
        with torch.no_grad():
            z, c = self.model(x.unsqueeze(0))

        return z.squeeze(0).cpu().numpy(), c.squeeze(0).cpu().numpy()_

**Comment by mhn226** [comment]
Hi @Adportas , have you fixed it yet?
Hi @alexeib , according to your recommendation, I do it this way:

`class PretrainedWav2VecModel(nn.Module):
    def __init__(self, fname):
        super().__init__()
        model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([fname])
        model = model[0]
        model.eval()

        self.model = model

    def forward(self, x):
        with torch.no_grad():
            self.model.eval()
            return self.model.extract_features(x, padding_mask=None, mask=False)
`

and in Prediction:
`class Prediction:
    """ Lightweight wrapper around a fairspeech embedding model """

    def __init__(self, fname, gpu=0):
        self.gpu = gpu
        self.model = PretrainedWav2VecModel(fname).cuda(gpu)

    def __call__(self, x):
        x = torch.from_numpy(x).float().cuda(self.gpu)
        with torch.no_grad():
            #z, c = self.model(x.unsqueeze(0))
            f, padding = self.model(x.unsqueeze(0))

        #return z.squeeze(0).cpu().numpy(), c.squeeze(0).cpu().numpy()
        return f.squeeze(0).cpu().numpy()
`
Is this what you mean by using extract_features()

Many thanks in advance!

**Comment by turian** [comment]
@alexeib In what work did you discuss extracting features from non-final transformer layers to capture different speech phenoma? "btw if you guys are extracting features from this model, you may want to try to extract features from various transformer layers, not just the last one. for example we found that features from middle layers most correspond to things like phones, as opposed to features from the last layer"

Thank you

**Comment by alexeib** [comment]
we have some hints of it in unsupervised asr work (https://arxiv.org/abs/2105.11084) and clustering (https://arxiv.org/abs/2102.01192), and there is also work by someone else that analyzes different layers of pretrained w2v models that is probably most relevant here: https://homepages.inf.ed.ac.uk/htang2/sigml/mlslp2021/MLSLP2021_paper_15.pdf
