### ISSUE TITLE
Cleaner generation output

### ISSUE THREAD

**Issue by munael** [pytorch/fairseq#2498]
## 🚀 Feature Request
Split generation output into two types:
1. Final scores
2. Text output and example model scores

Then add flags to manage them separately. For example, with option to write the text output (source, target, hypothesis, etc., with their scores) to a log file, and print the final scores (BLEU, and other such timestamped log lines) to stdout.

### Motivation

The final report is useful on its own (and can be requested alone by `--quiet`) and almost always useful to print to stdout. But the text output is almost never useful on stdout (we're talking about generation, not an interactive session). Separating the two types from the log file that includes both is unnecessary hassle.

### Pitch

1. Split output of `generate.py` and `interactive.py` into two types: timestamped aggregate logs, and the gen-subset output that includes source, target, hypothesis, scores, etc.
2. Add flags to manage them separately. E.g. write the example output to file but print the aggregate data to stdout.

### Alternatives

Not sure.

### Additional context

N/A

**Comment by myleott** [comment]
We have `--results-path` which does something like this: https://github.com/pytorch/fairseq/blob/77983ee1a52c4e011e54cc6bfa5352b7811ec96d/fairseq/options.py#L546-L547

I generally don't like splitting my generation output from the rest of the log file though. Inevitably someday you'll end up with just the output file and have no idea what model it was, what data it was run on, what the BLEU was, etc. (stuff that you get from the Namespace and summary output).

**Comment by myleott** [comment]
We have `--results-path` which writes to file, but doesn't split the outputs like you describe: https://github.com/pytorch/fairseq/blob/77983ee1a52c4e011e54cc6bfa5352b7811ec96d/fairseq/options.py#L546-L547

I generally don't like splitting my generation output from the rest of the log file though. Inevitably someday you'll end up with just the output file and have no idea what model it was, what data it was run on, what the BLEU was, etc. (stuff that you get from the Namespace and summary output).

But a simple bash script could accomplish what you want and could be useful to have in the `scripts/` directory. Something like (untested):
```bash
OUTDIR=$1
shift

fairseq-generate $@ > $OUTDIR/raw.out

# TODO sort the output to match the original ordering
grep ^S- $OUTDIR/raw.out > $OUTDIR/source
grep ^T- $OUTDIR/raw.out > $OUTDIR/target
grep ^H- $OUTDIR/raw.out > $OUTDIR/hypothesis
(...)
```

PRs welcome! :)
