### ISSUE TITLE
Errors when decoding with language model in wav2vec2.0

### ISSUE THREAD

**Issue by cywang97** [pytorch/fairseq#2502]
## 🐛 Bug
I am trying to reproduce the number in wav2vec2.0 paper with the released model.  The code works well when I set --w2l-decoder=viterbi to reproduce the CTC results. However, when I set --w2l-decoder='kenlm' or 'fairseqlm'. I met the following errors:

For Kenlm, I download the lm_librispeech_kenlm_word_4g_200kvocab.bin in https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/sota/2019. Running command 
'python examples/speech_recognition/infer.py /path/to/manifest/ --task audio_pretraining --nbest 1 --path /path/to/mymodel --gen-subset dev_clean --results-path /path/to/results --w2l-decoder kenlm --lm-model /path/to/lm_librispeech_word_transformer.pt --lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter'

The code reports error in line 137 "self.lexicon = load_words(args.lexicon)" in fairseq/examples/speech_recognition/w2l_decoder.py as args.lexicon is None. I can't find lexicon file in model repository. Can you upload it?

For Transformer, I download the released transformer language model and dictionary in wav2letter repository.
My command is 
'python examples/speech_recognition/infer.py /path/to/manifest/ --task audio_pretraining --nbest 1 --path /path/to/mymodel --gen-subset dev_clean --results-path /path/to/results --w2l-decoder fairseqlm --lm-model /path/to/lm_librispeech_word_transformer.pt --lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter'
There are several issues:
1. The arguments in the released model do not match the arguments defined in transformer_lm.py. For example, there is no args.decoder_layers_to_keep in lm_librispeech_word_transformer.pt. It seems the language model is not trained with the code in master branch.
2. I have tried to replace fairseq/models/transformer_lm.py and fairseq/models/transformer.py with the same files in branch v0.7.0.  The command didn't report errors. However, the hypothesis is too too bad (much worse than viterbi decoding)! Can you upload the pretrained model that compatible with master branch and give more details of hyperparameters?

### Environment
I use the docker wav2letter/wav2letter:cuda-latest

 - fairseq Version : master
 - PyTorch Version :  1.4.0
 - OS : Ubuntu18.04
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.9
 - CUDA/cuDNN version: 10.0

**Comment by MrityunjoyS** [comment]
Hi @cywang97 , I'm actually trying to use this wav2vec 2.0 model, to use as ASR, so that it can listen to the audio files and give an transcript of it as output, can you suggest how can I proceed with it ?
Thanks in advance..

**Comment by cywang97** [comment]
> Hi @cywang97 , I'm actually trying to use this wav2vec 2.0 model, to use as ASR, so that it can listen to the audio files and give an transcript of it as output, can you suggest how can I proceed with it ?
> Thanks in advance..

Hi, I think you can simply run the proposed decoding command with --w2l-decoder viterbi to get the raw number without language model.
The complete command is 'python examples/speech_recognition/infer.py /path/to/manifest/ --task audio_pretraining --nbest 1 --path /path/to/model --gen-subset dev_clean --results-path /path/to/results --w2l-decoder viterbi --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter'.
Please make sure you have python binding of wav2letter.
In your /path/to/manifest, you need to prepare the following files (take dev_clean subset as an example):
dev_clean.ltr
dev_clean.tsv
dev_clean.wrd.txt
dict.ltr.txt

**Comment by alexeib** [comment]
Here's the lexicon:
https://dl.fbaipublicfiles.com/fairseq/wav2vec/librispeech_lexicon.lst
I will link it in the readme soon

**Comment by MrityunjoyS** [comment]
Thanks @cywang97 for your response. I'll try it but have some doubts if you may help. In the command, how will I add my raw audio file without any labels, so that the model can create the transcript by itself and about " dev_clean.ltr, dev_clean.tsv, dev_clean.wrd.txt " are these the files that were created by "manifest" command using the pretrained Librispeech model ?

**Comment by alexeib** [comment]
that error is a bug recently introduced by constraints-based decoding. i'll push a fix through, meanwhile you can just checkout a copy of the code before that commit or you can change the signature of "generate" in w2l_decoder.py to 
```
def generate(self, models, sample, **unused):
```

**Comment by MrityunjoyS** [comment]
@alexeib thanks for the suggestion, it's working. 
But I'm still facing issue while trying to use kenlm LM. I've downloaded the **librispeech_lexicon.lst** as suggested by you, but my problem is still not solved, can you please help me on that

**Comment by MrityunjoyS** [comment]
Thanks @alexeib for quick response, really helped.

**Comment by aayagar001** [comment]
> Thanks @alexeib for quick response, really helped.

@MrityunjoyS What were the content for dev_clean.ltr,  dev_clean.wrd.txt . I could get tsv file from manifest but not able to know what will be content of these file. I am also trying to get text from raw audio file. Could you help with sample command or file?

**Comment by AmirHussein96** [comment]
> > Hi @cywang97 , I'm actually trying to use this wav2vec 2.0 model, to use as ASR, so that it can listen to the audio files and give an transcript of it as output, can you suggest how can I proceed with it ?
> > Thanks in advance..
> 
> Hi, I think you can simply run the proposed decoding command with --w2l-decoder viterbi to get the raw number without language model.
> The complete command is 'python examples/speech_recognition/infer.py /path/to/manifest/ --task audio_pretraining --nbest 1 --path /path/to/model --gen-subset dev_clean --results-path /path/to/results --w2l-decoder viterbi --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter'.
> Please make sure you have python binding of wav2letter.
> In your /path/to/manifest, you need to prepare the following files (take dev_clean subset as an example):
> dev_clean.ltr
> dev_clean.tsv
> dev_clean.wrd.txt
> dict.ltr.txt

@cywang97 Do you need the  wav2letter binding even when you do not use LM? I have finetuned the `Wav2Vec 2.0 Base` on 100h and it worked well. For inferenceI am running a similar command to yours but I do not have wav2letter binding 

` python examples/speech_recognition/infer.py examples/wav2vec/data/ --task audio_pretraining --nbest 1 --path examples/wav2vec/outputs/2021-01-03/21-08-21/checkpoints/checkpoint_best.pt --gen-subset dev_other --results-path examples/wav2vec/results/ --w2l-decoder=viterbi --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter `
 
and I am getting the following error

  main(args)
  File "examples/speech_recognition/infer.py", line 240, in main
    task.load_dataset(args.gen_subset, task_cfg=saved_cfg.task)
  File "/alt-arabic/speech/amir/fairseq/fairseq/tasks/audio_pretraining.py", line 135, in load_dataset
    task_cfg.autoregressive = not task_cfg.criterion == 'ctc'
  File "/home/local/QCRI/ahussein/anaconda3/envs/espnet/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 297, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/local/QCRI/ahussein/anaconda3/envs/espnet/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/home/local/QCRI/ahussein/anaconda3/envs/espnet/lib/python3.7/site-packages/omegaconf/_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "/home/local/QCRI/ahussein/anaconda3/envs/espnet/lib/python3.7/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/home/local/QCRI/ahussein/anaconda3/envs/espnet/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 295, in __getattr__
    return self._get_impl(key=key, default_value=DEFAULT_VALUE_MARKER)
  File "/home/local/QCRI/ahussein/anaconda3/envs/espnet/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 353, in _get_impl
    node = self._get_node(key=key)
  File "/home/local/QCRI/ahussein/anaconda3/envs/espnet/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 375, in _get_node
    self._validate_get(key)
  File "/home/local/QCRI/ahussein/anaconda3/envs/espnet/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 128, in _validate_get
    key=key, value=value, cause=ConfigAttributeError(msg)
  File "/home/local/QCRI/ahussein/anaconda3/envs/espnet/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/home/local/QCRI/ahussein/anaconda3/envs/espnet/lib/python3.7/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/home/local/QCRI/ahussein/anaconda3/envs/espnet/lib/python3.7/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'criterion' is not in struct
        full_key: task.criterion
        reference_type=Any
        object_type=dict
