### ISSUE TITLE
what's purpuse of nll_loss?

### ISSUE THREAD

**Issue by xu-song** [pytorch/fairseq#2504]
#### What is your question?

`loss_sum / sample_size` is the average loss for each token. `sample_size` is used as the denominator for the gradient.

what about `loss_sum / ntokens`

#### Code

https://github.com/pytorch/fairseq/blob/adbd89fd4be9e68100bf9a4ba9eed1e7fb2e4040/fairseq/criterions/sentence_prediction.py#L80-L83

**Comment by myleott** [comment]
If you have `--sentence-avg` then the loss will be normalized by the number of sentences.  In that case you may still want the token-level NLL loss, so we log that as an extra key :)
