### ISSUE TITLE
Problem About Changing the encoder_out 

### ISSUE THREAD

**Issue by cocaer** [pytorch/fairseq#251]
em... When I want to change the encoder_out in decode time,the program will go run.the error is

`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
`
The operation I done is like this:

`
    encoder_out[0][:,:,j] = do_something (encoder_out[0][:,:,j] )
`

So, does encoder_out  participate in gradient calculation and how can i change the encoder_out correctly?

**Comment by huihuifan** [comment]
You can't modify it in place like this, or PyTorch will have trouble automatically computing the gradient. You should copy the variable and modify it. encoder_out does participate in gradient calculation- the loss gets backpropagated to all those variables.

**Comment by cocaer** [comment]
@huihuifan Thanks a lot , you are right.
