### ISSUE TITLE
Model can't locate bindings, even after installation

### ISSUE THREAD

**Issue by MrityunjoyS** [pytorch/fairseq#2512]
I've successfully installed **Python Bindings**. :- 
```
****@**-gpu:~/wav2letter/bindings/python$ pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///path/wav2letter/bindings/python
Installing collected packages: wav2letter
  Running setup.py develop for wav2letter
Successfully installed wav2letter
```

Still  while running below command :- 

`****@**-gpu:~/wav2letter/bindings/python$ PYTHONPATH=/path/fairseq python3 examples/speech_recognition/infer.py /path/audio_file/wav2vec/ --task audio_pretraining --nbest 1 --path /path/audio_file/wav2vec_small.pt --gen-subset valid --results-path /path/audio_file/wav2vec/tmp/am/ --w2l-decoder viterbi --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter`

Getting below errors :- 

> INFO:fairseq.data.audio.raw_audio_dataset:loaded 29, skipped 0 samples
> INFO:__main__:| /path/audio_file/wav2vec/ valid 29 examples
> INFO:__main__:| decoding with criterion ctc
> INFO:__main__:| loading model(s) from /path/audio_file/wav2vec_small.pt
> /path/fairseq/examples/speech_recognition/w2l_decoder.py:39: UserWarning: wav2letter python bindings are required to use this functionality. Please install from https://github.com/facebookresearch/wav2letter/wiki/Python-bindings
>   "wav2letter python bindings are required to use this functionality. Please install from https://github.com/facebookresearch/wav2letter/wiki/Python-bindings"
> Traceback (most recent call last):                                                                                                            
>   File "examples/speech_recognition/infer.py", line 428, in <module>
>     cli_main()
>   File "examples/speech_recognition/infer.py", line 424, in cli_main
>     main(args)
>   File "examples/speech_recognition/infer.py", line 361, in main
>     hypos = task.inference_step(generator, models, sample, prefix_tokens)
>   File "/path/fairseq/fairseq/tasks/fairseq_task.py", line 400, in inference_step
>     return generator.generate(models, sample, prefix_tokens=prefix_tokens)
>   File "/path/fairseq/examples/speech_recognition/w2l_decoder.py", line 76, in generate
>     emissions = self.get_emissions(models, encoder_input)
>   File "/path/fairseq/examples/speech_recognition/w2l_decoder.py", line 84, in get_emissions
>     emissions = models[0].get_normalized_probs(encoder_out, log_probs=True)
>   File "/path/fairseq/fairseq/models/fairseq_model.py", line 53, in get_normalized_probs
>     return self.get_normalized_probs_scriptable(net_output, log_probs, sample)
>   File "/path/fairseq/fairseq/models/fairseq_model.py", line 74, in get_normalized_probs_scriptable
>     raise NotImplementedError
> NotImplementedError

Can you please suggest what might be the issue @alexeib  . Thanks in advance.

**Comment by alexeib** [comment]
i think you must have solved this since you had a different error in another issue, right?

**Comment by taiman9** [comment]
Hi @manthanthakker, did you solve this issue? I'm having the same issue after installing wav2letter bindings with CUDA enabled. Please let me know, thanks.

**Comment by taiman9** [comment]
Hi @MrityunjoyS , did you solve this issue? I'm having the same issue after installing wav2letter bindings with CUDA enabled. Please let me know, thanks.
