### ISSUE TITLE
Guidance on using FAIRseq for seq2seq tasks

### ISSUE THREAD

**Issue by neel04** [pytorch/fairseq#2513]
Hi, I want to use FairSeq for a custom seq2seq task but had a few doubts using it:- 

1. What is the format required for the dataset? I have a `.csv` file which has input corresponding to outputs. However, I found no mention in the docs that explicitly specify on what format data is going to be (I have never trained a model from command-line so am more used to customization). My plan was to split it into 2 separate files - one will have the inputs and the other will have the corresponding output w.r.t to the lines, but I don't see any parameters that allow training/preprocessing in such way. Can anyone clarify how exactly can I accomplish this? [BTW I have 500Mb file of data which has 10 million lines/data points].  Does it require tokenization on the fly?

2. Seeing the `fairseq-preprocess` docs, It seems that fairseq requires no tokenization. Now the HuggingFace tokenization library does not use GPU and thus takes a lot of time along with a LOT of memory. So does the `--tokenizer` or `--bpe` flag in the preprocessing step use GPU resources OR does it still utilize the standard CPU+RAM combination? I did try to train using the HF lib but would prefer GPU/TPU for the task. 

3. Lastly, in the TPU training section the `--tpu` flag has this doc:- "use TPU instead of CUDA". Is there any way to set which TPU strategy to use? the Distributed Training section only offers options for GPU training and not a way to set TPU  strategy. 

> Lastly, I would be extremely pleased if someone can specify what GPU time it took to train the FairSeq model. Please keep such refs. in the docs themselves so that people can at least have an idea of how much resources it would take to train it to a significant level. I am planning at using 10 hours of TPU v2 (180 TFLOP's) OR 3x v3 TPU's (480 TFLOPS) for 6 total TPUs hours. How much training I can accomplish with that?

**Comment by myleott** [comment]
Yes, it's fine to put any arbitrary suffixes, e.g., `.input` and `.output`.

**Comment by neel04** [comment]
Thanx a ton for your help. Just one last thing- I am starting my training phase, but from this link (https://fairseq.readthedocs.io/en/latest/command_line_tools.html#Model%20configuration) seems that there are plenty of model architectures.

Can you advise me which ones I should try first If I want to do 'seq2seq' for ciphers (Like an architecture particularly good for finding the relations between the sequences)? My model is basically one that extracts the plaintext out of ciphertext/encrypted text....

**Comment by neel04** [comment]
@myleott Hi, I am training my model on TPU device but am encountering this error:-

> 2020-08-25 13:00:20 | WARNING | root | TPU has started up successfully with version pytorch-1.6
> 
> WARNING:root:TPU has started up successfully with version pytorch-1.6
> Exception in device=TPU:0: 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
>     fn(gindex, *args)
>   File "/content/fairseq/fairseq/distributed_utils.py", line 150, in distributed_main
>     args.distributed_rank = distributed_init(args)
>   File "/content/fairseq/fairseq/distributed_utils.py", line 112, in distributed_init
>     assert xm.xrt_world_size() == args.distributed_world_size
> AssertionError
> Traceback (most recent call last):
>   File "/usr/local/bin/fairseq-train", line 33, in <module>
>     sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
>   File "/content/fairseq/fairseq_cli/train.py", line 333, in cli_main
>     distributed_utils.call_main(args, main)
>   File "/content/fairseq/fairseq/distributed_utils.py", line 185, in call_main
>     nprocs=8,  # use all 8 TPU cores
>   File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 296, in spawn
>     start_method=start_method)
>   File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
>     while not context.join():
>   File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 113, in join
>     (error_index, exitcode)
> Exception: process 0 terminated with exit code 17


I am trying to do a seq2seq problem and am using preprocessed data using the commands provided in FAIRseq docs. the data was preprocessed successfully, I am presumably running my code on a TPUv2 and have PyTorch along with `XLA` installed. In both the Tracebacks, the error does not clearly specify what exactly went wrong. This is the training code:-

`%%bash`
`fairseq-train /content/drive/'My Drive'/HashPro/preprocessed/ \`
`    --lr 0.02 --clip-norm 0.1 --optimizer sgd --bpe characters --dropout 0.2 --tpu --bf16\  `
`    --arch bart_large --save-dir /content/drive/'My Drive'/HashPro/Checkpoints/`

Any ideas on what the problem might be?

**Comment by rajgar114** [comment]
Hi @neel04 ,

I also have the similar type of sequence to sequence task in which I have a CSV file consisting of two columns Input & Output. Can you please share your code or guide me how I can pre-process the data, fine-tune the fairseq model and what other steps need to be done to get the results. Also explain what models you have tried for your tasks and if possible the results too.

**Comment by neel04** [comment]
I ditched `fairseq` in the end - it's too heavy and buggy for my needs. I would recommend using some repo for the model and writing your own wrapper since it would be faster and easier than this. FAIR really needs to put a lot of work in this; nor is this library easy-to-use nor do heavy professionals have an actual use for this.

**Comment by rajgar114** [comment]
Thanks for your suggestion @neel04. I also feel its buggy & erroneous. So, I will explore other libraries.
