### ISSUE TITLE
Wav2Vec 2.0 change dict.ltr.txt 

### ISSUE THREAD

**Issue by karanglass34** [pytorch/fairseq#2514]
#### What is your question?
I am trying to use wav2vec for other languages like french. How can I modify the dict.ltr.txt so that I can accommodate extra characters for Automatic Speech Recognition? 

#### Code
Also, the dictionary is something like this:

```
| 94802
E 51860
T 38431
A 33152
O 31495
N 28855
I 28794
H 27187
S 26071
R 23546
D 18289
L 16308
U 12400
...
```
What does the second number mean? Is this a word count in the training corpus/data? Is this generated from any script dynamically? Any references would be really helpful. 

Thanks in advance!

**Comment by alexeib** [comment]
if you are finetuning a pre-trained model on another dataset then yes you can certainly create a new dictionary. i used fairseq's "preprocess.py" but you can also create them by hand if you'd like, with one symbol per line. doesnt have to be letters, this also works with e.g. bpe or sentence pieces if you prefer.

for preprocess i did something like this
```
python preprocess.py --dataset-impl mmap --trainpref train.txt  --only-source  --thresholdsrc 0
```
and then just deleted the bin and idx files it created

the 2nd line is the count of each symbol but its not actually used. you can just put any number youd like there.

**Comment by Adportas** [comment]
> if you are finetuning a pre-trained model on another dataset then yes you can certainly create a new dictionary. i used fairseq's "preprocess.py" but you can also create them by hand if you'd like, with one symbol per line. doesnt have to be letters, this also works with e.g. bpe or sentence pieces if you prefer.
> 
> for preprocess i did something like this
> 
> ```
> python preprocess.py --dataset-impl mmap --trainpref train.txt  --only-source  --thresholdsrc 0
> ```
> 
> and then just deleted the bin and idx files it created
> 
> the 2nd column is the count of each symbol but its not actually used. you can just put any number youd like there.

In the first column, the order of the letters is associated with the probability of occurrence or is any one, for example alphabet?
