### ISSUE TITLE
Why does the non autoregresive transfomer model in fairseq require the prev_output_tokens input?

### ISSUE THREAD

**Issue by ophiry** [pytorch/fairseq#2515]
[fairseq][1] includes an implementation of a non autoregressive transformer - which (as much as I understand) means that the whole output sequence is generated in a single forward run (in contrast to autoregresive models where each forward run predicts the next token from the input and the previous predicted tokens)

However, from the code it appears that the models still expects the previous tokens as input:

    def forward(self, src_tokens, src_lengths, prev_output_tokens, tgt_tokens, **kwargs)
https://github.com/pytorch/fairseq/blob/master/fairseq/models/nat/nonautoregressive_transformer.py#L78

why is it needed? what data should be provided?
(I plan to use it a a standalone pytorch model, not within the fairseq framework)

  [1]: https://github.com/pytorch/fairseq

(also posted here: https://datascience.stackexchange.com/q/80682/6436)

**Comment by lematt1991** [comment]
Looks like this was answered on stackexchange.  If you still have questions, please open a new issue.  Thanks!
