### ISSUE TITLE
"Batch" vs. "for loops" in trainer.py `train_step`

### ISSUE THREAD

**Issue by priyamtejaswin** [pytorch/fairseq#2517]
## ❓ Questions and Help

Hi folks,
Asking this because it was not obviously clear to me.

I'm a long-time Tfv1+Keras user who has been exploring PyTorch, mostly via Fairseq.
I came across this piece of code in [`def train_step`, trainer.py](https://github.com/pytorch/fairseq/blob/master/fairseq/trainer.py#L405)
```python
        # forward and backward pass
        logging_outputs, sample_size, ooms = [], 0, 0
        for i, sample in enumerate(samples):
            sample = self._prepare_sample(sample)
```

I believe that `samples` here is a batch of size `UPDATE_FREQ`.
From some of the examples on the PyTorch website (and from past experience), I assumed that a batch of samples would be processed by the model as a single entity, and not in a per-sample manner.

I was just wondering:
(1) why this choice was made?
(2) is there any impact on the training speed?

Thanks for your time.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0) 1.6
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.10

**Comment by alexeib** [comment]
a sample is a some number of individual examples collated by the dataset/dataloader (this is a common practice with pytorch) representing all of the input processed in a single forward and backward pass. inside this sample you'll see a dictionary where values are most likely tensors with the first dimension usually being the batch dimension. so they will be processed by the model as a single entity :)

**Comment by priyamtejaswin** [comment]
Yup. Just checked 😅 .
Thanks for clearing this up, @alexeib !
