### ISSUE TITLE
What is incremental_state?

### ISSUE THREAD

**Issue by robertodessi** [pytorch/fairseq#252]
I am trying to understand the decoder in the fconv architecture and I am wondering what does the incremental_state variable do and what values does it hold when doing inference? Is it not used at all at training time?

Thanks in advance

**Comment by myleott** [comment]
Please see my comment here: https://github.com/pytorch/fairseq/issues/166#issuecomment-392259850

Let me know if you have any more questions about it!

**Comment by ankur6ue** [comment]
I wrote up a blog post that describes some of what the incremental_decoder does:
http://www.telesens.co/2019/04/21/understanding-incremental-decoding-in-fairseq
