### ISSUE TITLE
Running trained models in interactive mode

### ISSUE THREAD

**Issue by reubenharry** [pytorch/fairseq#253]
I followed the steps on the fairseq readme to train a de-en translator, and it seems to have worked (using generate.py gives sane results), but I get odd results when I try the interactive mode with the following command, which make me wonder if something is going wrong:

python interactive.py data-bin/iwslt14.tokenized.de-en   --path checkpoints/fconv/checkpoint_best.pt  --beam 5 --source de --target en

For instance, for "Wie heißen Sie?" I get "that &apos;s what happens to be ." and for "Der Hund ist groß." I get "it &apos;s a lot of time .". 

Relatedly, are other pre-trained translation models are available than those on the github page?

Thanks so much!

Reuben

**Comment by myleott** [comment]
The training dataset was probably preprocessed with BPE, so you'll need to apply BPE before feeding the input to interactive.py. You can do something similar to this: https://github.com/pytorch/fairseq/blob/af38ed48bb88cc489d1251e16519c7eef3a2fba7/examples/translation/prepare-iwslt14.sh#L113

**Comment by reubenharry** [comment]
The data was preprocessed with BPE, so that makes sense, but the pretrained English-French model was also trained on BPE data and inputting normal text doesn't make much of a difference to quality, whereas I'm getting nonsense. Maybe it's different for German - I'll try using BPE and let you know.

Thanks!!

**Comment by reubenharry** [comment]
Hmm, there's still some sort of issue. Using the BPE, I enter "M@@ ein N@@ ame ist J@@ o@@ hn ." and get "so , the other thing is , it &apos;s a ne@@ ck ."

(having run: python interactive.py data-bin/iwslt14.tokenized.de-en   --path checkpoints/fconv/checkpoint_best.pt    --beam 5 --source de --target en)

**Comment by myleott** [comment]
Yep, we lowercase IWSLT, which seems to be standard practice on this dataset: https://github.com/pytorch/fairseq/blob/master/examples/translation/prepare-iwslt14.sh#L67
