### ISSUE TITLE
Sharding an already Pre-processed data-bin for training

### ISSUE THREAD

**Issue by hichiaty** [pytorch/fairseq#2533]
Hi, 

So I have some CPU and GPU machines, the CPU machines have more RAM. 

I have managed to Preprocess my full training data with mmap indexing and Lazy Loading into 1 data-bin, but when I attempt to do distributed training on the GPU machines I run out of CPU RAM, I believe my only other option is sharding. Must I re-pre-process my data in shards or can I just load in shards? (pre-processing took a week so would prefer if I didn't have to).

**Comment by myleott** [comment]
Did you install pyarrow? `pip install pyarrow` might improve the memory situation.

Also, how big is the dataset? How much CPU RAM do you have and how many GPUs are sharing that CPU RAM?

**Comment by hichiaty** [comment]
@myleott Yes I do have pyarrow installed. my dataset is 1 186GB binarized file (after being encoded with Sentencepiece), on my preprocessing machine I have 260GB RAM, no GPUs, On my 4 GPU nodes I have 4 GPUs in each node, with 30GB CPU RAM/Node.

**Comment by hichiaty** [comment]
Just sharded the data and re-processed.
