### ISSUE TITLE
how to share encoder input and output embeddings and some defination question

### ISSUE THREAD

**Issue by naginoa** [pytorch/fairseq#2537]
## 🚀 Feature Request
how to share encoder input and output embeddings

### Motivation

There are only two commands about sharing embedding but no sharing encoder:
"--share-decoder-input-output-embed" and "--share-all-embeddings"

### Pitch

I want to make the experiment about only sharing decoder and only sharing encoder. 

### Additional context

I’m sorry that the explanation of the document about sharing embeddings is not so clear for me.
'--share-all-embeddings' mean share all the embeddings weighted matrix and "--share-decoder-input-output-embed" means share the weighted matrix of input and output embeddings of decoder? right?

thanks a lot!

**Comment by alexeib** [comment]
thats right, when you specify --share-all-embeddings then the embedding matrices for encoder input, decoder input and decoder output are all shared. when you specify --share-decoder-input-output-embed, then the matrices for decoder input and output are shared, but encoder has its own embeddings. does this help?

**Comment by naginoasukara** [comment]
It does help me a lot! Thank you very much！
But I still wonder if I can share only encoder embedding, but the decoder has its own embeddings.
Thanks a lot!

**Comment by alexeib** [comment]
what does sharing encoder embeddings mean? encoder only has input embeddings - what would you share them with?

**Comment by dxli94** [comment]
Would it make any sense if just sharing the encoder input and decoder input, while leaving decoder output separate? I am wondering whether this would be of any use for seq2seq problem using monolingual language?
