### ISSUE TITLE
size mismatch for w2v_encoder while loading pretrained model(wav2vec2.0)

### ISSUE THREAD

**Issue by MorrisXu-Driving** [pytorch/fairseq#2539]
#### What is your question?
RuntimeError: Error(s) in loading state_dict for Wav2VecCtc:
        size mismatch for w2v_encoder.proj.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([512, 768]).
        size mismatch for w2v_encoder.proj.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
#### Code
python train.py /data/home/v_liwenxu/data/LibriSpeech/train-pipeline/data/ \
--save-dir /data/home/v_liwenxu/data/LibriSpeech/train-pipeline/models/ --fp16 \
--post-process letter --valid-subset /data/home/v_liwenxu/data/LibriSpeech/train-pipeline/data/libris-train \
--no-epoch-checkpoints --best-checkpoint-metric wer --num-workers 4 \
--max-update 80000 --sentence-avg --task audio_pretraining --arch wav2vec_ctc --w2v-path /data/home/v_liwenxu/data/LibriSpeech/train-pipeline/models/wav2vec_small_960h.pt \
--labels ltr --apply-mask --mask-selection static --mask-other 0 --mask-length 10 --mask-prob 0.5 --layerdrop 0.1 \
--mask-channel-selection static --mask-channel-other 0 --mask-channel-length 64 --mask-channel-prob 0.5 --zero-infinity \
--feature-grad-mult 0.0 --freeze-finetune-updates 10000 --validate-after-updates 10000 --optimizer adam \
--adam-betas '(0.9, 0.98)' --adam-eps 1e-08 --lr 2e-05 --lr-scheduler tri_stage --warmup-steps 8000 --hold-steps 32000 \
--decay-steps 40000 --final-lr-scale 0.05 --final-dropout 0.0 --dropout 0.0 --activation-dropout 0.1 --criterion ctc \
--attention-dropout 0.0 --max-tokens 1280000 --seed 2337 --log-format json --log-interval 500 --ddp-backend no_c10d

I am trying to fine-tune the pre-trained model in wav2vec2.0，wav2vec_small_960h.pt ，specifically. However, while I ran the above code, the following error emerged.:
Traceback (most recent call last):
  File "/data/home/v_liwenxu/miniconda3/envs/mirex/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/data1/home/v_liwenxu/fairseq/fairseq/distributed_utils.py", line 156, in distributed_main
    main(args, **kwargs)
  File "/data1/home/v_liwenxu/fairseq/fairseq_cli/train.py", line 67, in main
    model = task.build_model(args)
  File "/data1/home/v_liwenxu/fairseq/fairseq/tasks/fairseq_task.py", line 248, in build_model
    model = models.build_model(args, self)
  File "/data1/home/v_liwenxu/fairseq/fairseq/models/__init__.py", line 48, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
  File "/data1/home/v_liwenxu/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 168, in build_model
    w2v_encoder = Wav2VecEncoder(args, task.target_dictionary)
  File "/data1/home/v_liwenxu/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 345, in __init__
    model.load_state_dict(state["model"], strict=True)
  File "/data1/home/v_liwenxu/fairseq/fairseq/models/fairseq_model.py", line 93, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/data/home/v_liwenxu/miniconda3/envs/mirex/lib/python3.6/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Wav2VecCtc:
        size mismatch for w2v_encoder.proj.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([512, 768]).
        size mismatch for w2v_encoder.proj.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).

I really have no idea how to fix this problem, could anyone help?

**Comment by alexeib** [comment]
the model you are trying to finetune is itself a finetuned model. what you probably want is to download the model with "no finetuning", and finetune that instead. or if you want to continue training a model that has already been fine-tuned, then you can just use it as a checkpoint (--restore-file /path/to/model), and dont forget to set the various --reset-x flags as well

**Comment by zilunpeng** [comment]
Did you manage to solve this problem? I tried to --restore-file and --reset and still get this error.....

**Comment by alexeib** [comment]
actually i guess someone added a --finetune-from-model arg that resets all the relevant things, so maybe you can try using that (if you are finetuning a finetuned model)

**Comment by tarang-jain** [comment]
Hello @alexeib ! I am trying to fine-tune an already fine-tuned wav2vec 2.0 base model (wav2vec 2.0 base model fine tuned on 100 hours of librispeech). However, I am trying to fine-tune it on a different language and therefore with a different dict.ltr.txt. So the dimensions of the final output layer would of course be different. I want that layer to be replaced with the new dimensions for my new letter targets, but I wish to fine-tune the layers before that by starting from the already fine-tuned model. Can this be done?
Also, I am facing the same error as above even with the --fine-tune-from-model arg and with the --restore-file arg. 
RuntimeError: Error(s) in loading state_dict for Wav2VecCtc:
size mismatch for w2v_encoder.proj.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([512, 768]).
size mismatch for w2v_encoder.proj.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).

Please help me solve these two problems.

**Comment by alexeib** [comment]
i would suggest finetuning the pretrained ("no finetuning") model instead of one that has been already finetuned for english.

however to do what you are trying to do, you can just modify the code in wav2vec2_asr.py to load the weights in non-strict mode - either modify or create an alternative to load_checkpoint_to_cpu where torch.load is called with strict=False flag. for example you can add "strict" argument to load_checkpoint_to_cpu defaulted to True and change this:
```
    with PathManager.open(path, "rb") as f:
        state = torch.load(
            f, map_location=lambda s, l: default_restore_location(s, "cpu"), strict=False
        )
```

**Comment by spygaurad** [comment]
> Hello @alexeib ! I am trying to fine-tune an already fine-tuned wav2vec 2.0 base model (wav2vec 2.0 base model fine tuned on 100 hours of librispeech). However, I am trying to fine-tune it on a different language and therefore with a different dict.ltr.txt. So the dimensions of the final output layer would of course be different. I want that layer to be replaced with the new dimensions for my new letter targets, but I wish to fine-tune the layers before that by starting from the already fine-tuned model. Can this be done?
> Also, I am facing the same error as above even with the --fine-tune-from-model arg and with the --restore-file arg.
> RuntimeError: Error(s) in loading state_dict for Wav2VecCtc:
> size mismatch for w2v_encoder.proj.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([512, 768]).
> size mismatch for w2v_encoder.proj.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
> 
> Please help me solve these two problems.

@tarang-jain have you solved this issue.
