### ISSUE TITLE
Can you sample from the LM models?

### ISSUE THREAD

**Issue by hughbzhang** [pytorch/fairseq#254]
Question in title.

**Comment by myleott** [comment]
You can try patching this PR: #215. @amrsharaf any status on that? :)

**Comment by hughbzhang** [comment]
Thanks Myle! is this PR ready to use?

**Comment by amrsharaf** [comment]
So sorry for being late on this. I'll have more time next week. I'm hoping
to address the comments in this PR by end of next week. I'll update the
encoder incremental state function call and run all the tests again.

**Comment by hughbzhang** [comment]
I saw that there was a commit. Is this functionality now ready to use? Thanks a bunch in advance!

**Comment by myleott** [comment]
This is merged. You can use interactive.py.
