### ISSUE TITLE
importlib_metadata.PackageNotFoundError: No package metadata was found for fairseq

### ISSUE THREAD

**Issue by tmtmaj** [pytorch/fairseq#2546]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

Hi, I am trying to use the fairseq toolkit in google colab notebook.

I installed and ran the fairseq tookit without any problems until yesterday, but an error suddenly occurs today.

"importlib_metadata.PackageNotFoundError: No package metadata was found for fairseq"

#### Code

install 

```
!git clone https://github.com/pytorch/fairseq
%cd /content/fairseq
!pip install --editable ./
%cd /content
```

install log

```
Cloning into 'fairseq'...
remote: Enumerating objects: 17478, done.
remote: Total 17478 (delta 0), reused 0 (delta 0), pack-reused 17478
Receiving objects: 100% (17478/17478), 7.99 MiB | 27.91 MiB/s, done.
Resolving deltas: 100% (12926/12926), done.
/content/fairseq
Obtaining file:///content/fairseq
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from fairseq==0.9.0) (4.41.1)
Requirement already satisfied: editdistance in /usr/local/lib/python3.6/dist-packages (from fairseq==0.9.0) (0.5.3)
Requirement already satisfied: regex in /usr/local/lib/python3.6/dist-packages (from fairseq==0.9.0) (2019.12.20)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from fairseq==0.9.0) (1.18.5)
Requirement already satisfied: torch in /usr/local/lib/python3.6/dist-packages (from fairseq==0.9.0) (1.6.0+cu101)
Collecting sacrebleu
  Downloading https://files.pythonhosted.org/packages/23/d3/be980ad7cda7c4bbfa97ee3de062fb3014fc1a34d6dd5b82d7b92f8d6522/sacrebleu-1.4.13-py3-none-any.whl (43kB)
     |████████████████████████████████| 51kB 1.6MB/s 
Requirement already satisfied: cython in /usr/local/lib/python3.6/dist-packages (from fairseq==0.9.0) (0.29.21)
Requirement already satisfied: cffi in /usr/local/lib/python3.6/dist-packages (from fairseq==0.9.0) (1.14.2)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from torch->fairseq==0.9.0) (0.16.0)
Collecting portalocker
  Downloading https://files.pythonhosted.org/packages/89/a6/3814b7107e0788040870e8825eebf214d72166adf656ba7d4bf14759a06a/portalocker-2.0.0-py2.py3-none-any.whl
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi->fairseq==0.9.0) (2.20)
Installing collected packages: portalocker, sacrebleu, fairseq
  Running setup.py develop for fairseq
Successfully installed fairseq portalocker-2.0.0 sacrebleu-1.4.13
/content
```

preprocess

```
!fairseq-preprocess \ 
    --source-lang en --target-lang de \
    --trainpref /content/train \
    --validpref /content/valid \
    --testpref /content/test \
    --destdir /content/preprocess_data \
    --workers 32
```

preprocess log

```
Traceback (most recent call last):
  File "/usr/bin/fairseq-preprocess", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-preprocess')())
  File "/usr/bin/fairseq-preprocess", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 558, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 215, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for fairseq
```

Does anyone know how to solve it?

   

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.6.0+cu101
 - OS (e.g., Linux):Ubuntu
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version: Python 3.6.9
 - CUDA/cuDNN version: 10.1 
 - GPU models and configuration:Tesla P100
 - Any other relevant information: I run the code in google colab

**Comment by masonreznov** [comment]
Mount to your gooogle drive and install fairseq in your drive itself. That works for me.

**Comment by masonreznov** [comment]
I ran into similar problem. Untill yesterday everything was running fine. Moreover, I didn't update the fairseq repo. So, I guess the problem is with google colab.

**Comment by tmtmaj** [comment]
@masonreznov I think there's a problem with Google colab, too. I tried to install it from pip, but there's another error. 

```
Traceback (most recent call last):
  File "/content/fairseq_contrastive_attn/fairseq-master/fairseq_cli/generate.py", line 18, in <module>
    from fairseq.logging import progress_bar
ModuleNotFoundError: No module named 'fairseq.logging'
```

I think there's something wrong with setting path. Have you solved it?

**Comment by masonreznov** [comment]
I've just checked it, the installation from `pip` works as of now. Could you please uninstall the previously installed fairseq and then re-install.

**Comment by tmtmaj** [comment]
@masonreznov thank you. that's work on me. After installing it from pip, I was able to execute the code.  
`!pip install fariseq
!Fairseq-preprocess`

But I'm modifying the code to test some new approach.
so, I have to run "!python /content/fairseq/fairseq_cli/preprocess.py" instead of "fairseq-preprocess". 

`!git clone https://github.com/pytorch/fairseq
%cd /content/fairseq
!pip install --editable ./
%cd /content`

`!python /content/fairseq/fairseq_cli/preprocess.py` still not working..

Is there any other solution?

**Comment by avecama23** [comment]
> I've just checked it, the installation from `pip` works as of now. Could you please uninstall the previously installed fairseq and then re-install.

I got the same error today. I tried !pip install fariseq,  but I get 

ERROR: Could not find a version that satisfies the requirement fariseq (from versions: none)
ERROR: No matching distribution found for fariseq

Can you please tell me what I'm doing wrong??

**Comment by alexeib** [comment]
you can just point to your working fairseq dir with PYTHONPATH=/path/to/fairseq
```
!pip install fariseq !Fairseq-preprocess
```
you have a typo here, its "fairseq"

the error about logging means you have an older version of fairseq somewhere in your path

**Comment by tmtmaj** [comment]
@alexeib thank you. that's work!  I added '/content/fairseq/' to PYTHONPATH and it was able to run it.

```
!!git clone https://github.com/pytorch/fairseq
%cd /content/fairseq/
!python -m pip install --editable .
%cd /content

! echo $PYTHONPATH

import os
os.environ['PYTHONPATH'] += ":/content/fairseq/"

! echo $PYTHONPATH
```
