### ISSUE TITLE
Unable to run inference on raw text using Prophetnet model

### ISSUE THREAD

**Issue by tc9sachin12** [pytorch/fairseq#2547]
I have been trying to run inference using the finetuned model of Prophetnet provided [here](https://github.com/microsoft/ProphetNet#checkpoint-1)

I used the preprocessing step mentioned [here](https://github.com/microsoft/ProphetNet#data-preprocess-2) with --only-source argument. I got three files namely 'dict.src.txt' , 'valid.src-tgt.src.bin' and 'valid.src-tgt.src.idx'.

I used the following code to run preprocessing step:
fairseq-preprocess --user-dir src_files/prophetnet --task translation_prophetnet --source-lang src --target-lang tgt --validpref input/dev --destdir gigaword/processed --srcdict src_files/vocab.txt --tgtdict src_files/vocab.txt

the folder src_files contains the files downloaded from the git repo https://github.com/microsoft/ProphetNet

Now when i try to inference using the checkpoint mentioned [here](https://github.com/microsoft/ProphetNet#checkpoint-1) with the inference code mentioned [here](https://github.com/microsoft/ProphetNet#inference-and-evaluation-1) i am getting the following error:

The code:
fairseq-generate gigaword/processed --path $CHECK_POINT --user-dir src_files/prophetnet --task translation_prophetnet --gen-subset valid --beam $BEAM --num-workers 4 --min-len 60 --max-len-b 120 --no-repeat-ngram-size 3 --lenpen $LENPEN 2>&1> $OUTPUT_FILE

Traceback (most recent call last):
  File "/mnt/vol1/anaconda3/bin/fairseq-generate", line 10, in <module>
    sys.exit(cli_main())
  File "/mnt/vol1/anaconda3/lib/python3.7/site-packages/fairseq_cli/generate.py", line 199, in cli_main
    main(args)
  File "/mnt/vol1/anaconda3/lib/python3.7/site-packages/fairseq_cli/generate.py", line 33, in main
    task.load_dataset(args.gen_subset)
  File "/mnt/vol1/anaconda3/lib/python3.7/site-packages/fairseq/tasks/translation.py", line 219, in load_dataset
    truncate_source=self.args.truncate_source,
  File "/mnt/vol1/anaconda3/lib/python3.7/site-packages/fairseq/tasks/translation.py", line 96, in load_langpair_dataset
    tgt_dataset, tgt_dataset.sizes, tgt_dict,
AttributeError: 'NoneType' object has no attribute 'sizes'

Kindly note, i do not want to train any model, rather just run inference and check the performance of the model.

**Comment by lematt1991** [comment]
Can you open an issue in their repo: https://github.com/microsoft/ProphetNet
