### ISSUE TITLE
Multilingual XLSR model availability? (wav2vec2)

### ISSUE THREAD

**Issue by craigbaker** [pytorch/fairseq#2548]
The paper [Unsupervised Cross-lingual Representation Learning for Speech Recognition](https://arxiv.org/abs/2006.13979) describes training the wav2vec2 model with multilingual data (Mozilla CommonVoice and other datasets), rather than just English data as in the wav2vec2 models available already in fairseq. I notice that several authors are the same (including @alexeib), and they mention that the model was developed in fairseq. I wonder if they might consider making the pretrained models public?

Thank you for releasing the wav2vec2 models. I've tried finetuning them on other languages, and as expected (from the cross-language monolingual experiments described in the XLSR paper, table 1), the performance is worse on languages other than English, especially lower-resource ones. I think a multilingual pretrained model would be very valuable to a wider community, in addition to the already valuable English models.

**Comment by alexeib** [comment]
this should be coming soon

**Comment by SeunghyunSEO** [comment]
> this should be coming soon

CANT WAIT TO USE THAT MODEL !

**Comment by aconneau** [comment]
Hey @SeunghyunSEO,

just wanted to make sure you had the chance to take a look at our XLSR-53 model that we release a few weeks ago :). I hope this will be useful to the applications you are considering. You can expect additional releases of such models in the future.

Best,
Alexis

**Comment by AmirHussein96** [comment]
Where can we find the config.yaml file for the  XLSR-53?
Thank you.

**Comment by Gorodecki** [comment]
@alexeib it would be nice to see this config file.
Thank you!

**Comment by alexeib** [comment]
unfortunately i dont have a config as those models were trained on an older branch, but you should be able to reconstruct it pretty easily by looking at args/cfg in the checkpoint dict

**Comment by Gorodecki** [comment]
@alexeib Thank's!
