### ISSUE TITLE
how to utilise multiple GPUs at the time of inference for MT?

### ISSUE THREAD

**Issue by kaushal0494** [pytorch/fairseq#2549]
#### What is your question?

 I have Nvidia 4 V100 GPUs. I observed that during inference (either `generate.py` or `interactive.py`) only one GPU is utilized and others remain ideal. Is there a possible way to utilize the other three GPUs as well at the inference time? Thank you!

**Comment by huihuifan** [comment]
No, currently inference only runs on one GPU. You can pass a shard-id and run generate and interactive on multiple gpus by sharding the dataset, but it won't automatically run on multiple

**Comment by kaushal0494** [comment]
Thank you @huihuifan

**Comment by FayZ676** [comment]
@huihuifan @kaushal0494 is this still the case, or is there support for multi gpu inference?
