### ISSUE TITLE
infer.py in speech recognition example

### ISSUE THREAD

**Issue by sooftware** [pytorch/fairseq#2550]
infer.py in speech recognition example, line 288, return super().build_generator(args).  
But super() is impossible because it is not a class but a function.  
I have to face line 298 because I don't use wav2letters.   
Or should I set up another w2l_decoder?  
  
Thank You.

**Comment by Lineldor** [comment]
Hi, have you solved this problem?

**Comment by sooftware** [comment]
yes, Are you in the same situation as me?

**Comment by Lineldor** [comment]
Yeah, I have encountered the same problem. If I don't use any decoder, can I run infer.py without this error?

**Comment by sooftware** [comment]
I was modified and used as an old commit on infer.py. infer.py now has to install wav2letters and set --w2ldecoder as viterbi.

**Comment by Lineldor** [comment]
Oh, thanks!
