### ISSUE TITLE
get_normalized_probs_scriptable seems broken

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/fairseq#2554]
https://github.com/pytorch/fairseq/blob/2887663/fairseq/models/fairseq_model.py#L59:
```python
  def get_normalized_probs_scriptable(
        self,
        net_output: Tuple[Tensor, Optional[Dict[str, List[Optional[Tensor]]]]],
        log_probs: bool,
        sample: Optional[Dict[str, Tensor]] = None,
    ):
        """Scriptable helper function for get_normalized_probs in ~BaseFairseqModel"""
        if hasattr(self, "decoder"):
            return self.decoder.get_normalized_probs(net_output, log_probs, sample)
        elif torch.is_tensor(net_output):
            logits = net_output.float()
            if log_probs:
                return F.log_softmax(logits, dim=-1)
            else:
                return F.softmax(logits, dim=-1)
        raise NotImplementedError
```

It accepts `net_output` as tuple and later checks it to be a tensor. Is it okay?

**Comment by huihuifan** [comment]
What error message are you experiencing? are you on the latest version of fairseq?

**Comment by myleott** [comment]
Yeah this looks off. Probably didn't get fully updated when we added types for torchscript.

**Comment by spygaurad** [comment]
@vadimkantorov  I am also facing the same problem.
How did you solve this issue? Which code path did you use for inferencing ?

**Comment by Shridharkrishna** [comment]
Hello, @myleott  how to solve the above issue I am also facing the same issue.
