### ISSUE TITLE
What is the raw input and vector size of wav2vec2?

### ISSUE THREAD

**Issue by shamoons** [pytorch/fairseq#2556]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
How much time does each vector correspond to in the pretrained wav2vec 2.0 models? And what is the vector dimension. I read through paper 3 times and can’t figure it out. 

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by alexeib** [comment]
we have this in the pretraining section:

![image](https://user-images.githubusercontent.com/3497946/92188874-9aabe500-ee12-11ea-8a9a-d6df9c5a8d0c.png)

so for each 1 second of audio, you get about 49 timesteps

hope this helps.
