### ISSUE TITLE
Dataset not found even though all files are present

### ISSUE THREAD

**Issue by neel04** [pytorch/fairseq#2558]
Hi all!
I was training a seq2seq model for a specific task (In same language) however I am getting this error:-
```
Namespace(activation_fn='gelu', adaptive_softmax_cutoff=None, adaptive_softmax_dropout=0, arch='bart_large', attention_dropout=0.0, best_checkpoint_metric='loss', bpe=None, bucket_cap_mb=25, clip_norm=0.1, cpu=False, criterion='cross_entropy', cross_self_attention=False, curriculum=0, data='/content/drive/My Drive/HashPro/preprocessed', dataset_impl=None, ddp_backend='c10d', decoder_attention_heads=16, decoder_embed_dim=1024, decoder_embed_path=None, decoder_ffn_embed_dim=4096, decoder_input_dim=1024, decoder_layerdrop=0, decoder_layers=12, decoder_layers_to_keep=None, decoder_learned_pos=True, decoder_normalize_before=False, decoder_output_dim=1024, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, dropout=0.2, empty_cache_freq=0, encoder_attention_heads=16, encoder_embed_dim=1024, encoder_embed_path=None, encoder_ffn_embed_dim=4096, encoder_layerdrop=0, encoder_layers=12, encoder_layers_to_keep=None, encoder_learned_pos=True, encoder_normalize_before=False, fast_stat_sync=False, find_unused_parameters=False, fix_batches_to_gpus=False, fixed_validation_seed=None, force_anneal=None, fp16=True, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, keep_interval_updates=-1, keep_last_epochs=-1, layer_wise_attention=False, layernorm_embedding=True, lazy_load=False, left_pad_source='True', left_pad_target='False', load_alignments=False, log_format=None, log_interval=1000, lr=[0.02], lr_scheduler='fixed', lr_shrink=0.1, max_epoch=0, max_sentences=8, max_sentences_valid=8, max_source_positions=1024, max_target_positions=1024, max_tokens=None, max_tokens_valid=None, max_update=0, maximize_best_checkpoint_metric=False, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=-1, momentum=0.0, no_cross_attention=False, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_save=False, no_save_optimizer_state=False, no_scale_embedding=True, no_token_positional_embeddings=False, num_workers=1, optimizer='sgd', optimizer_overrides='{}', pooler_activation_fn='tanh', pooler_dropout=0.0, raw_text=False, relu_dropout=0.0, required_batch_size_multiple=8, reset_dataloader=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', save_dir='/content/drive/My Drive/HashPro/Checkpoints/', save_interval=1, save_interval_updates=0, seed=1, sentence_avg=False, share_all_embeddings=True, share_decoder_input_output_embed=True, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, task='translation', tensorboard_logdir='', threshold_loss_scale=None, tokenizer=None, train_subset='train', truncate_source=False, update_freq=[1], upsample_primary=1, use_bmuf=False, user_dir=None, valid_subset='valid', validate_interval=1, warmup_updates=0, weight_decay=0.0)
| [input] dictionary: 21936 types
| [output] dictionary: 9216 types

Traceback (most recent call last):
  File "/usr/local/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/usr/local/lib/python3.6/dist-packages/fairseq_cli/train.py", line 333, in cli_main
    main(args)
  File "/usr/local/lib/python3.6/dist-packages/fairseq_cli/train.py", line 48, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=0)
  File "/usr/local/lib/python3.6/dist-packages/fairseq/tasks/translation.py", line 219, in load_dataset
    truncate_source=self.args.truncate_source,
  File "/usr/local/lib/python3.6/dist-packages/fairseq/tasks/translation.py", line 52, in load_langpair_dataset
    raise FileNotFoundError('Dataset not found: {} ({})'.format(split, data_path))
FileNotFoundError: Dataset not found: valid (/content/drive/My Drive/HashPro/preprocessed)
```
It does report finding the dictionaries, but apparently the dataset is not found. Here are the dataset files :-
> dict.input.txt
> dict.output.txt
> hashpro_hashes.bpe.input
> hashpro_hashes.bpe.output
> preprocess.log
> train.input-output.input.bin
> train.input-output.input.idx
> train.input-output.output.bin
> train.input-output.output.idx

Since all the files are included, and the path seems to be correct (since it can load up the dictionaries) I don't understand why such a problem is occurring. This is the training command I am using to train the whole model-

`%%bash`
`fairseq-train '/content/drive/My Drive/HashPro/preprocessed' --max-sentences 8 --fp16 --lr 0.02 --clip-norm 0.1 --optimizer sgd --dropout 0.2 --arch bart_large --save-dir /content/drive/'My Drive'/HashPro/Checkpoints/`

I am using TPU which has been initialized in the standard way shown in Colab examples. Apparently there have been some changes in the implementations - I can no longer put the `--tpu` flag or `--bf16`. Has the support been disabled for debugging or is there a problem with the way I have installed FairSeq?

**Comment by huihuifan** [comment]
You need to have valid.input and valid.output when you run preprocess.py, that's what --validpref is looking for. Your model is trying to validate, and it cannot find it. preprocess.py will generate valid.input-output.input.bin, valid.input-output.input.idx etc just like train

**Comment by neel04** [comment]
@huihuifan Thanks a ton!! I had not put the `--validpref` flag in my preprocessing step and since it didn't give me any warning or error, I thought that it must have used the same argument for `--trainpref` as the path for validpref. Again, appreciate the help!!

**Comment by Crista23** [comment]
Hi @huihuifan , I have the same problem even though my files are present in the correct format and I am trying to generate translations with --replace_unk:

Traceback (most recent call last):
  File "generate.py", line 192, in <module>
    cli_main()
  File "generate.py", line 188, in cli_main
    main(args)
  File "generate.py", line 35, in main
    task.load_dataset(args.gen_subset)
  File "/usr/fairseq/tasks/translation.py", line 154, in load_dataset
    raise FileNotFoundError('Dataset not found: {} ({})'.format(split, data_path))
FileNotFoundError: Dataset not found: test (/data/test)

What could be causing this? Thanks!
