### ISSUE TITLE
Why does the feature vector increase the dimensionality?

### ISSUE THREAD

**Issue by shamoons** [pytorch/fairseq#2560]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
When running the `wav2vec_featurize.py` on a raw audio file, I find that I have `93680` length for an audio file, but that results in a feature vector with a shape of `(512, 583)`. That means I have `298496` data points now, whereas the raw audio only has `93680`. I thought the point of embeddings was to reduce dimensionality, so I'm a bit confused as to why it's expanded?

#### Code
```
python examples/wav2vec/wav2vec_featurize.py --input data-bin/LibriSpeech --output tmp --model data-bin/models/wav2vec_large.pt --split dev-clean --ext flac --no-copy-labels --use-feat
```

   

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): `master`
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by alexeib** [comment]
the raw waveform is encoded into representations with strides of 10ms. librispeech has sample rate of 16khz so 93680/160 = 585.5. you lose a bit because of "valid" padding (as opposed to "same") but seems to add up...
