### ISSUE TITLE
Unclear what differences if any exist in handling trainpref/validpref/testpref

### ISSUE THREAD

**Issue by munael** [pytorch/fairseq#2565]
## 📚 Documentation

See: https://fairseq.readthedocs.io/en/latest/command_line_tools.html#Preprocessing

| - | - |
| - | - |
| `--trainpref` | train file prefix |
| `--validpref` | comma separated, valid file prefixes |
| `--testpref`  | comma separated, test file prefixes |

Besides that, does `fairseq-preprocess` do any extra processing of the data (that is, besides binarization) for any of the splits? Is any processing different between the splits?

**Comment by myleott** [comment]
Good point, I'll add some docs. `--trainpref` produces the dictionary (`dict.txt`). `--validpref` and `--testpref` use that dictionary, but any missing words are replaced with `<unk>`. There is no difference between `--validpref` and `--testpref` other than the output filenames.
