### ISSUE TITLE
Signature of apply_sparse_mask method in MultiheadAttention

### ISSUE THREAD

**Issue by Alvant** [pytorch/fairseq#2574]
### Additional context

In MultiheadAttention module, `apply_sparse_mask` method signature
https://github.com/pytorch/fairseq/blob/master/fairseq/modules/multihead_attention.py#L445
is invalid (but it still works). It is written like a function, not a class method.

I suggest fixing the signature from
```python
def apply_sparse_mask(attn_weights, ...
```
to
```python
def apply_sparse_mask(self, attn_weights, ...
```
and the line https://github.com/pytorch/fairseq/blob/master/fairseq/modules/multihead_attention.py#L320 from
```python
attn_weights = MultiheadAttention.apply_sparse_mask(...)
```
to
```python
attn_weights = self.apply_sparse_mask(...)
```

Why am I suggesting using an instance method instead of a class- or staticmethod?
I noticed that SparseMultiHeadAttention redefines this `apply_sparse_mask` method https://github.com/pytorch/fairseq/blob/master/fairseq/modules/sparse_multihead_attention.py#L101.
So it seems that `def apply_sparse_mask(self, ...)` signature would be more appropriate to use in MultiheadAttention.

### P.S.

It is not quite a bug, but it is something not quite right.

### P.P.S.

If the idea is OK, I could make a pullrequest.

**Comment by lematt1991** [comment]
Nice catch!  Definitely agree with your proposed fix, feel free to submit a PR, thanks!

**Comment by Alvant** [comment]
Ok! Here https://github.com/pytorch/fairseq/pull/2587
but for some reason the tests did not run after submitting the pull request...

**Comment by lematt1991** [comment]
I think it might be because there was a lint error that got merged somehow.  It should be fixed now if you want to rebase.

**Comment by Alvant** [comment]
:balloon: :smiley:
