### ISSUE TITLE
Can I use fairseq without GPU?

### ISSUE THREAD

**Issue by nashid** [pytorch/fairseq#2575]
I don't have access to GPU. However, I have access to powerful multicore machines with CPU. 

Can I use fairseq with CPU? I need to train existing models with a new dataset?

**Comment by lematt1991** [comment]
You can specify the [`--cpu`](https://github.com/pytorch/fairseq/blob/master/fairseq/options.py#L239) flag

**Comment by nashid** [comment]
@lematt1991 I think this should be reflected in the Readme.

Readme mentions GPU is a mandatory prereq.
