### ISSUE TITLE
memory issue with  joint_alignment_translation example

### ISSUE THREAD

**Issue by hlncrg** [pytorch/fairseq#2576]
#### What is your question?

I am trying to run the example joint_alignment_translation (https://github.com/pytorch/fairseq/tree/master/examples/joint_alignment_translation).  I am getting an error if I run the command:

fairseq-train \
    binarized \
    --arch transformer_wmt_en_de_big_align --share-all-embeddings \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 --activation-fn relu\
    --lr 0.0002 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07 \
    --dropout 0.3 --attention-dropout 0.1 --weight-decay 0.0 \
    --max-tokens 3500 --label-smoothing 0.1 \
    --save-dir ./checkpoints --log-interval 1000 --max-update 60000 \
    --keep-interval-updates -1 --save-interval-updates 0 \
    --load-alignments --criterion label_smoothed_cross_entropy_with_alignment \
    --fp16

as given in the example.

The error that I am getting is:
CUDA out of memory. Tried to allocate 814.00 MiB (GPU 0; 4.00 GiB total capacity; 2.38 GiB already allocated; 606.83 MiB free; 2.39 GiB reserved in total by PyTorch)

#### What have you tried?

I have tried to lower the parameter 'max-tokens' but this still results in the same error even if it is lowered to 2.  If I lower it to 1 I get the error: UnboundLocalError: local variable 'valid_losses' referenced before assignment

Is there anything else I can do to resolve this issue?

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Windows
 - How you installed fairseq (`pip`, source): 

git clone https://github.com/pytorch/fairseq
cd fairseq
pip install --editable ./

 - Build command you used (if compiling from source):
 - Python version: 3.6.5
 - CUDA/cuDNN version: V11.0.221
 - GPU models and configuration: NVIDIA GeForce GTX 970
 - Any other relevant information:

**Comment by lematt1991** [comment]
Hmm, 4GB of GPU memory is quite small, you can try using a smaller model architecture like `transformer_align` instead of `transformer_wmt_en_de_big_align`.  Also make sure that no other processes are using the GPU.  You can verify this using `nvidia-smi`.  If that still won't fit on your GPU you can further try to trim down the model size by reducing the number of layers, embedding dimensions, etc.

**Comment by hlncrg** [comment]
Thanks for the response!  What is the difference between transformer_align and transformer_wmt_en_de_big_align?

**Comment by lematt1991** [comment]
The `transformer_align` model is simply smaller (fewer layers, less embedding dimensions, etc.)

**Comment by hlncrg** [comment]
I tried to use the following command:

fairseq-train binarized --arch transformer_align --share-all-embeddings --optimizer adam --adam-betas '(0.9,0.98)' --clip-norm 0.0 --activation-fn relu --lr 0.0002 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07 --dropout 0.3 --attention-dropout 0.1 --weight-decay 0.0 --max-tokens 3500 --label-smoothing 0.1 --save-dir ./checkpoints --log-interval 1000 --max-update 60000 --keep-interval-updates -1 --save-interval-updates 0 --load-alignments --criterion label_smoothed_cross_entropy_with_alignment --fp16

In addition to the warnings of out of memory it also gave me this error:

  File "C:\Users\hecraig\AppData\Local\Continuum\anaconda2\envs\cntk-py36\Scripts\fairseq-train-script.py", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "c:\users\hecraig\src\fairseq\fairseq_cli\train.py", line 351, in cli_main
    distributed_utils.call_main(args, main)
  File "c:\users\hecraig\src\fairseq\fairseq\distributed_utils.py", line 189, in call_main
    main(args, **kwargs)
  File "c:\users\hecraig\src\fairseq\fairseq_cli\train.py", line 121, in main
    valid_losses, should_stop = train(args, trainer, task, epoch_itr)
  File "c:\users\hecraig\appdata\local\continuum\anaconda2\envs\cntk-py36\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "c:\users\hecraig\src\fairseq\fairseq_cli\train.py", line 217, in train
    log_output = trainer.train_step(samples)
  File "c:\users\hecraig\appdata\local\continuum\anaconda2\envs\cntk-py36\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "c:\users\hecraig\src\fairseq\fairseq\trainer.py", line 521, in train_step
    self.optimizer.step()
  File "c:\users\hecraig\src\fairseq\fairseq\optim\fp16_optimizer.py", line 147, in step
    self.fp32_optimizer.step(closure)
  File "c:\users\hecraig\src\fairseq\fairseq\optim\fairseq_optimizer.py", line 102, in step
    self.optimizer.step(closure)
  File "c:\users\hecraig\src\fairseq\fairseq\optim\adam.py", line 182, in step
    beta1, beta2 = group['betas']
ValueError: too many values to unpack (expected 2)

**Comment by hlncrg** [comment]
I ended up using a more powerful machine and no longer ran into any of these issues.
