### ISSUE TITLE
[Bug Report] AttributeError: _source_iter

### ISSUE THREAD

**Issue by jia-zhuang** [pytorch/fairseq#2577]
https://github.com/pytorch/fairseq/blob/e7f76c44817e9766acca3aacf0d4e8807a6a2d03/fairseq/data/iterators.py#L491

`BackgroundConsumer` class do not have `_source_iter` variable, which cuase `AttributeError: _source_iter`.

**Comment by myleott** [comment]
Fixed in 0ffb94151f597ecb677551289e7046a21fb5ebaf
