### ISSUE TITLE
How to transfer a TPU-model to GPU.

### ISSUE THREAD

**Issue by shizhediao** [pytorch/fairseq#2578]
#### What is your question?
I have successfully pre-trained a Roberta model on TPU following the official guide.
Then I want to do fine-tune tasks on GPU.
However, I encountered some issues which seem that due to the mismatch of the devices.

#### Code

   
For the pre-train: https://cloud.google.com/tpu/docs/tutorials/roberta-pytorch?hl=zh-cn
For the fine-tune: 
from fairseq.models.roberta import RobertaModel
roberta = RobertaModel.from_pretrained('checkpoints', 'checkpoint_best.pt', 'path/to/data')
I got an error like this:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/import/home/sdiaoaa/fairseq/fairseq/models/roberta/model.py", line 169, in from_pretrained
    **kwargs,
  File "/import/home/sdiaoaa/fairseq/fairseq/hub_utils.py", line 73, in from_pretrained
    arg_overrides=kwargs,
  File "/import/home/sdiaoaa/fairseq/fairseq/checkpoint_utils.py", line 239, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/import/home/sdiaoaa/fairseq/fairseq/checkpoint_utils.py", line 205, in load_checkpoint_to_cpu
    f, map_location=lambda s, l: default_restore_location(s, "cpu")
  File "/home/sdiaoaa/.conda/envs/domains/lib/python3.7/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/home/sdiaoaa/.conda/envs/domains/lib/python3.7/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579040055865/work/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /opt/conda/conda-bld/pytorch_1579040055865/work/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7fe0cecbd627 in /home/sdiaoaa/.conda/envs/domains/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7fe0d3729e2b in /home/sdiaoaa/.conda/envs/domains/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >) + 0x57 (0x7fe0d372af77 in /home/sdiaoaa/.conda/envs/domains/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6b0792 (0x7fe1005a4792 in /home/sdiaoaa/.conda/envs/domains/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x28ba06 (0x7fe10017fa06 in /home/sdiaoaa/.conda/envs/domains/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #42: __libc_start_main + 0xe7 (0x7fe110c04b97 in /lib/x86_64-linux-gnu/libc.so.6)

#### What's your environment?

TPU: V3-8 Pytorch: 1.6
GPU: 2080Ti  Pytorch: 1.4

**Comment by lematt1991** [comment]
CC @myleott @ngoyal2707

**Comment by nate-bush** [comment]
@shizhediao I ran into the same issue and had to install PyTorch 1.6 on my GPU machine to workaround it.
