### ISSUE TITLE
Question About Pre-trained Models

### ISSUE THREAD

**Issue by cocaer** [pytorch/fairseq#258]
When I tried to use the pre-trained  [Model(cons2s wmt14en-de)](https://s3.amazonaws.com/fairseq-py/models/wmt14.v2.en-de.fconv-py.tar.bz2), I I have encountered such an error

`
RuntimeError: Error(s) in loading state_dict for FConvModel:
	size mismatch for encoder.embed_tokens.weight: copying a param of torch.Size([40472, 768]) from checkpoint, where the shape is torch.Size([40358, 768]) in current model.
	size mismatch for decoder.embed_tokens.weight: copying a param of torch.Size([42720, 768]) from checkpoint, where the shape is torch.Size([42714, 768]) in current model.
	size mismatch for decoder.fc3.bias: copying a param of torch.Size([42720]) from checkpoint, where the shape is torch.Size([42714]) in current model.
	size mismatch for decoder.fc3.weight_g: copying a param of torch.Size([42720, 1]) from checkpoint, where the shape is torch.Size([42714, 1]) in current model.
	size mismatch for decoder.fc3.weight_v: copying a param of torch.Size([42720, 512]) from checkpoint, where the shape is torch.Size([42714, 512]) in current model.
`

My generate script is like this
`
CUDA_VISIBLE_DEVICES=3  python generate.py wmt14_en_de 
  --path model.pt --beam 5 --remove-bpe
`

Is the model already behind the code version? I confirmed that I didn't  made any changes to the source 
 code.

**Comment by nithya4** [comment]
Just wondering: how did you fix this?

**Comment by narfanar** [comment]
Hi, this's still an issue :/

**Comment by QzzIsCoding** [comment]
I tried to use the pre-trained Model conv.wmt17.en-de and appeared an error.
`Traceback (most recent call last):                                                                                                          
  File "/home/anaconda3/envs/editor/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/share/en2de/fairseq-editor/fairseq_cli/generate.py", line 235, in cli_main
    main(args)
  File "/share/en2de/fairseq-editor/fairseq_cli/generate.py", line 35, in main
    return _main(args, sys.stdout)
  File "/share/en2de/fairseq-editor/fairseq_cli/generate.py", line 133, in _main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/share/en2de/fairseq-editor/fairseq/tasks/fairseq_task.py", line 351, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/anaconda3/envs/editor/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/share/en2de/fairseq-editor/fairseq/iterative_refinement_generator.py", line 158, in generate
    encoder_out = model.forward_encoder([src_tokens, src_lengths])
  File "/home/anaconda3/envs/editor/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1131, in __getattr__
    type(self).__name__, name))
AttributeError: 'FConvModel' object has no attribute 'forward_encoder`
