### ISSUE TITLE
Wav2vec2 sample_negatives device mismatch

### ISSUE THREAD

**Issue by arminarj** [pytorch/fairseq#2582]
## 🐛 Bug

It seems there is a device mismatch at these lines, [(one)](https://github.com/pytorch/fairseq/blob/0ffb94151f597ecb677551289e7046a21fb5ebaf/fairseq/models/wav2vec/wav2vec2.py#L480) and [(two)](https://github.com/pytorch/fairseq/blob/0ffb94151f597ecb677551289e7046a21fb5ebaf/fairseq/models/wav2vec/wav2vec2.py#L495). 

### To Reproduce

During the training time, when calling the `sample_negatives()` function, there is a device mismatch that occurs when the `torch.randint()`[(link)](https://github.com/pytorch/fairseq/blob/0ffb94151f597ecb677551289e7046a21fb5ebaf/fairseq/models/wav2vec/wav2vec2.py#L477-L479) and the new `tszs ` [(link)](https://github.com/pytorch/fairseq/blob/0ffb94151f597ecb677551289e7046a21fb5ebaf/fairseq/models/wav2vec/wav2vec2.py#L470-L475) using the same device.
And it seems the problem can be solved using the `device=` tags.

Regards

**Comment by lematt1991** [comment]
Can you provide a gist of the full backtrace you get.  Please run with the `CUDA_LAUNCH_BLOCKING=1` environment variable.
