### ISSUE TITLE
the output log format do not have timestamp info 

### ISSUE THREAD

**Issue by ismymajia** [pytorch/fairseq#2584]
| epoch 001:  15000 / 34323 loss=6.628, nll_loss=6.628, ppl=98.88, wps=644, ups=0, wpb=262143.968, bsz=2048.000, num_updates=15001, lr=0.00025819, gnorm=0.224, clip=0.106, oom=0.000, wall=407, train_wall=6043
| epoch 001:  15010 / 34323 loss=6.627, nll_loss=6.627, ppl=98.85, wps=7006, ups=0, wpb=262143.968, bsz=2048.000, num_updates=15011, lr=0.000258104, gnorm=0.224, clip=0.106, oom=0.000, wall=412, train_wall=6047

Now the output log format is above. Why not have timestamp info in the line header.

**Comment by lematt1991** [comment]
You should be able to reconstruct this from the `train_wall` times
