### ISSUE TITLE
Can I train monolingual training (ko_KR) using mbart?

### ISSUE THREAD

**Issue by gusdnd852** [pytorch/fairseq#2586]
#### What is your question?
Hello, I'm going to use Fairseq to train the mBart model for monolingual (ko_KR) Seq2Seq task. As mentioned in the paper, the input of the mBart model must be added with a language code. However, in fairseq-preprocess, it must work only if I give different languages ​​to sources and targets for train, valid, and test files. Is there a solution to this? Also, should I add language id  (like en_XX, ko_KR..) myself in the preprocessing stage? If it is automatically added, can I know at what stage the language code is added? and can I set it to only one language (ko_KR)?

**Comment by lematt1991** [comment]
The language token will be added to the end of the sequence on the fly using the [`DenoisingDataset`](https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/multilingual_denoising.py#L160).  You shouldn't need to do anything special, other than specify the languages beings used via the `--langs` flag.  Hope this helps!

**Comment by gusdnd852** [comment]
thank you !!
