### ISSUE TITLE
need to preprocess (binarize) a huge dataset ~ 200G data. 

### ISSUE THREAD

**Issue by kkissmart** [pytorch/fairseq#2588]
Hi 

I need to binarize a huge dataset ~200G, however my machine is limited. ~128G memory. Is there an arg to do so in the fairseq-preprocess command?

Thanks so much!

**Comment by lematt1991** [comment]
Did you try preprocessing and get an out of memory error?  As far as I know, I don't think `fairseq-preprocess` should need to read the entire file in at once.

**Comment by kkissmart** [comment]
@lematt1991 yes. the process was auto-killed, and I have tried multiple times. Can you reopen this issue so that other people can help?
