### ISSUE TITLE
preprocess was killed due to large dataset. 

### ISSUE THREAD

**Issue by kkissmart** [pytorch/fairseq#2589]
I was trying to binarize a huge dataset ~200G. but my server CPU size is 16v with 128G. I tried multiple times with different number of workers. seems that each worker works fine but when the entire process tried to merge, the process was auto-killed. regardless to the number of workers when the bin size reach about 120G, the process was killed without generating idx file. 

my previous question was closed. 

https://github.com/pytorch/fairseq/issues/2588

so I opened a new one here.

**Comment by lematt1991** [comment]
You can try splitting your input file into `k` chunks, and then call `fairseq-preprocess` `k` times.  You can then specify all data paths separated by colons.  See the [`data`](https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/translation.py#L161-L164) argument for more details.

**Comment by kkissmart** [comment]
@lematt1991 thanks! I will try and get back to you if it works. before that, let us keep this issue open.

**Comment by kkissmart** [comment]
tried multiple ways. split is the only way works.  Thanks

**Comment by akalieren** [comment]
I am facing with same issue however I need to create `dict.txt` in this step with the fairseq-preprocess. I split my dataset into ~40 chunks but it seems in this way we will create 40 different `dict.txt`. Do you think it is a problem? What is the recommended data size to create proper dict.txt? Maybe I can first create dict.txt then preprocess data? Any idea?

Thanks

**Comment by Felixgithub2017** [comment]
@lematt1991 @akalieren 
> You can try splitting your input file into `k` chunks, and then call `fairseq-preprocess` `k` times. You can then specify all data paths separated by colons. See the [`data`](https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/translation.py#L161-L164) argument for more details.

Hi, just like @akalieren said, the preprocess step will create multiple dict files, what is your suggestion to this problem?
