### ISSUE TITLE
backtranslation

### ISSUE THREAD

**Issue by bianlele** [pytorch/fairseq#2590]
## ❓ Questions and Help

How to import our own local data to train our own translation model in the backtranslation project

   

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by lematt1991** [comment]
Please see the [backtranslation example](https://github.com/pytorch/fairseq/tree/master/examples/backtranslation#training-your-own-model-wmt18-english-german) for details.
