### ISSUE TITLE
mBART monolingual finetuning

### ISSUE THREAD

**Issue by gusdnd852** [pytorch/fairseq#2595]
#### What is your question?
As I said [here](https://github.com/pytorch/fairseq/issues/2586), I'm going to use mbart to do a monolingual seq2seq training. And language id (such as ko_KR) can be added to `--langs` argument, but the important thing is how do I organize training data files? 

Because it is the same language, the file name must be configured with extensions such as (src or tgt) not (ko_KR or en_XX) 
e.g. (train.src or train.tgt) not (train.ko_KR or train.en_XX) Is the lang id applied well in this case?

**Comment by gusdnd852** [comment]
When learning mBART, is there a way to not use bos or eos tokens at all? In this case, it seems better to add when I construct a dataset.

**Comment by gusdnd852** [comment]
Yesterday, I studied this problem all day. When mBART is pre-learning, it is learned that the decoder must receive [ko_KR] as bos to output Korean, and the decoder must receive [ar_AR] as bos to output in Arabic. And learned that to receive Korean as the source, Encoder must receive [ko_KR] as the eos of the source document, and to receive Arabic as the source, Encoder must receive [ar_AR] as the eos of the source document.

![image](https://user-images.githubusercontent.com/38183241/92700950-609a9000-f38a-11ea-8b79-dddfa00d17b9.png)

However, if we set something like "tgt" or "src" to language, `<unk>` token is entered as the encoder's eos and decoder's bos (see code for this). `<unk>` is returned if there is no such language in the dictionary 
```
dict.index(language) -> <unk> -> eos 
```

- append_source_id=True [here](https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/translation_from_pretrained_bart.py#L84)
- eos set as dictionary.index [here](https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/translation.py#L115)
- but [tgt] is not contains in vocab. so `<unk>` is returned [here](https://github.com/pytorch/fairseq/blob/42c5dcbd18c85dcdc9424886f3880c184d589f0d/fairseq/data/dictionary.py#L63)

This is not a problem because BART (not mBART) uses tokens such as `<s>` and `</s>` as bos and eos, but in mBART, It is a problem because it uses language token like [ko_KR], [ar_AR] as bos and eos. To solve this problem I am implementing mBART monolingaul Seq2Seq task. I'll share it when it's done.

**Comment by NomadXD** [comment]
@hyunwoongko I'm facing the same issue. Did you find any solution or implemented the Seq2Seq task ??? Thanks
