### ISSUE TITLE
How fairseq-generate work? (dimension mismatch in decoder output)

### ISSUE THREAD

**Issue by steventan0110** [pytorch/fairseq#2597]
#### What is your question?

I just implemented a customized LSTM model on fairseq and the training process has no bug. Then in the generation process, I could only successfully generate the first batch, then there is a dimension mismatch for my decoder's output and the vocab size, which really confused me. 

#### Code

```
decoder output dimension: torch.Size([1000, 1, 62992])
torch.Size([1000, 62992])
decoder output dimension: torch.Size([1000, 2, 62992])
torch.Size([1000, 62992])
decoder output dimension: torch.Size([1000, 3, 62992])
torch.Size([1000, 62992])
decoder output dimension: torch.Size([1000, 4, 62992])
torch.Size([1000, 62992])
decoder output dimension: torch.Size([965, 5, 62992])
torch.Size([965, 62992])
decoder output dimension: torch.Size([935, 6, 62992])
torch.Size([935, 62992])
decoder output dimension: torch.Size([675, 7, 62992])
torch.Size([675, 62992])
decoder output dimension: torch.Size([415, 8, 62992])
torch.Size([415, 62992])
decoder output dimension: torch.Size([370, 9, 62992])
torch.Size([370, 62992])
decoder output dimension: torch.Size([315, 10, 62992])
torch.Size([315, 62992])
decoder output dimension: torch.Size([125, 11, 62992])
torch.Size([125, 62992])
decoder output dimension: torch.Size([115, 12, 62992])
```
The print results above are from `sequence_generator.py`: 
I print out the dimension for my decoder out
```
decoder_out = model.decoder.forward(tokens, encoder_out=encoder_out)
```
This batch works properly and then a new batch starts, where my decoder_out has a dimension
```
decoder output dimension: torch.Size([800, 1, 62993])
```
and an error was thrown in following code because ` lprobs.view(bsz, -1, self.vocab_size)` use a vocab size of 62992, not 62993. I'm really confused why the decoder output dimension's vocab size is incremented by 1. (I map my decoder output to len(dictionary), which should be the vocab size 62992)

```
# Shape: (batch, cand_size)
            cand_scores, cand_indices, cand_beams = self.search.step(
                step,
                lprobs.view(bsz, -1, self.vocab_size),
                scores.view(bsz, beam_size, -1)[:, :, :step],
            )
```

#### What's your environment?

fairseq Version (e.g., 1.0 or master): master
PyTorch Version (e.g., 1.0) 1.6
OS (e.g., Linux): linux
How you installed fairseq (pip, source): source
Build command you used (if compiling from source):
```
fairseq-generate /home/steven/Documents/GITHUB/DQN/data/multilingual/azetur_eng\
--path /home/steven/Documents/GITHUB/DQN/checkpoints/azetur_eng/checkpoint_best.pt \
--user-dir /home/steven/Documents/GITHUB/DQN/src \
--beam 5 \
--remove-bpe \
```
    Python version: 3.7
    CUDA/cuDNN version: 10.2
    GPU models and configuration: RTX2070, default config
    Any other relevant information:

**Comment by lematt1991** [comment]
It's hard to say without having access to your custom model.  Make sure that you specify the same `task` when training and generating (some tasks add extra entries to the dictionary).  To debug, I would simply set a breakpoint when the dictionaries are loaded in both training and generation and see what entries are different.

**Comment by steventan0110** [comment]
> It's hard to say without having access to your custom model. Make sure that you specify the same `task` when training and generating (some tasks add extra entries to the dictionary). To debug, I would simply set a breakpoint when the dictionaries are loaded in both training and generation and see what entries are different.

I used the default task of fairseq and it should be consistent for both training and generating.

for the model, I use the `len(self.dictionary)` (in decoder class) as the output dimension, and map my final output from RNN to size of (batch_size, target_length, output_dim), as requested by the documentation. I used fairseq-preprocess to handle the text preprocessing so I think the vocab size (len(self.dictionary)) should be constant but somehow it's changed. Should I look into data loading code? I think the default loading should not have a problem in vocab size?

Also, I'm just generally confused about the generation process. I thought the generation process is batch by batch sentence generation, but my decoder output dimension changes from [1000, 1, 62992] to [1000, 2, 62992], [1000, 3, 62992],  [1000, 4, 62992], [965, 5, 62992], etc. It seems like the target_len is always incremented by 1 and batch size is not consistent throughout the loop. Could you point to some helpful resource to learn about fairseq's generation process? Any help would be appreciated!

Thank you.
