### ISSUE TITLE
Can not find Docs for libnat_cuda.levenshtein_distance/generate_deletion_labels/generate_insertion_labels   or libnat.suggested_ed2_path

### ISSUE THREAD

**Issue by CheungZeeCn** [pytorch/fairseq#2602]
#### What is your question?
I am reading the code of lev-T (thx for the great job!).

When I come to the codes about libnat or libnat_cuda part, I found that there is no docs for the functions :

libnat_cuda.levenshtein_distance/generate_deletion_labels/generate_insertion_labels  
libnat.suggested_ed2_path

what are the input and output and the meanings of them? 
what are the main steps for these function ? 
Those really make me frustrated, any help? Thanks! 

#### Code
        # in   fairseq/models/nat/levenshtein_utils.py  
         mask_ins_targets, masked_tgt_masks = libnat.generate_insertion_labels(
            out_tokens.int(), libnat.levenshtein_distance(
                in_tokens.int(), out_tokens.int(),
                in_masks.sum(1).int(), out_masks.sum(1).int()
            )
        )

        word_del_targets = libnat.generate_deletion_labels(
            in_tokens.int(),
            libnat.levenshtein_distance(
                in_tokens.int(), out_tokens.int(),
                in_masks.sum(1).int(), out_masks.sum(1).int()
            )
        )

>>> a = torch.Tensor([[0,1,2]]).to('cuda').int()
>>> b = torch.Tensor([[0,1,2]]).to('cuda').int();
>>> la = torch.Tensor([3]).to('cuda').int()
>>> lb = torch.Tensor([3]).to('cuda').int()
>>> libnat_cuda.levenshtein_distance(a, b, la, lb)
tensor([[3, 3, 3, 0, 0, 0]], device='cuda:0', dtype=torch.int32)
>>> b = torch.Tensor([[0,1]]).to('cuda').int();
>>> lb = torch.Tensor([2]).to('cuda').int()
>>> libnat_cuda.levenshtein_distance(a, b, la, lb)
tensor([[3, 3, 2, 0, 0]], device='cuda:0', dtype=torch.int32)
>>> b = torch.Tensor([[0,1,3]]).to('cuda').int();
>>> lb = torch.Tensor([3]).to('cuda').int()
>>> libnat_cuda.levenshtein_distance(a, b, la, lb)
tensor([[3, 3, 2, 1, 0, 0]], device='cuda:0', dtype=torch.int32)

#### What have you tried?
read the documents of fairseq
google the doc or codes of libnat/libnat_cuda but have got nothing.

**Comment by lematt1991** [comment]
CC @kahne @MultiPath

**Comment by CheungZeeCn** [comment]
any help ?

**Comment by conan1024hao** [comment]
Have you figured it out?
