### ISSUE TITLE
Can i find any test data  for the transformer lm model or arch?

### ISSUE THREAD

**Issue by ismymajia** [pytorch/fairseq#2610]
Can i find any test data  for the transformer lm model or arch?

 --arch ARCH, -a ARCH  model architecture: fconv_lm,
                        fconv_lm_dauphin_wikitext103, fconv_lm_dauphin_gbw,
                        fconv, fconv_iwslt_de_en, fconv_wmt_en_ro,
                        fconv_wmt_en_de, fconv_wmt_en_fr, lstm,
                        lstm_wiseman_iwslt_de_en, lstm_luong_wmt_en_de,
                        fconv_self_att, fconv_self_att_wp,
                        transformer_lm, transformer_lm_big,
                        transformer_lm_wiki103, transformer_lm_gbw,
                        transformer, transformer_iwslt_de_en,
                        transformer_wmt_en_de,
                        transformer_vaswani_wmt_en_de_big,
                        transformer_vaswani_wmt_en_fr_big,
                        transformer_wmt_en_de_big,
                        transformer_wmt_en_de_big_t2t (default: fconv)

**Comment by lematt1991** [comment]
Please follow the issue templates
