### ISSUE TITLE
No results from --profile

### ISSUE THREAD

**Issue by Rivendile** [pytorch/fairseq#2613]
#### What is your question?
When I try to get the profile, the .prof file saves nothing. The source code is not changed. Could you please tell me how to fix this?

#### Code
TOTAL_UPDATES=10    # Total number of training steps
WARMUP_UPDATES=10000    # Warmup the learning rate over this many updates
PEAK_LR=0.0005          # Peak learning rate, adjust as needed
TOKENS_PER_SAMPLE=512   # Max sequence length
MAX_POSITIONS=512       # Num. positional embeddings (usually same as above)
MAX_SENTENCES=8        # Number of sequences per batch (batch size)
UPDATE_FREQ=32          # Increase the batch size 16x

DATA_DIR=data-bin/wikitext-103

nvprof --profile-from-start off -o trace_name.prof -f python ../fairseq/train.py $DATA_DIR\
    --task masked_lm --criterion masked_lm \
    --arch roberta_base --sample-break-mode complete --tokens-per-sample $TOKENS_PER_SAMPLE \
    --optimizer adam --adam-betas '(0.9,0.98)' --adam-eps 1e-6 --clip-norm 0.0 \
    --lr-scheduler polynomial_decay --lr $PEAK_LR --warmup-updates $WARMUP_UPDATES --total-num-update $TOTAL_UPDATES \
    --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 \
    --max-sentences $MAX_SENTENCES --update-freq $UPDATE_FREQ \
    --max-update $TOTAL_UPDATES --log-format simple --log-interval 1 --profile

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version (e.g., 1.0)1.6
 - OS (e.g., Linux): Linux
 - How you installed fairseq: source
 - Python version:3.8
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: 4xP100
 - Any other relevant information:

**Comment by Rivendile** [comment]
Besides, when I try to torch.autograd.profiler.load_prof, error occurs:
TypeError: __init__() missing 1 required positional argument: 'node_id'

**Comment by Rivendile** [comment]
Besides, when I try to torch.autograd.profiler.load_prof, error occurs:

> Traceback (most recent call last):
>   File "prof.py", line 3, in <module>
>     print(torch.autograd.profiler.load_nvprof('bert.prof'))
>   File "/home/yihao/anaconda3/envs/bert/lib/python3.8/site-packages/torch/autograd/profiler.py", line 572, in load_nvprof
>     return EventList(parse_nvprof_trace(path))
>   File "/home/yihao/anaconda3/envs/bert/lib/python3.8/site-packages/torch/autograd/profiler.py", line 993, in parse_nvprof_trace
>     evt = FunctionEvent(id=row['marker_id'],
> TypeError: __init__() missing 1 required positional argument: 'node_id'

**Comment by lazerliu** [comment]
have you fixed it? I meet the same problem now
