### ISSUE TITLE
How can I inference just one audio by Pre-train Wav2vec 2.0 model?

### ISSUE THREAD

**Issue by sooftware** [pytorch/fairseq#2618]
How can I inference just one audio by Pre-train Wav2vec 2.0 model?  
`examples/speech_recognition/infer.py` too difficult to me.

**Comment by loretoparisi** [comment]
+1 because the inference script needs to be cleanup in a simple inference pipeline.

**Comment by sooftware** [comment]
I Success.  
Refer [here](https://github.com/pytorch/fairseq/issues/2651)

**Comment by lyogavin** [comment]
I've created pull request #3244 for this.
