### ISSUE TITLE
File structure issues?

### ISSUE THREAD

**Issue by elfsmelf** [pytorch/fairseq#262]
Trying to get the code to work:

Command: 
python preprocess.py --source-lang wp_source --target-lang wp_target --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test --destdir data-bin/writingPrompts --padding-factor 1 --thresholdtgt 10 --thresholdsrc 10

Does $TEXT need to be replaced with something?

Error:
FileNotFoundError: [Errno 2] No such file or directory: '/train.wp_source'

**Comment by huihuifan** [comment]
Yes, you need to replace $TEXT with the name of the directory where you
downloaded the data, ie the folder containing the files called
train.wp_source, etc. You can download this data following the readme in
examples/stories.
