### ISSUE TITLE
Alignment output of joint_alignment_translation

### ISSUE THREAD

**Issue by hlncrg** [pytorch/fairseq#2634]
#### What is your question?

I am using the example of 'joint alignment translation' found here: 

The input sentence is something like: 'The order back@@ log in the transportation unit was $ 3@@ 2.6 billion as of September 30 , up margin@@ ally from December 31 .' (with bpe)

The output sentence is something like: 'Der Auftrags@@ eingang in der Transport@@ einheit belief sich auf 3@@ 2,@@ 6 Milliarden Dollar ab dem 30. September , gegenüber dem 31. Dezember .'

And the alignment is something like: '0-0 1-1 2-2 8-3 24-4 6-5 7-6 8-7 24-8 13-9 10-10 11-11 11-12 12-13 9-14 13-15 16-16 16-17 15-18 18-19 19-20 23-21 23-22 22-23 19-24'  

I could not find documentation on this but it looks like the format 'i-j' where the j is the index of the output term and i is the index of the input term.  It also seems that for every output term, the best alignment for the input term is given but I actually want the opposite: for every input term, what is the best alignment from the output terms.  Is there a way to easily get this information? 

I have just been using the command line tool 'fairseq-generate' thus far and I can not find a flag for this in the documentation.

#### Code

fairseq-generate \
    binarized --gen-subset test --print-alignment \
    --source-lang en --target-lang de \
    --path checkpoints/checkpoint_best.pt --beam 5 --nbest 1

#### What have you tried?

I have just been using the command line tool as is.  Looking through the source code, I think I might have to modify the source code: https://fairseq.readthedocs.io/en/latest/_modules/fairseq/data/language_pair_dataset.html?highlight=alignment
But I am not totally sure.

**Comment by hlncrg** [comment]
@sarthakgarg or @lematt1991 Any suggestions?

**Comment by lifecircle** [comment]
@hlncrg, The code only supports generating the alignments per target words. If you want alignments for every source word, you can try the following:

1. Use fairseq-generate to produce the de translations
2. Binarize the en source sentences and de translations using fairseq-preprocess. Name the binarized dataset as test_translations for e.g.
3. Use the --score-reference option in fairseq-generate to score the en source sentences given the de translations (processing in reverse direction). Something like: fairseq-generate test_translations --gen-subset test --print-alignment --source-lang de --target-lang en --path checkpoints/checkpoint_best.pt --score-reference

Let me know if this works for you, or if you have any questions!

**Comment by sarthakgarg** [comment]
@hlncrg, The code only supports generating the alignments per target words. If you want alignments for every source word, you can try the following:
1. Use fairseq-generate to produce the de translations
2. Binarize the en source sentences and de translations using fairseq-preprocess. Name the binarized dataset as test_translations for e.g.
3. Use the --score-reference option in fairseq-generate to score the en source sentences given the de translations (processing in reverse direction). Something like: fairseq-generate test_translations --gen-subset test --print-alignment --source-lang de --target-lang en --path checkpoints/checkpoint_best.pt --score-reference
Let me know if this works for you, or if you have any questions!

**Comment by hlncrg** [comment]
Hi @sarthakgarg ,

Thank you for your response.  It seems that when I use the flag --score-reference the alignments are not created.  When I use it I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/fairseq-generate", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')()
  File "/home/hecraig/fairseq/fairseq_cli/generate.py", line 286, in cli_main
    main(args)
  File "/home/hecraig/fairseq/fairseq_cli/generate.py", line 38, in main
    return _main(args, sys.stdout)
  File "/home/hecraig/fairseq/fairseq_cli/generate.py", line 233, in _main
    ' '.join(['{}-{}'.format(src_idx, tgt_idx) for src_idx, tgt_idx in alignment])
TypeError: 'NoneType' object is not iterable

**Comment by sarthakgarg** [comment]
Hi @hlncrg,
Thanks for your fix!
