### ISSUE TITLE
About downloading WMT17 dataset in prepare-wmt14en2de.sh

### ISSUE THREAD

**Issue by zhao1402072392** [pytorch/fairseq#2637]
Thanks for your contribution, it's really helpful! But I'm a little confused about the downloading of the data. Why are there three links to download the WMT17 training dataset in prepare-wmt14en2de.sh, including "http://statmt.org/wmt13/training-parallel-europarl-v7.tgz"
    "http://statmt.org/wmt13/training-parallel-commoncrawl.tgz"
    "http://data.statmt.org/wmt17/translation-task/training-parallel-nc-v12.tgz" instead of the single "http://data.statmt.org/wmt17/translation-task/training-parallel-nc-v12.tgz". Thanks you so much ^_^

**Comment by gvskalyan** [comment]
All of these data can be combined to train the model. They are from different sources such as europarl, commoncrawl, news crawl etc. There is no single dataset provided by WMT to download, but they list these sources.

**Comment by shainaraza** [comment]
any solution to merge and produce language modeling format?
