### ISSUE TITLE
fairseq inference without using command line arguments for translation task

### ISSUE THREAD

**Issue by pankajksingh** [pytorch/fairseq#2648]
#### What have you tried?
I tried to follow the evaluation script example https://fairseq.readthedocs.io/en/latest/tutorial_classifying_names.html but I am trying to run it without command line arguments and my task is translation. I am doing this on Jupyter. I am hoping to load my translation model from checkpoint & binarizer files and then run translation on it. What is the way to create the task object such that all the defaults are populated right? Sharing sample code that is failing on me.

from fairseq import checkpoint_utils, data, options, tasks

//Parse command-line arguments for generation
parser = options.get_generation_parser()
args = options.parse_args_and_arch(parser)

The last line results in error 
ArgumentError: argument --momentum: conflicting option string: --momentum

#### What's your environment?
 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version (e.g., 1.0) : 1.6.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version:3.7.3
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: I am training on VM, 1 GPU but my query is about inference
 - Any other relevant information:

**Comment by myleott** [comment]
I usually recommend using the `XYZModel.from_pretrained` interface for this.

Here are some instructions for seq2seq (translation) models: https://github.com/pytorch/fairseq/tree/master/examples/translation#example-usage-torchhub

Here's a more advanced example where task is specified manually: https://github.com/pytorch/fairseq/blob/master/examples/paraphraser/paraphrase.py#L51-L57

**Comment by pankajksingh** [comment]
Thanks @myleott 
I was able to use the eval script example at https://fairseq.readthedocs.io/en/latest/tutorial_classifying_names.html
I found a way to pass the arguments to options as the api allowed that and proceed further. Sharing my approach below.

 input_args=[ databin_folder
                    ,'--path', checkpoint_filepath
                    ,'--source-lang',"text",'--target-lang',"summary"
                    , '--beam', '5', '--min-len', '3', '--nbest', '1'
                    ]
 args = options.parse_args_and_arch(parser,input_args)
