### ISSUE TITLE
AssertionError: sentence at index 16482046 of size 201 exceeds max_tokens limit of 200!

### ISSUE THREAD

**Issue by priyamehta01** [pytorch/fairseq#2650]
I looked up the solution for the same and came across various fixes like adding `--skip-invalid-size-inputs-valid-test` to the command. It is not working. Is there any other way to approach this? Thanks in advance! :)

Note: Having a GPU with 4GB RAM, I am not able to allocate a massive number to the `--max-tokens` parameter. On that note, is it possible to train Fairseq from scratch with a 4GB GPU?

**Comment by NomadXD** [comment]
@priyamehta01 Did you find any solution ?
