### ISSUE TITLE
How to generate new sentence given some words with trained language models?

### ISSUE THREAD

**Issue by lqniunjunlper** [pytorch/fairseq#2659]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### Code

`/opt/conda/bin/fairseq-generate $DATA/fairseq/gen \
  --task language_modeling \
  --path $MODEL/checkpoint_best.pt \
  --sampling \
  --beam 2 \
  --nbest 2 \
  --max-tokens 1000 \
  --results-path $DATA/fairseq/gen`

   

#### What have you tried?

`In generate-test.txt:

I got no new sentence words...
`

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
Can you try the hub interface instead: https://github.com/pytorch/fairseq/tree/master/examples/language_model#example-usage

Alternatively you might try `fairseq-interactive`
