### ISSUE TITLE
Multiple copies of data caused OOM

### ISSUE THREAD

**Issue by zxw866** [pytorch/fairseq#266]
My training data is about 200 million, and the size is 50G. I found that each GPU's process reads a copy of data into memory, resulting in more than 400G of memory usage. Then the program ran out of memory and crashed. Have you encountered similar problems in the experiment of Paracrawl data?  How can I solve this problem?

**Comment by myleott** [comment]
Yes, this is a known problem. For Paracrawl we were able to fit the entire dataset in memory, but ideally we could load separate subsets of the dataset on each worker. I'll work on a fix.

**Comment by zherowolf** [comment]
Hi,did you fix the problem now? I have also encountered this problem.
great work!

**Comment by myleott** [comment]
In the meantime, I think you can change this to IndexedDataset to avoid loading the whole dataset into memory:
https://github.com/pytorch/fairseq/blob/6381cc977fa909bd53c8915a18684e49b3507332/fairseq/tasks/translation.py#L117

**Comment by zherowolf** [comment]
using IndexedDataSet instead of IndexInMemoryDataSet makes training much slower.
In my experiments, using IndexInMemoryDataSet, the wps is ~35k, while using IndexedDataSet it's only ~1600.

**Comment by myleott** [comment]
You should be able to use `--fix-batches-to-gpus` (introduced in 90f52a1) to fix this.
