### ISSUE TITLE
Incorrect link to wav2letter repo in wav2vec documentation

### ISSUE THREAD

**Issue by MonideepDe** [pytorch/fairseq#2662]
Incorrect link to wav2letter under section [Evaluating a CTC model](https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/README.md#evaluating-a-ctc-model) in [wav2vec documentation](https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/README.md)

**Comment by MonideepDe** [comment]
PR# 2663 to fix this

**Comment by kamakshi-malhotra** [comment]
Hi @MonideepDe, I am also not able to find link to wav2letter. Do you have any idea about the correct link?

**Comment by MonideepDe** [comment]
Hi @kamakshi-malhotra, the issue is fixed now - the link should work.
In any case, the correct link is-https://github.com/facebookresearch/wav2letter/tree/master/recipes/sota/2019

**Comment by MonideepDe** [comment]
PR# 2663 has been closed and issue fixed. Closing this issue.

**Comment by kamakshi-malhotra** [comment]
Thanks @MonideepDe , I am able to access correct link now.
