### ISSUE TITLE
Changes in TransformerDecoder break arch compat with published models

### ISSUE THREAD

**Issue by narfanar** [pytorch/fairseq#2664]
Example: `transformer_vaswani_wmt_en_de_big`.

Specifically, `output_projection` in the case that `share_input_output_embed == True`.

Model example: https://dl.fbaipublicfiles.com/fairseq/models/wmt14.en-fr.joined-dict.transformer.tar.bz2, from: https://github.com/pytorch/fairseq/tree/master/examples/translation

v0.9.0:
https://github.com/pytorch/fairseq/blob/df2f84ce619edddb80e720a56abc74d5490fed99/fairseq/models/transformer.py#L538-L551

master:
https://github.com/pytorch/fairseq/blob/fd080b308e1e3361d6c498b235496080fa6599e5/fairseq/models/transformer.py#L620-L633

**Comment by myleott** [comment]
There should be an automatic upgrade path for old checkpoints: https://github.com/pytorch/fairseq/blob/fd080b308e1e3361d6c498b235496080fa6599e5/fairseq/models/transformer.py#L848-L858

Please let us know if this doesn't work! We also have some internal tests that should confirm that all of the released models run, although again please let us know if something doesn't and we can add more tests.
