### ISSUE TITLE
How to load a pretrained model from huggingface and use it in fairseq?

### ISSUE THREAD

**Issue by ttzHome** [pytorch/fairseq#2666]
I want to load bert-base-chinese in huggingface or google bert and use fairseq to finetune it, how to do? thanks a lot!

**Comment by jia-zhuang** [comment]
me too, hope for answers

**Comment by myleott** [comment]
It should be straightforward to wrap huggingface models in the corresponding fairseq abstractions. We've done this for the gpt2 language models in huggingface: https://github.com/pytorch/fairseq/blob/master/fairseq/models/huggingface/hf_gpt2.py

It'd be great to add more wrappers for arbitrary models, and other model types (e.g., FairseqEncoderModel for BERT-like models).

PRs are welcome! 😄

**Comment by shamanez** [comment]
@myleott  According to the suggested way can we use the pretrained huggingface checkpoint? 

I feel like we need to specially change data preprocessing steps. 

1. Tokenization
2. Fairseq-preprocess function. (Here I don't understand how to create a dict.txt)

**Comment by myleott** [comment]
Fairseq doesn’t really do any preprocessing. If you want to apply tokenization or BPE, that should happen outside of fairseq, then you can feed the resulting text into fairseq-preprocess/train.

Steps might be:
1) start with raw text training data
2) use huggingface to tokenize and apply BPE. Get back a text file with BPE tokens separated by spaces
3) feed step 2 into fairseq-preprocess, which will tensorize and generate dict.txt

**Comment by shamanez** [comment]
You can do it. But it will slow down your training. Specially the data
feeding part.

**Comment by CheungZeeCn** [comment]
Is there an example of using  the code in https://github.com/pytorch/fairseq/blob/master/fairseq/models/huggingface/hf_gpt2.py ? 
@myleott @shamanez 
Thank you!

**Comment by CheungZeeCn** [comment]
Hi guys, Here is my code for this task exactly,  [HERE](https://github.com/CheungZeeCn/fairseq/blob/master/Sentence_prediction_Chinese_bert_demo.md) plz check this whether it can help you! 
@ttzHome @shamanez 

cc @myleott
