### ISSUE TITLE
Output probability of n best translations during generation

### ISSUE THREAD

**Issue by MaggieMeow** [pytorch/fairseq#267]
Is there a way to get the probability of each of the n-best translations during generation?

Thanks!

**Comment by myleott** [comment]
Yes, please pass the `--nbest` option to generate.py.

**Comment by MaggieMeow** [comment]
I realised that when generating using single model, log probability is used instead. Sorry for bothering you @myleott  and thanks anyways!

**Comment by myleott** [comment]
The positional scores and average hypothesis scores are output as log-probabilities, thus are negative.

For example:
```
S-72628	head massager
T-72628	3625 1238 4228
H-72628	-0.26392436027526855	3625 1238 4228
P-72628	-0.2926 -0.7546 -0.0085 0.0000
```

The probability of this hypothesis is `exp(-0.26392436027526855) = 0.768`
