### ISSUE TITLE
Cannot load models transformer_lm.gbw.adaptive_huge and transformer_lm.wiki103.adaptive

### ISSUE THREAD

**Issue by KsenijaS** [pytorch/fairseq#2672]
## 🐛 Bug
When loading models transformer_lm.gbw.adaptive_huge and transformer_lm.wiki103.adaptive using torch.hub.load I got this error:
AttributeError: 'Namespace' object has no attribute 'bpe_codes'

### To Reproduce
model = torch.hub.load('pytorch/fairseq', 'transformer_lm.gbw.adaptive_huge', tokenizer='moses', bpe='fastbpe')

### Expected behavior
Models to load.

### Environment

 - fairseq Version (e.g., 1.0 or master): 0.9
 - PyTorch Version (e.g., 1.0) 1.7
 - OS (e.g., Linux): 18.04
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.2 /8.0.2
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
The GBW model doesn't use BPE, so it should work if you remove the `bpe='fastbpe'` part.

I also recommend adding `tokenizer='moses', moses_no_escape=True`, based on looking at the dict.txt file in the model archive
