### ISSUE TITLE
How to load data in batches instead of all at once ?

### ISSUE THREAD

**Issue by zhao1402072392** [pytorch/fairseq#2677]
Recently, I have been using Transformer for machine translation task. But the data set is too large, and M appears when loading data to GPU, I want to load data in batches, could you please tell me how do I modify the load data section? Thanks very much!

**Comment by myleott** [comment]
Ah, we added some documentation for this recently, but I forgot to rebuild the readthedocs.

You should be able to chunk you dataset into multiple data-bins and train over them: https://fairseq.readthedocs.io/en/latest/getting_started.html#sharding-very-large-datasets

**Comment by zhao1402072392** [comment]
I splitted my input file into 4 chunks, and then call fairseq-preprocess 4 times. and I use the command : fairseq-train data-bin1:data-bin2:data-bin3:data-bin4 . And I put test dataset and valid dataset in data-bin1. I include the same vocabulary in each of my data-bin folders. But it also have MemoryError. Do I need to include the same vocabulary in each of my data-bin folders? And could you give me some advice?
