### ISSUE TITLE
How to generate multiple translations for a single sentence?

### ISSUE THREAD

**Issue by customer101** [pytorch/fairseq#2680]
I have `fconv` translation model and I want to get the best `K` translations for a single sentence.

I'm using this code:
```
from fairseq.models.fconv import FConvModel
model = FConvModel.from_pretrained(**)
model.eval()
model.translate(sent)
```
I traced the translate method, but couldn't find what parameter should I provide to get best `K` translation, though `fairseq-interactive` with `--nbest` returns multiple translations.

 - fairseq Version: v0.9.0
 - PyTorch Version: 1.6.0
 - OS: Linux
 - How you installed fairseq: `pip install --editable ./` 
 - Python version: 3.6.9

**Comment by myleott** [comment]
You need to use the `.generate` interface. Try something like this:

```python
>>> en = model.encode("Hello world")
>>> outputs = model.generate(en, beam=5, nbest=5)
>>> [en2fr.decode(x['tokens']) for x in output]
['Bonjour à tous.', 'Bonjour au monde', 'Bonjour à tous', 'Bonjour monde', 'Bonjour.']
```
