### ISSUE TITLE
training speed is too much slowly

### ISSUE THREAD

**Issue by dahaogewsh** [pytorch/fairseq#2683]
when I training the model just like "transformer_vaswani_wmt_en_de_big" ,and my wps is 1706 ,this is too much slow, I have run the training about one week, and now the training steps is 112000, one epoch has 522288 steps, so I have to run about one month to complete one epoch, this is too slow

**Comment by neel04** [comment]
@dahaogewsh I am having the same problem - In the earlier versions I believe there was no such problem but now with the current branch, It's taking 4x more time than previously thought

**Comment by myleott** [comment]
Sorry, we can't help if you don't share the command you ran and more details about your system setup. Please open a new Issue following the provided templates.
