### ISSUE TITLE
Is there any visualization method that can generate attention value visualization similar to "Attention is all you need"?

### ISSUE THREAD

**Issue by zhao1402072392** [pytorch/fairseq#2689]
I want to visualize the attention value in the transformer, is there a way, as shown below:
![image](https://user-images.githubusercontent.com/26305182/94986290-1c1ca180-0590-11eb-95c6-2ab8993205e0.png)

**Comment by 9Olive** [comment]
Hey! Have you tried using this [BertVis ](https://github.com/jessevig/bertviz) tool?  Here's a brief [article ](https://towardsdatascience.com/deconstructing-bert-distilling-6-patterns-from-100-million-parameters-b49113672f77) on it. Hope that helps!
