### ISSUE TITLE
Errors while evaluating CTC wav2vec model

### ISSUE THREAD

**Issue by kamakshi-malhotra** [pytorch/fairseq#2694]
### Command used
python examples/speech_recognition/infer.py ./manifest --task audio_pretraining --nbest 1 --path ./wav2vec_small_100h.pt --gen-subset dev_other --results-path ./ --w2l-decoder fairseqlm --lm-model ./lm_librispeech_word_transformer.pt --lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter

When I use this command I got error->

### Additional context
I have downloaded transformer model from wav2letter and its dictionary(renamed it as dict.txt). Also I have saved dict.ltr.txt provided in the link in wav2vec readme. 

### Environment

 - fairseq Version : 0.9.0
 - PyTorch Version : 1.6.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Python version: 3.8
 - CUDA/cuDNN version:10.1

**Comment by alexbittar** [comment]
Hello, have you solved this issue? I just had the same error
