### ISSUE TITLE
Custom vocabulary in wav2vec 2.0

### ISSUE THREAD

**Issue by bharat-patidar** [pytorch/fairseq#2699]
Hello everyone,

I am working on speech recognition model for the English language. So, I want to confirm _a)_ How can we add custom vocabulary to the already trained model **(wav2vec 2.0)** ?
Also, _b)_ Is there any way to control or reduce word spellings mistakes? Can we have ASR output in form of English dictionary/vocabulary words only?

Thank you in advance.

**Comment by ArtemisZGL** [comment]
@bharat-patidar hello, do you know how to get this vocabulary(https://dl.fbaipublicfiles.com/fairseq/wav2vec/dict.ltr.txt), I'm confused about the index after the symbol.

**Comment by mcggood** [comment]
> @bharat-patidar hello, do you know how to get this vocabulary(https://dl.fbaipublicfiles.com/fairseq/wav2vec/dict.ltr.txt), I'm confused about the index after the symbol.

you can can easily get dict.ltr.txt by simple for loop. It's chars count by descending order
