### ISSUE TITLE
Custom <init> tokens

### ISSUE THREAD

**Issue by SinghJasdeep** [pytorch/fairseq#270]
Hello, 

I am doing a translation task where my data already has custom init tokens on the target language side, (but no eos tokens). 

What in the code do I need to disable so that fairseq does not add an extra init/ pad" token to the beginnings of each target sentence. 

Thank you!

**Comment by SinghJasdeep** [comment]
I understand that taking out the code that adds the padding or init token might break generation. This is okay, I just need to train & val.

**Comment by huihuifan** [comment]
We use the same token for beginning of sentence and end of sentence, so you don't need to modify the dictionary. You just need to modify where the <s> is being appended to the beginning of the sentence for each example. You can check out how this is being done in fairseq/data.

**Comment by SinghJasdeep** [comment]
For others who may want this you can change the collate_tokens function in fairseq/data/data_utils.py

Thanks @huihuifan
