### ISSUE TITLE
[wav2vec 2.0] How to get char time information

### ISSUE THREAD

**Issue by shoegazerstella** [pytorch/fairseq#2701]
I am using [this](https://github.com/loretoparisi/wave2vec-recognize-docker) code for doing inference with wav2vec on an audio file. There is a discussion about it [here](https://github.com/pytorch/fairseq/issues/2651).

The code works fine and I am able to get the transcription, but I was wondering if there was a way to get information on the times at which each character appears with respect to the audio duration, like some sort of synchronization.

Some ASR models output a matrix with char probabilities. Each column of the matrix corresponds to the inference done on some portion of audio, usually the window is very small.

 Is it possible to get a similar output using wav2vec? How can I modify the code for doing this? Thanks a lot!

**Comment by lbinding** [comment]
Hey, was any progress made on this?
