### ISSUE TITLE
[wav2vec2.0]Error while evaluating CTC model using Transformer LM

### ISSUE THREAD

**Issue by kamakshi-malhotra** [pytorch/fairseq#2704]
#### Command used ->
python examples/speech_recognition/infer.py ./manifest --task audio_pretraining --nbest 1 --path ./wav2vec2_vox_960h.pt --gen-subset dev_other --results-path ./manifest/ --w2l-decoder fairseqlm --lm-model ./lm_librispeech_word_transformer.pt --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000
  
#### Error shown->
INFO:__main__:Namespace(all_gather_list_size=16384, batch_size=None, beam=5, beam_size_token=100, beam_threshold=25.0, bf16=False, bpe=None, broadcast_buffers=False, bucket_cap_mb=25, checkpoint_suffix='', constraints=None, cpu=False, criterion='ctc', curriculum=0, data='./manifest', data_buffer_size=10, dataset_impl=None, ddp_backend='c10d', decoding_format=None, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, distributed_wrapper='DDP', diverse_beam_groups=-1, diverse_beam_strength=0.5, diversity_rate=-1.0, dump_emissions=None, dump_features=None, empty_cache_freq=0, enable_padding=False, fast_stat_sync=False, find_unused_parameters=False, fix_batches_to_gpus=False, fixed_validation_seed=None, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, gen_subset='dev_other', iter_decode_eos_penalty=0.0, iter_decode_force_max_iter=False, iter_decode_max_iter=10, iter_decode_with_beam=1, iter_decode_with_external_reranker=False, kenlm_model='./lm_librispeech_word_transformer.pt', kspmodel=None, labels='ltr', lenpen=1, lexicon=None, lm_weight=0.2, load_emissions=None, local_rank=0, localsgd_frequency=3, log_format=None, log_interval=100, lr_scheduler='fixed', lr_shrink=0.1, match_source_len=False, max_len_a=0, max_len_b=200, max_sample_size=None, max_sentences=None, max_sentences_valid=None, max_tokens=4000000, max_tokens_valid=4000000, memory_efficient_bf16=False, memory_efficient_fp16=False, min_len=1, min_loss_scale=0.0001, min_sample_size=None, model_overrides='{}', model_parallel_size=1, nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, no_repeat_ngram_size=0, no_seed_provided=False, normalize=False, nprocs_per_node=1, num_shards=1, num_workers=1, optimizer=None, path='./wav2vec2_vox_960h.pt', pipeline_balance=None, pipeline_checkpoint='never', pipeline_chunks=0, pipeline_devices=None, pipeline_model_parallel=False, prefix_size=0, print_alignment=False, print_step=False, profile=False, quantization_config_path=None, quiet=False, remove_bpe=None, replace_unk=None, required_batch_size_multiple=8, required_seq_len_multiple=1, results_path='./manifest/', retain_dropout=False, retain_dropout_modules=None, retain_iter_history=False, rnnt_decoding_type='greedy', rnnt_len_penalty=-0.5, sacrebleu=False, sample_rate=16000, sampling=False, sampling_topk=-1, sampling_topp=-1.0, score_reference=False, scoring='bleu', seed=1, shard_id=0, sil_weight=0.0, skip_invalid_size_inputs_valid_test=False, slowmo_algorithm='LocalSGD', slowmo_momentum=None, task='audio_pretraining', temperature=1.0, tensorboard_logdir=None, threshold_loss_scale=None, tokenizer=None, tpu=False, train_subset='train', unit_lm=False, unk_weight=-inf, unkpen=0, unnormalized=False, user_dir=None, valid_subset='valid', validate_after_updates=0, validate_interval=1, validate_interval_updates=0, w2l_decoder='fairseqlm', warmup_updates=0, wer_args=None, wfstlm=None, word_score=-1.0, zero_infinity=False, zero_sharding='none')
INFO:fairseq.data.audio.raw_audio_dataset:loaded 2864, skipped 0 samples
INFO:__main__:| ./manifest dev_other 2864 examples
INFO:__main__:| decoding with criterion ctc
INFO:__main__:| loading model(s) from ./wav2vec2_vox_960h.pt

  warnings.warn(
Namespace(activation_dropout=0.1, activation_fn='relu', adaptive_input=True, adaptive_input_cutoff='60000,160000', adaptive_input_factor=4.0, adaptive_softmax_cutoff='60000,160000', adaptive_softmax_dropout=0, adaptive_softmax_factor=4.0, add_bos_token=False, arch='transformer_lm_gbw', attention_dropout=0.1, best_checkpoint_metric='loss', bpe=None, bucket_cap_mb=25, char_embedder_highway_layers=2, character_embedding_dim=4, character_embeddings=False, character_filters='[(1, 64), (2, 128), (3, 192), (4, 256), (5, 256), (6, 256), (7, 256)]', clip_norm=0.1, cpu=False, criterion='adaptive_loss', curriculum=0, data='.', dataset_impl=None, ddp_backend='no_c10d', decoder_attention_heads=16, decoder_embed_dim=1280, decoder_ffn_embed_dim=6144, decoder_input_dim=1280, decoder_layers=20, decoder_learned_pos=False, decoder_normalize_before=True, decoder_output_dim=1280, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method='tcp://learnfair1288:10075', distributed_no_spawn=False, distributed_port=10075, distributed_rank=0, distributed_world_size=128, dropout=0.1, empty_cache_freq=0, fast_stat_sync=False, find_unused_parameters=False, fix_batches_to_gpus=False, fixed_validation_seed=None, fp16=True, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, future_target=False, keep_interval_updates=1, keep_last_epochs=-1, lazy_load=False, log_format='json', log_interval=1000, lr=[0.05], lr_scheduler='inverse_sqrt', max_epoch=100, max_sentences=None, max_sentences_valid=None, max_target_positions=256, max_tokens=2048, max_tokens_valid=2048, max_update=0, maximize_best_checkpoint_metric=False, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=-1, momentum=0.99, no_decoder_final_norm=True, no_epoch_checkpoints=True, no_last_checkpoints=False, no_progress_bar=False, no_save=False, no_save_optimizer_state=False, no_token_positional_embeddings=False, num_workers=1, optimizer='nag', optimizer_overrides='{}', output_dictionary_size=-1, past_target=False, raw_text=False, required_batch_size_multiple=8, reset_dataloader=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', sample_break_mode='eos', save_dir='/checkpoint/antares/2019-11-02/v4_reduced_lr_trlmgb.invsqrt.wrm16000.int1e-07.nag.lr0.05.clp0.1.lyr20.hd16.drp0.1.adp=60000_160000.ad_inp.ad_f4.ad_sf4.inp=60000_160000.tie.ffn6144.at_d0.1.rl_d0.1.i1280.m1280.o1280.mxtk2048.tps256.seed1.bm=eos.ngpu128', save_interval=1, save_interval_updates=40000, seed=1, self_target=False, sentence_avg=False, share_decoder_input_output_embed=False, skip_invalid_size_inputs_valid_test=True, task='language_modeling', tbmf_wrapper=False, tensorboard_logdir='/checkpoint/antares/tensorboard_logs/2019-11-02/v4_reduced_lr_trlmgb.invsqrt.wrm16000.int1e-07.nag.lr0.05.clp0.1.lyr20.hd16.drp0.1.adp=60000_160000.ad_inp.ad_f4.ad_sf4.inp=60000_160000.tie.ffn6144.at_d0.1.rl_d0.1.i1280.m1280.o1280.mxtk2048.tps256.seed1.bm=eos.ngpu128', threshold_loss_scale=None, tie_adaptive_proj=False, tie_adaptive_weights=True, tokenizer=None, tokens_per_sample=256, train_subset='train', update_freq=[1], use_bmuf=False, user_dir=None, valid_subset='valid', validate_interval=1, warmup_init_lr=1e-07, warmup_updates=16000, weight_decay=0.0)
INFO:fairseq.tasks.language_modeling:dictionary: 221456 types
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=47 error=100 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "examples/speech_recognition/infer.py", line 429, in <module>
    cli_main()
  File "examples/speech_recognition/infer.py", line 425, in cli_main
    main(args)
  File "examples/speech_recognition/infer.py", line 301, in main
    generator = build_generator(args)
  File "examples/speech_recognition/infer.py", line 297, in build_generator
    return W2lFairseqLMDecoder(args, task.target_dictionary)
  File "/home/kamakshi/speech_to_text/fairseq/examples/speech_recognition/w2l_decoder.py", line 360, in __init__
    self.lm = FairseqLM(self.word_dict, model)
  File "/home/kamakshi/speech_to_text/fairseq/examples/speech_recognition/w2l_decoder.py", line 221, in __init__
    model.cuda()
  File "/home/kamakshi/fair_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 458, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/kamakshi/fair_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/home/kamakshi/fair_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/home/kamakshi/fair_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/kamakshi/fair_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 376, in _apply
    param_applied = fn(param)
  File "/home/kamakshi/fair_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 458, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/kamakshi/fair_env/lib/python3.8/site-packages/torch/cuda/__init__.py", line 190, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:47

I don't have GPU in my system so I tried with --cpu in command but I am still getting the exact same error. Can someone help with this?

#### What's your environment?

 - PyTorch Version (e.g., 1.0): 1.6
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Python version: 3.8.2
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: NA

**Comment by mychiux413** [comment]
seems the FairseqLM always call `model.cuda()`, whatever you specify the `--cpu` or not
https://github.com/pytorch/fairseq/blob/3544f5f24eb52f3a7c5f2dba78462ca08d52c1f0/examples/speech_recognition/w2l_decoder.py#L221

In addition, when program loads the pretrained Fairseq Language Model, the argument: `args.cpu` should come from saved model, instead of your console arguments.

**Comment by pkadambi** [comment]
Have you specified the lexicon? https://github.com/pytorch/fairseq/issues/2651#issuecomment-720056844
