### ISSUE TITLE
back translation for the augmentation using trained models from torch.hub

### ISSUE THREAD

**Issue by JJumSSu** [pytorch/fairseq#2706]
Hi, thank you guys for the great library.

I'm currently trying to augment my text samples via back-translation.

I'm trying to use trained models from torch.hub (e.g., 'transformer.wmt19.en-de.single_model', 'transformer.wmt19.de-en.single_model')

I currently implemented my code something like this referencing the [link](https://github.com/GT-SALT/MixText/tree/master/data/yahoo_answers_csv).

```
en2de  = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.en-de.single_model', tokenizer='moses', bpe='fastbpe')
de2en  = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.de-en.single_model', tokenizer='moses', bpe='fastbpe')
for sentence in range sent_lines:
    # sentence is a string (e.g. "hello")
    de2en.translate(en2de.translate(sentence,  sampling = True, temperature = 0.8),  sampling = True, temperature = 0.8))
```
first of all, I'm not sure whether this is the correct implementation. (sampling in both directions?)

secondly, this piece of code conducts back-translation sample-wise, thus being extremely slow. I want to do it batch-wise. Do I have to use ```fairseq-generate``` for this case? (doing ```fairseq-preprocess``` beforehand with the dictionary from the pretrained-model).

Thank you :)

**Comment by myleott** [comment]
You can do batches generation via the torch.hub interface, but for anything large you should use fairseq-preprocess and fairseq-generate.

You can take a look at this walkthrough for backtranslation: https://github.com/pytorch/fairseq/tree/master/examples/backtranslation#training-your-own-model-wmt18-english-german

Note that backtranslation typically starts with monolingual data on the target side, so you’re only translating once. You don’t need to do round-trip translations.

**Comment by JJumSSu** [comment]
Thank you for the novel comment. @myleott 

However, I'm now currently facing a new issue when translating sentences batch-wise.

![image](https://user-images.githubusercontent.com/39372342/95719454-cb512b00-0caa-11eb-841b-6faa3b0dbb3c.png)

When the input consists of 3 sentences (i.e. 3 elements of strings in list format),  the output from the hub's translate function is weird (3 elements are concatenated as one string which is shown in the figure).

This works fine when running on the local machine (3 elements of strings -> 3 elements of strings).
However when running from the docker, the output is weird as shown in the figure. 

I installed the fairseq using ```pip install fairseq==0.9.0``` and am using torch==1.5.1 and python==3.6.9

Is this a bug? or am I'm doing something wrong?

**Comment by JJumSSu** [comment]
Running on docker kept failing, so I solved the problem by running on local machine (conda environment). Batch-wise processing works nicely. Thank you!
