### ISSUE TITLE
(wav2vec2.0)when I finetune the pretrained model, The performance of pre-trained model connected to Transformer decoder is worse than that of CTC？

### ISSUE THREAD

**Issue by zqs01** [pytorch/fairseq#2709]
Hello everyone, I have a question. When I finetune the pretrained model, The performance of pre-trained model connected to Transformer decoder is worse than that of CTC？Generally speaking, the result of accessing the decoder is better than the result of accessing the CTC. I want to know if anyone else has encountered the same problem and how to solve it. Thanks a lot.

**Comment by phantomcoder1996** [comment]
Yes, I have the same problem the viterbi decoder gets much better results
