### ISSUE TITLE
AttributeError: 'SpeechRecognitionEspressoTask' object has no attribute 'feat_dim'

### ISSUE THREAD

**Issue by krishnanpooja** [pytorch/fairseq#2711]
## 🐛 Bug

The SpeechRecognitionEspressoTask has no attribute 'feat_dim'. Issue seen when trying to evaluate the model. 

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Try to import pretrained model using checkpoint file.
2. See error

```
model = models.build_model(args, self)
File "git/espresso/fairseq/models/init.py", line 48, in build_model
return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
File "git/espresso/espresso/models/speech_transformer.py", line 128, in build_model
logger.info("input feature dimension: {}, channels: {}".format(task.feat_dim, task.feat_in_channels))
AttributeError: 'SpeechRecognitionEspressoTask' object has no attribute 'feat_dim'
```

### Expected behavior

No error

### Environment

 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version (e.g., 1.0) 1.6.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip

**Comment by erip** [comment]
This seems like a bug for espresso rather than fairseq.

**Comment by krishnanpooja** [comment]
I used the issues in espresso I don't know how it ended up in fairseq. Will reopen the ticket in espresso.
