### ISSUE TITLE
How to load transformer model from local files?

### ISSUE THREAD

**Issue by junwen-austin** [pytorch/fairseq#2718]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
Due to the restriction of my company's Internet policy, I'd like to see if it is possible to load a transformer model locally.  I was able to download the model file for wmt19.de-en.joined-dict.single_model from the following link

https://dl.fbaipublicfiles.com/fairseq/models/wmt19.de-en.joined-dict.single_model.tar.gz

based on the link in the [source code](https://github.com/pytorch/fairseq/blob/master/fairseq/models/transformer.py)
and also unzipped it into the directory `wmt19.de-en.joined-dict.single_model`. The files under it are 

- model.pt
- dict.de.txt
- dict.en.txt
- bpecodes.txt

and I have installed fairseq from PyPI.

My question is, how do I initialize the transformer model locally?

I tried the following and it does not work:

```
from fairseq.models.transformer import TransformerModel
en2de = TransformerModel.from_pretrained('wmt19.de-en.joined-dict.single_model','model.pt')
```

```
 en2de = TransformerModel.from_pretrained('wmt19.de-en.joined-dict.single_model', 'model.pt')
Archive name 'wmt19.de-en.joined-dict.single_model' was not found in archive name list. We assumed 'wmt19.de-en.joined-dict.single_model' was a path or URL but couldn't find any file associated to this path or URL.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xc/opt/anaconda3/envs/nmt/lib/python3.7/site-packages/fairseq/models/fairseq_model.py", line 174, in from_pretrained
    **kwargs,
  File "/Users/xc/opt/anaconda3/envs/nmt/lib/python3.7/site-packages/fairseq/hub_utils.py", line 51, in from_pretrained
    kwargs['data'] = os.path.abspath(os.path.join(model_path, data_name_or_path))
  File "/Users/xc/opt/anaconda3/envs/nmt/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```
Looking at the [source code](https://github.com/pytorch/fairseq/blob/master/fairseq/models/fairseq_model.py) of `from_pretrained` does not reveal much:

```
def from_pretrained(
        cls,
        model_name_or_path,
        checkpoint_file="model.pt",
        data_name_or_path=".",
        **kwargs,
    ):
        """
        Load a :class:`~fairseq.models.FairseqModel` from a pre-trained model
        file. Downloads and caches the pre-trained model file if needed.
        The base implementation returns a
        :class:`~fairseq.hub_utils.GeneratorHubInterface`, which can be used to
        generate translations or sample from language models. The underlying
        :class:`~fairseq.models.FairseqModel` can be accessed via the
        *generator.models* attribute.
        Other models may override this to implement custom hub interfaces.
        Args:
            model_name_or_path (str): either the name of a pre-trained model to
                load or a path/URL to a pre-trained model state dict
            checkpoint_file (str, optional): colon-separated list of checkpoint
                files in the model archive to ensemble (default: 'model.pt')
            data_name_or_path (str, optional): point args.data to the archive
                at the given path/URL. Can start with '.' or './' to reuse the
                model archive path.
        """
```

Thank you so much for your help!

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):  0.9
 - PyTorch Version (e.g., 1.0).  1.4
 - OS (e.g., Linux):  MacOS
 - How you installed fairseq (`pip`, source):   pip
 - Build command you used (if compiling from source):
 - Python version:   3.7
 - CUDA/cuDNN version:  None
 - GPU models and configuration: 
 - Any other relevant information:

**Comment by erip** [comment]
From a local file, the required args are:

```
model_name_or_path: path to the directory containing the checkpoint you want to load.
checkpoint_file: the name of the checkpoint file (not full path - just the name)
data_name_or_path: path to the directory containing the dictionaries 
```

additionally you'll want to provide...

```
bpe: the type of byte-pair encoding you used (sentencepiece, subword_nmt, etc.)
```

and then kwargs specific to that bpe choice.

**Comment by junwen-austin** [comment]
thanks it works now
