### ISSUE TITLE
Negative Constraints Implementation

### ISSUE THREAD

**Issue by JoaoPauloAires** [pytorch/fairseq#2720]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
Are you planning to implement the use of negative constraints on constrained decoding? If not, can you give me some tips to do it using the existing code?

Thanks in advance.
#### What have you tried?
I have not tried anything yet.
#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.6
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
  git clone https://github.com/pytorch/fairseq
  cd fairseq
  pip install --editable ./
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1/7.6
 - GPU models and configuration:
 - Any other relevant information:

**Comment by wangpeng138375** [comment]
I am also very concerned about this issue.

**Comment by wangpeng138375** [comment]
In negative constraint decoding, it's easy to avoid a word by setting its probability to inf. But for phrase, I'm a little confused. Is it just setting the probability of the last word in the phrase to inf?

**Comment by mjpost** [comment]
Yes, you have to track the state and only penalize the last word. You also have to take care to reset the state if you generate part of a phrase but then don't finish.  

The constraints interface in search.py should be sufficient, though I haven't thought it through. See LexicallyConstrainedBeamSearch. I think you would make a sister class of this and modify as appropriate. It's considerably easier to do than positive constraints and should be straightforward.

**Comment by JoaoPauloAires** [comment]
Thank you! I'll try to implement it following your instructions.

**Comment by wangpeng138375** [comment]
I created a PR at [here](https://github.com/pytorch/fairseq/pull/2958)
