### ISSUE TITLE
OOM error when resume pretraining (MBART) from checkpoint_last.pt

### ISSUE THREAD

**Issue by wasiahmad** [pytorch/fairseq#2721]
I was pretraining MBART on my data and it accidentally stopped. Then when I tried to resume the training, it is giving OOM error when `checkpoint_last.pt` is used. Fairseq tries to get back from the OOM error but it can't for a long time. So, I terminated the job. Then I tried to restore from a previous checkpoint and it works! So, my question is:

1. In what situation does the use of `checkpoint_last.pt` causes OOM error? I am using fp16 during pretraining.

2. Will there be any difference in optimization settings if I load from an earlier checkpoint? Say the last checkpoint was saved after 40k steps but I am loading from a checkpoint that was saved after 38k steps. Loading from 38k steps would cause me 2k steps to be done again but I assume in terms of learning rates and other optimization settings, things will be the same. Is it right?

**Environment**

```
Python 3.6.10 :: Anaconda, Inc.

Name: fairseq
Version: 0.9.0

NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
```

**Comment by firdota** [comment]
hello，how can we continue pretraining mBART from the released checkpoint? @wasiahmad
