### ISSUE TITLE
Cache loading fails when there is no internet connection

### ISSUE THREAD

**Issue by psorianom** [pytorch/fairseq#2724]
## 🐛 Bug

When getting resources from cache (with `get_from_cache` in [`file_utils.py`](https://github.com/pytorch/fairseq/blob/60442af216d551e4afc9d4fab1c056c1051725cc/fairseq/file_utils.py#L243)), and not having an internet connection, the launched process fails (after several retrials in [`request_wrap_timeout`](https://github.com/pytorch/fairseq/blob/60442af216d551e4afc9d4fab1c056c1051725cc/fairseq/file_utils.py#L216)) with a `RuntimeError` that is not handled in the caller function ([`get_from_cache`](https://github.com/pytorch/fairseq/blob/60442af216d551e4afc9d4fab1c056c1051725cc/fairseq/file_utils.py#L267)). Instead, an `EnvironmentError` exception is handled and thus the `RuntimeError`exception ends the process, **even if the searched file is already cached**. 

#### Code sample

```python
from fairseq.file_utils import get_from_cache
url = "https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/encoder.json"

path = get_from_cache(url)
print(f"This is the path I got: {path}")
```

```bash
File "/home/user/fairseq/fairseq/file_utils.py", line 225, in request_wrap_timeout
    raise RuntimeError(f"Unable to fetch file {url}")
RuntimeError: Unable to fetch file https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/encoder.json
```

### Expected behavior
The process should not end if the file is already cached. When catching the exception, the value of `etag` should be set to `None` and finally the cached file path should be found.

```bash
This is the path I got: /home/user/.cache/torch/pytorch_fairseq/e2aab4d600e7568c2d88fc7732130ccc815ea84ec63906cb0913c7a3a4906a2e.
0f323dfaed92d080380e63f0291d0f31adfa8c61a62cbcb3cb8114f061be27f7

```

### Environment

 - fairseq Version : master
 - PyTorch Version : 1.6.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): `git clone` + `pip install -e .`

 - Python version: 3.7.9
 - CPU

### Additional context

A proper solution would entail not needing an internet connection to check if we have the file cached in disk. I guess this has been already pondered and the current solution must be the best.

A simple way to address the returned exception, `RuntimeError`, would be to handle it *in lieu* of the handled `EnvironmentError`, as it stands. This is proposed in a [branch of mine](https://github.com/pytorch/fairseq/compare/master...psorianom:request_wrap_exception).

**Comment by myleott** [comment]
Your fix looks good to me! Can you please submit a PR?

**Comment by psorianom** [comment]
yes ! I will do that!

**Comment by uhuohuy** [comment]
Hi psorianom,
Thanks! Your solution really helps
