### ISSUE TITLE
IndexedDataset instead of IndexedInMemoryDataset

### ISSUE THREAD

**Issue by SinghJasdeep** [pytorch/fairseq#273]
How do you switch from using IndexedInMemoryDataset to IndexedDataset? 

Thank you!

**Comment by myleott** [comment]
I think you would change this to IndexedDataset: https://github.com/pytorch/fairseq/blob/6381cc977fa909bd53c8915a18684e49b3507332/fairseq/tasks/translation.py#L117. It shouldn't be necessary to change preprocess.py

**Comment by SinghJasdeep** [comment]
Thank you @myleott 

Changing to IndexedDataset works like a charm.
