### ISSUE TITLE
OOM when fine-tune BART for summarization

### ISSUE THREAD

**Issue by monologue1107** [pytorch/fairseq#2731]
#### What is your question?

With my GPU 1080Ti with 12GB memory, it keeps having errors OOM until I decrease the max_tokens to 64. However, it has another error below:
"AssertionError: sentence at index 2512 of size 101 exceeds max_tokens limit of 64!"
So is it possible to fine-tune bart with 12GB memory?  I wonder it cannot have great performance in 64 tokens even if it can run successfully.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):cent os7
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by moussaKam** [comment]
Try with --memory-efficient-fp16 . Otherwise, you can use the base architecture instead of the large one.
Also you can use --truncate-source to avoid exceeding limit error.

**Comment by monologue1107** [comment]
> Try with --memory-efficient-fp16 . Otherwise, you can use the base architecture instead of the large one.
> Also you can use --truncate-source to avoid exceeding limit error.

Thanks for your reply. I used --memory-efficient-fp16 for bart-large model and now train successfully with max_tokens=1024 in two 1080Ti GPU with 12GB memory. Hope for good training results.
