### ISSUE TITLE
Wav2vec 2.0 decoding with KenLM failed

### ISSUE THREAD

**Issue by sooftware** [pytorch/fairseq#2734]
When I try evaluating the wav2vec-2.0 model with Ken-LM, I encounter a `Segmentation fault` error.  
By debugging, I found the location that this error occurs.  
  
In `examples/speech_recognition/w2l_decoder.py`  145-153 line (W2lKenLMDecoder Class)
```python
for i, (word, spellings) in enumerate(self.lexicon.items()):
        word_idx = self.word_dict.get_index(word)
        _, score = self.lm.score(start_state, word_idx)
        for spelling in spellings:
            spelling_idxs = [tgt_dict.index(token) for token in spelling]
            assert (
                tgt_dict.unk() not in spelling_idxs
            ), f"{spelling} {spelling_idxs}"
            self.trie.insert(spelling_idxs, word_idx, score)
```
  
I download lexicon from https://dl.fbaipublicfiles.com/fairseq/wav2vec/librispeech_lexicon.lst  
and I download kenlm from https://dl.fbaipublicfiles.com/wav2letter/lexicon_free/librispeech/models/lm/lm_librispeech_kenlm_word_4g_200kvocab.bin  
  
I don't know what I did wrong. Please let me know.  
  
Thank You !!

* Command
```
python examples/speech_recognition/infer.py $MANIFEST_PATH --task audio_pretraining \
--nbest 1 --path /data/project/rw/kaki/model/wav2vec/wav2vec2_vox_960h.pt --gen-subset test-other \
--results-path /root/ --w2l-decoder kenlm \
--lm-model /data/project/rw/kaki/model/wav2vec/lm_librispeech_kenlm_word_4g_200kvocab.bin  \
--lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 \
--post-process letter --lexicon /data/project/rw/kaki/model/wav2vec/librispeech_lexicon.lst
```

**Comment by alexeib** [comment]
i dont know either :(
whats the error? is there any stacktrace?
can you try downloading the official librispeech kenlm? wav2letter people usually lowercase their output, but for official librispeech (and in our dictionaries) it is uppercased

**Comment by sooftware** [comment]
Here are download list:  
  
[lexicon](https://dl.fbaipublicfiles.com/fairseq/wav2vec/librispeech_lexicon.lst)  
[4-gram-arpa](http://www.openslr.org/resources/11/4-gram.arpa.gz)  
[dict.ltr.txt](https://dl.fbaipublicfiles.com/fairseq/wav2vec/dict.ltr.txt)  
  
Unfortunately, there is no separate stacktrace.  Just Segmentation Fault.  
  
What I found by debugging is that the W2lKenLMDecoder __init__ method in the w2l_decoder.py file produces Segmentation Fault in this section.  
  
```python
start_state = self.lm.start(False)
for i, (word, spellings) in enumerate(self.lexicon.items()):
    word_idx = self.word_dict.get_index(word)
    _, score = self.lm.score(start_state, word_idx)
    for spelling in spellings:
        spelling_idxs = [tgt_dict.index(token) for token in spelling]
        assert (
            tgt_dict.unk() not in spelling_idxs
        ), f"{spelling} {spelling_idxs}"
        self.trie.insert(spelling_idxs, word_idx, score)
self.trie.smear(SmearingMode.MAX)
```  
  
It's not that it doesn't work at all, it iterates and it dies.  
  
I don't know what I am wrong.

**Comment by mychiux413** [comment]
I had encountered error while iterating dataset, but I fixed it after removing the characters which doesn't exist in `dict.ltr.txt`. or maybe you can send your manifest file like `test.ltr`, `test.wrd`, `test.tsv` to me, I can help you to check the integrity.
mychiux413@gmail

**Comment by sooftware** [comment]
@mychiux413  Thank You!! I'll send my manifest files.

**Comment by mychiux413** [comment]
@sooftware I inference your datasets, and everything is fine, the WER is 2.08 with --lm-weight 1.0 --word-score -1, so maybe the problem lies in the program instead of the datasets or command.

**Comment by sooftware** [comment]
@mychiux413 Thank You for Check!!  
Can you share the wav2letter installation command?

**Comment by mychiux413** [comment]
I didn't install it, I just used the docker image: `wav2letter/wav2letter:cpu-latest`, installing everything right is a nightmare for me.
Maybe you can inspect the history of the image to realize how to install them.
``` bash
docker pull wav2letter/wav2letter:cpu-latest

# To inspect the history of the building commands
docker history wav2letter/wav2letter:cpu-latest

# Just extract the "kenlm" keywords
docker history --format "{{.CreatedBy}}" --no-trunc wav2letter/wav2letter:cpu-latest | grep kenlm
```

**Comment by sooftware** [comment]
Thank You @mychiux413 !!

**Comment by tonyyy10111** [comment]
@sooftware How did you solve the problem?

**Comment by sooftware** [comment]
@tonyyy10111 I don't. 
I haven't solved this problem yet.

**Comment by EmreOzkose** [comment]
Is there any solution for this problem? I have the same one.
