### ISSUE TITLE
PyPI has old fairseq code. Can we get the package refreshed?

### ISSUE THREAD

**Issue by pankajksingh** [pytorch/fairseq#2737]
## What is your question?
According to PyPI(https://pypi.org/project/fairseq/#history), the latest package was released on Dec4, 2019
Can we get a refresh for 2020? What is your cadence of updating this location?

**Comment by erip** [comment]
@pankajksingh we just bumped the repo's version to 1.0.0a0. I'm given to believe that the anticipated release cadence going forward is more regular, but I'll defer to an actual maintainer to provide details. 😄

**Comment by myleott** [comment]
Yes, we plan to release 1.0.0 in the near future, and thereafter will provide more regular releases.

**Comment by pankajksingh** [comment]
Thanks. Looking forward to more regular updates to PyPI

**Comment by scgupta** [comment]
@myleott Any timeframe in mind. I want to use wav2vec 2.0 from pypi instead of source code. thx.
