### ISSUE TITLE
noisechannel code issue

### ISSUE THREAD

**Issue by wns823** [pytorch/fairseq#2738]
## 🐛 Bug

For reproducing noisechannel code, I just executed the Example usage Script. But I saw some errors.
'FileNotFoundError: [Errno 2] No such file or directory: 
'/home/compu/GAN/fairseq/examples/noisychannel/rerank_data/wmt17/nbest_10_subset_test_fw_name_model_ex_shard_0_of_1/rescore_data_new_bpe.en' '

In my guess, the Latest code is not uploaded. So, I hope to see the latest code. 

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0) : torch 1.4
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed fairseq (`pip`, source): pip install --editable ./
 - Python version: Python 3.8
 - CUDA/cuDNN version: CUDA 11.0
 - GPU models and configuration: NVIDIA TITAN RTX 
 - Any other relevant information:

**Comment by myleott** [comment]
What commands did you run? What's the full error message + stack trace?

**Comment by wns823** [comment]
I just use the Example usage script with beam_size = 10.
![default](https://user-images.githubusercontent.com/30249213/96375087-e394de80-11b1-11eb-98db-cd68a1883148.png)

This is error message.
![스크린샷, 2020-10-15 22-57-10](https://user-images.githubusercontent.com/30249213/96375158-471f0c00-11b2-11eb-969f-de9ef79d98fa.png)

**Comment by kurtabela** [comment]
How was this issue fixed exactly? I still get the same error
