### ISSUE TITLE
English to Chinese translation training tutorials

### ISSUE THREAD

**Issue by jinfagang** [pytorch/fairseq#274]
Hi, is there any resources or tutorial abouth translate Chinese to English?

**Comment by jinfagang** [comment]
@edunov Thanks, the big question is about hyper parameters. I'll take a dive into that

**Comment by GeorgeS2019** [comment]
@benbijituo 

I follow the data preparation according to https://github.com/benbijituo/fairseq-zh-en

For the provided [pretrained model,](https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper) using the approach data preparatoin for zh-en dose not work. 

Anyone has working experience **how to prepare the binary data** needed for this [pre-trained model](https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper)?

**Comment by GeorgeS2019** [comment]
It is not clear for me if the data binary preparation step needs a join dictionary for this [pre-trained model ](https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper)as described [here](https://github.com/pytorch/fairseq/issues/1239#issue-506234985)

```bash
fairseq-preprocess --source-lang zh --target-lang en \
    --trainpref data/train --validpref data/valid --testpref data/test \
    --joined-dictionary \
    --destdir data-bin \
    --workers 20`

**Comment by GeorgeS2019** [comment]
For users looking for Zh to En translation, now there is a new [link ](https://github.com/pytorch/fairseq/issues/1260#issuecomment-566276257)to follow.
