### ISSUE TITLE
Freezing while Finetuning Wav2vec 2.0 Models

### ISSUE THREAD

**Issue by spygaurad** [pytorch/fairseq#2740]
How can i freeze the finetuned wav2vec 2.0 .pt model upto certain layers and train on other language so that i can achieve transfer learning ?

**Comment by medabalimi** [comment]
How many hours of labeled data do you have on the target language?

**Comment by spygaurad** [comment]
@medabalimi I have nearly 150 hours labeled data. I am experimenting with changing the model to make a multilingual decoder.

**Comment by medabalimi** [comment]
If you have 150 hours labeled data try just try training on it.

**Comment by spygaurad** [comment]
I dont have the training resource right now. So i am using smaller size of labelled audios. Also i want my model to learn some english styles as well because i am trying to implement the model on bilingual data.
