### ISSUE TITLE
Wav2vec2.0 libri_labels.py not working correctly on windows

### ISSUE THREAD

**Issue by phantomcoder1996** [pytorch/fairseq#2744]
## 🐛 Bug

When running the script fairseq/examples/wav2vec/libri_labels.py  to generate librispeech labels on windows , I get the error 
```
Traceback (most recent call last):
  File "libri_labels.py", line 56, in <module>
    main()
  File "libri_labels.py", line 37, in main
    trans_path = f"{parts[-2]}-{parts[-1]}.trans.txt"
IndexError: list index out of range

```

### To Reproduce
1- python wav2vec_manifest.py  LibriSpeech\train --dest LibriSpeech\train --ext flac
2- python libri_labels.py LibriSpeech\train\train.tsv --output-dir LibriSpeech\train --output-name train

### Expected behavior

generate train.ltr and train.wrd in the output-dir LibriSpeech\train

### Environment

 - fairseq Version (master):
 - OS (windows):

### Additional context

The problem is because the script relies on the linux path separator "/" 
I have created a PR to fix this issue

**Comment by wahyubram82** [comment]
it's not bug...

windows and linux, recognize path with mark '/'

in windows there is 3 folder that can use to recognize path (in python language):
`D:/Speech/Dataset/Libri` or `D:\\Speech\\Dataset\\Libri` or `r'D:\Speech\Dataset\Libri`

in linux, only one form:
`/home/username/Speech/Dataset/Libri`

they are similar, and the path can recognize in python, so the command to run python in windows is the false command.
the correction may be add the clue to README.md how to use in Windows. but i'm doubt it will be, may be the developer make it  to anybody who understood python language.
