### ISSUE TITLE
Change layer shape in Wav2Vec models

### ISSUE THREAD

**Issue by spygaurad** [pytorch/fairseq#2747]
Can i change the layer shape of the fine-tuned models?
eg. i want to change the final linear layer of  of fine-tuned English model of size torch.Size([36]) to torch.Size([Any other value]).

**Comment by spygaurad** [comment]
@alexeib do you have any insights regarding this ?

**Comment by alexeib** [comment]
you can certainly do this by modifying the code to replace the loader layer by a new one and then (optionally) copying part of the weights from the old layer. why would you want to do this?

**Comment by spygaurad** [comment]
thanks @alexeib for the reply. I am experimenting if i could create a bilingual decoder by further finetuning the english finetuned model on another language by concatenating the dictionary with that of english.

**Comment by edunov** [comment]
I'm not sure if there are still any questions, closing the issue, please reopen if you have any other questions

**Comment by rinoji** [comment]
@edunov @alexeib 
I am a Japanese high school student studying speech recognition. Is it possible to fine tune again using only 2 layers of the wav2vec fine tuned model (other layers freezed)? And please tell me how to do it.
