### ISSUE TITLE
different behavior in local machine was colab

### ISSUE THREAD

**Issue by tuhinjubcse** [pytorch/fairseq#2748]
![image](https://user-images.githubusercontent.com/3104771/96362649-cc47e980-10fc-11eb-8147-9339e9d2147d.png)

![image](https://user-images.githubusercontent.com/3104771/96362654-d669e800-10fc-11eb-8f83-322fb9b21f30.png)

Getting error in colab . Can anyone help ?

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version (e.g., 1.0) 1.3.1
 - OS (e.g., Linux): Linux vs Colab
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.3 vs 3.6
 - CUDA/cuDNN version: 10.1.243

**Comment by tuhinjubcse** [comment]
@myleott @ngoyal2707

**Comment by myleott** [comment]
Do you have any other local code changes?

**Comment by tuhinjubcse** [comment]
Not really

**Comment by myleott** [comment]
I'm not able to reproduce this with the released checkpoints. Can you try using a newer version of fairseq (master) + pytorch (1.6) and see if the issue persists?
