### ISSUE TITLE
How to translate a long text with fairest

### ISSUE THREAD

**Issue by junwen-austin** [pytorch/fairseq#2750]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
I am trying to back translate a long text from movie review data and it appears that somehow it was trucated and I have tried to set the max_len_a and max_len_b with no success 

#### Code

   
```
en2de = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.en-de.single_model', tokenizer='moses', bpe='fastbpe')
de2en = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.de-en.single_model', tokenizer='moses', bpe='fastbpe')

text = """
Evening is the beautiful story of the flawed love of a mother. The movie split in time, is magically shot, amazingly acted and has a touching script. Vanessa Redgrave plays Anne Grant Lord, a woman sun-setting out of life. Lying in her bed, her mind remembering and misfiring, she recalls her first mistake. Claire Danes plays the young Anne, giving a youthful vitality to dying bed ridden woman. Daughters Nina (Toni Collette) and Constance (Natasha Richardson) try to decipher the real story from the disheartening dementia. Her first mistake revolves around Harris Arden (Patrick Wilson); the man her best friend Lila (Mamie Gummer) deeply loved. The daughters must come to terms with their mother's past, and their futures. The cast is glowing in Evening. The collective acting energy of this movie could have powered the equipment for the production of this entire film. I am so glad to see Claire Danes working again, especially in this role. She is so young, and alive, fully living the joys, mistakes and heartbreak of young Anne's first mistake. This is a true feat when you realize she is playing a woman, dying in bed. When her life overwhelms her, you can feel her desire to crack and her hopeless hope that she won't. Some of her facial expressions grinded on me a little, but over all her performance was so radiant, I was left with that only as a side note. Toni Collette continues to prove that you can be a powerful actress without being a super model. She plays the black sheep of the family; a little lost. Nina finds a great deal of strength in her mother's mistake. Collette delicately avoids creating a cruel character who revels in the mistakes of her mother, instead choosing the wiser path of learning from her mother's mistakes. There is a great deal of infighting between Nina and her sister Constance. Their fights remind me of ones I have with my sister all the time. Mamie Gummer, who plays Anne's youthful best friend, is wonderful. Her character is stuck between her heart and her status in society. Even when she is crying and her heart is breaking, she is incredibly regal and charming. I can't wait to see her act in something else in the future. Vanessa Redgrave's performance is very hard for me to describe. Her talent at making her mental status ambiguous without being wacko or even especially tragic is why it is so powerful. The audience does not know if she is making up the story because she is slipping away or if these events truly happened. Physically and emotionally speaking, Redgrave is acting in a box. Not much physical space and limited emotional range might have been a stunner to a lesser actress but she makes the limitations work for her. I was constantly amazed. The movie is definitely woman-focused but the men in the movie are not just accessories. Patrick Wilson is mesmerizing as Harris. It is no wonder that everyone in the movie is in love with him, I sure was. Buddy Wittenborn is Lila's brother, spiraling out of control. Hugh Dancy spirals Buddy out of control without sending his acting down the drain. Glen Close has my favorite scene in the movie. It reminded me of the famous scene from Monster's Ball. It is terrible and jaw dropping grief. I was utterly stunned. The one acting disappointment was Natasha Richardson. While her fight scenes were memorable, most of her acting reeks of melodrama. It would have suited her to take an acting bath before we had to breathe her stink. It's a good thing she wasn't in charge of the visuals. The visuals of the movie are sparkling. Cinematographer Gyula Pados couldn't make a film richer in color, light so perfectly matched to mood and emotion. The visual concepts of the flash back sequences are powerful and resonating. There were many scenes that could have been stopped, printed, mounted and sold as art. I admit it, I cried. Evening is a powerful movie. Evening is defiantly a chick flick but a really great chick flick. If you want to impress a woman with a movie choice, pick Evening.
"""
print(text)
paraphrase = de2en.translate(en2de.translate(text,max_len_a=1, max_len_b=1000), max_len_a=1, max_len_b=1000)
print(paraphrase)

```

Below shows the original text and back translated text and one can see that the back translated text is much shorter than the original one and clearly the result was trucated somehow:

*Evening is the beautiful story of the flawed love of a mother. The movie split in time, is magically shot, amazingly acted and has a touching script. Vanessa Redgrave plays Anne Grant Lord, a woman sun-setting out of life. Lying in her bed, her mind remembering and misfiring, she recalls her first mistake. Claire Danes plays the young Anne, giving a youthful vitality to dying bed ridden woman. Daughters Nina (Toni Collette) and Constance (Natasha Richardson) try to decipher the real story from the disheartening dementia. Her first mistake revolves around Harris Arden (Patrick Wilson); the man her best friend Lila (Mamie Gummer) deeply loved. The daughters must come to terms with their mother's past, and their futures. The cast is glowing in Evening. The collective acting energy of this movie could have powered the equipment for the production of this entire film. I am so glad to see Claire Danes working again, especially in this role. She is so young, and alive, fully living the joys, mistakes and heartbreak of young Anne's first mistake. This is a true feat when you realize she is playing a woman, dying in bed. When her life overwhelms her, you can feel her desire to crack and her hopeless hope that she won't. Some of her facial expressions grinded on me a little, but over all her performance was so radiant, I was left with that only as a side note. Toni Collette continues to prove that you can be a powerful actress without being a super model. She plays the black sheep of the family; a little lost. Nina finds a great deal of strength in her mother's mistake. Collette delicately avoids creating a cruel character who revels in the mistakes of her mother, instead choosing the wiser path of learning from her mother's mistakes. There is a great deal of infighting between Nina and her sister Constance. Their fights remind me of ones I have with my sister all the time. Mamie Gummer, who plays Anne's youthful best friend, is wonderful. Her character is stuck between her heart and her status in society. Even when she is crying and her heart is breaking, she is incredibly regal and charming. I can't wait to see her act in something else in the future. Vanessa Redgrave's performance is very hard for me to describe. Her talent at making her mental status ambiguous without being wacko or even especially tragic is why it is so powerful. The audience does not know if she is making up the story because she is slipping away or if these events truly happened. Physically and emotionally speaking, Redgrave is acting in a box. Not much physical space and limited emotional range might have been a stunner to a lesser actress but she makes the limitations work for her. I was constantly amazed. The movie is definitely woman-focused but the men in the movie are not just accessories. Patrick Wilson is mesmerizing as Harris. It is no wonder that everyone in the movie is in love with him, I sure was. Buddy Wittenborn is Lila's brother, spiraling out of control. Hugh Dancy spirals Buddy out of control without sending his acting down the drain. Glen Close has my favorite scene in the movie. It reminded me of the famous scene from Monster's Ball. It is terrible and jaw dropping grief. I was utterly stunned. The one acting disappointment was Natasha Richardson. While her fight scenes were memorable, most of her acting reeks of melodrama. It would have suited her to take an acting bath before we had to breathe her stink. It's a good thing she wasn't in charge of the visuals. The visuals of the movie are sparkling. Cinematographer Gyula Pados couldn't make a film richer in color, light so perfectly matched to mood and emotion. The visual concepts of the flash back sequences are powerful and resonating. There were many scenes that could have been stopped, printed, mounted and sold as art. I admit it, I cried. Evening is a powerful movie. Evening is defiantly a chick flick but a really great chick flick. If you want to impress a woman with a movie choice, pick Evening.*

*The film is split in time, is magically shot, amazingly acted and has a touching script. Vanessa Redgrave plays Anne Grant Lord, a woman sunset from life. Lying in her bed, her mind remembers and misfires, she remembers her first mistake. Claire Danes plays the young Anne, gives a youthful vitality to bed-ridden woman. Daughters Nina (Toni Collette) and Constance (Natasha Richardson) try to decipher the real story of the disheartening dementia. Her first mistake revolves around Harris Arden (Patrick Wilson); the man deeply loved her best friend Lila (Mamie Gummer). The daughters must come to reconcile with their mother's past, and her future. The cast is glowing in Evening. The collective acting energy of this film could have driven the production of this entire movie.*

Thank you so much!

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):  0.9.0
 - PyTorch Version (e.g., 1.0).   1.4.0
 - OS (e.g., Linux):            MacOS
 - How you installed fairseq (`pip`, source):   pip
 - Build command you used (if compiling from source):
 - Python version:  3.7
 - CUDA/cuDNN version:   10.1
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
You should probably split the input into separate sentences. Most of these models have a maximum length that they support, due to the number of positional embeddings that were present at training time, so you can’t feed in arbitrarily long inputs.
