### ISSUE TITLE
What is the difference between each model in WMT'19 Ensemble model

### ISSUE THREAD

**Issue by babangain** [pytorch/fairseq#2752]
I was doing WMT'19 experiments.
There are four models in https://dl.fbaipublicfiles.com/fairseq/models/wmt19.en-de.joined-dict.ensemble.tar.gz

How they are different from each other?

Thanks.

**Comment by myleott** [comment]
They’re trained the same way, but begin from different random weight initializations (the --seed flag). Ensembling results from multiple models like this typically improves performance.
