### ISSUE TITLE
Zero-shot generating of pre-trained mBART25 behaves weirdly.

### ISSUE THREAD

**Issue by yongchanghao** [pytorch/fairseq#2755]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

I tried to run zero-shot generating with pre-trained mbart.cc25/model.pt. According to the description of paper, I expected it to generate something similar with source tokens. However, all it can generate are "," and "...". 

Do you have any idea about this problem?

Thank you.

#### What have you tried?
I've checked the format of `sample['net_input']['src_tokens']`, `sample['net_input']['prev_output_tokens']`, and `sample['target']`. They are as follows:
* src: `▁risk s </s> [en_XX]`
* prev_output: `[en_XX] ▁risk s </s>`
* target: `▁risk s </s> [en_XX]`

It seems like the correct input format that matches the pre-training objective of mbart. But it just could not generate legal sentences. Instead, it would output something like `,,,,,,,,...`.

#### What's your environment?

 - fairseq Version: master:
 - PyTorch Version: 1.6
 - OS: Linux
 - How you installed fairseq: source
 - Build command you used (if compiling from source): pip install -e .
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: V100
 - Any other relevant information:

**Comment by kaushal0494** [comment]
Hi @yongchanghao, I am facing a similar probelm.  Any suggestions how did you solved to the problem. Thank you!

**Comment by yongchanghao** [comment]
I didn't solve this problem actually. I pre-trained a new model and didn't find this problem. But the fine-tuning results are similar.

**Comment by kaushal0494** [comment]
Hi @yongchanghao, Thank you for your reply.  This seems a feasible solution. Are your code and pre-trained models are available openly?  Please share if possible.
