### ISSUE TITLE
Error while listing available models

### ISSUE THREAD

**Issue by Worm4047** [pytorch/fairseq#2756]
## 🐛 Bug

I'm trying to list available models and getting an error while doing that. This error wasn't there till yesterday but for some reason is showing today after updating the module.

### To Reproduce

1. I'm following the guide mentioned here - https://github.com/pytorch/fairseq/blob/master/examples/translation/README.md
2. Same error occurs on the google collab provided here - https://pytorch.org/hub/pytorch_fairseq_translation/
3. See error

`setuptools.sandbox.SandboxViolation: SandboxViolation: symlink('../config', 'fairseq/config') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

During handling of the above exception, another exception occurred:`

**Comment by myleott** [comment]
Ah, this is due to a recent change in our packaging script. I’ll work on a fix, thanks for opening the issue!
