### ISSUE TITLE
RoBERTa checkpoint trained on NSP objective

### ISSUE THREAD

**Issue by prajjwal1** [pytorch/fairseq#2759]
It has been mentioned in the RoBERTa paper that RoBERTa trained with NSP objective does not help in performance. But for my use case, I wanted to try out RoBERTa trained on NSP+MLM instead of the MLM one which is publicly released. Wanted to know if the NSP+MLM variant can be made publicly available. If it already is, can you please point me to it, unable to find it here and in HF model hub.

**Comment by myleott** [comment]
Sorry, we don’t have these. In any case, the models with NSP in the paper were smaller scale, so would not be comparable to the released models.
