### ISSUE TITLE
Getting error when trying to load a bart finetuned model from torch 1.6.0 to torch 1.6.0+cu101

### ISSUE THREAD

**Issue by tuhinjubcse** [pytorch/fairseq#2765]
## 🐛 Bug

![image](https://user-images.githubusercontent.com/3104771/96702630-f220f880-135f-11eb-86f8-182d9287f803.png)

### Environment

 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version (e.g., 1.0) 1.6.0+cu101
 - OS (e.g., Linux): Colab
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration:
 - Any other relevant information:

**Comment by tuhinjubcse** [comment]
@myleott

**Comment by myleott** [comment]
I'm not able to reproduce this. Can you try using the latest master version of fairseq and see if the issue is still there?
