### ISSUE TITLE
Link to M2M-100's WAT dataset is unavailable

### ISSUE THREAD

**Issue by nguyenvanhoang7398** [pytorch/fairseq#2770]
The link http://lotus.kuee.kyoto-u.ac.jp/WAT/my-en-data/wat2019.my-en.zip for WAT dataset used in M2M-100 example https://github.com/pytorch/fairseq/tree/master/examples/m2m_100 is not available. Would you mind double-checking it? 

Thank you.

**Comment by huihuifan** [comment]
Thanks, looks like the link is not valid anymore. It should be the same as this: http://lotus.kuee.kyoto-u.ac.jp/WAT/my-en-data/wat2020.my-en.zip

I will update the readme soon.

**Comment by zhmingzhaung** [comment]
> Thanks, looks like the link is not valid anymore. It should be the same as this: http://lotus.kuee.kyoto-u.ac.jp/WAT/my-en-data/wat2020.my-en.zip
> 
> I will update the readme soon.

The link is not valid again. I try [this](http://lotus.kuee.kyoto-u.ac.jp/WAT/my-en-data/wat2020.my-en.zip) but still doesn't work.
