### ISSUE TITLE
Access Denied to CRISS checkpoints

### ISSUE THREAD

**Issue by igorvlnascimento** [pytorch/fairseq#2771]
## 🐛 Access Denied

Access Denied to CRISS checkpoints

### To Reproduce

1. Run wget https://dl.fbaipublicfiles.com/fairseq/models/criss/criss_checkpoints.tar.gz
2. ERROR 403: Forbidden

**Comment by chtran** [comment]
The correct link should be https://dl.fbaipublicfiles.com/criss/criss_3rd_checkpoints.tar.gz. We will update the README accordingly.

Sorry for the confusion
