### ISSUE TITLE
m2m: generate OOMs on v100

### ISSUE THREAD

**Issue by sshleifer** [pytorch/fairseq#2772]
I ran the downloads and the documented "generate on a v100" command:

```bash
fairseq-generate \
    data_bin \
    --batch-size 1 \
    --path 12b_last_checkpoint.pt \
    --fixed-dictionary model_dict.128k.txt \
    -s de -t fr \
    --remove-bpe 'sentencepiece' \
    --beam 5 \
    --task translation_multi_simple_epoch \
    --lang-pairs language_pairs.txt \
    --decoder-langtok --encoder-langtok src \
    --gen-subset test \
    --fp16 \
    --dataset-impl mmap \
    --distributed-world-size 1 --distributed-no-spawn \
    --pipeline-model-parallel \
    --pipeline-chunks 1 \
    --pipeline-encoder-balance '[26]' \
    --pipeline-encoder-devices '[0]' \
    --pipeline-decoder-balance '[1,24,1]' \
    --pipeline-decoder-devices '[0,1,0]' > gen_out
```
on a V100 w torch 1.5 and I got OOM.
```bash
fairscale==0.0.3
fairseq # pip install -e . from source at 9b0611e6
torch==1.5.1+cu101
```

#### Questions
1) Has this command worked for others?
2) Does anyone have a working `generate` command that takes advantage of multiple gpus?

cc: @shruti-bh 

Thanks in advance!

**Comment by sshleifer** [comment]
Traceback suggests issue during fairscale's `split_module`:

```python
Traceback (most recent call last):
  File "/home/shleifer/.conda/envs/nb/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/home/shleifer/fairseq/fairseq_cli/generate.py", line 392, in cli_main
    main(args)
  File "/home/shleifer/fairseq/fairseq_cli/generate.py", line 53, in main
    return _main(cfg, sys.stdout)
  File "/home/shleifer/fairseq/fairseq_cli/generate.py", line 106, in _main
    num_shards=cfg.checkpoint.checkpoint_shard_count,
  File "/home/shleifer/fairseq/fairseq/checkpoint_utils.py", line 263, in load_model_ensemble
    num_shards,
  File "/home/shleifer/fairseq/fairseq/checkpoint_utils.py", line 301, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/home/shleifer/fairseq/fairseq/tasks/translation_multi_simple_epoch.py", line 204, in build_model
    return super().build_model(args)
  File "/home/shleifer/fairseq/fairseq/tasks/fairseq_task.py", line 548, in build_model
    model = models.build_model(args, self)
  File "/home/shleifer/fairseq/fairseq/models/__init__.py", line 56, in build_model
    return ARCH_MODEL_REGISTRY[cfg.arch].build_model(cfg, task)
  File "/home/shleifer/fairseq/fairseq/model_parallel/models/pipeline_parallel_transformer/model.py", line 277, in build_model
    checkpoint=args.pipeline_checkpoint,
  File "/home/shleifer/fairseq/fairseq/model_parallel/models/pipeline_parallel_transformer/model.py", line 73, in __init__
    checkpoint=checkpoint,
  File "/home/shleifer/.conda/envs/nb/lib/python3.7/site-packages/fairscale/nn/pipe/pipe.py", line 403, in __init__
    self.partitions, self.balance, self.devices = split_module(module, balance, devices)
  File "/home/shleifer/.conda/envs/nb/lib/python3.7/site-packages/fairscale/nn/pipe/pipe.py", line 224, in split_module
    partition.to(device)
  File "/home/shleifer/.conda/envs/nb/lib/python3.7/site-packages/torch/nn/modules/module.py", line 443, in to
    return self._apply(convert)
  File "/home/shleifer/.conda/envs/nb/lib/python3.7/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/home/shleifer/.conda/envs/nb/lib/python3.7/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/home/shleifer/.conda/envs/nb/lib/python3.7/site-packages/torch/nn/modules/module.py", line 225, in _apply
    param_applied = fn(param)
  File "/home/shleifer/.conda/envs/nb/lib/python3.7/site-packages/torch/nn/modules/module.py", line 441, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 15.75 GiB total capacity; 14.46 GiB already allocated; 102.38 MiB free; 14.46 GiB reserved in total by PyTorch)
```

**Comment by shruti-bh** [comment]
@sshleifer Sorry about that. This command actually needs two V100 32GB GPUs. The model checkpoint also needs a fix to ensure that it can work with 2 V100 32GB GPUs, instead of 4. I will update the README soon to reflect these changes.
```
    --pipeline-encoder-balance '[26]' \
    --pipeline-encoder-devices '[0]' \
    --pipeline-decoder-balance '[1,24,1]' \
    --pipeline-decoder-devices '[0,1,0]'
```
This indicates that the encoder resides on GPU 0 and the decoder resides on GPU 1 except for the shared embedding parameters which reside on GPU 0.

Let me know if you have more questions going forward.

**Comment by sshleifer** [comment]
Would it be possible to add a command with a chunking scheme works on 8 v100 GPUs? On Google Compute Platform, and also AWS I think, this is the nicest hardware you can rent as far as I know. I was thinking of adding the model to `huggingface/transformers`, but would be somewhat less motivated if it can't run on commodity hardware.

**Comment by shruti-bh** [comment]
It is possible to release a model that splits across 8 GPUs and I can do that if needed. But for inference with this 12B model, we only need two 32GB V100 GPUs. Do you mean you would like inference to work across 8 16GB V100 gpus?
Adding this to huggingface/transformers would be awesome. Let me know if you have any questions.

**Comment by sshleifer** [comment]
> Do you mean you would like inference to work across 8 16GB V100 gpus
Yes, or 4 16GB V100 GPUs if possible.

**Comment by shruti-bh** [comment]
I will try to get these models and commands in by end of this week or early next week!

**Comment by sshleifer** [comment]
Also, if you are planning on changing the `.pt` file, would be awesome if you could remove optimizer states. I think they are 70GB and `fairseq-generate` will work without them.

**Comment by mjpost** [comment]
I can confirm `fairseq-generate` works after you remove the optimizer states (reduced model is 48 GB).

**Comment by mjpost** [comment]
@shruti-bh can you confirm that the tokenizers were only used for evaluation, and not in preprocessing of the training data? So the SPM model was applied to raw text? We're doing some sanity checking of the model and want to make sure we have this important detail right.

**Comment by damyana79** [comment]
Can one run the model also on another GPU models, e.g. on 6 12GB Nvidia Titan X (without the --fp16 flag)? If yes, what would be the proper configuration for the --pipeline-encoder-balance and the pipeline-decoder-balance arguments? I don't quite get what each element in the list does so that I can adapt the configuration for my case.

 Or alternatively, can one run the model on the cpu with the --cpu flag? When trying to run it on the cpu, I still get an GPU OOM error.

**Comment by shruti-bh** [comment]
> @shruti-bh can you confirm that the tokenizers were only used for evaluation, and not in preprocessing of the training data? So the SPM model was applied to raw text? We're doing some sanity checking of the model and want to make sure we have this important detail right.

@mjpost I can confirm that the tokenizers were only used for computing BLEU by tokenizing the hypotheses and references. For preprocessing the training or validation data, we do not apply tokenizers (ref: https://github.com/pytorch/fairseq/tree/master/examples/m2m_100#introduction)

**Comment by shruti-bh** [comment]
@sshleifer - The README (https://github.com/pytorch/fairseq/tree/master/examples/m2m_100) now contains checkpoints that work with 4 16GB GPUs along with pipeline arguments needed to be used at generation time. Let me know if this works on your end. I also removed the optimizer states so that the size of the checkpoint is now ~48GB as @mjpost mentioned.

@damyana79 I added checkpoints that should work with 6 12GB GPUs with associated pipeline arguments to be used at generation time. We will look into adding CPU generation as well.

**Comment by Kyubyong** [comment]
Hi, is is also possible to translate using the Python interface like this: https://github.com/pytorch/fairseq/blob/master/examples/translation/README.md? If that's the case, please let us know a running example.

**Comment by shruti-bh** [comment]
@Kyubyong Yes, adding a torch hub interface is also something we plan to do soon within the next few weeks.

**Comment by sshleifer** [comment]
Thanks. I tried 4x16GB, but in `torch 1.5.1/fairscale 0.0.3/master`:

```bash
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/home/shleifer/fairseq/fairseq_cli/generate.py", line 392, in cli_main
    main(args)
  File "/home/shleifer/fairseq/fairseq_cli/generate.py", line 53, in main
    return _main(cfg, sys.stdout)
  File "/home/shleifer/fairseq/fairseq_cli/generate.py", line 106, in _main
    num_shards=cfg.checkpoint.checkpoint_shard_count,
  File "/home/shleifer/fairseq/fairseq/checkpoint_utils.py", line 263, in load_model_ensemble
    num_shards,
  File "/home/shleifer/fairseq/fairseq/checkpoint_utils.py", line 303, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, model_cfg=cfg.model)
TypeError: load_state_dict() got an unexpected keyword argument 'model_cfg'
```
Should I be on a different version of something?

**Comment by shruti-bh** [comment]
@sshleifer I cannot reproduce this on my end yet. Have you pulled the latest master of fairseq? Because when I added the model checkpoints, I also needed to make some code changes to ensure that everything worked correctly on top of the new dataclass configs that have been recently added to fairseq.

**Comment by sshleifer** [comment]
that worked! (on `6debe291`) Thanks!

**Comment by lauhaide** [comment]
Hi all, I'm trying to run the provided fairseq-generate with the *8 8GB GPUs* configurations. But still get OOM error on a machine with 8 10Gb GPUs. It just remains in the following line until crash:

INFO | fairseq_cli.generate | loading model(s) from /home/lperez/storage/pretrained/m2m/12b_last_chk_8_gpus.pt

Any hints on what I could look at, extra config, etc.?

Thanks!

**Comment by lauhaide** [comment]
Hi all, @shruti-bh, I'm trying to run the provided fairseq-generate with the 8 8GB GPUs configurations. But still get OOM error on a machine with 8 10Gb GPUs. It just remains in the following line until memory crash:

INFO | fairseq_cli.generate | loading model(s) from HOME/m2m/12b_last_chk_8_gpus.pt

Any hint on what I could look at, extra config, etc.?

Thanks!

**Comment by firdota** [comment]
> @sshleifer - The README (https://github.com/pytorch/fairseq/tree/master/examples/m2m_100) now contains checkpoints that work with 4 16GB GPUs along with pipeline arguments needed to be used at generation time. Let me know if this works on your end. I also removed the optimizer states so that the size of the checkpoint is now ~48GB as @mjpost mentioned.
> 
> @damyana79 I added checkpoints that should work with 6 12GB GPUs with associated pipeline arguments to be used at generation time. We will look into adding CPU generation as well.

@shruti-bh hello, can i fine-tune with the 48GB model, which you removed the optimizer states?

**Comment by Fikavec** [comment]
@shruti-bh hello, It is possible to release a largest M2M 12B model checkpoint for one A100 80Gb GPU? In your opinion, can 2_gpus checkpoints from this repository (12b_last_chk_2_gpus.pt, ...) be considered fully or partially compatible with two A100 40Gb GPUs (AMPHERE architecture+CUDA 11.1+pytorch 1.9.1), are there any unstable work, crashes, oom, fully incorrect translations, what is the speed up of inference (sentence translation) compared to v100? Can I use [MIG technology](https://developer.nvidia.com/blog/getting-the-most-out-of-the-a100-gpu-with-multi-instance-gpu/) to split 80Gb to 32Gb, 32Gb,16Gb GPU slices and use 2 32Gb GPU slices for M2M 12b_last_chk_2_gpus.pt, and what is best choice to inference m2m100: 1 A100 80Gb GPU or  2 A100 40Gb GPUs? Thanks!
