### ISSUE TITLE
Tried to access nonexistent attribute or method 'new' of type 'Tensor'

### ISSUE THREAD

**Issue by ismymajia** [pytorch/fairseq#2775]
When i convert to  torch.jit.script by below code:
model = load_model_ensemble_and_task([args.input_model])[0][0]
model.eval()
model_dict = model.decoder.dictionary
generator = SequenceGenerator([model], model_dict, beam_size=args.beam_size)
scripted_generator = torch.jit.script(generator)
scripted_generator.save(args.output_model)

error occor:
Tried to access nonexistent attribute or method 'new' of type 'Tensor'

The corresponding error location is ：
https://github.com/pytorch/fairseq/blob/a48f235636557b8d3bc4922a6fa90f3a0fa57955/fairseq/modules/adaptive_input.py#L70

@myleott @pietern

**Comment by myleott** [comment]
Looks like an issue with TorchScript, let's see what happens in the related issue here: https://github.com/pytorch/pytorch/issues/46695
