### ISSUE TITLE
I just tried to run exactly the same command on the latest version of fairseq and I don't see the issue. Could be fixed with #2761

### ISSUE THREAD

**Issue by davidepatrucco** [pytorch/fairseq#2776]
I just tried to run exactly the same command on the latest version of fairseq and I don't see the issue. Could be fixed with #2761 
If you still see the issue, can you please get exact version of your fairseq and re-open this ticket: 
git log -n 1

_Originally posted by @edunov in https://github.com/pytorch/fairseq/issues/2764#issuecomment-713920425_

**Comment by davidepatrucco** [comment]
Hi I keep on having this issue, as per my checks the issue arise when the fairseq installation is done by performing these steps for developing locally:

1)git clone https://github.com/pytorch/fairseq
2)cd fairseq
3)pip install --editable ./
in this case I do keep getting 
argparse.ArgumentError: argument -s/--source-lang: conflicting option string: --source-lang

If i install fairseq by:
1) pip install fairseq
it works 

as requested, here's the version obtained by > git log -n 1

commit 0f44e89c383f45ea455bddc3c44ec950b3df91f1 (HEAD -> master, origin/master, origin/HEAD)
Author: Myle Ott <myleott@fb.com>
Date:   Wed Oct 21 15:30:18 2020 -0700

    Fix Latent Depth args (#1365)
    
    Summary:
    Args should be registered in the Model rather than modules
    
    Pull Request resolved: https://github.com/fairinternal/fairseq-py/pull/1365
    
    Reviewed By: pipibjc
    
    Differential Revision: D24453007
    
    Pulled By: myleott
    
    fbshipit-source-id: d22b0d86a3c940456b394b005acab4bb6a3f5bed

<img width="639" alt="Error screenshot" src="https://user-images.githubusercontent.com/27724701/96847547-9c2d7d00-1453-11eb-9983-e4a9a8056f46.png">

**Comment by davidepatrucco** [comment]
BTW it does not happen if i clone the package_fairseq branch instead of the master branch.

In this case it works.

**Comment by myleott** [comment]
@alexeib has a fix, should be merged soon
