### ISSUE TITLE
Why replace the embed_tokens.weight in loading a transformer model ? 

### ISSUE THREAD

**Issue by KelleyYin** [pytorch/fairseq#278]
https://github.com/pytorch/fairseq/blob/5d00e8eea2644611f397d05c6c8f15083388b8b4/fairseq/models/transformer.py#L330
The question have discribed in title .

**Comment by KelleyYin** [comment]
Is there any impact without using the replacement ?

**Comment by myleott** [comment]
That’s not the weight, it’s a dummy buffer that’s used to indicate the type, i.e., whether the module is on CPU or GPU. Previously we used a 0-element tensor, but some versions of DistributedDataParallel fail to work with 0-dimensional tensors, so we’ve replaced it with a 1-element tensor instead. The value in the tensor is not used, just the type.
