### ISSUE TITLE
m2m for paraphrasing: sanity check

### ISSUE THREAD

**Issue by mjpost** [pytorch/fairseq#2785]
## ❓ Questions and Help

I'm trying to use M2M as a paraphraser for scoring (to see if this significantly better model improves [Prism](https://arxiv.org/abs/2004.14564). This is complicated a bit because `fairseq_cli.preprocess` uses `--source-lang` and `--target-lang` to save the source and reference file. I think we have a workaround, but it's not doing as well as we expected, and I am wondering if someone can sanity check our approach.

Assume you have English files `system.en` and `reference.en`. I want to get token-level probabilities for `P(ref | sys)`. First, I apply SPM to the raw text. Next, I binarize, using an irrelevant language code for the source:

```bash
PYTHONPATH=$FAIRSEQ python -m fairseq_cli.preprocess \
    --source-lang jabt --target-lang en \
    [snip]
```

Third, I translate, overwriting the source language code:

```bash
PYTHONPATH=$FAIRSEQ python -m fairseq_cli.generate \
    $datadir \
    --path $MODELDIR/12b_last_checkpoint_trimmed.pt \
    -s jabt -t en \
    --task translation_multi_simple_epoch \
    --decoder-langtok --encoder-langtok tgt \
    [snip]
````

From [the argparse documentation in tasks/multilingual_translation.py](https://github.com/pytorch/fairseq/blob/2409d5a36e074fe237a734fa2053867fe62b5e01/fairseq/tasks/multilingual_translation.py#L86-L91), this seems correct, but as I mentioned, it's not doing as well as we'd expected, so I thought I would check.

This works fine and provides scores, but they do not work as well as we anticipated. So I am wondering if you see any issues with what we're doing (for example, perhaps the language code flag isn't doing what we expect?)

**Comment by shruti-bh** [comment]
This is pretty cool and we would love to see if this works. (cc: @huihuifan)
I can't think of anything incorrect in your approach or commands at the moment. But I will need to give this more thought and get back to you if I think of something you could do differently for your use-case.
