### ISSUE TITLE
Inconsistent results of IWSLT data preprocessing between fairseq 0.6 and 0.9

### ISSUE THREAD

**Issue by haolibai** [pytorch/fairseq#2787]
#### What is your question?
I am running two versions of faiseq for neural machine translation, one is 0.6 and the other is 0.9, and find the data preprocessing results of IWSLT (for NMT) are inconsistent. I prepare the dataset following the guide in ./examples/translation/README.md, which includes: 

1) ./examples/translation/prepare-iwslt14.sh (for IWSLT-14)
2) data binarization.

But I find the results of two fairseq versions are different. For example:
1) IWSLT fairseq-0.6 produces 42MB binarized data, but 21MB for fairseq 0.9. 

IWSLT processed by fairseq 0.6: 42MB
![image](https://user-images.githubusercontent.com/24502378/97081018-2fbca480-1632-11eb-9a97-56f35cd2ec78.png)

IWSLT processed by fairseq 0.9: 21MB
![image](https://user-images.githubusercontent.com/24502378/97081042-54b11780-1632-11eb-8d5f-2c0d3922b5f9.png)

 - fairseq Version: fairseq 0.6 & fairseq 0.9
 - PyTorch Version 1.5.1
 - How you installed fairseq (`pip`, source): Yes. pip install . --editable
 - Python version: 3.7.4

**Comment by myleott** [comment]
This is expected. Newer versions of fairseq use a more efficient mmap data format that requires less disk space.
