### ISSUE TITLE
Story generation fusion model

### ISSUE THREAD

**Issue by aarontuor** [pytorch/fairseq#280]
It is not clear from the readme for the story generation example how to ensure the pre-trained language model and the story generation model use the same vocabulary mappings for  a fusion model. A more complete example for training a fusion model would be greatly appreciated.

**Comment by huihuifan** [comment]
In our work, we fuse two seq2seq models that are training on the same dataset, so the dictionaries are the same size. If you want to fuse a pretrained model with another model and the two are not going to use the same dataset, you can ensure dictionary match by binarizing the second model with preprocess.py --src-dict or --tgt-dict pointing to the right dictionary (from the first model). To train the fusion model, you use the same command provided in https://github.com/pytorch/fairseq/tree/master/examples/stories

except you add the pretrained flag and a path to the pretrained checkpoint. 

To fuse a pretrained language model with a seq2seq model, you will need to modify the code so it does not forward the pretrained encoder (as the LM is decoder only). Hope that helps.

**Comment by aarontuor** [comment]
Given the provided dataset, what are the commands you would use to
pre-train a sequence to sequence model?

Thanks,
Aaron

**Comment by huihuifan** [comment]
Q1- you will need to make code modifications if you want to fuse a pretrained language model with a training seq2seq model. In our paper, we fused two seq2seq models. If you want to do a pretrained LM, you can binarize the target side data with the LM dictionary, but you should build a new source side dictionary.
Q2- The command we use is here: https://github.com/pytorch/fairseq/tree/master/examples/stories

**Comment by aarontuor** [comment]
Huihui,

I understand now that you fuse two seq2seq models. What pre-trained seq2seq
model do you fuse with the story generation model? Is it as simple as
training the story gen model once, and then using this pre-trained model as
the pre-trained seq2seq model for the fusion model?

Thanks,
Aaron Tuor
Pacific Northwest National Laboratory

**Comment by huihuifan** [comment]
Yes, exactly! The commands in the readme should reproduce this.

**Comment by huihuifan** [comment]
Hope this issue has been resolved, closing for now.
