### ISSUE TITLE
wav2vec2.0 issue with decoding finetuned checkpoint

### ISSUE THREAD

**Issue by phantomcoder1996** [pytorch/fairseq#2803]
I finetune the wav2vec small model (wav2vec_small.pt) with some data and then when I try to decode the finetuned checkpoint I get this error
```
INFO:__main__:| decoding with criterion ctc
INFO:__main__:| loading model(s) from /root/decoding/model/checkpoint_best.pt
Traceback (most recent call last):
  File "examples/speech_recognition/infer.py", line 471, in <module>
    cli_main()
  File "examples/speech_recognition/infer.py", line 467, in cli_main
    main(args)
  File "examples/speech_recognition/infer.py", line 280, in main
    model_state=model_state,
  File "examples/speech_recognition/infer.py", line 217, in load_models_and_criterions
    model = task.build_model(cfg.model)
  File "/root/fairseq/fairseq/tasks/fairseq_task.py", line 548, in build_model
    model = models.build_model(args, self)
  File "/root/fairseq/fairseq/models/__init__.py", line 56, in build_model
    return ARCH_MODEL_REGISTRY[cfg.arch].build_model(cfg, task)
  File "/root/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 166, in build_model
    w2v_encoder = Wav2VecEncoder(args, task.target_dictionary)
  File "/root/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 329, in __init__
    args.w2v_path, arg_overrides
  File "/root/fairseq/fairseq/checkpoint_utils.py", line 227, in load_checkpoint_to_cpu
    with open(PathManager.get_local_path(path), "rb") as f:
No such file or directory: '/c/users/username/fairseq/models/wav2vec_small.pt
```
the path it is complaining about is the path that used to have wav2vec_small.pt during the finetuning. It is mainly the path I used for --w2v-path during finetuning
as if it is trying to read the weights from the wav2vec_small.pt without considering the trained weights

#### What have you tried?
1- Finetune wav2vec_small.pt using my data
2- run the decoding command with checkpoint_best.pt
```
python examples/speech_recognition/infer.py /root/decoding/testData/ --task audio_pretraining --nbest 1 --path /root/decoding/model/checkpoint_best.pt --gen-subset train --results-path /root/decoding/bestkenlm --w2l-decoder kenlm --lm-model /root/decoding/lm/lm.bin --lm-weight 1.48 --word-score 2.0 --sil-weight 0.0 --criterion ctc --labels ltr --max-tokens 4000000 --lexicon /root/decoding/lm/lexicon.lst --remove-bpe letter --beam 2500 --beam-size-token 25000 --beam-threshold 100
```

#### What's your environment?

 - fairseq Version ( master):
 - PyTorch Version (e.g., 1.6)
 - OS (e.g., Linux): linux (but using WSL1) 
 - How you installed fairseq : source
 - Build command you used (if compiling from source): pip install -e .
 - Python version: 3.6.9
 - CUDA/cuDNN version: None
 - GPU models and configuration: No GPU
 - Any other relevant information: 

-

**Comment by spygaurad** [comment]
If i am right then currently it uses  wav2vec_small.pt model to define encoder architecture it adds the decoder layer, then it copies the parameters from the checkpoint_best.pt model into the arch. You need both of them for inference.

**Comment by phantomcoder1996** [comment]
@spygaurad I thought so at first but what makes me think something is wrong is that the finetuned english models that are on the repo  donot produce that error

**Comment by spygaurad** [comment]
@phantomcoder1996  yeah i don't know why it is implemented that way. I finetuned on different language and i too require both .pt files ( the small.pt as well as finetuned.pt).

**Comment by mychiux413** [comment]
The root cause is: The dict structure from finetuned model is different to the official model like `wav2vec_small_960h`, at the beginning of inference, the fairseq framework automatically loads those training parameters according to your finetuned model's dict structure.

Here is the inspection and the temp solution below:
``` python
import torch
finetune_path = '/your/finetune/path.pt'
official_path = '/the/official/path/wav2vec_small_960h.pt'
fixed_model_path = '/path/to/fixed_model.pt'

finetune = torch.load(finetune_path, map_location=torch.device('cpu'))
official = torch.load(official_path, map_location=torch.device('cpu'))
print('finetune keys:', finetune.keys(), 'official keys', official.keys())

# the args in finetune is "None"
print('finetune args:', finetune['args'], 'official args: ', official['args'])


# To temporary solve it, we can imitate the args from official model
finetune.pop('cfg')
finetune['args'] = official['args']

torch.save(finetune, fixed_model_path)

```

**Comment by phantomcoder1996** [comment]
@mychiux413 thank you for the quick solution.

**Comment by mychiux413** [comment]
This temp solution might make the fixed model can NOT resume the training, because we drop those training configures to make it independent, so don't forget to backup one.
Fix the inference code should be a better idea.

**Comment by wahyubram82** [comment]
I open the similar issue in #2828, I alredy investigate..., it because the tourch cannot read the model `.pt` file.
until now is no answer why it's happen..., but i think, base on name of the function that run `load_checkpoint_to_cpu`, maybe... just maybe ... error because we train it in gpu meanwhile fairseq try to open with cpu...

the stranger things is.... the model that i use is not finish from creating the best pre-trainned mode.
and if i continue to train to make pre-trainned model, it's not a matter..., i train in google colab, so every 12 hrs i must set new virtual machine to train the dataset.

but, right now, I'm prepare to set the next step. so I try to test the finetuning step,  no matter i use wav2vec 2.0 base model or vq-wav2vec model, it's cannot load the model.

**Comment by alexeib** [comment]
this should have been fixed some time ago - the args saved in finetuned checkpoint get updated to not point at the pretrained wav2vec checkpoint. might not be the case for checkpoints finetuned in the past though
