### ISSUE TITLE
mismatch between BART-base and BART-large's embeddings' sizes

### ISSUE THREAD

**Issue by AutoTemp** [pytorch/fairseq#2804]
the size of bpe preprocess dict: 50260
(wget -N 'https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/dict.txt')

the size of bart-large dict: 50260
(wget -N 'http://dl.fbaipublicfiles.com/fairseq/models/bart.large.tar.gz')
load checkpoint successfully

the size of bart-base dict: 51196
(wget -N 'http://dl.fbaipublicfiles.com/fairseq/models/bart.base.tar.gz')
RuntimeError: Error(s) in loading state_dict for BARTModel:
        size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([51201, 768]) from
 checkpoint, the shape in current model is torch.Size([50264, 768]).
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([51201, 768]) from
 checkpoint, the shape in current model is torch.Size([50264, 768]).
        size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([51201, 768])
 from checkpoint, the shape in current model is torch.Size([50264, 768]).

since bart-base contains more makeupwords in the end of dict.txt, it's size of embedding of checkpoints (bart.base/model.pt) is larger than current model (build from gpt2_bpe/dict.txt)

**Comment by myleott** [comment]
In general the model archives are the source-of-truth for the dictionary to use. In this case the bart.base.tar.gz archive contains the correct dict.txt to use.

**Comment by qbetterk** [comment]
Hi, I am trying to loading the bart dict as well. The length of bart.base dict is 51196 and in the default setting fairseq only add 4 special token, which makes the size of embedding layer 51200. But in the pre-trained bart checkpoint, that size is 51201. So should I add an extra special token like "<mask>" while building the model or append a "maduptoken0939" to the end of the dict?
