### ISSUE TITLE
Can I get a translation score for a translation not generated by the model?

### ISSUE THREAD

**Issue by reachtarunhere** [pytorch/fairseq#2809]
#### What is your question?

Currently translating by using interactive.py prints scores for the hypothesis like H-0 and so on. I want to know if it is possible that given a source sentence and a hypothesis obtained from elsewhere can I use the NMT to assign a score to it. Please note I know there are measures like BLEU etc. which I am not keen on using.

If this is possible can I also modify the models to look into its activations?

Cheers,

Tarun

**Comment by lorelupo** [comment]
Same question here!
