### ISSUE TITLE
AdaFactor to save GPU memory?

### ISSUE THREAD

**Issue by AranKomat** [pytorch/fairseq#281]
Tensor2Tensor has [AdaFactor](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/adafactor.py) to drastically reduce the GPU memory usage. I believe it would be helpful for FairSeq to have this by default.

**Comment by myleott** [comment]
Good idea!

**Comment by luciodery** [comment]
Working on this

**Comment by luciodery** [comment]
See Adafactor here : 
https://github.com/pytorch/fairseq/blob/master/fairseq/optim/adafactor.py
