### ISSUE TITLE
get_normalized_probs_scriptable |  Not Implemented Error

### ISSUE THREAD

**Issue by spygaurad** [pytorch/fairseq#2810]
I am getting this error on all viterbi | fairseqlm decoding during inference.
The function is taking tuple input and checks for tensor later. How to solve this? 

![image](https://user-images.githubusercontent.com/16435245/97447767-02d10000-1958-11eb-81a8-a482455c6ca3.png)

![image](https://user-images.githubusercontent.com/16435245/97447532-c1405500-1957-11eb-970b-cc5e93c1c183.png)

**Comment by myleott** [comment]
Can you share a repro command?

Also cc @alexeib since this seems related to wav2vec

**Comment by spygaurad** [comment]
Sure. I also faced some other issues before reaching this stage. I somehow solved them. Should i meantion the changes i did?

python examples/speech_recognition/infer.py ~/semantro_aws/test_r/ --gen-subset train  --task audio_pretraining --nbest 1 --path ~/semantro/wav2vec_models/wav2vec_small_960h.pt  --results-path ~/semantro_aws/test_r/ --w2l-decoder fairseqlm --lm-model ~/Downloads/english_lm/lm_librispeech_word_transformer.pt  --lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000  --lexicon ~/Downloads/english_lm/librispeech_lexicon.lst.txt 

![image](https://user-images.githubusercontent.com/16435245/97464803-792a2e00-1969-11eb-85cd-4a21566a51c3.png)

**Comment by alexeib** [comment]
i am not sure what the problem is here. a fix for lexicon free decoder should be landing shortly - i've tested a similar setup to what you are doing (with translm) and it is working on my end. perhaps the lexicon free decoder fix will help.
for the dictionary, you need to put dict.ltr.txt into the same dir as your data (as per readme)

**Comment by spygaurad** [comment]
Thank you. The new update from yesterday solved this issue.
