### ISSUE TITLE
RoBERTa with next sentence prediction

### ISSUE THREAD

**Issue by yuanenming** [pytorch/fairseq#2816]
#### What is your question?
Recently, I am trying to apply pre-trained language models to a very different domain (i.e. protein sequence). I want to encode some domain knowledge that can be formulated as an NSP task. However, I did not find any implementations with NSP as part of the pre-train task. So I wonder if there is such implementation.

If the answer is no, Could you please give me some suggestions about how to modify the original RoBERTa framework.

thanks a lot!

**Comment by ddofer** [comment]
I'm doing the same problem! We will be releasing the model, code (including data loading) and paper soon :)
(Dan Ofer, M. Linial)

**Comment by yuanenming** [comment]
Hi, @ddofer 
Looking forward to your work
