### ISSUE TITLE
Using wav2vec2.0 finetuned model for streaming_asr

### ISSUE THREAD

**Issue by MrityunjoyS** [pytorch/fairseq#2820]
I'm sorry if I'm missing something or this feature is already there or if it's not possible. But is there any api with which if I've my own dataset finetuned by wa2vec2.0 model, it can be used for streamming_asr  ?

**Comment by srinath-zapr** [comment]
@MrityunjoyS  Did you solve this issue? I am also searching for a way to do this.

**Comment by magiczixiao** [comment]
@MrityunjoyS @srinath-zapr Do you have any solutions? I also want to use the streaming ASR. Thanks!
