### ISSUE TITLE
invalid choice: 'speech_recognition'

### ISSUE THREAD

**Issue by mironnn** [pytorch/fairseq#2822]
I'm trying to run a speech recognition example from [speech recognition example](https://github.com/pytorch/fairseq/tree/master/examples/speech_recognition).

But I'm getting an error:
infer.py: error: argument --task: invalid choice: 'speech_recognition'

**Comment by myleott** [comment]
Can you please reopen this issue following the template? In particular, we need to know what command you ran, your environment, etc.

**Comment by mironnn** [comment]
Open new bug, [link](https://github.com/pytorch/fairseq/issues/2827)
