### ISSUE TITLE
When did fairseq move the tensors into gpu?

### ISSUE THREAD

**Issue by CheungZeeCn** [pytorch/fairseq#2824]
I found that the device of samples' tensors in dataset's collate() is CPU, but in forward() of the model, I found the samples' tensors are on GPU;
When and how fairseq put them on GPU ?
Thank you !

**Comment by myleott** [comment]
It happens here: https://github.com/pytorch/fairseq/blob/a4356b1da2b19ebd2e1be5c12ff882026ea4d7d2/fairseq/trainer.py#L466
