### ISSUE TITLE
Can wav2vec2.0 be finetuned with unsupervised data ?

### ISSUE THREAD

**Issue by MrityunjoyS** [pytorch/fairseq#2840]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by alexeib** [comment]
if you mean, can you continue pre-training on a different dataset, then yes, you can - just be sure to reset the optimizer and lr-scheduler (with the appropriate --reset-* flags)

**Comment by MrityunjoyS** [comment]
Hi @alexeib , thanks for your quick response. Actually I'm trying to do unsuperviser training using my own audio files over any wav2vec2.0 base-model already provided. Can I do that ?

**Comment by alexeib** [comment]
yes, thats exactly what i mean

**Comment by MrityunjoyS** [comment]
So this is the command I'm running actually -->

```
python3 train.py /path/audio_file/manifest/save_dir/ \
--save-dir /path/audio_file/manifest/save_dir/checkpoints/ --fp16  --restore-file /path/audio_file/wav2vec_small.pt --task audio_pretraining --criterion wav2vec --arch wav2vec2 \
--reset-dataloader --reset-lr-scheduler --reset-meters --reset-optimizer \
--empty-cache-freq 3 --max-epoch 5 --best-checkpoint-metric wer --num-workers 6 \
--attention-dropout 0.0 --max-tokens 1280000 --seed 2337 --log-format json --log-interval 500 --ddp-backend no_c10d
```
Below errors I'm getting -->

> Traceback (most recent call last):
>   File "/path/fairseq/fairseq/trainer.py", line 301, in load_checkpoint
>     state["model"], strict=True, model_cfg=self.cfg.model
>   File "/path/fairseq/fairseq/models/fairseq_model.py", line 114, in load_state_dict
>     return super().load_state_dict(new_state_dict, strict)
>   File "/path/tmp/deepspeech-train-venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for Wav2Vec2Model:
> 	Unexpected key(s) in state_dict: "quantizer.vars", "quantizer.weight_proj.weight", "quantizer.weight_proj.bias", "feature_extractor.conv_layers.6.0.weight". 
> 	size mismatch for feature_extractor.conv_layers.1.0.weight: copying a param with shape torch.Size([512, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 8]).
> 	size mismatch for feature_extractor.conv_layers.2.0.weight: copying a param with shape torch.Size([512, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 4]).
> 	size mismatch for feature_extractor.conv_layers.3.0.weight: copying a param with shape torch.Size([512, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 4]).
> 	size mismatch for feature_extractor.conv_layers.4.0.weight: copying a param with shape torch.Size([512, 512, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 4]).
> 	size mismatch for feature_extractor.conv_layers.5.0.weight: copying a param with shape torch.Size([512, 512, 2]) from checkpoint, the shape in current model is torch.Size([512, 512, 1]).
> 	size mismatch for project_q.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([768, 512]).
> 	size mismatch for project_q.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([768]).
> 	size mismatch for final_proj.weight: copying a param with shape torch.Size([256, 768]) from checkpoint, the shape in current model is torch.Size([768, 768]).
> 	size mismatch for final_proj.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([768]).
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "train.py", line 14, in <module>
>     cli_main()
>   File "/path/fairseq/fairseq_cli/train.py", line 352, in cli_main
>     distributed_utils.call_main(cfg, main)
>   File "/path/fairseq/fairseq/distributed_utils.py", line 315, in call_main
>     main(cfg, **kwargs)
>   File "/path/fairseq/fairseq_cli/train.py", line 115, in main
>     disable_iterator_cache=task.has_sharded_data("train"),
>   File "/path/fairseq/fairseq/checkpoint_utils.py", line 196, in load_checkpoint
>     reset_meters=reset_meters,
>   File "/path/fairseq/fairseq/trainer.py", line 310, in load_checkpoint
>     "please ensure that the architectures match.".format(filename)
> Exception: Cannot load model parameters from checkpoint /path/audio_file/wav2vec_small.pt; please ensure that the architectures match.

Can you please look into it ?

**Comment by alexeib** [comment]
you need to specify all the params from the original pre-training run (you can find it in examples) so that fairseq creates the correct model into which it will then load the weights from your checkpoint

**Comment by MrityunjoyS** [comment]
HI @alexeib , thanks for the points, I'm able to first train the model with unsupervised data over wav2vec_small base model and then finetune it with 10-12min of supervised data using my own lexicon file. 
But after that while I'm trying to infer using the model I'm facing error, can you please have a look ?!

Code I'm using -->
```
python3 examples/speech_recognition/infer.py /path/audio_file/manifest/save_dir/ --task audio_pretraining --nbest 1 \
    --path /path/audio_file/manifest/save_dir/checkpoints1/checkpoint_best.pt --gen-subset valid --results-path /path/audio_file/manifest/save_dir/ \
    --w2l-decoder fairseqlm --lexicon /path/audio_file/lexicon.lst --lm-model /path/audio_file/lm_librispeech_word_transformer.pt \
    --lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --max-tokens 4000000 --labels ltr
```

Error I'm getting -->

> INFO:__main__:| loading model(s) from /path/audio_file/manifest/save_dir/checkpoints1/checkpoint_best.pt
> Traceback (most recent call last):
>   File "examples/speech_recognition/infer.py", line 464, in <module>
>     cli_main()
>   File "examples/speech_recognition/infer.py", line 460, in cli_main
>     main(args)
>   File "examples/speech_recognition/infer.py", line 285, in main
>     model_state=model_state,
>   File "examples/speech_recognition/infer.py", line 209, in load_models_and_criterions
>     model = task.build_model(args)
>   File "/path/fairseq/fairseq/tasks/fairseq_task.py", line 548, in build_model
>     model = models.build_model(args, self)
>   File "/path/fairseq/fairseq/models/__init__.py", line 56, in build_model
>     return ARCH_MODEL_REGISTRY[cfg.arch].build_model(cfg, task)
> AttributeError: 'NoneType' object has no attribute 'arch'
>
