### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by LoekvanKooten** [pytorch/fairseq#2842]
## 🐛 Bug

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### To Reproduce

Do any training from ModernMT on a 3090 with CUDA 11.1.

### Environment

 - fairseq 0.7.1
 - PyTorch Version 1.7.0
 - OS (e.g., Linux): Ubuntu 18.02
 - How you installed fairseq: pip3 install
 - Python version: 3.6.9
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: eVGA 3090 RTX

**Comment by myleott** [comment]
Sorry I don't have much context on ModernMT. Based on your Issue description it seems to be based on fairseq 0.7.1, which is over a year old. Can you please provide more detailed repro instructions, preferably using fairseq directly?

**Comment by LoekvanKooten** [comment]
You're right, it's a very old version. I will take this up with ModernMT first, as they say they're going to upgrade this. Also, ModernMT doesn't even support the 30 series yet anyway, even if we could get this to work. Now I need to convince them why it's a really bad idea to stick to 20 alone. https://github.com/modernmt/modernmt/issues/574

**Comment by turian** [comment]
This is possibly related to https://github.com/pytorch/fairseq/issues/2789
