### ISSUE TITLE
More integration tests for hydra are needed

### ISSUE THREAD

**Issue by erip** [pytorch/fairseq#2843]
### Motivation

The migration to hydra is nice, but has caused a huge number of bugs and regressions. Coupled with the lack of versioning, this makes the surface area for deep bugs quite large.

### Pitch

There need to be integration and regression tests in place to ensure that user-facing behavior doesn't change between commits. This will become more important as fairseq migrates to semantic versioning for releases - if breaking changes happen within a major version, this will make it impossible to use the software in a production environment.

### Alternatives

Status quo

**Comment by alexeib** [comment]
i think thats a great idea. we made sure that all the tests we have (both public and also a large amount of internal integration tests) pass before we push things, but unfortunately some issues remain. if there are certain things that you find break most often plz suggest them, or (if possible) contribute a pr!

**Comment by erip** [comment]
I try my best to submit PRs when I can. Windows tend to break often which is why I've submitted #2726 which is currently awaiting review and I've submitted other PRs in the past which have gone without review or aged off - I'm not sure what the possibility of opening some amount of ownership to the community would look like, but that might make it possible for more engagement from open-source contributors! 😄
