### ISSUE TITLE
Does wav2vec2.0 support character LM during decoding?

### ISSUE THREAD

**Issue by spygaurad** [pytorch/fairseq#2844]
Does wav2vec support character LM during decoding? If so, how can i train char LM using fariseq?

**Comment by alexeib** [comment]
yes if you dont specify a lexicon and build a version of wav2letter that has "LexiconFreeDecoder" compiled into it (or build a bridge to some other decoder like kaldi)

take a look at https://github.com/pytorch/fairseq/tree/master/examples/language_model for examples on how to train language models
