### ISSUE TITLE
Which kind of BLEU does fairseq-generate return by defualt?

### ISSUE THREAD

**Issue by haorannlp** [pytorch/fairseq#2850]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
Which kind of BLEU does fairseq-generate return by defualt? 
According to the generation command provided in ``https://github.com/pytorch/fairseq/tree/master/examples/translation``, there is no detokenization step. So does the BLEU score returned by those commands correspond to ``case-insensitive 4-gram tokenized BLEU``? What about the validation BLEU score returned when we finish one-epoch training? Thank you.
#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by haorannlp** [comment]
Another question, when we generate multiple hypotheses  ``--nbest 5``, what does the BLEU score mean? Is it the average of different hypotheses? Thanks.

**Comment by alexeib** [comment]
it does in fact detokenize if you pass the proper arguments to --tokenizer/--post-process/--remove-bpe/--sacrebleu. if you dont specify anything you get tokenized bleu. there are an argument like that for training as well, see this whole section in translation task:

```
        # options for reporting BLEU during validation
        parser.add_argument('--eval-bleu', action='store_true',
                            help='evaluation with BLEU scores')
        parser.add_argument('--eval-bleu-detok', type=str, default="space",
                            help='detokenize before computing BLEU (e.g., "moses"); '
                                 'required if using --eval-bleu; use "space" to '
                                 'disable detokenization; see fairseq.data.encoders '
                                 'for other options')
        parser.add_argument('--eval-bleu-detok-args', type=str, metavar='JSON',
                            help='args for building the tokenizer, if needed')
        parser.add_argument('--eval-tokenized-bleu', action='store_true', default=False,
                            help='compute tokenized BLEU instead of sacrebleu')
        parser.add_argument('--eval-bleu-remove-bpe', nargs='?', const='@@ ', default=None,
                            help='remove BPE before computing BLEU')
        parser.add_argument('--eval-bleu-args', type=str, metavar='JSON',
                            help='generation args for BLUE scoring, '
                                 'e.g., \'{"beam": 4, "lenpen": 0.6}\'')
        parser.add_argument('--eval-bleu-print-samples', action='store_true',
                            help='print sample generations during validation')
```
