### ISSUE TITLE
Getting Attribute error while inference in wav2vec2.0 model.

### ISSUE THREAD

**Issue by MrityunjoyS** [pytorch/fairseq#2851]
I've finetuned the wav2vece2.0 model using my own dataset. But while I'm trying to infer, I'm getting error.
Code I'm using -->
```
python3 examples/speech_recognition/infer.py /path/audio_file/manifest/save_dir/ --task audio_pretraining --nbest 1 \
    --path /path/audio_file/manifest/save_dir/checkpoints1/checkpoint_best.pt --gen-subset valid --results-path /path/audio_file/manifest/save_dir/ \
    --w2l-decoder fairseqlm --lexicon /path/audio_file/lexicon.lst --lm-model /path/audio_file/lm_librispeech_word_transformer.pt \
    --lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --max-tokens 4000000 --labels ltr
```

Error I'm getting -->

> INFO:__main__:| loading model(s) from /path/audio_file/manifest/save_dir/checkpoints1/checkpoint_best.pt
> Traceback (most recent call last):
>   File "examples/speech_recognition/infer.py", line 464, in <module>
>     cli_main()
>   File "examples/speech_recognition/infer.py", line 460, in cli_main
>     main(args)
>   File "examples/speech_recognition/infer.py", line 285, in main
>     model_state=model_state,
>   File "examples/speech_recognition/infer.py", line 209, in load_models_and_criterions
>     model = task.build_model(args)
>   File "/path/fairseq/fairseq/tasks/fairseq_task.py", line 548, in build_model
>     model = models.build_model(args, self)
>   File "/path/fairseq/fairseq/models/__init__.py", line 56, in build_model
>     return ARCH_MODEL_REGISTRY[cfg.arch].build_model(cfg, task)
> AttributeError: 'NoneType' object has no attribute 'arch'
> 

Can you please suggest like what I'm doing wrong? Thanks in advance

**Comment by alexeib** [comment]
can you share your checkpoint somewhere?

**Comment by MrityunjoyS** [comment]
[checkpoint](https://drive.google.com/file/d/1hXGSGtcGJE-GJ-RXkGrj86um9yRV-wi-/view?usp=sharing)
I've uploaded it to google drive, can you access the link

**Comment by alexeib** [comment]
please reopen if this is still an issue

**Comment by MrityunjoyS** [comment]
Still facing the same issue
