### ISSUE TITLE
Why does FairseqLM decoder predict only zero tokens?

### ISSUE THREAD

**Issue by lukerm** [pytorch/fairseq#2852]
#### What is your question?

I am having difficulty getting the `W2lFairseqLMDecoder` to give any reasonable predictions - in my case it only produces zero tokens. I am sure that I have the Wav2Vec 2.0 model properly working because I can get reasonable character emissions (see below). Also, I am able to get results from other types of decoder (i.e. `W2lViterbiDecoder` and `W2lKenLMDecoder`). 

My question is: why I am getting only zeros? Are there any likely misconfiguration traps that I've fallen into? 

I have scripted the code below where the print statements (particularly near the bottom) are useful for clarifying my problem and approach. In particular, you will see that I cannot convert the following emission (taking argmax probability to get most likely letter) into anything sensible with Fairseq LM:

`SO|ITT|SEEEMMSS||TTOO||MMEE||||`

The corresponding hypothesis after decoding with Fairseq LM is:

```python
[{'tokens': tensor([], dtype=torch.int64), 
  'score': -132.32041063059046, 
  'words': []}]
```

I have managed to get the KenLM version working and the decoding from that in this example is:

```python
[{'tokens': tensor([12,  8, 10,  6,  4, 12,  5,  5, 17, 12,  6,  8,  4, 17,  5,  7,  4]),
  'score': -109.02299984753859,
  'words': ['SOIT', 'SEEMSTO', 'MEA']}]
```

I would still very much like to get the Fairseq LM working. Any help on this would be appreciated. 

#### Code

```python
import os
import sys

import numpy as np
import torch
from fairseq import options

sys.path.insert(0, os.path.expanduser('~/fairseq'))
from examples.speech_recognition.infer import make_parser, load_models_and_criterions
from examples.speech_recognition.infer import get_dataset_itr

use_cuda = torch.cuda.is_available()
path = os.path.expanduser('~/fairseq/models/wav2vec2/wav2vec_small_100h.pt')
data_path = os.path.expanduser('~/fairseq/data')

# Mimics using fairseq/examples/speech_recognition/infer.py but from interactive terminal
parser = make_parser()
input_args = [
    'examples/speech_recognition/infer.py',
    data_path,  # data_path
    '--task', 'audio_pretraining',
    '--nbest', '1',
    '--path', path,
    '--gen-subset', 'train',  # Corresponds to train.tsv (listing audio files)
    '--w2l-decoder', 'fairseqlm',
    # downloaded: https://github.com/facebookresearch/wav2letter/blob/6c8ceaa7b0571b7ca3970f59a27c996b7531ec77/recipes/models/sota/2019/README.md#pre-trained-language-models
    # (row: Transformer, col: LM Fairseq)
    '--lm-model', os.path.expanduser('~/fairseq/models/fairseqlm/lm_librispeech_word_transformer.pt'),
    # downloaded from: https://dl.fbaipublicfiles.com/fairseq/wav2vec/librispeech_lexicon.lst
    '--lexicon', os.path.expanduser('~/fairseq/models/fairseqlm/librispeech_lexicon.lst'),
    '--beam', '1000',
    '--beam-size-token', '32',
    '--lm-weight', '2',
    '--word-score', '-1',
    '--sil-weight', '0',
    '--criterion', 'ctc',
    #'--labels', 'ltr',
    '--max-tokens', '4000000',
    #'--post-process', 'letter',
    '--batch-size', '1',
]
args = options.parse_args_and_arch(parser, input_args=input_args[1:])

# Loading: models and dataset
task = None
model_state = None
models, criterions, task = load_models_and_criterions(args.path, data_path=args.data, arg_overrides=eval(args.model_overrides))
# Hack to tell the task that there are no labels
task.args.labels = None
task.load_dataset(args.gen_subset)

# create decoder
from examples.speech_recognition.w2l_decoder import W2lFairseqLMDecoder
generator = W2lFairseqLMDecoder(args, task.target_dictionary)

# Data generator: get last sample
# Work with audio file: Librispeech/test-clean/1580/141083/1580-141083-0017.flac
# Transcription: "SO IT SEEMS TO ME"
itr = get_dataset_itr(args, task, models)
for sample in itr: pass
print(sample['net_input']['source'].size())  # torch.Size([1, 36480])

# Predict with wav2vec 2.0
sample['net_input']['padding_mask'] = None  # Otherwise TypeError: forward() missing 1 required positional argument: 'padding_mask'
encoder_out = models[0](**sample["net_input"])
emissions = models[0].get_normalized_probs(encoder_out, log_probs=True)  # prob distribution over final dimension
emissions = emissions.transpose(0, 1).cpu().detach()
print(emissions.size())  # torch.Size([1, 113, 32])

# Show that emissions are reasonable
char_seq_str = ''.join([task.target_dictionary[i] for i in np.apply_along_axis(np.argmax, 1, emissions[0]) if i > 0])
print(char_seq_str)  # "SSOO|IT||SSEEEMMMSS||TTOO||MMEEE||||"

# Question: why is this giving empty hypotheses?
hypos = task.inference_step(generator, models, sample, prefix_tokens=None)
print(hypos)  # [[{'tokens': tensor([], dtype=torch.int64), 'score': -132.32041063059046, 'words': []}]]

# debug decoder: rejigged from fairseq/examples/speech_recognition/w2l_decoder.py W2lFairseqLMDecoder:decode()
B, T, N = emissions.size()
b = 0
emissions_ptr = emissions.data_ptr() + 4 * b * emissions.stride(0)
best_result = generator.decoder.decode(emissions_ptr, T, N)[0]
# Why are all these tokens zero?
print(len(best_result.tokens))  # 115
print(any(best_result.tokens))  # False


```

#### What have you tried?

See code section above.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 1.0.0a0+de85969 (editable)
 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): `pip install -e fairseq/`
 - Python version: 3.6.9
 - CUDA/cuDNN version: N/A (CPU only)
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

**Comment by alexeib** [comment]
to use fairseqlm you need a dictionary for that lm to be located in the data dir. also you need to uppercase that dict because for wav2vec we use uppercase labels, whereas wav2letter used lowercase labels. (or you can lowercase letter dict + lexicon if you prefer)

**Comment by lukerm** [comment]
@alexeib Thanks for your suggestion - it worked. Amusingly, I had this situation:

```bash
~/fairseq/models/fairseqlm$ head -n3 dict*
==> dict.txt <==
the 49059384
and 26362574
of 24795903

==> dict_upper.txt <==
THE 49059384
AND 26362574
OF 24795903
```

So no error was thrown because it found `dict.txt` but it was in the wrong casing. I've now switched it round:

```bash
~/fairseq/models/fairseqlm$ head -n3 dict*
==> dict_lower.txt <==
the 49059384
and 26362574
of 24795903

==> dict.txt <==
THE 49059384
AND 26362574
OF 24795903
```

This has resolved my issue as the output from FairseqLM is now much better:
```python
[{'score': -79.35499740937848,
  'tokens': tensor([10,  6,  4, 12,  5,  5, 17, 12,  4,  6,  8,  4, 17,  5,  4]),
  'words': ['IT', 'SEEMS', 'TO', 'ME']}]
```

From my side you could close the issue, but here are a couple of related suggestion that may be worth considering?:
1. In the [wiki page](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec#evaluating-a-ctc-model), you refer to the letter-dictionary file [`dict.ltr.txt`](https://dl.fbaipublicfiles.com/fairseq/wav2vec/dict.ltr.txt) - is this the correct one? I'm not sure I ever used it (but then again I'm not doing the full CTC evaluation here).
2. The fact that Fairseq LM silently fails (as in my case) may not be ideal - perhaps there's an `assert` that could help catch this?

Thanks again.

**Comment by alexeib** [comment]
Great, glad that it worked!

1. dict.ltr.txt is used for actually outputting units (e.g. if you "viterbi" mode), whereas dict.txt is used for fairseq word level language model dictionary
2. thats a good idea, i will try to add it when i get around modifying those files!
