### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [pytorch/fairseq#2856]
The markup version of the readme that is displayed for the main page in this repo contains the following links:
Status code [404:NotFound] - Link: https://github.com/pytorch/fairseq/blob/master/examples/language_model/conv_lm/README.md
Status code [404:NotFound] - Link: https://github.com/pytorch/fairseq/blob/master/examples/language_model/transformer_lm/README.md
(The link in the readme’s raw markdown may appear in a different format to the link above)

Theses bad links were found by a tool I very recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback.

**Comment by myleott** [comment]
Thanks! I'll fix these shortly (and stared your repo 😄 )

**Comment by myleott** [comment]
Merged this with b4d57c6d49682094efe22fbe2c03fa2c4973869f
