### ISSUE TITLE
Using with CPU freezes the program

### ISSUE THREAD

**Issue by ihavetoomanyquestions** [pytorch/fairseq#286]
I am trying to generate some stories using pretrained model (and test dataset). I provided --cpu flag since I dont have GPU (using this script on my MAC OS).

python generate.py stories_test --cpu  --path models/fusion_checkpoint.pt --batch-size 32 --beam 1 --sampling --sampling-topk 10 --sampling-temperature 0.8 --nbest 1 --model-overrides "{'pretrained_checkpoint':'models/pretrained_checkpoint.pt'}"

However, the script just hangs there for the last 1 hour:

| loading pretrained model
  0%|                                                                                                                                                                               | 0/474 [00:00<?, ?it/s]

Does the script takes that long to generate even 1 story, or do you think using CPU somehow freezes the program? Is there any way I can debug this?

**Comment by ihavetoomanyquestions** [comment]
it turns out it takes about 2 hours to generate 1 story on a cpu. so i guess it's not a bug after all. closing the issue.

**Comment by huihuifan** [comment]
I suggest limiting the length of the story you are trying to generate to
improve speed, but unfortunately decoding on cpu is going to be slow.
