### ISSUE TITLE
how long to run speech_recognition/datasets/prepare-librispeech.sh

### ISSUE THREAD

**Issue by xwuShirley** [pytorch/fairseq#2861]
Dear speech team,

I am trying to prepare the data for speech recognition. I can successfully run the code
https://github.com/pytorch/fairseq/blob/master/examples/speech_recognition/datasets/prepare-librispeech.sh#L71

I have reduced the data into the following (remove train-clean-360 train-other-500)
dev-clean test-clean dev-other test-other train-clean-100

It has been running for almost three days (see following)
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND  
 267860 XXXX    20   0 1709316 645168   5276 R 100.0   2.0   1142:20 spm_train  

I am not sure how long this code will finish. It would be great if you have any experience and give some hint on the acceleration. 

Thank you very much
Best,
Shirley

**Comment by kahne** [comment]
Hi @xwuShirley , LibriSpeech has ~200k utterances and sentencepiece training should be pretty quick (say within 10min). Can you share the full script (your modified version)?

**Comment by xwuShirley** [comment]
Thanks! see the attached line 35
[prepare-librispeech.log](https://github.com/pytorch/fairseq/files/5504372/prepare-librispeech.log)

**Comment by xwuShirley** [comment]
trainer_interface.cc(320) LOG(INFO) SentenceIterator is not specified. Using MultiFileSentenceIterator.
trainer_interface.cc(175) LOG(INFO) Loading corpus: data/lang_char/input.txt
trainer_interface.cc(376) LOG(INFO) Loaded all 171234 sentences
trainer_interface.cc(391) LOG(INFO) Adding meta_piece: <pad>
trainer_interface.cc(391) LOG(INFO) Adding meta_piece: </s>
trainer_interface.cc(391) LOG(INFO) Adding meta_piece: <unk>
trainer_interface.cc(396) LOG(INFO) Normalizing sentences...
trainer_interface.cc(457) LOG(INFO) all chars count=31790142
trainer_interface.cc(478) LOG(INFO) Alphabet size=28
trainer_interface.cc(479) LOG(INFO) Final character coverage=1
trainer_interface.cc(511) LOG(INFO) Done! preprocessed 171234 sentences.
unigram_model_trainer.cc(138) LOG(INFO) Making suffix array...
unigram_model_trainer.cc(142) LOG(INFO) Extracting frequent sub strings...

**Comment by xwuShirley** [comment]
It stuck like above

**Comment by xwuShirley** [comment]
I found the error. It's the path  https://github.com/pytorch/fairseq/blob/master/examples/speech_recognition/datasets/prepare-librispeech.sh#L21

**Comment by kahne** [comment]
@xwuShirley Good catch, thanks! We will update the script. Not sure how it's related to SentencePiece though.

**Comment by xiaoxuegao499** [comment]
> I found the error. It's the path https://github.com/pytorch/fairseq/blob/master/examples/speech_recognition/datasets/prepare-librispeech.sh#L21

Hi, I faced the same problem. How'd you figure it out? Thanks~
