### ISSUE TITLE
Replace `os.path` with `pathlib.Path`

### ISSUE THREAD

**Issue by erip** [pytorch/fairseq#2864]
### Motivation

`os.path` gives cross-platform filesystem operations, but it's a cumbersome API because the primitive is a string. Since Python 3.4 `pathlib` has been available in the Python standard library, which makes some common filesystem operations available with better ergonomics.

### Pitch

Replace use of `str` paths with `pathlib.Path` and migrate away from `os.path` APIs to `pathlib` APIs. This can make the code much clearer in some cases.

### Alternatives

Leave the code as is.

**Comment by erip** [comment]
If this gets an OK from a maintainer, I'm happy to start working on this.

**Comment by alexeib** [comment]
@myleott ?

**Comment by myleott** [comment]
Sounds good to me!

> This can make the code much clearer in some cases.

What's an example?

**Comment by erip** [comment]
One example is [this](https://github.com/pytorch/fairseq/blob/3b27ed7996b0315f471c795cf9b7dfcc18467cbe/fairseq/hub_utils.py#L55-L56). When I first read this when trying to debug #2847, I realized the semantics are ambiguous: this could refer to hidden files (i.e., `".model/"`) or relative paths specified a certain way (i.e, `"./model/"`). By adding a path object, we have a lot of flexibility by way of expressive semantics. 

I'm happy to spin off a draft PR to see what the benefits actually look like. 😄

**Comment by erip** [comment]
As an aside: this might also be a good opportunity to gradually add type hints to the code in hopes of catching more bugs with a linter and to generate better API docs.
