### ISSUE TITLE
NAT WMT14_en_de distill dataset

### ISSUE THREAD

**Issue by SeunghyunSEO** [pytorch/fairseq#2872]
Hi guys

first of all, i rly appreciate for you to share this codes

however, when im trying to train NAT model (NACRF) using this [script](https://github.com/pytorch/fairseq/blob/b0fb74f143ec17e01da9cf18a852aebc559ccaef/examples/nonautoregressive_translation/scripts.md) and [distill dataset](https://github.com/pytorch/fairseq/tree/b0fb74f143ec17e01da9cf18a852aebc559ccaef/examples/nonautoregressive_translation) that you guys attach

i cant find binarized dataset, and cant understand how to binarize the wmt14-en-de dataset following [this ReadMe](https://github.com/pytorch/fairseq/tree/b152183d745d025514a4d4d03a3671cd85acbdcc/examples/translation#prepare-wmt14en2desh)

the files ive got from your preprocessed distillation dataset link is as follows
<pre>
<code>
dev.de.ori		test.de.ori		train.en-de.de		valid.en-de.de
dev.en.ori		test.en-de.de		train.en-de.en		valid.en-de.en
dict.de.txt		test.en-de.en		valid-repeat.en-de.de	valid.en-de.ori
dict.en.txt		test.en.ori		valid-repeat.en-de.en	wmt14.bpe.codes
</code>
</pre>

and everytime i run below script

<pre>
<code>
fairseq-train \
    data-bin/wmt14_en_de_distill \
    --save-dir checkpoints \
    --ddp-backend=no_c10d \
    --task translation_lev \
    --criterion nat_loss \
    --arch nacrf_transformer \
    --noise full_mask \
    --share-all-embeddings \
    --optimizer adam --adam-betas '(0.9,0.98)' \
    --lr 0.0005 --lr-scheduler inverse_sqrt \
    --min-lr '1e-09' --warmup-updates 10000 \
    --warmup-init-lr '1e-07' --label-smoothing 0.1 \
    --dropout 0.3 --weight-decay 0.01 \
    --decoder-learned-pos \
    --encoder-learned-pos \
    --pred-length-offset \
    --length-loss-factor 0.1 \
    --word-ins-loss-factor 0.5 \
    --crf-lowrank-approx 32 \
    --crf-beam-approx 64 \
    --apply-bert-init \
    --log-format 'simple' --log-interval 100 \
    --fixed-validation-seed 7 \
    --max-tokens 8000 \
    --save-interval-updates 10000 \
    --max-update 300000
</code>
</pre>

i got the following error message

<pre>
<code>
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    cli_main()
  File "fairseq/fairseq_cli/train.py", line 349, in cli_main
    distributed_utils.call_main(cfg, main)
  File "fairseq/fairseq/distributed_utils.py", line 317, in call_main
    main(cfg, **kwargs)
  File "fairseq/fairseq_cli/train.py", line 68, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=1)
  File "fairseq/fairseq/tasks/translation_lev.py", line 73, in load_dataset
    prepend_bos=True,
  File "fairseq/fairseq/tasks/translation.py", line 86, in load_langpair_dataset
    "Dataset not found: {} ({})".format(split, data_path)
FileNotFoundError: Dataset not found: valid (data-bin/wmt14_en_de_distill)
</code>
</pre>

By the way, its my first time to use WMT dataset and implement NMT  
sry for the long question, but i would very much appreciate if you anyone reply to me
thx :)

**Comment by SeunghyunSEO** [comment]
+ p.s)  i would very much appreciate if anybody share NAT implementation code. tq !

**Comment by hlzhang109** [comment]
Same. Does anyone solve it？

**Comment by weikang-wang** [comment]
Same. Does anyone solve it？
