### ISSUE TITLE
Can I increase the maximum input size using pre-trained M2M-100?

### ISSUE THREAD

**Issue by haruya-umemoto** [pytorch/fairseq#2875]
Hi, I try to use M2M-100 to generate the translation.
When I input my data to the pre-trained model,  an input size error has occurred.

`Exception: Size of sample #154922 is invalid (=(262, 3)) since max_positions=(256, 256), skip this example with --skip-invalid-size-inputs-valid-test`

I tried some options but these have not worked.
```
fairseq-generate \
        data_bin \
        --batch-size 32 \
        --num-workers 2 \
        --path 12b_last_chk_2_gpus.pt \
        --fixed-dictionary model_dict.128k.txt \
        -s ${source_lang} -t ${target_lang} \
        --remove-bpe 'sentencepiece' \
        --beam 5 \
        --task translation_multi_simple_epoch \
        --lang-pairs language_pairs.txt \
        --decoder-langtok --encoder-langtok src \
        --gen-subset test \
        --fp16 \
        --dataset-impl mmap \
        --distributed-world-size 1 --distributed-no-spawn \
        --max-source-positions 1024 \
        --max-target-positions 1024 \
        --max-tokens 1024 \
        --max-tokens-valid 1024 \
        --pipeline-model-parallel \
        --pipeline-chunks 1 \
        --pipeline-encoder-balance '[26]' \
        --pipeline-encoder-devices '[0]' \
        --pipeline-decoder-balance '[3,22,1]' \
        --pipeline-decoder-devices '[0,1,0]'
```
I'm wondering whether we can increase the maximum input size using the pre-trained model.

**Comment by SaricVr** [comment]
Hello, I'm interested in this as well. In particular, I'd like to be able to translate pieces of texts longer than 256 tokens. I understand that the quality of the results could be negatively impacted since training was done with a limit of 256. It would be interesting to investigate the behavior anyway.

Thanks
