### ISSUE TITLE
Does every process loads a copy of data?

### ISSUE THREAD

**Issue by alannlee** [pytorch/fairseq#288]
This issue is to confirm whether each process loads a copy of data into the memory in `multiprocessing_train`, which may consume too much memory when the dataset is huge , or there are some tricks I missed. 

Thanks a lot!

**Comment by edunov** [comment]
Thats true, although we have a working prototype right now that eliminates this problem. It should be available for everyone soon

**Comment by alannlee** [comment]
Ok, I got it. Thanks for your help!
