### ISSUE TITLE
should I rewrite the model with dataclass if I want to use hydra_train

### ISSUE THREAD

**Issue by zhengxxn** [pytorch/fairseq#2883]
I noticed that only language_modeling.py in tasks and transformer_lm.py in models  are implemented with the Dataclass, but if I want to  use hydra_train to train a translation task and use the vanilla transformer model, should I rewrite the model with Dataclass ?

**Comment by myleott** [comment]
Yep, we only migrated the LM task so far, but will be migrating the rest in a few weeks. If you do migrate the translation task before then, we'd love a PR! 😄

**Comment by zhengxxn** [comment]
Ok, I will try my best to submit a PR, but maybe I need to take some time to understand the code first ...
