### ISSUE TITLE
Releasing English-centric m2m model

### ISSUE THREAD

**Issue by avostryakov** [pytorch/fairseq#2893]
## 🚀 Feature Request
Can I ask to release English-centric m2m translation model from "Beyond English-Centric Multilingual Machine Translation" article?

### Motivation

In our work, we translate from all languages to English only. I think this model will have better quality for us comparing to the pure m2m 1.2B parameters model.

**Comment by lematt1991** [comment]
CC @huihuifan

**Comment by avostryakov** [comment]
I'm continue to be interested in English centric model

Thank you!
Anatoly Vostryakov,
email to: ***@***.***

//////


ср, 21 июл. 2021 г. в 11:04, stale[bot] ***@***.***>:
