### ISSUE TITLE
RecursionError: maximum recursion depth exceeded , error on inference , wav2vec2.0 .

### ISSUE THREAD

**Issue by SvPolina** [pytorch/fairseq#2894]
Hi,

I'm trying to test my fine-tuned model (language other than English) using the command given in readme.
The command exits with: 

RecursionError: maximum recursion depth exceeded.

Seemingly, it ogirinates from the build_model method in fairseq_task.py .
Using the fine-tuned English model - perfomes as expected.

Could you please guide me how to resolve this issue?

**Comment by lematt1991** [comment]
Can you provide the exact command you used as well as a gist of the backtrace.

**Comment by SvPolina** [comment]
> Can you provide the exact command you used as well as a gist of the backtrace.

Solved, specified unnecessary flag.

**Comment by SvPolina** [comment]
> Can you provide the exact command you used as well as a gist of the backtrace.

Hi @lematt1991 ,

The command :
 
python examples/speech_recognition/infer.py /path/to/manifest/ --task audio_pretraining --nbest 1 --path /path/to/model.pt     --gen-subset valid --results-path /path/to/results --w2l-decoder viterbi --word-score -1 --sil-weight 0 --criterion ctc --labels ltr   --max-tokens 4000000 

The backtrace attached.

[backtrace.txt](https://github.com/pytorch/fairseq/files/5564914/backtrace.txt)

**Comment by Charlottehoo** [comment]
@SvPolina Hello, I met the similar error when decoding. My command is python3 examples/speech_recognition/new/infer.py \
  --config-dir ~/fairseq/examples/hubert/config/decode \
  --config-name infer_viterbi \
  task.data=/.../test/data \
  task.normalize=false \
  dataset.gen_subset=test  \
  common_eval.path=/.../checkpoints/checkpoint_best.pt

Could you please tell me how to solve it?

**Comment by yash98** [comment]
It might not be very relevant the exact issue mentioned in the thread, but I encountered the same exception when running model inference for a library (ai4bharat-transliteration) using fairseq as a UDF on a spark cluster. The model object had to be distributed to different node, but I had defined it in the global scope of the script. It was failing with 

```
PythonException: 
  An exception was thrown from the Python worker. Please see the stack trace below.
'RecursionError: maximum recursion depth exceeded'. Full traceback below:
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/fairseq/tasks/fairseq_task.py", line 40, in __getattr__
    if name not in self._state and name in self._factories:
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/fairseq/tasks/fairseq_task.py", line 40, in __getattr__
    if name not in self._state and name in self._factories:
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/fairseq/tasks/fairseq_task.py", line 40, in __getattr__
    if name not in self._state and name in self._factories:
  [Previous line repeated 985 more times]
RecursionError: maximum recursion depth exceeded
```

It seemed like code was trying to get some attribute recursively but not finding it. So it seemed like some issue with loading the model

Ultimately loading the model for each paritition something like this helped me - https://stackoverflow.com/questions/75538208/reuse-a-class-in-pyspark-udf
