### ISSUE TITLE
How can I get the hidden state tensor of the input during loss computation?

### ISSUE THREAD

**Issue by monologue1107** [pytorch/fairseq#2895]
`net_output = model(**sample['net_input'])` is used to get the output of the net_input.
And how can I get the hidden state tensor of BART given net_input?

**Comment by lematt1991** [comment]
The `forward` method returns a tuple [[1](https://github.com/pytorch/fairseq/blob/master/fairseq/models/bart/model.py#L114)] containing the output tensor as well as a dict of "extra" tensors.  

```Python
output, extra = model(**sample['net_input'])
inner_states = extra['inner_states']
```

Should give you what you want

**Comment by monologue1107** [comment]
> The `forward` method returns a tuple [[1](https://github.com/pytorch/fairseq/blob/master/fairseq/models/bart/model.py#L114)] containing the output tensor as well as a dict of "extra" tensors.
> 
> ```python
> output, extra = model(**sample['net_input'])
> inner_states = extra['inner_states']
> ```
> 
> Should give you what you want

May I ask what the difference is between the code you give and code:
`inner_states = model.encoder(**sample['net_input'])`
according to the Model in bart. It seems I can use model.encoder to get the output of encoder as the hidden state
