### ISSUE TITLE
question about self-training wav2vec 2.0

### ISSUE THREAD

**Issue by natspan** [pytorch/fairseq#2896]
Hello, I was wondering if for finetuning the final wav2vec 2.0 model (ctc ft), you are using both the labeled and pseudo-labeled data? 
Also, would it help if we continued training the finetuned wav2vec model (with 100h labeled data) on the pseudo-labeled data or is better to finetune from scratch?

**Comment by alexeib** [comment]
yes it is using both. we finetuned the models from scratch. you can try fine-tuning a fine-tuned model. i tried it and it didnt help, but i also didnt run many experiments with this setup so it might be a question of finding the right hyper params

**Comment by natspan** [comment]
Thanks for the response!! I will close the issue.
