### ISSUE TITLE
Wav2Vec 2.0 Large (LV-60) Path is broken

### ISSUE THREAD

**Issue by harveenchadha** [pytorch/fairseq#2899]
The link for Wav2Vec 2.0 Large (LV-60) model is broken.

![image](https://user-images.githubusercontent.com/30959215/99351213-1a9c0400-28c6-11eb-9de3-dbbb0ca069bc.png)

**Comment by lematt1991** [comment]
Thanks for pointing this out!  Should be resolved when #2906 gets merged

**Comment by lematt1991** [comment]
We've renamed the file in the S3 bucket.  Downloads should work now.
