### ISSUE TITLE
how to save checkpoint in the middle of epoch training?

### ISSUE THREAD

**Issue by monologue1107** [pytorch/fairseq#2904]
I was about to save model every 10000 steps because the train takes almost 24 hrs every epoch.
What I do is to add another code in def validate_and_save of train.py, turn
```
do_save = (
        (end_of_epoch and epoch_itr.epoch % args.save_interval == 0)
        or num_updates >= max_update
        or (
            args.save_interval_updates > 0
            and num_updates > 0
            and num_updates % args.save_interval_updates == 0
            and num_updates >= args.validate_after_updates
        )
    )
```
into
```
do_save = (
        (end_of_epoch and epoch_itr.epoch % args.save_interval == 0)
        or (epoch_itr.epoch % 10000 == 0)
        or num_updates >= max_update
        or (
            args.save_interval_updates > 0
            and num_updates > 0
            and num_updates % args.save_interval_updates == 0
            and num_updates >= args.validate_after_updates
        )
    )
```
by adding `(epoch_itr.epoch % 10000 == 0)`
However, it does't work. So I wonder if there are some mistakes and what can I do in order to realize it.

**Comment by lematt1991** [comment]
If I understand correctly, your update will save every 10,000 epochs, not 10,000 updates.  That said, you shouldn't need to make any modifications to the code, this is what the `--save-interval-updates` argument is for.  Just add `--save-interval-updates 10000` to your command
