### ISSUE TITLE
on windows, functions of libbleu are not found

### ISSUE THREAD

**Issue by hollyhook** [pytorch/fairseq#292]
using microsoft visual compiler 14.0, fairseq 0.5.0
building libbleu dll by calling `python setup.py build develop`

functions in pyd are only exposed if they are declared as __declspec(dllexport).

problem is fixed if declaration of all exported C++ functions are changed, e.g.

```
extern "C" {
  __declspec(dllexport) void bleu_zero_init(bleu_stat* stat) {
    std::memset(stat, 0, sizeof(bleu_stat));
  }
}
```

**Comment by ShilinHe** [comment]
Have the same issue, can you share more details about the fix? where to put this code snippet?

**Comment by huihuifan** [comment]
Thanks @ShilinHe ! @hollyhook , hope that resolves your issue. Please re-open if not.

**Comment by GeorgeS2019** [comment]
@myleott  this modification needs to be included in the next release as part of pip install fairseq for Windows.

**Comment by erip** [comment]
I propose this should be re-opened. Requiring users to build your library from scratch is possible, but painful. I am not an expert at cross-compiling, but would it be as simple as adding the `__declspec` to the files in `master`? I don't know if that directive impacts Linux or OS X builds.
