### ISSUE TITLE
Inference using ctc decoder

### ISSUE THREAD

**Issue by haythemdhieb** [pytorch/fairseq#2920]
## 🚀 Feature Request
 Inference with wav2vec using ctc decoder

### Motivation

 I'm trying to build a pipeline using wav2vec embeedings on an arabic data set. I seem to have issues with wa2letter installation. So can anyone provide us with a simple inference using CTC decoder for example  or beam search

**Comment by alexeib** [comment]
look in ctc.py for an example of how to do argmax decoding which doesnt require a decoder or language model

**Comment by haythemdhieb** [comment]
This is a snippet of code of what I'm trying to do (I'm a beginner so no judgment):
`def greedy_decoder(data):
	# index for largest probability each row
	return [np.argmax(s) for s in data]
from fairseq.models.wav2vec import Wav2VecModel
cp = torch.load('/home/haythem/Downloads/wav2vec_small_960h.pt')
model = Wav2VecCtc.build_model(cp['args'],target_dict)
model.load_state_dict(cp['model'],strict=False)
with torch.no_grad():
    net_output = model(**sample["net_input"])
    lprobs = model.get_normalized_probs(
            net_output, log_probs=True
        ).contiguous()  
lprobs=utils.softmax(lprobs.float(),dim=-1)
data = np.array(lprobs)
result = greedy_decoder(data)
import pandas as pd
txt=pd.read_csv('/home/haythem/Desktop/libri/dict.ltr.txt',sep=' ',names=['letter','numbers'])
a2=list(txt.iloc[:,0])
results1=[a2[result[i]] for i in range(len(result))]
results1`

**Comment by alexeib** [comment]
heres the relevant code that you could plug in after your normalized_probs() call:
```
lprobs_t = lprobs.transpose(0, 1).float().contiguous().cpu()
toks = lp.argmax(dim=-1).unique_consecutive()
pred_units_arr = toks[toks != self.blank_idx].tolist()
pred_units = self.task.target_dictionary.string(pred_units_arr)
```

**Comment by sanakhamekhem** [comment]
I'm facing the same problem widh wav2letter. So, I'm trying to decode a sample using a simple decoder ctc. Here my code:
	import torch
	import fairseq

	import librosa
	model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(['/home/ubuntu/Self-Supervised/code/librispeech/finetuning/checkpoint_best.pt'], arg_overrides={"data": "dict.ltr"})

	model = model[0]
	model.eval()
	print('model loaded')
 
	
	with torch.no_grad():
		net_output = model(**sample["net_input"])
		lprobs = model.get_normalized_probs(
		net_output, log_probs=True
		).contiguous()

		lprobs=utils.log_softmax(lprobs.float(),dim=-1)
		data = np.array(lprobs)
		result = greedy_decoder(data)
		print(result)


error :
NameError: name 'sample' is not defined


I did not inderstand where I should put the wav data and how.
I will appreciate any help @alexeib and @haythemdhieb  .
Thanks.

**Comment by alexeib** [comment]
theres a problem in your python code. you need to iterate over the dataset to obtain "sample" which you use for your model

**Comment by sanakhamekhem** [comment]
Thank you, I have resolved the problem.
Just, one question:
I would like to work with handwritten text images instead of speech. Can I convert images into wav format and using the self-supervised code to train my model?

**Comment by alexeib** [comment]
wav format is for sound. while you can almost certainly use the same kind of model/training for handwritten ocr (and i think i saw some papers that do something similar), you'd have to implement a different data loader + encoder

**Comment by zahraomidi** [comment]
I am using Fairseq for Handwriting text recognition, and I am using an encoder + CTC architecture for my model. More specifically, I am using an architecture like Fairseq speech recognition "vggtransformerencoderonly" + CTC. Because I am using Google Colab to run my model, I was wondering if there is a way to infer translations for such a model without installing and using flashlight? @alexeib

**Comment by mthrok** [comment]
@haythemdhieb 

TorchAudio recently ported flashlight CTC decoder. It currently provides lexicon constrained beam search decoding with/without KenLM. 
You can try it with nightly build. 

The API documentation is found
https://pytorch.org/audio/main/prototype.ctc_decoder.html#lexicon-decoder

https://pytorch.org/audio/main/tutorials/asr_inference_with_ctc_decoder_tutorial.html

cc @carolineechen

**Comment by alexeib** [comment]
torchaudio is a good choice. additionally the "viterbi" (aka greedy) decoder doesnt rely on flashlight and can be used if you dont need to fuse with an LM
