### ISSUE TITLE
How to specify which GPU to use for inference of translation with fairseq-generate

### ISSUE THREAD

**Issue by junwen-austin** [pytorch/fairseq#2921]
## ❓ Questions and Help
I have 4 GPUs on a single machine and I would like to specify which GPU to use when doing inference of translation with fairseq-generate. I tried to use
```
--deive_id 1
--local-rank 1
```
to specify using GPU 1 instead of default GPU 0 with no success. I would appreciate if someone could drop a hint on how to do this. Many thanks.

   

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):  0.10.0
 - PyTorch Version (e.g., 1.0)        1.6
 - OS (e.g., Linux):   Linux
 - How you installed fairseq (`pip`, source):  pip
 - Build command you used (if compiling from source):
 - Python version:  3.7.8
 - CUDA/cuDNN version:   10.1
 - GPU models and configuration:   
 - Any other relevant information:

**Comment by lematt1991** [comment]
You should use the environment variable `CUDA_VISIBLE_DEVICES`:

```
CUDA_VISIBLE_DEVICES="1" <cmd>
```

to run on GPU 1.  You can also specify multiple devices via:


```
CUDA_VISIBLE_DEVICES="0,1" <cmd>
```

**Comment by DivyanshuBhoyar** [comment]
Still only one GPU getting used.
![image](https://github.com/facebookresearch/fairseq/assets/64900631/9eb27892-b5c5-48dc-86c8-d32013a2b3eb)

my command is
```
model=./checkpoints/best.pt
source_lang=mt1
target_lang=mt2

CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7" fairseq-generate data-bin \
  --path $model \
  --task translation \
  --gen-subset train \
  --source-lang $source_lang \
  --target-lang $target_lang \
  --remove-bpe 'sentencepiece'\
  --batch-size 128 --beam 5 --remove-bpe=sentencepiece \
  --log-format tqdm --results-path scripts/res.mt2
  ```
