### ISSUE TITLE
The sequence of operations in the Linformer Attention module is probably wrong.

### ISSUE THREAD

**Issue by pietruh** [pytorch/fairseq#2923]
## 🐛 Bug

Hi guys! 
In Linformer's example source code, I found that operation order may not match the official paper mathematics.

[Here, in the code](https://github.com/pytorch/fairseq/blob/master/examples/linformer/linformer_src/modules/multihead_linear_attention.py#L207), the linear attention is done in the following sequence of the two operations:
1. a Linear projection from `n` token's representations to `k.`
2. a Linear projection over the embedding dimension (`d_m` to `d_k`).
as here (#208 and #213 respectively) ![code_linformer](https://user-images.githubusercontent.com/9368870/99725937-20583c00-2ab6-11eb-9739-09aab879b771.png)

On the contrary, this image from the Linformer paper states that it should be performed in the order of:
1. a Linear projection over the embedding dimension (`d_m` to `d_k`).
2. a Linear projection from `n` token's representations to `k`.
As seen in the picture below:
![linformer](https://user-images.githubusercontent.com/9368870/99725299-30bbe700-2ab5-11eb-9c42-677d060a07b2.png)

Am I missing something important here? If anything gets confirmed, I am up for fixing it.

### Environment
Current fairseq version.

**Comment by myleott** [comment]
@madian9

**Comment by patil-suraj** [comment]
Any update on this?

**Comment by lorelupo** [comment]
I would also be happy to know more about this!
