### ISSUE TITLE
Typing issue on Mask

### ISSUE THREAD

**Issue by kearnsw** [pytorch/fairseq#2925]
### To Reproduce

When I run the following code:
```
import torch

de2en = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.de-en.single_model', tokenizer='moses', bpe='fastbpe')
de2en.eval()


de2en.translate("Maschinelles Lernen ist großartig!")
```
I get: 
RuntimeError: masked_select(): self and result must have the same scalar type
### Environment

MacOS 10.15.6 with python version 3.7 and torch version 1.7
This issue does not occur with a downgrade to torch version 1.5

**Comment by myleott** [comment]
I wasn't able to repro this...

```python
>>> import torch
>>> torch.__version__
'1.7.0'
>>> de2en = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.de-en.single_model', tokenizer='moses', bpe='fastbpe')
(...)
>>> de2en.eval()
(...)
>>> de2en.translate("Maschinelles Lernen ist großartig!")
'Machine learning is great!'
```

**Comment by myleott** [comment]
I also wasn't able to repro this on MacOS.

Can you try `torch.hub.load(..., force_reload=True)` and see if that works?
