### ISSUE TITLE
Wrong BPE codes in WMT19 En->Ru Ensemble model

### ISSUE THREAD

**Issue by jvamvas** [pytorch/fairseq#2928]
## 🐛 Bug

I am referring to the pre-trained model `transformer.wmt19.en-ru` which is available for download [here](https://github.com/pytorch/fairseq/tree/master/examples/translation) and [here](https://github.com/pytorch/fairseq/tree/master/examples/wmt19). The `bpecodes` file belongs to the English–German model instead of the English–Russian one, and should be replaced with the correct file.

### To Reproduce

```bash
wget https://dl.fbaipublicfiles.com/fairseq/models/wmt19.en-ru.ensemble.tar.gz
tar -xvf wmt19.en-ru.ensemble.tar.gz

# No difference to joint bpecodes of English-German model
diff -q wmt19.en-ru.ensemble/bpecodes wmt19.de-en.joined-dict.ensemble/bpecodes

# Should be 24k, but is 30k
wc -l wmt19.en-ru.ensemble/bpecodes 

# Look at a sample
tail wmt19.en-ru.ensemble/bpecodes
```

```
4 x 109019
F ische</w> 109018
sal aries</w> 109012
e kt 108978
ver gewal 108978
Sten cils</w> 108977
Freiwilli ge</w> 108969
doub les</w> 108965
po ckets</w> 108953
Gö tz</w> 108943
```

### Workaround

The model "En->Ru Single, no finetuning" linked [here](https://github.com/pytorch/fairseq/tree/master/examples/wmt19) seems to contain the correct BPE codes, so users can copy the file from there until the ensemble has been fixed.

**Comment by myleott** [comment]
I just redownloaded the archive and it seems correct to me. Note that it was fixed by @edunov a couple months back (see this issue for context: https://github.com/pytorch/fairseq/issues/2544#issuecomment-688054859).
