### ISSUE TITLE
AttributeError: 'Wav2VecCtc' object has no attribute 'remove_pretraining_modules'

### ISSUE THREAD

**Issue by xwuShirley** [pytorch/fairseq#2929]
Dear authors of wav2vec2,

Thank you for the great work and for open-source the code and model.

I have question regarding to the  fine-tuning the wav2v model code with my own dataset.  I followed exactly what it said:
$ fairseq-hydra-train \
    distributed_training.distributed_port=$PORT \
    task.data=/path/to/data \
    model.w2v_path=/path/to/model.pt \
    --config-path /path/to/fairseq-py/examples/wav2vec/config/finetuning \
    --config-name base_100h

I have successfully  run the code with  path/to/model.pt  to be **Wav2Vec 2.0 Base | No finetuning** (the first model in the table) and **Wav2Vec 2.0 Large (LV-60) | No finetuning** (the 9th-row model in the table) 

However, I could not run it with any other models.  it returns the following error.  Looks like those already finetuned models have no "remove_pretraining_modules". I am not sure how to fix it.  It would be great if you have any hints. 

Thank you very much for your help.
Best,
Shirley 

```

[2020-11-20 18:18:32,657][fairseq.data.audio.raw_audio_dataset][INFO] - loaded 2748, skipped 0 samples
Traceback (most recent call last):
  File “/home/fairseq/fairseq_cli/hydra_train.py", line 35, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File “/home/fairseq/fairseq/distributed_utils.py", line 334, in call_main
    main(cfg, **kwargs)
  File “/home/fairseq/fairseq_cli/train.py", line 74, in main
    model = task.build_model(cfg.model)
  File “/home/fairseq/fairseq/tasks/audio_pretraining.py", line 200, in build_model
    model = super().build_model(model_cfg)
  File “/home/fairseq/fairseq/tasks/fairseq_task.py", line 282, in build_model
    model = models.build_model(cfg, self)
  File “/home/fairseq/fairseq/models/__init__.py", line 86, in build_model
    return model.build_model(cfg, task)
  File “/home/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 147, in build_model
    w2v_encoder = Wav2VecEncoder(cfg, task.target_dictionary)
  File “/home/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 304, in __init__
    model.remove_pretraining_modules()
  File "/root/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'Wav2VecCtc' object has no attribute 'remove_pretraining_modules'

```

**Comment by xwuShirley** [comment]
We figured it out! those fine-tuned model should be modified as checkpoint_last and put to the checkpoint folder!

**Comment by iamxiaoyubei** [comment]
wav2vec_small_960h.pt still has such problem.

**Comment by Esdsnqxz** [comment]
i'm facing the same problem, have you solved the problem?

**Comment by Esdsnqxz** [comment]
hi @xwuShirley ,i'm facing the same problem,what do you mean the checkpoint folder?

**Comment by indifferen** [comment]
same question

**Comment by indifferen** [comment]
> hi @xwuShirley ,i'm facing the same problem,what do you mean the checkpoint folder?

 checkpoint.restore_file=/path/to/finetuned/model

**Comment by Esdsnqxz** [comment]
> > hi @xwuShirley ,i'm facing the same problem,what do you mean the checkpoint folder?
> 
> checkpoint.restore_file=/path/to/finetuned/model

u can reset the checkpoints:save_dir and restore_file in finetune config file

**Comment by zxpan** [comment]
> We figured it out. Those fine-tuned models should be modified as checkpoint_last and put to the checkpoint folder!

Hi, Could you please shed light on how you modify the fine-tuned model to checkpoint_last?
Thanks

**Comment by ngoel17** [comment]
A more detailed explanation will help me too.

**Comment by fainter1945** [comment]
fairseq-hydra-train task.data=/u01/wangfangyuan/wfy_udisk/librispeech/LibriSpeech/test-clean model.w2v_path=/u01/wangfangyuan/svn/Fairseq/fairseq/models_wav2vec2/wav2vec_small.pt --config-dir examples/wav2vec/config/finetuning --config-name base_1h
![image](https://user-images.githubusercontent.com/10337551/105300482-ca0e9300-5bf5-11eb-90df-0eeac2453e34.png)

**Comment by ksingla025** [comment]
Did anyone fix it? Does checkpoint.restore_file go in faiseq-hydra-train command

fairseq-hydra-train  distributed_training.distributed_port=6081     task.data=/data/home/karan/lap/mi_data     model.w2v_path=<path to wav2vec_small_960h.pt>  checkpoint.restore_file=<path-to-empty-folder where new model is stored> --config <fairseq/examples/wav2vec/config/finetuning> --config-name base_100h

**Comment by nshmyrev** [comment]
@ksingla025, in hydra config you do like this:

```
checkpoint:
  finetune_from_model: /hdd/fairseq/eval/wav2vec2_vox_960h_new.pt
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer
```

**Comment by Jeremyzzzz** [comment]
> @ksingla025, in hydra config you do like this:
> 
> ```
> checkpoint:
>   finetune_from_model: /hdd/fairseq/eval/wav2vec2_vox_960h_new.pt
>   no_epoch_checkpoints: true
>   best_checkpoint_metric: wer
> 
> ....
> 
> model:
>   _name: wav2vec_ctc
>   w2v_path: /hdd/fairseq/eval/wav2vec_vox_new.pt
>   apply_mask: true
>   mask_prob: 0.5
>   mask_channel_prob: 0.5
>   mask_channel_length: 64
>   layerdrop: 0.1
>   activation_dropout: 0.1
>   feature_grad_mult: 0.0
>   freeze_finetune_updates: 10000
> ```

Hi, Nick. I am finetuning the wav2vec2_vox_960_new.pt with my own corpus and I am a newbie to fairseq. I wonder what is your w2v_path? I thought it should also be the path to wav2vec2_vox_960_new.pt. Could you please explain that?

**Comment by fainter1945** [comment]
&nbsp;Hi,


&nbsp; &nbsp; You are right, the "w2v_path" can be set as wav2vec2_vox_960_new.pt or another pretrained model trained by yourself.
&nbsp; &nbsp; All in all, you should make sure the model used here is a wav2vec model not a wav2vec_ctc model.


&nbsp; &nbsp; Good luck!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pytorch/fairseq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月10日(星期六) 上午10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pytorch/fairseq] AttributeError: 'Wav2VecCtc' object has no attribute 'remove_pretraining_modules' (#2929)





  
@ksingla025, in hydra config you do like this:
 checkpoint:   finetune_from_model: /hdd/fairseq/eval/wav2vec2_vox_960h_new.pt   no_epoch_checkpoints: true   best_checkpoint_metric: wer .... model:   _name: wav2vec_ctc   w2v_path: /hdd/fairseq/eval/wav2vec_vox_new.pt   apply_mask: true   mask_prob: 0.5   mask_channel_prob: 0.5   mask_channel_length: 64   layerdrop: 0.1   activation_dropout: 0.1   feature_grad_mult: 0.0   freeze_finetune_updates: 10000   
Hi, Nick. I am finetuning the wav2vec2_vox_960_new.pt with my own corpus and I am a newbie to fairseq. I wonder what is your w2v_path? I thought it should also be the path to wav2vec2_vox_960_new.pt. Could you please explain that?
