### ISSUE TITLE
BART model does NOT work properly when trained from scratch

### ISSUE THREAD

**Issue by mcao610** [pytorch/fairseq#2934]
## 🐛 Bug

I trained a BART model from scratch (without the "--restore-file $PATH" argument) for the summarization task. During inference, the decoding seems wrong. Here are some output samples from the model:

```
s in Wales have been warned to be "inadequate" by the Welsh Government over the next five years.
s of a man who died after being hit by a car have been named by police.
ing the murder of a man who was found dead at a house in County Antrim has been jailed for life.
 Ched Evans has told a court that she would have to be a woman accused of raping a woman in the UK.
 Glamorgan has signed a new two-year contract with the Premier League club.
```

The beginning of each output sentence seems incomplete. Note that when the model is fine-tuned on the same dataset, everything is fine (with "--restore-file $PATH").

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Train a BART model on the summarization dataset (XSum/CNNDM) from scratch.
```
TOTAL_NUM_UPDATES=15000
WARMUP_UPDATES=500      
LR=3e-05
MAX_TOKENS=2048
UPDATE_FREQ=2
SAVE_DIR=checkpoints/

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 fairseq-train $DATA_PATH \
    --save-dir $SAVE_DIR \
    --max-tokens $MAX_TOKENS \
    --task translation \
    --source-lang source --target-lang target \
    --truncate-source \
    --layernorm-embedding \
    --share-all-embeddings \
    --share-decoder-input-output-embed \
    --reset-optimizer --reset-dataloader --reset-meters \
    --required-batch-size-multiple 1 \
    --arch bart_large \
    --criterion label_smoothed_cross_entropy \
    --label-smoothing 0.1 \
    --dropout 0.1 --attention-dropout 0.1 \
    --weight-decay 0.01 --optimizer adam --adam-betas "(0.9, 0.999)" --adam-eps 1e-08 \
    --clip-norm 0.1 \
    --lr-scheduler polynomial_decay --lr $LR --total-num-update $TOTAL_NUM_UPDATES --warmup-updates $WARMUP_UPDATES \
    --fp16 --update-freq $UPDATE_FREQ \
    --skip-invalid-size-inputs-valid-test \
    --find-unused-parameters;
```
2. Inference with the official code.
```
bart = BARTModel.from_pretrained(
    args.checkpoint_path,
    checkpoint_file="checkpoint_best.pt",
    data_name_or_path=args.data_path
)

bart.cuda()
bart.eval()
bart.half()
count = 1
bsz = 32
with open('test.source') as source, open('test.hypo', 'w') as fout:
    sline = source.readline().strip()
    slines = [sline]
    for sline in source:
        if count % bsz == 0:
            with torch.no_grad():
                hypotheses_batch = bart.sample(slines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)

            for hypothesis in hypotheses_batch:
                fout.write(hypothesis + '\n')
                fout.flush()
            slines = []

        slines.append(sline.strip())
        count += 1
    if slines != []:
        hypotheses_batch = bart.sample(slines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)
        for hypothesis in hypotheses_batch:
            fout.write(hypothesis + '\n')
            fout.flush()
```

### Expected behavior

During inference, the decoding goes wrong and the decoded sentences are not completed. 

### Environment

 - fairseq Version: 0.9.0
 - PyTorch Version: 1.5.0
 - OS: Linux
 - How you installed fairseq:  `pip`, source
 - Build command you used (if compiling from source): pip install --editable ./
 - Python version: 3.7.4
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: V100
 - Any other relevant information: None

**Comment by VikasRajashekar** [comment]
An off questions: How did you set up the environment to use this? I am not able to get it to run and face a lot of issues. 
If you can share your conda commands to set it up.

**Comment by mcao610** [comment]
> An off questions: How did you set up the environment to use this? I am not able to get it to run and face a lot of issues.
> If you can share your conda commands to set it up.



> An off questions: How did you set up the environment to use this? I am not able to get it to run and face a lot of issues.
> If you can share your conda commands to set it up.

**Comment by mcao610** [comment]
> An off questions: How did you set up the environment to use this? I am not able to get it to run and face a lot of issues.
> If you can share your conda commands to set it up.

I simply follow the official requirements and installation.

**Comment by FYYFU** [comment]
> > An off questions: How did you set up the environment to use this? I am not able to get it to run and face a lot of issues.
> > If you can share your conda commands to set it up.
> 
> I simply follow the official requirements and installation.

I also follow the offical README.md and run the CNN/DM summarization task. but something wrong happened in the code
```python
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-3a6394cfbbcb> in <module>
     10         if count % bsz == 0:
     11             with torch.no_grad():
---> 12                 hypotheses_batch = bart.sample(slines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)
     13 
     14             for hypothesis in hypotheses_batch:
      .........................
RuntimeError: Size does not match at dimension 0 expected index [128, 1] to be smaller than src [20, 50264] apart from dimension 1
```

**Comment by mcao610** [comment]
> > > An off questions: How did you set up the environment to use this? I am not able to get it to run and face a lot of issues.
> > > If you can share your conda commands to set it up.
> > 
> > 
> > I simply follow the official requirements and installation.
> 
> I also follow the offical README.md and run the CNN/DM summarization task. but something wrong happened in the code
> 
> ```python
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-17-3a6394cfbbcb> in <module>
>      10         if count % bsz == 0:
>      11             with torch.no_grad():
> ---> 12                 hypotheses_batch = bart.sample(slines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)
>      13 
>      14             for hypothesis in hypotheses_batch:
>       .........................
> RuntimeError: Size does not match at dimension 0 expected index [128, 1] to be smaller than src [20, 50264] apart from dimension 1
> ```

Did you use the official `bart.large.xsum` checkpoint? Or you trained the model by yourself?

**Comment by FYYFU** [comment]
> > > > An off questions: How did you set up the environment to use this? I am not able to get it to run and face a lot of issues.
> > > > If you can share your conda commands to set it up.
> > > 
> > > 
> > > I simply follow the official requirements and installation.
> > 
> > 
> > I also follow the offical README.md and run the CNN/DM summarization task. but something wrong happened in the code
> > ```python
> > RuntimeError                              Traceback (most recent call last)
> > <ipython-input-17-3a6394cfbbcb> in <module>
> >      10         if count % bsz == 0:
> >      11             with torch.no_grad():
> > ---> 12                 hypotheses_batch = bart.sample(slines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)
> >      13 
> >      14             for hypothesis in hypotheses_batch:
> >       .........................
> > RuntimeError: Size does not match at dimension 0 expected index [128, 1] to be smaller than src [20, 50264] apart from dimension 1
> > ```
> 
> Did you use the official `bart.large.xsum` checkpoint? Or you trained the model by yourself?

i try to train the `bart.large.cnn` from scratch. following the instruction of the README and get the checkpoint using 4 *  TITAN RTX。

but wrong happened in the `Inference for CNN-DM test data using above trained checkpoint` code provided by the `README.summarization.md`

**Comment by mcao610** [comment]
> > > > > An off questions: How did you set up the environment to use this? I am not able to get it to run and face a lot of issues.
> > > > > If you can share your conda commands to set it up.
> > > > 
> > > > 
> > > > I simply follow the official requirements and installation.
> > > 
> > > 
> > > I also follow the offical README.md and run the CNN/DM summarization task. but something wrong happened in the code
> > > ```python
> > > RuntimeError                              Traceback (most recent call last)
> > > <ipython-input-17-3a6394cfbbcb> in <module>
> > >      10         if count % bsz == 0:
> > >      11             with torch.no_grad():
> > > ---> 12                 hypotheses_batch = bart.sample(slines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)
> > >      13 
> > >      14             for hypothesis in hypotheses_batch:
> > >       .........................
> > > RuntimeError: Size does not match at dimension 0 expected index [128, 1] to be smaller than src [20, 50264] apart from dimension 1
> > > ```
> > 
> > 
> > Did you use the official `bart.large.xsum` checkpoint? Or you trained the model by yourself?
> 
> i try to train the `bart.large.cnn` from scratch. following the instruction of the README and get the checkpoint using 4 * TITAN RTX。
> 
> but wrong happened in the `Inference for CNN-DM test data using above trained checkpoint` code provided by the `README.summarization.md`

There are some bugs in the latest version of the code. You can checkout to previous commits (e.g. 23d8502b).

**Comment by FYYFU** [comment]
> > > > > > An off questions: How did you set up the environment to use this? I am not able to get it to run and face a lot of issues.
> > > > > > If you can share your conda commands to set it up.
> > > > > 
> > > > > 
> > > > > I simply follow the official requirements and installation.
> > > > 
> > > > 
> > > > I also follow the offical README.md and run the CNN/DM summarization task. but something wrong happened in the code
> > > > ```python
> > > > RuntimeError                              Traceback (most recent call last)
> > > > <ipython-input-17-3a6394cfbbcb> in <module>
> > > >      10         if count % bsz == 0:
> > > >      11             with torch.no_grad():
> > > > ---> 12                 hypotheses_batch = bart.sample(slines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)
> > > >      13 
> > > >      14             for hypothesis in hypotheses_batch:
> > > >       .........................
> > > > RuntimeError: Size does not match at dimension 0 expected index [128, 1] to be smaller than src [20, 50264] apart from dimension 1
> > > > ```
> > > 
> > > 
> > > Did you use the official `bart.large.xsum` checkpoint? Or you trained the model by yourself?
> > 
> > 
> > i try to train the `bart.large.cnn` from scratch. following the instruction of the README and get the checkpoint using 4 * TITAN RTX。
> > but wrong happened in the `Inference for CNN-DM test data using above trained checkpoint` code provided by the `README.summarization.md`
> 
> There are some bugs in the latest version of the code. You can checkout to previous commits (e.g. [23d8502](https://github.com/pytorch/fairseq/commit/23d8502bdde88a3e58e0910e2ee49834f8478b39)).

thanks a lot, i will check it. :)

**Comment by FYYFU** [comment]
> > > > > > An off questions: How did you set up the environment to use this? I am not able to get it to run and face a lot of issues.
> > > > > > If you can share your conda commands to set it up.
> > > > > 
> > > > > 
> > > > > I simply follow the official requirements and installation.
> > > > 
> > > > 
> > > > I also follow the offical README.md and run the CNN/DM summarization task. but something wrong happened in the code
> > > > ```python
> > > > RuntimeError                              Traceback (most recent call last)
> > > > <ipython-input-17-3a6394cfbbcb> in <module>
> > > >      10         if count % bsz == 0:
> > > >      11             with torch.no_grad():
> > > > ---> 12                 hypotheses_batch = bart.sample(slines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)
> > > >      13 
> > > >      14             for hypothesis in hypotheses_batch:
> > > >       .........................
> > > > RuntimeError: Size does not match at dimension 0 expected index [128, 1] to be smaller than src [20, 50264] apart from dimension 1
> > > > ```
> > > 
> > > 
> > > Did you use the official `bart.large.xsum` checkpoint? Or you trained the model by yourself?
> > 
> > 
> > i try to train the `bart.large.cnn` from scratch. following the instruction of the README and get the checkpoint using 4 * TITAN RTX。
> > but wrong happened in the `Inference for CNN-DM test data using above trained checkpoint` code provided by the `README.summarization.md`
> 
> There are some bugs in the latest version of the code. You can checkout to previous commits (e.g. [23d8502](https://github.com/pytorch/fairseq/commit/23d8502bdde88a3e58e0910e2ee49834f8478b39)).

i read the issue and checkout the code. My download version had fixed the bug. the code in my download version is below:
```python
            if torch.cuda.is_available():
                warnings.warn(
                    "amp_C fused kernels unavailable, disabling multi_tensor_l2norm; "
                    "you may get better performance by installing NVIDIA's apex library"
                )
                device = torch.cuda.current_device()
            elif grads[0].device.type == "xla":
                device = grads[0].device
            else:
                device = torch.device("cpu")
            total_norm = torch.norm(
                torch.stack(
                    [torch.norm(g, p=2, dtype=torch.float32).to(device) for g in grads]
                )
            )
```
so mistake may happen somewhere else.

**Comment by myleott** [comment]
Ah, you’re using the translation task rather than denoising. Probably there’s a mismatch with the hub interface relating to the beginning of sentence token, and you need to remove the <s> token from here: https://github.com/pytorch/fairseq/blob/f732b403ec15244c41a24b9e28d6c5a411a511df/fairseq/models/bart/hub_interface.py#L58

**Comment by mcao610** [comment]
> Ah, you’re using the translation task rather than denoising. Probably there’s a mismatch with the hub interface relating to the beginning of sentence token, and you need to remove the `<s>` token from here:
> 
> https://github.com/pytorch/fairseq/blob/f732b403ec15244c41a24b9e28d6c5a411a511df/fairseq/models/bart/hub_interface.py#L58

Yes

**Comment by mcao610** [comment]
> Ah, you’re using the translation task rather than denoising. Probably there’s a mismatch with the hub interface relating to the beginning of sentence token, and you need to remove the `<s>` token from here:
> 
> https://github.com/pytorch/fairseq/blob/f732b403ec15244c41a24b9e28d6c5a411a511df/fairseq/models/bart/hub_interface.py#L58

Hi @myleott, thanks for the replay. Yes, I am using the translation task. However, removing the `"<s> "` token doesn't work for me. The outputs are the same.

**Comment by mcao610** [comment]
> > Ah, you’re using the translation task rather than denoising. Probably there’s a mismatch with the hub interface relating to the beginning of sentence token, and you need to remove the `<s>` token from here:
> > https://github.com/pytorch/fairseq/blob/f732b403ec15244c41a24b9e28d6c5a411a511df/fairseq/models/bart/hub_interface.py#L58
> 
> Hi @myleott, thanks for the replay. Yes, I am using the translation task. However, removing the `"<s> "` token doesn't work for me. The outputs are the same.

I think the problem is caused by `prefix_tokens`. Force `prefix_tokens` to be `None` will solve the issue.

**Comment by negrinho** [comment]
Hi. I'm running into the same problem with `sample`. I'm following the [fine tuning recipe for BART](https://github.com/pytorch/fairseq/blob/master/examples/bart/README.summarization.md) using the latest version of `fairseq` with my own data (formatted as one sentence per line for the source and target files, without any special tokens added, for example, on line of each of these files could simply be "The cat sat on the mat."). 

@mcao610 Can you please elaborate what do you mean by setting `prefix_tokens` to `None`? `prefix_tokens` appears to be a string in `hub_interface.py`. Should you change the call to `sample` or `hub_interface.py` directly? Thank you.

**Comment by mcao610** [comment]
> Hi. I'm running into the same problem with `sample`. I'm following the [fine tuning recipe for BART](https://github.com/pytorch/fairseq/blob/master/examples/bart/README.summarization.md) using the latest version of `fairseq` with my own data (formatted as one sentence per line for the source and target files, without any special tokens added, for example, on line of each of these files could simply be "The cat sat on the mat.").
> 
> @mcao610 Can you please elaborate what do you mean by setting `prefix_tokens` to `None`? `prefix_tokens` appears to be a string in `hub_interface.py`. Should you change the call to `sample` or `hub_interface.py` directly? Thank you.

I mean set the `prefix_tokens` variable in `sequence_generator.py` to `None`. For instance, you can add `prefix_tokens = None` before this for loop in `sequence_generator.py` :

https://github.com/pytorch/fairseq/blob/f732b403ec15244c41a24b9e28d6c5a411a511df/fairseq/sequence_generator.py#L293

**Comment by cyc025** [comment]
@myleott The latest Fairseq version does not seem to work with the documented finetuning command:

TOTAL_NUM_UPDATES=20000  
WARMUP_UPDATES=500      
LR=3e-05
MAX_TOKENS=2048
UPDATE_FREQ=4
BART_PATH=/path/to/bart/model.pt

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 fairseq-train cnn_dm-bin \
    --restore-file $BART_PATH \
    --max-tokens $MAX_TOKENS \
    --task translation \
    --source-lang source --target-lang target \
    --truncate-source \
    --layernorm-embedding \
    --share-all-embeddings \
    --share-decoder-input-output-embed \
    --reset-optimizer --reset-dataloader --reset-meters \
    --required-batch-size-multiple 1 \
    --arch bart_large \
    --criterion label_smoothed_cross_entropy \
    --label-smoothing 0.1 \
    --dropout 0.1 --attention-dropout 0.1 \
    --weight-decay 0.01 --optimizer adam --adam-betas "(0.9, 0.999)" --adam-eps 1e-08 \
    --clip-norm 0.1 \
    --lr-scheduler polynomial_decay --lr $LR --total-num-update $TOTAL_NUM_UPDATES --warmup-updates $WARMUP_UPDATES \
    --fp16 --update-freq $UPDATE_FREQ \
    --skip-invalid-size-inputs-valid-test \
    --find-unused-parameters;

**Comment by abhisehk18** [comment]
hii..I am facing same issue while using Huginface Bart for text summarization(finetuned)

text_input_ids = tokenizer.batch_encode_plus([text],max_length=512,pad_to_max_length=True,
                        return_tensors='pt',truncation=True)

model_output='ings are s o multifocal patchy homogeneous areas of ground glass attenuation with septal thickening in both lung fields '

actual_output='findings are s o multifocal patchy homogeneous areas of ground glass attenuation with septal thickening in both lung fields'

**Comment by wbchief** [comment]
> > Hi. I'm running into the same problem with `sample`. I'm following the [fine tuning recipe for BART](https://github.com/pytorch/fairseq/blob/master/examples/bart/README.summarization.md) using the latest version of `fairseq` with my own data (formatted as one sentence per line for the source and target files, without any special tokens added, for example, on line of each of these files could simply be "The cat sat on the mat.").
> > @mcao610 Can you please elaborate what do you mean by setting `prefix_tokens` to `None`? `prefix_tokens` appears to be a string in `hub_interface.py`. Should you change the call to `sample` or `hub_interface.py` directly? Thank you.
> 
> I mean set the `prefix_tokens` variable in `sequence_generator.py` to `None`. For instance, you can add `prefix_tokens = None` before this for loop in `sequence_generator.py` :
> 
> https://github.com/pytorch/fairseq/blob/f732b403ec15244c41a24b9e28d6c5a411a511df/fairseq/sequence_generator.py#L293

您好！我也遇到这个问题了，加上prefix_tokens = None也不能解决，请问你是怎么解决的呢？谢谢

**Comment by wbchief** [comment]
> > > Ah, you’re using the translation task rather than denoising. Probably there’s a mismatch with the hub interface relating to the beginning of sentence token, and you need to remove the `<s>` token from here:
> > > https://github.com/pytorch/fairseq/blob/f732b403ec15244c41a24b9e28d6c5a411a511df/fairseq/models/bart/hub_interface.py#L58
> > 
> > 
> > Hi @myleott, thanks for the replay. Yes, I am using the translation task. However, removing the `"<s> "` token doesn't work for me. The outputs are the same.
> 
> I think the problem is caused by `prefix_tokens`. Force `prefix_tokens` to be `None` will solve the issue.

Hello! I also encountered this problem, and adding prefix_tokens = None could not solve it. How did you solve it? thank you
