### ISSUE TITLE
Would you release the models/checkpoints on speech-to-text tasks(eg.on MUST-C)

### ISSUE THREAD

**Issue by ReneeYe** [pytorch/fairseq#2937]
## 🚀 Feature Request
Would you release the models/checkpoints on speech-to-text tasks? Especially the checkpoints(both ASR and ST)on the MUST-C dataset.  

### Motivation

We are reproducing the speech translation on the MUST-C dataset, we find that our result is more than 1 BLEU less than yours. For example, in en-de, the best BLEU we got on tst-COMMON is 21.7. We guess this is probably due to the difference in ASR pretrained checkpoint or other details missing. So, would you release the models(asr and st models), so that we can swiftly reproduce the results reported in the paper (https://arxiv.org/pdf/2010.05171.pdf)? 
Thanks!

**Comment by kahne** [comment]
Hi @ReneeYe , thanks for your interest. Yes, we will release our pre-trained models soon (after Thanksgiving/first week of December). I will send you a release notification if you can provide me your email.

**Comment by ReneeYe** [comment]
> Hi @ReneeYe , thanks for your interest. Yes, we will release our pre-trained models soon (after Thanksgiving/first week of December). I will send you a release notification if you can provide me your email.

Many thanks! :)

**Comment by kahne** [comment]
@ReneeYe Pre-trained models are now available at https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/mustc_example.md
