### ISSUE TITLE
many torchscript errors in adaptive_softmax.py 

### ISSUE THREAD

**Issue by ismymajia** [pytorch/fairseq#2938]
#### problem
Many errors occur when i export the gpt lm to torchscript:

 aten::append.Tensor(Tensor[](a!) self, Tensor(c -> *) el) -> (Tensor[](a!)):
  Expected a value of type 'Tensor' for argument 'el' but instead found type 'int'.

  aten::append.int(int[](a!) self, int el) -> (int[](a!)):
  Expected a value of type 'List[int]' for argument 'self' but instead found type 'List[Tensor]'.
  Empty lists default to List[Tensor]. Add a variable annotation to the assignment to create an empty list of another type (torch.jit.annotate(List[T, []]) where T is the type of elements in the list for Python 2)

  aten::append.float(float[](a!) self, float el) -> (float[](a!)):
  Expected a value of type 'List[float]' for argument 'self' but instead found type 'List[Tensor]'.
  Empty lists default to List[Tensor]. Add a variable annotation to the assignment to create an empty list of another type (torch.jit.annotate(List[T, []]) where T is the type of elements in the list for Python 2)

  aten::append.bool(bool[](a!) self, bool el) -> (bool[](a!)):
  Expected a value of type 'List[bool]' for argument 'self' but instead found type 'List[Tensor]'.
  Empty lists default to List[Tensor]. Add a variable annotation to the assignment to create an empty list of another type (torch.jit.annotate(List[T, []]) where T is the type of elements in the list for Python 2)

  aten::append.t(t[](a!) self, t(c -> *) el) -> (t[](a!)):
  Could not match type int to t in argument 'el': Type variable 't' previously matched to type Tensor is matched to type int.

  aten::append(str[](a!) self, str? el) -> (str[](a!)):
  Expected a value of type 'List[str]' for argument 'self' but instead found type 'List[Tensor]'.
  Empty lists default to List[Tensor]. Add a variable annotation to the assignment to create an empty list of another type (torch.jit.annotate(List[T, []]) where T is the type of elements in the list for Python 2)

The original call is:
  File "/usr/local/lib/python3.6/dist-packages/fairseq/modules/adaptive_softmax.py", line 152
target_idxs.append(None)
      #~~~~~~~~~~~~~~~~~~ <--- HERE
new_target.append(None)

There are many None that cannot be supported by torchscript in  adaptive_softmax.py .

#### What have you tried?
i try modify target_idxs.append(None) to target_idxs.append(-1), but errors still occur.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):  0.9
 - PyTorch Version (e.g., 1.0)   1.4
 - OS (e.g., Linux):  centos7
 - How you installed fairseq (`pip`, source): pip install .
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: cu100
 - GPU models and configuration:
 - Any other relevant information:

@myleott

**Comment by myleott** [comment]
Yep, looks like this module isn't compatible with TorchScript. We don't have any immediate plans to add support, but would welcome a PR if you get a chance to make it work! 😄
