### ISSUE TITLE
data augmentation on summarization for BART

### ISSUE THREAD

**Issue by monologue1107** [pytorch/fairseq#2940]
I am supposed to manually add some other tags after sentences in each line in train.target for loss computation during training.
For example, the original line(summary) in train.target file is `"hello, world." ` (assumed tensor.size=[1,12]
The fixed line is supposed to be `hello, world. <token> positive.`(assumed tensor.size=[1,15]

However, when I slice the loaded target into two parts, I find that the size of net_output([1,15]) and the size of actual target([1,12]) didn't match so that it can't calculate well when code goes to 
`nll_loss = -lprobs.gather(dim=-1, index=target)`
with errors:
`RuntimeError: invalid argument 2: Input tensor must have same size as output tensor apart from the specified dimension`
(I need to use the other information(positive) in target for another loss computation.)

How can I fix this? Or what other method is more proper to achieve my goals? I would really appreciate if you can help me.
@myleott  @alexeib  @tangyuq

**Comment by monologue1107** [comment]
As far as I am concerned, it might be useful if I also slice the prev_output_tokens in BART.forward function. 
```
x, extra = self.decoder(
            prev_output_tokens,
            encoder_out=encoder_out,
            features_only=features_only,
            **kwargs,
        )
```

I don't know if it will hurt the model performance or other issues. Looking forward to your kindly reply.

**Comment by monologue1107** [comment]
I have tried to slice the previous_output_tokens, new issues occurred when batch size is more than 1.(It will result different operations when slice) Is there any solution to limit the batch size or solve this problem?

**Comment by myleott** [comment]
It's not quite clear what you're trying to achieve, what you tried, and what didn't work.

It sounds like you want to append some extra tokens to the target when training. In this case you'll need to modify both `sample["target"]` (the reference tokens for computing the loss) and `sample["net_input"]["prev_output_tokens"]` (the target tokens, shifted left by one position for "teacher forcing").

The easiest way to do this is to create your own Criterion. You can start by forking the [cross_entropy](https://github.com/pytorch/fairseq/blob/master/fairseq/criterions/cross_entropy.py) criterion and then you can modify `sample` before calling the model.

**Comment by monologue1107** [comment]
> It's not quite clear what you're trying to achieve, what you tried, and what didn't work.
> 
> It sounds like you want to append some extra tokens to the target when training. In this case you'll need to modify both `sample["target"]` (the reference tokens for computing the loss) and `sample["net_input"]["prev_output_tokens"]` (the target tokens, shifted left by one position for "teacher forcing").
> 
> The easiest way to do this is to create your own Criterion. You can start by forking the [cross_entropy](https://github.com/pytorch/fairseq/blob/master/fairseq/criterions/cross_entropy.py) criterion and then you can modify `sample` before calling the model.

Thanks for your reply. I think we are thinking the same!
I have already create my own Criterion to modify the sample['target']. And I modify the sample['net_input'][prev_output_tokens'] in model.py of BART by using
```
        x, extra = self.decoder(
            target_slice(prev_output_tokens),
            encoder_out=encoder_out,
            features_only=features_only,
            **kwargs,
        )
```
I just keep the real target remained before I feed them into decoder.(target_slice is my own function to modify them)
It now seems to work well that `lprobs` match `target` well. Please notify anything you think is not appropriate.

Another issue is that when sample size is small and fairseq feed more than one sample once, there seems to be some difficulty. 
For example, there are two augmented sample in the same 16 tokens length which are fed into model at the same time.(target .size()=[2,16]) However, their compositions are different that one is 14+2, the other is 13+3. ['initial target'+'extra tokens']
Now I need to modify them by cutting extra tokens in teacher forcing. So am I right that I just cut the extra tokens off and pad the shorter one sample target (with 13 tokens) to 14 tokens with one '0'?
Do appreciate if you can help me to figure this out.
