### ISSUE TITLE
Don't translate keywords and names

### ISSUE THREAD

**Issue by sophgit** [pytorch/fairseq#2941]
## ❓ Questions and Help
Hello, I'm new to this. 
I did search the docs and issues for a solution but couldn't find any. If there already is an issue/doc about this topic, I'm sorry and I'd be really thankful for a pointer.

#### What is your question?
I am using the transformer.wmt19.de-en.single_model and its result were really good so far. But for my use case it would be important to keep some keywords in the original input without translating them. Also some names are translated to different names. For example the German "Bernd" translates to "Bernard" in English which doesn't work at all for my use case. 
(How) can I prevent certain words and names from translating?

**Comment by myleott** [comment]
I haven't tried this myself, but you could look into constrained decoding (implemented as `--constraints`): https://github.com/pytorch/fairseq/tree/master/examples/constrained_decoding

**Comment by Mr-wang2016** [comment]
@myleott
Hi. I have tried --constraints, but the translation speed is slower than before without using --constraints. Is there any solution?
