### ISSUE TITLE
ZIPing error while preprocessing LibriSpeech

### ISSUE THREAD

**Issue by Munzu** [pytorch/fairseq#2946]
### What is your question?

I tried to follow the speech to text guide for LibriSpeech:

https://github.com/pytorch/fairseq/tree/master/examples/speech_to_text#example-1-speech-recognition-asr-on-librispeech

I created a directory `ls_root` in the fairseq root directory, defined `LS_ROOT="ls_root"` in my shell and executed the terminal command shown in the guide

```
python examples/speech_to_text/prep_librispeech_data.py --output-root ${LS_ROOT} --vocab-type unigram --vocab-size 10000
```

Fairseq then seems to do its work until it has to do ZIP the features:

```
Fetching split train-clean-100...
Extracting log mel filter bank features...
100%|██████████| 28539/28539 [02:34<00:00, 185.08it/s]
Fetching split train-clean-360...
Extracting log mel filter bank features...
100%|██████████| 104014/104014 [11:26<00:00, 151.58it/s]
Fetching split train-other-500...
Extracting log mel filter bank features...
100%|██████████| 148688/148688 [18:21<00:00, 135.01it/s]
Fetching split dev-clean...
Extracting log mel filter bank features...
100%|██████████| 2703/2703 [00:10<00:00, 256.36it/s]
Fetching split dev-other... 
Extracting log mel filter bank features... 
100%|██████████| 2864/2864 [00:07<00:00, 371.37it/s] 
Fetching split test-clean...  
Extracting log mel filter bank features...  
100%|██████████| 2620/2620 [00:08<00:00, 327.50it/s]    
Fetching split test-other...    
Extracting log mel filter bank features...   
100%|██████████| 2939/2939 [00:07<00:00, 378.47it/s] 
Extracting log mel filter bank features...
100%|██████████| 2939/2939 [00:07<00:00, 378.47it/s]
ZIPing features...
Traceback (most recent call last):
  File "examples/speech_to_text/prep_librispeech_data.py", line 119, in <module>
    main()
  File "examples/speech_to_text/prep_librispeech_data.py", line 115, in main
    process(args)
  File "examples/speech_to_text/prep_librispeech_data.py", line 60, in process
    create_zip(feature_root, zip_path)
  File "/home/students/mai/joeynmt-aug/fairseq/examples/speech_to_text/data_utils.py", line 104, in create_zip
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_STORED) as f:
  File "/home/students/mai/miniconda3/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'ls_root/fbank80.zip'
```

#### What have you tried?

- Tried installing fairseq by using pip, as well as cloning the repository as instructed in the README.
- Tried both the master branch, as well as the v0.10.1 branch. 
- Tried copying a `fbank80.zip` file from a colleague to my `$LS_ROOT`

Same error for all of the above.

#### What's your environment?

 - fairseq Version v0.10.1, as well as master
 - PyTorch Version 1.7.0+cu101
 - OS: Linux (Debian based cluster server)
 - How I installed fairseq: Both `pip install fairseq`, as well as from source as instructed in the README. Also checked out both master branch, as well as v0.10.1 branch.
 - Build command I used (when compiling from source):
```
git clone https://github.com/pytorch/fairseq
cd fairseq
# git checkout v0.10.1
pip install --editable ./
```
 - Python version: 3.8.5 (installed through miniconda)
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Nvidia GTX 1080 Ti, accessed on a computing cluster at my university through slurm
 - Any other relevant information: Please let me know if I'm missing anything.

Any help would be much appreciated.

**Comment by kahne** [comment]
Hi @Munzu , thanks for reporting the issue. Can you try using the absolute path for `ls_root`?

**Comment by kahne** [comment]
@Munzu I will close this issue for now. Let us know if you get other questions later.
