### ISSUE TITLE
Fairseq without GPU

### ISSUE THREAD

**Issue by gleidsonh** [pytorch/fairseq#2948]
Is it possible to use fairseq without GPU?

I don't have GPU in my computer, so I just want to test fairseq with done models, but I got some errors about cuda.

I don't know if I did something wrong or if it's really impossible to use without GPU.

**Comment by brookman** [comment]
Somebody managed to run the M2M-100 models on a CPU. It (needs >=64GB RAM and inference takes more than 10 minutes.
See: [https://medium.com/@twilightdema_14017/running-fairseq-m2m-100-machine-translation-model-in-cpu-only-environment-27ca4da39a1e](https://medium.com/@twilightdema_14017/running-fairseq-m2m-100-machine-translation-model-in-cpu-only-environment-27ca4da39a1e)

**Comment by WilliamTambellini** [comment]
And the 'small' models can also now run on CPU: 
```
model=418M_last_checkpoint.pt # or model=1.2B_last_checkpoint.pt
fairseq-generate  data_bin --batch-size 1 --cpu  --device-id 0 --path $model \
 --fixed-dictionary ~/Downloads/m2m/model_dict.128k.txt  -s de -t fr  --remove-bpe 'sentencepiece'  --beam 5 \
    --task translation_multi_simple_epoch    --lang-pairs ~/Downloads/m2m/language_pairs.txt \
    --decoder-langtok --encoder-langtok src  --gen-subset test  --dataset-impl mmap \
    --distributed-world-size 1 --distributed-no-spawn --pipeline-model-parallel --pipeline-chunks 1 
```
