### ISSUE TITLE
Any plan releases mBART50?

### ISSUE THREAD

**Issue by SunbowLiu** [pytorch/fairseq#2950]
## 🚀 Feature Request
Release pre-trained [mBART50](https://arxiv.org/pdf/2008.00401v1.pdf) checkpoint.

### Motivation
mBART25 is a very nice pre-trained model for downstream tasks, e.g., machine translation and parallel corpus mining. As ACL21's deadline is approaching, many NLP researchers could hardly wait to conduct experiments on the more powerful mBART50. Do you have any exact date for releasing mBART50 and then we can accordingly adjust our research plan. 

@huihuifan @MultiPath @ngoyal2707 Thank you very much!

**Comment by SunbowLiu** [comment]
@tangyuq @chtran @xianxl

**Comment by devgunn** [comment]
is there any updates on the mBART50 model releasing?

**Comment by tangyuq** [comment]
Update: It is now released at: https://github.com/pytorch/fairseq/tree/master/examples/multilingual#mbart50-models
