### ISSUE TITLE
Getting OOM system RAM when fine tuning MBart on TPU

### ISSUE THREAD

**Issue by mani-rai** [pytorch/fairseq#2954]
I am need to this industry and little I know. I am tryining to fine tune MBart of TPU colab pro with distributed --distributed-world-size 8. It has 24GB system memory and TPU v2. The model size is around 5.5GB with 600M parameter. I can't understand why I am getting system memory OOM issue no matter how much I minimize batch size?

At the moment, I am also fine tuning the same thing in 1 GPU colab pro with much higher batch size. Everything is fine.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.10.1
 - PyTorch Version (e.g., 1.0) 1.7
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source): pip install --editable fairseq
 - Python version: 3.6
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
TPU support is somewhat experiments currently. What command are you running? Most likely you are running out of TPU memory, not system memory, and need to lower the batch size further. Keep in mind that there is significant extra memory usage during training from things like optimizer state, activations, etc., it’s not just the model size.
