### ISSUE TITLE
Training Translation models using pipeline parallism with multi nodes and multi GPUs

### ISSUE THREAD

**Issue by zherowolf** [pytorch/fairseq#2957]
#### What is your question?
How can we training translation models using pipeline parallism with multi nodes and multi GPUs?

#### What have you tried?
I tried with the following command and it works well in one node and 4 gpus, just hope this issue can collect ideas about pipeline parallism training.

fairseq-train $TRAIN_DIR --arch transformer_base_pipeline_parallel ...... --distributed-world-size 4 --pipeline-model-parallel --pipeline-balance '[4,4,4,4]' --pipeline-devices '[0, 1, 2, 3]' --pipeline-chunks 4

#### What's your environment?
 - fairseq Version:0.10.0
 - PyTorch Version:1.6
 - OS (e.g., Linux):Linux
 - How you installed fairseq (`pip`, source): source
 - Python version:3.6
 - CUDA/cuDNN version:10.0
 - GPU models and configuration:V100

**Comment by myleott** [comment]
@shruti-bh are you able to add a brief section to the m2m-100 docs on how to use the pipeline parallel flags for training?
