### ISSUE TITLE
error when loading wav2vector model

### ISSUE THREAD

**Issue by wl-junlin** [pytorch/fairseq#2959]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
just run the give example of wav2vector, this error is caused by recent updats
2. See error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-7d1e8947ae92> in <module>
      3 
      4 cp = torch.load('wav2vec_large.pt')
----> 5 model = Wav2VecModel.build_model(cp['args'], task=None)
      6 model.load_state_dict(cp['model'])
      7 model.eval()

~/fairseq/fairseq/models/wav2vec/wav2vec.py in build_model(cls, cfg, task)
    166         """Build a new model instance."""
    167 
--> 168         model = Wav2VecModel(cfg)
    169         logger.info(model)
    170         return model

~/fairseq/fairseq/models/wav2vec/wav2vec.py in __init__(self, cfg)
    176         offset = cfg.offset
    177 
--> 178         if cfg.activation == "relu":
    179             activation = nn.ReLU()
    180         elif cfg.activation == "gelu":

AttributeError: 'Namespace' object has no attribute 'activation'

---------------------------------------------------------------------------

#### Code sample
---------------------------------------------------------------------------

import torch
from fairseq.models.wav2vec import Wav2VecModel

cp = torch.load('/path/to/wav2vec.pt')
model = Wav2VecModel.build_model(cp['args'], task=None)
model.load_state_dict(cp['model'])
model.eval()

wav_input_16khz = torch.randn(1,10000)
z = model.feature_extractor(wav_input_16khz)
c = model.feature_aggregator(z)

---------------------------------------------------------------------------

### Environment

 - fairseq Version (0.1.0):
 - PyTorch Version (1.7.0)
 - OS (ubuntu18.04):
 - How you installed fairseq (git clone https://github.com/pytorch/fairseq
cd fairseq
pip install --editable ./):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1

**Comment by alexeib** [comment]
can you load the model like this for now?
```
import fairseq

cp = '/path/to/checkpoint.pt'
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp])
model = model[0]
```

i'll update the script to do this soon

**Comment by wl-junlin** [comment]
> can you load the model like this for now?
> 
> ```
> import fairseq
> 
> cp = '/path/to/checkpoint.pt'
> model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp])
> model = model[0]
> ```
> 
> i'll update the script to do this soon
