### ISSUE TITLE
MBart 'NoneType' object has no attribute 'task' (Potential Bug)

### ISSUE THREAD

**Issue by mani-rai** [pytorch/fairseq#2962]
I was following [this mbart] (https://github.com/pytorch/fairseq/blob/dea66cc294a18dd4d9e59aa0af8d51f951e83884/examples/mbart/README.md) fine tuning guide. I followed almost exactly just the update frequency, max tokens, and source and target language changed. The model is trained fine generating checkpoint_best.pt.

However, when I tried to use it with generate fairseq cli to measure sacrebleu. I am getting NoneType object has no attribute task.

> Traceback (most recent call last):
  File "fairseq/fairseq_cli/generate.py", line 383, in <module>
    cli_main()
  File "fairseq/fairseq_cli/generate.py", line 379, in cli_main
    main(args)
  File "fairseq/fairseq_cli/generate.py", line 41, in main
    return _main(args, sys.stdout)
  File "fairseq/fairseq_cli/generate.py", line 94, in _main
    num_shards=args.checkpoint_shard_count,
  File "/content/fairseq/fairseq/checkpoint_utils.py", line 257, in load_model_ensemble
    num_shards,
  File "/content/fairseq/fairseq/checkpoint_utils.py", line 280, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/content/fairseq/fairseq/checkpoint_utils.py", line 233, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/content/fairseq/fairseq/checkpoint_utils.py", line 421, in _upgrade_state_dict
    state["args"].task = "translation"
AttributeError: 'NoneType' object has no attribute 'task'

I followed almost exactly as mentioned in guide. But still having problem. I used following command:
`python generate.py "postprocessed" --path "checkpoint_best.pt" --task translation_from_pretrained_bart --gen-subset test -t ne_NP -s en_XX --bpe 'sentencepiece' --sentencepiece-model "mbart.cc25/sentence.bpe.model" --sacrebleu --remove-bpe 'sentencepiece' --batch-size 32 --langs "ar_AR,cs_CZ,de_DE,en_XX,es_XX,et_EE,fi_FI,fr_XX,gu_IN,hi_IN,it_IT,ja_XX,kk_KZ,ko_KR,lt_LT,lv_LV,my_MM,ne_NP,nl_XX,ro_RO,ru_RU,si_LK,tr_TR,vi_VN,zh_CN"`
#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.10.1
 - PyTorch Version (e.g., 1.0) 1.7
 - OS (e.g., Linux): Colab
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source): pip install --editable .
 - Python version: 3.6
 - CUDA/cuDNN version:
 - GPU models and configuration: V100
 - Any other relevant information:

**Comment by mani-rai** [comment]
Found the problem. I fine tuned mbart from different commit and used 0.10.1 for evaluation. I reinstalled toolkit of used commit version. Everything working like a charm.

**Comment by S-GeGe** [comment]
Did you reinstall fairseq? What about that version? @mani-rai
