### ISSUE TITLE
space character is replaced by <unk> token (wav2vec 2.0)

### ISSUE THREAD

**Issue by LamyaMohamed** [pytorch/fairseq#2964]
Hello,
I used wav2vec's pre-trained model for fine-tuning with librispeech, then tested it, and everything worked fine. However, when I trained the model and tested it against different language (Arabic), I got a really high WER, and when I tested some audio files I found out that the space character is replaced by <unk> token. 
My transcript files are written in the same way as librispeech's. For dict.ltr.txt file, I put all the characters that appeared in the  transcripts (except for the space character) and I put a random number in front of each character.

How can I fix this problem?

Thank you

**Comment by LamyaMohamed** [comment]
The problem is solved, I forgot to add `|` sperator in `dict.ltr.txt `. This answer helped me [here](https://github.com/pytorch/fairseq/issues/2493#issuecomment-719915281)

**Comment by abkw** [comment]
I'm just wondering, did you reverse the Arabic text on the transcript file or did you use it as it is since Arabic is a right-to-left language. I'm doing a project on Arabic and it would really be helpful if you could share how you did it
