### ISSUE TITLE
How can we get features from wav2vec 2.0

### ISSUE THREAD

**Issue by casssie-zhang** [pytorch/fairseq#2967]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

Hi, for wav2vec 2.0, how can I get pre-trained features like wav2vec?
https://github.com/pytorch/fairseq/tree/master/examples/wav2vec#pre-trained-models-1

My error ⬇️
/content/fairseq/fairseq/models/wav2vec/wav2vec2.py in __init__(self, cfg)
    244         self.mask_prob = cfg.mask_prob
    245         self.mask_selection = cfg.mask_selection
--> 246         self.mask_other = cfg.mask_other
    247         self.mask_length = cfg.mask_length
    248         self.no_mask_overlap = cfg.no_mask_overlap

AttributeError: 'Namespace' object has no attribute 'mask_other'

#### Code

```
import torch
from fairseq.models.wav2vec import Wav2Vec2Model

cp = torch.load('/content/pretrain_model/wav2vec_vox_new.pt')
model = Wav2Vec2Model.build_model(cp['args'], task=None)
model.load_state_dict(cp['model'])
model.eval()

wav_input_16khz = torch.randn(1,10000)
z = model.feature_extractor(wav_input_16khz)
c = model.feature_aggregator(z)
```
   

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 
 - PyTorch Version (e.g., 1.0) 1.7.0
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source): 
cd fairseq
pip install --editable ./
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1

**Comment by alexeib** [comment]
can you load it like this instead:
```
import fairseq

cp = '/content/pretrain_model/wav2vec_vox_new.pt'
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp])
model = model[0]
```

after that you can extract features from feature encoder in the way you tried it, or from the transformer by just doing a model forward (with mask=False and features_only=True). you may also want to try features from different layers of the model, but you need to make some changes to return results from each layer, here: https://github.com/pytorch/fairseq/blob/master/fairseq/models/wav2vec/wav2vec2.py#L764 and then also in the model forward()

**Comment by casssie-zhang** [comment]
> can you load it like this instead:
> 
> ```
> import fairseq
> 
> cp = '/content/pretrain_model/wav2vec_vox_new.pt'
> model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp])
> model = model[0]
> ```
> 
> after that you can extract features from feature encoder in the way you tried it, or from the transformer by just doing a model forward (with mask=False and features_only=True). you may also want to try features from different layers of the model, but you need to make some changes to return results from each layer, here: https://github.com/pytorch/fairseq/blob/master/fairseq/models/wav2vec/wav2vec2.py#L764 and then also in the model forward()

Thanks, it solves my issue!

**Comment by yygle** [comment]
I face a similar problem when trying to load wav2vec2 model here:
when I was loading xlsr_53_56k.pt:
Traceback (most recent call last):
  File "/data1/yangyuguang/pro100/speech_term_detecter-master/test_ideas/test_wav2vec.py", line 26, in <module>
    model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])
  File "/home/yangyuguang/anaconda3/envs/fairseq/lib/python3.6/site-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/yangyuguang/anaconda3/envs/fairseq/lib/python3.6/site-packages/fairseq/checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/home/yangyuguang/anaconda3/envs/fairseq/lib/python3.6/site-packages/fairseq/checkpoint_utils.py", line 420, in _upgrade_state_dict
    state["args"].task = "translation"
AttributeError: 'NoneType' object has no attribute 'task'
========================================================================
when I was loading wav2vec2_vox_960h.pt
Traceback (most recent call last):
  File "/data1/yangyuguang/pro100/speech_term_detecter-master/test_ideas/test_wav2vec.py", line 26, in <module>
    model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])
  File "/home/yangyuguang/anaconda3/envs/fairseq/lib/python3.6/site-packages/fairseq/checkpoint_utils.py", line 287, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, args=args)
  File "/home/yangyuguang/anaconda3/envs/fairseq/lib/python3.6/site-packages/fairseq/models/fairseq_model.py", line 98, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/yangyuguang/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Wav2VecCtc:
	size mismatch for w2v_encoder.proj.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in current model is torch.Size([512, 1024]).
	size mismatch for w2v_encoder.proj.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
(fairseq Version 0.10.1)

**Comment by alexeib** [comment]
you are trying to use it with a dictionary that has 32 symbols but it was trained with 512?

**Comment by yygle** [comment]
no, I guess it is because of the version of fairseq, I successfully done it with master branch, that is the inconsistence error of version 0.10

**Comment by timofeeva16tanya** [comment]
I face a similar problem when trying to load wav2vec2 model here:
when I was loading xlsr_53_56k.pt:
>>> c = model.feature_aggregator(z)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/lc/timofeeva/fairseq/anaconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Wav2Vec2Model' object has no attribute 'feature_aggregator'

**Comment by SolomidHero** [comment]
@timofeeva16tanya, your error and its traceback are not related to model loading. Wav2vec2.0 model has no attribute `feature_aggregate` comparing to wav2vec model. To extract features you can use method suggested above: via model forward (with mask=False and features_only=True).

**Comment by timofeeva16tanya** [comment]
Thank you for answer

**Comment by stonelazy** [comment]
Have been facing a same problem. Faced many compatibility issues. Turns out the reason was that pip source was not updated. I tried to [install and develop locally](https://github.com/pytorch/fairseq#requirements-and-installation). Then XLS43, wav2vec_large,wav2vec_small everything was working properly.

**Comment by roboticsai** [comment]
I'm getting this problem again. AttributeError: 'Wav2Vec2Model' object has no attribute 'feature_aggregator' 
Even after i tried the solution described in here. 
Environment:
1. Ubuntu 20.04
2. fairseq master 
3. python 3.6
```
import fairseq
import torch
import soundfile as sf

cp = '/home/robot/Downloads/wav2vec_small.pt'
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp])
model = model[0]

audio_input = torch.randn(1,10000)
z = model.feature_extractor(audio_input)
c = model.feature_aggregator(z)
```
s

**Comment by alexeib** [comment]
the example you are trying is for wav2vec 1.0 not 2.0. i dont currently have an example for extracting w2v 2.0 features but it should be pretty easy to adapt the code above to make it work

**Comment by Kamilbentounes** [comment]
@alexeib I fintuned the base model 1h on my own data without language model. Now that I have my checkpoints_best.pt, I don't know how to make prediction with. I used the following code to load my model:
```
import fairseq
import torch
import soundfile as sf

cp = '/path/to/best_checkpoint.pt'
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp])
model = model[0]
```

Then:
```
audio_input, _  = sf.read(fileName) 
z = model.feature_extractor(audio_input)
c = model.feature_aggregator(z)
```
I got the following error `AttributeError: 'Wav2VecCtc' object has no attribute 'feature_extractor'`. I understand that `feature_extractor` method no longer exists for Wav2vec2.0 but I don't know how can I run inference ? 

I tested `predict = model.forward(audio_input)` and `predict = model(audio_input)` but get the following error `TypeError: forward() takes 1 positional argument but 2 were given` 

Can you please help me ?

**Comment by alexeib** [comment]
can you take a look at examples and use infer.py to make predictions?

**Comment by happypanda5** [comment]
Hello @alexeib 

Can you please guide me why one needs **feature_aggregator** after **feature_extractor**? 

I am unable to find a good reason to use the aggregator. I don't think it changes the dimensions of the features. Thanks

`audio_input, _  = sf.read(fileName) 
z = model.feature_extractor(audio_input)
c = model.feature_aggregator(z)`
