### ISSUE TITLE
How to solve the bug in using average_model ?

### ISSUE THREAD

**Issue by KelleyYin** [pytorch/fairseq#297]
I prepare to average the last 10 models of transformer. However, there is a strange bug . My command and logs  as follow :
`python scripts/average_checkpoints.py --inputs checkpoints/transformer-big-data --output . --num-epoch-checkpoints 10`

averaging checkpoints:  ['checkpoints/transformer-big-data/checkpoint53.pt', 'checkpoints/transformer-big-data/checkpoint52.pt', 'checkpoints/transformer-big-data/checkpoint51.pt', 'checkpoints/transformer-big-data/checkpoint50.pt', 'checkpoints/transformer-big-data/checkpoint49.pt', 'checkpoints/transformer-big-data/checkpoint48.pt', 'checkpoints/transformer-big-data/checkpoint47.pt', 'checkpoints/transformer-big-data/checkpoint46.pt', 'checkpoints/transformer-big-data/checkpoint45.pt', 'checkpoints/transformer-big-data/checkpoint44.pt']
Traceback (most recent call last):
  File "scripts/average_checkpoints.py", line 137, in <module>
    main()
  File "scripts/average_checkpoints.py", line 131, in main
    new_state = average_checkpoints(args.inputs)
  File "scripts/average_checkpoints.py", line 28, in average_checkpoints
    lambda s, _: torch.serialization.default_restore_location(s, 'cpu')
  File "/home/mmyin/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/mmyin/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'fairseq'

**Comment by edunov** [comment]
Did you run  "python setup.py build develop" ? 
Alternatively, you can also do:

PYTHONPATH=.  python scripts/average_checkpoints.py --inputs checkpoints/transformer-big-data --output . --num-epoch-checkpoints 10

**Comment by KelleyYin** [comment]
Thanks a lot . The problem have been solved.

**Comment by LividWo** [comment]
Can anyone explain why prepending "PYTHONPATH=. " before the command can solve the problem? I am facing the same problem with the stable release 0.9.0
Or explain a bit why the problem occurs so I can fix it.
many thanks~ @myleott @edunov
