### ISSUE TITLE
what is the most appropriate way to add customized position encoding

### ISSUE THREAD

**Issue by FTD007** [pytorch/fairseq#2970]
I wonder what is the best way to add in the customized positional encoding? stored in one other binary file and read it somewhere?

**Comment by myleott** [comment]
Sorry it’s not clear what you mean. We support [loading pretrained word embeddings](https://github.com/pytorch/fairseq/blob/f732b403ec15244c41a24b9e28d6c5a411a511df/fairseq/models/transformer.py#L234-L238), but if you want to use pretrained positional embeddings you’ll need to modify the code to support that. Probably here for the Encoder and a bit lower in the same file for the decoder: https://github.com/pytorch/fairseq/blob/f732b403ec15244c41a24b9e28d6c5a411a511df/fairseq/models/transformer.py#L328-L337

**Comment by FTD007** [comment]
> Sorry it’s not clear what you mean. We support [loading pretrained word embeddings](https://github.com/pytorch/fairseq/blob/f732b403ec15244c41a24b9e28d6c5a411a511df/fairseq/models/transformer.py#L234-L238), but if you want to use pretrained positional embeddings you’ll need to modify the code to support that. Probably here for the Encoder and a bit lower in the same file for the decoder:
> 
> https://github.com/pytorch/fairseq/blob/f732b403ec15244c41a24b9e28d6c5a411a511df/fairseq/models/transformer.py#L328-L337

I want to train a sequence model using different position encoding (domain specific). So its not learned position embedding nor Sinusoidal embedding. Is there a way to either pack with preporcess binary or it need to be somehow read from other files?
