### ISSUE TITLE
How to export wav2vec 2.0 pretrained model to ONNX and run it in ONNX Runtime

### ISSUE THREAD

**Issue by Denovitz** [pytorch/fairseq#2972]
Is it possible to do it?
Will we have performance improvements after that?

**Comment by myleott** [comment]
I don’t know if we’ve tried that, but cc @alexeib to confirm.

**Comment by alexeib** [comment]
i havent tried it, but in theory it should work because its just a bunch of convolutions followed by a vanilla transformer
