### ISSUE TITLE
why the pretrained transformer model size is much bigger than original paper?

### ISSUE THREAD

**Issue by ZhaoQianfeng** [pytorch/fairseq#2974]
I download the pretrained [transformer.wmt16.en-de](https://github.com/pytorch/fairseq/blob/master/examples/translation/README.md) model from fairseq for machince translation. I unzipped the file and found `model.pt` 2.5G. When I use fairseq-interactive to do inference, it occupy about 1599MB GPU ram.

The model is bigger than I expected. at original paper  [attention is all you need](https://arxiv.org/pdf/1706.03762.pdf), the base model has 63M parameters , so it's size should be 63M\*4bytes, about 252MB. The transformer-big has 213M parameters ,so it's size should be 213M\*4bytes, about 852MB.

Why the fairseq pretrained transformer model is much bigger , could someone tell me where is the problem?

**Comment by myleott** [comment]
It’s the big model (~210M params) and the checkpoint file also contains the optimizer state, which is 2x larger than the model size due to the Adam buffers. These can be removed by torch.load’ing the checkpoint and deleting the “last_optimizer_state” key.
