### ISSUE TITLE
Can I build&register the criterion and task outside fairseq document

### ISSUE THREAD

**Issue by zjw1990** [pytorch/fairseq#2975]
Since I need to run fairseq on server, there's permission issues when I need to add those model features, like model.py, criterion.py and task.py, into a specific document. 

I saw a help that I can specify a --user-dir but only for register models. Yet most models are associate with new criterions and tasks. Therefore I am wondering whether there is any way to split all my code(including criterion code, model code, task) outside fairseq. Which makes more sence as this is a package instead of kind like changing source code :)

**Comment by myleott** [comment]
Yes, this is what --user-dir is for. You can look at examples/speech_recognition to see how you can package various components outside of the fairseq source directory. Several other examples in the examples/ directory also rely on user-dir.
