### ISSUE TITLE
Cannot download IWSLT datasets from wit3.fbk.eu

### ISSUE THREAD

**Issue by zml24** [pytorch/fairseq#2984]
When trying translation examples, I found that `prepare-iwslt14.sh` and `prepare-iwslt17-multilingual.sh` both failed.
After that, I tried to open wit3.fbk.eu but failed again.
I want to train a model from scratch, so how can I download the IWSLT datasets?

**Comment by ghlai9665** [comment]
I think I'm having a similar issue here. Running 

`train_data, valid_data, test_data = IWSLT.splits(exts = ('.de', '.en'),
                                                 fields = (SRC, TRG))` 

on Google Colab leads to this error:

```
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f9467921c18>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
MaxRetryError: HTTPSConnectionPool(host='wit3.fbk.eu', port=443): Max retries exceeded with url: /archive/2016-01//texts/de/en/de-en.tgz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9467921c18>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPSConnectionPool(host='wit3.fbk.eu', port=443): Max retries exceeded with url: /archive/2016-01//texts/de/en/de-en.tgz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9467921c18>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by kriscroes** [comment]
I'm getting the same issue, unable to download the IWSLT'14 dataset. Did you solve this?

**Comment by zml24** [comment]
> I'm getting the same issue, unable to download the IWSLT'14 dataset. Did you solve this?

Not yet.

**Comment by ghlai9665** [comment]
For those of you still stuck, @zml24 , there is a new url available for downloading IWSLT at 

https://drive.google.com/uc?id=1l5y6Giag9aRPwGtuZHswh3w5v3qEz8D8

Note that the link will download an IWSLT tgz containing the tgzs for all the languages. You still need to extract the specific language tgz you want. Once you extract the language-specific tgz, everything else should be the same as before.

I fixed this for Torchtext in a similar issue (https://github.com/pytorch/text/pull/1115/files) as a reference.

**Comment by pritamdamania87** [comment]
@ghlai9665 Thanks for providing this alternative, although I only found the train files (ex: train.de) in that gz and not the valid/test files.

**Comment by ghlai9665** [comment]
> @ghlai9665 Thanks for providing this alternative, although I only found the train files (ex: train.de) in that gz and not the valid/test files.

Which language pairs are you looking at? At least for de-en language pairs, the entire dataset should be identical to what was available previously (i.e. training, valid, test). I am sure of this because I have checked the valid/test files myself.

Also the new download link is provided by the same wit3.fbk.eu website, just organized differently.

**Comment by pritamdamania87** [comment]
@ghlai9665 This is what the de-en directory looks like for me (there is only a train.en file and no test/valid files):

```
IWSLT16.TED.dev2010.de-en.de.xml	IWSLT16.TED.tst2011.de-en.de.xml	IWSLT16.TED.tst2013.de-en.de.xml	IWSLT16.TEDX.dev2012.de-en.de.xml	IWSLT16.TEDX.tst2014.de-en.de.xml	train.tags.de-en.de
IWSLT16.TED.dev2010.de-en.en.xml	IWSLT16.TED.tst2011.de-en.en.xml	IWSLT16.TED.tst2013.de-en.en.xml	IWSLT16.TEDX.dev2012.de-en.en.xml	IWSLT16.TEDX.tst2014.de-en.en.xml	train.tags.de-en.en
IWSLT16.TED.tst2010.de-en.de.xml	IWSLT16.TED.tst2012.de-en.de.xml	IWSLT16.TED.tst2014.de-en.de.xml	IWSLT16.TEDX.tst2013.de-en.de.xml	README
IWSLT16.TED.tst2010.de-en.en.xml	IWSLT16.TED.tst2012.de-en.en.xml	IWSLT16.TED.tst2014.de-en.en.xml	IWSLT16.TEDX.tst2013.de-en.en.xml	train.en
```

**Comment by myleott** [comment]
I had a backup of the original data archive and uploaded it here: http://dl.fbaipublicfiles.com/fairseq/data/iwslt14/de-en.tgz

I'll update the docs with the new link.

**Comment by ghlai9665** [comment]
> @ghlai9665 This is what the de-en directory looks like for me (there is only a train.en file and no test/valid files):
> 
> ```
> IWSLT16.TED.dev2010.de-en.de.xml	IWSLT16.TED.tst2011.de-en.de.xml	IWSLT16.TED.tst2013.de-en.de.xml	IWSLT16.TEDX.dev2012.de-en.de.xml	IWSLT16.TEDX.tst2014.de-en.de.xml	train.tags.de-en.de
> IWSLT16.TED.dev2010.de-en.en.xml	IWSLT16.TED.tst2011.de-en.en.xml	IWSLT16.TED.tst2013.de-en.en.xml	IWSLT16.TEDX.dev2012.de-en.en.xml	IWSLT16.TEDX.tst2014.de-en.en.xml	train.tags.de-en.en
> IWSLT16.TED.tst2010.de-en.de.xml	IWSLT16.TED.tst2012.de-en.de.xml	IWSLT16.TED.tst2014.de-en.de.xml	IWSLT16.TEDX.tst2013.de-en.de.xml	README
> IWSLT16.TED.tst2010.de-en.en.xml	IWSLT16.TED.tst2012.de-en.en.xml	IWSLT16.TED.tst2014.de-en.en.xml	IWSLT16.TEDX.tst2013.de-en.en.xml	train.en
> ```

This is expected. Your valid and test files are right there. The default valid_filenames should be `('IWSLT16.TED.tst2013.de-en.de', 'IWSLT16.TED.tst2013.de-en.en')` and test_filenames are `('IWSLT16.TED.tst2014.de-en.de', 'IWSLT16.TED.tst2014.de-en.en')`. Exactly the same as before the link broke.

**Comment by ludwigwittgenstein2** [comment]
> 

Where do you actually extract this? 
I am confused.
