### ISSUE TITLE
Print Alignment at word level 

### ISSUE THREAD

**Issue by Nagoudi** [pytorch/fairseq#2987]
## ❓ Questions and Help
Hello, 

I used the ENG-GER Fairseq model with the interactive function. I'm able to print the alignment between the BPE token using **--print-alignment** (please see the example below).
However, I want it to print the alignment between the original word in each sentence.

#### Code

```
S-104	 the weeknd may be a god or the new age michael jackson
H-104	-0.3077760338783264	das wochenende kann ein gott sein oder das neue zeitalter michael jackson
A-104	1-0 1-1 2-2 4-3 7-4 7-5 8-6 5-7 9-8 13-9 11-10 12-11 12-12 9-13 13-14 14-15 15-16 16-17 17-18

```

Any suggestion would be appreciated. 

Thanks

**Comment by Samyak005** [comment]
I am facing the same problem. any solutions?
