### ISSUE TITLE
[New]Difficulties for reproduce XSUM results with BART

### ISSUE THREAD

**Issue by monologue1107** [pytorch/fairseq#2990]
I have tried CNNDM datasets with BART before, which has a great performance.
However, when I tried the Xsum datasets, the ROUGE-1 result only have 23.8 (45.14 was claimed in paper). But I don't know where I am wrong.
My actions are below:
1、I download the Xsum datasets and divide them into 6 files in [train/val/test].[source/target]
2、I run the bpe and binary process which is exactly the same as what I did on CNNDM datasets.
3、I download the `bart.large.xsum` which is already fine-tuned in your page.
4、I run the inference script as you provided with changes `Use beam=6, lenpen=1.0, max_len_b=60, min_len=10 for Xsum Generation`
5、I run code to get the ROUGE result
```
cat xsum_baseline.hypo | java edu.stanford.nlp.process.PTBTokenizer -ioFileList -preserveLines > xsum_baseline.hypo.tokenized
cat test.target | java edu.stanford.nlp.process.PTBTokenizer -ioFileList -preserveLines > test.hypo.target
files2rouge xsum_baseline.hypo.tokenized test.hypo.target
```
-------------------------------
Now I wonder where I did wrong or which step I missed to get this awful result.
There are other issues I met during the reproduction:
1、When I run the inference script in step 4, I faced an error like "cannot find file xsum/dict.document.txt". I find it was named "dict.[source/target].txt" in CNNDM datasets, so I just move the dict.[document/summary].txt file in `bart.large.xsum` to xsum folder, then the error disappears.
2、I found that current inference result are likely much longer than the reference summary. For example, the reference summary is
 `Gaza crisis: Tel Aviv adjusts to life in rocket-range`
, while the generated result is 
`Residents of the Israeli city of Tel Aviv are returning to work after a weekend of heightened security following a series of rocket attacks from the Gaza Strip, the BBC has learned.`
I wonder if hyperparameter in inference script (`max_len_b=60, min_len=10`) are much too large for Xsum datasets. But I also have seen other people have reproduce this performance. So I don't know how to do with it. Can you help?

my inference script is below if you need:

```
import torch
from fairseq.models.bart import BARTModel
bart = BARTModel.from_pretrained(
    'bart.large.xsum/',
    checkpoint_file='model.pt',
    data_name_or_path='xsum-bin'
)

bart.cuda()
bart.eval()
bart.half()
count = 1
bsz = 16
with open('xsum/test.source') as source, open('xsum/xsum_baseline.hypo', 'w') as fout:
    sline = source.readline().strip()
    slines = [sline]
    for sline in source:
        if count % bsz == 0:
            with torch.no_grad():
                hypotheses_batch = bart.sample(slines, beam=6, lenpen=1.0, max_len_b=60, min_len=10, no_repeat_ngram_size=3)

            for hypothesis in hypotheses_batch:
                fout.write(hypothesis + '\n')
                fout.flush()
            slines = []

        slines.append(sline.strip())
        count += 1
    if slines != []:
        hypotheses_batch = bart.sample(slines, beam=6, lenpen=1.0, max_len_b=60, min_len=10, no_repeat_ngram_size=3)
        for hypothesis in hypotheses_batch:
            fout.write(hypothesis + '\n')
            fout.flush()
```

**Comment by monologue1107** [comment]
@myleott @alexeib @lematt1991 @huihuifan @tangyuq

**Comment by cece00** [comment]
I wonder if this problem is solved, because I come into nearly the same problem on CNN-DM dataset. If yes, could you please tell me the solution? 
With all my best.

**Comment by Ricardokevins** [comment]
Hey man, I meet the same problem. can you tell me how you solve the problem? (any suggestion is great appreciate!!!)
