### ISSUE TITLE
fairseq-preprocess with transformer.wmt19.de-en model produced many <unk>

### ISSUE THREAD

**Issue by junwen-austin** [pytorch/fairseq#2993]
## ❓ Questions and Help
I am using `transformer.wmt19.de-en` model to back translate hundreds of thousands of text. To speed up translation, I followed the recommendation of using fairest-preprocess first:

```
fairseq-preprocess
        --source-lang en
        --target-lang de
       --srcdict "$MODEL_PATH/dict.en.txt"
       --tgtdict "$MODEL_PATH/dict.de.txt"
       --destdir $DESTDIR
       --bpe fastbpe
       --testpref $SOURCE
       --only-source
       --tokenizer moses
```

and I am seeing more than 20% of `<unk>` and I thought this happened probably because I did not apply bpe, as suggested in #2299 

Could someone suggest how to apply that in the fairseq-preprocess as I do not see this option in the command line tool. Thanks so much!

I am using fairseq 0.10.0 and torch 1.6 thanks.

**Comment by myleott** [comment]
Correct, you need to apply BPE before calling fairseq-preprocess. That model uses fastBPE. You can use the tools there to preprocess the input and then pass it to fairseq: https://github.com/glample/fastBPE

**Comment by junwen-austin** [comment]
@myleott Thanks for getting back to me quickly.
