### ISSUE TITLE
Installing wav2vec docker container

### ISSUE THREAD

**Issue by rnehrboss** [pytorch/fairseq#3007]
Using:  docker build -t wav2vec2 -f wav2letter.Dockerfile .

Output:
Sending build context to Docker daemon 11.84 GB
Step 1/12 : FROM wav2letter/wav2letter:cpu-latest
cpu-latest: Pulling from wav2letter/wav2letter
5bed26d33875: Pull complete
f11b29a9c730: Pull complete
930bda195c84: Pull complete
78bf9a5ad49e: Pull complete
a3fe9eb161b7: Pull complete
1578aaade1c0: Pull complete
c1ff967ad7e2: Pull complete
37e8cb0535ee: Pull complete
875254d2e7d8: Pull complete
Digest: sha256:6f470c3c42f0688143af1f51bfecb70a49c285b16e69100fe702525a1e404353
Status: Downloaded newer image for wav2letter/wav2letter:cpu-latest
 ---> b6d696266985
Step 2/12 : ENV USE_CUDA 0
 ---> Running in e9331b3107a0
 ---> a349d881a17f
Removing intermediate container e9331b3107a0
Step 3/12 : ENV KENLM_ROOT_DIR /root/kenlm
 ---> Running in 5c915ca50364
 ---> 546458793b2c
Removing intermediate container 5c915ca50364
Step 4/12 : ENV LD_LIBRARY_PATH /opt/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64:$LD_IBRARY_PATH
 ---> Running in 1ad70137c17e
 ---> ae8072ed934c
Removing intermediate container 1ad70137c17e
Step 5/12 : WORKDIR /root/wav2letter/bindings/python
 ---> dec7bc3d8620
Removing intermediate container 313cd7bd0873
Step 6/12 : RUN TMPDIR=/data/mydir/ pip install --upgrade pip && pip install --cache-dir=/data/vincents/ --build /data/mydir/ editdistance soundfile packaging && pip install -e .
 ---> Running in d4d0f1f80563
Collecting pip
  Downloading pip-20.3.1-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-20.3.1
DEPRECATION: The -b/--build/--build-dir/--build-directory option is deprecated and has no effect anymore. pip 21.1 will remove support for this functionality. A possible replacement is use the TMPDIR/TEMP/TMP environment variable, possibly combined with --no-clean. You can find discussion regarding this at https://github.com/pypa/pip/issues/8333.
Collecting editdistance
  Downloading editdistance-0.5.3-cp36-cp36m-manylinux1_x86_64.whl (178 kB)
Collecting packaging
  Downloading packaging-20.7-py2.py3-none-any.whl (35 kB)
Collecting soundfile
  Downloading SoundFile-0.10.3.post1-py2.py3-none-any.whl (21 kB)
Collecting cffi>=1.0
  Downloading cffi-1.14.4-cp36-cp36m-manylinux1_x86_64.whl (401 kB)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Installing collected packages: pycparser, pyparsing, cffi, soundfile, packaging, editdistance
Successfully installed cffi-1.14.4 editdistance-0.5.3 packaging-20.7 pycparser-2.20 pyparsing-2.4.7 soundfile-0.10.3.post1
Obtaining file:///root/wav2letter/bindings/python
Installing collected packages: wav2letter
  Running setup.py develop for wav2letter
Successfully installed wav2letter
 ---> 6edba40c0410
Removing intermediate container d4d0f1f80563
Step 7/12 : WORKDIR /root
 ---> 77f27bee642a
Removing intermediate container dcd5fd939215
Step 8/12 : RUN git clone https://github.com/pytorch/fairseq.git
 ---> Running in 2d1d35adbca4
Cloning into 'fairseq'...
 ---> 27394758031f
Removing intermediate container 2d1d35adbca4
Step 9/12 : RUN mkdir data
 ---> Running in 923a562d1231
 ---> 0c46a042c611
Removing intermediate container 923a562d1231
Step 10/12 : COPY src/recognize.py /root/fairseq/examples/wav2vec/recognize.py
lstat src/recognize.py: no such file or directory

__________________________________________
Anyone have some suggestions?

Thanks!

**Comment by mironnn** [comment]
you have no `src/recognize.py` that should be copied inside the docker.
src/recognize.py - it is your own code, it is not a part of fairseq.

As I saw [here](https://github.com/pytorch/fairseq/issues/2651) there was a [guy](https://github.com/sooftware), who wrote this recognize.py
Check out the provided link to the issue, you'll find this recognize.py.
