### ISSUE TITLE
Train on gpu - about 1 day to 7 epochs

### ISSUE THREAD

**Issue by ShiraKadosh** [pytorch/fairseq#301]
Hi,
I'm training fair-seq with the following parameters:
PYTHONPATH=$FAIRSEQPY:$PYTHONPATH CUDA_VISIBLE_DEVICES="0,1,2" python3.5 $FAIRSEQPY/train.py --max-tokens 2500 --save-dir $OUT_DIR --encoder-embed-dim 500 --encoder-embed-path $EMBED_PATH --decoder-embed-dim 500 --decoder-embed-path $EMBED_PATH --decoder-out-embed-dim 500 --dropout 0.2 --clip-norm 0.1 --lr 0.001 --min-lr 1e-4 --encoder-layers '[(1024,3)] * 7' --decoder-layers '[(1024,3)] * 7' --momentum 0.99 --max-epoch 100 --batch-size 32 --no-progress-bar --seed $SEED $DATA_BIN_DIR

It takes 1 day for 7 epochs, using gpu - GRID K2.
how can I accelerate the train? tried with --max-tokens 4000 but got out of memory error, the max I can use is 2500

**Comment by ShiraKadosh** [comment]
Adding logs:
Namespace(arch='fconv', batch_size=32, clip_norm=0.1, data='processed/bin', decoder_attention='True', decoder_embed_dim=500, decoder_embed_path='/mlconvgec2018/models/embeddings/wiki_model.vec', decoder_layers='[(1024,3)] * 7', decoder_out_embed_dim=500, dropout=0.2, encoder_embed_dim=500, encoder_embed_path='/mlconvgec2018/models/embeddings/wiki_model.vec', encoder_layers='[(1024,3)] * 7', force_anneal=0, label_smoothing=0, log_interval=1000, lr=0.001, lrshrink=0.1, max_epoch=100, max_positions=1024, max_tokens=2500, min_lr=0.0001, model='fconv', momentum=0.99, no_epoch_checkpoints=False, no_progress_bar=True, no_save=False, restore_file='checkpoint_last.pt', sample_without_replacement=0, save_dir='models/mlconv_embed/new_model1000/', save_interval=-1, seed=1000, source_lang=None, target_lang=None, test_batch_size=32, test_subset='test', train_subset='train', valid_batch_size=32, valid_script=None, valid_subset='valid', weight_decay=0.0, workers=1)
| [src] dictionary: 21002 types
| [trg] dictionary: 19952 types
| processed/bin train 263012 examples
| processed/bin valid 87670 examples
| processed/bin test 87670 examples
| using 1 GPUs (with max tokens per GPU = 2500)
| model fconv
| Loading encoder embeddings from /mlconvgec2018/models/embeddings/wiki_model.vec
| Found 10838/21002 types in embeddings file.
| Loading decoder embeddings from /mlconvgec2018/models/embeddings/wiki_model.vec
| Found 10099/19952 types in embeddings file.
| epoch 001  1000 / 8223 loss=10.47 (11.93), wps=960, wpb=899, bsz=32, lr=0.001, clip=100%, gnorm=2.7883
| epoch 001  2000 / 8223 loss=9.68 (11.06), wps=960, wpb=900, bsz=32, lr=0.001, clip=100%, gnorm=2.2355
| epoch 001  3000 / 8223 loss=9.32 (10.61), wps=961, wpb=904, bsz=32, lr=0.001, clip=100%, gnorm=1.9547
| epoch 001  4000 / 8223 loss=9.26 (10.32), wps=961, wpb=907, bsz=32, lr=0.001, clip=100%, gnorm=1.8119
| epoch 001  5000 / 8223 loss=9.08 (10.09), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=1.7391
| epoch 001  6000 / 8223 loss=9.05 (9.90), wps=961, wpb=904, bsz=32, lr=0.001, clip=100%, gnorm=1.6923
| epoch 001  7000 / 8223 loss=8.16 (9.74), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=1.6742
| epoch 001  8000 / 8223 loss=8.26 (9.58), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=1.6721
| epoch 001 | train loss 9.54 | train ppl 744.92 | s/checkpoint    7748 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 1.6757
| epoch 001 | valid on 'valid' subset  1000 / 1311 loss=8.38
| epoch 001 | valid on 'valid' subset | valid loss 8.67 | valid ppl 407.31
| epoch 002  1000 / 8223 loss=7.92 (8.03), wps=961, wpb=904, bsz=32, lr=0.001, clip=100%, gnorm=1.8546
| epoch 002  2000 / 8223 loss=7.57 (7.86), wps=960, wpb=901, bsz=32, lr=0.001, clip=100%, gnorm=1.9593
| epoch 002  3000 / 8223 loss=7.13 (7.66), wps=961, wpb=908, bsz=32, lr=0.001, clip=100%, gnorm=2.0073
| epoch 002  4000 / 8223 loss=7.18 (7.47), wps=962, wpb=911, bsz=32, lr=0.001, clip=100%, gnorm=2.0399
| epoch 002  5000 / 8223 loss=7.25 (7.28), wps=961, wpb=907, bsz=32, lr=0.001, clip=100%, gnorm=2.0631
| epoch 002  6000 / 8223 loss=7.22 (7.11), wps=961, wpb=907, bsz=32, lr=0.001, clip=100%, gnorm=2.0794
| epoch 002  7000 / 8223 loss=4.32 (6.94), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=2.0962
| epoch 002  8000 / 8223 loss=5.85 (6.79), wps=961, wpb=905, bsz=32, lr=0.001, clip=100%, gnorm=2.1174
| epoch 002 | train loss 6.75 | train ppl 107.84 | s/checkpoint    7748 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 2.1233
| epoch 002 | valid on 'valid' subset  1000 / 1311 loss=5.61
| epoch 002 | valid on 'valid' subset | valid loss 6.08 | valid ppl 67.61
| epoch 003  1000 / 8223 loss=3.96 (5.45), wps=962, wpb=910, bsz=32, lr=0.001, clip=100%, gnorm=2.3681
| epoch 003  2000 / 8223 loss=6.59 (5.36), wps=963, wpb=915, bsz=32, lr=0.001, clip=100%, gnorm=2.4353
| epoch 003  3000 / 8223 loss=3.55 (5.25), wps=963, wpb=913, bsz=32, lr=0.001, clip=100%, gnorm=2.5041
| epoch 003  4000 / 8223 loss=3.27 (5.16), wps=963, wpb=915, bsz=32, lr=0.001, clip=100%, gnorm=2.5423
| epoch 003  5000 / 8223 loss=4.78 (5.06), wps=963, wpb=914, bsz=32, lr=0.001, clip=100%, gnorm=2.5660
| epoch 003  6000 / 8223 loss=3.28 (4.95), wps=962, wpb=911, bsz=32, lr=0.001, clip=100%, gnorm=2.5856
| epoch 003  7000 / 8223 loss=2.98 (4.86), wps=962, wpb=910, bsz=32, lr=0.001, clip=100%, gnorm=2.6137
| epoch 003  8000 / 8223 loss=3.04 (4.77), wps=961, wpb=905, bsz=32, lr=0.001, clip=100%, gnorm=2.6315
| epoch 003 | train loss 4.76 | train ppl 27.02 | s/checkpoint    7747 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 2.6400
| epoch 003 | valid on 'valid' subset  1000 / 1311 loss=4.06
| epoch 003 | valid on 'valid' subset | valid loss 4.54 | valid ppl 23.33
| epoch 004  1000 / 8223 loss=3.98 (4.04), wps=960, wpb=900, bsz=32, lr=0.001, clip=100%, gnorm=2.9029
| epoch 004  2000 / 8223 loss=4.03 (3.95), wps=960, wpb=902, bsz=32, lr=0.001, clip=100%, gnorm=2.8632
| epoch 004  3000 / 8223 loss=6.71 (3.88), wps=961, wpb=904, bsz=32, lr=0.001, clip=100%, gnorm=2.8605
| epoch 004  4000 / 8223 loss=4.07 (3.84), wps=960, wpb=902, bsz=32, lr=0.001, clip=100%, gnorm=2.8716
| epoch 004  5000 / 8223 loss=2.81 (3.78), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=2.8506
| epoch 004  6000 / 8223 loss=2.51 (3.73), wps=961, wpb=904, bsz=32, lr=0.001, clip=100%, gnorm=2.8546
| epoch 004  7000 / 8223 loss=2.43 (3.68), wps=960, wpb=903, bsz=32, lr=0.001, clip=100%, gnorm=2.8421
| epoch 004  8000 / 8223 loss=2.69 (3.64), wps=961, wpb=905, bsz=32, lr=0.001, clip=100%, gnorm=2.8275
| epoch 004 | train loss 3.62 | train ppl 12.33 | s/checkpoint    7748 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 2.8236
| epoch 004 | valid on 'valid' subset  1000 / 1311 loss=3.24
| epoch 004 | valid on 'valid' subset | valid loss 3.69 | valid ppl 12.94
| epoch 005  1000 / 8223 loss=2.17 (3.20), wps=959, wpb=897, bsz=32, lr=0.001, clip=100%, gnorm=2.7374
| epoch 005  2000 / 8223 loss=2.20 (3.14), wps=960, wpb=900, bsz=32, lr=0.001, clip=100%, gnorm=2.7204
| epoch 005  3000 / 8223 loss=3.52 (3.08), wps=960, wpb=899, bsz=32, lr=0.001, clip=100%, gnorm=2.6783
| epoch 005  4000 / 8223 loss=2.20 (3.06), wps=961, wpb=903, bsz=32, lr=0.001, clip=100%, gnorm=2.6938
| epoch 005  5000 / 8223 loss=3.03 (3.03), wps=960, wpb=901, bsz=32, lr=0.001, clip=100%, gnorm=2.6796
| epoch 005  6000 / 8223 loss=2.91 (2.99), wps=960, wpb=902, bsz=32, lr=0.001, clip=100%, gnorm=2.6866
| epoch 005  7000 / 8223 loss=3.03 (2.96), wps=960, wpb=902, bsz=32, lr=0.001, clip=100%, gnorm=2.6826
| epoch 005  8000 / 8223 loss=1.47 (2.93), wps=961, wpb=904, bsz=32, lr=0.001, clip=100%, gnorm=2.6741
| epoch 005 | train loss 2.92 | train ppl 7.59 | s/checkpoint    7748 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 2.6727
| epoch 005 | valid on 'valid' subset  1000 / 1311 loss=2.72
| epoch 005 | valid on 'valid' subset | valid loss 3.13 | valid ppl 8.78
| epoch 006  1000 / 8223 loss=1.97 (2.58), wps=966, wpb=923, bsz=32, lr=0.001, clip=100%, gnorm=2.5053
| epoch 006  2000 / 8223 loss=2.49 (2.64), wps=960, wpb=902, bsz=32, lr=0.001, clip=100%, gnorm=2.5882
| epoch 006  3000 / 8223 loss=3.20 (2.59), wps=959, wpb=899, bsz=32, lr=0.001, clip=100%, gnorm=2.5681
| epoch 006  4000 / 8223 loss=5.30 (2.55), wps=960, wpb=900, bsz=32, lr=0.001, clip=100%, gnorm=2.5398
| epoch 006  5000 / 8223 loss=2.08 (2.52), wps=960, wpb=901, bsz=32, lr=0.001, clip=100%, gnorm=2.5301
| epoch 006  6000 / 8223 loss=2.33 (2.50), wps=960, wpb=902, bsz=32, lr=0.001, clip=100%, gnorm=2.5360
| epoch 006  7000 / 8223 loss=2.29 (2.48), wps=961, wpb=904, bsz=32, lr=0.001, clip=100%, gnorm=2.5279
| epoch 006  8000 / 8223 loss=1.65 (2.45), wps=961, wpb=905, bsz=32, lr=0.001, clip=100%, gnorm=2.5129
| epoch 006 | train loss 2.45 | train ppl 5.45 | s/checkpoint    7748 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 2.5113
| epoch 006 | valid on 'valid' subset  1000 / 1311 loss=2.36
| epoch 006 | valid on 'valid' subset | valid loss 2.75 | valid ppl 6.72
| epoch 007  1000 / 8223 loss=1.45 (2.17), wps=959, wpb=895, bsz=32, lr=0.001, clip=100%, gnorm=2.3611
| epoch 007  2000 / 8223 loss=1.55 (2.20), wps=961, wpb=901, bsz=32, lr=0.001, clip=100%, gnorm=2.4208
| epoch 007  3000 / 8223 loss=2.17 (2.18), wps=959, wpb=897, bsz=32, lr=0.001, clip=100%, gnorm=2.4179
| epoch 007  4000 / 8223 loss=1.69 (2.16), wps=960, wpb=902, bsz=32, lr=0.001, clip=100%, gnorm=2.3983
| epoch 007  5000 / 8223 loss=2.38 (2.14), wps=960, wpb=901, bsz=32, lr=0.001, clip=100%, gnorm=2.3856
| epoch 007  6000 / 8223 loss=1.46 (2.12), wps=960, wpb=902, bsz=32, lr=0.001, clip=100%, gnorm=2.3893
| epoch 007  7000 / 8223 loss=2.06 (2.11), wps=961, wpb=904, bsz=32, lr=0.001, clip=100%, gnorm=2.3805
| epoch 007  8000 / 8223 loss=1.98 (2.10), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=2.3806
| epoch 007 | train loss 2.10 | train ppl 4.28 | s/checkpoint    7748 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 2.3861
| epoch 007 | valid on 'valid' subset  1000 / 1311 loss=2.09
| epoch 007 | valid on 'valid' subset | valid loss 2.46 | valid ppl 5.49
| epoch 008  1000 / 8223 loss=3.59 (1.97), wps=967, wpb=931, bsz=32, lr=0.001, clip=100%, gnorm=2.3700
| epoch 008  2000 / 8223 loss=1.68 (1.94), wps=964, wpb=919, bsz=32, lr=0.001, clip=100%, gnorm=2.3307
| epoch 008  3000 / 8223 loss=1.81 (1.92), wps=964, wpb=915, bsz=32, lr=0.001, clip=100%, gnorm=2.3062
| epoch 008  4000 / 8223 loss=1.18 (1.90), wps=962, wpb=908, bsz=32, lr=0.001, clip=100%, gnorm=2.3063
| epoch 008  5000 / 8223 loss=1.12 (1.89), wps=962, wpb=909, bsz=32, lr=0.001, clip=100%, gnorm=2.3197
| epoch 008  6000 / 8223 loss=1.24 (1.86), wps=961, wpb=904, bsz=32, lr=0.001, clip=100%, gnorm=2.3035
| epoch 008  7000 / 8223 loss=1.83 (1.85), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=2.2954
| epoch 008  8000 / 8223 loss=2.14 (1.83), wps=961, wpb=907, bsz=32, lr=0.001, clip=100%, gnorm=2.2907
| epoch 008 | train loss 1.83 | train ppl 3.55 | s/checkpoint    7748 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 2.2858
| epoch 008 | valid on 'valid' subset  1000 / 1311 loss=1.89
| epoch 008 | valid on 'valid' subset | valid loss 2.24 | valid ppl 4.73
| epoch 009  1000 / 8223 loss=3.02 (1.68), wps=963, wpb=910, bsz=32, lr=0.001, clip=100%, gnorm=2.1812
| epoch 009  2000 / 8223 loss=1.07 (1.70), wps=963, wpb=913, bsz=32, lr=0.001, clip=100%, gnorm=2.2284
| epoch 009  3000 / 8223 loss=1.11 (1.69), wps=963, wpb=914, bsz=32, lr=0.001, clip=100%, gnorm=2.2271
| epoch 009  4000 / 8223 loss=1.29 (1.67), wps=962, wpb=908, bsz=32, lr=0.001, clip=100%, gnorm=2.2088
| epoch 009  5000 / 8223 loss=1.29 (1.65), wps=962, wpb=908, bsz=32, lr=0.001, clip=100%, gnorm=2.2042
| epoch 009  6000 / 8223 loss=0.96 (1.64), wps=961, wpb=905, bsz=32, lr=0.001, clip=100%, gnorm=2.2012
| epoch 009  7000 / 8223 loss=1.72 (1.62), wps=961, wpb=905, bsz=32, lr=0.001, clip=100%, gnorm=2.1844
| epoch 009  8000 / 8223 loss=1.31 (1.62), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=2.1934
| epoch 009 | train loss 1.61 | train ppl 3.06 | s/checkpoint    7748 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 2.1922
| epoch 009 | valid on 'valid' subset  1000 / 1311 loss=1.73
| epoch 009 | valid on 'valid' subset | valid loss 2.07 | valid ppl 4.20
| epoch 010  1000 / 8223 loss=1.17 (1.51), wps=963, wpb=912, bsz=32, lr=0.001, clip=100%, gnorm=2.1459
| epoch 010  2000 / 8223 loss=1.27 (1.50), wps=962, wpb=908, bsz=32, lr=0.001, clip=100%, gnorm=2.1427
| epoch 010  3000 / 8223 loss=1.28 (1.49), wps=962, wpb=908, bsz=32, lr=0.001, clip=100%, gnorm=2.1507
| epoch 010  4000 / 8223 loss=0.91 (1.48), wps=962, wpb=908, bsz=32, lr=0.001, clip=100%, gnorm=2.1628
| epoch 010  5000 / 8223 loss=0.95 (1.47), wps=962, wpb=908, bsz=32, lr=0.001, clip=100%, gnorm=2.1358
| epoch 010  6000 / 8223 loss=1.56 (1.46), wps=961, wpb=905, bsz=32, lr=0.001, clip=100%, gnorm=2.1214
| epoch 010  7000 / 8223 loss=0.86 (1.46), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=2.1233
| epoch 010  8000 / 8223 loss=1.33 (1.45), wps=961, wpb=905, bsz=32, lr=0.001, clip=100%, gnorm=2.1133
| epoch 010 | train loss 1.44 | train ppl 2.72 | s/checkpoint    7747 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 2.1113
| epoch 010 | valid on 'valid' subset  1000 / 1311 loss=1.60
| epoch 010 | valid on 'valid' subset | valid loss 1.94 | valid ppl 3.83
| epoch 011  1000 / 8223 loss=1.89 (1.38), wps=963, wpb=918, bsz=32, lr=0.001, clip=100%, gnorm=2.0860
| epoch 011  2000 / 8223 loss=1.37 (1.35), wps=962, wpb=912, bsz=32, lr=0.001, clip=100%, gnorm=2.0606
| epoch 011  3000 / 8223 loss=0.75 (1.35), wps=963, wpb=916, bsz=32, lr=0.001, clip=100%, gnorm=2.0545
| epoch 011  4000 / 8223 loss=1.18 (1.33), wps=962, wpb=910, bsz=32, lr=0.001, clip=100%, gnorm=2.0534
| epoch 011  5000 / 8223 loss=1.19 (1.33), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=2.0408
| epoch 011  6000 / 8223 loss=2.48 (1.32), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=2.0341
| epoch 011  7000 / 8223 loss=0.72 (1.31), wps=961, wpb=904, bsz=32, lr=0.001, clip=100%, gnorm=2.0296
| epoch 011  8000 / 8223 loss=2.01 (1.30), wps=961, wpb=905, bsz=32, lr=0.001, clip=100%, gnorm=2.0225
| epoch 011 | train loss 1.30 | train ppl 2.46 | s/checkpoint    7748 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 2.0241
| epoch 011 | valid on 'valid' subset  1000 / 1311 loss=1.50
| epoch 011 | valid on 'valid' subset | valid loss 1.83 | valid ppl 3.55
| epoch 012  1000 / 8223 loss=0.96 (1.26), wps=966, wpb=925, bsz=32, lr=0.001, clip=100%, gnorm=2.0506
| epoch 012  2000 / 8223 loss=0.67 (1.22), wps=964, wpb=916, bsz=32, lr=0.001, clip=100%, gnorm=2.0042
| epoch 012  3000 / 8223 loss=0.69 (1.21), wps=962, wpb=912, bsz=32, lr=0.001, clip=100%, gnorm=1.9935
| epoch 012  4000 / 8223 loss=1.44 (1.21), wps=962, wpb=910, bsz=32, lr=0.001, clip=100%, gnorm=1.9925
| epoch 012  5000 / 8223 loss=0.93 (1.20), wps=962, wpb=910, bsz=32, lr=0.001, clip=100%, gnorm=1.9851
| epoch 012  6000 / 8223 loss=1.25 (1.19), wps=962, wpb=908, bsz=32, lr=0.001, clip=100%, gnorm=1.9702
| epoch 012  7000 / 8223 loss=0.82 (1.19), wps=961, wpb=905, bsz=32, lr=0.001, clip=100%, gnorm=1.9662
| epoch 012  8000 / 8223 loss=0.82 (1.18), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=1.9627
| epoch 012 | train loss 1.18 | train ppl 2.27 | s/checkpoint    7748 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 1.9609
| epoch 012 | valid on 'valid' subset  1000 / 1311 loss=1.43
| epoch 012 | valid on 'valid' subset | valid loss 1.74 | valid ppl 3.35
| epoch 013  1000 / 8223 loss=0.73 (1.15), wps=965, wpb=923, bsz=32, lr=0.001, clip=100%, gnorm=1.9486
| epoch 013  2000 / 8223 loss=0.83 (1.14), wps=964, wpb=919, bsz=32, lr=0.001, clip=100%, gnorm=1.9450
| epoch 013  3000 / 8223 loss=1.14 (1.12), wps=963, wpb=912, bsz=32, lr=0.001, clip=100%, gnorm=1.9137
| epoch 013  4000 / 8223 loss=0.82 (1.12), wps=964, wpb=917, bsz=32, lr=0.001, clip=100%, gnorm=1.9096
| epoch 013  5000 / 8223 loss=0.61 (1.10), wps=963, wpb=913, bsz=32, lr=0.001, clip=100%, gnorm=1.9013
| epoch 013  6000 / 8223 loss=1.76 (1.10), wps=962, wpb=909, bsz=32, lr=0.001, clip=100%, gnorm=1.8971
| epoch 013  7000 / 8223 loss=1.62 (1.09), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=1.9087
| epoch 013  8000 / 8223 loss=0.68 (1.08), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=1.9023
| epoch 013 | train loss 1.08 | train ppl 2.11 | s/checkpoint    7748 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 1.8997
| epoch 013 | valid on 'valid' subset  1000 / 1311 loss=1.36
| epoch 013 | valid on 'valid' subset | valid loss 1.67 | valid ppl 3.19
| epoch 014  1000 / 8223 loss=0.81 (1.03), wps=960, wpb=904, bsz=32, lr=0.001, clip=100%, gnorm=1.8836
| epoch 014  2000 / 8223 loss=1.18 (1.02), wps=961, wpb=905, bsz=32, lr=0.001, clip=100%, gnorm=1.8914
| epoch 014  3000 / 8223 loss=1.09 (1.02), wps=961, wpb=905, bsz=32, lr=0.001, clip=100%, gnorm=1.8764
| epoch 014  4000 / 8223 loss=0.86 (1.01), wps=961, wpb=904, bsz=32, lr=0.001, clip=100%, gnorm=1.8695
| epoch 014  5000 / 8223 loss=1.04 (1.00), wps=961, wpb=904, bsz=32, lr=0.001, clip=100%, gnorm=1.8560
| epoch 014  6000 / 8223 loss=1.00 (1.01), wps=961, wpb=908, bsz=32, lr=0.001, clip=100%, gnorm=1.8581
| epoch 014  7000 / 8223 loss=0.78 (1.01), wps=962, wpb=910, bsz=32, lr=0.001, clip=100%, gnorm=1.8546
| epoch 014  8000 / 8223 loss=1.09 (1.00), wps=962, wpb=908, bsz=32, lr=0.001, clip=100%, gnorm=1.8487
| epoch 014 | train loss 1.00 | train ppl 1.99 | s/checkpoint    7748 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 1.8480
| epoch 014 | valid on 'valid' subset  1000 / 1311 loss=1.31
| epoch 014 | valid on 'valid' subset | valid loss 1.62 | valid ppl 3.07
| epoch 015  1000 / 8223 loss=0.67 (0.98), wps=964, wpb=919, bsz=32, lr=0.001, clip=100%, gnorm=1.8502
| epoch 015  2000 / 8223 loss=0.85 (0.96), wps=963, wpb=913, bsz=32, lr=0.001, clip=100%, gnorm=1.8272
| epoch 015  3000 / 8223 loss=0.83 (0.96), wps=964, wpb=916, bsz=32, lr=0.001, clip=100%, gnorm=1.8139
| epoch 015  4000 / 8223 loss=0.73 (0.96), wps=963, wpb=915, bsz=32, lr=0.001, clip=100%, gnorm=1.8137
| epoch 015  5000 / 8223 loss=0.73 (0.95), wps=962, wpb=909, bsz=32, lr=0.001, clip=100%, gnorm=1.8049
| epoch 015  6000 / 8223 loss=2.99 (0.94), wps=962, wpb=910, bsz=32, lr=0.001, clip=100%, gnorm=1.7922
| epoch 015  7000 / 8223 loss=0.66 (0.93), wps=962, wpb=908, bsz=32, lr=0.001, clip=100%, gnorm=1.7845
| epoch 015  8000 / 8223 loss=3.33 (0.92), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=1.7872
| epoch 015 | train loss 0.92 | train ppl 1.89 | s/checkpoint    7748 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 1.7830
| epoch 015 | valid on 'valid' subset  1000 / 1311 loss=1.27
| epoch 015 | valid on 'valid' subset | valid loss 1.57 | valid ppl 2.97
| epoch 016  1000 / 8223 loss=0.56 (0.86), wps=961, wpb=905, bsz=32, lr=0.001, clip=100%, gnorm=1.7126
| epoch 016  2000 / 8223 loss=0.52 (0.86), wps=961, wpb=904, bsz=32, lr=0.001, clip=100%, gnorm=1.7232
| epoch 016  3000 / 8223 loss=0.78 (0.86), wps=962, wpb=907, bsz=32, lr=0.001, clip=100%, gnorm=1.7197
| epoch 016  4000 / 8223 loss=0.57 (0.87), wps=963, wpb=911, bsz=32, lr=0.001, clip=100%, gnorm=1.7252
| epoch 016  5000 / 8223 loss=0.38 (0.86), wps=962, wpb=909, bsz=32, lr=0.001, clip=100%, gnorm=1.7170
| epoch 016  6000 / 8223 loss=0.48 (0.86), wps=961, wpb=907, bsz=32, lr=0.001, clip=100%, gnorm=1.7178
| epoch 016  7000 / 8223 loss=1.27 (0.85), wps=961, wpb=906, bsz=32, lr=0.001, clip=100%, gnorm=1.7159
| epoch 016  8000 / 8223 loss=0.54 (0.85), wps=961, wpb=905, bsz=32, lr=0.001, clip=100%, gnorm=1.7197
| epoch 016 | train loss 0.85 | train ppl 1.81 | s/checkpoint    7748 | words/s    961 | words/batch    906 | bsz    32 | lr 0.001000 | clip 100% | gnorm 1.7225
| epoch 016 | valid on 'valid' subset  1000 / 1311 loss=1.23
| epoch 016 | valid on 'valid' subset | valid loss 1.53 | valid ppl 2.89
| epoch 017  1000 / 8223 loss=0.65 (0.80), wps=957, wpb=889, bsz=32, lr=0.001, clip=100%, gnorm=1.6627
| epoch 017  2000 / 8223 loss=1.10 (0.80), wps=960, wpb=901, bsz=32, lr=0.001, clip=100%, gnorm=1.6551

**Comment by patelrajnath** [comment]
PYTHONPATH=$FAIRSEQPY:$PYTHONPATH CUDA_VISIBLE_DEVICES="0,1,2" python3.5 $FAIRSEQPY/train.py --max-tokens 2500 --save-dir $OUT_DIR --encoder-embed-dim 500 --encoder-embed-path $EMBED_PATH --decoder-embed-dim 500 --decoder-embed-path $EMBED_PATH --decoder-out-embed-dim 500 --dropout 0.2 --clip-norm 0.1 --lr 0.001 --min-lr 1e-4 --encoder-layers '[(1024,3)] * 7' --decoder-layers '[(1024,3)] * 7' --momentum 0.99 --max-epoch 100 --batch-size 32 --no-progress-bar --seed $SEED $DATA_BIN_DIR

**Comment by ShiraKadosh** [comment]
Thanks @patelrajnath I'll try this.  
How can I know if the train is about to end?  I don't see the lr change during the last 17 epochs...

**Comment by patelrajnath** [comment]
The learning rate will change if there is no gain in validation ppl. 
epoch 014 | valid on 'valid' subset | valid loss 1.62 | **valid ppl 3.07**
epoch 015 | valid on 'valid' subset | valid loss 1.57 | **valid ppl 2.97**

**Comment by huihuifan** [comment]
The different learning rate schedules (https://github.com/pytorch/fairseq/tree/master/fairseq/optim/lr_scheduler) will affect when the training is about to end.

**Comment by ShiraKadosh** [comment]
Thanks @huihuifan, @patelrajnath
