### ISSUE TITLE
Model model.cfg.generation is overwritten in hub_utils.py

### ISSUE THREAD

**Issue by louismartin** [pytorch/fairseq#3011]
https://github.com/pytorch/fairseq/blob/feb5f07ff4220b7908ff12c6692685784c7c9a71/fairseq/hub_utils.py#L160
It seems that when running `gen_args = copy.copy(self.cfg.generation)`, the copy operation does not actually copy `omegaconf.dictconfig.DictConfig` objects causing them to be modified inplace afterwards in the code.

I noticed this by running `model.score("Hello world")` and then `model.sample("Hello")`. The second call to `sample()` returns nothing because `model.cfg.generation["score_reference"]` is was modified to True inplace in the call to `score()`.

### Repro
Simple repro of the behaviour of omegaconf DictConfigs:
```
import copy
from omegaconf import OmegaConf
a = OmegaConf.create({"a": 1, "b": 2})
b = copy.copy(a)
b["a"] = 42
print(b)
print(a)
```
Outputs:
```
{'a': 42, 'b': 2}
{'a': 42, 'b': 2}
```

### Simple fix
A simple fix would be to first cast the object to a dict with `gen_args = dict(self.cfg.generation).copy()` (and not use `open_dict()` afterwards).
For example with a simple omegaconf DictConfig:
```
from omegaconf import OmegaConf
a = OmegaConf.create({"a": 1, "b": 2})
b = dict(a).copy()
b["a"] = 42
print(b)
print(a)
```
Outputs:
```
{'a': 42, 'b': 2}
{'a': 1, 'b': 2}
```

This however only works for first level attributes, nested DictConfigs won't be casted to dict and will therefore be modified inplace.
For instance:
```
from omegaconf import OmegaConf
a = OmegaConf.create({"a": {"aa": 1}, "b": 2})
b = dict(a).copy()
b["a"]["aa"] = 42
print(b)
print(a)
```
Outputs:
```
{'a': {'aa': 42}, 'b': 2}
{'a': {'aa': 42}, 'b': 2}
```

@alexeib I am not sure if this is intended in omegaconf, I will open an issue there as well.

**Comment by alexeib** [comment]
should be easy to fix by just using deepcopy:
`b = copy.deepcopy(a)`

**Comment by louismartin** [comment]
Yes perfect deepcopy works like a charm! And actually casting to a dict caused downstream bugs because other functions called `getattr(args, "foo")` which does not work on a dict.
I'll submit a PR.
