### ISSUE TITLE
Fairseq stucks when resuming the training procedure by using --restore-file (multi-gpu)

### ISSUE THREAD

**Issue by gpengzhi** [pytorch/fairseq#3016]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

I first trained a`transformer_big` model on 8 GPUs for some epochs, then I stoped the training procedure. When I tried to resume the training procedure on 8 GPUs by specifying `--restore-file`, `fairseq` stucked. The GPU-Util of all 8 GPUs became 100%, and Memory-Usage of each one is 8373MiB / 16160MiB.

I tried to decrease the `max_tokens`, but it did not help. I had no issue when I resume the training procedure with the same configurations on a single GPU.

`fairseq` stuck at the beginning.

epoch 014:   0%|                                              | 0/6372 [00:00<?, ?it/s]
2020-12-10 18:51:31 | INFO | fairseq.trainer | begin training epoch 14

#### Code

```bash
python3 fairseq/fairseq_cli/train.py data-bin/*** --arch transformer_wmt_en_de_big --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 8000 --lr 5e-4 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --weight-decay 0.0 --max-tokens 1024 --save-dir checkpoints/*** --eval-bleu --eval-bleu-args '{"beam": 4, "lenpen": 0.6}' --eval-bleu-detok moses --eval-bleu-remove-bpe --eval-bleu-print-samples --best-checkpoint-metric bleu --maximize-best-checkpoint-metric --alpha 1.0 --update-freq 6 --ddp-backend=no_c10d --skip-invalid-size-inputs-valid-test --restore-file checkpoints/***
```

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 1.0.0a0+b58f4f0
 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip install --editable ./
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by gpengzhi** [comment]
Traceback (most recent call last):
  File "fairseq/fairseq_cli/train.py", line 396, in <module>
    cli_main()
  File "fairseq/fairseq_cli/train.py", line 392, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/users/gaopengzhi/nmt/fairseq/fairseq/distributed_utils.py", line 303, in call_main
    cfg.distributed_training.distributed_world_size,
  File "/home/users/gaopengzhi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/users/gaopengzhi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/users/gaopengzhi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 0 terminated with signal SIGTERM

**Comment by gpengzhi** [comment]
This might be the reason that `fairseq` stuck. How can I resolve it? Thanks!

**Comment by myleott** [comment]
Can you try `--load-checkpoint-on-all-dp-ranks`? We made some recent changes to checkpoint loading that seem to be problematic. That flag should revert to the old behavior.

**Comment by flckv** [comment]
I tried to load last checkpoint too:

srun fairseq-hydra-train distributed_training.distributed_world_size=4 +optimization.update_freq='[16]' --config-dir /home/flck/fairseq/examples/wav2vec/config/pretraining --config-name wav2vec2_base_librispeech `--load-checkpoint-on-all-dp-ranks /home/flck/outputs/2023-05-22/07-19-53/checkpoints  `

but I got error:

fairseq-hydra-train: **error**: `unrecognized arguments:` --load-checkpoint-on-all-dp-ranks /home/flck/outputs/2023-05-22/07-19-53/checkpoints

how to load the checkpoint to continue pretraining?
