### ISSUE TITLE
MBART fairseq-train error

### ISSUE THREAD

**Issue by bkj** [pytorch/fairseq#3019]
## 🐛 Bug

Cannot load `mbart.cc25.v2` model for fine-tuning

### To Reproduce
When I run the command in the README, I get a warning message that says the model cannot be found:
```
$ PRETRAIN=mbart.cc25.v2 # fix if you moved the downloaded checkpoint
$ langs=ar_AR,cs_CZ,de_DE,en_XX,es_XX,et_EE,fi_FI,fr_XX,gu_IN,hi_IN,it_IT,ja_XX,kk_KZ,ko_KR,lt_LT,lv_LV,my_MM,ne_NP,nl_XX,ro_RO,ru_RU,si_LK,tr_TR,vi_VN,zh_CN

$ fairseq-train results/v0 \
  --encoder-normalize-before --decoder-normalize-before \
  --arch mbart_large --layernorm-embedding \
  --task translation_from_pretrained_bart \
  --source-lang en_XX --target-lang ro_RO \
  --criterion label_smoothed_cross_entropy --label-smoothing 0.2 \
  --optimizer adam --adam-eps 1e-06 --adam-betas '(0.9, 0.98)' \
  --lr-scheduler polynomial_decay --lr 3e-05 --warmup-updates 2500 --total-num-update 40000 \
  --dropout 0.3 --attention-dropout 0.1 --weight-decay 0.0 \
  --max-tokens 512 --update-freq 2 \
  --save-interval 1 --save-interval-updates 5000 --keep-interval-updates 10 --no-epoch-checkpoints \
  --seed 222 --log-format simple --log-interval 2 \
  --restore-file $PRETRAIN \
  --reset-optimizer --reset-meters --reset-dataloader --reset-lr-scheduler \
  --langs $langs \
  --ddp-backend no_c10d

...
2020-12-11 04:45:52 | INFO | fairseq.trainer | no existing checkpoint found models/mbart.cc25
...
```

If I change the code to `PRETRAIN=mbart.cc25.v2/model.pt`, then it finds the model but gives an error:
```
...
RuntimeError: [enforce fail at inline_container.cc:143] . PytorchStreamReader failed reading file data/94565435476624: file read failed
```

### Expected behavior

Expect the model to load

### Environment

 - fairseq Version : master
 - PyTorch Version : 1.5.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): pip install --editable ./
 - Python version: 3.7
 - CUDA/cuDNN version: 10..2
 - GPU models and configuration: V100 on AWS

**Comment by myleott** [comment]
Ah, yes that looks like a bug in the docs, it should be `PRETRAIN=mbart.cc25.v2/model.pt`

As for the other error, I've never seen that before... can you try redownloading the model archive in case it got corrupted somehow?

**Comment by zhengxxn** [comment]
@bkj I got the same load error, have you resolved it?

**Comment by PursuitN** [comment]
With PyTorch 1.5.0 I got the same error, and solved the problem using PyTorch1.6.
