### ISSUE TITLE
Azure Machine Learning logging support

### ISSUE THREAD

**Issue by sksq96** [pytorch/fairseq#3020]
## 🚀 Feature Request

Support for [Azure ML](https://azure.microsoft.com/en-us/services/machine-learning/#features) logging.

### Motivation

- Azure Machine Learning has extensive logging support compared to Tensorbard. 
- Bringing the model training and logging capabilities on the same platform would speeden up researcher productivity. 
- Azure ML interface is better suited for many experiments, it also can log model weights, configs, and source code. 

### Pitch

A way to log the training/validation statistics on the Azure ML context to improve training on Azure Machine Learning services. Perhaps a flag to activate the logging while using the `fairseq-train` cli should solve this problem. 

### Additional context

A current PR draft is available at #2999 which addresses this issue to log to Azure ML.

**Comment by myleott** [comment]
Closing since the associated PR is merged. Please feel free to reopen if needed
