### ISSUE TITLE
Implementing Coverage Penalty

### ISSUE THREAD

**Issue by felix-schneider** [pytorch/fairseq#3024]
I'm looking to implement a coverage penalty similar to [Wu et al.](https://arxiv.org/pdf/1609.08144.pdf%20%287.pdf). I'm not sure what the correct place for it is. Should it be in `SequenceGenerator::finalize_hypos` or should I extend `BeamSearch`?
Or is there already an example of a similar penalty?

I'm using fairseq 0.10.1

**Comment by AlexNLP** [comment]
Have you got the target code? Can share with the code community?

> I'm looking to implement a coverage penalty similar to [Wu et al.](https://arxiv.org/pdf/1609.08144.pdf%20%287.pdf). I'm not sure what the correct place for it is. Should it be in `SequenceGenerator::finalize_hypos` or should I extend `BeamSearch`? Or is there already an example of a similar penalty?
> 
> I'm using fairseq 0.10.1
