### ISSUE TITLE
How to load pre-trained wav2vec2.0 models

### ISSUE THREAD

**Issue by othrif** [pytorch/fairseq#3025]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

I would like to load pre-trained models for wav2vec2 as given in the instructions README (https://github.com/pytorch/fairseq/tree/master/examples/wav2vec). My goal is to export the pre-trained model to ONNX following the instructions given here: https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html.

In order to run `torch.onnx.export()`, I need the model as an input. I am having problems loading the pre-trained model in order to export it. 

#### Code

   

I have tried the code snippets in the wav2vec2 README (https://github.com/pytorch/fairseq/tree/master/examples/wav2vec):

``` python
import torch
import fairseq
cp = torch.load('path/to/file/wav2vec_small_10m.pt', map_location=torch.device('cpu'))
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp])
```
I am getting the following error: 
> AttributeError: 'dict' object has no attribute 'replace'

Looking at the documentation here: https://pytorch.org/tutorials/beginner/saving_loading_models.html, I tried
``` python
# Model class must be defined somewhere
model = torch.load(PATH)
model.eval()
```
But not sure how to exactly get the model in order to pass it to `torch.onnx.export()`

#### What have you tried?

* Tried loading the pre-trained model with the code snippet above as detailed in https://github.com/pytorch/fairseq/tree/master/examples/wav2vec
* Tried Loading the pre-trained model as outlined in https://pytorch.org/tutorials/beginner/saving_loading_models.html

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): macOS 10.15.7
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): `CFLAGS="-stdlib=libc++"; pip install --editable ./`
 - Python version: Python 3.8.5
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information:

**Comment by ag027592** [comment]
I have faced the same problem. 

Therefore, I temporarily the "previous version".

import torch
from fairseq.models.wav2vec import Wav2VecModel

cp = torch.load("/path/to/wav2vec_large.pt")
model = Wav2VecModel.build_model(cp['args'], task=None)
model.load_state_dict(cp['model'])
model.eval()

wav_input_16khz = torch.randn(1,10000)
z = model.feature_extractor(wav_input_16khz)
c = model.feature_aggregator(z)

**Comment by othrif** [comment]
Thanks @ag027592 for the reply! 

When I invoque `model = Wav2VecModel.build_model(cp['args'], task=None)`, I get
> AttributeError: 'Namespace' object has no attribute 'activation'

**Comment by ag027592** [comment]
> Thanks @ag027592 for the reply!
> 
> When I invoque `model = Wav2VecModel.build_model(cp['args'], task=None)`, I get
> 
> > AttributeError: 'Namespace' object has no attribute 'activation'

I have used the pretrained model, wav2vec_large.pt (https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_large.pt)
Did you use the pretrained model,wav2vec_small_10m.pt?
I think the pretrained model you used is the lasted version, so it is not compatible when using the previous version method.
Could you try to use the pretrained, wav2vec_large.pt?

**Comment by othrif** [comment]
I was using `wav2vec_large.pt`. 

I started again from scratch doing the following:
``` bash 
git clone https://github.com/pytorch/fairseq.git
cd fairseq
CFLAGS="-stdlib=libc++" # on MacOS according to the instructions
pip install --editable ./
```

Then I run:
``` python
import torch
from fairseq.models.wav2vec import Wav2VecModel

cp = torch.load('wav2vec_large.pt', map_location=torch.device('cpu'))
model = Wav2VecModel.build_model(cp['args'], task=None)
```

Here is the error I get:
``` bash 
Traceback (most recent call last):
  File "XYZ/load_wav2vec.py", line 7, in <module>
    model = Wav2VecModel.build_model(cp['args'], task=None)
  File "XYZ/wav2vec.py", line 168, in build_model
    model = Wav2VecModel(cfg)
  File "XYZ/wav2vec.py", line 178, in __init__
    if cfg.activation == "relu":
AttributeError: 'Namespace' object has no attribute 'activation'
```

**Comment by othrif** [comment]
Testing with the wav2vec2.0 model with the same prescription, I get the error: 
> FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/abaevski/data/speech/libri/10m/wav2vec/raw/dict.ltr.txt'

@alexeib Could you please clarify how to pass the letter dictionary to the model loading sequence. 

I run 
``` python
import torch
import fairseq
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(['/Users/othrif/spectrum/voice/projects/wav2vec/models/wav2vec2/wav2vec_small_10m.pt'])

```

**Comment by ag027592** [comment]
> Testing with the wav2vec2.0 model with the same prescription, I get the error:
> 
> > FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/abaevski/data/speech/libri/10m/wav2vec/raw/dict.ltr.txt'
> 
> @alexeib Could you please clarify how to pass the letter dictionary to the model loading sequence.
> 
> I run
> 
> ```python
> import torch
> import fairseq
> model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(['path/to/wav2vec_small_10m.pt'])
> ```

I faced the same problem.

**Comment by alexeib** [comment]
if you want to load these checkpoints, you need to override the data arg stored in the checkpoint:

```
import torch
import fairseq
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(['path/to/wav2vec_small_10m.pt'], arg_overrides={"data": "/path/to/data/with/dict"})

```

**Comment by ag027592** [comment]
> if you want to load these checkpoints, you need to override the data arg stored in the checkpoint:
> 
> ```
> import torch
> import fairseq
> model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(['path/to/wav2vec_small_10m.pt'], arg_overrides={"data": "/path/to/data/with/dict"})
> ```

Thank you. 
I just want to check.
I download the dict from the link by https://dl.fbaipublicfiles.com/fairseq/wav2vec/dict.ltr.txt
Am I right?

**Comment by alexeib** [comment]
yes, that should work

**Comment by NickCis** [comment]
I'm trying to load the [XLSR-53 multilingual model](https://dl.fbaipublicfiles.com/fairseq/wav2vec/xlsr_53_56k.pt), but get the following error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-d3753068bd38> in <module>()
      6 cp_path = './xlsr_53_56k.pt'
      7 
----> 8 model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])
      9 
     10 model = model[0]

2 frames
/usr/local/lib/python3.6/dist-packages/fairseq/checkpoint_utils.py in _upgrade_state_dict(state)
    418     # default to translation task
    419     if not hasattr(state["args"], "task"):
--> 420         state["args"].task = "translation"
    421     # --raw-text and --lazy-load are deprecated
    422     if getattr(state["args"], "raw_text", False):

AttributeError: 'NoneType' object has no attribute 'task'
```

Code:
```python
import torch
import librosa
import fairseq

wav_input_16khz = librosa.load('./audio.wav')
cp_path = './xlsr_53_56k.pt'

model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])

model = model[0]
model.eval()

z = model.feature_extractor(wav_input_16khz)
c = model.feature_aggregator(z)
```

Any ideas?

**Comment by alexeib** [comment]
try updating to the latest version of fairseq and/or re-download the checkpoint?

```python
>>> cp = '/private/home/abaevski/models/wav2vec2/xlsr_53_56k.pt'
>>> import fairseq
>>> model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp])
>>> task
<fairseq.tasks.audio_pretraining.AudioPretrainingTask object at 0x7fdd6dc5c460>
```

**Comment by NickCis** [comment]
@alexeib Thanks for the quick reply!. I'm downloading the checkpoint from: `https://dl.fbaipublicfiles.com/fairseq/wav2vec/xlsr_53_56k.pt` is that the correct link?.

I've move the sample to [google collaboratory](https://colab.research.google.com/drive/1A2Xai09oHAnvP-uDGIvpF8y5foLtzwpJ#scrollTo=-zY0Lga0-mHo), which also throws the error :/

**Comment by stonelazy** [comment]
Have been facing a same problem. Faced many compatibility issues. Turns out the reason was that pip source was not updated. I tried to [install and develop locally](https://github.com/pytorch/fairseq#requirements-and-installation). Then XLS43, wav2vec_large,wav2vec_small everything was working properly.
