### ISSUE TITLE
Are punctuations predicted by the speech-to-text model?

### ISSUE THREAD

**Issue by gungor2** [pytorch/fairseq#3029]
I am quite new to this area as you will tell from my question:

Does the speech-to-text model in this repo predict punctuations (e.g., sentence boundaries). I experimented with deep search 1 that only outputs the words without any punctuation.

**Comment by cromz22** [comment]
Yes, it predicts punctuations.
For example, En ASR produces output like this:
```
T-3679	The fire burned the fox.
H-3679	-0.020622575655579567	▁ T h e ▁ f i r e ▁ b u r n e d ▁ t h e ▁ f o x .
D-3679	-0.020622575655579567	The fire burned the fox.
P-3679	-0.0000 -0.0006 -0.0000 -0.0001 -0.0009 -0.0002 -0.0015 -0.0129 0.0000 -0.0005 -0.0000 -0.0000 -0.0000 -0.0000 -0.2480 0.0000 -0.0000 -0.0000 -0.0000 -0.0000 -0.0000 -0.0118 -0.2470 -0.0126 -0.0000 0.0000
```

The explanation of this output can be found [here](https://fairseq.readthedocs.io/en/latest/getting_started.html):
> This generation script produces three types of outputs: a line prefixed with O is a copy of the original source sentence; H is the hypothesis along with an average log-likelihood; and P is the positional score per token position, including the end-of-sentence marker which is omitted from the text.
> Other types of output lines you might see are D, the detokenized hypothesis, T, the reference target, A, alignment info, E the history of generation steps.

**Comment by kahne** [comment]
Yes, our speech-to-text examples train MuST-C/CoVoST ASR models with capitalization and punctuation (doesn't apply to the LibriSpeech example because there is no punctuation in the raw data). When using your own dataset, the ASR model should output punctuation as long as you don't remove punctuation from your train data.

**Comment by dvirginz** [comment]
> Yes, our speech-to-text examples train MuST-C/CoVoST ASR models with capitalization and punctuation (doesn't apply to the LibriSpeech example because there is no punctuation in the raw data). When using your own dataset, the ASR model should output punctuation as long as you don't remove punctuation from your train data.

Thanks for the answer @kahne. The explanation and link provided above refer to the getting started page.
Do you have a code example of the provided inference pipeline?
Thanks.
