### ISSUE TITLE
mBART w/ Arabic source language

### ISSUE THREAD

**Issue by bkj** [pytorch/fairseq#3033]
Hi --

I was able to ~ reproduce the results of fine-tuning mBART for English->Romanian translation.  I'm interested in trying to reproduce some of the other results in the paper.

I'm curious whether anything needs to be done in either the preprocessing or training scripts to account for the fact that Arabic is written right-to-left instead of left-to-right.  I'm assuming I should be using the same approach that was used in mBART pre-training, but unfortunately I don't think the source code for that is available (yet?).

Thanks!

**Comment by bkj** [comment]
@myleott maybe you're the right person to direct the question to? 
Or @sshleifer? I've seen you do a lot of inspection of the mBART model as well.

Thanks!

**Comment by sshleifer** [comment]
I don't know the answer, but excited to learn!
