### ISSUE TITLE
omegaconf.errors.ConfigKeyError: str interpolation key 'optimization.lr' not found

### ISSUE THREAD

**Issue by fenimi** [pytorch/fairseq#3046]
I don't know how to solve this error: " omegaconf.errors.ConfigKeyError: str interpolation key 'optimization.lr' not found"
Here is the command i'm running:

#### Code
fairseq-train data-bin/XXXX/ --save-dir XXXX --arch lstm --encoder-bidirectional --encoder-layers 2 --decoder-layers 2 --dropout 0.2  --lr 5e-4 --batch-size 32 --optimizer adam --eval-bleu --eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}' --eval-bleu-detok moses --best-checkpoint-metric bleu --maximize-best-checkpoint-metric   

I'll appreciate your help. 
                                                                                          
#### What have you tried?
I checked that i have the optimizer and learning rate in the command. 

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):master
 - PyTorch Version (e.g., 1.0)   1.7.1
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source):source 
 - Build command you used (if compiling from source): git clone https://github.com/pytorch/fairseq
cd fairseq
pip install --editable ./

 - Python version:python/3.8.2
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
Hmm, I wasn't able to reproduce this on my environment, but could be an issue with the version of omegaconf or hydra.

What does this report?
```
python -c 'import hydra, omegaconf; print(f"hydra={hydra.__version__}, omegaconf={omegaconf.__version__}")'
# I get: hydra=1.0.4, omegaconf=2.0.5
```

**Comment by fenimi** [comment]
Hi Myleott, 
Thank you for replying. I get: hydra=1.0.3, omegaconf=2.0.2". 
#I'm not able to get omegaconf 2.0.5 / hydra 1.0.4 : ERROR: No matching distribution found for XXX

**Comment by myleott** [comment]
What is the full error if you do `pip install -U omegaconf==2.0.5 hydra-core==1.0.4`?

**Comment by fenimi** [comment]
Hi Myleott, 
I uninstalled the previous version and reinstalled omegconf==2.0.5 hydra-core==1.0.4 and it works fine now. Thank you so much

**Comment by RuABraun** [comment]
I get this error after switching from a commit from May 31st to current master.
