### ISSUE TITLE
Using Fairseq for Chinese to English translation and export the model to ONNX still not possible?

### ISSUE THREAD

**Issue by GeorgeS2019** [pytorch/fairseq#3048]
I need a working fairseq [generated NOT interactive](https://github.com/pytorch/fairseq/issues/2713) Chinese to English model that is exported to ONNX (which hopefully will appear in the ONNX public repository)

I will be fine if it is slightly out-of-date as long as it is a working fairseq (generated and not Interactive). Only the interactive version is with sufficient documentation BUT there is not the version we need for serious work.

The only repository with a claimed working [Fairseq Chinese to English generated version](https://github.com/twairball/fairseq-zh-en) is archived.

FYI  [I keep coming back to Fairseq](https://github.com/pytorch/fairseq/issues/1433#issuecomment-682724974) because We NEED THIS working Fairseq Chinese to English generated with ONNX urgently TO BRING HOPE TO END COVID-19  ( that is how urgent and how serious is that)

**Comment by yugaljain1999** [comment]
@GeorgeS2019 have u find any solution yet?
If yes, can u pls share?
