### ISSUE TITLE
Load_model_ensemble_and_task() gives error for multiple models

### ISSUE THREAD

**Issue by myazann** [pytorch/fairseq#3050]
#### What is your question?

Hi, I am having problems loading pretrained models. I used the code given in the readme file, and I have tried it for two models, but the load_model_ensemble_and_task()  function is raising different errors for both of them.

**When I try to load "wav2vec_large.pt" model, I get** 

KeyError                                  Traceback (most recent call last)
<ipython-input-3-ca5356f4acbd> in <module>
----> 1 model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp])

~/fairseq/checkpoint_utils.py in load_model_ensemble_and_task(filenames, arg_overrides, task, strict, suffix, num_shards)
    277             if not PathManager.exists(filename):
    278                 raise IOError("Model file not found: {}".format(filename))
--> 279             state = load_checkpoint_to_cpu(filename, arg_overrides)
    280             if shard_idx == 0:
    281                 args = state["args"]

~/fairseq/checkpoint_utils.py in load_checkpoint_to_cpu(path, arg_overrides)
    230         for arg_name, arg_val in arg_overrides.items():
    231             setattr(args, arg_name, arg_val)
--> 232     state = _upgrade_state_dict(state)
    233     return state
    234 

~/fairseq/checkpoint_utils.py in _upgrade_state_dict(state)
    432 
    433     # set any missing default values in the task, model or other registries
--> 434     registry.set_defaults(state["args"], tasks.TASK_REGISTRY[state["args"].task])
    435     registry.set_defaults(state["args"], models.ARCH_MODEL_REGISTRY[state["args"].arch])
    436     for registry_name, REGISTRY in registry.REGISTRIES.items():

KeyError: 'speech_pretraining' 

 **And when I try to load "wav2vec_small_960h.pt", I get:**

RuntimeError: Error(s) in loading state_dict for Wav2VecCtc:
	size mismatch for w2v_encoder.proj.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([512, 768]).
	size mismatch for w2v_encoder.proj.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).

#### Code

import torch
import fairseq

cp = "wav2vec_large.pt"
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp])

#### What's your environment?
I am trying this in a container which is created from the jupyter/base-notebook image.

 - fairseq Version: 0.10.1
 - PyTorch Version (e.g., 1.0): 1.7.0
 - How you installed fairseq (`pip`, source): pip 
 - Python version: 3.8.6

**Comment by ajmssc** [comment]
try `pip install soundfile git+git://github.com/pytorch/fairseq.git@b8ea8a9b72c82192da07e3377adf4ebbde16716d`

**Comment by myazann** [comment]
> try `pip install soundfile git+git://github.com/pytorch/fairseq.git@b8ea8a9b72c82192da07e3377adf4ebbde16716d`

This works, thanks.
