### ISSUE TITLE
FileNotFoundError rescore_data_new_bpe.en in rerank.py

### ISSUE THREAD

**Issue by babangain** [pytorch/fairseq#3061]
I tried to reproduce experiments as in 
https://github.com/pytorch/fairseq/tree/master/examples/noisychannel

I encountered the following error. 
FileNotFoundError: [Errno 2] No such file or directory: '/content/fairseq/examples/noisychannel/rerank_data/wmt17/nbest_50_subset_test_fw_name_fw_model_ex_shard_0_of_1/rescore_data_new_bpe.en'

I have no idea where the file should come from. Please help. Thansk

**Comment by myleott** [comment]
I'm not that familiar with this code, any ideas @nng555?
