### ISSUE TITLE
Wav2vec 2.0 inference with "kenlm" got much higher WER (many repeats words)  than with "viterbi" sometimes

### ISSUE THREAD

**Issue by JINGZIjingzi** [pytorch/fairseq#3062]
## ❓ Questions and Help
I finetune the wav2vec 2.0 pretrained model with other languages (pashto, cantonese separately).  The performance with viterbi inference seems good.

However, when I try to infer with Kenlm, some problems come up. Sometimes, the inference results with Kenlm have losts of repeats, which leads the WER to very high numbers, like 200% or 500%.  The WER with viterbi is about 50%. More confused, the exactly same files and configs for inference with kenlm works well with one finetuned model (xlsr_53_56k.pt finetuned with pashto), but the results turns to be weird when I just change the finetuned model. I have tried many times, the results remains the same.

Does anyone meet similar problems…

**Comment by Esdsnqxz** [comment]
so am i，how do you solve this problem？

**Comment by JINGZIjingzi** [comment]
You can check another [issuse in wav2letter](https://github.com/facebookresearch/wav2letter/issues/909) . It is caused by some bugs in the recent commit of wav2letter. Reverting that commit fixes the problem.
