### ISSUE TITLE
How to calculate steps through epochs?

### ISSUE THREAD

**Issue by Surnal** [pytorch/fairseq#3073]
#### What is your question?
Hello, I want to compare the training time of transformer and my own model. By looking at the paper "Attention is all you need", I found an original sentence"We trained our models on one machine with 8 NVIDIA P100 GPUs. For our base models using the hyperparameters described throughout the paper, each training step took about 0.4 seconds. We trained the base models for a total of 100,000 steps or 12 hours. For our big models,(described on the bottom line of table 3), step time was 1.0 seconds. The big models were trained for 300,000 steps (3.5 days)."
How to calculate the steps here, the printed log of my model is as follows:
#### Code
![IMG_4367](https://user-images.githubusercontent.com/50646972/103144698-d8899c00-4768-11eb-8437-d02773c3435e.JPG)
![IMG_4369](https://user-images.githubusercontent.com/50646972/103144700-df181380-4768-11eb-93bb-1b5f1b8491a1.JPG)

Looking forward to your reply, thank you very much.
@myleott

**Comment by myleott** [comment]
The "ups" key corresponds to updates-per-second. So the step time here would be `(1 / ups) = (1 / 1.11) = 0.9 seconds`
