### ISSUE TITLE
Possible to load wav2vec 2.0 finetuned models with load_model_ensemble_and_task ?

### ISSUE THREAD

**Issue by prsull** [pytorch/fairseq#3077]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

Is it possible and intended to load wav2vec 2.0 finetuned models using load_model_ensemble_and_task()?  This works fine for non-finetuned pre-trained wav2vec 2.0 models as well as the wav2vec 1.0 pre-trained models, however I run into issues with using this for the fine-tuned models, and am not sure if this is simply because it isn't designed for use with them, or an oversight. The only documentation for the wav2vec 2.0 models is through the CLI tools.

Issue seems to be that the fine-tuned models depend on the label dictionary files from the fine tuning (which can't be loaded since the path is on someone else's computer)

#### Code

model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([filename])

works fine for non-finetuned files (e.g. libri960_big.pt) however, runs into a missing file error with any of the finetuned files (e.g. wav2vec_big_960h.pt)

### Error Code
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-13-bf8e3570ffee> in <module>
      1 filename = model_names[3]
      2 print(filename)
----> 3 model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(["./checkpoints/"+ filename], task=None)
      4 
      5 

~/fairseq/fairseq/checkpoint_utils.py in load_model_ensemble_and_task(filenames, arg_overrides, task, strict, suffix, num_shards, state)
    313 
    314             if task is None:
--> 315                 task = tasks.setup_task(cfg.task)
    316 
    317             # build model for ensemble

~/fairseq/fairseq/tasks/__init__.py in setup_task(cfg, **kwargs)
     42     assert task is not None, f"Could not infer task type from {cfg}"
     43 
---> 44     return task.setup_task(cfg, **kwargs)
     45 
     46 

~/fairseq/fairseq/tasks/audio_pretraining.py in setup_task(cls, cfg, **kwargs)
    119         if cfg.labels:
    120             dict_path = os.path.join(cfg.data, f"dict.{cfg.labels}.txt")
--> 121             target_dictionary = Dictionary.load(dict_path)
    122         else:
    123             target_dictionary = None

~/fairseq/fairseq/data/dictionary.py in load(cls, f)
    213         """
    214         d = cls()
--> 215         d.add_from_file(f)
    216         return d
    217 

~/fairseq/fairseq/data/dictionary.py in add_from_file(self, f)
    226                     self.add_from_file(fd)
    227             except FileNotFoundError as fnfe:
--> 228                 raise fnfe
    229             except UnicodeError:
    230                 raise Exception(

~/fairseq/fairseq/data/dictionary.py in add_from_file(self, f)
    223         if isinstance(f, str):
    224             try:
--> 225                 with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
    226                     self.add_from_file(fd)
    227             except FileNotFoundError as fnfe:

FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/abaevski/data/speech/libri/960h/wav2vec/raw/dict.ltr.txt'

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 1.0
 - PyTorch Version (e.g., 1.0): 1.6
 - OS (e.g., Linux): CentOS
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):   
 - git clone https://github.com/pytorch/fairseq
cd fairseq
pip install --editable ./
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: N/A
 - Any other relevant information:

**Comment by jubick1337** [comment]
When you trying to load pretrained model it also requiers target dictionary that was used for fine tuning model that you're trying to load.
You can try to load checkpoint with
```
temp_cp = torch.load('model.pt')
```
and get config out of checkpoint, change target dict path, save checkpoint again and rerun your code
