### ISSUE TITLE
Trouble with incremental_state for text generation

### ISSUE THREAD

**Issue by tommccoy1** [pytorch/fairseq#3079]
### Before asking:   
1. search the issues.   [Done]
2. search the docs.    [Done]

#### What is your question?

I am using a Transformer Language Model for text generation (i.e., feed in a prompt, and have the model continue it). It works fine when I recompute all of the hidden states at each time step, but it does not work when I cache the hidden states using the incremental_state argument (even though this should, in theory, give the same output as recomputing the hidden states every time). 

In my specific case, I need to be able to use incremental_state, because I am doing an experiment that requires direct manipulation of the internal states. Below I've pasted a minimum working example showing the different results that I get when using incremental_state vs. not using it. Can you tell what I'm doing wrong?

#### Code

```
import torch
from fairseq.models.transformer_lm import TransformerLanguageModel
import argparse
from fairseq import checkpoint_utils, distributed_utils, options, progress_bar, tasks, utils

parser = argparse.ArgumentParser()
args = parser.parse_args()

# To simplify this example, I'm just defining all
# the model hyperparameters here
args.task = "language_modeling"
args.data = "data-bin/wikitext-103/"
args.output_dictionary_size = -1
args.arch = "transformer_lm_wiki103"
args.decoder_layers = 16
args.decoder_attention_heads = 8
args.dropout = 0.0
args.adaptive_input = True
args.tie_adaptive_weights = True
args.adaptive_input_cutoff = '20000,60000'
args.adaptive_softmax_cutoff = '20000,60000'
args.no_decoder_final_norm = True
args.tie_adaptive_proj = True
args.decoder_embed_dim = 1024
args.decoder_ffn_embed_dim = 4096

# Loading the model from here: https://github.com/urvashik/knnlm/blob/master/fairseq_cli/interactive.py
task = tasks.setup_task(args)
model = task.build_model(args)
model.load_state_dict(torch.load("wt103_checkpoint_best.pt", map_location=torch.device('cpu'))["model"])
model.eval()

trg_dict = task.target_dictionary

index2word = {}
for key in trg_dict.indices:
    index2word[trg_dict.indices[key]] = key

index2word[trg_dict.eos()] = "<eos>"
index2word[trg_dict.unk()] = "<unk>"

def encode_prompt(prompt):
    encoding = []
    words = prompt.strip().split()
    for word in words:
        if word == "<eos>":
            encoding.append(trg_dict.eos())
        elif word not in trg_dict:
            encoding.append(trg_dict.unk())
        else:
            encoding.append(trg_dict.indices[word])

    return torch.LongTensor([encoding])


# Text generation without any incremental state
def get_next_word(prompt):
    output = model.decoder(encode_prompt(prompt))
    probs = model.decoder.adaptive_softmax.get_log_prob(output[0], target=None)[0]
    topv, topi = probs[-1].topk(1)
    word = index2word[topi.item()]

    return word

# gives "the"
print(get_next_word("Barack Obama is the President of"))

# gives "United"
print(get_next_word("Barack Obama is the President of the"))


# Text generation with an incremental state
def generate(prompt):
    generated = []
    output, inc_state = model(encode_prompt(prompt))

    word = get_next_word(prompt)
    generated.append(word)

    for pos in range(4):
        output, inc_state = model(encode_prompt(word), incremental_state=inc_state)

        probs = model.decoder.adaptive_softmax.get_log_prob(output, target=None)
        topv, topi = probs.topk(1)
        word = index2word[topi[-1].item()]

        generated.append(word)

    return " ".join(generated)

# If this was the same as non-incremental decoding, it
# should start with "the United", but instead it
# starts with "the first".
print(generate("Barack Obama is the President"))

# Note that "first" is the output of the following. This makes
# me think that the "generate" function above is not
# properly incorporating the incremental_state, as it gives
# the same output as it would without the incremental_state
print(get_next_word("the"))

```

#### What have you tried?

I have tried several variations of the code above. I have also tried the "Example usage" setup from [the language model example](https://github.com/pytorch/fairseq/tree/master/examples/language_model), but I could not get that to work for my purposes, since I need to be able to manipulate the internal states before generating outputs, and I could not find a way to do that using the torch.hub setup or the custom_lm.sample setup.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): MacOS
 - How you installed fairseq (`pip`, source): "pip install --editable ." from the master branch on GitHub
 - Build command you used (if compiling from source): pip install --editable .
 - Python version: 3.7.3
 - CUDA/cuDNN version: N/A (using a CPU)
 - GPU models and configuration: N/A (using a CPU)
 - Any other relevant information: N/A

**Comment by menphix-watanabe** [comment]
@tommccoy1 Hi! Did you resolve this issue? I think I'm facing the same issue as you, the results I got by supplying `incremental_state` is the same as not supplying `incremental_state`.

**Comment by menphix-watanabe** [comment]
I think this might be because in the first `output, inc_state = model(encode_prompt(prompt))` call, `incremental_state` is not provided so it took on the default value of `None`. I think it needs to be set to an empty dictionary `{}` for the decoder to output the next incremental state.

**Comment by tommccoy1** [comment]
Unfortunately, I was never able to figure out how to fix this, and it is no longer relevant because I ended up changing the setup of my experiment to a version that does not require manipulating the internal state. I hope that the fix you proposed works for you!

**Comment by menphix-watanabe** [comment]
Thanks for the reply! I think setting the initial `incremental_state = {}` solved it for me :)
