### ISSUE TITLE
Transf-LM gives a very high WER compared to Viterbi

### ISSUE THREAD

**Issue by LamyaMohamed** [pytorch/fairseq#3080]
Hello,

I tested` wav2vec_small_960h.pt` downloaded from pre-trained models [here](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec) against test-clean set of librispeech. 
Using viterbi algorithm I got a **WER around `3`.**
Also, I used a transformer language model `lm_librispeech_word_transformer.pt ` from [here](https://github.com/facebookresearch/wav2letter/tree/master/recipes/sota/2019#pre-trained-language-models) and I downloaded the associated dictionary and didn't forget to upper-case it, however, I got a **WER of `81.2823`.**

It's worh mentioning that I only installed python bindings of wav2letter, and when I tried the evaluation command at first with LM  I got this error: 
`ImportError: cannot import name 'LexiconFreeDecoder' from 'wav2letter.decoder'`
but I found the solution [here](https://github.com/facebookresearch/wav2letter/issues/775).

Also, is it normal that the evaluation with the transformer LM took 7 hours on test-clean?

**Comment by alexeib** [comment]
yes, transformer lm does an evaluation for each token so it is quite expensive. a more realistic approach is to emit multiple hypothesis with an n-gram lm and then rerank using a transformer lm - this is much quicker and usually is pretty similar in accuracy as using a fused transformer lm 

as for accuracy drop - did you use the word score and silence score for transformer lm (it is in the appendix in the paper)? did you upper case the dict? also have you looked at the predicted hypothesis? does anything look strange?

**Comment by LamyaMohamed** [comment]
yes I did use the word score and silence score, but I'm not sure about their values, I used the same values as [here]( https://github.com/pytorch/fairseq/tree/master/examples/wav2vec#evaluating-a-ctc-model). This is my evaluation command:
`python3 examples/speech_recognition/infer.py /home/lamya/Downloads/test-clean/LibriSpeech/output --task audio_pretraining --nbest 1 --path /home/lamya/Downloads/wav2vec_small_960h.pt --gen-subset test --results-path /home/lamya/Downloads/test-clean/LibriSpeech/results  --w2l-decoder fairseqlm --lm-model '/home/lamya/Downloads/lm_librispeech_word_transformer.pt' --lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 1280000 --post-process letter`

I think according to the appendix lm-weight should be 0.92 and word-score -0.86, but what about sil-weight?

Yes I did upper-case the dict, and I looked at the predicted hypothesis and it was really unreadable..

Also I've tried another LM, that I trained on my own language using the commands [here](https://github.com/pytorch/fairseq/tree/master/examples/language_model#training-a-transformer-language-model-with-the-cli-tools) and it gives me a high WER (~99%) and before it was below 20%.

**Comment by LamyaMohamed** [comment]
After setting `--lm-weight` to 0.92 and `--word-score` to -0.86, the WER with Transf-LM became 11.9%!
But it still greater than WER using Viterbi. What do you suggest for hyper-parameter-tuning?
