### ISSUE TITLE
Availability of the best Base (smaller) multilingual models from the XLSR paper

### ISSUE THREAD

**Issue by ajd12342** [pytorch/fairseq#3086]
## 🚀 Feature Request
The paper [Unsupervised Cross-lingual Representation Learning for speech recognition](https://arxiv.org/abs/2006.13979) demonstrates experiments using two sizes of the XLSR architecture; Base and Large. I appreciate that the XLSR-53 Large model has been released; it is very useful for multilingual experiments. However, could the best available Base XLSR system also be released? This would be easier for the purpose of finetuning for researchers with limited number of GPU resources.

**Comment by alexeib** [comment]
@aconneau

**Comment by aconneau** [comment]
Hey @ajd12342 , 

unfortunately I have not trained an XLSR-53 model with the Base architecture. But I understand the constraint, and will definitely consider releasing a Base model as well for the next version of XLSR. For now I would suggest increasing the "update-freq" parameter and reducing the number of GPUs you are using. You can also potentially consider reducing the number of updates during which the model is frozen at the beginning (which is usually set to 10k).

Best,
Alexis

**Comment by ajd12342** [comment]
Thanks! I will try your suggestions. Looking forward to the next version of XLSR, too. I will close the issue now.
