### ISSUE TITLE
Does "Roberta on K-means codes" of vq-wav2vec include finetuning?

### ISSUE THREAD

**Issue by syoamakase** [pytorch/fairseq#3088]
#### What is your question?

You uploaded the pre-trained model "Roberta on K-means codes" in the vq-wav2vec.
Did this Roberta model include fine-tuning like "Effectiveness of self-supervised pre-training for speech recognition (Baevski et al., 2019)?"

Thank you.

**Comment by alexeib** [comment]
no, this model was not fine-tuned. but it shouldn't be very difficult to fine tune it (it is essentially the same model as in that paper, just minus the fine tuning).

**Comment by syoamakase** [comment]
Thank you for your help!

**Comment by pilarspeakai** [comment]
Hi, I have a question about using the "Roberta on K-means codes" model with the right dictionary.

If I use the dict.txt that comes in the compressed file, the obtained codes are different than if I use the `model.task.source_dictionary.encode_line` method. Both methods were mentioned as valid in https://github.com/pytorch/fairseq/issues/1793.

However, if use the dict.txt, I obtain codes that seem to be outside of the embedding vocabulary, getting an index error. If I use `model.task.source_dictionary.encode_line` I do get values that are processed when running `model.extract_features`.

Could you let me know which is the correct method to use?

I'm loading the model like this:
``` 
from fairseq.models.roberta import RobertaModel
model = RobertaModel.from_pretrained('./', checkpoint_file='bert_kmeans.pt')
```

Thank you!

**Comment by alexeib** [comment]
sorry i am not sure i follow. 

when you load a model, one of the arguments to the "from_pretrained" method is to specify "data path". this is the path where the dictionary will be loaded. i think by default it is current working directory. what dict do you have there? that is what's going to be loaded and used when you do "encode_line"
