### ISSUE TITLE
Freezing Encoder, Decoder or Embedding in mBART

### ISSUE THREAD

**Issue by kaushal0494** [pytorch/fairseq#3089]
### Before asking:   
1. search the issues.   Yes
2. search the docs.    Yes

#### What is your question? 
How can I freeze the decoder's parameters and words embedding (only want to update encoder's parameters)  in mBART fine-tuning? Thank you!

**Comment by myleott** [comment]
This isn't directly supported by command-line arguments, but you can modify the model code to freeze parameters by setting `requires_grad=False` for them.

While not directly applicable, here's an example of how the Linformer paper authors froze some parameters in their work: https://github.com/pytorch/fairseq/blob/5a3e51d21187415a66632f65e92c71de61367a93/examples/linformer/linformer_src/modules/multihead_linear_attention.py#L108-L111

**Comment by kaushal0494** [comment]
Thank you @myleott
