### ISSUE TITLE
How to install pytorch, fairseq and GPU support?

### ISSUE THREAD

**Issue by DarrenCook** [pytorch/fairseq#3091]
I've been trying to use conda to install pytorch 1.71, with GPU support for cuda 11.1, and fairseq 0.10.1, on Linux.

I started a StackOverflow question (https://stackoverflow.com/q/65543178/841830), which I've self-answered but my answer is only useful for the case of no GPU support.

A summary:

If I use pytorch channel to install pytorch and cudatoolkit=11.0, then conda-forge to install fairseq 0.10.1, it all installs, and I can confirm `torch.cuda.is_available()` is true, but fairseq won't work with my Transformer model, as described in the StackOverflow question. (fairseq 0.9.0 also fails.)

If I install everything from the conda-forge channel, then my fairseq Transformer model works fine, but it is using the CPU and `torch.cuda.is_available()` is false.

If I try to just use the conda-forge channel, and specify `pytorch-gpu`, it refuses to install, as that version only offers cuda 10.2 and earlier support. No cuda 11.1 support.

Surely someone must have got this combination of software working together? I'm not tied to conda - ironically I am using it because I thought it would give me the smoothest install. If no-one has any ideas, my next try will be wiping conda and trying with pip.

Other information: Python 3.8,  NVIDIA-SMI 455.38.

**Comment by myleott** [comment]
It's possible there's a bug in fairseq in the case of the GPU install. Assuming PyTorch + GPU support is working (`torch.cuda.is_available()` returns True), then based on the SO post it looks like the following produces an error, correct?
```python
model = TransformerModel.from_pretrained(...)
model.eval()
model.cuda()
inputs = [model.binarize(encode(src, str)) for str in texts]
batched_hypos = model.generate(inputs, beam)
```

Can you share more details about the model, encoding, etc.?

For example, this seems to work fine for me on fairseq==0.10.1 using [this model](https://github.com/pytorch/fairseq/tree/master/examples/scaling_nmt#pre-trained-models):
```python
model = TransformerModel.from_pretrained("wmt16.en-de.joined-dict.transformer", "model.pt")
model.eval()
model.cuda()
model.generate(model.binarize("Hel@@ lo world"), 5)
```

**Comment by DarrenCook** [comment]
I got this working earlier today by ignoring the advice to not mix conda and pip. So from a fresh machine I did:

```
sudo apt install python3-dev git g++
# install Anaconda3-2020.11-Linux-x86_64.sh from anaconda.com
# Set up and activate a conda env called "test"
conda install pytorch cudatoolkit=11.0 -c pytorch
```

And then:

```
git clone https://github.com/pytorch/fairseq
cd fairseq
pip install --editable ./

pip install sentencepiece
```

What I couldn't get to work was the apex install. It fails with "pip._internal.operations.install.legacy.LegacyInstallFailure". It appears this is either due to a clash with cuda 11.1, or with the 3090 GPU.

So, as it was optional, I've left apex for the moment. But it made me wonder if the problems I had after installing fairseq using conda was due to some cuda version differences?

**Comment by myleott** [comment]
Ah, that makes sense, glad it's working now!

Apex is indeed optional. I'm on cuda 11 and can confirm apex build seems fine, but good to know that there may be issues starting with cuda 11.1.
