### ISSUE TITLE
Errors when using roberta.extract_features_aligned_to_words

### ISSUE THREAD

**Issue by yyhyplxyz** [pytorch/fairseq#3094]
When using extract_features_aligned_to_words to encode some sentences, like "It can’t be me, I’m standing right here.", the following error will occur.
`Traceback (most recent call last):
  File "D:/Research/nlp project/code/test.py", line 50, in <module>
    doc = roberta.extract_features_aligned_to_words("It can’t be me, I’m standing right here.")
  File "C:\Users\Administrator\PycharmProjects\pytorch\venv\lib\site-packages\fairseq\models\roberta\hub_interface.py", line 133, in extract_features_aligned_to_words
    alignment = alignment_utils.align_bpe_to_words(self, bpe_toks, spacy_toks_ws)
  File "C:\Users\Administrator\PycharmProjects\pytorch\venv\lib\site-packages\fairseq\models\roberta\alignment_utils.py", line 39, in align_bpe_to_words
    assert "".join(bpe_tokens) == "".join(other_tokens)
AssertionError`
The specific local values in align_bpe_to_words is shown as below. 
![image](https://user-images.githubusercontent.com/24438083/103554744-59bffc00-4eea-11eb-9dd2-59a53235da2b.png)

This error won't usually happen. If the sentence is "Yes you did! What was it?", everything is OK. So I'm wondering what I can do to prevent such errors from happening. 
My fairseq version is 1.0, pytorch version is 1.5 and python version is 3.7.
Thanks for your help in advance!

**Comment by myleott** [comment]
Unfortunately the `extract_features_aligned_to_words` is very robust to all inputs, since the alignment procedure is very simplistic. One issue I've seen in this past is that it's important to remove any double-spaces in the input.
