### ISSUE TITLE
speech-to-text example 2 computes BLEU on BPEs, not detokenised text

### ISSUE THREAD

**Issue by bhaddow** [pytorch/fairseq#3095]
## 🐛 Bug

In speech-to-text example 2, the fairseq-generate command provided for ST (speech translation) runs sacrebleu. However it does not undo pre-processing, so bleu is calculated on text that has been split into BPEs. This gives results that are not comparable with any other published results, and is poor experimental procedure. Possibly the BLEU scores in the table in the README have been calculated in this way, and so should be updated.

### To Reproduce
Follow example 2
 1. Prepare must-c data
 2. Train ASR
 3. Train ST
 4. Run the provided generate command with the trained model.

### Expected behavior

I should be able to reproduce the expected bleu scores. In fact my bleu score is lower, but if I extract the translations, detokenise and run sacrebleu, then I get an even lower bleu score. By extracting the BPEs, and running  sacrebleu on them, I can verify that fairseq is using this approach.

### Environment

 - fairseq Version (e.g., 1.0 or master: master
 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Ubuntu
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): pip install --editable ./
 - Python version: 3.7.9
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: GTX 1080
 - Any other relevant information:

**Comment by myleott** [comment]
@kahne can you please look into this?

**Comment by kahne** [comment]
Hi @bhaddow, thanks for reporting this issue. The bug seems to be introduced later by a different pull request (unexpectedly reverting the S2T updates to `fairseq-generate` for de-tokenization). The results in our paper/README.md should not be affected by this. I will make a fix today and let you know.

**Comment by kahne** [comment]
The bug fix has been pushed to the latest master branch. Thanks again for reporting the issue.

**Comment by bhaddow** [comment]
Thanks for the quick response!
