### ISSUE TITLE
En-Ja, En-Lv data missing for Speech-to-text CoVoST2 experiment

### ISSUE THREAD

**Issue by devgunn** [pytorch/fairseq#3099]
## 🐛 Bug

En-Ja, En-Lv data missing for Speech-to-text CoVoST2 dataset,
possibly file link is broken or wrong tar files (empty inside) are uploaded.
All different EN_XX languages except for Ja, Lv are good.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/13184386/103627785-6e030800-4f81-11eb-987e-f734e52746da.png">

[examples/speech_to_text/prep_covost_data.py#L56](https://github.com/pytorch/fairseq/blob/336942734c85791a90baa373c212d27e7c722662/examples/speech_to_text/prep_covost_data.py#L56)

<img width="528" alt="image" src="https://user-images.githubusercontent.com/13184386/103627893-8ffc8a80-4f81-11eb-8ddd-fdd174600a30.png">

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Download En-Ja, En-Lv data for Speech-to-text CoVoST2 experiment with following link
2. For En-Ja [https://dl.fbaipublicfiles.com/covost/covost_v2.en_ja.tsv.tar.gz](https://dl.fbaipublicfiles.com/covost/covost_v2.en_ja.tsv.tar.gz)
3. For En-Lv [https://dl.fbaipublicfiles.com/covost/covost_v2.en_lv.tsv.tar.gz](https://dl.fbaipublicfiles.com/covost/covost_v2.en_lv.tsv.tar.gz)
4. Untar and check 'covost_v2.en_ja.tsv', 'covost_v2.en_lv.tsv' files

### Expected behavior
En-Ja, En-Lv tsv files are not supposed to be empty.

### Environment

 - fairseq Version (e.g., 1.0 or master): https://github.com/pytorch/fairseq/tree/336942734c85791a90baa373c212d27e7c722662
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by kahne** [comment]
Thanks for reporting the issue! I've re-uploaded the corrupted files. Please remove the old files and re-download via either the script or the same links manually.

**Comment by KangTomwk** [comment]
Hello, Do you know where to download dict. en_ XX. Txt and dict.zh_CN.txt these two files？？
