### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by Hannabrahman** [pytorch/fairseq#310]
Hi,

I just read your impressive paper: Hierarchical Neural Story Generation
In this regard, I have some ambiguities about the training and testing process.

So in training, you are given prompts and their associated story. However; in the testing the model in only given the prompts, right? So, I do not understand why the model needs to generate a prompt if it has already that? 
I just do not get why does it do the prompt generation?

Any explanation is highly appreciated

**Comment by huihuifan** [comment]
In the paper, we use the prompt generation to empower fully AI generated
stories. A language model generates the prompt and then we do prompt to
story with seq to seq. Exploring data augmentation is interesting, but we
did not do this.

**Comment by villmow** [comment]
Hi @huihuifan, 

I have read your paper as well and have a question regarding the vocabulary. You said the large size of the vocabulary makes the model computationally challenging. Could you elaborate why you chose not to use BPE on the dataset?

Thank you very much in advance!

**Comment by huihuifan** [comment]
BPE would be a good choice :) but we reduced the vocabulary size by modeling more common words.

**Comment by Hannabrahman** [comment]
@huihuifan I actually understand that because language models can be trained from abundantly available unsupervised text corpora, integrating them with the seq2seq model is very helpful.
I read the cold fusion paper. But still, cannot figure out why in your case that would be beneficial since you pretrained and trained on the same WRITINGPROMPT dataset. What is the intuition behind that guarantees the second seq2seq model will focus on what the first model failed to learn?

Really appreciate your explaination

**Comment by huihuifan** [comment]
Hi, sorry I missed this! Must have missed the email. The thought is that- in the case of a dataset such as Writing Prompts where the relationship between the source sequence and the target sequence is complex and subtle, many seq2seq models degenerate into language models. Contrast this with a task such as translation, where the model relies heavily on the source sequence to write the target. In this case, the first seq2seq model essentially acts as a language model over stories. Then, fusing this pretrained "language model" with a second model allows the second model to focus on these complex relationships as it has help predicting lower level things, such as when to write "the." You can think of the second model as a residual-like connection- given the trained model, it learns new things.
