### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'task'

### ISSUE THREAD

**Issue by wiktor7245** [pytorch/fairseq#3106]
Hi, when i try to generate translation from trained mode  with command:
```
fairseq-interactive output --path checkpoints/fconv/checkpoint1.pt --beam 5 --cpu --task translation --optimizer sgd
```
I get error:
```
AttributeError: 'NoneType' object has no attribute 'task'
```
I tried this on Ubunu 20.04, Google Colab and i get the same error.
I am using the newest version of fairseq

**Comment by Joshwlks** [comment]
bump
I am getting the same issue

**Comment by wying8349** [comment]
Same issue. Any suggestions?

**Comment by Ramlinbird** [comment]
Same issue. Any suggestions?

**Comment by masus04** [comment]
Has there been any progress on this?

In my case I took over a repository in which the model is loaded using the following:
`fairseq.checkpoint_utils.load_model_ensemble_and_task(filepath, arg_overrides=arg_dict)`

The `arg_overrides` dict contains a key 'task' which at some point in the library is written to state[args], which seems to be None.
But why would state[args] be None?

**Comment by Joshwlks** [comment]
I managed to solve this by installing Fairseq via the Github Repo rather than via Pip Install.

**Comment by masus04** [comment]
> I managed to solve this by installing Fairseq via the Github Repo rather than via Pip Install.

Are you using a different version from GitHub than is available from Pip?

**Comment by Joshwlks** [comment]
> Are you using a different version from GitHub than is available from Pip?

From what I remember the GitHub version is quite a bit more up to date as the last release to Pip was Jan 5

**Comment by Old-Young233** [comment]
bump
I am getting the same issue

**Comment by masus04** [comment]
Installing with pip from GitHub did the trick for me.

**Comment by Old-Young233** [comment]
> 
The problem I ran into was that I trained a translation model in giuhub's 0.10.1 download, and then tried to use the model in a paper's open source code, but  appeared when loading `AttributeError:'NoneType' object has no attribute 'task'`

**Comment by S-GeGe** [comment]
> 

How did you solve this problem?

**Comment by S-GeGe** [comment]
How did you solve this problem? @Old-Young233

**Comment by S-GeGe** [comment]
How did you solve this problem? @wiktor7245

**Comment by Lihwnlp** [comment]
Check to see if it is a version issue, which can occur when the fairseq version of the training model produces a different fairseq version of the translation

**Comment by tqzhou75** [comment]
@Lihwnlp Is there a suitable version

**Comment by tqzhou75** [comment]
I had the same problem   AttributeError: 'NoneType' object has no attribute 'task'
