### ISSUE TITLE
Fine-tuning mBART for unseen language

### ISSUE THREAD

**Issue by sumanthd17** [pytorch/fairseq#3108]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
The code in the README for mBART provides code snippet for English Romanian task. Do we have to any modifications to the code to fine-tune the model for supporting unseen language either or source side or target side?

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by sumanthd17** [comment]
@sshleifer I've seen you posted a lot of content on BART and mBART, do you know about this?

Sorry for troubling you.

**Comment by sshleifer** [comment]
From grep, I think the answer is no, the code in [`./examples/mbart/README.md`](./examples/mbart/README.md) is all that the authors released. 
Sorry! Interesting question :)

**Comment by thpun** [comment]
In [this paper](https://arxiv.org/abs/2008.00401), the authors talked about how to create mBART50 from mBART25.
> We take the public available pretrained mBART model which was pretrained on 25 languages and extend its embedding layers with randomly initialized vectors for an extra set of 25 language tokens.

So i dont think you need to modify the fairseq code to fine-tune the model. But you may need some code to extend the embedding layer dimension of the checkpoint before you call `fairseq-train`

**Comment by kurtabela** [comment]
Did you ever find a solution for this? I tried following the exact setup but getting an error that the architectures don't match, I'm assuming because I need to some extra code like thpun explained above - not sure if you already have a working implementation somewhere
