### ISSUE TITLE
Loading wav2vec2.0 error

### ISSUE THREAD

**Issue by SolomidHero** [pytorch/fairseq#3110]
Hello! I am trying to transfer knowledge from pre-trained wav2vec2.0 model. (from [here](https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/README.md))

From the docs of wav2vec, I tried the common way of loading pre-trained model:
```python
cp_path = 'libri960_big.pt' # some model name
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])
```
This lines works for "no finetuning" models, but  fails for some of checkpoints (that labeled as fine-tuned (with 10m, 1h, 100h and other datasets)) with similar trace (`wav2vec_big_10m.pt` checkpoint for example):
```pytb
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-adea221460b0> in <module>()
      4 wav2vec_path = '/content/wav2vec_big_10m.pt'
      5 # wav2vec_path = 'libri960_big.pt'
----> 6 model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([wav2vec_path])
      7 model = model[0].to(device)
      8 model.eval()

2 frames
/usr/local/lib/python3.6/dist-packages/fairseq/checkpoint_utils.py in load_model_ensemble_and_task(filenames, arg_overrides, task, strict, suffix, num_shards)
    285                 # build model for ensemble
    286                 model = task.build_model(args)
--> 287             model.load_state_dict(state["model"], strict=strict, args=args)
    288         ensemble.append(model)
    289     return ensemble, args, task

/usr/local/lib/python3.6/dist-packages/fairseq/models/fairseq_model.py in load_state_dict(self, state_dict, strict, args)
     97         self.upgrade_state_dict(state_dict)
     98         new_state_dict = prune_state_dict(state_dict, args)
---> 99         return super().load_state_dict(new_state_dict, strict)
    100 
    101     def upgrade_state_dict(self, state_dict):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   1050         if len(error_msgs) > 0:
   1051             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
-> 1052                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1053         return _IncompatibleKeys(missing_keys, unexpected_keys)
   1054 

RuntimeError: Error(s) in loading state_dict for Wav2VecCtc:
	size mismatch for w2v_encoder.proj.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in current model is torch.Size([512, 1024]).
	size mismatch for w2v_encoder.proj.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
```

Actually this is problem (bug in my opinion, because of `build_model` uses config parameter, not checkpoint).

Also, in the paper, downstream task for fine-tuning was phoneme classification on TIMIT (with 39 classes). So I don't quite understand for what last layer is used (with 32 output dim).

I want to use either features from the last layer with shape (batch_size, sequence length, final_dim) or scores for phoneme classes with shape (batch_size, sequence length, n_classes) (similar to PPG feature).
I appreciate any help and advice for this question!

**Comment by jubick1337** [comment]
Could you specify fairseq version that you use?
Did you use pip install fairseq or cloned master branch?

**Comment by SolomidHero** [comment]
Installed via `pip install fairseq`, version is 0.10.2

**Comment by SolomidHero** [comment]
I guess the problems with config and letter dictionary, which were mentioned in many other issues, will be solved in a future release. So, it is ok to end this issue.
