### ISSUE TITLE
Really slow Wav2Vec 2 pretraining

### ISSUE THREAD

**Issue by jubick1337** [pytorch/fairseq#3114]
#### What is your question?
I'm trying to pretrain wav2vec2 base model on my own dataset and it is really slow. I want to speed it up.
My dataset contains about 100 hours of speech.
It's stored in data directory. All of them are single channel 16khz wav files.
This 
```
python examples/wav2vec/wav2vec_manifest.py /path/to/waves --dest /manifest/path --ext $ext --valid-percent $valid
```
runs fine and gives correct manifest.
I expected reasonable slow down compared to original set up of 64 Tesla V100 but not thousand times slower.
Currently one epoch takes 5 minutes and if I want to do 400000 updates it'd take almost 4 years!

#### Code
I don't code anything but here's comand i'm using for training.
```
fairseq-train --distributed-world-size 6 ./manifest/ --save-dir ./res --fp16 --num-workers 16 --task audio_pretraining 
--criterion wav2vec --arch wav2vec2 --log-keys '["prob_perplexity","code_perplexity","temp"]'
--quantize-targets --extractor-mode default --conv-feature-layers '[(512, 10, 5)] + [(512, 3, 2)] * 4 + [(512,2,2)] * 2' 
--final-dim 256 --latent-vars 320 --latent-groups 2 --latent-temp '(2,0.5,0.999995)' --infonce --optimizer adam 
--adam-betas '(0.9,0.98)' --adam-eps 1e-06 --lr-scheduler polynomial_decay --total-num-update 10000 --lr 0.0005 
--warmup-updates 800 --mask-length 10 --mask-prob 0.65 --mask-selection static --mask-other 0 
--encoder-layerdrop 0.05 --dropout-input 0.1 --dropout-features 0.1 --feature-grad-mult 0.1 
--loss-weights '[0.1, 10]' --conv-pos 128 --conv-pos-groups 16 --num-negatives 100 
--cross-sample-negatives 0 --max-sample-size 250000 --min-sample-size 32000 --dropout 0.1 
--attention-dropout 0.1 --weight-decay 0.01 --max-tokens 1400000 --max-update 10000 
--skip-invalid-size-inputs-valid-test --ddp-backend no_c10d --update-freq 64/6 --save-interval 5000
```

#### What have you tried?
I tried installing apex as it should speed up fairseq.
It gave a 2x boost but it's still years to go. 
#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.10.1
 - PyTorch Version (e.g., 1.0) 1.8.0a0+1606899
 - OS (e.g., Linux): Ubuntu 20.04.1 LTS (Focal Fossa)
 - How you installed fairseq (`pip`, source): pip install fairseq==0.10.1
 - Build command you used (if compiling from source): None
 - Python version: Python 3.8.5
 - CUDA/cuDNN version: CUDA 11.1.105
 - GPU models and configuration: six RTX 3090
 - Any other relevant information: I also tested on VM with two rtx 2080 ti

**Comment by jubick1337** [comment]
It seems like wav2vec 2 pretraining uses a lot of ideas form this [paper](https://arxiv.org/pdf/1806.00187.pdf) such as fp16 trainig and large bath sizes.
Can someone confirm that my usage uses it?
I'm not sure if RTX 3090 got speed boost from fp16 as I only found that A100 (from Ampere arch) supports fp16 training  [in this blog](https://developer.nvidia.com/blog/nvidia-ampere-architecture-in-depth/).
Also I don't really understand what is "Large batch size" in my circumstances. I feel like ```--max-tokens``` parameter is resposible for that but in docs it says 

> maximum number of tokens in a batch

**Comment by marma** [comment]
epoch != update

**Comment by apoca909** [comment]
update == step

**Comment by jubick1337** [comment]
Yep @marma @apoca909 I got it but it is still really slow process. I expermiented a lot with different setups an yet to archive training speed that was indicated in original paper.

**Comment by matrixtempnew** [comment]
I am also facing this issue with wav2vec (not 2.0). I have 3 GPUs (each Nvidia Quadro RTX 4000 8 GB). This particular single GPU can't train Wav2vec (getting OOM) so I am using pipelining. While using pipelining I can train it (default batch size) and also GPU VRAM is usage is quite low (approx 3.7, 2.8, 2.8 GB on GPUs). I tried to increase the batch size (set it to 1024 which should give OOM) to speed up the training but it's still slow (trains at the same speed as above) and GPU VRAM usage is the same as in above.

Am I doing something wrong or is it the bug? I tried different batch sizes lesser than 1024 but it's the same.

My command:

```
CUDA_VISIBLE_DEVICES=1,2,3 python train.py /home/user/Documents/ASR --save-dir /home/user --num-workers 4 --max-update 400000 --save-interval 1 --no-epoch-checkpoints \
--arch wav2vec --task audio_pretraining --min-lr 1e-06 --stop-min-lr 1e-09 --optimizer adam --lr 0.005 --lr-scheduler cosine \
--conv-feature-layers '[(512, 10, 5), (512, 8, 4), (512, 4, 2), (512, 4, 2), (512, 4, 2), (512, 1, 1), (512, 1, 1)]' \
--conv-aggregator-layers '[(512, 2, 1), (512, 3, 1), (512, 4, 1), (512, 5, 1), (512, 6, 1), (512, 7, 1), (512, 8, 1), (512, 9, 1), (512, 10, 1), (512, 11, 1), (512, 12, 1), (512, 13, 1)]' \
--skip-connections-agg --residual-scale 0.5 --log-compression --warmup-updates 500 --warmup-init-lr 1e-07 --criterion wav2vec --num-negatives 10 \
--max-sample-size 150000 --max-tokens 1500000 --skip-invalid-size-inputs-valid-test --batch-size 1024 \
--distributed-world-size 3 --nprocs-per-node 3 \
--pipeline-model-parallel --pipeline-balance '[6, 6, 7]' --pipeline-devices '[1,2,3]'
```

**Comment by RuABraun** [comment]
use `--max-tokens` to change batch size @matrixtempnew
