### ISSUE TITLE
(Managing project folders) How to add models and tasks outside of their dedicated folders

### ISSUE THREAD

**Issue by hadyelsahar** [pytorch/fairseq#312]
Hello, 

Is there a possibility of registering Models / Tasks / Architectures outside of the Model / Task folders? 

I am currently using Fairseq for several projects and I would like to keep one source folder for fairseq referring to it from several other project folders.

**Comment by myleott** [comment]
Typically we’d fork train.py and do the additional model imports there. This is what pytorch-translate does.

**Comment by hadyelsahar** [comment]
cool very smooth! will give it a try
Thanks Myle

**Comment by hadyelsahar** [comment]
This doesn't work that smooth unfortunately because of the __init__.py code in the task folder
https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/__init__.py#L59
and similarly in the models folder
https://github.com/pytorch/fairseq/blob/master/fairseq/models/__init__.py#L107

only way that works (still hacky because of code duplication) is to copy similar folder structure as fairseq and duplicate the __init__.py manually in each folder.

**Comment by johntiger1** [comment]
Is there an update to this? Something like a `--use-folder` option to specify an additional area to look, or some way to add to PYTHONPATH
