### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'sacrebleu_char_level'

### ISSUE THREAD

**Issue by rizwan09** [pytorch/fairseq#3126]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 
FILE_PREF=${SAVE_DIR}/output;
RESULT_FILE=${SAVE_DIR}/result.txt;
GOUND_TRUTH_PATH="${path_2_data}/test.target";

fairseq-generate "${path_2_data}/data-bin" $USER_DIR \
    --fp16 \
    --path ${SAVE_DIR}/checkpoint_best.pt \
    --task translation_in_same_language \
    --langs $langs \
    --gen-subset test \
    --source-lang en_XX \
    --target-lang $LANG \
    --sacrebleu \
    --remove-bpe 'sentencepiece'\
    --batch-size 64 \
    --beam 5 > ${FILE_PREF};

2. See error

/home/rizwan/fairseq-0.10.2/fairseq_cli/generate.py:172: UserWarning: --sacrebleu is deprecated. Please use --scoring sacrebleu instead.
  scorer = scoring.build_scorer(args, tgt_dict)
Traceback (most recent call last):
  File "/home/rizwan/anaconda3_2020/envs/fairseq/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/home/rizwan/fairseq-0.10.2/fairseq_cli/generate.py", line 379, in cli_main
    main(args)
  File "/home/rizwan/fairseq-0.10.2/fairseq_cli/generate.py", line 41, in main
    return _main(args, sys.stdout)
  File "/home/rizwan/fairseq-0.10.2/fairseq_cli/generate.py", line 172, in _main
    scorer = scoring.build_scorer(args, tgt_dict)
  File "/home/rizwan/fairseq-0.10.2/fairseq/scoring/__init__.py", line 54, in build_scorer
    return _build_scorer(args)
  File "/home/rizwan/fairseq-0.10.2/fairseq/registry.py", line 54, in build_x
    return builder(args, *extra_args, **extra_kwargs)
  File "/home/rizwan/fairseq-0.10.2/fairseq/scoring/bleu.py", line 41, in __init__
    character_tokenization=self.args.sacrebleu_char_level,
AttributeError: 'Namespace' object has no attribute 'sacrebleu_char_level'

### Environment

 - fairseq Version (0.10.2):
 - PyTorch Version (1.7.1)
 - OS (Linux):
 - How you installed fairseq (source):
 - Build command you used (pip install -e .):
 - Python version: 3.8
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: 
 - Any other relevant information:

**Comment by kahne** [comment]
We had a bug fix after the v0.10.2 release and will include it in the next release. For now, can you pull the latest master branch and install it via `pip install -e <fairseq repo root>`?

**Comment by kahne** [comment]
I will close the issue for now. Feel free to re-open if it's still unsolved.
