### ISSUE TITLE
`--lang-pairs` of mMBART50 are not provided

### ISSUE THREAD

**Issue by thpun** [pytorch/fairseq#3130]
## 📚 Documentation

cc. @tangyuq 

mMBART50 1-N, N-1, N-N models are released and the generation command is provided in [here](https://github.com/pytorch/fairseq/tree/master/examples/multilingual#mbart50-models). But `lang_pairs` used in training commands of the 3 models is not given.

As written in the same [README](https://github.com/pytorch/fairseq/tree/master/examples/multilingual#generate),
> Options --lang-dict and --lang-pairs are needed to tell the generation process the ordered list of languages and translation directions that the trained model are awared of; **they will need to be consistent with the training.**

Running the given command (without `--lang-pairs`) yields the following error:
```
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/workspace/fairseq/fairseq_cli/generate.py", line 389, in cli_main
    main(args)
  File "/workspace/fairseq/fairseq_cli/generate.py", line 50, in main
    return _main(cfg, sys.stdout)
  File "/workspace/fairseq/fairseq_cli/generate.py", line 83, in _main
    task = tasks.setup_task(cfg.task)
  File "/workspace/fairseq/fairseq/tasks/__init__.py", line 41, in setup_task
    return task.setup_task(cfg, **kwargs)
  File "/workspace/fairseq/fairseq/tasks/translation_multi_simple_epoch.py", line 126, in setup_task
    cls.load_dictionary, args, **kwargs
  File "/workspace/fairseq/fairseq/data/multilingual/multilingual_data_manager.py", line 331, in prepare
    "--lang-pairs is required. List all the language pairs in the training objective."
ValueError: --lang-pairs is required. List all the language pairs in the training objective.
```

**Comment by lematt1991** [comment]
When you unzip the checkpoint file that you download from the README that you linked, you should see a file named `ML50_langs.txt` which contains all of the languages you need to list (ex: `mbart50.pretrained/ML50_langs.txt`).

**Comment by thpun** [comment]
I did find `ML50_langs.txt`. But that file should be supplied as `--lang-dict` instead of `--lang-pairs`.
https://github.com/pytorch/fairseq/blob/bfcc13e20a6cfa18fb25daaae39644f9b7872699/fairseq/data/multilingual/multilingual_data_manager.py#L104-L111
https://github.com/pytorch/fairseq/blob/bfcc13e20a6cfa18fb25daaae39644f9b7872699/fairseq/tasks/translation_multi_simple_epoch.py#L70-L72
And i also saw `ML50_langs.txt` has 52 language codes. So is ML50 actually trained with 52 languages?
