### ISSUE TITLE
Bad initialization in ConvTBC

### ISSUE THREAD

**Issue by markovka17** [pytorch/fairseq#3131]
## 🚀 Feature Request
Add `reset_parameters` method to `ConvTBC` and call it in  `__init__`.

### Motivation
Currently, `ConvTBC` weights are initialised with zeros. It often cause NaN outputs.

### Pitch
Add method `reset_parameters` as in pytorch ConvNd.
I think naive copy&paste from `conv1d` will work good enough :)

**Comment by myleott** [comment]
That sounds great, can you send a PR? We can copy the weight init from here: https://github.com/pytorch/fairseq/blob/1164a7fc432a188d401895018eaa85175fb06f9d/fairseq/models/fconv.py#L688-L696

**Comment by markovka17** [comment]
This initialization seems a little strange to me. It looks like `xavier_normal_` but not exactly.
I suggest adding it like this:
```
def reset_parameters(self):
    nn.init.xavier_normal_(self.weight)
    nn.init.constant_(self.bias, 0)
```

**Comment by myleott** [comment]
Sure, your simplified default looks good, just please keep the wrapped version in fconv.py the way it is to match the original fconv paper
