### ISSUE TITLE
Classical Structured Prediction Losses for Sequence to Sequence Learning

### ISSUE THREAD

**Issue by haorannlp** [pytorch/fairseq#3133]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
I've tried to implement the Sequence Negative Loglikehood loss in Fairseq 0.9 using the code in ``https://github.com/pytorch/fairseq/tree/classic_seqlevel/fairseq/criterions``.
The differences are:
1) In line 94-103 of ``fairseq_sequence_criterion.py``, I did not detokenize and then tokenize.
The original code:
```
 for i, hypos_i in enumerate(hypos):
       ref = utils.lstrip_pad(target[i, :], self.pad_idx).cpu()
       r = self.dst_dict.string(ref, bpe_symbol='@@ ', escape_unk=True)
       r = tokenizer.Tokenizer.tokenize(r, self.dst_dict, add_if_not_exist=True)
       for hypo in hypos_i:
                h = self.dst_dict.string(hypo['tokens'].int().cpu(), bpe_symbol='@@ ')
                h = tokenizer.Tokenizer.tokenize(h, self.dst_dict, add_if_not_exist=True)
                # use +1 smoothing for sentence BLEU
                hypo['bleu'] = self._scorer.score(r, h)
 return hypos
```

My modification:
```
       for i, hypos_i in enumerate(hypos):
            ref = utils.strip_pad(target[i, :], self.pad_idx).cpu()
            for hypo in hypos_i:
                # use +1 smoothing for sentence BLEU
                hypo['bleu'] = self._scorer.score(ref, h)
        return hypos
```
2) In line 210-214 of ``fairseq_sequence_criterion.py``, I did not left pad the decoder inputs.
Original code:
```
        input_hypos = [h['tokens'] for hypos_i in hypos for h in hypos_i]
        sample['hypotheses'] = data.LanguagePairDataset.collate_tokens(
            input_hypos, self.pad_idx, self.eos_idx, left_pad=True, move_eos_to_beginning=False)
        input['input_tokens'].data = data.LanguagePairDataset.collate_tokens(
            input_hypos, self.pad_idx, self.eos_idx, left_pad=True, move_eos_to_beginning=True)
```
my modification:
```
        input_hypos = [h['tokens'] for hypo_i in hypos for h in hypo_i]
        sample['hypotheses'] = data_utils.collate_tokens(
            input_hypos, self.pad, self.eos, left_pad=False, move_eos_to_beginning=False)
        sample['net_input']['prev_output_tokens'] = data_utils.collate_tokens(
            input_hypos, self.pad, self.eos, left_pad=False, move_eos_to_beginning=True)
```

 When I finetune a base Transformer pre-trained with MLE on WMT16 Ro-En using SeqNLL (beam search with beam size 16) for around 1000 updates, it gives me this error 
``RuntimeError: Function 'LogSoftmaxBackward' returned nan values in its 0th output.``
I checked the forward pass and found the encoder outputs to be normal whereas the decoder_out containing ``NAN`` values.
I also find the decoder produce NAN values when the sentence BLEU scores between the hypos and refs are mostly 0.
But not all sentence BLEUs are 0, others are still good, e.g. 70 or even 100.
 The sentence BLEU looks like:
```
bleu: 0.0
bleu: 0.0
bleu: 70.71067811865476
bleu: 0.0
bleu: 0.0
bleu: 0.0
bleu: 0.0
bleu: 0.0
bleu: 0.0
bleu: 0.0
bleu: 0.0
bleu: 0.0
bleu: 0.0
bleu: 0.0
bleu: 36.787944117144235
bleu: 0.0
bleu: 100.0
```

New updates:
I tried to include the detokenize and tokenize step as described in difference 1), now the error occurs at around 4000 updates.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.9
 - PyTorch Version (e.g., 1.0): 1.2
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
Are you applying the +1 smoothing for sentence BLEU correctly? I think you need to initialize the counts to 1 somewhere.

You might also take a look at the `seq_task` branch, where we tried to update the branch to work with a more recent version of fairseq. If you're using 0.9.0, it should actually line up pretty nicely.

The main logic is implemented in a new task called "translation_struct": https://github.com/pytorch/fairseq/blob/seq_task/fairseq/tasks/translation_struct.py and you can combine it with the "sequence_risk" criterion: https://github.com/pytorch/fairseq/blob/seq_task/fairseq/criterions/sequence_risk.py
