### ISSUE TITLE
'Wav2Vec2Model' object has no attribute 'feature_aggregator'?

### ISSUE THREAD

**Issue by hmholen** [pytorch/fairseq#3134]
Hi, I'm following the readme of wav2vec 2.

Under [Example usage for the pretrained model](https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/README.md#example-usage), the following lines are given:

`import torch`
`import fairseq`

`cp_path = '/path/to/wav2vec.pt'`
`model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])`
`model = model[0]`
`model.eval()`

`wav_input_16khz = torch.randn(1,10000)`
`z = model.feature_extractor(wav_input_16khz)`
`c = model.feature_aggregator(z)`

I change the paths to my own. 
The feature extractor works, but the aggregator line gives me 'Wav2Vec2Model' object has no attribute 'feature_aggregator'.
I checked [the source](https://github.com/pytorch/fairseq/blob/master/fairseq/models/wav2vec/wav2vec2.py) and I cannot find `self.feature_aggregator` there.
Is the documentation wrong, or am I doing something wrong?

**Comment by jubick1337** [comment]
The example you are referring to is about wav2vec 1.0 or first gen (let's call it so).
If you want to extract features using wav2vec 2.0 I'd suggest this way:
```
import fairseq
import torch

checkpoint = torch.load(wav2vec2_checkpoint_path)
wav2vec2_encoder = fairseq.models.wav2vec.Wav2Vec2Model.build_model(checkpoint['cfg']['model'])
wav2vec2_encoder.load_state_dict(checkpoint['model'])
audio = torch.randn(1,10000)
features = wav2vec2_encoder(audio, features_only=True, mask=False)['x']
```
Note: this code was tested using xlsr53 checkpoint and fairseq 0.10.1. 
Arguments for ```build_model()``` method may vary on different checkpoints.
If some errors occur you can always look what's inside checkpoint as it is kind of a dictionary.

**Comment by hmholen** [comment]
Oh you are right!
And thank you for the suggested way.
Found my checkpoint was a bit different as it had args instead of cfg.
Solved it by converting the args:
`cfg = fairseq.dataclass.utils.convert_namespace_to_omegaconf(checkpoint['args'])`
and then your suggestion worked perfectly by changing to:
`wav2vec2_encoder = fairseq.models.wav2vec.Wav2Vec2Model.build_model(cfg.model)`
Closing, thanks!

**Comment by paklau99988** [comment]
Try make load:
wav2vec2_checkpoint_path = "xlsr_53_56k.pt"

```
import fairseq
import torch

checkpoint = torch.load(wav2vec2_checkpoint_path)
print (checkpoint['cfg']['model'])
# cfg = fairseq.dataclass.utils.convert_namespace_to_omegaconf(checkpoint['args'])
wav2vec2_encoder = fairseq.models.wav2vec.Wav2Vec2Model.build_model(checkpoint['cfg']['model'])
# wav2vec2_encoder = fairseq.models.wav2vec.Wav2Vec2Model.build_model(checkpoint['args'])
# https://github.com/pytorch/fairseq/issues/3134
# wav2vec2_encoder = fairseq.models.wav2vec.Wav2Vec2Model.build_model(cfg.model)
wav2vec2_encoder.load_state_dict(checkpoint['model'])
```
But get:

`{'_name': 'wav2vec2', 'extractor_mode': 'layer_norm', 'encoder_layers': 24, 'encoder_embed_dim': 1024, 'encoder_ffn_embed_dim': 4096, 'encoder_attention_heads': 16, 'activation_fn': 'gelu', 'dropout': 0.0, 'attention_dropout': 0.0, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.0, 'dropout_input': 0.0, 'dropout_features': 0.0, 'final_dim': 768, 'layer_norm_first': True, 'conv_feature_layers': '[(512, 10, 5)] + [(512, 3, 2)] * 4 + [(512,2,2)] * 2', 'conv_bias': True, 'logit_temp': 0.1, 'quantize_targets': True, 'quantize_input': False, 'same_quantizer': False, 'target_glu': False, 'feature_grad_mult': 1.0, 'latent_vars': 320, 'latent_groups': 2, 'latent_dim': 0, 'mask_length': 10, 'mask_prob': 0.65, 'mask_selection': 'static', 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': 'static', 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'num_negatives': 100, 'negatives_from_everywhere': False, 'cross_sample_negatives': 0, 'codebook_negatives': 0, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.1, 0.999995]}`

```
TypeError                                 Traceback (most recent call last)
<ipython-input-12-268d7985882b> in <module>
     12 print (checkpoint['cfg']['model'])
     13 # cfg = fairseq.dataclass.utils.convert_namespace_to_omegaconf(checkpoint['args'])
---> 14 wav2vec2_encoder = fairseq.models.wav2vec.Wav2Vec2Model.build_model(checkpoint['cfg']['model'])
     15 # wav2vec2_encoder = fairseq.models.wav2vec.Wav2Vec2Model.build_model(checkpoint['args'])
     16 # https://github.com/pytorch/fairseq/issues/3134

/opt/conda/lib/python3.7/site-packages/fairseq/models/wav2vec/wav2vec2.py in build_model(cls, args, task)
    410         base_architecture(args)
    411 
--> 412         return cls(args)
    413 
    414     def apply_mask(self, x, padding_mask):

/opt/conda/lib/python3.7/site-packages/fairseq/models/wav2vec/wav2vec2.py in __init__(self, args)
    354                 dim=self.embed,
    355                 num_vars=args.latent_vars,
--> 356                 temp=eval(args.latent_temp),
    357                 groups=args.latent_groups,
    358                 combine_groups=False,

TypeError: eval() arg 1 must be a string, bytes or code object
```

**Comment by kunyao2015** [comment]
> Try make load: wav2vec2_checkpoint_path = "xlsr_53_56k.pt"
> 
> ```
> import fairseq
> import torch
> 
> checkpoint = torch.load(wav2vec2_checkpoint_path)
> print (checkpoint['cfg']['model'])
> # cfg = fairseq.dataclass.utils.convert_namespace_to_omegaconf(checkpoint['args'])
> wav2vec2_encoder = fairseq.models.wav2vec.Wav2Vec2Model.build_model(checkpoint['cfg']['model'])
> # wav2vec2_encoder = fairseq.models.wav2vec.Wav2Vec2Model.build_model(checkpoint['args'])
> # https://github.com/pytorch/fairseq/issues/3134
> # wav2vec2_encoder = fairseq.models.wav2vec.Wav2Vec2Model.build_model(cfg.model)
> wav2vec2_encoder.load_state_dict(checkpoint['model'])
> ```
> 
> But get:
> 
> `{'_name': 'wav2vec2', 'extractor_mode': 'layer_norm', 'encoder_layers': 24, 'encoder_embed_dim': 1024, 'encoder_ffn_embed_dim': 4096, 'encoder_attention_heads': 16, 'activation_fn': 'gelu', 'dropout': 0.0, 'attention_dropout': 0.0, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.0, 'dropout_input': 0.0, 'dropout_features': 0.0, 'final_dim': 768, 'layer_norm_first': True, 'conv_feature_layers': '[(512, 10, 5)] + [(512, 3, 2)] * 4 + [(512,2,2)] * 2', 'conv_bias': True, 'logit_temp': 0.1, 'quantize_targets': True, 'quantize_input': False, 'same_quantizer': False, 'target_glu': False, 'feature_grad_mult': 1.0, 'latent_vars': 320, 'latent_groups': 2, 'latent_dim': 0, 'mask_length': 10, 'mask_prob': 0.65, 'mask_selection': 'static', 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': 'static', 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'num_negatives': 100, 'negatives_from_everywhere': False, 'cross_sample_negatives': 0, 'codebook_negatives': 0, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.1, 0.999995]}`
> 
> ```
> TypeError                                 Traceback (most recent call last)
> <ipython-input-12-268d7985882b> in <module>
>      12 print (checkpoint['cfg']['model'])
>      13 # cfg = fairseq.dataclass.utils.convert_namespace_to_omegaconf(checkpoint['args'])
> ---> 14 wav2vec2_encoder = fairseq.models.wav2vec.Wav2Vec2Model.build_model(checkpoint['cfg']['model'])
>      15 # wav2vec2_encoder = fairseq.models.wav2vec.Wav2Vec2Model.build_model(checkpoint['args'])
>      16 # https://github.com/pytorch/fairseq/issues/3134
> 
> /opt/conda/lib/python3.7/site-packages/fairseq/models/wav2vec/wav2vec2.py in build_model(cls, args, task)
>     410         base_architecture(args)
>     411 
> --> 412         return cls(args)
>     413 
>     414     def apply_mask(self, x, padding_mask):
> 
> /opt/conda/lib/python3.7/site-packages/fairseq/models/wav2vec/wav2vec2.py in __init__(self, args)
>     354                 dim=self.embed,
>     355                 num_vars=args.latent_vars,
> --> 356                 temp=eval(args.latent_temp),
>     357                 groups=args.latent_groups,
>     358                 combine_groups=False,
> 
> TypeError: eval() arg 1 must be a string, bytes or code object
> ```

Have you solved this problem?
