### ISSUE TITLE
time_warp always shrink first part of the spec and expand the latter part, which is not expected.

### ISSUE THREAD

**Issue by chenjiasheng** [pytorch/fairseq#3141]
https://github.com/pytorch/fairseq/blob/9f5eda48edfad4cb33610f272cb503dedf60ab67/fairseq/data/audio/feature_transforms/specaugment.py#L101

time_warp always shrinks first part of the spec and expands the latter part, which is not expected.
line 101 should be:
`w = np.random.randint(-self.time_warp_w+1, self.time_warp_w)`

@kahne @myleott

**Comment by kahne** [comment]
Thanks for reporting the issue! We will make a fix shortly.
