### ISSUE TITLE
Extract layers features from m2m_100 model

### ISSUE THREAD

**Issue by jofregit** [pytorch/fairseq#3151]
## ❓ Questions and Help

Currently, I'm trying to convert the **M2M_100** model into a different programming language. For testing the conversion I would like to extract certain layers features from **M2M_100** model. Is there a straightforward way to achieve that?  Like in the "Example Usage" section for the Roberta model: https://github.com/pytorch/fairseq/tree/master/examples/roberta

But I could not find the equivalent to **.extract_features** in the **pipeline_parallel_transformer**: https://github.com/pytorch/fairseq/blob/master/fairseq/model_parallel/models/pipeline_parallel_transformer/model.py

**Comment by huihuifan** [comment]
hello, we have not implemented this feature, but if you do, please consider making a pull request!
