### ISSUE TITLE
What is this meaning?

### ISSUE THREAD

**Issue by HyejinWon** [pytorch/fairseq#3152]
When I running 'fairseq-score', returning 
BLEU4 = 76.27  90.4/80.8/72.1/64.3 (BP=1.000, ratio=1.000, syslen=52927, reflen=52942)

I understand BLEU4 is bleu score, what is '90.4/80.8/72.1/64.3' this meaning?

It is True Positive? or some else?

**Comment by HyejinWon** [comment]
and how to get precision, recall, f1score?

**Comment by lematt1991** [comment]
You can find details about each metric [here](https://github.com/pytorch/fairseq/blob/master/fairseq/scoring/bleu.py#L152-L167)
