### ISSUE TITLE
[Wav2Vec2] Community: How to run Wav2Vec2 for inference

### ISSUE THREAD

**Issue by patrickvonplaten** [pytorch/fairseq#3155]
The following gave me good results on the easy "clean" part of Librispeech. Might be helpful for others:-)

1. Download a fine-tuned wav2vec AM:

`$ wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_small_960h.pt`

2. Download dictionary:

`$ wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/dict.ltr.txt`

3. Load a sample of the Librispeech clean dataset for inference.
   Librispeech will soon be added to `https://huggingface.co/datasets`. In the meantime, I added a dummy 
  dataset that takes a tiny portion of the clean-dev dataset for some quick experiments

`$ pip install datasets`
`$ pip install soundfile`  

  ```python
  from datasets import load_dataset
  libri_dummy = load_dataset("patrickvonplaten/librispeech_asr_dummy", "clean", split="validation")
 
  # check out the dataset
  print(libri_dummy)
  ```

4. Run a forward pass

  ```python
  import torch
  import fairseq

  input_sample = torch.tensor(libri_dummy[0]["speech"])[None, :]
  
  model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(['/path/to/wav2vec_small_960h.pt'], arg_overrides={"data": "/path/to/folder/of/dict"})
  model = model[0]
  model.eval()
  
  logits = model(source=input_sample, padding_mask=None)["encoder_out"]
```
  
5. Decode the prediction

The output is a tensor of shape [seq_len, 1, vocab_size]. We are interested in the most likely token for each time step. So we can take the argmax:

```python
  predicted_ids = torch.argmax(logits[:, 0], axis=-1)
```

6. Now we'll create our own decoder based on the dict we downloaded previously to decode the result

```python
  json_dict = {"<s>": 0, "<pad>": 1, "</s>": 2, "<unk>": 3, "|": 4, "E": 5, "T": 6, "A": 7, "O": 8, "N": 9, "I": 10, "H": 11, "S": 12, "R": 13, "D": 14, "L": 15, "U": 16, "M": 17, "W": 18, "C": 19, "F": 20, "G": 21, "Y": 22, "P": 23, "B": 24, "V": 25, "K": 26, "'": 27, "X": 28, "J": 29, "Q": 30, "Z": 31}
```

and create a decoder

```python
  import numpy as np
  from itertools import groupby

  class Decoder:
      def __init__(self, json_dict):
          self.dict = json_dict
          self.look_up = np.asarray(list(self.dict.keys()))
  
      def decode(self, ids):
          converted_tokens = self.look_up[ids]
          fused_tokens = [tok[0] for tok in groupby(converted_tokens)]
          output = ' '.join(''.join(''.join(fused_tokens).split("<s>")).split("|"))
          return output
```

Now we can decode the output and compare it to the correct output:

```python
decoder = Decoder(json_dict=json_dict)
print("Prediction: ", decoder.decode(predicted_ids))
```

This should give *'A MAN SAID TO THE UNIVERSE SIR I EXIST '
* which fits with the correct output when compared to:

`print(libri_dummy[0]["text"])`

  Wav2Vec2 will soon be available in 🤗 Transformers :-)

**Comment by raja1196** [comment]
Thank you for focusing your time on this. I have tested a workaround [wav2vec-docker](https://github.com/loretoparisi/wave2vec-recognize-docker), but this will help a lot more people.

**Comment by tensorfoo** [comment]
Hey @patrickvonplaten this is really cool! Is there a way to use cuda acceleration?

**Comment by tensorfoo** [comment]
Has anyone figured out how to use kenlm decoding to this recipe?

**Comment by sourabharsh** [comment]
It worked. I had been trying to make it run for the last 3 days. finally, I can see some transcripts!

One more thing, the solution that you have suggested is for finetuned models. How do I run inference from a fine-tuned checkpoint?

**Comment by magiczixiao** [comment]
I have a problem while executing the following line:
`input_sample = torch.tensor(libri_dummy[0]["speech"])[None, :]` 
It looks like the format of the data set is wrong:
`Traceback (most recent call last):
  File "infer_lite.py", line 41, in <module>
    input_sample = torch.tensor(libri_dummy[0]["speech"])[None, :]
KeyError: 'speech'`
I checked `libri_dummy[0]` and found that there is indeed no key'speech':
`libri_dummy[0] = {
    'file': '/root/.cache/huggingface/datasets/downloads/extracted/dfbece23564f422bc5794f3090902cd16d52d86767b746125ebc2ff3ea5f89ef/dev_clean/1272/135031/1272-135031-0000.flac', 
    'id': '1272-135031-0000', 
    'audio': {'path': '/root/.cache/huggingface/datasets/downloads/extracted/dfbece23564f422bc5794f3090902cd16d52d86767b746125ebc2ff3ea5f89ef/dev_clean/1272/135031/1272-135031-0000.flac', 
        'array': array([-0.00018311, -0.00033569, -0.00021362, ..., -0.00323486,
       -0.00402832, -0.00393677], dtype=float32), 'sampling_rate': 16000}, 
    'chapter_id': 135031, 
    'text': 'BECAUSE YOU WERE SLEEPING INSTEAD OF CONQUERING THE LOVELY ROSE PRINCESS HAS BECOME A FIDDLE WITHOUT A BOW WHILE POOR SHAGGY SITS THERE A COOING DOVE', 
    'speaker_id': 1272
    }
`

Does anyone know what type of data `input_sample` should receive? Is it the audio file path or the characteristics after reading the file? And whether other preprocessing is needed?
Thanks a lot!

**Comment by Luyizhe** [comment]
When I load the model and this is my code:
```
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(['wav2vec_small_960h.pt'],arg_overrides={"data": 'dict.ltr.txt'})
```
I got an error:
```
2021-12-20 21:31:25.760162: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-12-20 21:31:25.760328: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "E:/NLP/SpeechEmotion/prompt/main.py", line 51, in <module>
    args.outfile)
  File "E:\NLP\SpeechEmotion\prompt\usewav2vec.py", line 150, in train_and_test_inadvance_middle_fusion
    model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(['wav2vec_small_960h.pt'],
  File "D:\WorkSoftware\Anaconda\envs\py36\lib\site-packages\fairseq\checkpoint_utils.py", line 287, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, args=args)
  File "D:\WorkSoftware\Anaconda\envs\py36\lib\site-packages\fairseq\models\fairseq_model.py", line 98, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "D:\WorkSoftware\Anaconda\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Wav2VecCtc:
	size mismatch for w2v_encoder.proj.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([512, 768]).
	size mismatch for w2v_encoder.proj.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([512]).
```
I don't find any case like me. Does anyone know how to slove it?

Thanks!
