### ISSUE TITLE
Question about Multi-task learning process in fairseq

### ISSUE THREAD

**Issue by SeolhwaLee** [pytorch/fairseq#3156]
Hi, I'm working to develop multi-task learning with BART. 

I want to use two tasks for joint loss learning in BART. 

I saw the instructions fairseq documentation for doing this. Probably I have to use those files as follows:

1. tasks/translation.py, tasks/sentence_prediction.py (if I use those two tasks), (e.g., for task parameter --task)
2. criterions/label_smoothed_cross_entropy.py, criterions/new_loss_code.py (e.g., for loss parameter --criterion)
3. models/bart/model.py (might be using the same architecture model since it is multi-task learning.) (e.g., for architecture parameter --arch)

But, I don't understand the exact processing for doing this.  For more details, I want to know how to load two tasks simultaneously and calculate the joint loss. 

Could you give any tips on it?

Many thanks!!

**Comment by lematt1991** [comment]
I think the [`SemiSupervisedTranslationTask`](https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/semisupervised_translation.py) is a good example of how to do this.  It combines a denoising autoencoding task with 2 translation tasks.  Basically, you'll need to implement a new task that composes the tasks that you want to use, and then specify that one composed task using `--task`.  In this task you can choose how the user specifies the different criterions for the different subtasks, etc.

**Comment by SeolhwaLee** [comment]
I see. Great thanks! 
I'll try to your instruction :)

**Comment by lematt1991** [comment]
Sounds good.  I'm going to close this issue for now.  Please re-open if you are still having problems.
