### ISSUE TITLE
Any manual to use backtranslation dataset?

### ISSUE THREAD

**Issue by getao** [pytorch/fairseq#3160]
Hi,

I want to learn how to use backtranslation dataset to generate on-the-fly back translations that could be used for training for other tasks. Is there any manual for the backtranslation dataset?

Thanks

**Comment by lematt1991** [comment]
Other than the [docs](https://github.com/pytorch/fairseq/blob/master/fairseq/data/backtranslation_dataset.py#L54-L76) in the source file, I don't believe we have any additional documentation.
