### ISSUE TITLE
OOM in Tesla v100-SXM2 (4 16GB GPUs) for m2m_100 12B Model (Multilingual Machine Translation)

### ISSUE THREAD

**Issue by ShihabYasin** [pytorch/fairseq#3162]
#### Question
While generating with m2m_100 12B Model(12b_avg10_chk_4_gpus.pt) in Tesla v100-SXM2 and 4 16GB GPUs recommended config setting from doc getting attached OOM every time.

#### Attaching
1. config that were sent, attached full below in config.txt
`
...
pipeline_encoder_balance = [1,15,10],
pipeline_encoder_devices = [0,1,0],
pipeline_decoder_balance = [3,11,11,1],
pipeline_decoder_devices = [0,2,3,0]
...`
2. nvidia-smi screenshot
3. Error screenshot

#### Environment
 - fairseq 0.10.2
 - OS : Ubuntu 18.04
 - Install method: pip install fairseq 
 - Python version: 3.6
 - GPU models and configuration: 12B Model(12b_avg10_chk_4_gpus.pt), config attached

**Anybody with this situation with a solution?**

[config.txt](https://github.com/pytorch/fairseq/files/5864723/config.txt)

nvidia-smi:
![22](https://user-images.githubusercontent.com/14265415/105671059-4bbf3300-5f0c-11eb-9de9-e21da26a7524.png)

OOM Error:
![11](https://user-images.githubusercontent.com/14265415/105671045-46fa7f00-5f0c-11eb-8983-ba2fd9d50973.png)

**Comment by lematt1991** [comment]
What's the full command that you ran?  The config you posted doesn't seem to match the suggested command in the [README](https://github.com/pytorch/fairseq/tree/master/examples/m2m_100#generation-for-the-12b-model).  For example `pipeline_model_parallel` is `False`, but should be set to `True` using `--pipeline-model-parallel`.  Also, it looks like `batch_size` is `None`, but should be `1`

**Comment by ShihabYasin** [comment]
Thanks @lematt1991 it works.

**Comment by Hanlard** [comment]
> Thanks @lematt1991 it works.

Hellow, I meet the simillar errors with you..   Could you show me all the full command to finetuning the 12B model?

**Comment by wei-ann-Github** [comment]
> > Thanks @lematt1991 it works.
> 
> Hellow, I meet the simillar errors with you.. Could you show me all the full command to finetuning the 12B model?

Hi @Hanlard ,

Did you eventually manage to finetune the 12B model without CUDA OOM  error? I have no luck as well. This issue is about generation though.
