### ISSUE TITLE
Finetuning wav2vec 2.0 with transformer language model

### ISSUE THREAD

**Issue by abirkorched** [pytorch/fairseq#3171]
## ❓ Questions and Help
Hello,

Any hint about using a transformer LM along with CTC during the fine-tuning of wav2vec?
The CTC criterion implemented in fairseq only supports 4gram LM. 
https://github.com/pytorch/fairseq/blob/83e615d66905b8ca7483122a37da1a85f13f4b8e/fairseq/criterions/ctc.py#L19

Thank you!

**Comment by alexeib** [comment]
it wouldnt be too difficult but i would not recommend because then your finetuning will run for a very long time

**Comment by abirkorched** [comment]
Yes I see. Thank you very much @alexeib for your return! I really appreciated your help.

**Comment by tonyyy10111** [comment]
Why do we need using a language model during the fine-tuning of wav2vec?

**Comment by abirkorched** [comment]
I wanted to evaluate wav2vec using the language during the fine-tuning.
