### ISSUE TITLE
Multi accent Speech to Text model

### ISSUE THREAD

**Issue by bharat-patidar** [pytorch/fairseq#3172]
Hi everyone,

Can we use wav2vec 2.0 to build a multi accent S2T model?
example: I want to build an ASR model that can transcribe US and Indian accent English language. I have 3-4k hours of labelled data for each accent. Is it possible to build a single model for these accents which can give me good enough WER(<15)?

Any suggestion would be of great help!

Thanks

**Comment by alexeib** [comment]
have you tried finetuning the released librivox model on your data? should already work reasonably well.
