### ISSUE TITLE
key_padding_mask is not used in the attention in fconv_self_att.py 

### ISSUE THREAD

**Issue by 1400012780** [pytorch/fairseq#318]
I wonder why  **key_padding mask** not used in the attention between the encoder and decoder in the hierarchical story generation framework.
the source code is shown below.
`x, attn_scores = attention(attproj(x) + target_embedding, encoder_a, encoder_b)`

**Comment by huihuifan** [comment]
Yes, the key padding mask was added to our repo after the stories code. I will add it to my list of changes, but if you would like to make this change as a pull request, please let me know :) Thanks!
