### ISSUE TITLE
Reproducing joint_alignment_translation - FloatingPointError: Minimum loss scale reached

### ISSUE THREAD

**Issue by dmitrytoda** [pytorch/fairseq#3185]
#### What is your question?

I am trying to reproduce the results of the paper [Jointly Learning to Align and Translate with Transformer Models (Garg et al., 2019)](https://arxiv.org/abs/1909.02074) according to [this instruction](https://github.com/pytorch/fairseq/tree/master/examples/joint_alignment_translation).

I successfully went throug steps 1-3, but when I try to run step 4 (training the model), I get this error: 
> FloatingPointError: Minimum loss scale reached (0.0001). Your loss is probably exploding. Try lowering the learning rate, using gradient clipping or increasing the batch size.

Full cell output is attached.
[train_error.txt](https://github.com/pytorch/fairseq/files/5898329/train_error.txt)

#### Code
The code is exactly as in the manual, except for the binarized folder location

> !fairseq-train \
>     /content/drive/MyDrive/WordAlign/EN-DE/binarized \
>     --arch transformer_wmt_en_de_big_align --share-all-embeddings \
>     --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 --activation-fn relu\
>     --lr 0.0002 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07 \
>     --dropout 0.3 --attention-dropout 0.1 --weight-decay 0.0 \
>     --max-tokens 3500 --label-smoothing 0.1 \
>     --save-dir ./checkpoints --log-interval 1000 --max-update 60000 \
>     --keep-interval-updates -1 --save-interval-updates 0 \
>     --load-alignments --criterion label_smoothed_cross_entropy_with_alignment \
>     --fp16

#### What have you tried?

1. I understand I can try reducing the learning rate or doing anything suggested [here](https://github.com/pytorch/fairseq/issues/1529), and I will try that. However, the idea of reproducing the paper is to run everything with the same settings and hyperparameters, so I want to understand why it does not work that way.
2. May it be the case that something went wrong on one of the previous steps? They all worked and produced some output that I have saved, but is there a way to check if that output was correct?
3. In the output it says: `max tokens per GPU = 3500 and batch size per GPU = None`, is it normal to have batch size = None? does it default to some reasonable value, or does None imply training by one example or using the entire training set somehow?

#### What's your environment?

 - fairseq: master
 - PyTorch Version: 1.7.0+cu101
 - OS: google colab
 - How you installed fairseq (`pip`, source): source
 - Build command you used: `pip install --editable ./`
 - Python version: 3.6.9
 - CUDA/cuDNN version: V10.1.243
 - GPU models and configuration: different every time with colab, but on last run it said `capabilities =  7.5  ; total memory = 14.726 GB ; name = Tesla T4` 
 - Any other relevant information: I installed NVIDIA apex with this command `!pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" --global-option="--deprecated_fused_adam" --global-option="--xentropy" apex/` The main FairSeq readme also has the ` --global-option="--fast_multihead_attn"` option but that was always giving me an error

**Comment by myleott** [comment]
Most likely you're using too small of a batch size. Looking at the README, the original model was trained on 64 GPUs, and the batch size per GPU was 3500 tokens (since `--max-tokens=3500`), for a total batch size of 64*3500 ~= 224000 (it would typically be a bit less than this, due to padding).

If you train on fewer GPUs, then you need to accumulate gradients from multiple batches to achieve the same total batch size. This is done via `--update-freq` option. So if you're training on 1 GPU, you would do `--max-tokens 3500 --update-freq 64`. If you're training on 2 GPUs, you could do `--max-tokens 3500 --update-freq 32`, etc.

**Comment by dmitrytoda** [comment]
Thank you!
I saw the `--update-freq` in the readme but I didn't realize that the fewer GPUs I have, the bigger it should be.
Should I also increase learning rate to 0.0007 as suggested there? I am training on one GPU right now (yes I know it will take forever, but I just want to make sure everything is working before I start using paid resouces).
