### ISSUE TITLE
fairseq-generate scripts

### ISSUE THREAD

**Issue by zoki701** [pytorch/fairseq#3191]
I am currently working on a project in NMT using fairseq toolkit. .I am using fairseq-generate script to generate translations and compute BLEU score over the test set. 
However I am not sure whether my scripts for top k sampling and top p sampling(nucleus sampling) are correct.

Here is the script for top-k sampling
fairseq-generate \
     data-bin/iwslt14.tokenized.de-en \
    --source-lang en --target-lang de \
    --path checkpoints/checkpoint100.pt \
    --sampling \
    --sampling-topk 8 --lenpen 1.3 \
    --nbest 1 \
    --scoring sacrebleu \
    --remove-bpe=sentencepiece

Here is the script for top-p sampling
fairseq-generate \
    data-bin/iwslt14.tokenized.de-en \
    --source-lang en --target-lang de \
     -path checkpoints/checkpoint100.pt \
    --sampling \
    --sampling-topp 0.4 --lenpen 1.3 \
    --nbest 1 \
    --scoring sacrebleu \
    --remove-bpe

Do I need to specify beam size as well in these decoding algorithms?
What are the optimal values for k and p that would generate better Blue scores?

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by lematt1991** [comment]
Yes, `beam_size` is still used in `topp` and `topk` sampling.  See additional details [here](https://github.com/pytorch/fairseq/blob/master/fairseq/search.py#L676-L742).  As far as optimal parameters go, you'll need to experiment with this.  It should be easy to sweep over these paramters, as it's only done at inference time and you won't need to retrain the model each time.

**Comment by jovan72** [comment]
Ok thanks a lot. Why do we have to specify beam size when beam search is a completely different algorithm? We are not combining them right?

**Comment by zoki701** [comment]
Thanks a lot. Why do we have to specify it when they are completely different algorithms? We are not combining them right?

**Comment by lematt1991** [comment]
Sorry, I actually don't have much context on this.  Maybe @myleott  can clarify?

**Comment by tolerancecky** [comment]
hi，I want to ask you how I can get the top_n output results for every sentences of test.txt unsing beam search or others. I try to add "--nbest" or "-beam" to ”fairseq generate“, but it makes no sence.
