### ISSUE TITLE
Why hydra_init need to store the default into ConfigStore

### ISSUE THREAD

**Issue by npuichigo** [pytorch/fairseq#3192]
I read the hydra doc recently and found fairseq as a good example showing how to use structured config to validate configuration files.

But I have a question that why fairseq need to store the default into ConfigStore in hydra_init
```python
def hydra_init(cfg_name="config") -> None:

    cs = ConfigStore.instance()
    cs.store(name=cfg_name, node=FairseqConfig)

    for k in FairseqConfig.__dataclass_fields__:
        v = FairseqConfig.__dataclass_fields__[k].default
        try:
            cs.store(name=k, node=v)
        except BaseException:
            logger.error(f"{k} - {v}")
            raise
```
The tutorial in hydra doesn't handle default values except for [default list](https://hydra.cc/docs/tutorials/structured_config/defaults), is that the same thing?

**Comment by lematt1991** [comment]
Defaults need to be registered in the ConfigStore.  See [this](https://hydra.cc/docs/tutorials/structured_config/defaults) example

**Comment by npuichigo** [comment]
@lematt1991 Do u mean that it's the same as the following lines?
```python
@dataclass
class Config:
    # this is unfortunately verbose due to @dataclass limitations
    defaults: List[Any] = field(default_factory=lambda: [{"db": "mysql"}])
```
