### ISSUE TITLE
How to test pretrained LM on a new dataset

### ISSUE THREAD

**Issue by omarfoq** [pytorch/fairseq#3201]
What is the correct way to evaluate a language modeling pretrained model, using a dataset A, on a dataset B? 
I ask this question because the vocab dict is not necessary compatible when moving from one dataset to another.

**Comment by alexeib** [comment]
you would either 
a) re-encode teh data you are testing on using the vocab used for training or
b) use --dataset-impl raw and point at a unencoded text file. you would still use the dictionary from training
