### ISSUE TITLE
Difference of BLEU score on WMT'14 newstest2014 En-Fr dataset

### ISSUE THREAD

**Issue by ChuanyangZheng** [pytorch/fairseq#3207]
I'm trying to reproduce the results in Transformer(Ott et al., 2018). At first, I followded the readme file in [prepare-wmt14en2fr.sh](https://github.com/pytorch/fairseq/blob/master/examples/translation/prepare-wmt14en2fr.sh#L1) to download and prepare WMT14 English-French data. 
Then I process data by the example code:
```
fairseq-preprocess \
        --source-lang en --target-lang fr \
        --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test \
        --destdir data-bin/wmt14_en_fr \
        --workers 60 \
        --joined-dictionary 
 ```
However, when I evaluate the performance with [pretrained model](https://dl.fbaipublicfiles.com/fairseq/models/wmt14.en-fr.joined-dict.transformer.tar.bz2), I get RuntimeError when evaluating. 
```
RuntimeError: Error(s) in loading state_dict for TransformerModel:
        size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([44512, 1024]) from checkpoint, the shape in current model is torch.Size([39416, 1024]).
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([44512, 1024]) from checkpoint, the shape in current model is torch.Size([39416, 1024]).
        size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([44512, 1024]) from checkpoint, the shape in current model is torch.Size([39416, 1024]).
```
So I copy the dict under [pretrained model] to overwrite my preprocessed dict. 
After that, I get terrible result by evaluating them with the [pretrained model](https://dl.fbaipublicfiles.com/fairseq/models/wmt14.en-fr.joined-dict.transformer.tar.bz2) as follows:
```
Generate test with beam=5: BLEU4 = 4.54, 19.4/6.5/3.5/1.8 (BP=0.853, ratio=0.863, syslen=74137, reflen=85898)
```
So I try to use the [provided newstest2014](https://dl.fbaipublicfiles.com/fairseq/data/wmt14.en-fr.joined-dict.newstest2014.tar.bz2) dataset by fairseq and get a pretty good result:
```
Generate test with beam=5: BLEU4 = 43.00, 69.0/48.9/36.6/27.7 (BP=1.000, ratio=1.003, syslen=83041, reflen=82787)
```
Then I think there are some problems in my prerocessing, so I search related [issues](https://github.com/pytorch/fairseq/issues/2836, https://github.com/pytorch/fairseq/issues/788) and modified my process:
```
fairseq-preprocess \
        --source-lang en --target-lang fr \
        --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test \
        --destdir data-bin/wmt14_en_fr \
        --workers 60 \
        --srcdict $DICT/dict.en.txt \
        --tgtdict $DICT/dict.fr.txt \
```
And I get better result:
```
Generate test with beam=5: BLEU4 = 35.41, 63.8/41.8/29.5/21.1 (BP=0.987, ratio=0.987, syslen=82373, reflen=83484)
```
But still large distance from the reported result by Transformer(Ott et al., 2018). Can someone help me out? Where is the problem in my preprocessing? 

#### What's your environment?
 - fairseq Version: master
 - PyTorch Version : 1.5
 - OS: Linux
 - How you installed fairseq: source
 - Build command you used (if compiling from source):
 - Python version: 3.65
 - CUDA/cuDNN version: 10.1 / 7.6.5
 - GPU models and configuration: TitanXp
 - Any other relevant information:

**Comment by ChuanyangZheng** [comment]
I figure it out myself. When process the data, I only process nc-v9 and test-full data, so i go wrong. If process the whole training data with test-full, it go well.

**Comment by tjshu** [comment]
> nc-v9
sorry, how to process the whole training data with test-full,

**Comment by tjshu** [comment]
> I figure it out myself. When process the data, I only process nc-v9 and test-full data, so it goes wrong. If process the whole training data with test-full, it goes well.

how to process the whole training data with test-full?
thank you
