### ISSUE TITLE
 Testing new data using  fairseq-generate with trained models

### ISSUE THREAD

**Issue by sascam** [pytorch/fairseq#3222]
**What is the exact command to translate a new test data using the fairseq trained models ?**  
I have kept a test data set for translation inside /home/ola/NMT/corpus/test-en-hi folder. The command I have given is,
 fairseq-generate /home/ola/NMT/corpus/test-en-hi --path checkpoints/fconv/checkpoint_best.pt --batch-size 128 --beam 5 --skip-invalid-size-inputs-valid-test --source-lang en --target-lang hi >trans-en-hi.out
But, it is showing an error
     **FileNotFoundError: [Errno 2] No such file or directory: '/home/ola/NMT/corpus/test-en-hi/dict.en.txt'**
It is asking for a dict.en.txt file..  Why it is so ?  Actually, after preprocessing (before training) there is a data-bin/IITB.en-hi folder created with all binarized fies in that dict.en.txt also present.
Now what is the requirement for a dict.en.txt to translate a new dataset..?

Could you please help me to get the exact command to translate a test data using fairseq trained models.
  

#### What have you tried?
fairseq-generate /home/ola/NMT/corpus/test-en-hi --path checkpoints/fconv/checkpoint_best.pt --batch-size 128 --beam 5 --skip-invalid-size-inputs-valid-test --source-lang en --target-lang hi >trans-en-hi.out
#### What's your environment?

 - fairseq Version :0.10.1
 - PyTorch Version  : 1.7.1.post2
 - OS : Ubuntu 18.04
 - How you installed fairseq (`pip`, source):conda install -c conda-forge pytorch cudatoolkit=10.1 nvidia-apex fairseq==0.10.1
 - Build command you used (if compiling from source):
 - Python version: Python 3.6.12 :: Anaconda, Inc.
 - CUDA/cuDNN version:10.1
 - GPU models and configuration: NVIDIA-SMI 418.40.04    Driver Version: 418.40.04    CUDA Version: 10.1  Tesla K80 
 - Any other relevant information:

**Comment by alexeib** [comment]
you need 2 dict files when translating from language a to b, dict.a.txt and dict.b.txt. they need to be in the same dir as you are pointing to as your "data" dir. and of course they have to be exactly the same dicts as was used when the model was trained

**Comment by sascam** [comment]
Could you please provide **the exact command to translate a new text file into a target text file using the trained models** ?

I am getting various errors when I am trying using fairseq-generate

**Comment by sascam** [comment]
> you need 2 dict files when translating from language a to b, dict.a.txt and dict.b.txt. they need to be in the same dir as you are pointing to as your "data" dir. and of course they have to be exactly the same dicts as was used when the model was trained

Could you please provide the exact command to translate a new text file into a target text file using the trained models ?

I am getting various errors when I am trying using fairseq-generate

**Comment by sascam** [comment]
Could you please provide **the exact command to translate a new text file into a target text file using the trained models** ?

I am getting various errors when I am trying using fairseq-generate

**Comment by sascam** [comment]
bump

This issue is still there.

**Comment by oaarnikoivu** [comment]
I'm curious about this as well. I've trained my NMT system and evaluated on a in-domain test set using fairseq-generate, but now I would like to evaluate on a new out-of-domain test set without having to train the model again using this test set, is this possible?
