### ISSUE TITLE
Wav2Vec2.0: Where is the dict file for XLSR53?

### ISSUE THREAD

**Issue by weiyengs** [pytorch/fairseq#3223]
I can't seem to find any answers after searching. For normal models, we have to indicate the dictionary file like this: https://github.com/pytorch/fairseq/issues/3155

However, I couldn't find the dict file for XLSR53 model. Or how do I create 1?

Thanks!

**Comment by alexeib** [comment]
the released xlsr model is not fine-tuned on anything, so there is no dictionary. you would create your own for whatever dataset you are finetuning on. you can create it by copying existing dicts and modifying them or, for example, running preprocess.py as in language modeling examples and then taking that dict (possibly renaming it)
