### ISSUE TITLE
Issue of reproducing Must-C result on S2T

### ISSUE THREAD

**Issue by zjw1990** [pytorch/fairseq#3224]
## 🐛 Bug

2021-02-09 09:46:37 | INFO | fairseq_cli.generate | loading model(s) from /data/mustc/en-fr/mustc_fr_st_transformer_s.pt
/opt/conda/lib/python3.7/site-packages/hydra/_internal/hydra.py:71: UserWarning: 
@hydra.main(strict) flag is deprecated and will removed in the next version.
See 
https://hydra.cc/docs/next/upgrades/0.11_to_1.0/strict_mode_flag_deprecated
  warnings.warn(message=msg, category=UserWarning)
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/workspace/fairseq/fairseq_cli/generate.py", line 389, in cli_main
    main(args)
  File "/workspace/fairseq/fairseq_cli/generate.py", line 50, in main
    return _main(cfg, sys.stdout)
  File "/workspace/fairseq/fairseq_cli/generate.py", line 103, in _main
    num_shards=cfg.checkpoint.checkpoint_shard_count,
  File "/workspace/fairseq/fairseq/checkpoint_utils.py", line 264, in load_model_ensemble
    num_shards,
  File "/workspace/fairseq/fairseq/checkpoint_utils.py", line 302, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/workspace/fairseq/fairseq/tasks/speech_to_text.py", line 109, in build_model
    return super(SpeechToTextTask, self).build_model(args)
  File "/workspace/fairseq/fairseq/tasks/fairseq_task.py", line 548, in build_model
    model = models.build_model(args, self)
  File "/workspace/fairseq/fairseq/models/__init__.py", line 56, in build_model
    return ARCH_MODEL_REGISTRY[cfg.arch].build_model(cfg, task)
  File "/workspace/fairseq/fairseq/models/speech_to_text/s2t_transformer.py", line 237, in build_model
    encoder = cls.build_encoder(args)
  File "/workspace/fairseq/fairseq/models/speech_to_text/s2t_transformer.py", line 210, in build_encoder
    component=encoder, checkpoint=args.load_pretrained_encoder_from
  File "/workspace/fairseq/fairseq/checkpoint_utils.py", line 576, in load_pretrained_component_from_model
    raise IOError("Model file not found: {}".format(checkpoint))
OSError: Model file not found: /checkpoint/changhan/projects/fairseq_s2t/mustc.task_fr_asr_unigram5000.ls_0.1.arch_s2t_transformer_s.dp_0.1.lr_0.001.wu_10000.ngpu8/avg_last_10_checkpoint.pt
execute status:1
failed

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

Using Fairseq-genertae. The path seems to be fixed in the checkpoint. I used exact the same command lines provided

#!/bin/bash

MUSTC_ROOT=/mustc
ST_SAVE_DIR=${MUSTC_ROOT}/en-fr
FAIR_ROOT=/fairseq
CHECKPOINT_FILENAME=mustc_fr_st_transformer_s.pt

#Evaluate st
fairseq-generate ${MUSTC_ROOT}/en-fr --gen-subset tst-COMMON_st --task speech_to_text --max-tokens 50000 --num-workers 0 \
    --path ${ST_SAVE_DIR}/${CHECKPOINT_FILENAME} --beam 5 --scoring sacrebleu --config-yaml ${MUSTC_ROOT}/en-fr/config_st.yaml

### Environment

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by kahne** [comment]
@zjw1990 Thanks for reporting the issue. We've updated the checkpoints. Can you re-download and try again?

**Comment by zjw1990** [comment]
Thank you it works for me. However the result is not correct.

This is what I got from the fairseq-generate 

Generate tst-COMMON_st with beam=5: BLEU = 16.64 47.4/22.7/11.9/6.5 (BP = 0.977 ratio = 0.978 hyp_len = 69666 ref_len = 71260)
execute status:0
success

I think the difference might be the vocab or sentencepiece model? I used the preprocess script provided in fairseq. The command line is:

fairseq-generate ${MUSTC_ROOT}/en-fr --gen-subset tst-COMMON_st --task speech_to_text --max-tokens 50000 --num-workers 0 \
    --path ${ST_SAVE_DIR}/${CHECKPOINT_FILENAME} --beam 5 --scoring sacrebleu --config-yaml ${MUSTC_ROOT}/en-fr/config_st.yaml --quiet


Could you provide any clues? Thank you.

**Comment by zjw1990** [comment]
> @zjw1990 Thanks for reporting the issue. We've updated the checkpoints. Can you re-download and try again?

**Comment by zjw1990** [comment]
> > @zjw1990 Thanks for reporting the issue. We've updated the checkpoints. Can you re-download and try again?

**Comment by zjw1990** [comment]
Thank you it works for me. However the result is not correct.

This is what I got from the fairseq-generate

Generate tst-COMMON_st with beam=5: BLEU = 16.64 47.4/22.7/11.9/6.5 (BP = 0.977 ratio = 0.978 hyp_len = 69666 ref_len = 71260)
execute status:0
success

I think the difference might be the vocab or sentencepiece model? I used the preprocess script provided in fairseq. The command line is:

fairseq-generate ${MUSTC_ROOT}/en-fr --gen-subset tst-COMMON_st --task speech_to_text --max-tokens 50000 --num-workers 0
--path ${ST_SAVE_DIR}/${CHECKPOINT_FILENAME} --beam 5 --scoring sacrebleu --config-yaml ${MUSTC_ROOT}/en-fr/config_st.yaml --quiet

Could you provide any clues? Thank you

**Comment by kahne** [comment]
Yeah, you are supposed to use our vocab and spm files for this pre-trained model (downloadable from the same web page)? The ones from the preprocessing script are not guaranteed to be the same even when generated with the same data and settings.

**Comment by zjw1990** [comment]
> Yeah, you are supposed to use our vocab and spm files for this pre-trained model (downloadable from the same web page)? The ones from the preprocessing script are not guaranteed to be the same even when generated with the same data and settings.

Thank you! I tried and got surprisingly good result with 35.39

2021-02-22 05:52:55 | INFO | fairseq_cli.generate | Translated 2578 sentences (71533 tokens) in 56.1s (45.96 sentences/s, 1275.39 tokens/s)
/opt/conda/lib/python3.7/site-packages/hydra/_internal/hydra.py:71: UserWarning: 
@hydra.main(strict) flag is deprecated and will removed in the next version.
See 
https://hydra.cc/docs/next/upgrades/0.11_to_1.0/strict_mode_flag_deprecated
  warnings.warn(message=msg, category=UserWarning)
Generate tst-COMMON_st with beam=5: BLEU = 35.39 61.2/41.3/30.3/22.6 (BP = 0.976 ratio = 0.977 hyp_len = 69583 ref_len = 71257)
execute st

However, I tried with reproduing this result before and only got 32.8(32.9 is reported to be the suppossing result) following the instruction. I checked with the details and find the training hyperparameters are different from the default instruction. Is this the  reason? Thank you.
