### ISSUE TITLE
Stuck during wav2vec Inference using Flask/Django API

### ISSUE THREAD

**Issue by spygaurad** [pytorch/fairseq#3230]
Stuck at hypos = task.inference_step(generator, models, sample, prefix_tokens)      

This code run perfectly when calling from terminal but when i called it using Flask or Django api, it is stuck there forever. Is this api implementation not supported currently?

**Comment by erip** [comment]
Can you share any code?

**Comment by spygaurad** [comment]
`def predict(audio_file):   ` 

    PredictorConfig.task.load_dataset(audio_file, PredictorConfig.args.gen_subset)
    itr = get_dataset_itr(PredictorConfig.args, PredictorConfig.task, PredictorConfig.models)
    print("Generated dataset Iterator")
    num_sentences = 0

    max_source_pos = (
        utils.resolve_max_positions(
            PredictorConfig.task.max_positions(), *[model.max_positions() for model in PredictorConfig.models]
        ),
    )
    if max_source_pos is not None:
        max_source_pos = max_source_pos[0]
        if max_source_pos is not None:
            max_source_pos = max_source_pos[0] - 1
    result_final = ""
    for item in itr:
        print("Entered Decoding Loop")
        sample = utils.move_to_cuda(item) if PredictorConfig.use_cuda else item
        if "net_input" not in sample:
                continue
        prefix_tokens = None
        if PredictorConfig.args.prefix_size > 0:
            prefix_tokens = sample["target"][:, : PredictorConfig.args.prefix_size]
        
        hypos = PredictorConfig.task.inference_step(PredictorConfig.generator, PredictorConfig.models, sample, prefix_tokens)        
        print("Hypos generated predictions")

        num_generated_tokens = sum(len(h[0]["tokens"]) for h in hypos)
        for i, sample_id in enumerate(sample["id"].tolist()):
            speaker = None
            # id = task.dataset(args.gen_subset).ids[int(sample_id)]
            id = sample_id
            toks = (
                sample["target"][i, :]
                if "target_label" not in sample
                else sample["target_label"][i, :]
            )
            target_tokens = utils.strip_pad(toks, PredictorConfig.tgt_dict.pad()).int().cpu()
            # Process top predictions
        print("Generating Result")
        result = asr_result(
                PredictorConfig.args,
                hypos[i],
                None,
                PredictorConfig.tgt_dict,
                target_tokens,
                PredictorConfig.res_files,
                speaker,
                id,
            )
        result_final += result
        print("-------", result)
    return result_final

------------------------------------------------------------------------------------------------------------
Result:


![image](https://user-images.githubusercontent.com/16435245/107602975-6e16b780-6c53-11eb-9d82-7f044cfc3a4b.png)

Its stuck here.

**Comment by spygaurad** [comment]
I tried modifying current speech_recognition/infer.py code. The language model is not producing same results. There is some error in this code, will update soon on further progress.
