### ISSUE TITLE
Support for the Long-Range Arena benchmark

### ISSUE THREAD

**Issue by lioutasb** [pytorch/fairseq#3232]
## 🚀 Feature Request

Import the dataset loaders of the [Long-Range Arena](https://github.com/google-research/long-range-arena) benchmark as well as the evaluation procedure to quickly and easily test Fairseq-based sequence modeling methods with the LRA benchmark.

### Motivation

Many recent sequence modeling techniques are implemented and designed around Fairseq and some of them are PyTorch exclusive (i.e [Dynamic Convolutions](https://arxiv.org/abs/1901.10430) and [TaLK Convolutions](https://arxiv.org/abs/2002.03184)). Recently, a new benchmark was published called the [Long-Range Arena](https://github.com/google-research/long-range-arena) that aims to measure the long-range encoding capabilities of many newly proposed Transformer-based sequence modeling methods. It would be extremely helpful to support this benchmark out-of-the-box since many researchers use Fairseq to develop new sequence modeling architectures and this benchmark is becoming one of the standard long-range performance tests.

**Comment by alexeib** [comment]
sounds like a good idea. contributions are welcome!

**Comment by excitingtimes** [comment]
Hello, are there any news on that front ? Thanks in advance !
