### ISSUE TITLE
Speech Translation -> prep_covost_data.py

### ISSUE THREAD

**Issue by pyyush** [pytorch/fairseq#3238]
#### What is your question?

Is this step needed for flac and mp3 files loaded by torchaudio.load() [sox backend] and default args ? 

#### Code 
`_waveform = waveform * (2 ** 15)  # Kaldi compliance: 16-bit signed integers`
 `_waveform = _waveform.squeeze().numpy()`

#### What's your environment?
- PyTorch 1.7.1
- torchaudio 0.7.2

**Comment by kahne** [comment]
Hi @pyyush , this also applies to FLAC and MP3 because `torchaudio.load()` always returns 16-bit floats (normalized to [-1, 1]). However, Kaldi uses 16-bit signed integers (in range of [-2^15, 2^15]). The conversion is still needed here.

**Comment by pyyush** [comment]
Hi @kahne,  thank you for the answer. So torchaudio.compliance.kaldi also uses 16-bit signed integers? The reason why I asked this is because I visualized one of the fbank after data prep and the last 10 (71-80) bins seemed odd.

**Comment by kahne** [comment]
> Hi @kahne, thank you for the answer. So torchaudio.compliance.kaldi also uses 16-bit signed integers? The reason why I asked this is because I visualized one of the fbank after data prep and the last 10 (71-80) bins seemed odd.

Yes, `torchaudio.compliance.kaldi` is designed to have exactly the same inputs/outputs as the original Kaldi implementation.

**Comment by pyyush** [comment]
Okay, thanks.
