### ISSUE TITLE
Typo Wav2Vec 2.0 - HugginFace 'vesion' 4.3

### ISSUE THREAD

**Issue by jpmcarrilho** [pytorch/fairseq#3239]
## 📚 Documentation
Typo in https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/README.md.
Use wav2vec 2.0 with 🤗Transformers: section
Line 1: Wav2Vec2 is also available in the 🤗Transformers library since ~vesion~ version 4.3
For typos and doc fixes, please go ahead and:

1. Create an issue.
2. Fix the typo.
3. Submit a PR.

Thanks!

**Comment by noetits** [comment]
Hello,

The README seems to be empty now

**Comment by jpmcarrilho** [comment]
It's been corrected @noetits . Closing the issue.
