### ISSUE TITLE
Confused about wav2vec2 negative sampling 

### ISSUE THREAD

**Issue by jjjjohnson** [pytorch/fairseq#3243]
Hello!
I have a hard time understanding this line of code:
https://github.com/pytorch/fairseq/blob/5ac5e8a20a7a914698f9970c2a384f14015ece3d/fairseq/models/wav2vec/wav2vec2.py#L397
Base on my current understanding, the purpose of this line is to avoid sampling the positive samples. Why not just set `neg_idxs[neg_idxs == tszs] += 1` ?

Thanks for any hints!

**Comment by alexeib** [comment]
thats right. if you do what you suggest then the sampling distribution will be skewed (with timesteps immediately after positives having a higher chance of being chosen than the rest), but if you move everything after the positive then the selection is still uniform

**Comment by jjjjohnson** [comment]
@alexeib Thanks a lot!
