### ISSUE TITLE
When will you release mBart-base?

### ISSUE THREAD

**Issue by HuihuiChyan** [pytorch/fairseq#3252]
## 🚀 Feature Request
Dear author, I only have two P100 with 16GB graphic memory, so it is nearly impossible for me to fine-tune mBart. I tried the batch size of 1 with max sequence length as 64, but still got OOM. So I wonder will there be a mBart-base model, or you do not have the plan to train a smaller model?

### Motivation

I am very poor, and cannot afford bigger GPU. But I still want to do research on mBart. Please help me to seek for my dream.

### Pitch

I wish there could be a mbart model with smaller size, enabling me to fine-tune it with only two P100(16GB memory).

**Comment by lematt1991** [comment]
As far as I know, there aren't any plans to release a smaller model.  You could try training a smaller model from scratch following the methodology in the paper.
