### ISSUE TITLE
S2T: Very high wer when using pre-trained model on librispeech

### ISSUE THREAD

**Issue by yyyyxie** [pytorch/fairseq#3260]
## 🐛 Bug
I am trying to reproduce the result of using naive transformer to do the s2t on librispeech dataset. But by running the pretrained model, I got very high wer as 101.10 (sould be under 10)
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):
1. preprocess the data: 
python  examples/speech_to_text/prep_librispeech_data.py  --output-root /data/LibriSpeech --vocab-type unigram --vocab-size 10000
Then I got tsv file for training and test audio features.
And I also got spm_unigram10000.model , spm_unigram10000.txt and config.yaml files ready.

2. Evaluate the pretrained model.
I downloaded the librispeech pretrained model [here](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/librispeech_example.md)
and run the cmd: 
fairseq-generate /data/LibriSpeech  --config-yaml config.yaml --gen-subset dev-clean --task speech_to_text    --path /home/librispeech_transformer_s.pt --max-tokens 50000 --beam 5 --scoring wer

3. Result:
I got wer over 30 when using my own spm_unigram10000 from data preprocessing.
 And the wer result is more than 100 when I use the spm_unigram10000 files you provided with the pratrained model.
Similar results happened on transformer_m model as well.

### Expected behavior

Could you check with the spm_unigram10000 files. Do they match with the given pretrained model? Or is there anything I missed? Thanks!
 
### Environment

 - fairseq Version : 1.0
 - PyTorch Version  1.7.1
 - How you installed fairseq (`pip`, source): pip
 - Python version: 3.8.3
 - CUDA/cuDNN version: 11.0

**Comment by kahne** [comment]
Thanks for reporting the issue. 

This is likely due to an inconsistency between the pre-trained model and the data prep script, which we just fixed. (The former was trained on lowercased transcripts, while the latter provides the original uppercased transcripts. We've changed the latter to the lowercased version for consistency.) 

Can you pull the latest code and re-run the data prep script? Or a hackier (and quicker) approach is to convert the target text in the manifest TSV files (column "tgt_text") to lowercased version.

**Comment by yyyyxie** [comment]
> Thanks for reporting the issue.
> 
> This is likely due to an inconsistency between the pre-trained model and the data prep script, which we just fixed. (The former was trained on lowercased transcripts, while the latter provides the original uppercased transcripts. We've changed the latter to the lowercased version for consistency.)
> 
> Can you pull the latest code and re-run the data prep script? Or a hackier (and quicker) approach is to convert the target text in the manifest TSV files (column "tgt_text") to lowercased version.

Thank you for your reply. I re-run the latest data preprocess script and got the correct wer result now(~4).
