### ISSUE TITLE
 No module named 'fairseq.visual'

### ISSUE THREAD

**Issue by jhkd-kevin** [pytorch/fairseq#3263]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):0.6.1
 - PyTorch Version (e.g., 1.0)：
 - OS (e.g., Linux):linux
 - How you installed fairseq (`pip`, source):source
 - Build command you used (if compiling from source):
 - Python version:3.7.3
 - CUDA/cuDNN version:10.0/~
 - GPU models and configuration:2060
 - Any other relevant information:

**Comment by lematt1991** [comment]
Not enough context.  Please follow the instructions in the issue template
