### ISSUE TITLE
Preprocessing: help with parameter

### ISSUE THREAD

**Issue by Ferlix** [pytorch/fairseq#3265]
I'm training a couple of transformer for some translation tasks to make a research, but I'm not sure if the fairseq-preprocess command does what I want to. Specifically, I'm wondering about the parameter --tokenizer and --bpe.

When we specify these, like --tokenizer moses, is the preprocessing going to tokenize, or we are just telling to the script that the data was already tokenized using the one indicated? I'm wondering the same for the parameter --bpe.

On top of that, do we need to give these two parameters again to the fairseq-train command right? 

I know it's probably a silly question, but I would like some clarification, as the documentation is a bit vague.

**Comment by lematt1991** [comment]
Hmm, I'm  not sure why these arguments are even visible for `fairseq-preprocess` as they seem to meant for use with the torch hub interface (Maybe @myleott  or @alexeib have more context on this?).  To clarify, you should apply tokenization and BPE encoding prior to calling `fairseq-preprocess`.

**Comment by Ferlix** [comment]
@lematt1991 thanks a lot for the clarification. I had this doubt as the example for the translator use the moses library and the subword-nmt before using the fairseq library, but in the documentation they were given as possible parameters. 
I assume that I don't need to specify these parameter in the `fairseq-preprocess` and `fairseq-train` right?

Thanks a lot for your time! :)

**Comment by lematt1991** [comment]
> I assume that I don't need to specify these parameter in the fairseq-preprocess and fairseq-train right?

Tha's correct

**Comment by lematt1991** [comment]
Closing for now.  Please open a new issue if you are still having problems.
