### ISSUE TITLE
Is there any way to reduce the memory size of bin and model?

### ISSUE THREAD

**Issue by we29758143** [pytorch/fairseq#3269]
When I inference the model, we need bin file(dictionary) and model(checkpoint.pt), however, these two files are too large. (~ 5G)

Is there any way that I can reduce the size of these two files?

**Comment by olafthiele** [comment]
Both the dictionary and model carry all the information in an already somewhat packed way. You can build a smaller KenLM model, but it will have "less" information in it. As for the neural net itself, there might be some way of pruning it, but again you would loose information. But especially for the XSLR I am unsure whether there is another way. Anybody?

**Comment by lematt1991** [comment]
Yeah can try reducing the size of the dictionary.  This will reduce the dictionary size and the number of parameters in the model.  You can also try reducing the size of other parameters in the model
