### ISSUE TITLE
How can I get the vocab distribution at each step in the decoder

### ISSUE THREAD

**Issue by ShiraKadosh** [pytorch/fairseq#327]
Hello dear folks,

How can I get the vocab distribution at each step in the decoder.
After I successfully trained the model,
I would like to access the probability distribution over the vocabulary at each step, in the decoder. Say given the context of a target word, how can I get the probs for the target?

Ideally, given a sentence w_1 w_2 ... w_i ...w_n, is there any possibility to get the probability P(w_i = w_j | context)  for all w_j I have in the vocabulary, given that context consist of both the prefix and the postfix of w_i. If postfix is not possible, then only from the prefix.

I think it might be in fconv.py in the Decoder class, the incremental_inference function. But I can't figure out exactly how.

Thank you so much ahead,
Victor

**Comment by edunov** [comment]
You can't get postfix with a translation model, translations are left to right, so the model is trained to see prefixes only. For language models the story is different, but again, you seem to be talking about translation. 

You can get log probs for each word in the vocabulary by inspecting lprobs variable here: 
https://github.com/pytorch/fairseq/blob/master/fairseq/sequence_generator.py#L299

Be careful about batching and beam size though, it might be easier to put a breakpoint and inspect the content of this tensor before changing it.

**Comment by robotsp** [comment]
@shirakad  do you solve your problem, I have the same problem as well. Thanks!
