### ISSUE TITLE
How can I use XLSR-53 with Transformers?

### ISSUE THREAD

**Issue by PhilipMay** [pytorch/fairseq#3272]
Hi,
is it possible to use the multilingual wav2vec model called "XLSR-53" with transformers?
Thanks
Philip

**Comment by rodrigoheck** [comment]
My question as well.

**Comment by guillefix** [comment]
+1 Is it possible to use them for ASR? And if they need fine tuning how hard is it? how do we do it?

**Comment by alexeib** [comment]
you might want to open this issue in the transformers github
@patrickvonplaten
