### ISSUE TITLE
Optimize model for faster generation with training mode enabled

### ISSUE THREAD

**Issue by patelrajnath** [pytorch/fairseq#328]
Hi, I'm trying to add on-the-fly adaptation in fairseq-decoder. I'm able to run it with commenting out the code related to the "make_generation_fast" method. Is there any way to optimize the model for the generation with keeping the training-mode enabled? 

Please suggest. Thank you.

**Comment by edunov** [comment]
What exactly happens if you don't make_generation_fast? We did something similar in this paper https://arxiv.org/abs/1711.04956   but the code is a bit out of date now.  

Here is the relevant piece of code that we used to generate on the fly: 
https://github.com/pytorch/fairseq/blob/classic_seqlevel/fairseq/criterions/fairseq_sequence_criterion.py#L187

**Comment by patelrajnath** [comment]
Hi, Thanks for the quick response.

So in our case, we train (adapt) the model during the generation. The process is as follows-
1. We extract sentence pairs from translation memory, similar to the source sentence
2. Using the above we update/train the model parameter
3. We decode the source segment using the updated model

So in the above process, if we use make_generation_fast(), we can not use the model for training as it removes (https://github.com/pytorch/fairseq/blob/0d63cf03a949ea01d18c2b61281a5d124a6d6a7f/fairseq/models/fairseq_model.py#L96) some of the parameter required for training. However, if we don't (use make_generation_fast) it makes the generation really slow.

**Comment by myleott** [comment]
What model are you using? make_generation_fast is designed for when you no longer need to train with the model, and sometimes has model-specific optimizations for inference. It is not necessarily reversible, thus why you cannot continue training after calling it.

How big is the speed difference that you observe? It shouldn’t be too large...

**Comment by patelrajnath** [comment]
Hi @myleott  
Thanks for the response. On a moderate CPU machine, the generation without "make_generation_fast" is **6 times slower** than with that function.

If I try to train the model after applying the function, it complaints for the following error-
```python
self.model.train()
TypeError: train() missing 1 required positional argument: 'mode'
```

**Comment by patelrajnath** [comment]
@edunov @myleott 
I commented line numbers, 108-114 in fairseq_model.py module (https://github.com/pytorch/fairseq/blob/b1521f962e4ca670311c0cd0c8b1dadf310cb242/fairseq/models/fairseq_model.py#L108). Now it works fine. Also, I can confirm that training loss is exactly the same as without applying the make_generation_fast function, so the training procedure is unaffected by commenting those lines. 

Thanks!

**Comment by patelrajnath** [comment]
@myleott @edunov 
Sorry, the loss differs actually. It was just for that segment. Following is the log (in make_generation_fast the above-mentioned lines:108-114, are commented)- 

**With make_generation_fast**
| epoch 001 | loss 3.724 | ppl 13.21 | wps 0 | ups 5.1 | wpb 130 | bsz 1 | num_updates 1 | lr 0.15 | gnorm 4.920 | clip 100% | oom 0 | wall 0
| epoch 002 | loss 3.749 | ppl 13.44 | wps 0 | ups 7.4 | wpb 130 | bsz 1 | num_updates 2 | lr 0.15 | gnorm 4.943 | clip 100% | oom 0 | wall 0
| epoch 003 | loss 3.472 | ppl 11.09 | wps 0 | ups 7.4 | wpb 130 | bsz 1 | num_updates 3 | lr 0.15 | gnorm 4.916 | clip 100% | oom 0 | wall 0
| done training in 0.5 seconds

**Without make_generation_fast**
| epoch 001 | loss 3.724 | ppl 13.21 | wps 0 | ups 3.4 | wpb 130 | bsz 1 | num_updates 1 | lr 0.15 | gnorm 2.604 | clip 100% | oom 0 | wall 0
| epoch 002 | loss 3.810 | ppl 14.03 | wps 0 | ups 5.6 | wpb 130 | bsz 1 | num_updates 2 | lr 0.15 | gnorm 2.610 | clip 100% | oom 0 | wall 0
| epoch 003 | loss 3.613 | ppl 12.24 | wps 0 | ups 5.4 | wpb 130 | bsz 1 | num_updates 3 | lr 0.15 | gnorm 2.605 | clip 100% | oom 0 | wall 1
| done training in 0.7 seconds

Is it normal? I can see that PPL is better in the first case. Please suggest.

**Comment by myleott** [comment]
Well make_generation_fast does a few things, some of which change the results and some which don’t. For example, it removes the weight norm, so if you resume training after that then it will give different results. For fconv, make_generation_fast will also change the batch matrix multiplication to one that is optimized for inference: https://github.com/pytorch/fairseq/blob/6381cc977fa909bd53c8915a18684e49b3507332/fairseq/models/fconv.py#L379

I believe those are the only two changes. Can you time the impact of each one separately and see which is causing the huge speedup? If it’s the bmm change then that should be reversible. If it’s the weight norm then you are probably out of luck, since that change is not reversible.

**Comment by patelrajnath** [comment]
@myleott Thanks! I'll check the speedup in both cases.

**Comment by patelrajnath** [comment]
@myleott 
I collected the speedup separately when applying either/both of them. Following is the stats (time is in seconds and averaged with three runs).

|| || Training time || Translation time || Response time||
| Remove weight norm + Replace torch.bmm with BeamableMM | 0.73 | **0.08** | 0.81 |
|  Remove weight norm | 0.63 | **0.08** |  0.71 |
| Replacing torch.bmm with BeamableMM | 0.87 | 0.22 | 1.09 |
| Without Optimization | 0.86 | 0.20 | 1.06 |

It is to be noted here that the major speedup is when removing "weight norm", which is non-reversible. Now I guess I need to think for some other workarounds, please suggest if you could think of any?

**Comment by davidecaroselli** [comment]
Interesting topic indeed! We were also looking at this framework for adaptation. Do you have any updates?

**Comment by patelrajnath** [comment]
@davidecaroselli 
I tried a workaround to have two copies of the model- 
1. Optimized one for translation in general
2. Base model (without optimization) for the case of on-the-fly adaptation. 

In the second case when we tune+optimize the model for generation, the model-reset part requires rebuilding the model and copying the trained parameters. Which is time taking process and slows down the overall translation speed. 

@myleott 
I'm thinking to test this case - Remove weight norm + Replace torch.bmm with BeamableMM
In my understanding, this will affect more if we need to fine tune the model with a good amount of data. For 1-2 segments/epochs, it should not matter much.

**Comment by davidecaroselli** [comment]
I'm really curious to test a "tuning" step on an optimized-model, I agree that for very few cycles on very tiny dataset, quality optimizations do not really matters.

But the fact is, did yo say that calling `make_generation_fast()` resulted in being unable to actually run training? Didi you solve that?

**Comment by patelrajnath** [comment]
This solves that problem- https://github.com/pytorch/fairseq/issues/328#issuecomment-435913689

**Comment by huihuifan** [comment]
seems this may be resolved, but please re-open if not. Thank you!

**Comment by vince62s** [comment]
@myleott sorry to revive this old thread. I tested your BeamableMM trick but got odd results.
I posted here: https://discuss.pytorch.org/t/weird-matmul-behavior/164916
