### ISSUE TITLE
Wav2Vec 2: Data for training a new model

### ISSUE THREAD

**Issue by ThuPro27** [pytorch/fairseq#3285]
Hi, 
Is it necessary that each speech audio file in training dataset contains only one speaker?
Thanks.

**Comment by olafthiele** [comment]
No, but they should be separated without overlapping. But you would need more material if finetuning.

**Comment by ThuPro27** [comment]
Thank you for your answer. So what are the requirements  for constructing a new training dataset?

**Comment by olafthiele** [comment]
Check the paper to see what material they used. And it depends on your use case. If you want to transcribe phone calls, I wouldn't take spotless training files :-)
