### ISSUE TITLE
Still facing below issue. Please check

### ISSUE THREAD

**Issue by MrityunjoyS** [pytorch/fairseq#3294]
https://github.com/pytorch/fairseq/issues/2851#

**Comment by MrityunjoyS** [comment]
We've trained the trained the unsupervised model on top of "Wav2Vec 2.0 Base". Then finetuned over our own audio file with transcript. Then,
While trying to infer with below command :- 

`python3 examples/speech_recognition/infer.py /path_to_tsv/ --task audio_pretraining --nbest 1 --path /path_to_checkpoint/checkpoint_best.pt --gen-subset test --results-path /save_path/ --criterion ctc --labels ltr --max-tokens 4000000  --w2l-decoder viterbi --lm-weight 2 --word-score -1 --sil-weight 0`

Getting below error :-

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/root/miniconda3/envs/asrfair/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
>     state = load_checkpoint_to_cpu(filename, arg_overrides)
>   File "/root/miniconda3/envs/asrfair/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
>     state = _upgrade_state_dict(state)
>   File "/root/miniconda3/envs/asrfair/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 420, in _upgrade_state_dict
>     state["args"].task = "translation"
> AttributeError: 'NoneType' object has no attribute 'task'

Please look into this. Thank you

**Comment by alexeib** [comment]
this shouldnt be happening with an updated version of fairseq. please get latest master and reopen if it is an issue
