### ISSUE TITLE
Loading from pretrained downloads tokenization resources even when provided

### ISSUE THREAD

**Issue by mogeid** [pytorch/fairseq#3297]
I'm attempting to load a Roberta model I pretrained with custom Byte-Pair Encodings. I am providing the `merges.txt` and `vocab.json`, as well as the `dict.txt` files in the `data` folder.
```python
roberta = RobertaModel.from_pretrained(model_path, checkpoint_file='checkpoint_best.pt', data_name_or_path=data)
```
However, this line still attempts to download the BPE files from dl.fbaipublicfiles.com. As far as I can tell from the [`from_pretrained` hub utils function](https://github.com/pytorch/fairseq/blob/e5e8b3fee1e57a7abf35ad1a3ff223a2b7190c65/fairseq/hub_utils.py#L23), the provided files should override the need for the `encoder.json` and `vocab.bpe` files from dl.fbai.publicfiles.com.
Is this expected behaviour?
I have also tried moving the files to the model folder and renaming them to `encoder.json` and `vocab.bpe`

#### Environment
 - fairseq 1.0.0
 - pytorch 1.7.0
 - python 3.6

**Comment by lematt1991** [comment]
Can you try:

```Python
roberta = RobertaModel.from_pretrained(model_path, checkpoint_file='checkpoint_best.pt', data_name_or_path=data, bpe="hf_byte_bpe", bpe_vocab="vocab.json", bpe_merges="merges.txt")
```
Where `"vocab.json"` and `"merges.txt"` point to your custom versions.

**Comment by mogeid** [comment]
> ```python
> bpe="hf_byte_bpe", bpe_vocab="vocab.json", bpe_merges="merges.txt"
> ```

That did the trick. Thank you :)
