### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'conv_feature_layers'

### ISSUE THREAD

**Issue by debadityamandal** [pytorch/fairseq#3298]
I was reading "Wav2Vec 2.0 Large (LV-60) + Self Training 960 hours" pre-trained model using torch but I am getting following error-
AttributeError                            Traceback (most recent call last)
<ipython-input-12-a6c36b388893> in <module>
      2 from fairseq.models.wav2vec import Wav2Vec2Model
      3 cp=torch.load("/media/administrator/hdd/speech_recognition_wav2vec/wav2vec_vox_960h_pl.pt")
----> 4 model=Wav2Vec2Model.build_model(cp['args'],task=None)

/media/administrator/hdd/speech_recognition_wav2vec/fairseq/fairseq/models/wav2vec/wav2vec2.py in build_model(cls, cfg, task)
    329         """Build a new model instance."""
    330 
--> 331         return cls(cfg)
    332 
    333     def apply_mask(self, x, padding_mask):

/media/administrator/hdd/speech_recognition_wav2vec/fairseq/fairseq/models/wav2vec/wav2vec2.py in __init__(self, cfg)
    226         self.cfg = cfg
    227 
--> 228         feature_enc_layers = eval(cfg.conv_feature_layers)
    229         self.embed = feature_enc_layers[-1][0]
    230 

AttributeError: 'Namespace' object has no attribute 'conv_feature_layers'

I wrote the following code to access pre-trained model-
import torch
from fairseq.models.wav2vec import Wav2Vec2Model
cp=torch.load("/media/administrator/hdd/speech_recognition_wav2vec/wav2vec_vox_960h_pl.pt")
model=Wav2Vec2Model.build_model(cp['args'],task=None)

**System Configuration**

- PyTorch Version: 1.7.1
- OS: Linux
- Python Version: 3.8.0
- CUDA Version: 10.2
- Installed fairseq from source and followed instructions mentioned in README.md

**Comment by jlmarrugom** [comment]
Hi, I solve it installing the version 0.10.1 of FairSeq.
`pip install fairseq==0.10.1`
