### ISSUE TITLE
Does Fairseq support auto complete?

### ISSUE THREAD

**Issue by aj7tesh** [pytorch/fairseq#3301]
Does Fairseq support autocomplete and forced translation feature as of now? For example generating translation from source to target language, I wish to provide couple of starting words from output and want to model to predict rest of translation, kind of autocomplete with best possible translation.
Is something like this achievable in Fairseq.

**Comment by erip** [comment]
Yes. See [`PrefixConstrainedBeamSearch`](https://github.com/pytorch/fairseq/blob/master/fairseq/search.py#L147).

**Comment by gowtham1997** [comment]
@erip I looked at PrefixConstrainedBeamSearch. I'm currently not sure what should `prefix_allowed_tokens_fn` be in this case?

Also, can you give me an example of using this in conjunction with fairseq_interactive for inference?

**Comment by maxiek0071** [comment]
@erip I also would like to follow-up on this thread. Any news on this?

**Comment by erip** [comment]
Search the open pull requests. There's on that adds documentation, but it hasn't been merged.
