### ISSUE TITLE
Cannot reproduce SimulST from README

### ISSUE THREAD

**Issue by sarapapi** [pytorch/fairseq#3302]
Hi all,
I'm trying to reproduce your system for simultaneous ST and in the README it is written that, for data preprocessing and ASR pre-training, I have to follow the offline S2T part.
I've preprocessed the MustC data and I've downloaded the best_checkpoint from the ASR offline pre-training, then I've tried to launch the wait-k version of the training but this error arises:
```
Traceback (most recent call last):
  File "/home/fonorato/anaconda3/envs/myenv/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/fonorato/fairseqSLT/fairseq/fairseq_cli/train.py", line 450, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/distributed/utils.py", line 364, in call_main
    main(cfg, **kwargs)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq_cli/train.py", line 79, in main
    model = task.build_model(cfg.model)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/tasks/speech_to_text.py", line 110, in build_model
    return super(SpeechToTextTask, self).build_model(args)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/tasks/fairseq_task.py", line 633, in build_model
    model = models.build_model(args, self)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/models/speech_to_text/convtransformer.py", line 189, in build_model
    encoder = cls.build_encoder(args)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/models/speech_to_text/convtransformer.py", line 161, in build_encoder
    component=encoder, checkpoint=args.load_pretrained_encoder_from
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/checkpoint_utils.py", line 688, in load_pretrained_component_from_model
    component.load_state_dict(component_state_dict, strict=True)
  File "/home/fonorato/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ConvTransformerEncoder:
        Missing key(s) in state_dict: "conv.0.weight", "conv.0.bias", "conv.2.weight", "conv.2.bias", "out.weight", "out.bias".
        Unexpected key(s) in state_dict: "subsample.conv_layers.0.weight", "subsample.conv_layers.0.bias", "subsample.conv_layers.1.weight", "subsample.conv_layers.1.bias", "layer_norm.weight", "layer_norm.bias".

```
Which is the architecture size that you have used in your paper "SimulMT to SimulST: Adapting Simultaneous Text Translation to End-to-End Simultaneous Speech Translation"? Is it incompatible with your s2t_transformer_s architecture whose checkpoints are downloadable from the README of the offline part?

I've noticed also that the link in the simultaneous README which points to the offline README is broken because you've recently moved the offline speech2text part from the examples to the main part of the repository.

Thank you

**Comment by jmp84** [comment]
@sarapapi can you give the link of the checkpoint you downloaded?
The model for the offline example is s2t_transformer while the model for the simultaneous example is slightly different, it's a convtransformer.
@xutaima, would it be possible to also make an ASR pre-trained checkpoint available for download?

**Comment by sarapapi** [comment]
> @sarapapi can you give the link of the checkpoint you downloaded?
> The model for the offline example is s2t_transformer while the model for the simultaneous example is slightly different, it's a convtransformer.
> @xutaima, would it be possible to also make an ASR pre-trained checkpoint available for download?

Hi, thanks for your reply.
I've seen that the README is recently changed (in particular, the part referred to the ASR pre-training) and a downloadable checkpoint would be very helpful.
Is the difference between s2t_transformer and convtransformer the presence of attention layers after the CNNs?

**Comment by jmp84** [comment]
@sarapapi, sorry for the late reply, the main difference is that the subsampler is slightly different, compare https://github.com/pytorch/fairseq/blob/master/fairseq/models/speech_to_text/s2t_transformer.py#L50 vs https://github.com/pytorch/fairseq/blob/master/fairseq/models/speech_to_text/convtransformer.py#L241
You cannot load the pre-trained s2t_transformer and use it to initialize the encoder of convtransformer.py
While we prepare the checkpoint, I recommend following the instructions (including ASR pre-training).

**Comment by xutaima** [comment]
Thanks @jmp84 for the explanation!

As @jmp84  mentioned, the pre-trained ASR model has to have the same architecture (convtransformer_espnet) as the SimulST model. You can follow the instruction [here](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/simulst_mustc_example.md#asr-pretraining) to pretrain ASR model. 

[Here](https://dl.fbaipublicfiles.com/simultaneous_translation/must_c_v1_en_de_pretrained_asr) is a trained ASR checkpoint. You can use it to initialize the SimulST encoder for now. We are working on adding it to the README file.

**Comment by jmp84** [comment]
https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/simulst_mustc_example.md now has the pre-trained ASR checkpoint. Please let us know if you have any issues with the instructions.

**Comment by mzaidi59** [comment]
@xutaima @sarapapi @jmp84 

I could not find this in other issues or documentation. 
Can you provide some help regarding how to load the checkpoint in `*.zip` format, the earlier checkpoints were `*.pt`?

**Comment by xutaima** [comment]
@mzaidi59 Hi, we didn't compress the checkpoint to a zip file. The link is in this [doc](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/simulst_mustc_example.md) is the binary (or the `*.pt` you mentioned) that you could directly load with `--load-pretrained-encoder-from` for training or ` --model-path` for evaluation. Do you have any issue load the checkpoint? Could you please provide more details?

**Comment by mzaidi59** [comment]
Both the [ASR](https://dl.fbaipublicfiles.com/simultaneous_translation/must_c_v1_en_de_pretrained_asr) and [Simul ST](https://dl.fbaipublicfiles.com/simultaneous_translation/convtransformer_wait5_pre7) checkpoints provided in this doc seem to be `.zip` files.
Evaluating using the provided [databin](https://dl.fbaipublicfiles.com/simultaneous_translation/must_c_v1.0_en_de_databin.tgz) and ST checkpoint(using `--model_path`) gives the following error.
```
2021-03-17 10:19:51 | INFO     | fairseq.data.audio.speech_to_text_dataset | Cannot find /home/user/receive/databin/config_gvmcn_specaug.yaml
..
..
raise FileNotFoundError(f"Dict not found: {dict_path}")
FileNotFoundError: Dict not found: /home/user/receive/databin/dict.txt
```

In the databin, if I rename the `spm_unigram10000_st.txt` to `dict.txt` and `config_st.yaml` to `config_gvmcn_specaug.yaml`, it gives some random output with 0 BLEU score.

Sample outputs
```
{"index": 20, "prediction": "Ich bin \"Windoin\". </s>", "delays": [1680.0, 1960.0, 3640.0, 3640.0], "elapsed": [6249.568157196045, 7562.153301239014, 15698.38942527771, 15700.776948928833], "prediction_length": 4, "reference": "Sowohl in meinem Beruf bei Robin Hood als auch in meinem Nebenberuf als freiwilliger Feuerwehrmann bin ich Zeuge von Gro\u00dfz\u00fcgigkeit und Freundlichkeit im gro\u00dfen Ma\u00dfstab, aber ich sehe auch Taten der N\u00e4chstenliebe und des Muts von Einzelnen.", "source": ["/speech_translation/data/clean/MUSTC_ST/seg/ted_1096_seg_21.wav", "samplerate: 16000 Hz", "channels: 1", "duration: 13.300 s", "format: WAV (Microsoft) [WAV]", "subtype: Signed 16 bit PCM [PCM_16]"], "source_length": 13300.0, "reference_length": 37, "metric": {"sentence_bleu": 0.0, "latency": {"AL": 2205.0, "AP": 0.205263152718544, "DAL": 1680.0}, "latency_ca": {"AL": 9486.7041015625, "AP": 0.8498287796974182, "DAL": 7648.9794921875}}}
{"index": 21, "prediction": "Ich bin \"Windoin\". </s>", "delays": [1680.0, 1960.0, 3640.0, 3640.0], "elapsed": [6260.043792724609, 7591.891965866089, 15693.130865097046, 15695.445909500122], "prediction_length": 4, "reference": "Und wissen Sie was ich gelernt habe? Sie sind alle wichtig. Wenn ich mich also in diesem Raum umsehe und Menschen sehe, die entweder schon einen beachtenswerten Erfolg erreicht haben oder auf ihrem Weg dorthin sind, m\u00f6chte ich folgende Erinnerung anbieten: Warten Sie nicht.", "source": ["/speech_translation/data/clean/MUSTC_ST/seg/ted_1096_seg_22.wav", "samplerate: 16000 Hz", "channels: 1", "duration: 14.200 s", "format: WAV (Microsoft) [WAV]", "subtype: Signed 16 bit PCM [PCM_16]"], "source_length": 14200.0, "reference_length": 44, "metric": {"sentence_bleu": 0.0, "latency": {"AL": 2256.66650390625, "AP": 0.19225351512432098, "DAL": 1680.00048828125}, "latency_ca": {"AL": 9532.7998046875, "AP": 0.7964878678321838, "DAL": 7426.587890625}}}
```

**Comment by xutaima** [comment]
Thanks for the detailed information. Did you run the unzip command on the model file we provided? It looks that the model file is successfully loaded. The error you got is mainly because we had a bug in the databin and the agent. We just update the databin and fixed some bugs in dd74992, with new instructions on [how to evaluate a pretrained model](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/simulst_mustc_example.md#inference--evaluation). Could you please redownload the [databin](https://dl.fbaipublicfiles.com/simultaneous_translation/must_c_v1.0_en_de_databin.tgz) and follow the new instruction?

Thank you so much for the feedback and sorry for the inconvenience.

**Comment by mzaidi59** [comment]
It is working now :+1: 
The `*.zip` file can be loaded normally like a `*.pt` checkpoint. 
Thanks a lot @xutaima for the quick response, I really appreciate it!

Another minor doubt, did you train your ASR and ST models in the Simul MuSTC [tutorial](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/simulst_mustc_example.md) using a single GPU?

**Comment by xutaima** [comment]
You are welcome!

As to the training, we actually used 8 volta gpus. Thanks for bring this up and I will add it to the tutorial. The models can also be trained with one gpu with `--update-freq 8`.
