### ISSUE TITLE
Resume pre-training RoBERTa with smaller context size

### ISSUE THREAD

**Issue by ruiqi-zhong** [pytorch/fairseq#3325]
How do I resume pretraining RoBERTa with a smaller context size (since my GPUs don't have a lot of memory)? 

To continue pretraining, I need to set the -restore-file to a pretrained directory; to reduce context size, I need to reduce -tokens-per-sample (e.g. 256). 

Then the program complains to me that it cannot load the model because the positional embedding size mismatches. 

What is the most efficient way to achieve the functionality? how do I change the code such that it can ignore embedding > 256? or I could potentially change the pretraining corpus such that the max sequence length is at most 256?

**Comment by myleott** [comment]
You can try modifying the state dict manually:
```python
import torch
cpt = torch.load('checkpoint.pt')
cpt['model'].keys()
# modify cpt['model'][...]
torch.save(cpt, 'checkpoint_updated.pt')
```

**Comment by ruiqi-zhong** [comment]
thanks, that works!!
