### ISSUE TITLE
Spacy related error in roberta.extract_features_aligned_to_words()

### ISSUE THREAD

**Issue by ZhendongLiu** [pytorch/fairseq#3339]
I had this error when using the extract_features_aligned_to_words(). It looks like this is Spacy related.
I have spacy = 3.0.5
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-104-bbd8876e5db2> in <module>
----> 1 roberta.extract_features_aligned_to_words("hello world!")

~/.cache/torch/hub/pytorch_fairseq_master/fairseq/models/roberta/hub_interface.py in extract_features_aligned_to_words(self, sentence, return_all_hiddens)
    125 
    126         nlp = alignment_utils.spacy_nlp()
--> 127         tokenizer = alignment_utils.spacy_tokenizer()
    128 
    129         # tokenize both with GPT-2 BPE and spaCy

~/.cache/torch/hub/pytorch_fairseq_master/fairseq/models/roberta/alignment_utils.py in spacy_tokenizer()
    113         try:
    114             nlp = spacy_nlp()
--> 115             spacy_tokenizer._tokenizer = nlp.Defaults.create_tokenizer(nlp)
    116         except ImportError:
    117             raise ImportError("Please install spacy with: pip install spacy")

AttributeError: type object 'EnglishDefaults' has no attribute 'create_tokenizer'`

**Comment by LakshmiVandanaNunna** [comment]
Hi, did you find a solution to this? I'm facing the same issue

**Comment by wenting-zhao** [comment]
This is an issue specific to spacy v3.  To fix it, go to fairseq/fairseq/models/roberta/alignment_utils.py ; on line 115, change ``spacy_tokenizer._tokenizer = nlp.Defaults.create_tokenizer(nlp)`` to ``spacy_tokenizer._tokenizer = nlp.tokenizer``, then it should work.
