### ISSUE TITLE
How to use fairseq for unsupervised or semisupervised translation？

### ISSUE THREAD

**Issue by zwhe99** [pytorch/fairseq#3345]
#### What is your question?
How to use fairseq for unsupervised or unsupervised translation？
I found the _SemisupervisedTranslationTask_. But i don't know how to use it.

 - fairseq Version (e.g., 1.0 or master): 0.10.2
 - PyTorch Version (e.g., 1.0):1.6
 - OS (e.g., Linux):Linux
 - How you installed fairseq (`pip`, source): pip 
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by Hbenmazi** [comment]
@myleott
