### ISSUE TITLE
Argument order error of files2rouge in bart example's README

### ISSUE THREAD

**Issue by Shengqiang-Zhang** [pytorch/fairseq#3346]
## 🐛 Bug
Instruction of arguments for files2rouge is:
`files2rouge reference summary`
However, in the README of bart example, the rouge evaluation uses:
`files2rouge test.hypo.tokenized test.hypo.target`
where the first argument is summary, and the second argument is the reference, which is the reverse format of that in the files2rouge's README.

**Comment by baoguangsheng** [comment]
I have the same concern about the argument order. Shouldn't the evaluation use: files2rouge test.hypo.target test.hypo.tokenized ?
