### ISSUE TITLE
Multilingual Translation - language-specific components

### ISSUE THREAD

**Issue by JoaoMCAlves** [pytorch/fairseq#3348]
## ❓ Questions and Help

Is there any way of identifying the source/target language inside the `transformer_layer.py`. I'm trying to have a language specific layer inside each transformer layer when performing multilingual translation with the task `translation_multi_simple_epoch`. But to do that I need to know which is the current language-pair. Is it possible?

**Comment by JoaoMCAlves** [comment]
no one knows?

**Comment by felixkreuk** [comment]
@JoaoMCAlves , did you figure it out? I am also wondering about this.
An ugly way to do that would be to use the --encoder-langtok and --decoder-langtok.
