### ISSUE TITLE
ValueError: Please build (or rebuild) Cython components with: `pip install  --editable .` or `python setup.py build_ext --inplace`.

### ISSUE THREAD

**Issue by wongz97** [pytorch/fairseq#3351]
### Before asking:   
1. search the issues.   not relevant for this question
2. search the docs.    No

#### What is your question?
i want to train my model but enounters an error.
#### Code
fairseq-train data-bin/iwslt14.tokenized.de-en --arch seq2seq_arch --encoder-dropout 0.2 --decoder-dropout 0.2 --optimizer adam --lr 0.005 --lr-shrink 0.5 --max-tokens 12000
   
Traceback (most recent call last):
  File "G:\Program Files\PyvirtualEnv\torchenv\Scripts\fairseq-train-script.py", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "e:\learnfairseq\fairseq\fairseq_cli\train.py", line 477, in cli_main
    distributed_utils.call_main(cfg, main)
  File "e:\learnfairseq\fairseq\fairseq\distributed\utils.py", line 364, in call_main
    main(cfg, **kwargs)
  File "e:\learnfairseq\fairseq\fairseq_cli\train.py", line 136, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(
  File "e:\learnfairseq\fairseq\fairseq\checkpoint_utils.py", line 228, in load_checkpoint
    epoch_itr = trainer.get_train_iterator(
  File "e:\learnfairseq\fairseq\fairseq\trainer.py", line 532, in get_train_iterator
    batch_iterator = self.task.get_batch_iterator(
  File "e:\learnfairseq\fairseq\fairseq\tasks\fairseq_task.py", line 285, in get_batch_iterator
    batch_sampler = dataset.batch_by_size(
  File "e:\learnfairseq\fairseq\fairseq\data\fairseq_dataset.py", line 145, in batch_by_size
    return data_utils.batch_by_size(
  File "e:\learnfairseq\fairseq\fairseq\data\data_utils.py", line 313, in batch_by_size
    raise ValueError(

#### What have you tried?
1): I have tried pip install  --editable . and it did't work.
2): When I tried this command python setup.py build_ext --inplace
I got these message
G:\Program Files\Python38\lib\site-packages\torch\include\c10/util/Optional.h(465): warning C4814: 'c10::optional<at::Generator>::contained_val': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
G:\Program Files\Python38\lib\site-packages\torch\include\c10/util/Optional.h(466): error C2556: 'at::Generator &c10::optional<at::Generator>::contained_val(void) const &': overloaded function differs only by return type from 'const at::Generator &c10::optional<at::Generator>::contained_val(void) const &'
G:\Program Files\Python38\lib\site-packages\torch\include\c10/util/Optional.h(460): note: see declaration of 'c10::optional<at::Generator>::contained_val'
G:\Program Files\Python38\lib\site-packages\torch\include\c10/util/Optional.h(466): error C2373: 'c10::optional<at::Generator>::contained_val': redefinition; different type modifiers
G:\Program Files\Python38\lib\site-packages\torch\include\c10/util/Optional.h(460): note: see declaration of 'c10::optional<at::Generator>::contained_val'
G:\Program Files\Python38\lib\site-packages\torch\include\ATen/core/TensorBody.h(694): error C2440: 'default argument': cannot convert from 'const c10::nullopt_t' to 'c10::optional<at::Generator>'
G:\Program Files\Python38\lib\site-packages\torch\include\ATen/core/TensorBody.h(694): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
G:\Program Files\Python38\lib\site-packages\torch\include\ATen/core/TensorBody.h(695): error C2440: 'default argument': cannot convert from 'const c10::nullopt_t' to 'c10::optional<at::Generator>'
G:\Program Files\Python38\lib\site-packages\torch\include\ATen/core/TensorBody.h(695): fatal error C1003: error count exceeds 100; stopping compilation
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version 1.6
 - OS (e.g., Linux): Win 10 64 bit
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): pip install  --editable .
 - Python version: 3.8.6
 - CUDA/cuDNN version: 10.1/7.6.5
 - GPU models and configuration: rtx 2070s
 - Any other relevant information:

**Comment by Hbenmazi** [comment]
Hi, Have you solved this error?

**Comment by Hbenmazi** [comment]
> ## ❓ Questions and Help
> ### Before asking:
> 1. search the issues.   not relevant for this question
> 2. search the docs.    No
> 
> #### What is your question?
> i want to train my model but enounters an error.
> 
> #### Code
> fairseq-train data-bin/iwslt14.tokenized.de-en --arch seq2seq_arch --encoder-dropout 0.2 --decoder-dropout 0.2 --optimizer adam --lr 0.005 --lr-shrink 0.5 --max-tokens 12000
> 
> Traceback (most recent call last):
> File "G:\Program Files\PyvirtualEnv\torchenv\Scripts\fairseq-train-script.py", line 33, in
> sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
> File "e:\learnfairseq\fairseq\fairseq_cli\train.py", line 477, in cli_main
> distributed_utils.call_main(cfg, main)
> File "e:\learnfairseq\fairseq\fairseq\distributed\utils.py", line 364, in call_main
> main(cfg, **kwargs)
> File "e:\learnfairseq\fairseq\fairseq_cli\train.py", line 136, in main
> extra_state, epoch_itr = checkpoint_utils.load_checkpoint(
> File "e:\learnfairseq\fairseq\fairseq\checkpoint_utils.py", line 228, in load_checkpoint
> epoch_itr = trainer.get_train_iterator(
> File "e:\learnfairseq\fairseq\fairseq\trainer.py", line 532, in get_train_iterator
> batch_iterator = self.task.get_batch_iterator(
> File "e:\learnfairseq\fairseq\fairseq\tasks\fairseq_task.py", line 285, in get_batch_iterator
> batch_sampler = dataset.batch_by_size(
> File "e:\learnfairseq\fairseq\fairseq\data\fairseq_dataset.py", line 145, in batch_by_size
> return data_utils.batch_by_size(
> File "e:\learnfairseq\fairseq\fairseq\data\data_utils.py", line 313, in batch_by_size
> raise ValueError(
> 
> #### What have you tried?
> 1): I have tried pip install --editable . and it did't work.
> 2): When I tried this command python setup.py build_ext --inplace
> I got these message
> G:\Program Files\Python38\lib\site-packages\torch\include\c10/util/Optional.h(465): warning C4814: 'c10::optionalat::Generator::contained_val': in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'
> G:\Program Files\Python38\lib\site-packages\torch\include\c10/util/Optional.h(466): error C2556: 'at::Generator &c10::optionalat::Generator::contained_val(void) const &': overloaded function differs only by return type from 'const at::Generator &c10::optionalat::Generator::contained_val(void) const &'
> G:\Program Files\Python38\lib\site-packages\torch\include\c10/util/Optional.h(460): note: see declaration of 'c10::optionalat::Generator::contained_val'
> G:\Program Files\Python38\lib\site-packages\torch\include\c10/util/Optional.h(466): error C2373: 'c10::optionalat::Generator::contained_val': redefinition; different type modifiers
> G:\Program Files\Python38\lib\site-packages\torch\include\c10/util/Optional.h(460): note: see declaration of 'c10::optionalat::Generator::contained_val'
> G:\Program Files\Python38\lib\site-packages\torch\include\ATen/core/TensorBody.h(694): error C2440: 'default argument': cannot convert from 'const c10::nullopt_t' to 'c10::optionalat::Generator'
> G:\Program Files\Python38\lib\site-packages\torch\include\ATen/core/TensorBody.h(694): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
> G:\Program Files\Python38\lib\site-packages\torch\include\ATen/core/TensorBody.h(695): error C2440: 'default argument': cannot convert from 'const c10::nullopt_t' to 'c10::optionalat::Generator'
> G:\Program Files\Python38\lib\site-packages\torch\include\ATen/core/TensorBody.h(695): fatal error C1003: error count exceeds 100; stopping compilation
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2
> 
> #### What's your environment?
> * fairseq Version (e.g., 1.0 or master):
> * PyTorch Version 1.6
> * OS (e.g., Linux): Win 10 64 bit
> * How you installed fairseq (`pip`, source): source
> * Build command you used (if compiling from source): pip install  --editable .
> * Python version: 3.8.6
> * CUDA/cuDNN version: 10.1/7.6.5
> * GPU models and configuration: rtx 2070s
> * Any other relevant information:

Hi, Have you solved this error?

**Comment by YBZh** [comment]
install the newest numpy version can solve this problem:
pip uninstall numpy
pip install numpy
