### ISSUE TITLE
Doubts in Simul MuSTC ST example

### ISSUE THREAD

**Issue by mzaidi59** [pytorch/fairseq#3360]
## ❓Doubts in Simul MuSTC ST example

I have a few doubts related to this [tutorial](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/simulst_mustc_example.md)

#### Question?
1. The pretrained checkpoints provided [for ST here](https://dl.fbaipublicfiles.com/simultaneous_translation/convtransformer_wait5_pre7) and pretrained ASR [here](https://dl.fbaipublicfiles.com/simultaneous_translation/must_c_v1_en_de_pretrained_asr) are zip files. Can you provide instructions about loading these checkpoints? In most of the other tutorials, the checkpoints are provided as `*.pt` which can be directly used.
2. What is the number of GPUs used for training the models?

**Comment by mzaidi59** [comment]
#### Answers
These doubts were clarified in a discussion with the author over [here](https://github.com/pytorch/fairseq/issues/3302#issuecomment-800097834)

1. `*.zip` can be directly loaded as `*.pt` 
2. ST was trained on 8 GPUs, I'm assuming ASR was trained on a single GPU since it has `--update-frequency=8`.

**Comment by jmp84** [comment]
@mzaidi59 I just made some edits to the tutorial to clarify: https://github.com/pytorch/fairseq/pull/3374
