### ISSUE TITLE
How can I fine-tune BART on my own datasets with the pre-trained task (i.e., the denoised autoencoding task)

### ISSUE THREAD

**Issue by xieyxclack** [pytorch/fairseq#3361]
How can I fine-tune BART on my own datasets with the pre-trained task (i.e., the denoised autoencoding task)?

Is there any tutorial about how to pre-process the datasets and how to set the denoised task?

Many THX :)

**Comment by clown-ck** [comment]
Hi, I meet the same question, do you solve this problem ? I use a totally different dictionary to preocess my corpus, and there is error:

1. size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([18000, 512]) from checkpoint, the shape in current model is torch.Size([22336, 512]).
2. size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([18000, 512]) from checkpoint, the shape in current model is torch.Size([22336, 512]).

How do you finetune your model? And do you know how to initiate the decoder with some command lines ?
