### ISSUE TITLE
Multilingual Translation - language-aware layers

### ISSUE THREAD

**Issue by ChristinaA1** [pytorch/fairseq#3368]
#### What is your question?

Hello, I'm trying to develop a multilingual model for NMT with language-specific layers. To do that, I was thinking about to condition on the target token. I'm using the multi_simple_epoch task to perform my experiments, I know how to append a target token at the beginning of every sentence (encoder-langtok), my question is: how do I know the target token inside the model, for example inside the transformer_layer. I would appreciate your help. Thank you very much!

**Comment by felixkreuk** [comment]
Hi @ChristinaA1, did you find a solution to your issue?
