### ISSUE TITLE
Memory issues when fine-tuning M2M 12B with the right GPUs

### ISSUE THREAD

**Issue by jaspock** [pytorch/fairseq#3383]
I am trying to fine-tune the largest M2M 12B model on two A100 GPUs (2x40GB), but I am finding some memory issues. I guess I am missing some command-line argument but tried many combinations in vain.

I can run `fairseq-generate` with no issues, though, and then fairseq uses both GPUs during translation.

I run the training process with:

```
fairseq-train data_bin --finetune-from-model /models/m2m-12B-2GPU/model.pt --save-dir /checkpoint 
--task translation_multi_simple_epoch --encoder-normalize-before 
--langs 'af,am,ar,ast,az,ba,be,bg,bn,br,bs,ca,ceb,cs,cy,da,de,el,en,es,et,fa,ff,fi,fr,fy,ga,gd,gl,gu,ha,he,hi,hr,ht,hu,hy,id,ig,ilo,is,it,ja,jv,ka,kk,km,kn,ko,lb,lg,ln,lo,lt,lv,mg,mk,ml,mn,mr,ms,my,ne,nl,no,ns,oc,or,pa,pl,ps,pt,ro,ru,sd,si,sk,sl,so,sq,sr,ss,su,sv,sw,ta,th,tl,tn,tr,uk,ur,uz,vi,wo,xh,yi,yo,zh,zu' 
--lang-pairs 'en-es,es-en' --max-tokens 1200 --decoder-normalize-before --sampling-method temperature 
--sampling-temperature 1.5 --encoder-langtok src --decoder-langtok --criterion label_smoothed_cross_entropy 
--label-smoothing 0.2 --optimizer adam --adam-eps 1e-06 --adam-betas '(0.9, 0.98)' --lr-scheduler inverse_sqrt --lr 3e-05 
--warmup-updates 2500 --max-update 40000 --dropout 0.3 --attention-dropout 0.1 --weight-decay 0.0 --update-freq 2 
--save-interval 1 --save-interval-updates 5000 --keep-interval-updates 10 --no-epoch-checkpoints --seed 222 
--log-format simple --log-interval 2 --patience 10 --arch transformer_wmt_en_de_big_pipeline_parallel --encoder-layers 24 
--decoder-layers 24 --encoder-attention-heads 16 --decoder-attention-heads 16 --encoder-ffn-embed-dim 16384 
--decoder-ffn-embed-dim 16384 --decoder-embed-dim 4096 --encoder-embed-dim 4096 --num-embedding-chunks 2 
--pipeline-balance '[29,22,1]' --pipeline-devices '[0,1,0]' --fp16 --dataset-impl mmap --pipeline-chunks 1 
--share-decoder-input-output-embed --share-all-embeddings --ddp-backend no_c10d --clip-norm 1.0
```

And I get the following error:

```
RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB 
(GPU 0; 39.59 GiB total capacity; 15.21 GiB already allocated; 110.19 MiB free; 15.21 GiB reserved in total by PyTorch)
```

My environment is: fairseq 0.10.2; fairscale 0.3.1; Cuda compilation tools, release 11.1, V11.1.105; Build cuda_11.1.TC455_06.29190527_0; CUDNN, 8.0.5; GPUs 2 x A100-SXM4-40GB.

**Comment by firdota** [comment]
hello, I have the same problem.  have you solved it?

**Comment by jaspock** [comment]
No. I simply gave up. If you decide to use the models with fewer parameters, I would go for MM100 instead (search for ``flores101_mm100_615M`` [here](http://www.statmt.org/wmt21/large-scale-multilingual-translation-task.html)), which has been mostly trained with the same languages also by Facebook developers. I remember I read somewhere about potential issues of M2M for some language pairs; since MM100 was released later (a few weeks ago, actually), maybe these issues have been fixed. However, note that the largest MM100 available is 20 times smaller than the largest M2M (0.61B vs 12B parameters). Carbon footprint will be smaller as well ;-)

Table 4 in the [FLORES-101 paper](https://scontent-mad1-1.xx.fbcdn.net/v/t39.8562-6/196203317_1861942553982349_5142503689226033347_n.pdf?_nc_cat=110&ccb=1-3&_nc_sid=ae5e01&_nc_ohc=mJ9KRIujizgAX818KBC&_nc_ht=scontent-mad1-1.xx&oh=1a27c24e9d68c015cf2f4b575fe4ceb1&oe=60EBF6CD) describes the languages involved. The model you download probably matches the one described in section 6 of the paper.  Figure 8 of the paper shows BLEU scores for all language pairs before any fine-tuning.

Sadly, I have not been able to fine-tune the 615M-parameter MM100 model in a 16GB GPU except if I use an extremely small batch size, so I guess you need a 24GB GPU minimum, or use the even smaller 0.17M-parameter MM100 model.

**Comment by firdota** [comment]
@jaspock thanks for your reply

**Comment by Fikavec** [comment]
Please tell me @jaspock how long you have been testing the inference (only translation, without fine-tuning) largest M2M 12B model on two A100 GPUs (2x40GB) (maybe in a large number of sentences or languages or around the clock). In your opinion, can largest M2M 12B model checkpoints from this repository (12b_last_chk_2_gpus.pt, 12b_avg5_chk_2_gpus.pt, or 12b_avg10_chk_2_gpus.pt) be considered fully compatible with two A100 GPUs, are there any crashes, oom, fully incorrect translations, what is the speed of inference (sentence translation)?

**Comment by jaspock** [comment]
Sorry, @Fikavec, but I don't remember the inference times and I don't have access to the GPUs right now so that I could rerun the models and tell you. Probably, it was slow compared to the smaller models and maybe not fast enough for interactive translation, but I don't remember having thought that it was so extremely slow as to give up. I simply run it to evaluate a thousand sentences, but I didn't find any stability issues.

**Comment by Fikavec** [comment]
Thanks for your reply, @jaspock! Inference time not so critical to me, but stability is important question. Thousand sentences is not enough to draw conclusions, but your's problem with OOM during fine-tuning on a100 can mean incompatible CUDA 11 (or Apmhere microarchitecture) with v100 pytorch checkpoints and, as a result, crashes, oom, fully incorrect translations on some languages or sentences (I'm saw such things with the Bert models trained under CUDA 9 after the update to CUDA 10) .
