### ISSUE TITLE
error when transfer NMT transformer to torch script

### ISSUE THREAD

**Issue by yjegssl** [pytorch/fairseq#3388]
#### What is your question?
error when transfer NMT transformer to torch 

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-21-a949a463979a> in <module>()
>       1 import fairseq
>       2 assert isinstance(en2de.models[0], fairseq.models.transformer.TransformerModel)
> ----> 3 torch.jit.script(en2de)
> 
> 18 frames
> /usr/local/lib/python3.7/dist-packages/torch/jit/_script.py in script(obj, optimize, _frames_up, _rcb)
>     941         obj = call_prepare_scriptable_func(obj)
>     942         return torch.jit._recursive.create_script_module(
> --> 943             obj, torch.jit._recursive.infer_methods_to_compile
>     944         )
>     945 
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py in create_script_module(nn_module, stubs_fn, share_types)
>     389     check_module_initialized(nn_module)
>     390     concrete_type = get_module_concrete_type(nn_module, share_types)
> --> 391     return create_script_module_impl(nn_module, concrete_type, stubs_fn)
>     392 
>     393 def create_script_module_impl(nn_module, concrete_type, stubs_fn):
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py in create_script_module_impl(nn_module, concrete_type, stubs_fn)
>     446 
>     447     # Actually create the ScriptModule, initializing it with the function we just defined
> --> 448     script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
>     449 
>     450     # Compile methods if necessary
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_script.py in _construct(cpp_module, init_fn)
>     389             """
>     390             script_module = RecursiveScriptModule(cpp_module)
> --> 391             init_fn(script_module)
>     392 
>     393             # Finalize the ScriptModule: replace the nn.Module state with our
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py in init_fn(script_module)
>     426             else:
>     427                 # always reuse the provided stubs_fn to infer the methods to compile
> --> 428                 scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
>     429 
>     430             cpp_module.setattr(name, scripted)
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py in create_script_module_impl(nn_module, concrete_type, stubs_fn)
>     446 
>     447     # Actually create the ScriptModule, initializing it with the function we just defined
> --> 448     script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
>     449 
>     450     # Compile methods if necessary
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_script.py in _construct(cpp_module, init_fn)
>     389             """
>     390             script_module = RecursiveScriptModule(cpp_module)
> --> 391             init_fn(script_module)
>     392 
>     393             # Finalize the ScriptModule: replace the nn.Module state with our
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py in init_fn(script_module)
>     426             else:
>     427                 # always reuse the provided stubs_fn to infer the methods to compile
> --> 428                 scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
>     429 
>     430             cpp_module.setattr(name, scripted)
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py in create_script_module_impl(nn_module, concrete_type, stubs_fn)
>     446 
>     447     # Actually create the ScriptModule, initializing it with the function we just defined
> --> 448     script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
>     449 
>     450     # Compile methods if necessary
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_script.py in _construct(cpp_module, init_fn)
>     389             """
>     390             script_module = RecursiveScriptModule(cpp_module)
> --> 391             init_fn(script_module)
>     392 
>     393             # Finalize the ScriptModule: replace the nn.Module state with our
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py in init_fn(script_module)
>     426             else:
>     427                 # always reuse the provided stubs_fn to infer the methods to compile
> --> 428                 scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
>     429 
>     430             cpp_module.setattr(name, scripted)
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py in create_script_module_impl(nn_module, concrete_type, stubs_fn)
>     446 
>     447     # Actually create the ScriptModule, initializing it with the function we just defined
> --> 448     script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
>     449 
>     450     # Compile methods if necessary
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_script.py in _construct(cpp_module, init_fn)
>     389             """
>     390             script_module = RecursiveScriptModule(cpp_module)
> --> 391             init_fn(script_module)
>     392 
>     393             # Finalize the ScriptModule: replace the nn.Module state with our
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py in init_fn(script_module)
>     426             else:
>     427                 # always reuse the provided stubs_fn to infer the methods to compile
> --> 428                 scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
>     429 
>     430             cpp_module.setattr(name, scripted)
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py in create_script_module_impl(nn_module, concrete_type, stubs_fn)
>     446 
>     447     # Actually create the ScriptModule, initializing it with the function we just defined
> --> 448     script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
>     449 
>     450     # Compile methods if necessary
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_script.py in _construct(cpp_module, init_fn)
>     389             """
>     390             script_module = RecursiveScriptModule(cpp_module)
> --> 391             init_fn(script_module)
>     392 
>     393             # Finalize the ScriptModule: replace the nn.Module state with our
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py in init_fn(script_module)
>     426             else:
>     427                 # always reuse the provided stubs_fn to infer the methods to compile
> --> 428                 scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
>     429 
>     430             cpp_module.setattr(name, scripted)
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py in create_script_module_impl(nn_module, concrete_type, stubs_fn)
>     450     # Compile methods if necessary
>     451     if concrete_type not in concrete_type_store.methods_compiled:
> --> 452         create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
>     453         # Create hooks after methods to ensure no name collisions between hooks and methods.
>     454         # If done before, hooks can overshadow methods that aren't exported.
> 
> /usr/local/lib/python3.7/dist-packages/torch/jit/_recursive.py in create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
>     333     property_rcbs = [p.resolution_callback for p in property_stubs]
>     334 
> --> 335     concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
>     336 
>     337 def create_hooks_from_stubs(concrete_type, hook_stubs, pre_hook_stubs):
> 
> RuntimeError: Can't redefine method: forward on class: __torch__.fairseq.modules.transformer_layer.TransformerDecoderLayer (of Python compilation unit at: 0x55be8daa6790)

#### Code

   
```
import torch
en2de = torch.hub.load('pytorch/fairseq', 'transformer.wmt16.en-de',
                       tokenizer='moses', bpe='subword_nmt')
en2de.eval()
torch.jit.script(en2de)
```
#### What have you tried?
torch.jit.script(en2de.models[0])
#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):0.10.2   
 - PyTorch Version (e.g., 1.0):1.8.0+cu101
 - OS (e.g., Linux):linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.1
 - CUDA/cuDNN version: 11.0

**Comment by INFOPAUL** [comment]
Hi @yjegssl ! I have same issue for speech transformer. Did you manage to fix this issue?
