### ISSUE TITLE
Relation of Wav2vec2.0 "max-sample-size" and audio time

### ISSUE THREAD

**Issue by CSLujunyu** [pytorch/fairseq#3394]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

I want to know the relation of Wav2vec2.0 "max-sample-size" and audio time. For example, when I set the "max_sample_size=320000", what is the duration of wav audios(16000Hz) ?

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by harveenchadha** [comment]
If your max_sample_size is 320000 and your sample rate is 16000 then it means at once you are allowing a file of 20 seconds.

320000/16000 = 20 seconds

**Comment by CSLujunyu** [comment]
Thanks~
