### ISSUE TITLE
How to evaluate wav2vec2 model without language model?

### ISSUE THREAD

**Issue by osamamo7sen** [pytorch/fairseq#3401]
#### What is your question?
I have finetuned a wav2vec2 model and in the file log the validation wer and wer-raw are present and it gives consistent numbers. I have not installed flashlight python bindings and I think that the wer is calculated without language model. Is this true or is it not working properly? Now I am not able to install flashlight, so how to evaluate the finetuned model without a lnaguage model and produce similar numbers to the ones that appear during the finetunig?

This is an example of the finetuning file log output:
[2021-03-24 11:54:34,370][fairseq_cli.train][INFO] - begin validation on "dev_other" subset
[2021-03-24 11:54:43,717][dev_other][INFO] - {"epoch": 81, "dev_other_loss": "10.401", "dev_other_ntokens": "1244.28", "dev_other_nsentences": "6.88372", "dev_other_nll_loss": "0.058", "dev_other_uer": "1.088", "dev_other_wer": "3.966", "dev_other_raw_wer": "3.966", "dev_other_wps": "6007.8", "dev_other_wpb": "1244.3", "dev_other_bsz": "6.9", "dev_other_num_updates": "80000", "dev_other_best_wer": "3.856"}

**Comment by osamamo7sen** [comment]
@alexeib

**Comment by alexeib** [comment]
use "viterbi" decoder - but for this you still need to install flashlight
or you can copy the code from ctc.py that does argmax decoding and adapt something like infer.py to use that instead of flashlight decoders

**Comment by srqj** [comment]
> use "viterbi" decoder - but for this you still need to install flashlight
> or you can copy the code from ctc.py that does argmax decoding and adapt something like infer.py to use that instead of flashlight decoders

Same question here: with the default setup from [Readme](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec#fine-tune-a-pre-trained-model-with-ctc), how is the "dev_other_wer" calculated without flashlight in the log? Thanks.

**Comment by alexeib** [comment]
"raw_wer" is computed with some simple code - this is the same as viterbi decoding, i just didnt get around to implementing it without depending on flashlight

"wer" is the same as "raw_wer" unless you provide ngram lm in the config, in which case it will in fact use flashlight decoder

**Comment by ishalyminov** [comment]
@alexeib quick question: apart from "wer" and "raw_wer", what does "best_wer" mean here?
```
[2022-01-18 05:41:02,006][fairseq_cli.train][INFO] - begin validation on "test" subset[2022-01-18 05:43:26,995][test][INFO] -
 {"epoch": 150, "test_loss": "24.118", "test_ntokens": "674.778", "test_nsentences": "13.3364",
  "test_nll_loss": "0.477", "test_uer": "7.599", "test_wer": "22.706", "test_raw_wer": "22.706",
  "test_wps": "1999.9", "test_wpb": "674.8", "test_bsz": "13.3", "test_num_updates": "20000",
  "test_best_wer": "14.46"}
```
I haven't installed any language model in my setup nor flashlight itself. Must be some oracle WER?
