### ISSUE TITLE
issue while fine tuning the wav2vec model

### ISSUE THREAD

**Issue by roboticsai** [pytorch/fairseq#3409]
## 🐛 Bug
When i run the fine tuning script on the wav2vec trained model. I'm getting below error everytime. 
```
Traceback (most recent call last):
  File "fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/home/robot/airobotics/speech/fairseq/fairseq/distributed/utils.py", line 366, in call_main
    main(cfg, **kwargs)
  File "/home/robot/airobotics/speech/fairseq/fairseq_cli/train.py", line 85, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=1)
  File "/home/robot/airobotics/speech/fairseq/fairseq/tasks/audio_pretraining.py", line 206, in load_dataset
    **self._get_mask_precompute_kwargs(task_cfg),
  File "/home/robot/airobotics/speech/fairseq/fairseq/data/audio/raw_audio_dataset.py", line 256, in __init__
    with open(manifest_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/robot/dataset/fairseq/libri_speech/audio/dev_other.tsv'
```
I'm following [this](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec) documentation to train and fine tune the wav2vec model on librespeech dataset. 
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):
I have generated the manifest and label data according to the instructions providd in that page. But when i run this command:
`fairseq-hydra-train task.data=/home/robot/dataset/fairseq/libri_speech/audio model.w2v_path=/home/robot/dataset/fairseq/libri_speech/models/wav2vec_small.pt --config-dir config/finetuning/ --config-name base_100h`
I'm getting the above error. 

### Environment
fairseq branch: master
os: ubuntu 20.04
cuda:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0

### Additional context

Since the documentation fore the speech recognition with wav2vec is little complex in the readme gude provided. Lots of developers are facing issue and taking longer time to use this framework. So i think it is better if the documentation guide is improved for better understanding and less error.

**Comment by RuABraun** [comment]
What is inside the `/home/robot/dataset/fairseq/libri_speech/audio` folder ?

**Comment by roboticsai** [comment]
Ok. after i changed the dev_other to train inside the confiruration file used by fine tuning script i.e base_100h.yal its is working.

**Comment by sathyagorla** [comment]
Hi @roboticsai 
can you please help me with testing of the saved checkpoint_best.pt model,
I am facing the issue in testing code with this error
ImportError: cannot import name 'base_architecture' from 'fairseq.models.wav2vec.wav2vec2_asr' (/home/Desktop/fairseq-main/fairseq/models/wav2vec/wav2vec2_asr.py)

can you please help me

**Comment by shuvohishab** [comment]
> If you look at the `base_100h` config file at `examples/wav2vec/configs/fintuning/base_100h.yaml` you'll see that the `dataset.valid_subset` field is set to `dev_other` which means the script is looking in your data directory (`/home/robot/dataset/fairseq/libri_speech/audio/`) for the files: `dev_other.tsv, dev_other.wrd, and dev_other.ltr` (if you're doing character recognition) in the same way as it is looking for your training dataset files.
> 
> I don't know how to turn validation off, so you'll have to create a dev/validation set in the same way as you created your training set and put those `dev_other` files in the data directory. If your validation set is named something else like `valid.tsv` you can just change the value in the `base_100h.yaml` file for the `dataset.valid_subset` field.

Thank you!! @dzubke
