### ISSUE TITLE
Trouble reproducing XLSR-53 numbers on CommonVoice

### ISSUE THREAD

**Issue by jefflai108** [pytorch/fairseq#3412]
Hi, 

I have issue reproducing the XLSR-53 numbers reported in the paper (https://arxiv.org/abs/2006.13979) on CommonVoice. I am getting an average **PER of 9.85** over 10 languages, while the paper report an average **PER of 7.6** (Table 1). I am using the latest version of fairseq, and I tried both 1-hour and 10-hour wav2vec2 finetuning configurations. I am wondering if someone could give me some tips on tuning it to the reported numbers? 
Thanks in advance!!

**Comment by zqs01** [comment]
@jefflai108 Hi,I have a question about XLSR-53 pretraining model. I cannot reproduce the results of the table. Does the CER results in the table contain the separator '|'. In other words, whether the delimiter ‘|’ is calculated when counting the CER. The results in the table seem to calculate the separator ‘|’. Have you encountered similar problems？ Thank you in advance for your reply.
 ![image](https://user-images.githubusercontent.com/40491290/129005228-15077785-237d-4ee9-b1ff-7e0b78b3c3b8.png)
