### ISSUE TITLE
Get an error  when using " from fariseq import libnat"

### ISSUE THREAD

**Issue by lmw0320** [pytorch/fairseq#3419]
I have installed the fairseq by pip install successfully.  But when I used the command " from fairseq import libnat"， it cause the error report: ImportError: cannot import name 'libnat'..
My fairseq version is 0.10.2 ----I also tryed to install the latest version of 1.0.0a0 by source code from github, but still had same problem. 
Hope someone can help me~~

**Comment by haorannlp** [comment]
Did you try "pip install --editable ." ?

**Comment by lmw0320** [comment]
> Did you try "pip install --editable ." ?

Yes, I have download the source code from github, and install the fairseq by the suggestion command:  pip install --editable . , but still failed。。

**Comment by i13harada1s** [comment]
@lmw0320 
I had the same issue, but I can solve it by the command described #2010: "python setup.py build_ext --inplace".

**Comment by conan1024hao** [comment]
I solved it by `python setup.py build_ext`
