### ISSUE TITLE
Does KenLM need to be trained with the same training corpus?

### ISSUE THREAD

**Issue by weiyengs** [pytorch/fairseq#3420]
Hi guys, I see that the KenLM binary that comes with LibriSpeech dataset is trained based on the LibriSpeech data. Does it work or perhaps even better if let's say the KenLM is trained from a different and bigger corpus(eg. Wikipedia). Is it okay if the vocab is different?

Thanks!!

**Comment by harveenchadha** [comment]
The dict for language model and the trained ASR model has to be the same!
