### ISSUE TITLE
Could nbest be larger than beam_size to get more hypos ?

### ISSUE THREAD

**Issue by SefaZeng** [pytorch/fairseq#3421]
## ❓ Questions and Help
I wanna get top 50 hypos for translation, but I don't want to set beam_size to a larget number because it will decrease the BLEU score. Then when I set nbest to 50 and 8 for beam_size, it just return 8 hypos. Is there any way to get top n translations which n is larger than beam_size ？
#### Code
  python3 $code_dir/fairseq-master/fairseq_cli/generate.py \
      $data \
      --results-path $results_path/result.txt \
      --path $model \
      --beam 8 \
      --batch-size 16 \
      --nbest 50
#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.9
 - PyTorch Version (e.g., 1.0) :1.4
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source):source
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: V100

**Comment by haorannlp** [comment]
beam size is always larger than or equal to nbest
