### ISSUE TITLE
numpy and cpython binary incompatibility

### ISSUE THREAD

**Issue by lsjiiia** [pytorch/fairseq#3426]
#### What is your question?
File "fairseq/data/data_utils_fast.pyx", line 1, in init fairseq.data.data_utils_fast
cython: language_level=3
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

#### Code
th2en = TransformerModel.from_pretrained(
        model_name_or_path=MODEL_BASE_DIR,
        checkpoint_file='checkpoint.pt',
        data_name_or_path=VOCAB_BASE_DIR,
        bpe='sentencepiece', sentencepiece_model=BPE_BASE_DIR + 'spm.th.model')
        # sentencepiece_vocab=BPE_BASE_DIR + 'spm.th.model')

print(th2en.translate(["งั้นเอาเป็นเวนติ แบล็คแอนด์ไวท์มอคค่าใส่นมสดกับวิปครีม จากสตาร์บัคส์สาขาห้างเบิร์ชวิลล์นะคะ"])

#### What's your environment?

 - fairseq Version (0.9.0):
 - PyTorch Version (1.6)
 - OS (Linux):
 - How you installed fairseq (pip install --editable .):
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information: numpy==1-19.5  Cython==0.29.22

**Comment by haorannlp** [comment]
You can  try to update your numpy version.

**Comment by ImanHosseini** [comment]
have the same issue. updated numpy, rebuilded again with: "python -m pip install --no-cache-dir --no-binary :all: --editable ./ " -> it didn't fix! tried multiple numpy versions (including latest)
