### ISSUE TITLE
Issue loading BART-large model finetuned on XSUM dataset 

### ISSUE THREAD

**Issue by xieyxclack** [pytorch/fairseq#3429]
I 'm trying to load bart.large.xsum finetuned weights:

bart = BARTModel.from_pretrained('./bart.large.xsum/', checkpoint_file='model.pt', data_name_or_path='./xsum-bin')
The checkpoint file is download from https://dl.fbaipublicfiles.com/fairseq/models/bart.large.xsum.tar.gz
And the dict.txt file is copy from that of bart.large.cnn

But I'm getting the following error :
RuntimeError: Error(s) in loading state_dict for BARTModel: 
         size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([50264, 1024]) from checkpoint, the shape in current model is torch.Size([50265, 1024]).
	size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([50264, 1024]) from checkpoint, the shape in current model is torch.Size([50265, 1024]).
	size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([50264, 1024]) from checkpoint, the shape in current model is torch.Size([50265, 1024]).

### Environment
fairseq Version： 0.10.2
PyTorch Version:   1.4.0
OS: Linux
How you installed fairseq (pip, source): pip
Python version: 3.6
CUDA/cuDNN version: 10.1

**Comment by clown-ck** [comment]
Hi, I meet the same question, do you solve this problem ? I use a totally different dictionary to preocess my corpus, and there is error:

size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([18000, 512]) from checkpoint, the shape in current model is torch.Size([22336, 512]).
size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([18000, 512]) from checkpoint, the shape in current model is torch.Size([22336, 512]).

How do you finetune your model? And do you know how to initiate the decoder with some command lines ?

**Comment by xieyxclack** [comment]
> Hi, I meet the same question, do you solve this problem ? I use a totally different dictionary to preocess my corpus, and there is error:
> 
> size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([18000, 512]) from checkpoint, the shape in current model is torch.Size([22336, 512]).
> size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([18000, 512]) from checkpoint, the shape in current model is torch.Size([22336, 512]).
> 
> How do you finetune your model? And do you know how to initiate the decoder with some command lines ?

I find that the problem I met is caused by the mismatch between the task ``translation`` and ``denoise`` (and blame to myself). Therefore I close this issue.
And I have no idea about your issue and could not provide suggestions for you.
