### ISSUE TITLE
Weights and/or training details for SQuAD result?

### ISSUE THREAD

**Issue by mboratko** [pytorch/fairseq#3433]
We are attempting to reproduce the results of BART on SQuAD reported in [this README](https://github.com/pytorch/fairseq/blob/master/examples/bart/README.md). Could you provide the fine-tuned weights and/or training details / hyperparameters used to achieve those results?

Thank you!

**Comment by sherlcok314159** [comment]
Hey, have you found any training detail of BART on SQuAD?
