### ISSUE TITLE
Dual Learning Task using Fairseq

### ISSUE THREAD

**Issue by VrutikShah** [pytorch/fairseq#3438]
#### I want to write a new task in fairseq for Translation using Dual Learning. 
As I am new to fairseq, I am not able to structure the code for a new dual learning task properly. It would be helpful if you could point me to any similar work. 

#### What I have tried:
So far, I have tried to directly run [Pytorch-translate](https://github.com/pytorch/translate/tree/master/pytorch_translate) as this repo has a Dual Learning Task defined. But, while executing, it has some runtime issues (mainly because it has been depreciated). Also, while using that repo, I am facing issues in the command line arguments to be passed for the task. Therefore, I want to look at a more recent work done in fairseq. I have tried to look it up online but have not found anything very relevant so far. 

#### My environment

 - fairseq Version: 0.10.2
 - PyTorch Version: 1.7.1
 - OS (e.g., Linux): Ubuntu 20.04.2
 - How you installed fairseq (`pip`, source): pip
 - Python version: 3.8.8
 - CUDA/cuDNN version: 11.2
 - GPU models and configuration: Tesla V100 (32GB) x 4
 - Any other relevant information:

**Comment by sharkchill-xy** [comment]
Hi, I am wondering if you have solved this problem since  I am faced with the same situation now. It will be appreciated if you share your progression on implementing dual learning based on fairseq.

**Comment by kkeleve** [comment]
> 嗨，我想知道你是否已经解决了这个问题，因为我现在面临着同样的情况。如果您分享您在基于 fairseq 实施双重学习方面的进展，我们将不胜感激。

Hello, I would like to ask if you have made any progress on this question? I want to implement dual machine translation on fairseq, so I am willing to ask you for a fee

**Comment by kkeleve** [comment]
> Hi, I am wondering if you have solved this problem since I am faced with the same situation now. It will be appreciated if you share your progression on implementing dual learning based on fairseq.
Hello, I would like to ask if you have made any progress on this question? I want to implement dual machine translation on fairseq, so I am willing to ask you for a fee

**Comment by kkeleve** [comment]
> Hi, I am wondering if you have solved this problem since I am faced with the same situation now. It will be appreciated if you share your progression on implementing dual learning based on fairseq.

Hello, I would like to ask if you have made any progress on this question? I want to implement dual machine translation on fairseq, so I am willing to ask you for a fee

**Comment by VrutikShah** [comment]
Hi @rookielxy @kkeleve ,
I did not use PyTorch-Translate in the end as there were persisting issues. I wrote the pipeline from scratch with fairseq. I suggest you try the same.
