### ISSUE TITLE
Mosesdecoder error when running prepare-iwslt14.sh

### ISSUE THREAD

**Issue by butoialexandra** [pytorch/fairseq#3442]
## ❓ Questions and Help

I am trying to train a new model following the example from [here](https://github.com/pytorch/fairseq/tree/master/examples/translation). When running bash prepare-iwslt14.sh I get the following output:

 

> Data successfully downloaded.
> de-en/
> de-en/IWSLT14.TED.dev2010.de-en.de.xml
> de-en/IWSLT14.TED.dev2010.de-en.en.xml
> de-en/IWSLT14.TED.tst2010.de-en.de.xml
> de-en/IWSLT14.TED.tst2010.de-en.en.xml
> de-en/IWSLT14.TED.tst2011.de-en.de.xml
> de-en/IWSLT14.TED.tst2011.de-en.en.xml
> de-en/IWSLT14.TED.tst2012.de-en.de.xml
> de-en/IWSLT14.TED.tst2012.de-en.en.xml
> de-en/IWSLT14.TEDX.dev2012.de-en.de.xml
> de-en/IWSLT14.TEDX.dev2012.de-en.en.xml
> de-en/README
> de-en/train.en
> de-en/train.tags.de-en.de
> de-en/train.tags.de-en.en
> pre-processing train data...
> Tokenizer Version 1.1
> Language: de
> Number of threads: 8
> Can't locate object method "new" via package "Thread" at mosesdecoder/scripts/tokenizer/tokenizer.perl line 130, <STDIN> line 16000.
> 
> Tokenizer Version 1.1
> Language: en
> Number of threads: 8
> Can't locate object method "new" via package "Thread" at mosesdecoder/scripts/tokenizer/tokenizer.perl line 130, <STDIN> line 16000.
> 
> clean-corpus.perl: processing iwslt14.tokenized.de-en/tmp/train.tags.de-en.tok.de & .en to iwslt14.tokenized.de-en/tmp/train.tags.de-en.clean, cutoff 1-175, ratio 1.5
> 
> Input sentences: 0  Output sentences:  0
> pre-processing valid/test data...
> orig/de-en/IWSLT14.TED.dev2010.de-en.de.xml iwslt14.tokenized.de-en/tmp/IWSLT14.TED.dev2010.de-en.de
> Tokenizer Version 1.1
> Language: de
> Number of threads: 8
> Can't locate object method "new" via package "Thread" at mosesdecoder/scripts/tokenizer/tokenizer.perl line 163, <STDIN> line 887.
> 
> orig/de-en/IWSLT14.TED.tst2010.de-en.de.xml iwslt14.tokenized.de-en/tmp/IWSLT14.TED.tst2010.de-en.de
> Tokenizer Version 1.1
> Language: de
> Number of threads: 8
> Can't locate object method "new" via package "Thread" at mosesdecoder/scripts/tokenizer/tokenizer.perl line 163, <STDIN> line 1565.
> 
> orig/de-en/IWSLT14.TED.tst2011.de-en.de.xml iwslt14.tokenized.de-en/tmp/IWSLT14.TED.tst2011.de-en.de
> Tokenizer Version 1.1
> Language: de
> Number of threads: 8
> Can't locate object method "new" via package "Thread" at mosesdecoder/scripts/tokenizer/tokenizer.perl line 163, <STDIN> line 1433.
> 
> orig/de-en/IWSLT14.TED.tst2012.de-en.de.xml iwslt14.tokenized.de-en/tmp/IWSLT14.TED.tst2012.de-en.de
> Tokenizer Version 1.1
> Language: de
> Number of threads: 8
> Can't locate object method "new" via package "Thread" at mosesdecoder/scripts/tokenizer/tokenizer.perl line 163, <STDIN> line 1700.
> 
> orig/de-en/IWSLT14.TEDX.dev2012.de-en.de.xml iwslt14.tokenized.de-en/tmp/IWSLT14.TEDX.dev2012.de-en.de
> Tokenizer Version 1.1
> Language: de
> Number of threads: 8
> Can't locate object method "new" via package "Thread" at mosesdecoder/scripts/tokenizer/tokenizer.perl line 163, <STDIN> line 1165.
> 
> orig/de-en/IWSLT14.TED.dev2010.de-en.en.xml iwslt14.tokenized.de-en/tmp/IWSLT14.TED.dev2010.de-en.en
> Tokenizer Version 1.1
> Language: en
> Number of threads: 8
> Can't locate object method "new" via package "Thread" at mosesdecoder/scripts/tokenizer/tokenizer.perl line 163, <STDIN> line 887.
> 
> orig/de-en/IWSLT14.TED.tst2010.de-en.en.xml iwslt14.tokenized.de-en/tmp/IWSLT14.TED.tst2010.de-en.en
> Tokenizer Version 1.1
> Language: en
> Number of threads: 8
> Can't locate object method "new" via package "Thread" at mosesdecoder/scripts/tokenizer/tokenizer.perl line 163, <STDIN> line 1565.
> 
> orig/de-en/IWSLT14.TED.tst2011.de-en.en.xml iwslt14.tokenized.de-en/tmp/IWSLT14.TED.tst2011.de-en.en
> Tokenizer Version 1.1
> Language: en
> Number of threads: 8
> Can't locate object method "new" via package "Thread" at mosesdecoder/scripts/tokenizer/tokenizer.perl line 163, <STDIN> line 1433.
> 
> orig/de-en/IWSLT14.TED.tst2012.de-en.en.xml iwslt14.tokenized.de-en/tmp/IWSLT14.TED.tst2012.de-en.en
> Tokenizer Version 1.1
> Language: en
> Number of threads: 8
> Can't locate object method "new" via package "Thread" at mosesdecoder/scripts/tokenizer/tokenizer.perl line 163, <STDIN> line 1700.
> 
> orig/de-en/IWSLT14.TEDX.dev2012.de-en.en.xml iwslt14.tokenized.de-en/tmp/IWSLT14.TEDX.dev2012.de-en.en
> Tokenizer Version 1.1
> Language: en
> Number of threads: 8
> Can't locate object method "new" via package "Thread" at mosesdecoder/scripts/tokenizer/tokenizer.perl line 163, <STDIN> line 1165.
> 
> creating train, valid, test...
> learn_bpe.py on iwslt14.tokenized.de-en/tmp/train.en-de...
> Traceback (most recent call last):
>   File "subword-nmt/subword_nmt/learn_bpe.py", line 361, in <module>
>     learn_bpe(args.input, args.output, args.symbols, args.min_frequency, args.verbose, is_dict=args.dict_input, total_symbols=args.total_symbols, num_workers=args.num_workers)
>   File "subword-nmt/subword_nmt/learn_bpe.py", line 296, in learn_bpe
>     threshold = max(stats.values()) / 10
> ValueError: max() arg is an empty sequence
> apply_bpe.py to train.de...
> Error: invalid line 2 in BPE codes file: 
> The line should exist of exactly two subword units, separated by whitespace
> apply_bpe.py to valid.de...
> Error: invalid line 2 in BPE codes file: 
> The line should exist of exactly two subword units, separated by whitespace
> apply_bpe.py to test.de...
> Error: invalid line 2 in BPE codes file: 
> The line should exist of exactly two subword units, separated by whitespace
> apply_bpe.py to train.en...
> Error: invalid line 2 in BPE codes file: 
> The line should exist of exactly two subword units, separated by whitespace
> apply_bpe.py to valid.en...
> Error: invalid line 2 in BPE codes file: 
> The line should exist of exactly two subword units, separated by whitespace
> apply_bpe.py to test.en...
> Error: invalid line 2 in BPE codes file: 
> The line should exist of exactly two subword units, separated by whitespace

#### What have you tried?

I only followed the installation guidelines from [here](https://github.com/pytorch/fairseq) and then bash prepare-iwslt14.sh from [here](https://github.com/pytorch/fairseq/tree/master/examples/translation#training-a-new-model). Can anyone help with this issue?

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): pip install --editable ./
 - Python version: 3.7.4
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by targetsm** [comment]
Removing the `-threads 8` arguments to the perl commands in `prepare-iwslt14.sh` file worked for me. Seems to be something with perl multithreading...
