### ISSUE TITLE
Failed to  reproduce the results of S2T Example on LibriSpeech

### ISSUE THREAD

**Issue by Jian-Xi** [pytorch/fairseq#3459]
## ❓ Questions and Help
Recently I'm trying to reproduce the results of S2T Example on LibriSpeech dataset. I used the provided scripts without any further change. It turns out that the sentence piece model plays a critical role in inference. 
I'm wondering how the provided **librispeech_vocab_unigram10000** model is trained since I got a different vocabulary and model for spm.  After merging there are 16 differences as shown as follow
`
local vocab size:9996	 pre vocab size:9996

Difference between local and pre vocab:16
 {'▁marr', '▁impregn', '▁relent', '▁venom', 'ral', 'ano', 'arried', '▁abus', '▁indispos', '▁married', 'ax', 'married', '▁deviat', '▁unp', 'dom', '▁picca'}
`
I also made a small experiment. spm means the spm model and the vocabulary. Here are the WER (beam=5) results (test-clear,  test-other, dev-other, dev-clean, respectively):
- transformer_s + spm (self trained  both): 40.12, 46.36, 47.17, 38.88
- transformer_s (pre-trained) + spm (self trained): 37.45, 38.44, 37.95, 36,73
- transformer_s (self trained) + spm (pre-trained): 28.87, 36.97, 37.42, 27.32
- transformer_s (pre-trained) + spm (pre-trained): 4.92, 9.10, 9.13, 3.7 

#### What is your question?

- How did you train the sentence piece model? What hyperparameter I should set if I reproduce the results as you show?
- How to train the model in order to get the results on LibriSpeech dataset?

#### What have you tried?
I also tried to set parameters of spm model and which does not help.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed fairseq (`pip`, source): clone repository and `pip install --editable ./`
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: GeForce RTX 2080 Ti
 - Any other relevant information: No

Thanks for any input in advance.
Cheers

**Comment by Jian-Xi** [comment]
I figure it out that the problem depends on the (implementation of ) spm model in python version.
I used the C++ code at [https://github.com/google/sentencepiece](sentencepiece). After comparing the outcomes of C++ version with the one provided,  there is only one different token that occurs only in the vocabulary got from C++ version.

The parameter of spm models are as follows:
`spm_train --input=train_tgt.txt --model_prefix=spm_librispeech_cc1  --vocab_size=10000 --character_coverage=1
`
where train_tgt.txt the ground truth text for LibriSpeech. 

The comparison resutls: 
`
local vocab_py size:9996	local vocab_cpp size:9997	 pre vocab size:9996
`

`
Difference between local_cpp and pre vocab:1
	 {'▁appertain'}`

`
Difference between local_py and pre vocab:16
	 {'▁venom', '▁marr', 'dom', 'ano', 'ax', '▁indispos', '▁relent', '▁deviat', '▁impregn', '▁picca', 'married', 'ral', 'arried', '▁unp', '▁married', '▁abus'}
`

**Comment by suyuzhang** [comment]
Hi @Jian-Xi,
Have you solved the problem? I also meet the same issue as you.

**Comment by Jian-Xi** [comment]
@suyuzhang I guess you need to train the spm model with cpp version as shown above. After it,  you need to write a script to extract the tokens from the vocabulary that is created by cpp version.  The extracted tokens are then used as your vocabulary that is used to train ASR model. If you do it so, you'll see the improvement of your ASR results.

Hope it helps you somehow..
