### ISSUE TITLE
Wrong Final Dimension size for wav2vec2 large tpu config

### ISSUE THREAD

**Issue by harveenchadha** [pytorch/fairseq#3466]
Hi,

I was trying to run wav2vec2 on TPU when I found a strange thing:

<img width="280" alt="Screenshot 2021-04-12 at 3 41 35 PM" src="https://user-images.githubusercontent.com/30959215/114378671-92383b80-9ba5-11eb-80d1-711b322d466a.png">

In the config file [here](https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/config/pretraining/wav2vec2_large_librivox_tpu-pod.yaml) The final dimension layer is of size 256 which is not the case with wav2vec2_large.

There can be two potential issues:

1. Either the name of the config is wrong i.e. wav2vec2_large_librivox_tpu-pod should be wav2vec2_base_librivox_tpu-pod

2. Or the the final dimension layer should be of size 768

Through my inspection I think it should be case 1.

**Comment by harveenchadha** [comment]
@alexeib Can you please confirm on this?

**Comment by alexeib** [comment]
yeah those dimensions are for the base model. please just copy the "model" part of the config from the librivox and i'll update the tpu configs when i get a chance

**Comment by harveenchadha** [comment]
Thanks Alexi.

This is fixed [here](https://github.com/pytorch/fairseq/commit/a4e1d4a3daf4f6f5557505026fd94b8716fba7b3)
