### ISSUE TITLE
M2M-100 12B model,I use 4 GPUs with the same efficiency as 8 GPUs.why?The result is (0.40 sentences/s, 11.68 tokens/s).The GPU is  Tesla T4

### ISSUE THREAD

**Issue by im-yangp** [pytorch/fairseq#3478]
12b_last_chk_4_gpus  config
fairseq-generate \
    data_bin \
    --batch-size 8 \
    --path ../../12b_last_chk_4_gpus/12b_last_chk_4_gpus.pt \
    --fixed-dictionary model_dict.128k.txt \
    -s de -t zh \
    --remove-bpe 'sentencepiece' \
    --beam 5 \
    --task translation_multi_simple_epoch \
    --lang-pairs language_pairs.txt \
    --decoder-langtok --encoder-langtok src \
    --gen-subset test \
    --fp16 \
    --dataset-impl mmap \
    --distributed-world-size 1 --distributed-no-spawn \
    --pipeline-model-parallel \
    --pipeline-chunks 2 \
    --pipeline-encoder-balance '[1,15,10]' \
    --pipeline-encoder-devices '[0,1,0]' \
    --pipeline-decoder-balance '[3,11,11,1]' \
    --pipeline-decoder-devices '[0,2,3,0]' 

######################################

12b_last_chk_8_gpus config
fairseq-generate \
    data_bin \
    --batch-size 32 \
    --path ../../12b_last_chk_8_gpus/12b_last_chk_8_gpus.pt \
    --fixed-dictionary model_dict.128k.txt \
    -s de -t zh \
    --remove-bpe 'sentencepiece' \
    --beam 5 \
    --task translation_multi_simple_epoch \
    --lang-pairs language_pairs.txt \
    --decoder-langtok --encoder-langtok src \
    --gen-subset test \
    --fp16 \
    --dataset-impl mmap \
    --distributed-world-size 1 --distributed-no-spawn \
    --pipeline-model-parallel \
    --pipeline-chunks 2 \
    --pipeline-encoder-balance '[1,6,6,6,7]' \
    --pipeline-encoder-devices '[0,4,5,1,0]' \
    --pipeline-decoder-balance '[1,6,6,6,6,1]' \
    --pipeline-decoder-devices '[0,2,6,7,3,0]'

**Comment by leonodelee** [comment]
请问你复现m2m出现这个问题了没？

**Comment by leonodelee** [comment]
I want to implement example/M2M  but got a error while loading model(s) from 12b_last_chk_2_gpus.pt:
ERROR | fairseq.dataclass.utils | Error when composing. Overrides:[…]
…
omegaconf.errors.ValidationError: Invalid value 'simple', expected one of [c10d, fully_sharded, legacy_ddp, no_c10d, pytorch_ddp,_mo]
	full_key: distributed_training.ddp_backend
	reference_type=DistributedTrainingConfig
object_type=DistributedTrainingConfig

**Comment by im-yangp** [comment]
@leonodelee 你检查一下参数配置 ，应该是参数配错了，按官方文档的配置是运行成功的，如果你用12b_last_chk_2_gpus，必须有两块32G内存以上的GPU

**Comment by Hanlard** [comment]
> @leonodelee 你检查一下参数配置 ，应该是参数配错了，按官方文档的配置是运行成功的，如果你用12b_last_chk_2_gpus，必须有两块32G内存以上的GPU

就是那个官方文档的配置，一样会有他说的这个报错
