### ISSUE TITLE
interactive.py runtime error

### ISSUE THREAD

**Issue by r-cui** [pytorch/fairseq#348]
Hi

When I run interactive.py to test my trained translation model. I can run normally into the sentence input step but after typing the raw text ("is that alright" in this case) I got runtime error complaining a tensor type mismatch.

```
| [s] dictionary: 18816 types
| [t] dictionary: 19368 types
| loading model(s) from /data/xu043/ran_play/experiment/fair_ppdb/checkpoints/fconv/checkpoint_best.pt
| Type the input sentence and press return:
is that alright
Traceback (most recent call last):
  File "interactive.py", line 184, in <module>
    main(args)
  File "interactive.py", line 169, in main
    results += process_batch(batch)
  File "interactive.py", line 151, in process_batch
    maxlen=int(args.max_len_a * tokens.size(1) + args.max_len_b),
  File "/home/xu043/ran_play/fairseq-master/fairseq/sequence_generator.py", line 117, in generate
    return self._generate(encoder_input, beam_size, maxlen, prefix_tokens)
  File "/home/xu043/ran_play/fairseq-master/fairseq/sequence_generator.py", line 143, in _generate
    encoder_out = model.encoder.reorder_encoder_out(encoder_out, new_order)
  File "/home/xu043/ran_play/fairseq-master/fairseq/models/fconv.py", line 321, in reorder_encoder_out
    encoder_out['encoder_out'][0].index_select(0, new_order),
RuntimeError: Expected object of type torch.cuda.LongTensor but found type torch.cuda.FloatTensor for argument #3 'index'
```
My environment is Ubuntu18.04 with pytorch/0.4.0-py36-cuda91 and python3.6.1.
My running command is 
```
python3 interactive.py --path MODEL_DIR BIN_DATA_DIR --beam 5
```

**Comment by myleott** [comment]
Hmm, I'm not able to reproduce this using the fconv models we've released. Did you make any changes to the code? Does standard generate.py work for your model?

**Comment by harmanpreet93** [comment]
Hi @r-cui , I encountered a similar issue. Did you resolve it??

**Comment by r-cui** [comment]
@myleott No I did not modify any part, I just trained on my own data with commands highly similar to "examples/translation". I have not fully installed the environment (which is necessary for running generate.py) so not sure if generate.py would work.

**Comment by r-cui** [comment]
@harmanpreet93 Not yet, maybe you could provide more details about your running? Since this problem seems not showing in the developer's environment.
