### ISSUE TITLE
Load Model once & generate

### ISSUE THREAD

**Issue by nikhiljaiswal** [pytorch/fairseq#3483]
Is there a way to load the trained model and use it for translation (interactive / generate).

    fairseq-interactive $FAIRSEQ_DICT --path $model \
     --input $INPUT --remove-bpe=sentencepiece --num-workers 8 --max-tokens 8000 | \
     grep "^H-" | cut -f3 > ${OUT}_dic_frame

So currently, we need to use the above commands to translate a given raw text. But this is slow since every time we need to translate, we need to load the model. How can we load the model only once and then use it for successive translations.

**Comment by lematt1991** [comment]
The input to these scripts can contain many sentences (one per line), so you can batch them together this way.  Another alternative is to load your model using [torch hub](https://github.com/pytorch/fairseq/tree/master/examples/translation#example-usage-torchhub), which you can then feed inputs to without re-loading the model

**Comment by HyejinWon** [comment]
@lematt1991 I run using `from_pretrained` function to load my custom model. But I got some error.
The error message is 
```
RuntimeError: Error(s) in loading state_dict for TransformerModel:
	Unexpected key(s) in state_dict:
```
So how to handle this error?

**Comment by lematt1991** [comment]
@HyejinWon, can you include the exact code that you ran?

**Comment by HyejinWon** [comment]
Note, I didn't run original Transformer model in Fairseq. 
I run `Transformer base model + some extra attention layer` model. This is my custom model. 
But,  When I run `from_pretrained` function I got some error, like that.
```
RuntimeError: Error(s) in loading state_dict for TransformerModel:
	Unexpected key(s) in state_dict: "decoder.extra_attention_layer.in_proj_weight", "decoder.extra_attention_layer.in_proj_bias", "decoder.extra_attention_layer.out_proj.weight", "decoder.extra_attention_layer.out_proj.bias" 
```

So, I try to run model like this [#2580](https://github.com/pytorch/fairseq/issues/2580#issuecomment-689145520) (also change Wav2vec to Transformer)
Unfortunately, I got some trouble define the `task`.
