### ISSUE TITLE
Fairseq Translation Error - Different results for Hub and non Hub

### ISSUE THREAD

**Issue by Oxi84** [pytorch/fairseq#3484]
Is there anything wrong that I do here, basically translation for apples is eggs, and this should not happen with a translator software. Translation for "Я люблю яблоки." should be "I love apples." and not "I love eggs".

    from fairseq.models.transformer import TransformerModel
    ru2en = TransformerModel.from_pretrained(
        '/root/models/ruen/wmt19.ru-en.ensemble/',
        #checkpoint_file='model1.pt:model2.pt:model3.pt:model4.pt',
        checkpoint_file='model1.pt',
        data_name_or_path='/root/models/ruen/wmt19.ru-en.ensemble/',
        bpe='fastbpe',
        bpe_codes='/root/models/ruen/wmt19.ru-en.ensemble/bpecodes'
        )
    print ("model_3 fairseq is loaded !!")
    
    #ru2en.half()
    ru2en.eval()
    ru2en.cuda()
    
    words = ["Я люблю яблоки."]
    translated_sentences = ru2en.translate(words)
    print("translated sentences en:",translated_sentences) 

and then I get:
    "translated sentences en: ,I like eggs"

If i use hub then i get different result:

    ru2en = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.ru-en.single_model', tokenizer='moses', bpe='fastbpe')
    words = ["я люблю яблоки .","я люблю яблоки ."]
    translated_sentences = ru2en.translate(words)
    print("translated_sentences", translated_sentences)

i GET:
translated_sentences ['I love apples.', 'I love apples.']

**Comment by thpun** [comment]
Are you getting translation result from 2 different models?
In `TransformerModel.from_pretrained`, you are reading a checkpoint from local path `/root/models/ruen/wmt19.ru-en.ensemble/`.
But in `torch.hub.load`, you are loading `transformer.wmt19.ru-en.single_model` from
https://github.com/pytorch/fairseq/blob/89371294e54ef8c306f19733f2e8bab8233c401e/fairseq/models/transformer.py#L97

**Comment by Oxi84** [comment]
Yes, but even if i load the model transformer.wmt19.ru-en.single_model via TransformerModel.from_pretrained it is the same.

It translates apples as eggs

**Comment by Oxi84** [comment]
from fairseq.models.transformer import TransformerModel
    ru2en = TransformerModel.from_pretrained(
        '/root/models/ruensin/wmt19.ru-en.single_model/',
        #checkpoint_file='model1.pt:model2.pt:model3.pt:model4.pt',
        checkpoint_file='model.pt',
        data_name_or_path='/root/models/ruensin/wmt19.ru-en.single_model/',
        bpe='fastbpe',
        bpe_codes='/root/models/ruensin/wmt19.ru-en.single_model/bpecodes'
        )

**Comment by zzaebok** [comment]
It has been a long time, but I faced the same issue and found the solution.

Add `tokenizer="moses"` to the arguments.
It prints `['I love apples.']` well.
