### ISSUE TITLE
How does BART's denoising infilling task work?  

### ISSUE THREAD

**Issue by thisiscam** [pytorch/fairseq#3486]
#### What is your question?

I wonder if someone can help me understand BART infilling algorithm?
In particular, I understand the rough scheme of sampling masks is the following:

- Sample N span lengths, where span's length is drawn from a Poisson distribution.
- Uniformly choose N indices as the starting position of the N spans.  
- Replace each span with a `<MASK>` token.

What I don't understand is how does the algorithm handle overlapping spans? Does it merge overlapping spans into a larger span? 

#### Code

I think the relevant code is https://github.com/pytorch/fairseq/blob/master/fairseq/data/denoising_dataset.py#L250
Unfortunately, this function is not easy to understand for me. 

#### What have you tried?

I debug stepped through the code above and my current best hypothesis is that the code does merge the spans. But I'm not certain.

#### What's your environment?

 NA

**Comment by thisiscam** [comment]
Bump

**Comment by fan-hd** [comment]
> ## ❓ Questions and Help
> #### What is your question?
> I wonder if someone can help me understand BART infilling algorithm?
> In particular, I understand the rough scheme of sampling masks is the following:
> 
> * Sample N span lengths, where span's length is drawn from a Poisson distribution.
> * Uniformly choose N indices as the starting position of the N spans.
> * Replace each span with a `<MASK>` token.
> 
> What I don't understand is how does the algorithm handle overlapping spans? Does it merge overlapping spans into a larger span?
> 
> #### Code
> I think the relevant code is https://github.com/pytorch/fairseq/blob/master/fairseq/data/denoising_dataset.py#L250
> Unfortunately, this function is not easy to understand for me.
> 
> #### What have you tried?
> I debug stepped through the code above and my current best hypothesis is that the code does merge the spans. But I'm not certain.
> 
> #### What's your environment?
> NA

Yes.
code here
https://github.com/pytorch/fairseq/blob/cb747010c47a017e71285556afa9acce0ec62786/fairseq/data/denoising_dataset.py#L312-L331
deletes the spans without checking overlapping spans.
