### ISSUE TITLE
Is wandb for fairseq-train supported?

### ISSUE THREAD

**Issue by cinjon** [pytorch/fairseq#3498]
## 📚 Documentation

The documentation (https://fairseq.readthedocs.io/en/latest/command_line_tools.html) suggests that it is, but running it with the flag `--wandb-project myrun` throws an error about unrecognized arguments. The command `fairseq-train -h | grep wandb` doesn't return anything either. I am using the pip install of fairseq, which is 0.10.2.

**Comment by cinjon** [comment]
Ok I see that the pip package hasn't been updated with the wandb changes. Is this going to happen soon?

**Comment by lematt1991** [comment]
CC @myleott for timeline of the next release.  In the meantime, you can install master using `pip install git+https://github.com/pytorch/fairseq.git`
