### ISSUE TITLE
Incorrect bpecodes file included with pre-trained WMT19 EN-RU translation model

### ISSUE THREAD

**Issue by demelin** [pytorch/fairseq#3510]
## 🐛 Bug

The `bpecodes` file included in the tar.gz archive of the pre-trained `transformer.wmt19.en-ru` model seems to be a copy of the one included with the `transformer.wmt19.en-de` model. As such, it segments Russian sentences incorrectly (usually close to producing character-level segmentations). The one provided with the `transformer.wmt19.ru-en` model, on the other hand, appears to be correct. Thanks for looking into this!

### To Reproduce

Not applicable.

#### Code sample

Not applicable.

### Environment

Not applicable.

### Additional context

None.

**Comment by lematt1991** [comment]
Does #2928 or [this](https://github.com/pytorch/fairseq/issues/2544#issuecomment-688054859) resolve your issue?

**Comment by demelin** [comment]
Yep, it does - thank you for pointing out the relevant issues :) .
