### ISSUE TITLE
The link of flores101_mm100_175M  in Flores101 is wrong

### ISSUE THREAD

**Issue by cocaer** [pytorch/fairseq#3517]
I tried to download the pretrain model flores101_mm100_175M but the the link is wrong.  Would you like to check this [link?](https://dl.fbaipublicfiles.com/flores101/pretrained_models/flores101_mm100_175M.tar.tgz)

**Comment by lematt1991** [comment]
Yep, I can confirm the link is broken.  Will have a fix for it soon.  Thanks for reporting!

**Comment by ngoyal2707** [comment]
Hey, sorry, there's a typo in that link, correct link is this: https://dl.fbaipublicfiles.com/flores101/pretrained_models/flores101_mm100_175M.tar.gz

I will correct the readme in the meantime

**Comment by kevin-haynie** [comment]
Does this link have the needed dictionaries?  I'm getting an error when trying to initialize the model saying 'no such file or directory: `/home/..../dict.af.txt`.  It appears that a large number of languages is loaded by default and the  infrastructure code is looking for all the language specific dictionaries.  The tar file only includes `dict.txt`.

Also, is there any sample code showing how to use Flores from Python?  

Thank you!
