### ISSUE TITLE
Paraphraser demo error

### ISSUE THREAD

**Issue by KyloRen1** [pytorch/fairseq#3521]
I tried to run Paraphrasing with round-trip translation and mixture of experts demo and I have found that there is an error in user_dir path. If I leave it blank, the path to `examples/translation_moe/src/` does not exist. And if I explicitly indicate the path to `examples/translation_moe/translation_moe_src/` it throws an error 

hydra.errors.ConfigCompositionException: Error merging override task.mean_pool_gating_network_dropout=null

How can I fix this? Thanks!

**Comment by cronopioelectronico** [comment]
Hi @KyloRen1 this bug can be fixed with #3605

**Comment by KyloRen1** [comment]
@cronopioelectronico thanks!
