### ISSUE TITLE
Check probability for certain outputs

### ISSUE THREAD

**Issue by fferlito** [pytorch/fairseq#3525]
I need to test the probabilities that the model would produce certain outputs. Let me give you an example:
I have a source sentence X, and several possible target sentences Y1, Y2, Y3, Y4 , ... 

I want to know if I can compute the probability that the model would give to each of the translation Y, given X. 
Is there a function to compute these values?

**Comment by uralik** [comment]
is your data iterator augmented with the sequences Y1 Y2 etc? If yes, then you may extend e.g. the valid step function in your `--user-dir` fairseq module. Essentially the model outputs for given input are produced like this:
`target_net_output = model(**sample['net_input'])`

So you may substitute the target input part of the sample with whatever sequence you need and get desired scores:

```
beam_hyps_target = data_utils.collate_tokens(beam_hyps, pad_idx=self.tgt_dict.pad(), move_eos_to_beginning=False)
beam_hyps_input = data_utils.collate_tokens(beam_hyps, pad_idx=self.tgt_dict.pad(), move_eos_to_beginning=True)

generated_net_output = model(sample['net_input']['src_tokens'], sample['net_input']['src_lengths'], beam_hyps_input)
```

Then you gather specific target token scores (`beam_hyps_target `) from `generated_net_output`. This may be not the best way to do this though.
