### ISSUE TITLE
xlm-roberta vocabulary

### ISSUE THREAD

**Issue by Syavaprd** [pytorch/fairseq#3527]
Hello. I need to preprocess xlm-roberta vocabulary file. But how can I read it properly or remake .model into .txt? Help me please!

**Comment by lematt1991** [comment]
What have you tried so far?  Please follow the issue templates

**Comment by Syavaprd** [comment]
I mean where can I get vocab.txt for xlm-roberta. I only found the .model file.
I need to run fairseq-preprocess with it

> What have you tried so far? Please follow the issue templates
