### ISSUE TITLE
Getting error during Inference of wav2vec2.0 model

### ISSUE THREAD

**Issue by MrityunjoyS** [pytorch/fairseq#3528]
Hi, I've trained my own model, with my own dataset using wav2vec2.0 . After that I'm trying to do inference using below command -
`python3 examples/speech_recognition/infer.py /path_to_tsv/ --task audio_pretraining --nbest 1 --path /path/to/model/checkpoint_best.pt --gen-subset test --results-path /path/to/save/results/ --w2l-decoder viterbi --lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter`

But getting below error -

> INFO:__main__:| decoding with criterion ctc
> INFO:__main__:| loading model(s) from /root/model_and_dict/checkpoint_best.pt
> Traceback (most recent call last):
>   File "examples/speech_recognition/infer.py", line 427, in <module>
>     cli_main()
>   File "examples/speech_recognition/infer.py", line 423, in cli_main
>     main(args)
>   File "examples/speech_recognition/infer.py", line 239, in main
>     task.load_dataset(args.gen_subset, task_cfg=saved_cfg.task)
>   File "/root/fairseq/fairseq/tasks/audio_pretraining.py", line 202, in load_dataset
>     if task_cfg.binarized_dataset:
>   File "/usr/local/lib/python3.6/dist-packages/omegaconf/dictconfig.py", line 305, in __getattr__
>     self._format_and_raise(key=key, value=None, cause=e)
>   File "/usr/local/lib/python3.6/dist-packages/omegaconf/base.py", line 101, in _format_and_raise
>     type_override=type_override,
>   File "/usr/local/lib/python3.6/dist-packages/omegaconf/_utils.py", line 629, in format_and_raise
>     _raise(ex, cause)
>   File "/usr/local/lib/python3.6/dist-packages/omegaconf/_utils.py", line 610, in _raise
>     raise ex  # set end OC_CAUSE=1 for full backtrace
>   File "/usr/local/lib/python3.6/dist-packages/omegaconf/dictconfig.py", line 303, in __getattr__
>     return self._get_impl(key=key, default_value=DEFAULT_VALUE_MARKER)
>   File "/usr/local/lib/python3.6/dist-packages/omegaconf/dictconfig.py", line 361, in _get_impl
>     node = self._get_node(key=key)
>   File "/usr/local/lib/python3.6/dist-packages/omegaconf/dictconfig.py", line 383, in _get_node
>     self._validate_get(key)
>   File "/usr/local/lib/python3.6/dist-packages/omegaconf/dictconfig.py", line 136, in _validate_get
>     key=key, value=value, cause=ConfigAttributeError(msg)
>   File "/usr/local/lib/python3.6/dist-packages/omegaconf/base.py", line 101, in _format_and_raise
>     type_override=type_override,
>   File "/usr/local/lib/python3.6/dist-packages/omegaconf/_utils.py", line 694, in format_and_raise
>     _raise(ex, cause)
>   File "/usr/local/lib/python3.6/dist-packages/omegaconf/_utils.py", line 610, in _raise
>     raise ex  # set end OC_CAUSE=1 for full backtrace
> omegaconf.errors.ConfigAttributeError: Key 'binarized_dataset' is not in struct
> 	full_key: task.binarized_dataset
> 	reference_type=Any
> 	object_type=dict

Can you please have a look and if possible please point out what I might be doing wrong

**Comment by harveenchadha** [comment]
Hi,

Can you please try with this commit:

https://github.com/pytorch/fairseq/tree/1bba712622b8ae4efb3eb793a8a40da386fe11d0/examples/wav2vec

I think @alexeib is working on something for large datasets! The previous commit should work fine!

**Comment by alexeib** [comment]
thanks for reporting, will fix

**Comment by MrityunjoyS** [comment]
Yeah, thanks @harveenchadha @alexeib . Actually last commit that you mentioned worked fine.
