### ISSUE TITLE
Where can I find pretrained embeddings?

### ISSUE THREAD

**Issue by grypesc** [pytorch/fairseq#3534]
Hello, I see some of the models for mt task, such as fconv, can be supplied with pretrained embeddings given argument ```--encoder-embed-path``` or ```--decoder-embed-path```. Docs do not specify where pretrained embeddings files can be downloaded from. I am interested in embeddings for a iwslt14 with BPE for research purposes. Could you help me with it?

**Comment by zxk19981227** [comment]
This is easy for that if you could load a pretrained or simply create model with named_parameters function, you could change and get all parameters in the model
