### ISSUE TITLE
ModuleNotFoundError: No module named 'fairseq.hub_utils' when attempting to load MBART using torch.hub.load

### ISSUE THREAD

**Issue by vmaddur** [pytorch/fairseq#3537]
#### What is your question?
I am trying to load an example model found [here](https://github.com/pytorch/fairseq/tree/master/examples/mbart), but the below code snippet terminates with ModuleNotFoundError: No module named 'fairseq.hub_utils'. 

#### Code

```
import torch
import fairseq
model = torch.hub.load("pytorch/fairseq", "mbart", force_reload=True)
print(torch)
```

#### What's your environment?

 - fairseq Version: 1.0.0a0+6d0eb1c /content/fairseq
 - PyTorch Version: 1.8.1+cu101  
 - Google Colab

**Comment by vkhangpham** [comment]
bump
