### ISSUE TITLE
MMA code with latency_augmented_label_smoothed_cross_entropy does NOT work

### ISSUE THREAD

**Issue by Onoratofra** [pytorch/fairseq#3546]
Hi! I am trying to train a model with MMA policy following the instruction in the tutorial 
https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/simulst_mustc_example.md
I have updated the code as there have been several commits on MMA but it still does not work. This is the log of the error:

2021-05-12 16:15:03 | INFO | fairseq.trainer | begin training epoch 1
2021-05-12 16:15:03 | INFO | fairseq_cli.train | Start iterating over samples
/home/fonorato/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py:474: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File "/home/fonorato/anaconda3/envs/myenv/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/fonorato/fairseqSLT/fairseq_mio/fairseq_cli/train.py", line 500, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/fonorato/fairseqSLT/fairseq_mio/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/home/fonorato/fairseqSLT/fairseq_mio/fairseq_cli/train.py", line 177, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/fonorato/anaconda3/envs/myenv/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/fonorato/fairseqSLT/fairseq_mio/fairseq_cli/train.py", line 288, in train
    log_output = trainer.train_step(samples)
  File "/home/fonorato/anaconda3/envs/myenv/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/fonorato/fairseqSLT/fairseq_mio/fairseq/trainer.py", line 669, in train_step
    loss, sample_size_i, logging_output = self.task.train_step(
  File "/home/fonorato/fairseqSLT/fairseq_mio/fairseq/tasks/fairseq_task.py", line 475, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/fonorato/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fonorato/fairseqSLT/fairseq_mio/fairseq/criterions/label_smoothed_cross_entropy.py", line 80, in forward
    loss, nll_loss = self.compute_loss(model, net_output, sample, reduce=reduce)
  File "/home/fonorato/fairseqSLT/fairseq_mio/fairseq/criterions/label_smoothed_cross_entropy_latency_augmented.py", line 95, in compute_loss
    attn_list = [item["alpha"] for item in net_output[-1]["attn_list"]]
TypeError: tuple indices must be integers or slices, not str

Can you help?
Thanks in advance

**Comment by dannigt** [comment]
Hi, I ran into the same error and was able to resolve it by reverting to commit `252d5a9ae93e68254cfb1896fb5624cf11cda15e`. (I'm not sure when exactly this starts to give this error, just picked an early enough commit)

**Comment by DanchuKim** [comment]
Hi, I got same issue, and resolve it.

move into "fairseq\fairseq\criterions\label_smoothed_cross_entropy_latency_augmented.py"

and do like this:

`` attn_list = [item["alpha"] for item in net_output[-1]["attn_list"]] ``-> `` attn_list = [item["alpha"] for item in net_output[-1]._asdict()["attn_list"]`` 

``source_padding_mask = net_output[-1].get("encoder_padding_mask", None) `` -> ``source_padding_mask = net_output[-1]._asdict()["encoder_padding_mask"]``

I'm not sure it is correct answer; but it is is work.

**Comment by DanchooKim** [comment]
> Hi, I got same issue, and resolve it.
> 
> move into "fairseq\fairseq\criterions\label_smoothed_cross_entropy_latency_augmented.py"
> 
> and do like this:
> 
> `attn_list = [item["alpha"] for item in net_output[-1]["attn_list"]]`-> ` attn_list = [item["alpha"] for item in net_output[-1]._asdict()["attn_list"]`
> 
> `source_padding_mask = net_output[-1].get("encoder_padding_mask", None) ` -> `source_padding_mask = net_output[-1]._asdict()["encoder_padding_mask"]`
> 
> I'm not sure it is correct answer; but it is work.

**Comment by MingyangHeseri** [comment]
Same problem..Anyone solved it sucucessfully?

**Comment by MingyangHeseri** [comment]
> Hi, I got same issue, and resolve it.
> 
> move into "fairseq\fairseq\criterions\label_smoothed_cross_entropy_latency_augmented.py"
> 
> and do like this:
> 
> `attn_list = [item["alpha"] for item in net_output[-1]["attn_list"]]`-> ` attn_list = [item["alpha"] for item in net_output[-1]._asdict()["attn_list"]`


Hi, Thanks for sharing your method, it worked, but I met another problem after changing the code, which is " Only right padding is allowed",did you met the same problem?,Thanks in advance

**Comment by kurtisxx** [comment]
Hey @kahne, @xutaima ! I was wondering if there is any progress on this issue? Is the official code still broken, or can we use it?

**Comment by xutaima** [comment]
Hi, https://github.com/pytorch/fairseq/commit/98d638c70cdbe751153c10fc571c34beac228347 is a fix for this issue. Feel free to let me know if there is any more questions.

**Comment by kurtisxx** [comment]
Thanks @xutaima ! Greatly appreciated! Will you also be able to look at #[3414](https://github.com/pytorch/fairseq/issues/3414) soon? It also blocks people to use the code and replicate the results :)
