### ISSUE TITLE
Which pre-training corpus is used for BART-base?

### ISSUE THREAD

**Issue by rakeshchada** [pytorch/fairseq#3550]
#### What is your question?

Hi ,
On what corpus is the [publicly available BART-base](https://huggingface.co/facebook/bart-base) pre-trained on? 
It was not explicitly mentioned in the [BART paper](https://www.aclweb.org/anthology/2020.acl-main.703/) but the phrase below from the paper suggests to me that the pre-training corpus used for BART-base is the same as the one used for pre-training BERT-base (Wikipedia + BooksCorpus). Is that correct?

`"For reference, we compare our implementations with published numbers from BERT, which was also trained for 1M steps on a combination of books and Wikipedia data."`

Appreciate if you can clarify this. Tagging @sshleifer .

**Comment by sshleifer** [comment]
I think section 3.2 of the Roberta Paper has the pertinent info https://arxiv.org/pdf/1907.11692.pdf. 

I pasted below and did some markdown:

### 3.2 Data
BERT-style pretraining crucially relies on large
quantities of text. Baevski et al. (2019) demonstrate that increasing data size can result in improved end-task performance. Several efforts
have trained on datasets larger and more diverse
than the original BERT (Radford et al., 2019;
Yang et al., 2019; Zellers et al., 2019). Unfortunately, not all of the additional datasets can be
publicly released. For our study, we focus on gathering as much data as possible for experimentation, allowing us to match the overall quality and
quantity of data as appropriate for each comparison.
We consider five English-language corpora of
varying sizes and domains, totaling over 160GB
of uncompressed text. We use the following text
corpora:
- BOOKCORPUS (Zhu et al., 2015) plus English
WIKIPEDIA. This is the original data used to
train BERT. (16GB).
- CC-NEWS, which we collected from the English portion of the CommonCrawl News
dataset (Nagel, 2016). The data contains 63
million English news articles crawled between
September 2016 and February 2019. (76GB after filtering). (footnote: We use news-please (Hamborg et al., 2017) to collect and extract CC-NEWS. CC-NEWS is similar to the REALNEWS dataset described in Zellers et al. (2019).
- OPENWEBTEXT (Gokaslan and Cohen, 2019),
an open-source recreation of the WebText corpus described in Radford et al. (2019). The text
is web content extracted from URLs shared on
Reddit with at least three upvotes. (38GB).5
- STORIES, a dataset introduced in Trinh and Le
(2018) containing a subset of CommonCrawl
data filtered to match the story-like style of
Winograd schemas. (31GB).

**Comment by rakeshchada** [comment]
Hi @sshleifer, Thanks for sharing. However, I think the info you've provided is for the RoBERTa model. My question is about the corpus used to pre-train "bart.base" model that is publicly released [here](https://github.com/pytorch/fairseq/tree/master/examples/bart).

**Comment by sshleifer** [comment]
bart-base was also trained on this dataset.
