### ISSUE TITLE
Current commit leads to StringScalar error with wav2vec_manifest.py generated tsvs

### ISSUE THREAD

**Issue by olafthiele** [pytorch/fairseq#3558]
Current master shows following error for hydra train with @kahne's commit 8f1a34af7cb6e92fa3c443e61803e0ff347a784e 

> Traceback (most recent call last):
>   File "/home/ubuntu/wav2vec/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
>     distributed_utils.call_main(cfg, pre_main)
>   File "/home/ubuntu/wav2vec/fairseq/fairseq/distributed/utils.py", line 369, in call_main
>     main(cfg, **kwargs)
>   File "/home/ubuntu/wav2vec/fairseq/fairseq_cli/train.py", line 157, in main
>     disable_iterator_cache=task.has_sharded_data("train"),
>   File "/home/ubuntu/wav2vec/fairseq/fairseq/checkpoint_utils.py", line 238, in load_checkpoint
>     epoch=1, load_dataset=True, **passthrough_args
>   File "/home/ubuntu/wav2vec/fairseq/fairseq/trainer.py", line 578, in get_train_iterator
>     self.reset_dummy_batch(batch_iterator.first_batch)
>   File "/home/ubuntu/wav2vec/fairseq/fairseq/data/iterators.py", line 321, in first_batch
>     return self.collate_fn([self.dataset[i] for i in self.frozen_batches[0]])
>   File "/home/ubuntu/wav2vec/fairseq/fairseq/data/iterators.py", line 321, in <listcomp>
>     return self.collate_fn([self.dataset[i] for i in self.frozen_batches[0]])
>   File "/home/ubuntu/wav2vec/fairseq/fairseq/data/audio/raw_audio_dataset.py", line 302, in __getitem__
>     path_or_fp = os.path.join(self.root_dir, self.fnames[index])
>   File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/posixpath.py", line 94, in join
>     genericpath._check_arg_types('join', a, *p)
>   File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/genericpath.py", line 153, in _check_arg_types
>     (funcname, s.__class__.__name__)) from None
> TypeError: join() argument must be str or bytes, not 'StringScalar'

My guess is it's leaving out the string conversion in the latest raw_audio_dataset.py:

Old:

> fname = os.path.join(self.root_dir, str(self.fnames[index]))

New:

> path_or_fp = os.path.join(self.root_dir, self.fnames[index])

**Comment by kahne** [comment]
@olafthiele Thanks for reporting the issue! We are merging a fix from #3561 .

**Comment by kahne** [comment]
Merged
