### ISSUE TITLE
Add Catalan language to XLSR-53

### ISSUE THREAD

**Issue by jmontane** [pytorch/fairseq#3562]
## 🚀 Feature Request
Add Catalan language to XLSR-53, currently is missing

### Motivation
Catalan language is 4th language on Common Voice by number of recorded hours, but it is not in XLSR-53 (!?)

### Pitch

Pre-train a wav2vec 2.0 model for Catalan language adding support.

**Comment by olafthiele** [comment]
I don't know whether they'll train another XLSR, but have you trieed the [huggingface finetuned](https://huggingface.co/PereLluis13/Wav2Vec2-Large-XLSR-53-catalan) model?
