### ISSUE TITLE
'Wav2VecModel' object has no attribute 'cfg'

### ISSUE THREAD

**Issue by leo19941227** [pytorch/fairseq#3574]
## 🐛 Bug

When loading wav2vec and vq-wav2vec checkpoint with `fairseq.checkpoint_utils.load_model_ensemble_and_task`, the first line will result in error since there is no `cfg` attribute. Perhaps it is a typo of `actualized_cfg = getattr(model, "cfg", None)`? After adding the default None value, both wav2vec and vq-wav2vec can correctly load the checkpoint.

https://github.com/pytorch/fairseq/blob/c8223e350cfc616bb47196151d1223683e483b6d/fairseq/tasks/audio_pretraining.py#L306-L309

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

```bash
# 1. Download wav2vec checkpoint
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_large.pt

# 2. Run the following code sample (the same as the one in examples/wav2vec/README.md)
python3 load.py

# 3. See error
Traceback (most recent call last):
  File "load.py", line 5, in <module>
    model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])
  File "/home/leo/d/Benchmarking/fairseq/fairseq/checkpoint_utils.py", line 446, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/home/leo/d/Benchmarking/fairseq/fairseq/tasks/audio_pretraining.py", line 306, in build_model
    actualized_cfg = getattr(model, "cfg")
  File "/home/leo/miniconda3/envs/benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Wav2VecModel' object has no attribute 'cfg'
```

#### Code sample
```python
# load.py

import torch
import fairseq

cp_path = '/path/to/wav2vec.pt'
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])
model = model[0]
model.eval()

wav_input_16khz = torch.randn(1,10000)
z = model.feature_extractor(wav_input_16khz)
c = model.feature_aggregator(z)
```

### Expected behavior

Successfully load the checkpoint.

### Environment

 - fairseq Version: master at c8223e350cfc616bb47196151d1223683e483b6d
 - PyTorch Version: 1.7.0
 - OS: Linux
 - How you installed fairseq: `pip install -e ./`
 - Python version: 3.8.5
 - CUDA/cuDNN version: 10.2

**Comment by pyyush** [comment]
`from fairseq.models.wav2vec import Wav2Vec2Model`
`xlsr = Wav2Vec2Model.from_pretrained('.', checkpoint_file='xlsr_53_56k.pt')`
`xlsr.cfg`
{'common': {'_name': None, 'no_progress_bar': False, 'log_interval': 500, 'log_format': 'json', 'tensorboard_logdir': None, ...

**Comment by alexeib** [comment]
good point, this works for new models, but breaks for older pre-hydra models. will fix this soon

**Comment by ahmedimaddd** [comment]
> good point, this works for new models, but breaks for older pre-hydra models. will fix this soon

I face this issue with S2UT model (payload['cfg'] has no 'model' attribute or it is None.)
