### ISSUE TITLE
What is the expected  unsupervised Wav2vec2 data set format?

### ISSUE THREAD

**Issue by Enescigdem** [pytorch/fairseq#3586]
How can i prepare a data set for my own language ? Which files are necessary and how can i create them in expected way ?Is there any example for any language ?

**Comment by olafthiele** [comment]
There is a nice script to prepare LibriSpeech in general on the main wav2vec example site and see [here ](4906387589365806) for details on wav2vecU.

**Comment by Enescigdem** [comment]
> There is a nice script to prepare LibriSpeech in general on the main wav2vec example site and see [here ](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec/unsupervised#preparation-of-speech-and-text-data) for details on wav2vecU.

Yes,i do know this script.After applying vad, manifest.py gave me empty .ltr and .wrd files.Also it did not give .phn file but prepare_audio.sh script wants these files.

**Comment by olafthiele** [comment]
Please describe in more detail what you have done and where it fails. You didn't give that information in the beginning ... it is all quite new and there is no detailed descripton on how to do stuff yet :-)

**Comment by Enescigdem** [comment]
I applied succesfully vad by rVADfast and removed silences.
Then python $FAIRSEQ_ROOT/examples/wav2vec/wav2vec_manifest.py /dir/to/save/audio/files --ext wav --dest /path/to/new/train.tsv --valid-percent 0 this script  (of course paths are different)
This script gave train.tsv file and empty .ltr and .wrd files for train files.
Although it is, i tried to apply prepare_audio.sh script but it wanted .ltr .wrd and .phn files.
So, am i supposed to prepare these files at first, if so how?

**Comment by olafthiele** [comment]
Sorry, you still don't provide much information. My best guess is that you have flac data and you provide the wav flag to the script. And what language, what type of material ...

**Comment by jimregan** [comment]
You have to prepare the `ltr`, `wrd` and `phn` files yourself. `wrd` is just cleaned words - case normalised, punctuation removed, etc. I prepared `.ltr` files like this:
```
for i in ['train', 'test', 'valid']:
    with open(f'{i}.wrd', 'r') as inf, open(f'{i}.ltr', 'w') as out:
        for line in inf.readlines():
            print(" ".join(list(line.strip().replace(" ", "|"))) + " |", file=out)
```
and used espeak for the `.phn` files - see the prepare-text script.

The .tsv for the audio is:
```
path/to/files/
file1.flac	[number of frames]
```
the files can be in any format that soundfile can open, but they have to be sampled at 16k

**Comment by Enescigdem** [comment]
@jimregan  You are the best.Thanks in advance

**Comment by jimregan** [comment]
Oh, also, you can fake the number of frames, because it's ignored, but if you really want it I can give you a snippet for that too

**Comment by Enescigdem** [comment]
> Oh, also, you can fake the number of frames, because it's ignored, but if you really want it I can give you a snippet for that too

No,thank you I have the tsv file whose format is soundfile and frame.Also I have little question about wrd file.What words should be in the wrd file ? Transcriptions or LM text corpus?
Besides,
For text_prapare.sh it wants lm.upper.lid.txt, and i do not know the content of this file.

@jimregan

**Comment by Khanifsaleh** [comment]
Hi, 
how about dict* ?
When I was running ```zsh prepare_audio.sh```, it gave me a notice ```prepare_audio.sh:30: no matches found: {path}/dict*```

**Comment by jimregan** [comment]
`prepare_audio.sh` just copies those files if they exist, it doesn't use them.

I haven't got to a point yet where they are used, but I'm assuming they're for Kaldi, so the format is
```
word W ER D
```
i.e., 
```
<word> <space> <space separated list of phonemes>
```

**Comment by Enescigdem** [comment]
In prepare_text.sh, normalize_and_filter_text.py gave an error about loading Fasttext model.
==>ValueError: lid.187.bin cannot be opened for loading! what can i do for this error ? 
Also, can we use another phonetizer for phonemizing texts ? 
@jimregan

**Comment by dairm** [comment]
You can download model from this link https://fasttext.cc/docs/en/language-identification.html and run script normalize_and_filter_text.py with parametr --fast-text lid.176.bin

**Comment by jimregan** [comment]
> Also, can we use another phonetizer for phonemizing texts ?

I don't see why not. There's code for using another one in the scripts directory. As long as the output is in the same format, it shouldn't make a difference - I'm planning to use one based on (epitran)[https://github.com/dmort27/epitran] if/when I get the whole way through this test run!

**Comment by JeromeNi** [comment]
> Also, can we use another phonetizer for phonemizing texts ?

I think in the paper they use https://github.com/Kyubyong/g2p for phonemizing LibriSpeech and the default option in `prepare_text.sh` for other languages (Section 5.2). They also removed the numerical stress from the output of `g2p_en`.

**Comment by Enescigdem** [comment]
Hello,
I have another problem with prepare_text.sh, words.txt is not created although I have dict.txt.

**Comment by Khanifsaleh** [comment]
So, is there any end to end tutorial which cleary explained to train wav2vec-U?

**Comment by imtiaz3990** [comment]
> You have to prepare the `ltr`, `wrd` and `phn` files yourself. `wrd` is just cleaned words - case normalised, punctuation removed, etc. I prepared `.ltr` files like this:
> 
> ```
> for i in ['train', 'test', 'valid']:
>     with open(f'{i}.wrd', 'r') as inf, open(f'{i}.ltr', 'w') as out:
>         for line in inf.readlines():
>             print(" ".join(list(line.strip().replace(" ", "|"))) + " |", file=out)
> ```
> 
> and used espeak for the `.phn` files - see the prepare-text script.
> 
> The .tsv for the audio is:
> 
> ```
> path/to/files/
> file1.flac	[number of frames]
> ```
> 
> the files can be in any format that soundfile can open, but they have to be sampled at 16k


Hi confused here , but the whole point of wav2vec unsupervised is not having these labelled text right ? What am i missing please help

**Comment by imtiaz3990** [comment]
> So, is there any end to end tutorial which cleary explained to train wav2vec-U?

interested in knowing , please reference if you have found it.

**Comment by imtiaz3990** [comment]
Hi Team,

I am getting an error in the first step itself 

python scripts/vads.py <directory in which tsv file is present along with audio files > train.vads

for some reason it doesnot take the first row of data , please help 
![image](https://user-images.githubusercontent.com/77395708/120998247-87fd7c80-c7a5-11eb-8e32-a2d24bdf69ea.png)

please see my folder is like this 

raw_data/train/

1. train.csv
2. audio1.flac
3. audio2.flac and so on.

**Comment by Khanifsaleh** [comment]
> Hi Team,
> 
> I am getting an error in the first step itself
> 
> python scripts/vads.py train.vads
> 
> for some reason it doesnot take the first row of data , please help
> ![image](https://user-images.githubusercontent.com/77395708/120998247-87fd7c80-c7a5-11eb-8e32-a2d24bdf69ea.png)
> 
> please see my folder is like this
> 
> raw_data/train/
> 
>     1. train.csv
> 
>     2. audio1.flac
> 
>     3. audio2.flac and so on.

I think your ```fpath``` contain null string

**Comment by Enescigdem** [comment]
> > You have to prepare the `ltr`, `wrd` and `phn` files yourself. `wrd` is just cleaned words - case normalised, punctuation removed, etc. I prepared `.ltr` files like this:
> > ```
> > for i in ['train', 'test', 'valid']:
> >     with open(f'{i}.wrd', 'r') as inf, open(f'{i}.ltr', 'w') as out:
> >         for line in inf.readlines():
> >             print(" ".join(list(line.strip().replace(" ", "|"))) + " |", file=out)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and used espeak for the `.phn` files - see the prepare-text script.
> > The .tsv for the audio is:
> > ```
> > path/to/files/
> > file1.flac	[number of frames]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the files can be in any format that soundfile can open, but they have to be sampled at 16k
> 
> Hi confused here , but the whole point of wav2vec unsupervised is not having these labelled text right ? What am i missing please help
This files is not labelled.

**Comment by jimregan** [comment]
> So, is there any end to end tutorial which cleary explained to train wav2vec-U?

See here: https://github.com/pytorch/fairseq/issues/3591#issuecomment-854260221

**Comment by jimregan** [comment]
> Hi Team,
> 
> I am getting an error in the first step itself
> 
> python scripts/vads.py train.vads
> 
> for some reason it doesnot take the first row of data , please help
> ![image](https://user-images.githubusercontent.com/77395708/120998247-87fd7c80-c7a5-11eb-8e32-a2d24bdf69ea.png)
> 
> please see my folder is like this
> 
> raw_data/train/
> 
> 1. train.csv
> 2. audio1.flac
> 3. audio2.flac and so on.

Your _folder_? What does the tsv file contain? Also, you're showing a file called `train.csv` in the folder, but using `train.tsv` for the script. Is it just a typo?

**Comment by imtiazBDSgit** [comment]
> > Hi Team,
> > I am getting an error in the first step itself
> > python scripts/vads.py train.vads
> > for some reason it doesnot take the first row of data , please help
> > ![image](https://user-images.githubusercontent.com/77395708/120998247-87fd7c80-c7a5-11eb-8e32-a2d24bdf69ea.png)
> > please see my folder is like this
> > raw_data/train/
> > 
> > 1. train.csv
> > 2. audio1.flac
> > 3. audio2.flac and so on.
> 
> Your _folder_? What does the tsv file contain? Also, you're showing a file called `train.csv` in the folder, but using `train.tsv` for the script. Is it just a typo?

yes its just a typo , train.tsv file contains absolute paths to the audio files and corresponding transcription

**Comment by imtiazBDSgit** [comment]
> > Hi Team,
> > I am getting an error in the first step itself
> > python scripts/vads.py train.vads
> > for some reason it doesnot take the first row of data , please help
> > ![image](https://user-images.githubusercontent.com/77395708/120998247-87fd7c80-c7a5-11eb-8e32-a2d24bdf69ea.png)
> > please see my folder is like this
> > raw_data/train/
> > ```
> > 1. train.csv
> > 
> > 2. audio1.flac
> > 
> > 3. audio2.flac and so on.
> > ```
> 
> I think your `fpath` contain null string, so please check your train.csv file. Make sure your file no missing value.

I dont see any null string in the train.tsv file , still facing the same issue

**Comment by imtiazBDSgit** [comment]
How should the train.tsv appear ? can you please show me an example ?

**Comment by Khanifsaleh** [comment]
> How should the train.tsv appear ? can you please show me an example ?

You can make train.tsv with command ```$ python examples/wav2vec/wav2vec_manifest.py /path/to/waves --dest /manifest/path --ext $ext --valid-percent $valid``` [https://github.com/pytorch/fairseq/tree/master/examples/wav2vec](url)

**Comment by jimregan** [comment]
> yes its just a typo , train.tsv file contains absolute paths to the audio files and corresponding transcription

There's your error. The format is
```
/absolute/path/to/directory
file01.wav	[number of frames]
file02.wav	[number of frames]
```

i.e., no absolute file paths, no transcripts. In your case:
```
/absolute/path/to/raw_data/train
audio1.flac	[frames]
audio2.flac	[frames]
```
etc.

The problem you are seeing is in reading the `.tsv` file, not in reading any of the files it refers to.

**Comment by imtiazBDSgit** [comment]
> > > You have to prepare the `ltr`, `wrd` and `phn` files yourself. `wrd` is just cleaned words - case normalised, punctuation removed, etc. I prepared `.ltr` files like this:
> > > ```
> > > for i in ['train', 'test', 'valid']:
> > >     with open(f'{i}.wrd', 'r') as inf, open(f'{i}.ltr', 'w') as out:
> > >         for line in inf.readlines():
> > >             print(" ".join(list(line.strip().replace(" ", "|"))) + " |", file=out)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and used espeak for the `.phn` files - see the prepare-text script.
> > > The .tsv for the audio is:
> > > ```
> > > path/to/files/
> > > file1.flac	[number of frames]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > the files can be in any format that soundfile can open, but they have to be sampled at 16k
> > 
> > 
> > Hi confused here , but the whole point of wav2vec unsupervised is not having these labelled text right ? What am i missing please help
> > This files are not labelled.

Pardon my ignorance , still didnt understand , since we are using transcripts to create the .wrd file is my understanding correct ?

Also can you help on .wrd,.ltr and dict creation please ?

**Comment by imtiazBDSgit** [comment]
> > yes its just a typo , train.tsv file contains absolute paths to the audio files and corresponding transcription
> 
> There's your error. The format is
> 
> ```
> /absolute/path/to/directory
> file01.wav	[number of frames]
> file02.wav	[number of frames]
> ```
> 
> i.e., no absolute file paths, no transcripts. In your case:
> 
> ```
> /absolute/path/to/raw_data/train
> audio1.flac	[frames]
> audio2.flac	[frames]
> ```
> 
> etc.
> 
> The problem you are seeing is in reading the `.tsv` file, not in reading any of the files it refers to.

Got it thank you so much !

**Comment by imtiazBDSgit** [comment]
> > > > You have to prepare the `ltr`, `wrd` and `phn` files yourself. `wrd` is just cleaned words - case normalised, punctuation removed, etc. I prepared `.ltr` files like this:
> > > > ```
> > > > for i in ['train', 'test', 'valid']:
> > > >     with open(f'{i}.wrd', 'r') as inf, open(f'{i}.ltr', 'w') as out:
> > > >         for line in inf.readlines():
> > > >             print(" ".join(list(line.strip().replace(" ", "|"))) + " |", file=out)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > and used espeak for the `.phn` files - see the prepare-text script.
> > > > The .tsv for the audio is:
> > > > ```
> > > > path/to/files/
> > > > file1.flac	[number of frames]
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > the files can be in any format that soundfile can open, but they have to be sampled at 16k
> > > 
> > > 
> > > Hi confused here , but the whole point of wav2vec unsupervised is not having these labelled text right ? What am i missing please help
> > > This files are not labelled.
> 
> Pardon my ignorance , still didnt understand , since we are using transcripts to create the .wrd file is my understanding correct ?
> 
> Also can you help on .wrd,.ltr and dict creation please ?

Still figuring out this please help !

**Comment by jimregan** [comment]
> > > Hi confused here , but the whole point of wav2vec unsupervised is not having these labelled text right ? What am i missing please help
> > > This files are not labelled.
> > Pardon my ignorance , still didnt understand , since we are using transcripts to create the .wrd file is my understanding correct ?
> > Also can you help on .wrd,.ltr and dict creation please ?
> 
> Still figuring out this please help !

You seem to be new to the internet in general, so the first thing I'll say to you is: don't do this.

If your question is going unanswered, it could be for a number of reasons. It could be, for example, that a few other questions came in at about the same time, and it got lost. It could be an issue with your question. But a sure-fire way to guarantee your question goes unanswered is by following it up by saying something like "still waiting for an answer". So don't do that.

Maybe read something like [this](http://www.catb.org/~esr/faqs/smart-questions.html) and see if you can rephrase your question. You asked:

> the whole point of wav2vec unsupervised is not having these labelled text right ?

Now, see how adding one word can change the question:

> the whole point of wav2vec unsupervised is not having these labelled _training_ text right?

My answer: I'm not sure, as I haven't made it through the whole process yet, but from what I've seen so far, it isn't used, but the scripts expect the training files to exist, so I've added them anyway. You could try adding empty files and see what happens.

Going forward, if you find you have other difficulties, maybe take a look at #3581 and #3591 - maybe your next question has already been answered, or, if not, you'll at least have a more specific starting point if you do have another question.

HTH.

**Comment by imtiazBDSgit** [comment]
> > > > Hi confused here , but the whole point of wav2vec unsupervised is not having these labelled text right ? What am i missing please help
> > > > This files are not labelled.
> > > > Pardon my ignorance , still didnt understand , since we are using transcripts to create the .wrd file is my understanding correct ?
> > > > Also can you help on .wrd,.ltr and dict creation please ?
> > 
> > 
> > Still figuring out this please help !
> 
> You seem to be new to the internet in general, so the first thing I'll say to you is: don't do this.
> 
> If your question is going unanswered, it could be for a number of reasons. It could be, for example, that a few other questions came in at about the same time, and it got lost. It could be an issue with your question. But a sure-fire way to guarantee your question goes unanswered is by following it up by saying something like "still waiting for an answer". So don't do that.
> 
> Maybe read something like [this](http://www.catb.org/~esr/faqs/smart-questions.html) and see if you can rephrase your question. You asked:
> 
> > the whole point of wav2vec unsupervised is not having these labelled text right ?
> 
> Now, see how adding one word can change the question:
> 
> > the whole point of wav2vec unsupervised is not having these labelled _training_ text right?
> 
> My answer: I'm not sure, as I haven't made it through the whole process yet, but from what I've seen so far, it isn't used, but the scripts expect the training files to exist, so I've added them anyway. You could try adding empty files and see what happens.
> 
> Going forward, if you find you have other difficulties, maybe take a look at #3581 and #3591 - maybe your next question has already been answered, or, if not, you'll at least have a more specific starting point if you do have another question.
> 
> HTH.

Sincere Apologies, Thank you for the constructive feedback
