### ISSUE TITLE
Why is the library more command line oriented ?

### ISSUE THREAD

**Issue by maroxtn** [pytorch/fairseq#3590]
I am wondering what's the philosophy behind the way the library is developed, why is it more oriented for command line use rather than interactive python use (more like pytorch, imagine if pytorch was only command line).  
There isn't many examples on how to fine-tune / train using solely python without command line. Is it possible to do that using the Library, or does this need new modules ? Doing that would help in experimenting with models, and with new ideas.

Sorry for my newbie question, but that's all I could think of when I'm learning how to use fairseq!

**Comment by knetch** [comment]
Towards your second question, I've found this to be very helpful, even if you aren't using ray:
[Fault-Tolerant Fairseq Training](https://docs.ray.io/en/master/auto_examples/plot_example-lm.html#fault-tolerant-fairseq-training)

**Comment by gegallego** [comment]
Hi! I've been using Fairseq for a while, and I still feel the same way as you @maroxtn. It's an interesting discussion, I'll subscribe to receive notifications 👌
