### ISSUE TITLE
(wav2vec 2.0) Inquiry about wav2vec 2.0 decoding parameters

### ISSUE THREAD

**Issue by yuanfeng-yl** [pytorch/fairseq#3616]
I am trying to reproduce your fantastic work. And when I am trying to do the evaluation part, I notice that you only provide part of decoding parameters in the paper (wav2vec 2.0: A Framework for Self-Supervised Learning of Speech Representations). After some experiments, I think it is for base model, right? Could you please also provide the parameters which you use for Large model?

**Comment by alexeib** [comment]
to be honest it might be painful to dig it out from the notes. I think using params for the vox model should probably also work for the librispeech model (maybe not exactly same results but close enough) - or you can just run the ax tuning yourself, it takes about a day

**Comment by yuanfeng-yl** [comment]
I see, thanks for your kind reply. I will close this issue.
