### ISSUE TITLE
HuBERT - cannot load fine-tuned checkpoints

### ISSUE THREAD

**Issue by patrickvonplaten** [pytorch/fairseq#3620]
## 🐛 Bug

It is currently not possible to load the fine-tuned weights of Hubert.

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

```python
checkpoint_path="./hubert_large_ll60k_finetune_ls960.pt"
fairseq.checkpoint_utils.load_model_ensemble_and_task([checkpoint_path], strict=False)
```

Also, see this [colab](https://colab.research.google.com/drive/1qKIhqj8Fcdi5LuFNdNBlqMkBYKlnNNXq?usp=sharing) for reproducibility.

### Expected behavior

One should be able to load the fine-tuned checkpoint.

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by wnhsu** [comment]
Hi @patrickvonplaten , this should be solved in [this commit](https://github.com/pytorch/fairseq/commit/272c4c5197250997148fb12c0db6306035f166a4)
