### ISSUE TITLE
Error while loading RoBERT model

### ISSUE THREAD

**Issue by TanikSaikh** [pytorch/fairseq#3626]
![error](https://user-images.githubusercontent.com/13650045/122348754-1d98c900-cf69-11eb-967b-60c3ddfe068a.png)
I am facing this "TypeError: compose() got an unexpected keyword argument 'strict'" error. Please help me in this regard.

**Comment by sanjay23singh** [comment]
@TanikSaikh  have you got the answer?

**Comment by TanikSaikh** [comment]
> @TanikSaikh have you got the answer?

@sanjay23singh no not yet.

**Comment by u-shiori** [comment]
@sanjay23singh 
I had the same error.
I haven't figured out how to fix it yet.

**Comment by u-shiori** [comment]
@sanjay23singh
There seems to be a problem with the version of the installed module. 
Try the following.
```sh
pip install hydra==1.0
pip install omegaconf==2.0.5
```
The version of my torch is 1.7.1.

I hope it works for you.

**Comment by sanjay23singh** [comment]
(base) sanjaysingh@sanjay-singh-budhala ~ % pip install hydra==1.0     
Collecting hydra==1.0
  Using cached Hydra-1.0.tar.gz (8.6 kB)
Building wheels for collected packages: hydra
  Building wheel for hydra (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-install-qceg4u3g/hydra_456790c13f6d47e187c51fdc331ed72f/setup.py'"'"'; __file__='"'"'/private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-install-qceg4u3g/hydra_456790c13f6d47e187c51fdc331ed72f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-wheel-n2u6ytmv
       cwd: /private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-install-qceg4u3g/hydra_456790c13f6d47e187c51fdc331ed72f/
  Complete output (47 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  copying src/hydra.py -> build/lib.macosx-10.9-x86_64-3.8
  running build_ext
  cythoning src/_hydra.pyx to src/_hydra.c
  /opt/anaconda3/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-install-qceg4u3g/hydra_456790c13f6d47e187c51fdc331ed72f/src/_hydra.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
              self._idx +=1
              return result
          raise StopIteration
  
  
  class UnsupportedOperationException(StandardError): pass
                                     ^
  ------------------------------------------------------------
  
  src/_hydra.pyx:110:36: undeclared name not builtin: StandardError
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
                  return
  
      def bulkload_text(self, char* filename):
          cdef FILE* file_in = fopen( filename, "r")
          cdef char line[128]
          if file:
            ^
  ------------------------------------------------------------
  
  src/_hydra.pyx:378:11: undeclared name not builtin: file
  building '_hydra' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/include -arch x86_64 -I/opt/anaconda3/include -arch x86_64 -I/private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-install-qceg4u3g/hydra_456790c13f6d47e187c51fdc331ed72f/src -I/opt/anaconda3/include/python3.8 -c src/_hydra.c -o build/temp.macosx-10.9-x86_64-3.8/src/_hydra.o -std=gnu99 -O2
  src/_hydra.c:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
  #error Do not use this file, it is the result of a failed Cython compilation.
   ^
  1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for hydra
  Running setup.py clean for hydra
Failed to build hydra
Installing collected packages: hydra
  Attempting uninstall: hydra
    Found existing installation: Hydra 2.5
    Uninstalling Hydra-2.5:
      Successfully uninstalled Hydra-2.5
    Running setup.py install for hydra ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-install-qceg4u3g/hydra_456790c13f6d47e187c51fdc331ed72f/setup.py'"'"'; __file__='"'"'/private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-install-qceg4u3g/hydra_456790c13f6d47e187c51fdc331ed72f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-record-gw57mh2z/install-record.txt --single-version-externally-managed --compile --install-headers /opt/anaconda3/include/python3.8/hydra
         cwd: /private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-install-qceg4u3g/hydra_456790c13f6d47e187c51fdc331ed72f/
    Complete output (47 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    copying src/hydra.py -> build/lib.macosx-10.9-x86_64-3.8
    running build_ext
    cythoning src/_hydra.pyx to src/_hydra.c
    /opt/anaconda3/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-install-qceg4u3g/hydra_456790c13f6d47e187c51fdc331ed72f/src/_hydra.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                self._idx +=1
                return result
            raise StopIteration
    
    
    class UnsupportedOperationException(StandardError): pass
                                       ^
    ------------------------------------------------------------
    
    src/_hydra.pyx:110:36: undeclared name not builtin: StandardError
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                    return
    
        def bulkload_text(self, char* filename):
            cdef FILE* file_in = fopen( filename, "r")
            cdef char line[128]
            if file:
              ^
    ------------------------------------------------------------
    
    src/_hydra.pyx:378:11: undeclared name not builtin: file
    building '_hydra' extension
    creating build/temp.macosx-10.9-x86_64-3.8
    creating build/temp.macosx-10.9-x86_64-3.8/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/include -arch x86_64 -I/opt/anaconda3/include -arch x86_64 -I/private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-install-qceg4u3g/hydra_456790c13f6d47e187c51fdc331ed72f/src -I/opt/anaconda3/include/python3.8 -c src/_hydra.c -o build/temp.macosx-10.9-x86_64-3.8/src/_hydra.o -std=gnu99 -O2
    src/_hydra.c:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
    #error Do not use this file, it is the result of a failed Cython compilation.
     ^
    1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of Hydra
  Moving to /opt/anaconda3/lib/python3.8/site-packages/Hydra-2.5.dist-info/
   from /opt/anaconda3/lib/python3.8/site-packages/~ydra-2.5.dist-info
  Moving to /opt/anaconda3/lib/python3.8/site-packages/__pycache__/hydra.cpython-38.pyc
   from /private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-uninstall-3iq892rl/hydra.cpython-38.pyc
  Moving to /opt/anaconda3/lib/python3.8/site-packages/_hydra.cpython-38-darwin.so
   from /private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-uninstall-oc9w7u1u/_hydra.cpython-38-darwin.so
  Moving to /opt/anaconda3/lib/python3.8/site-packages/hydra.py
   from /private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-uninstall-oc9w7u1u/hydra.py
ERROR: Command errored out with exit status 1: /opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-install-qceg4u3g/hydra_456790c13f6d47e187c51fdc331ed72f/setup.py'"'"'; __file__='"'"'/private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-install-qceg4u3g/hydra_456790c13f6d47e187c51fdc331ed72f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/yw/y99d0611211gy634f51tmnd00000gp/T/pip-record-gw57mh2z/install-record.txt --single-version-externally-managed --compile --install-headers /opt/anaconda3/include/python3.8/hydra Check the logs for full command output.




@u-shiori  getting this error getting hydra 1.0

**Comment by nickboucher** [comment]
I'm seeing the same error with fairseq==0.10.2 and torch==1.9.0:
```sh
TypeError: compose() got an unexpected keyword argument 'strict'
```

I was able to resolve the issue using a modified version of @u-shiori's suggestion:
```sh
pip install hydra-core==1.0.0
pip install omegaconf==2.0.5
```

**Comment by TanikSaikh** [comment]
I am getting error like : "ERROR: Failed building wheel for hydra " of @u-shiori's suggestion

**Comment by sanjay23singh** [comment]
> I am getting error like : "ERROR: Failed building wheel for hydra " of @u-shiori's suggestion

exactly, the same i am getting for hydra

**Comment by u-shiori** [comment]
@TanikSaikh @sanjay23singh
I set the torch version to 1.7.1, and it worked fine.
Please try lowering the torch version.

If you run the program with the latest version of torch, it seems that there is an error on the compiler side, but I don't know how to fix it.

**Comment by me301** [comment]
> If you run the program with the latest version of torch, it seems that there is an error on the compiler side, but I don't know how to fix it.

Yeah that solved the issue for me too. I needed to lower the PyTorch version to 1.7.1, hydra-core to 1.0, and omegaconf to 2.0.5.

**Comment by arcontechnologies** [comment]
I downgraded to PyTorch version to 1.7.1, hydra-core to 1.0.0 and omegaconf to 2.0.5 as suggested above but still getting the error. Am I missing something else ?

**Comment by alexeib** [comment]
looks like hydra removed the strict flag for awhile but then added it back: https://github.com/facebookresearch/hydra/commit/8fa67de09bf3f2d7ff668a51a34680670084a59c#diff-bcde2b8a436d764c734ca509198c96842e95273799d366bae4616cc69cae8bbf

cc @omry

**Comment by omry** [comment]
It was removed in Hydra 1.1.0 and will be re-introduced in 1.1.1 which is not yet released.
It looks like the reports here are all about Hydra 1.0 which should not have that issue.

If someone wants to try fairseq with Hydra 1.1 they should install Hydra from master until 1.1.1 is released.
