### ISSUE TITLE
speech to speech model there?

### ISSUE THREAD

**Issue by neso613** [pytorch/fairseq#3639]
## ❓ Questions and Help
I am looking for a pre-trained speech-to-speech model. Does this repo have such model?

**Comment by olafthiele** [comment]
Do you mean audio from one person in and in the voice of another person out? No, you won't find this here. If you are looking for something like that, use STT/ASR for speech2text and then TTS for text2speech.

**Comment by neso613** [comment]
> Do you mean audio from one person in and in the voice of another person out? No, you won't find this here. If you are looking for something like that, use STT/ASR for speech2text and then TTS for text2speech.

 STT/ASR for speech2text. It should be from one lang to another. Say, english is input audio and output is french text.

**Comment by olafthiele** [comment]
Check these examples:
https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/simulst_mustc_example.md
