### ISSUE TITLE
How to improve performance of vads.py?

### ISSUE THREAD

**Issue by mjurkus** [pytorch/fairseq#3653]
I'm following the guide from https://github.com/pytorch/fairseq/tree/master/examples/wav2vec/unsupervised

And this step is taking a lot of time.
```
python scripts/vads.py -r $RVAD_ROOT < /path/to/train.tsv > train.vads
```

I have about 30hrs of audio data with audio segments between 1 and 30 seconds.

Running the command above:
```
root@e0d566a9b981:/workspace# python /workspace/fairseq/examples/wav2vec/unsupervised/scripts/vads.py -r $RVAD_ROOT < /workspace/data/audio/train/train.tsv > /workspace/audio/liepa/train/train.vads
```
where `RVAD_ROOT`
```
RUN git clone https://github.com/zhenghuatan/rVADfast
ENV RVAD_ROOT=/workspace/rVADfast
```
this will take more than 12hrs to complete. Am I doing something wrong?
Could this be improved using `multiprocessing`?

**Comment by alexeib** [comment]
yeah you can definitely make it faster. what we did is split tsv files into chunks and ran it on a cluster, but multiprocessing is another option. you can also port it to use gpu. if you end up implementing any of these please contribute back!
