### ISSUE TITLE
TypeError: build_generator() got an unexpected keyword argument 'prefix_allowed_tokens_fn'

### ISSUE THREAD

**Issue by iTharindu** [pytorch/fairseq#3654]
#### The full error is:
          TypeError  Traceback (most recent call last)
          
          <ipython-input-8-12941c7c49bc> in <module>()
          ----> 1 bart.sample(sentences=sentence_list[0])
          
          3 frames
          
          /content/fairseq/fairseq/hub_utils.py in sample(self, sentences, beam, verbose, **kwargs)
              128     ) -> List[str]:
              129         if isinstance(sentences, str):
          --> 130             return self.sample([sentences], beam=beam, verbose=verbose, **kwargs)[0]
              131         tokenized_sentences = [self.encode(sentence) for sentence in sentences]
              132         batched_hypos = self.generate(tokenized_sentences, beam, verbose, **kwargs)
          
          /content/fairseq/fairseq/hub_utils.py in sample(self, sentences, beam, verbose, **kwargs)
              130             return self.sample([sentences], beam=beam, verbose=verbose, **kwargs)[0]
              131         tokenized_sentences = [self.encode(sentence) for sentence in sentences]
          --> 132         batched_hypos = self.generate(tokenized_sentences, beam, verbose, **kwargs)
              133         return [self.decode(hypos[0]["tokens"]) for hypos in batched_hypos]
              134 
          
          /content/fairseq/fairseq/models/bart/hub_interface.py in generate(self, tokenized_sentences, inference_step_args, skip_invalid_size_inputs, *args, **kwargs)
              110                 inference_step_args=inference_step_args,
              111                 skip_invalid_size_inputs=skip_invalid_size_inputs,
          --> 112                 **kwargs
              113             )
              114             for id, hypos in zip(batch['id'].tolist(), results):
          
          /content/fairseq/fairseq/hub_utils.py in generate(self, tokenized_sentences, beam, verbose, skip_invalid_size_inputs, inference_step_args, prefix_allowed_tokens_fn, **kwargs)
              169             self.models,
              170             gen_args,
          --> 171             prefix_allowed_tokens_fn=prefix_allowed_tokens_fn,
              172         )
              173 
          
          TypeError: build_generator() got an unexpected keyword argument 'prefix_allowed_tokens_fn'`

#### Code

Loading - Does not throw any error
          `bart = BARTModel.from_pretrained( 
                  BASEDIR, 
                  checkpoint_file='checkpoint_89_75000.pt',           
                  data_name_or_path='pretrained_models/preprocess',   
                  bpe='sentencepiece',
                  sentencepiece_model=f'{BASEDIR}/sentence.bpe.model', 
                  source_dict=f'{BASEDIR}/dict.si_LK.txt',     
                  target_dict=f'{BASEDIR}/dict.en_XX.txt'
                  ) `
        `bart.eval()`

Translate - This is the function that throws the above error
        `sentence_list = ["රටක ප්‍රවේශ මාර්ග ජාලයක් ඉදිකිරීම"]`
        `bart.translate(sentences=sentence_list[0])`

#### What's your environment?
- Colab pro environment
- Fairseq latest stable release - v0.10.2

**Comment by nikhiljaiswal** [comment]
hi @iTharindu  did you find solution to this?

**Comment by yugaljain1999** [comment]
@nikhiljaiswal @iTharindu  Did u find solution to this?
