### ISSUE TITLE
Finetuning wav2vec2 with another letter vocabulary and `wer_args` setting problem.

### ISSUE THREAD

**Issue by PeiyuChen1005** [pytorch/fairseq#3655]
##### About Wav2Vec2 fine-tune
I want to use `flashlight python bindings` and `kenlm` to see my wer when finetuning on labeled data. The (readme)[https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/README.md] told that add `+criterion.wer_args='[/path/to/kenlm, /path/to/lexicon, 2, -1]'` to the command line, but I don't get the exact meaning. My `kenlm` is installed in `home/pychen/kenlm`, is it mean `/path/to/kenlm` should be set to `home/pychen/kenlm`?
Here's what my kenlm folder looks like:
```
~/kenlm$ ls
build  BUILDING  clean_query_only.sh  cmake  CMakeLists.txt  compile_query_only.sh  COPYING  COPYING.3  COPYING.LESSER.3  Doxyfile  LICENSE  lm  MANIFEST.in  python  README.md  setup.py  util
```
And what should `/path/to/lexicon` be set if I want use another letter vocabulary which is different from the (provided vocabulary)[https://dl.fbaipublicfiles.com/fairseq/wav2vec/dict.ltr.txt]?
Here's what my vocab looks like:
```
args["CHAR_TO_INDEX"] = {" ": 1, "'": 22, "1": 30, "0": 29, "3": 37, "2": 32, "5": 34, "4": 38, "7": 36, "6": 35, "9": 31, "8": 33, "A": 5, "C": 17,
                         "B": 20, "E": 2, "D": 12, "G": 16, "F": 19, "I": 6, "H": 9, "K": 24, "J": 25, "M": 18, "L": 11, "O": 4, "N": 7, "Q": 27,
                         "P": 21, "S": 8, "R": 10, "U": 13, "T": 3, "W": 15, "V": 23, "Y": 14, "X": 26, "Z": 28, "<EOS>": 39}

args["INDEX_TO_CHAR"] = {1: " ", 22: "'", 30: "1", 29: "0", 37: "3", 32: "2", 34: "5", 38: "4", 36: "7", 35: "6", 31: "9", 33: "8", 5: "A", 17: "C",
                         20: "B", 2: "E", 12: "D", 16: "G", 19: "F", 6: "I", 9: "H", 24: "K", 25: "J", 18: "M", 11: "L", 4: "O", 7: "N", 27: "Q",
                         21: "P", 8: "S", 10: "R", 13: "U", 3: "T", 15: "W", 23: "V", 14: "Y", 26: "X", 28: "Z", 39: "<EOS>"}
```

#### What's your environment?

 - fairseq Version : master
 - PyTorch Version : 1.8.1
 - OS : Ubuntu
 - How you installed fairseq : source
 - Python version: 3.8.8
 - CUDA/cuDNN version: 11.2
 - GPU models and configuration: NVIDIA-A100
 - Any other relevant information: None

**Comment by medabalimi** [comment]
> /path/to/kenlm
Path to your binary (build_binary) language model built using kenlm (lmplz). You ltr/character dict (dict.ltr.txt) should be contain character followed by a space and a number (normally frequency of occurence) and typically in descending order of frequency.
> /path/to/lexicon
Your lexicon (not to be convised with dict.ltr.txt) should have each line in the format <word><tab><individual letters separated by space with last characters as |>

**Comment by PeiyuChen1005** [comment]
> > /path/to/kenlm
> 
> Path to your binary (build_binary) language model built using kenlm (lmplz). You ltr/character dict (dict.ltr.txt) should be contain character followed by a space and a number (normally frequency of occurence) and typically in descending order of frequency.
> 
> > /path/to/lexicon
> 
> Your lexicon (not to be confused with dict.ltr.txt) should have each line in the format <individual letters separated by space with last characters as |>

Sorry, I didn't quite catch you. So how to build my lm using kenlm and If i should generate my own dict.ltr.txt by counting the number of letters in the transcription text if I'm not using Librispeech?
And is it possible to pin a example of lexicon?
Thanks!!!

**Comment by medabalimi** [comment]
> And is it possible to pin a example of lexicon? Is lexicon mean files like `train.ltr/wrd`?

HELLO    H E L L O |

**Comment by medabalimi** [comment]
> how to build my lm using kenlm

https://github.com/kpu/kenlm/blob/master/README.md

**Comment by medabalimi** [comment]
> If i should generate my own dict.ltr.txt by counting the number of letters in the transcription text if I'm not using Librispeech?

Yes.

**Comment by PeiyuChen1005** [comment]
> > And is it possible to pin a example of lexicon? Is lexicon mean files like `train.ltr/wrd`?
> 
> HELLO H E L L O |
> WORLD W O R L D |

So does this mean I should traverse my `train.wrd` and `valid.wrd` file to generate a lexicon file(in the format like: `word` `letter in word` `|`) corresponding to specified datasets?

**Comment by tensorfoo** [comment]
> > /path/to/kenlm
> 
> Path to your binary (build_binary) language model built using kenlm (lmplz). You ltr/character dict (dict.ltr.txt) should be contain character followed by a space and a number (normally frequency of occurence) and typically in descending order of frequency.

Hey, have you actually got it to work like this? I keep getting `omegaconf.errors.ValidationError: Cannot convert 'ListConfig' to string : '['/fast/swa/lm/lm/lm.bin', '/fast/swa/lm/lm/lexicon.txt', 2, -1]'` errors. I've tried pretty much every iteration of quoting paths, not quoting them, using single or double quotes etc. I also like OP thought it wanted the path to the kenlm home but even pointing to the lm.bin file doesn't work.

**Comment by medabalimi** [comment]
> omegaconf.errors.ValidationError: Cannot convert 'ListConfig' to string : '['/swa/lm/lm/lm.bin', '/swa/lm/lm/lexicon.txt', 2, -1]'

Nope. You need to use --lm-model /path/to/kenlm.bin --lm-weight 2 --word-score -1

**Comment by tensorfoo** [comment]
That didn't work. To confirm, are you talking about finetuning? 

`fairseq-hydra-train: error: unrecognized arguments: --lm-model /swa/lm/lm/lm.bin --lexicon /swa/lm/lm/lm.bin --lm-weight 2 --word-score -1`

**Comment by medabalimi** [comment]
My bad. Mixed up the infer.py options with the training ones. 
`+criterion.wer_kenlm_model=$LM_PATH  +criterion.wer_lexicon=$LEX_PATH  +criterion.wer_lm_weight=2      +criterion.wer_word_score=-1 `

**Comment by tensorfoo** [comment]
Thank you so much. Working now :)
