### ISSUE TITLE
Error when inferring Wav2vec2.0 pre-trained model with Transformer LM

### ISSUE THREAD

**Issue by homin-ryu** [pytorch/fairseq#3656]
#### What is your question?
I downloaded the trained model and I am trying to reproduce the results of the paper ( https://arxiv.org/pdf/2006.11477.pdf ). 
However, I get the following error:

INFO:__main__:| decoding with criterion ctc
INFO:__main__:| loading model(s) from wav2vec_small_100h.pt
INFO:fairseq.data.audio.raw_audio_dataset:loaded 2939, skipped 0 samples
INFO:__main__:| manifest/test/ test-other 2939 examples
Traceback (most recent call last):
  File "/root/fairseq/examples/speech_recognition/infer.py", line 427, in <module>
    cli_main()
  File "/root/fairseq/examples/speech_recognition/infer.py", line 423, in cli_main
    main(args)
  File "/root/fairseq/examples/speech_recognition/infer.py", line 283, in main
    generator = build_generator(args)
  File "/root/fairseq/examples/speech_recognition/infer.py", line 276, in build_generator
    return W2lFairseqLMDecoder(args, task.target_dictionary)
  File "/root/fairseq/examples/speech_recognition/w2l_decoder.py", line 392, in __init__
    model = task.build_model(lm_args.model)
  File "/root/fairseq/fairseq/tasks/language_modeling.py", line 189, in build_model
    model = super().build_model(args)
  File "/root/fairseq/fairseq/tasks/fairseq_task.py", line 660, in build_model
    model = models.build_model(args, self)
  File "/root/fairseq/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/root/fairseq/fairseq/models/transformer_lm.py", line 261, in build_model
    len(task.source_dictionary),
TypeError: object of type 'NoneType' has no len()

How can I reproduce the results of paper without errors?

#### Code
`python ~/fairseq/examples/speech_recognition/infer.py manifest/path/ \`
`--task audio_pretraining \`
`--nbest 1 \`
`--path wav2vec_small_100h.pt \`
`--gen-subset test-other \`
`--results-path result/path/ \`
`--w2l-decoder fairseqlm  \`
`--lexicon librispeech_lexicon.lst \`
`--lm-model lm_librispeech_word_transformer.pt \`
`--lm-weight 0.87 --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter \`
`--beam 500`
   

#### What have you tried?
wav2vec_small_100h.pt: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_small_100h.pt
librispeech_lexicon.lst: https://dl.fbaipublicfiles.com/fairseq/wav2vec/librispeech_lexicon.lst
lm_librispeech_word_transformer.pt: https://dl.fbaipublicfiles.com/wav2letter/sota/2019/lm/lm_librispeech_word_transformer.pt

I succeeded in base model train/fine-tune and inference with 4-gram LM.

#### What's your environment?
 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.8.0
 - OS (e.g., Linux): ubuntu
 - How you installed fairseq (`pip`, source): git clone
 - Build command you used (if compiling from source): 
`git clone https://github.com/pytorch/fairseq`
`cd fairseq`
`pip install --editable ./`
 - Python version: 3.8.8
 - CUDA/cuDNN version: 11.2/8.0.5
 - GPU models and configuration: gtx titanX
 - Any other relevant information:

**Comment by medabalimi** [comment]
I suspect this has to do with hydra vs pre-hydra model. It looks like the dictionary file containing list of words is missing.

**Comment by Jxu-Thu** [comment]
any update?

**Comment by Jxu-Thu** [comment]
@homin-ryu Can you share the experience to reproduce the results with 4-gram LM?

**Comment by Jxu-Thu** [comment]
I provide more details for reproduction.

Using wav2vec_small_100h.pt on dev-other dataset.
virtebi : 13.58 [Paper: 13.5]
-
python examples/speech_recognition/infer.py dev_other --task audio_pretraining \
--nbest 1 --path wav2vec_small_100h.pt --gen-subset valid --results-path official_base --w2l-decoder viterbi \
--lm-model lm_librispeech_word_transformer.pt --lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter
-

kenlm : 13.19 [Paper 7.9]
python examples/speech_recognition/infer.py dev_other --task audio_pretraining \
--nbest 1 --lexicon librispeech_lexicon.lst \
--path wav2vec_small_100h.pt --gen-subset valid \
--results-path official_base --w2l-decoder kenlm \
--lm-model lm_librispeech_kenlm_word_4g_200kvocab.bin \
--lm-weight 0.1 --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter


Transformer LM : None
I encounter the error.

Why kenlm' results do not reach the results reported in the paper? I have tried many different lm-weight.

**Comment by homin-ryu** [comment]
@Jxu-Thu please refer to the https://github.com/pytorch/fairseq/issues/3658#event-4957215645

**Comment by Jxu-Thu** [comment]
> @Jxu-Thu please refer to the [#3658 (comment)](https://github.com/pytorch/fairseq/issues/3658#event-4957215645)

Thanks for your reply!!!!
Can you provide the command to reproduce the results? And help check the url below is correct.
With kenlm, you download the LM and lexicon directly from the [https://openslr.magicdatatech.com/resources/11/](url)?
LM : [https://openslr.magicdatatech.com/resources/11/4-gram.arpa.gz](url)
Lexicon: [https://openslr.magicdatatech.com/resources/11/librispeech-lexicon.txt](url)
And how to set the lm-weight and word-score?

And How about Transformer LM?
1 LM : [https://dl.fbaipublicfiles.com/wav2letter/sota/2019/lm/lm_librispeech_word_transformer.pt](url)
2 Lexicon: [https://dl.fbaipublicfiles.com/wav2letter/sota/2019/librispeech/models/am/librispeech-train%2Bdev-unigram-10000-nbest10.lexicon](url)
3 uppercase the transformer dictionary, name it 'dict.txt',

And how to set the lm-weight and word-score?

**Comment by homin-ryu** [comment]
i missed dictionary of LM. i can get the right inference results.
