### ISSUE TITLE
Why wav2vec 2.0 inference requires so many complicated packages to install?

### ISSUE THREAD

**Issue by Jxu-Thu** [pytorch/fairseq#3665]
Thanks for your great codes! I enjoy your codes for several years when using them for machine translation tasks.
Recently, I try your wav2vec 2.0 codebase.
But I found that wav2vec inference with a LM model needs the python binding flashlight and wav2letter. And the installation of flashlight/wav2letter is quite complicated.
I encounter many errors when installing KenLM and other packages.

Is there any possibility to remove these installations to make your codes to be self-contained?

**Comment by magiczixiao** [comment]
I ran into the same problem and I am curious why these libraries are not needed in the training phase but needed in the inference phase.
