### ISSUE TITLE
Implementation of "Fully Non-autoregressive Neural Machine Translation" (Gu and Kong, 2020)

### ISSUE THREAD

**Issue by stephanpeitz** [pytorch/fairseq#3666]
Hi all,

I just read the paper "Fully Non-autoregressive Neural Machine Translation: Tricks of the Trade" (https://arxiv.org/abs/2012.15833, great work!).
The authors mention that "[a]ll models are implemented on fairseq (Ott et al., 2019).".

I double checked https://github.com/pytorch/fairseq/tree/master/examples/nonautoregressive_translation but couldn't find any example/implementation for this method.

Are you planning to release related code?

Thanks!

Cheers,
Stephan

**Comment by lematt1991** [comment]
CC @MultiPath

**Comment by MultiPath** [comment]
Hi, I will push a version of this code soon maybe by next week. We worked on an old version of fairseq and we need to merge it to the current master branch.

**Comment by stephanpeitz** [comment]
Hi, 

thanks for the quick reply! Looking forward!!

Cheers,
Stephan

**Comment by stephanpeitz** [comment]
Hi @MultiPath,

any update on this? 

Cheers,
Stephan

**Comment by nlpcat** [comment]
@MultiPath can I ask whether there is any plan to add it into fairseq or open source the code? Thanks a lot.

**Comment by akashkm99** [comment]
> Hi, I will push a version of this code soon maybe by next week. We worked on an old version of fairseq and we need to merge it to the current master branch.

@MultiPath It would be great if you can release the current code in a separate repo if merging with the master branch is difficult. Thanks.

**Comment by jingmu123** [comment]
@MultiPath hello, is there still a plan for release the code? Thanks a lot.

**Comment by nihirv** [comment]
Hello - we're still looking for this code. Any update @MultiPath ? Even if it can be released on an older version of fairseq that would be great

**Comment by stephanpeitz** [comment]
Hi @nihirv, you might want to check out #4431.
This PR reimplements some of the methods + other STOA methods.

Cheers,
Stephan

**Comment by nihirv** [comment]
I wouldn't have found that otherwise. Thank you @stephanpeitz !
