### ISSUE TITLE
How to extract sentence features (vectors) from a custom transformer language model?

### ISSUE THREAD

**Issue by michal-pikusa** [pytorch/fairseq#3670]
#### What is your question?

I have trained a simple custom transformer language model following the exact instructions and parameters from your readme (https://github.com/pytorch/fairseq/blob/master/examples/language_model/README.md), and now I would like to extract features for new sentences (a vector for each sentence). Is that possible?

After loading the model, I can encode new sentences and get token tensors in return, but I don't see any functions to get the features (like the extract_features function in roBERTa) in the form of tensors/vectors for each new sentence. Is there any way to do that?

Thanks in advance.

**Comment by lematt1991** [comment]
You can access the underlying `models` from the hub interface.  The following should do what you're looking for:

```Python
import torch

en_lm = torch.hub.load('pytorch/fairseq', 'transformer_lm.wmt19.en', tokenizer='moses', bpe='fastbpe')
tokens = en_lm.encode('This is a test')
batch_tokens = tokens.unsqueeze(0)  # extract_features expects a batch of tokens
x, extra = en_lm.models[0](tokens)  # [0] specifies the first model in the ensemble
extracted_features = extra["inner_states"][-1]  # -1 will give you the last layer's features
```

**Comment by michal-pikusa** [comment]
Thanks for the code, however it seems that it's not working. This is what I have when I try it:

`>>> en_lm = torch.hub.load('pytorch/fairseq', 'transformer_lm.wmt19.en', tokenizer='moses', bpe='fastbpe')
Downloading: "https://github.com/pytorch/fairseq/archive/master.zip" to /Users/pikusmi1/.cache/torch/hub/master.zip
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3617096500/3617096500 [05:12<00:00, 11587188.41B/s]
Loading codes from /Users/pikusmi1/.cache/torch/pytorch_fairseq/0cabe4a3e5ef7de13b205be3ab7feaf000768c332991cab28503a5464cbd5133.1194dafe66fa251b0e81fb532efac27216c501bfb0573c5d7e77e04dd6d88b15/bpecodes ...
Read 30000 codes from the codes file.
>>> tokens = en_lm.encode('This is a test')
>>> batch_tokens = tokens.unsqueeze(0) 
>>> x, extra = en_lm.models[0](tokens)  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pikusmi1/miniconda3/envs/sig2cpd/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/pikusmi1/miniconda3/envs/sig2cpd/lib/python3.6/site-packages/fairseq/models/fairseq_model.py", line 481, in forward
    return self.decoder(src_tokens, **kwargs)
  File "/Users/pikusmi1/miniconda3/envs/sig2cpd/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/pikusmi1/miniconda3/envs/sig2cpd/lib/python3.6/site-packages/fairseq/models/transformer.py", line 691, in forward
    alignment_heads=alignment_heads,
  File "/Users/pikusmi1/miniconda3/envs/sig2cpd/lib/python3.6/site-packages/fairseq/models/transformer.py", line 712, in extract_features
    alignment_heads,
  File "/Users/pikusmi1/miniconda3/envs/sig2cpd/lib/python3.6/site-packages/fairseq/models/transformer.py", line 757, in extract_features_scriptable
    if self.embed_positions is not None
  File "/Users/pikusmi1/miniconda3/envs/sig2cpd/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/pikusmi1/miniconda3/envs/sig2cpd/lib/python3.6/site-packages/fairseq/modules/sinusoidal_positional_embedding.py", line 69, in forward
    bsz, seq_len = bspair[0], bspair[1]
IndexError: index 1 is out of bounds for dimension 0 with size 1`

Any suggestions what could be causing that error?
Thanks!

**Comment by michal-pikusa** [comment]
I figured it out. There was a typo, as in the code you pasted you passed tokens instead of batch_tokens to the model. 

Now it works correctly:
```
>>> x, extra = en_lm.models[0](batch_tokens)
>>> extracted_features = extra["inner_states"][-1]
>>> extracted_features
tensor([[[-3.5917, -1.8685, -9.1815,  ..., -4.9372,  8.9840,  7.8096]],

        [[ 0.5874, -4.2458, -6.0061,  ..., -5.2102,  4.8120, 10.1918]],

        [[ 5.3164, -3.1789, -2.2152,  ..., -7.4375,  5.0749,  7.6545]],

        [[ 7.2160, -2.4256, -2.2334,  ..., -6.8708, 11.5427,  0.9657]],

        [[-1.7110,  0.8291,  0.3438,  ..., -4.2493,  3.7655,  2.7240]]],
       grad_fn=<AddBackward0>)
```
Thanks a lot for your help!
