### ISSUE TITLE
ImportError: cannot import name 'MaskedLanguagePairDataset'

### ISSUE THREAD

**Issue by abhijithneilabraham** [pytorch/fairseq#3671]
When I try to run 
```
from fairseq.data import MaskedLanguagePairDataset 
```
I get the following error:

```
ImportError: cannot import name 'MaskedLanguagePairDataset'
```

I am running fairseq==0.8.0
Where has this been moved to?

**Comment by abhijithneilabraham** [comment]
Thanks. That worked. There's one more I am trying to find:
```from fairseq.data.legacy.bert_dictionary import BertDictionary```
raises
```
ModuleNotFoundError: No module named 'fairseq.data.legacy.bert_dictionary'
```
Can you tell me where this has been moved to as well?

**Comment by jubick1337** [comment]
Yep it's [here](https://github.com/pytorch/fairseq/blob/v0.8.0/fairseq/data/legacy/masked_lm_dictionary.py)

**Comment by abhijithneilabraham** [comment]
Thanks!
