### ISSUE TITLE
Compatibility with Hydra 1.1 release

### ISSUE THREAD

**Issue by ailzhang** [pytorch/fairseq#3672]
Latest hydra 1.1 release made some BC breaking changes in APIs, namely they removed kwarg `strict` in `experimental` which was available in 1.0.6. https://github.com/facebookresearch/hydra/blob/v1.0.6/hydra/experimental/compose.py#L13 

fairseq is using the old API so it's not working with the latest hydra release. One example to repro is
```
roberta = torch.hub.load('pytorch/fairseq', 'roberta.large')
```
This should be a simple fix but it's probably worth reporting to hydra about reducing future BC breaking changes.

**Comment by lematt1991** [comment]
Thanks for reporting, @ailzhang!  @omry created #3659 to address 1.1 compatibility, does this address the problem you mention?

**Comment by lematt1991** [comment]
```
roberta = torch.hub.load('pytorch/fairseq', 'roberta.large')
```

Seems to work now that #3659 has been merged.
