### ISSUE TITLE
How to generate config.yaml file for inferencing wav2vec_small_960h using fairseq-interactive

### ISSUE THREAD

**Issue by Hemant6174** [pytorch/fairseq#3688]
I am trying to run and generate a transcript for a single audio file using wav2vec_small_960h.pt model and fairseq-interactive. I need config.yaml file for running fairseq-interactive command so how to generate this file?

**Comment by ranveerkln** [comment]
Did you get some solution on your own to solve this issue. I am facing the same problem. I want  config.yaml file
