### ISSUE TITLE
Reproducing RoBERTa STS-B results 

### ISSUE THREAD

**Issue by xuuuluuu** [pytorch/fairseq#3690]
Hi, I am trying to use the following code to evaluate the saved model.

I found that some of the value of the output is larger than 5, which is not allowed for STS-B task. 

predictions = 5.0 * roberta.model.classification_heads'sentence_classification_head'

Why do we need to multiply 5.0 to the output of the model?

The same issue can also be found [here](https://github.com/pytorch/fairseq/issues/1009).

```

from fairseq.models.roberta import RobertaModel
from scipy.stats import pearsonr

roberta = RobertaModel.from_pretrained(
    'checkpoints/',
    checkpoint_file='checkpoint_best.pt',
    data_name_or_path='STS-B-bin'
)

roberta.cuda()
roberta.eval()
gold, pred = [], []
with open('glue_data/STS-B/dev.tsv') as fin:
    fin.readline()
    for index, line in enumerate(fin):
        tokens = line.strip().split('\t')
        sent1, sent2, target = tokens[7], tokens[8], float(tokens[9])
        tokens = roberta.encode(sent1, sent2)
        features = roberta.extract_features(tokens)
        predictions = 5.0 * roberta.model.classification_heads['sentence_classification_head'](features)
        gold.append(target)
        pred.append(predictions.item())

print('| Pearson: ', pearsonr(gold, pred))

```

**Comment by pqz793** [comment]
Hello!
In the original STS problem, the lables range from 0 to 5. 
In the examples/roberta/preprocess_GLUE_tasks.sh(see [https://github.com/pytorch/fairseq/blob/main/examples/roberta/preprocess_GLUE_tasks.sh#L182](url)), the label is reranged to 0 to 1.
So in evaluation step, we need to  multiply 5.0 to the output of the model to compute the Pearson with original labels correctly.

**Comment by QizhiPei** [comment]
> Hi, I am trying to use the following code to evaluate the saved model.
> 
> I found that some of the value of the output is larger than 5, which is not allowed for STS-B task.
> 
> predictions = 5.0 * roberta.model.classification_heads'sentence_classification_head'
> 
> Why do we need to multiply 5.0 to the output of the model?
> 
> The same issue can also be found [here](https://github.com/pytorch/fairseq/issues/1009).
> 
> ```
> 
> from fairseq.models.roberta import RobertaModel
> from scipy.stats import pearsonr
> 
> roberta = RobertaModel.from_pretrained(
>     'checkpoints/',
>     checkpoint_file='checkpoint_best.pt',
>     data_name_or_path='STS-B-bin'
> )
> 
> roberta.cuda()
> roberta.eval()
> gold, pred = [], []
> with open('glue_data/STS-B/dev.tsv') as fin:
>     fin.readline()
>     for index, line in enumerate(fin):
>         tokens = line.strip().split('\t')
>         sent1, sent2, target = tokens[7], tokens[8], float(tokens[9])
>         tokens = roberta.encode(sent1, sent2)
>         features = roberta.extract_features(tokens)
>         predictions = 5.0 * roberta.model.classification_heads['sentence_classification_head'](features)
>         gold.append(target)
>         pred.append(predictions.item())
> 
> print('| Pearson: ', pearsonr(gold, pred))
> ```

Hello!
In the original STS problem, the lables range from 0 to 5. 
In the examples/roberta/preprocess_GLUE_tasks.sh(see [Line 182 183](https://github.com/pytorch/fairseq/blob/d792b793a777bf660d2aaeb095c2381af189e626/examples/roberta/preprocess_GLUE_tasks.sh?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L182)) the label is reranged to 0 to 1.
So in evaluation step, we need to  multiply 5.0 to the output of the model to compute the Pearson with original labels correctly.
