### ISSUE TITLE
Training Fairseq model using pre-trained embeddings

### ISSUE THREAD

**Issue by NourKhdour** [pytorch/fairseq#3691]
## ❓ Questions and Help

I'm using a big model from fairseq. And I'm experimenting using pre-trained embedding  with fairseq. But when i start training with embeddings parameters in the encoder side  on fp16, this error generated (FloatingPointError: Minimum loss scale reached (0.0001). Your loss is probably exploding. Try lowering the learning rate, using gradient clipping or increasing the batch size).

#### Code

I used this command to train a fasttext model using custom data:
training fasttext command (skipgram -input data.en -output fasttext.en -lr 0.025 -dim 768 -ws 5 -epoch 10 -minCount 5 -neg 5 -loss ns -bucket 2000000   -minn 3 -maxn 6 -thread 16 -t 1e-4 -lrUpdateRate 100)

part of my training fairseq command that related to embeddings is (  --encoder-embed-path  fasttext.en.vec ---encoder-embed-dim 768 --decoder-embed-dim 768)

#### What have you tried?

As well i tried solutions such as:
1) decreasing the learning rate.
2) increase the batch size.
3) add these parameters ( --fp16-scale-tolerance, --min-loss-scale, --update-freq).

But none of them can solve the problem. The only thing that worked was switching to FP32 training, but that is not an option since the training will be slower.
#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 1.0.0
 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: Python 3.6.9
 - CUDA/cuDNN version:10.2
 - GPU models and configuration:
 - Any other relevant information:

#### What is your question?
How to solve this? and what is the proper way to use pre-trained embedding?

**Comment by LoganLiu66** [comment]
Have you found out any solution for this? I'm facing the same issue
