### ISSUE TITLE
wav2vec 2.0 inference (infer.py) without LM 

### ISSUE THREAD

**Issue by Orlllem** [pytorch/fairseq#3697]
## ❓ Questions and Help

Looking at `examples/speech_recognition/infer.py` I undestand that you a trained LM to evaluate your trained wav2vec 2.0.  
I would like to use `examples/speech_recognition/infer.py` without the need of a trained LM. 

It is possible?

**Comment by medabalimi** [comment]
You don't need a LM to evaluate wav2vec 2.0. The CTC decoder should suffice. Refer to https://github.com/pytorch/fairseq/tree/master/examples/wav2vec#evaluating-a-ctc-model

**Comment by tahirjmakhdoomi** [comment]
What you can do is use --w2l-decoder as viterbi

**Comment by magiczixiao** [comment]
> You don't need a LM to evaluate wav2vec 2.0. The CTC decoder should suffice. Refer to https://github.com/pytorch/fairseq/tree/master/examples/wav2vec#evaluating-a-ctc-model

Do I have to install flashlight python bindings (previously called wav2letter) if I don’t use the language model? I can’t install wav2letter due to the CUDA version. I’m curious why WER can be tested in the training phase and the wav2letter decoder must be relied on in the inference phase. Thanks!
