### ISSUE TITLE
What does 1 update in the log file correspond to? Does it refer to update after a pass through a batch?

### ISSUE THREAD

**Issue by Kanchan112** [pytorch/fairseq#3710]
What does 1 update in the log file correspond to? Does it refer to update after a pass through a batch?

**Comment by RuABraun** [comment]
What is `log_interval` set to in your config?

**Comment by Kanchan112** [comment]
100

**Comment by RuABraun** [comment]
Then it's every 100 updates, as you should see from what is bring printed (`num_updates` should be increasing by 100 each time).

**Comment by jubick1337** [comment]
I might be wrong but it seems to be number of optimizer.step() calls.
One can control update frequency in optimization part of config and if one sets it to be higher than 1 training would be slower (same amount of num updates but more time)
