### ISSUE TITLE
Self-training a fine-tuned wav2vec2 model?

### ISSUE THREAD

**Issue by thanhkm** [pytorch/fairseq#3711]
#### What is your question?
I did fine-tune a Wav2vec2 model. Now, I would like to do self-training this model to reinforce it with our unlabeled data. Could you give me some guidelines?

**Comment by olafthiele** [comment]
wav2vec works generally works by pretraining a model with unlabeled data and then fintuning it for ctc with labeled data, not the other way around.

**Comment by thanhkm** [comment]
> wav2vec works generally works by pretraining a model with unlabeled data and then fintuning it for ctc with labeled data, not the other way around.

If you see this paper https://arxiv.org/pdf/2010.11430v1.pdf, they did a supplement self-training after the fine-tuning. This is not only help reinforce the model but also improve the performance.

**Comment by olafthiele** [comment]
Ah, haven't seen configs for that here, I guess wav2vecu superseeds that approach. Maybe @alexeib could tell you more.
