### ISSUE TITLE
Error with wav2vec2 on TPU

### ISSUE THREAD

**Issue by cceyda** [pytorch/fairseq#3714]
#### What is your question?
Trying to run Wav2vec2 on TPU. Using the example [config ](https://github.com/pytorch/fairseq/blob/f2146bdc7abf293186de9449bfa2272775e39e1d/examples/wav2vec/config/pretraining/wav2vec2_large_librivox_tpu.yaml)

Getting Error:

`AssertionError: inferred_w2v_config must be set`

Can't find anything on how to set inferred_w2v_config. I mean model params are already defined on config.yaml 

#### Code
inferred_w2v_config  is here:

https://github.com/pytorch/fairseq/blob/f2146bdc7abf293186de9449bfa2272775e39e1d/fairseq/tasks/audio_pretraining.py#L47

#### What have you tried?

Not sure what to write in config
inferred_w2v_config: ???

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 0.9
 - OS (e.g., Linux):Linux
 - How you installed fairseq (`pip`, source): pip install -e .
 - Build command you used (if compiling from source):-
 - Python version:3.8
 - CUDA/cuDNN version:-
 - GPU models and configuration:-
 - Any other relevant information:

**Comment by Megumu2597** [comment]
I have experienced the same problem.
Hardcoding of inferred_w2v_config  also didn't work.
Then, I found this config is added in latest commit.
So as a workaround , I reverted the commit to the old one, and it works well like this.
> git checkout 374fdc5cd94d361bb9b1089fe2c1d30a2eb15fdd

**Comment by cceyda** [comment]
Good workaround, thanks for the info~ 
also needed to reinstall
```
pip uninstall fairseq
pip install -e .
```
not sure why inferred_w2v_config was added though 😕 
but at least it works this way 🙂
