### ISSUE TITLE
To generate transcript for longer audios using wav2vec2

### ISSUE THREAD

**Issue by Hemant6174** [pytorch/fairseq#3716]
I am trying to use wav2vec2_small_960h to generate transcripts for longer audios(length more than 30 seconds). I am trying to split the audio into smaller chunks and combine them but it is not giving good accuracy. Is there any method that I can use to generate transcripts for longer audios as well? @alexeib

**Comment by olafthiele** [comment]
Use VAD like [webrtcvad ](https://pypi.org/project/webrtcvad/)to get smaller chunks, maybe use longer chunks than it cuts.
