### ISSUE TITLE
--keep-inference-langtok flag doesn't work

### ISSUE THREAD

**Issue by jiminsun** [pytorch/fairseq#3719]
https://github.com/pytorch/fairseq/blob/c1624b273b206cc7c0a1529be4d2f35b38607ec5/fairseq/tasks/translation_multi_simple_epoch.py#L206

Hi, I have been training a multilingual translation model, and tried using the `--keep-inference-langtok` flag at inference time for debugging.
However, the flag doesn't work; the target language token is always stripped from the hypothesis even when you set the flag true.

I've tried printing out `args` right before the referenced point, which shows the following:

{'_name': None, 'beam': 4, 'nbest': 1, 'max_len_a': 0.0, 'max_len_b': 200, 'min_len': 1, 'match_source_len': False, 'unnormalized': False, 'no_early_stop': False, 'no_beamable_mm': False, 'lenpen': 0.6, 'unkpen': 0.0, 'replace_unk': None, 'sacrebleu': True, 'score_reference': False, 'prefix_size': 0, 'no_repeat_ngram_size': 0, 'sampling': False, 'sampling_topk': -1, 'sampling_topp': -1.0, 'constraints': None, 'temperature': 1.0, 'diverse_beam_groups': -1, 'diverse_beam_strength': 0.5, 'diversity_rate': -1.0, 'print_alignment': None, 'print_step': False, 'lm_path': None, 'lm_weight': 0.0, 'iter_decode_eos_penalty': 0.0, 'iter_decode_max_iter': 10, 'iter_decode_force_max_iter': False, 'iter_decode_with_beam': 1, 'iter_decode_with_external_reranker': False, 'retain_iter_history': False, 'retain_dropout': False, 'retain_dropout_modules': None, 'decoding_format': None, 'no_seed_provided': False}

You can see that `keep_inference_langtok` doesn't exist in args, and this seems to cause the referenced if statement to return True regardless the flag.

**Comment by cordercorder** [comment]
Modifying ` if not getattr(args, "keep_inference_langtok", False): ` to `if not getattr(self.args, "keep_inference_langtok", False):` will work.

Please see https://github.com/pytorch/fairseq/pull/3607
