### ISSUE TITLE
Fine-tuned robust Wav2Vec 2.0 models

### ISSUE THREAD

**Issue by Nithin-Holla** [pytorch/fairseq#3721]
#### What is your question?
Thanks for releasing the robust Wav2Vec 2.0 pretrained model. Would the fine-tuned models (particularly the one fine-tuned on LibriSpeech) be released as well?

@alexeib

**Comment by olafthiele** [comment]
You find the [English finetuned models here](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec#pre-trained-models), but I guess you mean the ones for the multi-language test? Those are not published afaik. You could try the [Huggingface models](https://huggingface.co/models?search=wav2vec) for a start.

**Comment by Nithin-Holla** [comment]
@olafthiele The robust Wav2Vec 2.0 model published [here](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec#pre-trained-models) and on Hugging Face is pretrained on LV-60 + CV + SWBD + FSH and is not fine-tuned on the ASR task. The models there that are fine-tuned on the ASR task are based on the regular Wav2Vec 2.0 and not the robust version.

**Comment by olafthiele** [comment]
@Nithin-Holla, yes you are right, didn't catch the robust part. No, not released yet afaik. @wnhsu?

**Comment by isgursoy** [comment]
watching
