### ISSUE TITLE
How to speed up Wav2vec 2.0 model performance and deploy this model on production?

### ISSUE THREAD

**Issue by miladfa7** [pytorch/fairseq#3736]
I fine-tuned the Wav2vec model on my database and we want to deploy it on the production, due to the high parameters (317M) of this model and the high speed of converting speech to text, so I can not deploy it on the production.
please help me!!!

**Comment by jubick1337** [comment]
Hi @miladfa7 
I don't think there are any tools for speed up in fairseq 
Although you can search for pruning/quantization etc
