### ISSUE TITLE
Support for lazy loading

### ISSUE THREAD

**Issue by gaojun4ever** [pytorch/fairseq#375]
Do you have any plan on implementing big data files loading functionality?

Suppose I have 300G data files for training, and I can’t load them all into memory.

**Comment by myleott** [comment]
We have some partial support for this via --fix-batches-to-gpus, where each worker will only load its portion of the full dataset. But when training with multiple workers on a single machine (e.g., multi-GPU training), then this will still require you to have enough memory to load the entire dataset.

It should be possible to process chunks of your dataset and modify train.py to load them separately though. For example, add an inner loop here that re-instantiates epoch_itr with different portions of your dataset: https://github.com/pytorch/fairseq/blob/master/train.py#L88-L100

**Comment by huihuifan** [comment]
@gaojun4ever , could yout ry the new --lazy-load option? https://github.com/pytorch/fairseq/commit/14bd9c62a3084ebc1cb3b5feb1e6b83f90be6449

should resolve your issue.

**Comment by huihuifan** [comment]
@gaojun4ever , hope the above helped. please re-open if this did not fix your problem.

**Comment by xu-song** [comment]
+1
