### ISSUE TITLE
Some bugs about model's architecture

### ISSUE THREAD

**Issue by trestad** [pytorch/fairseq#3761]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

I find that when I use cmd "git clone https://github.com/pytorch/fairseq" to install fairseq, there are some bugs. For example, in  
 “transformer_iwslt_de_en”,  the parameter "--encoder/decoder-ffn-embed-dim" should be 1024, but even though I have used "-arch transformer_iwslt_de_en" in the train command, I still got a model with architecture of "base_architecture" where "--encoder-ffn-embed-dim" is 2048. 
When I turn to the stable release, this bug never shows.
I hope you can fix this.

2. See error

![image](https://user-images.githubusercontent.com/55476033/128163353-ae8084d1-3a7d-4d59-8ee3-7c2f0ba39595.png)

![image](https://user-images.githubusercontent.com/55476033/128163478-045418b3-4f59-4eee-8c78-b67b036a02c5.png)

**Comment by freewym** [comment]
I have the same problem with the master branch: command line arguments for the Transformer's architecture seem not to overwrite the default values
