### ISSUE TITLE
fairseq-hydra-train: how to change the location of the outputs directory containing hydra_train.log 

### ISSUE THREAD

**Issue by tensorfoo** [pytorch/fairseq#3764]
it currently populates outputs/ in the location where `fairseq-hydra-train` is called but i'd like it to go somewhere else more sensible.

**Comment by tensorfoo** [comment]
Think i got it, needed to add `-m hydra.sweep.dir=pathtodir`

**Comment by chengrunyang** [comment]
Hi @tensorfoo , did you add `-m hydra.sweep.dir=<pathtodir>` as an argument to the `fairseq-hydra-train` command? 

On my end, adding `-m hydra.sweep.dir=<pathtodir>` gives `fairseq-hydra-train: error: unrecognized arguments: hydra.sweep.dir=<pathtodir>`, and adding `hydra.sweep.dir=<pathtodir>` (without `-m`) does not change the output location.

**Comment by tensorfoo** [comment]
Hi @chengrunyang. I don't know why I wrote -m either now. But for pretraining you're right it doesn't work but it did work for  fine-tuning (without the -m). I would also like to do it for pretraining so please let me know if you figure it out.

**Comment by chengrunyang** [comment]
Thanks for the information. Weird, I'm fine-tuning RoBERTa on GLUE tasks, and neither with nor without the `-m` works. Not sure if it's specific to your fine-tuning task. Would you mind sharing an example command that you used?
