### ISSUE TITLE
How to run the pretrained language model on the test set

### ISSUE THREAD

**Issue by getao** [pytorch/fairseq#377]
I downloaded the pretrained language model and the test set at:

Description | Dataset | Model | Test set(s)
-- | -- | -- | --
Convolutional (Dauphin et al., 2017) | Google Billion Words | download (.tar.bz2) | download (.tar.bz2)

However, I cannot run the model on the test set with the following command:

python $FAIRSEQPY/eval_lm.py $DATADIR --path $MODEL_PATH --sample-break-mode complete --batch-size 1 --tokens-per-sample 3500

My fairseq version is 0.5.0. I also put the dict.txt and test.bin to the $DATADIR but it says 

  File "/home/user1/fairseq-0.5.0/fairseq/tasks/language_modeling.py", line 57, in load_dataset
    raise FileNotFoundError('Dataset not found: {} ({})'.format(split, self.args.data))
FileNotFoundError: Dataset not found: test (fconv_lm)

Moreover, I also want to know how to run the pre-trained language model to score a raw text file.

Could anyone help me?

Thanks.

**Comment by snehilverma41** [comment]
Hey @getao, could you please explain how did you sort out the issue?

**Comment by getao** [comment]
> Hey @getao, could you please explain how did you sort out the issue?

Sorry, I haven't got it worked yet.

**Comment by huihuifan** [comment]
At the current moment, this is not possible. You would need to binarize your raw text file, and then you can use the eval_lm.py script following the example here:

https://github.com/pytorch/fairseq/tree/master/examples/language_model

**Comment by bricksdont** [comment]
@huihuifan Did this get implemented in the meantime? I opened a new issue about scoring text files: https://github.com/pytorch/fairseq/issues/1259

In my opinion, getting scores from language models is an extremely crucial and standard feature, so I'm wondering if this is in fairseq now.
