### ISSUE TITLE
Difference between task translation_multi_simple_epoch and multilingual_translation

### ISSUE THREAD

**Issue by rkoystart** [pytorch/fairseq#3777]
Hi, can anyone let me know what is the difference between the tasks translation_multi_simple_epoch and  multilingual_translation.
And also how both the task differ during the inference.
Thanks in advance.

**Comment by felixkreuk** [comment]
I am also wondering about this. As far as I can see, they differ in the model they use. `translation_multi_simple_epoch` uses a standard transformer model, while `multilingual_translation` uses a `multilingual_transformer` (which means use can use different encoders/decoder for different languages). I will be glad to know other differences between the tasks though.

**Comment by thpun** [comment]
See if https://github.com/pytorch/fairseq/issues/2410#issuecomment-671002353 has the info you want
