### ISSUE TITLE
I got AttributeError: module 'sacrebleu' has no attribute 'compute_bleu'.

### ISSUE THREAD

**Issue by husthkk** [pytorch/fairseq#3779]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
AttributeError: module 'sacrebleu' has no attribute 'compute_bleu'.
#### What have you tried?
CUDA_VISIBLE_DEVICES=0 fairseq-train     data-bin/iwslt14.tokenized.de-en     --arch transformer_iwslt_de_en --share-decoder-input-output-embed     --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0     --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000     --dropout 0.3 --weight-decay 0.0001     --criterion label_smoothed_cross_entropy --label-smoothing 0.1     --max-tokens 4096     --eval-bleu     --eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}'     --eval-bleu-detok moses     --eval-bleu-remove-bpe     --eval-bleu-print-samples     --best-checkpoint-metric bleu --maximize-best-checkpoint-metric

#### What's your environment?

 - fairseq Version 1.0.0a0+9825786
 - PyTorch Version 1.6
 - OS ubuntu 18.04
 - How you installed fairseq: source
 - Build command you used (if compiling from source): pip install --editable ./
 - Python version: 3.8
 - CUDA/cuDNN version: cuda10.2
 - GPU models and configuration: tesla p40
 - Any other relevant information:

**Comment by matthijsvk** [comment]
I think it's version 2.0 of sacrebleu causing issues.
You can do `pip uninstall sacrebleu; pip install sacrebleu==1.5.1`
