### ISSUE TITLE
i get same model if i pass arch as  transformer_wmt_en_de and transformer_wmt_en_de_big

### ISSUE THREAD

**Issue by vigneshmj1997** [pytorch/fairseq#3790]
i installed fairseq from source since  RTX a6000 doesn't support older version of cuda i installed pytorch 1.9  with cuda 11.1 now when i try use transformer_wmt_en_de_big as --arch parameter i am getting transformer base architecture

**Comment by liuwanyue868** [comment]
I have the same issue.I found some things in train.py
args = options.parse_args_and_arch(parser, modify_parser=modify_parser)
The default values of embed_dim, ffn_embed_dim, layers, attention_heads have been given here, so no matter what arch you change, it will not change

**Comment by xu-song** [comment]
+1

**Comment by shawnlimn** [comment]
Setting `delete_default=True` in the following line would do the job for me.
https://github.com/pytorch/fairseq/blob/f34abcf2b64d8659bae7d3eb2e0caf80cf1d6e7d/fairseq/models/transformer/transformer_base.py#L49
