### ISSUE TITLE
wav2vec Unsupervised  scripts/vads.py speed

### ISSUE THREAD

**Issue by ZhaoJiangJie** [pytorch/fairseq#3802]
the ori code to vad the wavs code didn't use multiprocessing:
python scripts/vads.py -r $RVAD_ROOT < /path/to/train.tsv > train.vads
so it really slow to handle massive wavs,i add the multiprocessing_code,and it will use multiprocessing and i found it can work well.

it's the modified mutiprocessing code:
        #!/usr/bin/env python3 -u
        # Copyright (c) Facebook, Inc. and its affiliates.
        #
        # This source code is licensed under the MIT license found in the
        # LICENSE file in the root directory of this source tree.
        
        import argparse
        import sys
        
        from copy import deepcopy
        from scipy.signal import lfilter
        
        import numpy as np
        from tqdm import tqdm
        import soundfile as sf
        import os.path as osp
        
        from multiprocessing import Pool
        from functools import partial
        
        def get_parser():
            parser = argparse.ArgumentParser(description="compute vad segments")
            parser.add_argument(
                "--rvad-home",
                "-r",
                help="path to rvad home (see https://github.com/zhenghuatan/rVADfast)",
                required=True,
            )
        
            parser.add_argument('--ori_file',type=str,help='path to tsv file',required=True)
            parser.add_argument('--vad_file',type=str,help='gene vad file',required=True)
            parser.add_argument('--cpus',type=int,default=40,help='multi processing num of cores')
        
            return parser
        
        
        def rvad(path):
            winlen, ovrlen, pre_coef, nfilter, nftt = 0.025, 0.01, 0.97, 20, 512
            ftThres = 0.5
            vadThres = 0.4
            opts = 1
        
            import speechproc
            path = '/data/2021-06-07/' + path.split('\t')[0]
        
            data, fs = sf.read(path)
            assert fs == 16000, "sample rate must be 16khz"
            ft, flen, fsh10, nfr10 = speechproc.sflux(data, fs, winlen, ovrlen, nftt)
        
            # --spectral flatness --
            pv01 = np.zeros(ft.shape[0])
            pv01[np.less_equal(ft, ftThres)] = 1
            pitch = deepcopy(ft)
        
            pvblk = speechproc.pitchblockdetect(pv01, pitch, nfr10, opts)
        
            # --filtering--
            ENERGYFLOOR = np.exp(-50)
            b = np.array([0.9770, -0.9770])
            a = np.array([1.0000, -0.9540])
            fdata = lfilter(b, a, data, axis=0)
        
            # --pass 1--
            noise_samp, noise_seg, n_noise_samp = speechproc.snre_highenergy(
                fdata, nfr10, flen, fsh10, ENERGYFLOOR, pv01, pvblk
            )
        
            # sets noisy segments to zero
            for j in range(n_noise_samp):
                fdata[range(int(noise_samp[j, 0]), int(noise_samp[j, 1]) + 1)] = 0
        
            vad_seg = speechproc.snre_vad(
                fdata, nfr10, flen, fsh10, ENERGYFLOOR, pv01, pvblk, vadThres
            )
            return vad_seg, data
        
        
        def main():
            parser = get_parser()
            args = parser.parse_args()
        
            sys.path.append(args.rvad_home)
           
            stride = 160
            # lines = sys.stdin.readlines()
            # root = lines[0].rstrip()
        
        
            num_lines = sum(1 for line in open(args.ori_file, 'r', encoding="utf8"))
            rf = open(args.ori_file, 'r', encoding="utf8").readlines()
            wf = open(args.vad_file, 'a+', encoding="utf8")
        
        
            p = Pool(args.cpus)
        
        
            func = partial(rvad)
        
        
            for rslt in tqdm(p.imap(func, rf[1:], chunksize=20),total=num_lines-1):
                vads, wav = rslt
        
                start = None
                vad_segs = []
                for i, v in enumerate(vads):
                    if start is None and v == 1:
                        start = i * stride
                    elif start is not None and v == 0:
                        vad_segs.append((start, i * stride))
                        start = None
                if start is not None:
                    vad_segs.append((start, len(wav)))
        
                print(" ".join(f"{v[0]}:{v[1]}" for v in vad_segs))
                wf.write(" ".join(f"{v[0]}:{v[1]}" for v in vad_segs)+'\n')
        
        
        
            # for fpath in tqdm(lines[1:]):
            #     path = osp.join(root, fpath.split()[0])
            #     vads, wav = rvad(speechproc, path)
            #
            #     start = None
            #     vad_segs = []
            #     for i, v in enumerate(vads):
            #         if start is None and v == 1:
            #             start = i * stride
            #         elif start is not None and v == 0:
            #             vad_segs.append((start, i * stride))
            #             start = None
            #     if start is not None:
            #         vad_segs.append((start, len(wav)))
            #
            #     print(" ".join(f"{v[0]}:{v[1]}" for v in vad_segs))
        
        
        if __name__ == "__main__":
            main()

you can run this code in the terminal:
   python3 scripts/vads.py -r $RVAD_ROOT --ori_file=<your train.tsv path> --vad_file=train.vads

I just want let sb who interested in in wav2vec unspuervided to know you can use multiprocessing and it will save your a lot time to processing data.

**Comment by lsrami** [comment]
@ZhaoJiangJie 
very useful. Can you leave a contact information, I have some other questions about wav2vec-u

**Comment by ChristopheZhao** [comment]
> @ZhaoJiangJie very useful. Can you leave a contact information, I have some other questions about wav2vec-u

thanks for  your attention,I'm not very familiar with wav2vec-u,but I'm interested in this way that use semi-supervised or unsupervised learning in ASR,we can make some discuss about it,my email is 398453241@qq.com ,or zjjsimon@gmail.com is ok.

**Comment by xiabingquan** [comment]
Try this one: https://github.com/snakers4/silero-vad. It's much faster.
