### ISSUE TITLE
ImportError of speech_to_text example

### ISSUE THREAD

**Issue by arabae** [pytorch/fairseq#3809]
## 🐛 Bug
Hi,

Run cmd `python3 ./examples/speech_to_text/prep_librispeech_data.py --output-root ./data`

During the example, the following error occurs when performing the prep_librispech_data.py of speech_to_text:
![image](https://user-images.githubusercontent.com/46676700/130195303-6e822961-6bb1-4b01-82ae-db4935d8df7e.png)

I think we should import "**convert_to_mono**" instead of "_convert_to_mono" to fairseq.data.audio.utils.

https://github.com/pytorch/fairseq/blob/1f7ef9ed1e1061f8c7f88f8b94c7186834398690/examples/speech_to_text/data_utils.py#L17-L19
https://github.com/pytorch/fairseq/blob/1f7ef9ed1e1061f8c7f88f8b94c7186834398690/examples/speech_to_text/data_utils.py#L81

### Environment

 - fairseq Version (e.g., 1.0 or master): 1.0
 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8.8
 - CUDA/cuDNN version: 11.2/8.1

**Comment by maheshmj007** [comment]
This is a bug in code, just change _convert_to_mono in fairseq/examples/speech_to_text/data_utils.py to convert_to_mono, it works fine

**Comment by kahne** [comment]
Thanks for reporting the bug! Please pull our latest code for a fix.
