### ISSUE TITLE
Torchscript EncoderDecoderTransformer

### ISSUE THREAD

**Issue by msaroufim** [pytorch/fairseq#3819]
I'm working with a model that someone else trained - from a fairseq transformer base . The latency on the model is high 200ms and I was hoping to cut that down to 50ms by torcshcripting it but getting issues doing so. Would appreciate any feedback on the right way to do this.
A pt file is loaded using this function from the fairseq codebase
```
self.model = TransformerModel.from_pretrained(
model_path,
checkpoint_file=model_checkpoint_file,
data_name_or_path=data_path
)
```
So I figured I'd JIT trace it and see what happens
```
traced_model = torch.jit.trace(self.model,
(tokenized_sentences[0], result[0][0]["tokens"])) # second argument is just the input to the decoder
```
But this gives me a forward not implemented error
So instead I tried
```
traced_model = torch.jit.trace(self.model.generate,
(tokenized_sentences[0], result[0][0]["tokens"]))
```
But the error I got was
```
AttributeError: trace doesn't support compiling individual module's functions.
Please use trace_module
```
So I tried
```
traced_model = torch.jit.trace_module(self.model.generate,
(tokenized_sentences[0], result[0][0]["tokens"]))
```
And got
`AttributeError: expected torch.nn.Module as the first argument`
Can I transform a GeneratorHubInterface model to a nn.Module and be done? Is this even the right way to do this?

@HamidShojanazeri

**Comment by pkuwudi** [comment]
@msaroufim Have you found a way to lower the infer latency ？ Thanks ahead.

**Comment by WilliamTambellini** [comment]
@msaroufim  the generator interface is a very high interface and probably not exportable as it (at least as today).
What should be exportable are the Transformer models at the back: see:
https://github.com/facebookresearch/fairseq/issues/4459

**Comment by rathnamachary** [comment]
> I'm working with a model that someone else trained - from a fairseq transformer base . The latency on the model is high 200ms and I was hoping to cut that down to 50ms by torcshcripting it but getting issues doing so. Would appreciate any feedback on the right way to do this. A pt file is loaded using this function from the fairseq codebase
> 
> ```
> self.model = TransformerModel.from_pretrained(
> model_path,
> checkpoint_file=model_checkpoint_file,
> data_name_or_path=data_path
> )
> ```
> 
> So I figured I'd JIT trace it and see what happens
> 
> ```
> traced_model = torch.jit.trace(self.model,
> (tokenized_sentences[0], result[0][0]["tokens"])) # second argument is just the input to the decoder
> ```
> 
> But this gives me a forward not implemented error So instead I tried
> 
> ```
> traced_model = torch.jit.trace(self.model.generate,
> (tokenized_sentences[0], result[0][0]["tokens"]))
> ```
> 
> But the error I got was
> 
> ```
> AttributeError: trace doesn't support compiling individual module's functions.
> Please use trace_module
> ```
> 
> So I tried
> 
> ```
> traced_model = torch.jit.trace_module(self.model.generate,
> (tokenized_sentences[0], result[0][0]["tokens"]))
> ```
> 
> And got `AttributeError: expected torch.nn.Module as the first argument` Can I transform a GeneratorHubInterface model to a nn.Module and be done? Is this even the right way to do this?
> 
> @HamidShojanazeri

Is it fixed/resolved the issue?
