### ISSUE TITLE
transformer decode

### ISSUE THREAD

**Issue by vidd-ai** [pytorch/fairseq#3820]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
A question pls for the wav2vec2 and @patrickvonplaten.

I'm exploring using wav2vec2 via transformers and would like to extend the librispeech lexicon file to allow for multiple ways to pronounce words and allow the CTC decoder, if possible, to allow multiple best outcomes: for example: "stay" may sound like "sty" if spoken by an Australian.  What would be the best approach to achieve this?

The model I'm interested in fine-tuning is [this model](https://huggingface.co/facebook/wav2vec2-large-960h-lv60-self).

Thanks very much for your help.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux): Ubuntu 18
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version: python3
 - CUDA/cuDNN version: none
 - GPU models and configuration:
 - Any other relevant information:

**Comment by patrickvonplaten** [comment]
Hey @vidd-ai,

Sorry it seems like your question fell through the cracks.

Could you maybe try to use the forum instead: https://discuss.huggingface.co/
?
