### ISSUE TITLE
Error when running fairseq-generate on Speech-to-text translation example

### ISSUE THREAD

**Issue by longdct2706** [pytorch/fairseq#3821]
## 🐛 Bug

I got the following error when try to run [speech translation example on MuST-C dataset](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/mustc_example.md), in the inference step

```
Traceback (most recent call last):
  File "miniconda3/envs/fairseq/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "fairseq/fairseq_cli/generate.py", line 409, in cli_main
    args = options.parse_args_and_arch(parser)
  File "fairseq/fairseq/options.py", line 148, in parse_args_and_arch
    TASK_REGISTRY[args.task].add_args(parser)
  File "fairseq/fairseq/tasks/speech_to_text.py", line 39, in add_args
    help="max number of tokens in the source sequence",
  File "miniconda3/envs/fairseq/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "miniconda3/envs/fairseq/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "miniconda3/envs/fairseq/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "miniconda3/envs/fairseq/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "miniconda3/envs/fairseq/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "miniconda3/envs/fairseq/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --max-source-positions: conflicting option string: --max-source-positions
```

### To Reproduce

Steps to reproduce the behavior

```
fairseq-train ${DATADIR} \
  --config-yaml config_st.yaml --train-subset train_st --valid-subset dev_st \
  --save-dir ${ST_SAVE_DIR} --num-workers 20 --max-tokens 40000 --max-update 100000 \
  --task speech_to_text --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --report-accuracy \
  --arch s2t_transformer_s --optimizer adam --lr 2e-3 --lr-scheduler inverse_sqrt \
  --warmup-updates 10000 --clip-norm 10.0 --seed 1 --update-freq 1 \
  --log-format simple --log-interval 100  --keep-last-epochs 10 \
  --skip-invalid-size-inputs-valid-test

fairseq-generate ${DATADIR} \
  --config-yaml config_st.yaml --gen-subset tst-COMMON_st --task speech_to_text \
  --path ${ST_SAVE_DIR}/${CHECKPOINT_FILENAME} \
  --max-tokens 50000 --beam 5 --scoring sacrebleu
 ```
 
 `fairseq-train` command works normally, but when I run `fairseq-generate`, it outputs  the above error.

### Expected behavior

`fairseq-generate` perform inference on tst-COMMON set and output BLEU score

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.10
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: A100 GPU
 - Any other relevant information

**Comment by arabae** [comment]
I also had the same problem.
If use comments as in the answer above, it works.
Instead, the cli_main function should not be all commented out.

```
def cli_main():
    parser = options.get_generation_parser()
    '''
    # TODO: replace this workaround with refactoring of `AudioPretraining`
    parser.add_argument(
        '--arch', '-a', metavar='ARCH', default="transformer",
        help='Model architecture. For constructing tasks that rely on '
             'model args (e.g. `AudioPretraining`)'
    )
    '''
    args = options.parse_args_and_arch(parser)
    main(args)
```

**Comment by dreamermary** [comment]
This is a misunderstanding. this punctuation is an ellipsis (.) and not quotes ('), my real comment line in (#).

**Comment by dreamermary** [comment]
> I also had the same problem.
> If use comments as in the answer above, it works.
> Instead, the cli_main function should not be all commented out.
> 
> ```
> def cli_main():
>     parser = options.get_generation_parser()
>     '''
>     # TODO: replace this workaround with refactoring of `AudioPretraining`
>     parser.add_argument(
>         '--arch', '-a', metavar='ARCH', default="transformer",
>         help='Model architecture. For constructing tasks that rely on '
>              'model args (e.g. `AudioPretraining`)'
>     )
>     '''
>     args = options.parse_args_and_arch(parser)
>     main(args)
> ```

I have another issue, I can not reproduce this [example](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/mustc_example.md). Everything is the same, but the result is sad. have you run this example?

**Comment by dreamermary** [comment]
I have another issue, I can not reproduce this asr [example](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/mustc_example.md). Everything is the same, but the result is sad. Have you run this example? My result is normal？@arabae 
```
| INFO | train | epoch 065 | loss 4.903 | nll_loss 3.625 | total 12448.9 | n_correct 6061.96 | ppl 12.34 | accuracy 48.695 | wps 4695.4 | ups 0.38 | wpb 12448.9 | bsz 454.4 | num_updates 31785 | lr 0.000560904 | gnorm 0.44 | clip 0 | train_wall 1216 | gb_free 13.5 | wall 36382
```

`epoch 65：tst-COMMON：WER: 90.57`
`epoch 65：dev：WER: 90.51`
`epoch 65：tst-HE：WER: 87.86`

**Comment by longdct2706** [comment]
@dreamermary I train for 10000 updates only on my custom data and got much better result than your. Have you try to change your learning rate or any other hyper-parameters?

**Comment by dreamermary** [comment]
This is my [LR](https://i.bmp.ovh/imgs/2021/09/53730587d7de5ce9.png), Do you have some good methods about LR or what other params? @longdct2706

**Comment by arabae** [comment]
Like @longdct2706, I did 50 epochs and the results were very good!

```
2021-08-30 11:53:05 | INFO | fairseq_cli.train | begin validation on "dev-clean" subset
2021-08-30 11:53:10 | INFO | dev-clean | epoch 050 | valid on 'dev-clean' subset | loss 2.068 | nll_loss 0.335 | total 2242.45 | n_correct 2160.24 | ppl 1.26 | accuracy 96.334 | wps 58870.2 | wpb 2242.4 | bsz 93.2 | num_updates 30550 | best_loss 2.068
2021-08-30 11:53:10 | INFO | fairseq_cli.train | begin validation on "dev-other" subset
2021-08-30 11:53:15 | INFO | dev-other | epoch 050 | valid on 'dev-other' subset | loss 2.327 | nll_loss 0.628 | total 2259.74 | n_correct 2069.85 | ppl 1.55 | accuracy 91.597 | wps 58449.2 | wpb 2259.7 | bsz 106.1 | num_updates 30550 | best_loss 2.068
```
I used the LibriSpeech dataset and the s2t-transformer-s model.

**Comment by dreamermary** [comment]
I also have run asr on librispeech，the result is ok. But when I run asr on mustc, the result is bad.
@arabae

**Comment by kahne** [comment]
Thanks for reporting this issue! We fixed this by changing `default="transformer"` to `default="wav2vec2"`. Please pull the latest code for the fix. (`--max-source-positions` was supposed to be a task-level argument and included in the `speech_to_text` task. However, it's recently added as a model-level argument to `transformer` and hence duplication happens when using `transformer` and `speech_to_text` at the same time).

**Comment by dearchill** [comment]
> I also have run asr on librispeech，the result is ok. But when I run asr on mustc, the result is bad.
> @arabae

I have a similar question, I trained a chinese asr model on CoVoST2, and the result is extremely bad. Is it possibly because the dataset is quite small and the model parameters are large? I also replace the _s2t_transformer_s_ model arch with _s2t_transformer_xs_, but no improvement, seems like it couldn't produce a single same word comparing with the reference test sentence. I'm curious about that. I will train an English asr model instead and follow the update here.

**Comment by dearchill** [comment]
By the way, did you solve that? @dreamermary

**Comment by dreamermary** [comment]
> By the way, did you solve that? @dreamermary

add me QQ ，1341584939
