### ISSUE TITLE
How to reproduct the result of "Fully Non-autoregressive Neural Machine Translation: Tricks of the Trade"

### ISSUE THREAD

**Issue by wangqi1996** [pytorch/fairseq#3824]
The paper "Fully Non-autoregressive Neural Machine Translation: Tricks of the Trade" claim that the code is released in "https://github.com/pytorch/fairseq/tree/master/examples/nonautoregressive_translation", however, I cannot find the code for the combination of CTC and GLAT.

**Comment by stephanpeitz** [comment]
There is an open issue already: https://github.com/pytorch/fairseq/issues/3666
