### ISSUE TITLE
Joint Speech Text Training for the IWSLT21 Data Preparation

### ISSUE THREAD

**Issue by KangsanKim07** [pytorch/fairseq#3837]
Thank you for sharing wonderful codes!

I was trying to execute speech to text joint translation following [Joint Speech Text Training for the 2021 IWSLT multilingual speech translation](https://github.com/pytorch/fairseq/blob/master/examples/speech_text_joint_to_text/docs/iwslt2021.md).
In the instruction, it said I should follow the data preparation for mTEDx dataset which uses fbank80.
But I found wav2vec2.0 doesn't use fbank80, but it uses raw audio as an input.
I think you need to change that part in the instructions.

And is there any codes for data preparation for joint speech text training for the IWSLT2021?
It would be a great help if you share your codes.

**Comment by alexeib** [comment]
@yuntang could you please look?

**Comment by yuntang** [comment]
@KangsanKim07 Thanks for reporting this. We will update the data preparation part accordingly.

**Comment by yuntang** [comment]
Hi, @KangsanKim07 an new option (--use-audio-input) is added for data preparation scripts
https://github.com/pytorch/fairseq/blob/d974c709bf57cf494738a824a1597e1886bebb7a/examples/speech_to_text/prep_mtedx_data.py#L261

Please update your fairseq and prepare the tsv file with option --use-audio-input option.
