### ISSUE TITLE
Hubert finetuning hyperparameters

### ISSUE THREAD

**Issue by cywang97** [pytorch/fairseq#3843]
## ❓ Questions and Help
Hi, I try to finetune the released pretrained Hubert model with the config examples/hubert/config/finetune/base_10h.yaml and then decoding with 4-gram LM, but I cannot reproduce the number in the paper.
Could you release the finetuning hyperparameters to reproduce the reported results in https://arxiv.org/abs/2106.07447?
Thanks very much.

**Comment by Diamondfan** [comment]
I met the same problem recently. Did you reproduce the number eventually?
