### ISSUE TITLE
The shell script examples/speech_to_text/data_utils.py import fairseq.data.audio.audio_utils error.

### ISSUE THREAD

**Issue by Cuihao1208** [pytorch/fairseq#3845]
## 🐛 Bug

I got the following error when try to run [S2T Example: Speech Recognition (ASR) on LibriSpeech](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/librispeech_example.md#s2t-example-speech-recognition-asr-on-librispeech). Then error:
```
Traceback (most recent call last):
  File "examples/speech_to_text/prep_librispeech_data.py", line 14, in <module>
    from examples.speech_to_text.data_utils import (
  File "/fairseq-master/examples/speech_to_text/data_utils.py", line 17, in <module>
    from fairseq.data.audio.audio_utils import (
ImportError: cannot import name '_convert_to_mono' from 'fairseq.data.audio.audio_utils' (/fairseq-master/fairseq/data/audio/audio_utils.py)
```

### To Reproduce

Steps to reproduce the behavior :
`python examples/speech_to_text/prep_librispeech_data.py 
  --output-root ${LS_ROOT} --vocab-type unigram --vocab-size 10000`

#### Code sample

line 17-19 in examples/speech_to_text/data_utils.py:
```
from fairseq.data.audio.audio_utils import (
    _convert_to_mono, _get_kaldi_fbank, _get_torchaudio_fbank
)
```

The func **"_convert_to_mono"** in fairseq/data/audio/audio_utils.py is deleted on 28 Jul:
[Add speech/text joint training for speech to text task](https://github.com/pytorch/fairseq/commit/7ca95a66d64411deea49cb8710195ed2e0699f0a#diff-b9288c5137e5626007e93a4fe8893bd11e307c4c47fa5f3610cb7773db6f979c)

### Expected behavior

Hope to update related references when updating a script.

### Environment

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by arabae** [comment]
I also inquired about this issue. (https://github.com/pytorch/fairseq/issues/3809)
For a simple fix, replace "_convert_to_mono" with "convert_to_mono".

**Comment by kahne** [comment]
Thanks for reporting the bug! Please pull our latest code for a fix.
