### ISSUE TITLE
Lack of args of encoder While Using examples/RoBERTa to PreTrain RoBERTa on custom datasets

### ISSUE THREAD

**Issue by Why1005** [pytorch/fairseq#3850]
I tried to pretrain Roberta on my datasets by examples/roberta/README.pretraining.md
When excuting cmd : 

DATA_DIR=data-bin/wikitext-103

fairseq-hydra-train -m --config-dir examples/roberta/config/pretraining \
--config-name base task.data=$DATA_DIR

It reports bug below:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  ...
  File "/fairseq/fairseq/models/roberta/model.py", line 465, in build_encoder
    encoder = TransformerEncoder(args, dictionary, embed_tokens)
  File "/fairseq/fairseq/models/transformer/transformer_encoder.py", line 333, in __init__
    TransformerConfig.from_namespace(args),
  File "/fairseq/fairseq/models/transformer/transformer_config.py", line 297, in from_namespace
    config.encoder = EncDecBaseConfig(**args.encoder)
TypeError: type object argument after ** must be a mapping, not NoneType

Seems that it doesn't specify the args of encoder. How to deal with the situation?

Thanks!

**Comment by RuABraun** [comment]
Hi! What was the fix for this? Guessing there was an additional config var to set?

edit: nvm saw your discussion [here](https://github.com/pytorch/fairseq/issues/3844)
