### ISSUE TITLE
Too many states in FairseqLM decoder?

### ISSUE THREAD

**Issue by TaridaGeorge** [pytorch/fairseq#3856]
## ❓ Questions and Help

This question is about the FairseqLM class from : https://github.com/pytorch/fairseq/blob/3c4a8e41559fa50b6c907fbefa1dab55d57bda5c/examples/speech_recognition/w2l_decoder.py

I'm using the fairseqlm for inference and I've noticed that sometimes the memory goes really high. I suspect that the problem is in the LexiconDecoder. I'm not that familiar with C++ so I can't say for sure but from my findings I've noticed that the `score` method from the FairseqLM is called a lot (sometimes, for specific audio files). For an audio file of 21.75 seconds the `self.states` list holds about 10_001 states. Is this ok?

#### What is your question?
Is it ok to have 10_001 states decoded with FairseqLM for an audio file of 21.75 seconds duration?

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 1.0.0a0+c8a0659
 - PyTorch Version (e.g., 1.0): 1.9
 - OS (e.g., Linux): Linux Mint
 - How you installed fairseq: source
 - Python version: 3.9.6
 - Any other relevant information: CPU
![Selection_791](https://user-images.githubusercontent.com/1283959/132685100-0d5e0e7d-8e65-424b-9d23-05e3ecaabf38.png)

**Comment by RuABraun** [comment]
Yeah that looks very normal. You could reduce it by lowering the beam.

**Comment by TaridaGeorge** [comment]
Ok. Thank you!
