### ISSUE TITLE
How to add new tokens while finetuning a pretrained model?

### ISSUE THREAD

**Issue by nikhiljaiswal** [pytorch/fairseq#3857]
Hi, I want to finetune a pre-trained model on a custom dataset that contains some new tags for e.g <sep>, etc. These tags were not present when I trained the spm model while training the base model. Hence such tags are not present in the spm vocabulary list as well as in the dictionary. How can we add these new tokens to the spm vocab as well as dictionary and initialize the tokenizer embeddings?

I think this functionality is available in huggingface as can be seen in the issue below. Any leads for fairseq?

https://github.com/huggingface/transformers/issues/1413

**Comment by SouthWindShiB** [comment]
Hey, I have meet the problem too.

Have you finished this issue?

**Comment by nikhiljaiswal** [comment]
no not yet. @SouthWindShiB any leads near you?

**Comment by nikhiljaiswal** [comment]
@ALL, any help on this?
