### ISSUE TITLE
relationship between train, distribution train and multiprocessing train

### ISSUE THREAD

**Issue by gaopeng-eugene** [pytorch/fairseq#390]

**Comment by gaopeng-eugene** [comment]
As the name implied, can you clarify the relationship between train, distribution train and multiprocessing train. It seems that you can do distribution train with train.py.

**Comment by myleott** [comment]
train.py is the main entry point for all training. Then, depending on the number of GPUs and provided arguments we will either run:
- main(), defined in train.py, which assumes only a single process and GPU
- multiprocess_main(), defined in multiprocess_train.py, which will spin up N processes on the local machine and train on N GPUs
- distributed_main(), defined in distributed_train.py, which will initialize distributed training on N GPUs across M nodes

That code appears at the bottom of train.py here:
https://github.com/pytorch/fairseq/blob/50591a29736110e405f4641d77e2b98a3cf6bd2a/train.py#L346-L359

Generally you just need to run train.py though. Instructions for distributed training can be found in the docs: https://fairseq.readthedocs.io/en/latest/getting_started.html#distributed-training
