### ISSUE TITLE
distribution training on one machine with multiple GPU

### ISSUE THREAD

**Issue by gaopeng-eugene** [pytorch/fairseq#391]

**Comment by gaopeng-eugene** [comment]
Can you tell me how to do distribution on one machine with multi gpu?

**Comment by frankang** [comment]
By default the code uses all available GPUs on your machine. You can customize it with the CUDA_VISIBLE_DEVICES env.
` CUDA_VISIBLE_DEVICES=0,1,2... python train.py ...`

**Comment by gaopeng-eugene** [comment]
Hi, thank you for your response. However, I think multi gpu training and one machine distribution training is different. In one machine distribution training, each gpu will have one process.

**Comment by gaopeng-eugene** [comment]
It seems that the current version support distribution directly. Thank you for your excellent code.
