### ISSUE TITLE
lstm.py IndexError when encoder_layers is NOT EQUAL to decoder_layers

### ISSUE THREAD

**Issue by vineetk1** [pytorch/fairseq#394]
**FILE**: [fairseq/models/lstm.py](https://github.com/pytorch/fairseq/blob/master/fairseq/models/lstm.py)
IndexError occurs in each of the following lines 365 and 366 when  encoder_layers is NOT EQUAL to decoder_layers:
`            prev_hiddens = [encoder_hiddens[i] for i in range(num_layers)]
`
`            prev_cells = [encoder_cells[i] for i in range(num_layers)]
`
It seems to make sense that encoder_layers must be EQUAL to decoder_layers because the hidden and cell states of the encoder LSTM are written into the hidden and cell states of the decoder LSTM.
A solution is to combine encoder_layers and decoder_layers into encoder_decoder_layers. Then the LSTMs of encoder and decoder will always have the same number of layers.

**Comment by myleott** [comment]
Just going with an assert for now, since it's easier to remove if we later add support for non-matching numbers of layers.
