### ISSUE TITLE
How to preprocess a new dataset ?

### ISSUE THREAD

**Issue by Sumegh-git** [pytorch/fairseq#411]
I have 2 files separate each having around 20k sentences in respective languages . Since , there is no documentation to explain how and in which format should i pre-process the dataset so as to run the training , i was having some difficulty .

Can anyone help with the pre-processing instructions ? 

Thanks.

**Comment by huihuifan** [comment]
We provide example commands: https://github.com/pytorch/fairseq/tree/master/examples/translation
