### ISSUE TITLE
ArrayIndex out of bounds in ordered_indices(self)

### ISSUE THREAD

**Issue by Sumegh-git** [pytorch/fairseq#413]
Can someone please explain what `ordered_indices()` in `language_pair_dataset.py` is doing? 
Im training with a new dataset when i created the valid,train and test data . Then ran `preprocess.py` to create dict and bin data . 

Then after running train.py i'm getting an error like 
` return indices[np.argsort(self.src_sizes[indices.any()], kind='mergesort')]
IndexError: index 2220 is out of bounds for axis 0 with size 1
`
ALSO , i have put that .any() after indices , otherwise it was showing error.

Thanks.

**Comment by myleott** [comment]
I don’t think putting `.any()` there is the right fix, what was the error you saw before changing that?

`ordered_indices` is meant to give a list of dataset indices (sentence IDs) that is sorted by size. By default we sort by source length and break ties based on target length.

**Comment by Sumegh-git** [comment]
Before that , i was getting `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
`

**Comment by myleott** [comment]
Can you paste the whole exception with traceback?

**Comment by Sumegh-git** [comment]
This is the whole exception before i changed anything:
`Traceback (most recent call last):
  File "train.py", line 360, in <module>
    main(args)
  File "train.py", line 74, in main
    shard_id=args.distributed_rank,
  File "/home/others/17EC30042/fairseq/fairseq/tasks/fairseq_task.py", line 96, in get_batch_iterator
    indices = dataset.ordered_indices()
  File "/home/others/17EC30042/fairseq/fairseq/data/language_pair_dataset.py", line 223, in ordered_indices
    indices = indices[np.argsort(self.tgt_sizes[indices], kind='mergesort')]
IndexError: index 18268 is out of bounds for axis 1 with size 18249
`

**Comment by myleott** [comment]
Interesting, you said you’re doing LM training right? For LM there’s only a “source” sentence but no “target,” but that exception is related to target lengths.

When you preprocessed the data did you use the `--only-source` flag?

**Comment by Sumegh-git** [comment]
No , i am doing Translation training only .

**Comment by myleott** [comment]
How many sentences are in your datasets? That exception sugguests somehow the `tgt_lengths` array is smaller than `len(self)`...

Can you add some debug messages to `ordered_indices`:
```
print(“Num. pairs in dataset:”, len(self))
print(“Num. targets in dataset:”, len(self.tgt_sizes))
```

**Comment by Sumegh-git** [comment]
Yes , true ...    I don't know how this happened .  It is less actually than `len(self)`

**Comment by JJumSSu** [comment]
Can you give me explanation why that index error occured or any solution to handle that error? @Sumegh-git

**Comment by Rabailkamboh** [comment]
hey! i am having the same probelm and unable to solve it!!
