### ISSUE TITLE
Questions about training a transformer model with different corpus

### ISSUE THREAD

**Issue by xyx-x** [pytorch/fairseq#420]
I encountered difficulties in training transformer with different datasets. I used the WMT de-en parallel corpus to train a transformer model with fairseq. And there is no problem in training with de-en dataset  except the Paracrawl de-en dataset. The Paracrawl de-en dataset is poor in quality.  There exists an oom(out of memory) bug, and is this related to the quality of dataset?

**Comment by huihuifan** [comment]
The Paracrawl dataset was extensively filtered before being used: https://arxiv.org/pdf/1806.00187.pdf

the OOM- please provide more detail of where there is an OOM.

**Comment by myleott** [comment]
Also, in the case of OOM, you can try lowering the batch size (`--max-tokens`). The maximum possible batch size depends on how much GPU RAM you have, the model architecture, dictionary size, etc.

**Comment by huihuifan** [comment]
@xyx-x , hope the above helped. please re-open if this did not fix your problem.
