### ISSUE TITLE
Initialize only encoder decoder weights from a pre-trained model

### ISSUE THREAD

**Issue by ashim95** [pytorch/fairseq#429]
I am trying to fine tune a seq2seq translation model for domain adaptation. I understand I can fine tune the whole model by restoring from the checkpoint file (keeping the vocabularies same). But I only want to initialize some of the parameters (for example only encode-decoder weights) from the pre-trained model. How can this be done in fairseq? 

Also, is it possible to initialize weights from a numpy array using `torch.from_numpy()` and If not, what part of the code do I need to change to accomplish this?

Thanks a lot for your help.

**Comment by huihuifan** [comment]
Please re-open if you have issues, otherwise closing based on the examples Myle provided

**Comment by skeshaw** [comment]
I would like to reopen this issue.
It seems the issue at hand was different - how to load the model weights, not those of the embeddings? Currently, I am experiencing the same problem and would like to know if there is some existing solution.
To summarize, I would allow word embeddings to initialize in the usual (say, random) way, but I would like to reuse the other learned parameters in the model as a starting point for my training.
