### ISSUE TITLE
Invalid syntax with preprocess.py

### ISSUE THREAD

**Issue by lengockyquang** [pytorch/fairseq#443]
Hi, i'm trying to follow the fairseq [tutorial](https://fairseq.readthedocs.io/en/latest/tutorial_classifying_names.html) and ran to this error in the preprocess data step: 
File "preprocess.py", line 306
    base = f"{args.destdir}/{output_prefix}"
                                           ^
SyntaxError: invalid syntax
I'm using Python 3.5.2, PyTorch 1.0.0. I don't know exactly what happened. Maybe there're something wrong with my Python version

**Comment by frankang** [comment]
f-strings is a feature introduced in python 3.6.
![image](https://user-images.githubusercontent.com/16100899/51102801-5160e900-181b-11e9-8818-adbf6d950e4c.png)

**Comment by lengockyquang** [comment]
oh thks,  i forgot to check python version requirement.
