### ISSUE TITLE
Group binaries in "bin" dir and install them globally with setup.py

### ISSUE THREAD

**Issue by davidecaroselli** [pytorch/fairseq#450]
Hi fairseq team!

I would like to make a pull-request aiming to give fairseq a group of globally callable binaries. Just like tensro2tensor's `t2t-train` or `t2t-datagen`, I think that fairseq should expose its binaries like: `fairseq-datagen`, `fairseq-train`, `fairseq-lmeval`, `fairseq-generate` and `fairseq-decode`. This is also a fundamental step towards installable `pip` wheel.

So my idea is to:

1. Create a `bin` directory at top-level.
2. Move `eval_lm.py`, `preprocess.py`, `train.py`, `generate.py` and `interactive.py` into `bin/fairseq-lmeval`, `bin/fairseq-datagen`, `bin/fairseq-train`, `bin/fairseq-generate` and `bin/fairseq-decode`
3. Configure `setup.py` to make it install bins in user bin folder (I think usually `/usl/local/bin`)
4. For the sake of back-compatibility, replace top-level scripts (`eval_lm.py`, `preprocess.py`, ...) with scripts that print a deprecation warning and then run the correct `bin` script.

The result would be a much more integrated `fairseq` installation, for example I can run a training no matter from with the command:
```bash
fairseq-train  data-bin --save-dir ...
```

Are you interested in this feature?

**Comment by myleott** [comment]
Fixed by https://github.com/pytorch/fairseq/commit/829bd8ce5fc336991c828f178ac5f231250ef77d
