### ISSUE TITLE
Bug in check_size() function for multilingual translation (confirmed)

### ISSUE THREAD

**Issue by frankang** [pytorch/fairseq#451]
The current code for the dict type position filtration part uses the "<=" sign to compare data sizes in two tuples. However, direct compare of two tuples usually may not behave as expected in python. See: [https://stackoverflow.com/questions/5292303/how-does-tuple-comparison-work-in-python](url)
```
        elif isinstance(max_positions, dict):
            idx_size = size_fn(idx)
            assert isinstance(idx_size, dict)
            intersect_keys = set(max_positions.keys()) & set(idx_size.keys())
            return all(idx_size[key] <= max_positions[key] for key in intersect_keys)
```
So the above criterion will not filter sentence pair which possess a qualified source sentence and an unqualified target sentence. i.e., (190, 210) <= (200, 200) returns True.

my fix code for this part is:
```
        elif isinstance(max_positions, dict):
            idx_size = size_fn(idx)
            assert isinstance(idx_size, dict)
            intersect_keys = set(max_positions.keys()) & set(idx_size.keys())
            return all(
                            all( a is None or b is None or a <= b for a, b in zip(idx_size[key], max_positions[key])) 
                            for key in intersect_keys )
```
Can I provide a PR for this bug?  It will also include the fix for this issue https://github.com/pytorch/fairseq/issues/441

**Comment by myleott** [comment]
Yep that'd be great, thanks!

**Comment by huihuifan** [comment]
Closing issue as there is now a PR. Thank you for noticing this bug!
