### ISSUE TITLE
How to get the attention matrix during the training process

### ISSUE THREAD

**Issue by nicolabertoldi** [pytorch/fairseq#456]
Is it possible to get the attention matrix during the training process?
Is this information already accessible?

**Comment by huihuifan** [comment]
The attention matrix can be accessed: https://github.com/pytorch/fairseq/blob/master/fairseq/models/transformer.py#L520 for example (though it depends on the model, whether you want self-attention or encoder-decoder attention, whether you want to get the attn for one head, averaged across all heads, one layer, averaged across all layers, etc.). Usually I index to get what I want, and then you can see it during training in various ways. Usually I look at an intermediate checkpoint, but you could save this matrix as well, etc.
