### ISSUE TITLE
Link of WritingPrompts data is wrong

### ISSUE THREAD

**Issue by pyiaal** [pytorch/fairseq#457]
Hi,

I wanted inform you of that the link to the WritingPrompts dataset on the section Pre-trained Models is literally misleading (it leads you to paper itself on archive). Will it be fixed?

Thank you.

**Comment by huihuifan** [comment]
You can download the data here: https://github.com/pytorch/fairseq/tree/master/examples/stories

We are planning to restructure to highlight this examples section, where all of the scripts are. I believe the dataset link in the pre-trained models was supposed to describe the dataset, but perhaps we can link it directly to examples.
