### ISSUE TITLE
Example for continuous input to text output mapping

### ISSUE THREAD

**Issue by sameerkhurana10** [pytorch/fairseq#475]
Hi,

is it possible to add a minimal example of sequence to sequence learning for continuous input to text output, such as in Image captioning or speech-to-text transcription? Like in OpenNMT-py

This wonderful toolkit can be used to build seq2seq speech recognition systems. A minimal example of mapping continuous vectors to text output would be very helpful.

**Comment by ShigekiKarita** [comment]
I'm making such examples at https://github.com/ShigekiKarita/fairseq-speech

**Comment by krasserm** [comment]
See https://github.com/pytorch/fairseq/issues/759#issuecomment-559406973
