### ISSUE TITLE
Replicate Fig8 of Hierachical SG

### ISSUE THREAD

**Issue by bepierre** [pytorch/fairseq#476]
Hey!

I would be interested to know which weights exactly I should average to do something similar to the Figure 8 in the paper[ Hierarchical Neural Story Generation](https://arxiv.org/pdf/1805.04833.pdf).

![image](https://user-images.githubusercontent.com/13301237/51788040-a389fe80-2179-11e9-97f7-b53e6b8889e0.png)

Thanks a lot!

**Comment by huihuifan** [comment]
For figure 8, we looked at the two independent gates learned to gate the
pretrained and training models. The averaging is over the gate’s
dimensionality at that time step.

**Comment by huihuifan** [comment]
Sorry for missing this. Yes, that is correct.

**Comment by huihuifan** [comment]
Closing, but let us know if you have any more questions please!
