### ISSUE TITLE
Bug in shebang for Linux

### ISSUE THREAD

**Issue by davidecaroselli** [pytorch/fairseq#477]
The shebang line in fairseq binaries are broken in Linux:
```bash
#!/usr/bin/env python3 -u
```

The `command [arg]` syntax is not valid on Linux, as already explained here for example: [StackOverflow - Shebang line with `#!/usr/bin/env command --argument` fails on Linux
](https://unix.stackexchange.com/questions/63979/shebang-line-with-usr-bin-env-command-argument-fails-on-linux).

I'm creating a PR together with feature discussed in #450 to solve this.

**Comment by frankang** [comment]
I'm just curious that the in link you posted above mentioned that an error will be raised when executing that script. 
` /usr/bin/env: ruby --verbose: No such file or directory`
however I didn't see error output when run fairseq with `#!/usr/bin/env python3 -u `
How could this happen if shebang interpret the argument as "python3 -u"

**Comment by myleott** [comment]
Yeah, I also have not observed any issues with this. @davidecaroselli, does it cause that error for you?

We added the `-u` to make Python's output unbuffered, since we log training progress to stdout. It's not critical to have it, but seemed to improve logging latency.

**Comment by davidecaroselli** [comment]
In order to replicate the bug (tested on Ubuntu 16.04 and 18.04):

1. Create a simple "hello world" python script:
```bash
echo -e '#/usr/bin/env python3 -u python3 -u\nprint("hello world")' > test
```
2. Try the script:
```bash
$ python3 test
hello world
```
3. Now make the script executable:
```bash
chmod +x test
```
4. Try to run the script:
```bash
$ ./test 
/usr/bin/env: ‘python3 -u’: No such file or directory
```

**Comment by myleott** [comment]
Fixed by https://github.com/pytorch/fairseq/commit/829bd8ce5fc336991c828f178ac5f231250ef77d
