### ISSUE TITLE
KeyError: nll_loss in multilingual_transaltion

### ISSUE THREAD

**Issue by AyaNsar** [pytorch/fairseq#479]
I am trying to train a multi-language-source model using the multilingual translation task, it seems to start fine with given parameters, but as soon as it gets to the first epoch, it generates the following:

epoch 001:   0%|                                                                                                                                                                                                  | 0/793 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 414, in <module>
    main(args)
  File "train.py", line 100, in main
    train(args, trainer, task, epoch_itr)
  File "train.py", line 135, in train
    log_output = trainer.train_step(samples)
  File "~\fairseq\trainer.py", line 233, in train_step
    logging_outputs, self.criterion
  File "~\fairseq\tasks\multilingual_translation.py", line 249, in aggregate_logging_outputs
    flat_logging_output['nll_loss'] = sum_over_languages('nll_loss')
  File "~\fairseq\tasks\multilingual_translation.py", line 240, in sum_over_languages
    return sum(logging_output[key] for logging_output in agg_logging_outputs.values())
  File "~\fairseq\tasks\multilingual_translation.py", line 240, in <genexpr>
    return sum(logging_output[key] for logging_output in agg_logging_outputs.values())
KeyError: 'nll_loss'

Can anyone tell me what the problem is?

**Comment by AyaNsar** [comment]
I set the criterion to label_smoothed_cross_entropy and it worked..so far

**Comment by myleott** [comment]
Thanks, this is a corner case with multilnigual_translation.py. I'll submit a fix, but label_smoothed_cross_entropy should work for now.

**Comment by RobotGF** [comment]
@myleott when train translation task with cross_entropy and adafactor, I got KeyError exp_avg

**Comment by rbrugaro** [comment]
When training translation task with cross_entropy (instead of label_smoothed_cross_entropy) I got the  KeyError: 'nll_loss'. Error seems related to @AyaNsar . @myleott is the corner case with multilingual translation still unfixed?
