### ISSUE TITLE
How to replicate "Time to Train Facebook’s Fairseq" data: 1.5 Days using DGX-2

### ISSUE THREAD

**Issue by asispatra** [pytorch/fairseq#486]
I have found that "Time to Train Facebook’s Fairseq" is done in 1.5 Days using DGX-2 system.
https://devblogs.nvidia.com/tensor-core-ai-performance-milestones

Can anyone help me to replicate the data?

**Comment by myleott** [comment]
That is a slightly older reference, based on the convolutional model architecture (fconv) in fairseq. Instructions for running that model are here: https://github.com/pytorch/fairseq/tree/master/examples/translation

Our more recent work trains state-of-the-art Transformer models in an hour. Details for reproducing that work can be found here: https://github.com/pytorch/fairseq/tree/master/examples/scaling_nmt and in our paper: https://arxiv.org/abs/1806.00187.

**Comment by asispatra** [comment]
In this paper, "Scaling Neural Machine Translation", The system used DGX-1 with V100 GPUs. 
What is the memory size of these GPUs?

**Comment by myleott** [comment]
16GB

**Comment by asispatra** [comment]
Is there any suggestion for 32GB V100 gpus to reduce the training time?

**Comment by myleott** [comment]
See my reply in the other thread: https://github.com/pytorch/fairseq/issues/491
