### ISSUE TITLE
What is wall and train_wall in the output log?

### ISSUE THREAD

**Issue by asispatra** [pytorch/fairseq#493]
In the scalling_nmt example training output log there is two column named "wall" and "train_wall". 
What does these two column means? How this is related to training time?

**Comment by myleott** [comment]
"wall" is the total time, including time spent in validation, saving checkpoints to disk, etc. In the paper we reported "train_wall," which is just the time spent in training.

**Comment by asispatra** [comment]
Thanks @myleott :)
