### ISSUE TITLE
Did you have any plan to implement the Evolved Transformer?

### ISSUE THREAD

**Issue by ghost** [pytorch/fairseq#496]
Dear developers:
      Did you have any plan to implement the [Evolved Transformer](https://arxiv.org/abs/1901.11117)?

**Comment by huihuifan** [comment]
At this moment, no, but if you look at the architecture diagram of the evolved transformer, we have the building blocks for it already in fairseq/PyTorch- you need to change the TransformerDecoderLayer to modify the modules. For example, the GatedLinearUnit and the Separable Convolution can be added easily. To get the 16 attention heads, just change the number of heads parameter. We also welcome pull requests if you implement!

**Comment by HuangZhanPeng** [comment]
@huihuifan Thank you for your response! I will take a try
