### ISSUE TITLE
Why using the TBC format for the light convolutions? 

### ISSUE THREAD

**Issue by vlievin** [pytorch/fairseq#525]
Hi, I am not sure to get all the reasons that motivated you to use the TBC format instead of the traditional BCT format in the lightconv and dynamic conv implementations. I would like to have a better understanding before starting important refactoring in my project (to make it compatible) . Thanks in advance for your help!

**Comment by myleott** [comment]
I believe we provide a BCT implementation as well: https://github.com/pytorch/fairseq/blob/master/fairseq/modules/lightweight_convolution.py#L18-L20

While I didn't profile the lightconv implementation, for the original convolutional model we found TBC results in fewer transpose/contiguous calls (esp. relating to the attention mechanism) and was therefore faster.

**Comment by vlievin** [comment]
Thanks for the explanation! Indeed, I had seen the vanilla implementation, hence my curiosity :)

**Comment by simpleoier** [comment]
Hi @myleott , I don't quite understand your reply. Can you explain in more detail about why TBC implementation results in fewer transpose/contiguous calls?  Thanks.
