### ISSUE TITLE
fairseq-interactive for Language Model

### ISSUE THREAD

**Issue by josephch405** [pytorch/fairseq#526]
I trained a new language model and was trying to use it with fairseq-interactive (since in the docs LM is listed as compatible with interactive), but it seems like a few parts are still unimplemented. Is this something in the works or can I try making a PR for this?

**Comment by myleott** [comment]
I have this implemented, I can merge it soon.

**Comment by myleott** [comment]
Fixed in https://github.com/pytorch/fairseq/pull/528.
