### ISSUE TITLE
Curriculum learning

### ISSUE THREAD

**Issue by noe** [pytorch/fairseq#533]
Option `--curriculum` was introduced in 820f796fd9f67014bf933bc25b0943c70d2d539d (October 2017) and removed in 4fa8760e9a1f93320007aa9060e7c60fd2e90cc7 (April 2018).

It seems useful for some architectures to be able to feed shorter sequences at the begining and introduce longer sequences progressively.

Is there any way to achieve this effect with other options?

**Comment by myleott** [comment]
Added back in #554

**Comment by noe** [comment]
Great, thanks!
