### ISSUE TITLE
Missing mandatory parameter for lightconv language model (patch attached)

### ISSUE THREAD

**Issue by bobpepin** [pytorch/fairseq#536]
Hi,
while playing around with language modeling, I noticed that the lightconv language model is lacking the decoder_conv_dim command line argument required by the Decoder. This prevents it from being used. One-line patch attached which mimics the behaviour of the translation model.

[fairseq_dec_conv_dim.diff.txt](https://github.com/pytorch/fairseq/files/2909057/fairseq_dec_conv_dim.diff.txt)

**Comment by myleott** [comment]
This has been fixed, thanks!
