### ISSUE TITLE
How to specify GPU when ensemble？

### ISSUE THREAD

**Issue by niutransWZY** [pytorch/fairseq#539]
How to specify GPU when ensemble？Can I use multiple GPUs?

**Comment by karlgeorge** [comment]
try this:
`export CUDA_VISIBLE_DEVICES=gpuid1,gpuid2,gpuid3 `

**Comment by niutransWZY** [comment]
> try this:
> `export CUDA_VISIBLE_DEVICES=gpuid1,gpuid2,gpuid3`

This method only uses the specified first GPU

**Comment by edunov** [comment]
It is not supported currently. Generation is always done on one GPU.  
I don't see why it can not be implemented, but what is your use case?  

If you need to generate a lot of translations I find it easier to do data parallel approach, that is to split data into multiple chunks and run separate generate.py for each chunk.

**Comment by huihuifan** [comment]
Closing for now following Sergey's suggestions.
