### ISSUE TITLE
transformer prefers aligning the hypothesis words to words in the end of the source sentence 

### ISSUE THREAD

**Issue by gyn0806** [pytorch/fairseq#552]
I'm doing a text-editing task, using the transformer architecture in fairseq, I found that transformer prefer aligning  the hypothesis words to words in the end of the source sentence.

There are 2  examples of the alignment, we can see that many words in the hypothesis sentence  are aligned to the words in the end of the source sentence , like '.', '<eos>', and I don't know why, though the quality of the hypothesis is not bad.

Source : Stuart[0] Parker[1] is[2] the[3] manager[4] of[5] A.F.C.[6] Blackpool[7] ,[8] and[9] plays[10] for[11] Blackburn[12] Rovers[13] F.C.[14]<eos>[15]
Hypothesis : Stuart Parker is the manager of pilgrBlackpool . _SPLIT_ He plays for Blackburn Rovers F.C. .
Possibility   -0.0001 -0.0004 -0.0819 -0.1044 -0.0062 -0.0836 -4.3644 -0.0027 -0.2883 -0.0383 -0.5328 -0.8308 -0.0894 -0.0027 -0.0003 -0.0051 -0.0683 -0.0586
Alignment: 0 1 15 15 15 15 15 7 15 15 1 15 15 12 13 15 15 15

Source :  AIDS[0] journal[1] is[2] from[3] the[4] United[5] Kingdom[6] where[7] the[8] leader[9] is[10] David[11] Cameron[12] .[13] <eos>[14]
Hypothesis :  AIDS journal is from the United Kingdom . _SPLIT_ The leader is David Cameron .
Possibility :  -0.0012 -0.0005 -0.0864 -0.1356 -0.0959 -0.0439 -0.0244 -0.3737 -0.0397 -0.3282 -0.0164 -0.2280 -0.0093 -0.0004 -0.0817 -0.0589
Alignment : 0 1 13 13 13 5 6 13 13 13 9 13 11 12 13 14

**Comment by myleott** [comment]
Sorry, not sure how to help without more information (e.g., dataset, commands you ran, etc.). Closing for now, please open a new issue following one of the new Issue templates if needed, thanks!
