### ISSUE TITLE
Implementation of Self-Attention with Relative Position Representations

### ISSUE THREAD

**Issue by gxzks** [pytorch/fairseq#556]
Could you please implement the [Self-Attention with Relative Position Representations](https://arxiv.org/pdf/1803.02155.pdf)

It was done in [tensor2tensor](https://github.com/tensorflow/tensor2tensor).

Relative position  representations outperforms the origin Transformer by about 1 BLEU.

Thanks

**Comment by huihuifan** [comment]
This is currently not on our roadmap. We welcome any contributions by pull request! Note that we have some models trained in fairseq that have quite strong BLEU results. For example, this paper: https://openreview.net/pdf?id=SkVhlh09tX

models linked here: https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper

**Comment by myleott** [comment]
FWIW, we actually experimented internally with relative positional embeddings in fairseq and found them to be only marginally better and quite a bit slower, so we never pushed it public. cc @alexeib: any interest in pushing your branch public?

**Comment by gxzks** [comment]
Thanks for your reply :)
I've implemented the relative positional embeddings roughly just as a mimic of what T2T did but got no better performance. In T2T it actually performed better by about 0.5 BLEU scores in my own dataset. The training speed was slower too but I think it's normal as additional computation will happen.
I think the relative positional embeddings may be just an additional part in transformer not a new architecture, since it only changes the dot product function to plus an additional embedding and sets no absolute positional embeddings. Maybe can we set flags to control whether to use it or not?

**Comment by noe** [comment]
@myleott @gxzks care to share the implementations of the relative positional embeddings? I may be useful for other scenarios, even if they have not been thoroughly tested in the last fairseq version.

**Comment by frankang** [comment]
MPNet has published their implementation of relative positional embeddings. Will get a 30% slowdown if you use it.
https://github.com/microsoft/MPNet/blob/master/pretraining/fairseq/modules/rel_multihead_attention.py

**Comment by alexeib** [comment]
you can also copy from transformer xl pytorch implementation. it works but its slower. good for something like a conformer reimplementation. if i have time i will clean up my impl where i have a few different approaches implemented, or PR welcome :)

**Comment by allanj** [comment]
Also this one implemented:
https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/master/labml_nn/transformers/xl/relative_mha.py
