### ISSUE TITLE
How to score translations useing trained model?

### ISSUE THREAD

**Issue by lhcoder** [pytorch/fairseq#557]
Hello.
Here is a source sentence and some translation results. And I want to score the results with a trained translation model. 
I know there is a `--score-reference` option in generate.py. But I don't know how to apply it for multi translation results. Is there any simple method? 
Thanks.

**Comment by mali-nuist** [comment]
You want to translate the source sentences with the trained model and  using the result to compare with other already translated results?
If i do not misunderstand you, you can just run the fairseq-score command multi times with different pair of source and target sentences ...Then you can compare the bleu of different results...

**Comment by lhcoder** [comment]
@mali-nuist 
I'm sorry I didn't make myself clear. 
I want to use a trained model to rerank some translated results with their ppl, not bleu.
Thanks.

**Comment by huihuifan** [comment]
What is a multi translation result? You can use score-reference to output the likelihood of different translations. If you have multiple results, each can be scored.

**Comment by mali-nuist** [comment]
@lhcoder  Each translation text can be paired with the src text and binarized using the same dict to form  multi datasets, then for each dataset you can run the generate.py with --score-reference to rescore the translation result with the pretrained model... 
I did not do this before, but i think the your problem can be solved in this way ....

**Comment by lhcoder** [comment]
I think I get it, thanks you two.
