### ISSUE TITLE
[Question] Fairseq for sentence compression?

### ISSUE THREAD

**Issue by Hellisotherpeople** [pytorch/fairseq#562]
I'm trying to solve a word/phrase level extractive summarization task. Would Fairseq be suitable for this task, or should I try a binary tagger (tag 1 if word in compressed sentence else tag 0) ?

**Comment by huihuifan** [comment]
If your extractive summarization is deletion based, I recommend trying a binary tagger or restricting the output space of Fairseq's model generation to enforce what the model can and cannot generate, or you will get some abstractive summarization.
