### ISSUE TITLE
Why wall time is much more than train wall time?

### ISSUE THREAD

**Issue by STayinloves** [pytorch/fairseq#564]
I'm training transformer model on wmt17 chinese-english corpus using 6 GPUs(K40m), but I find that the `wall` is about 10x of the `train_wall`.

I assumed this problem may be related to data loading, so I tried use `--fix-batches-to-gpus` according to issue #217, but got OOM warnings:

```
| WARNING: OOM in all workers, skipping update
| WARNING: ran out of memory, skipping batch
```

The command I used to train is:

```
fairseq-train $DATADIR \
  -a transformer_wmt_en_de_big_t2t --optimizer adam -s zh -t en \
  --label-smoothing 0.1 --dropout 0.3 --max-tokens 5120 \
  --min-lr '1e-09' --lr-scheduler inverse_sqrt --weight-decay 0.0001 \
  --criterion label_smoothed_cross_entropy --max-update 200000 \
  --warmup-updates 4000 --warmup-init-lr '0.01' \
  --adam-betas '(0.9, 0.98)' --adam-eps '1e-09' \
  --keep-last-epochs 20 --save-dir checkpoints --log-format json > train.log
```

![image](https://user-images.githubusercontent.com/18565449/54035158-abff3b80-41f3-11e9-8458-6c3c56dc60a4.png)

It would be nice if you could offer me some advice on how to make the training more efficient. Thank!

**Comment by myleott** [comment]
This could be due to any number of factors. Maybe the code is spending too long on validation (how big is the validation set?). Or maybe the code is spending too long writing checkpoints after each epoch (maybe the disk is slow?).

Please open a new issue if this is still a problem, thanks!
