### ISSUE TITLE
How to binarize text summarization (Gigaword) data?

### ISSUE THREAD

**Issue by ailsamm** [pytorch/fairseq#566]
I'm looking to use Fairseq to train a text summarization model (with Gigaword corpus data).
I currently have aligned txt files of articles and titles for training, validation and test.
Does Fairseq have a script/ functionality I can use to convert raw text into binary files so that I can use it for training?

**Comment by huihuifan** [comment]
Yes, any of the examples for seq2seq will contain a command you can use: https://github.com/pytorch/fairseq/tree/master/examples

Basically, you want to run preprocess.py, which will build the dictionary and then binarize your dataset. Make sure your source and target files have the same number of lines.

**Comment by ailsamm** [comment]
Thank you @huihuifan . I appreciate the help!
