### ISSUE TITLE
Performance degradation when training with `--memory-efficient-fp16` argument

### ISSUE THREAD

**Issue by young-zonglin** [pytorch/fairseq#573]
Hi, I am using fairseq to train a Chinese grammatical error correction seq2seq model. I found that the model performance dropped by 1.47(from 24.33 to 22.86) when I used the `--memory-efficient-fp16` argument like `train.py -a fconv --fp16 --memory-efficient-fp16`. And I can't find more instructions on the official documentation. So any more details would be appreciate.

**Comment by myleott** [comment]
`--memory-efficient-fp16` is somewhat experimental and may not give as good results as regular `--fp16`, it depends on the architecture/optimizer, etc. For some architectures (e.g., Transformer), one typically gets the same results with reduced memory usage. But I never tried for fconv, so it's possible it doesn't work as well there.

**Comment by young-zonglin** [comment]
ok, thank you for reply!
