### ISSUE TITLE
In the doc, it should be 'output_format', not be 'output-format'.

### ISSUE THREAD

**Issue by 2hip3ng** [pytorch/fairseq#590]
![image](https://user-images.githubusercontent.com/38064349/54753969-56785500-4c1d-11e9-90a6-0215c3c7b246.png)

**Comment by myleott** [comment]
It's defined as `--output-format`: https://github.com/pytorch/fairseq/blob/master/fairseq/options.py#L201. Argparse then stores this in args.output_format.
