### ISSUE TITLE
Inference pipeline deletes lines in translation

### ISSUE THREAD

**Issue by ykl7** [pytorch/fairseq#591]
Hi,

I was translating monolingual de data into en using a transformer_wmt_en_de_big trained accordingly. During inference, I passed in a few files with 4 million sentences each and one file with around 6.7 million sentences.

I used the command:

```cat $file | python $FAIRSEQ/interactive.py --path $MODELPATH $DATA/binarized-data --source-lang de --target-lang en --buffer-size 1024 --sampling --sampling-topk 10 --beam 1 --nbest 1 --batch-size --remove-bpe | grep -P '^H' | cut -f3- > $OUTPUT```

The model failed to translate ~110 lines in each file. This is a problem since the monolingual data and backtranslations are not aligned. There was nothing in the error logs to suggest that the model had skipped over these sentences during inference.

Initially, I thought ```cut -f3-``` sometimes removes really small lines from the final output file, causing this problem (as evidenced by the original title for this issue). On having to run inference all over again (without cut -f3-) I found that I still lost the same number of lines in each file. The command I used this time round is:
```cat $file | python $FAIRSEQ/interactive.py --path $MODELPATH $DATA/binarized-data --source-lang de --target-lang en --buffer-size 1024 --sampling --sampling-topk 10 --beam 1 --nbest 1 --batch-size --remove-bpe | grep -P '^H' > $OUTPUT```

The longest line in each of the files to be translated is >10000 characters. If there is a memory problem, it is not reported in the logs. It looks like the model just arbitrarily skips ~110 out of every 4 million sentences when translating.

I cannot go through ~30 million lines to figure out which ones were excluded. Is there a workaround or a reason behind this happening?

**Comment by ykl7** [comment]
Individually executing each step of the pipeline does not cause this error. Prior to that, I filtered the input files by length. Most likely, it is a memory problem. Is there a way to figure out how much memory a model might need at inference?

**Comment by myleott** [comment]
It's not a memory problem, rather we filter inputs that are too long (see the `--max-source-positions` and `--max-target-positions` options). The filtering happens here: https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/fairseq_task.py#L132-L135.

Note that fairseq-interactive outputs the original sentence IDs, so you should be able to align it with the original input based on these IDs.

**Comment by myleott** [comment]
You might also try `fairseq-interactive --input source.txt` instead of piping the file. Sometimes I've noticed piping the input will truncate long lines (something to do with buffering of sys.stdin or readline).

**Comment by myleott** [comment]
interactive.py outputs the original line IDs, so you should be able to align using those. If a line is filtered, then it won't be printed but the subsequent line IDs will reflect the gap.

**Comment by harold1505** [comment]
@kellymarchisio If you want to identify the sentences which are longer than the `--max-source-positions`, you can do that with the following command in linux,

```grep -E '([^[:space:]]+([[:space:]]+|$)){1024,}'  input_file.txt```
