### ISSUE TITLE
dictionary implement

### ISSUE THREAD

**Issue by Hongzl1996** [pytorch/fairseq#599]
Hi,
I am wondering about the 'load' function in 'Dictionary' class, for it doesn't use 'add_symbol' to add symbols from text file. If there are a source sequence like 'A B C \<pad\> D' in the train data,  the index of '\<pad\>' would be changed without using 'add_symbol' function. 
![image](https://user-images.githubusercontent.com/25878132/54987313-539bac80-4fef-11e9-8191-e7c280aab1d8.png)

**Comment by villmow** [comment]
Hi, why did you close this issue? This problem still exists...

Is there any option to load a dictionary without having the special symbols at the beginning?

**Comment by Hongzl1996** [comment]
I think it isn't a situation encountered frequently.
As for personal use, I install this package locally and edit the _load_ function base on _add_symbol_.
