### ISSUE TITLE
questions in new uploaded adaptive language modeling

### ISSUE THREAD

**Issue by jiahuigeng** [pytorch/fairseq#601]
1 In https://github.com/pytorch/fairseq/tree/master/examples/language_model page, when downloading gbw model, there is no dict file and test file in the .bz2 file.

2 the model file after decompressed named "adaptive_lm_gbw_huge", not .pt type.
When I try to load that file as model:  errors happened in load_ensemble_for_inference  "filename 'storages' not found"

**Comment by uralik** [comment]
hey @jiahuigeng , this is a bzipped tar file, try to extract it as
`tar xjf <filename>`

this way you will get all the files

**Comment by alexeib** [comment]
thanks @uralik!
