### ISSUE TITLE
Connection time out with multi-node 

### ISSUE THREAD

**Issue by daothanhtuan** [pytorch/fairseq#604]
I follow the instructions in here to run in 2 nodes: 
https://fairseq.readthedocs.io/en/latest/getting_started.html#distributed-training

Basically I added this line before a single node command and run on node 0 (each node has 4 GPUs):
> python -m torch.distributed.launch --nproc_per_node=4 \
    --nnodes=2 --node_rank=0 --master_addr="192.168.010.100" \
    --master_port=22015 \
and replace --node_rank=1 for node 1.

However, both processes wait for a minute and stop with "Connection time out". I wonder if I am missing anything or if anyone succeeded running fairseq on multi-node please let me how you did it. 

```
| dictionary: 267744 types
| data-bin/wikitext-103 train 403231 examples
| data-bin/wikitext-103 valid 851 examples
| distributed init (rank 0): tcp://192.168.010.100:22015
Traceback (most recent call last):
  File "/home/tuan/anaconda3/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/home/tuan/pytorch/fairseq/fairseq_cli/train.py", line 392, in cli_main
    distributed_main(args.device_id, args)
  File "/home/tuan/pytorch/fairseq/fairseq_cli/train.py", line 380, in distributed_main
    main(args, init_distributed=True)
  File "/home/tuan/pytorch/fairseq/fairseq_cli/train.py", line 47, in main
    args.distributed_rank = distributed_utils.distributed_init(args)
  File "/home/tuan/pytorch/fairseq/fairseq/distributed_utils.py", line 67, in distributed_init
    rank=args.distributed_rank,
  File "/home/tuan/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 354, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/tuan/anaconda3/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 95, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon)
RuntimeError: Connection timed out
```

Thanks

**Comment by myleott** [comment]
Please make sure that that IP address is reachable from both hosts. Alternatively you can try passing any valid distributed_init method via the --distributed-init-method argument to fairseq. The available init methods are described here (scroll down a bit): https://pytorch.org/docs/stable/distributed.html#torch.distributed.init_process_group

**Comment by daothanhtuan** [comment]
Thanks a lot. I figured that the IPs were incorrect. The training runs fine after that.

**Comment by kamalravi** [comment]
> Thanks a lot. I figured that the IPs were incorrect. The training runs fine after that.

Same issue here. https://discuss.pytorch.org/t/runtimeerror-with-distributed-package-using-nccl-or-gloo-backend/30992/3

Can you please explain? Were you using any cloud (aws, gcp) for this?
