### ISSUE TITLE
Evaluation results path for fairseq-generation

### ISSUE THREAD

**Issue by sajastu** [pytorch/fairseq#609]
Hi,

I'm wondering if there is any way to output the evaluation results in fairseq-generate?

```
CUDA_VISIBLE_DEVICES=0 fairseq-generate data-bin/articles \
    --path checkpoints/transformer-embeddings/checkpoint_best.pt \
    --batch-size 25 --beam 5 --remove-bpe --results-path articles-test-prediction.txt
```

Well, I expect the results to be written into a file named `articles-test-prediction.txt`, but it is not the case. So, is there any argument to pass for generating predicted texts in fairseq-generate?

To be clear, I'm trying to use fairseq for summarization purpose. 

Thanks!

**Comment by myleott** [comment]
You can save the output using the > operator:
```
fairseq-generate (...) > articles-test-prediction.txt
```
