### ISSUE TITLE
how to preprocess wmt17 zh-en translation and reproduce the self attention and dynamic conv resulsts reported in the paper"Pay less attention"

### ISSUE THREAD

**Issue by zhaoguangxiang** [pytorch/fairseq#610]
Fairseq has provided support for en-de,de-en, en-fr , but  has not supported zh-en yet

**Comment by benbijituo** [comment]
As to pre-processing of wmt17 zh-en, refer to https://github.com/STayinloves/NMT2017-ZH-EN. 
And the zh-en dataset can be directly applied to transformer_en_de.

**Comment by huihuifan** [comment]
we have pretrained models available here: https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper as well

**Comment by GeorgeS2019** [comment]
@huihuifan , @benbijituo I use the data preparation suggested by https://github.com/STayinloves/NMT2017-ZH-EN for the pre-trained model provided by [paper ](https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper)cited by @huihuifan. However in the provided paper, the data preparation refers to that of the Microsoft paper. Anyone has any success in the binary data preparation for the [pre-trained model](https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper)?
