### ISSUE TITLE
Is there a way to modify data input pipeline during training?

### ISSUE THREAD

**Issue by gxzks** [pytorch/fairseq#616]
I want to apply curriculum learning into fairseq. One necessary step is to change the data input pipeline to select samples following a specific schedule. I only found "--curriculum" but it is not the method I need. Could you give me some advice on how to modify the data input pipeline in fairseq?

**Comment by mohamedafify2001** [comment]
Hello, same question here. Is there an existing implementation or we have to rewrite it. Thanks
