### ISSUE TITLE
Cannot download pretrained models.

### ISSUE THREAD

**Issue by magic282** [pytorch/fairseq#619]
Hi,

The two pretrained models in [page](https://github.com/pytorch/fairseq/tree/bi_trans_lm/examples/pretraining) cannot be downloaded.

![image](https://user-images.githubusercontent.com/2285145/55454649-3a0feb80-5613-11e9-90ec-733672e5ab23.png)

**Comment by huihuifan** [comment]
@edunov @alexeib

**Comment by lematt1991** [comment]
This seems to have been fixed as they downloading fine for me.  Please re-open if you are still having issues.
