### ISSUE TITLE
Memory issue when training the transformer model

### ISSUE THREAD

**Issue by GitHub-v7** [pytorch/fairseq#648]
Hi,
I trained the transformer model with base architecture. The training process run normally when seed 1  was used. But when I used the other seed like 2, 3..., I encountered the issue of out of memory on the backward step of two certain consecutive batches (torch.Size([67, 88, 512]) and torch.Size([36, 152, 512])). Input shape is Time x Batch x Channel.

Actually when I tried to debug it, I found the same batch size (torch.Size([67, 88, 512]) in the training process of seed 1 transformer model. So, I want to ask why the transformer model of seed 1 can work but the other seeds meet the memory issue? 

Besides, these two consecutive batches occurs two error types. the former occurs the "CUDA error: out of memory" while the latter occurs the "cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1532581333611/work/aten/src/THC/generic/THCTensorMathPairwise.cu:81". what's the difference between these two errors?

**Comment by myleott** [comment]
Your batch size is probably right on the edge of what can fit on your GPU. This means that slight variations in the batch ordering can cause OOM. What model size/batch size/GPU are you using? Try reducing --max-tokens.

**Comment by huihuifan** [comment]
@GitHub-v7
