### ISSUE TITLE
Error in multilingual translation example during inference

### ISSUE THREAD

**Issue by maksym-del** [pytorch/fairseq#656]
Command:
> 
> cat iwslt17.test.${SRC}-en.${SRC}.bpe | fairseq-interactive data-bin/iwslt17.de_fr.en.bpe16k/   --task multilingual_translation --source-lang ${SRC} --target-la
> ng en   --path checkpoints/multilingual_transformer/checkpoint_best.pt   --buffer 2000 --batch-size 128   --beam 5 --remove-bpe=sentencepiece --decoder-langtok > iwslt17.test.${SRC}-en.en.sys

> Traceback (most recent call last):
>   File "/home/maksym/.conda/envs/fseq/bin/fairseq-interactive", line 11, in <module>
>     load_entry_point('fairseq', 'console_scripts', 'fairseq-interactive')()
>   File "/home/maksym/research/interlingua/fairseq/fairseq_cli/interactive.py", line 169, in cli_main
>     main(args)
>   File "/home/maksym/research/interlingua/fairseq/fairseq_cli/interactive.py", line 76, in main
>     task = tasks.setup_task(args)
>   File "/home/maksym/research/interlingua/fairseq/fairseq/tasks/__init__.py", line 19, in setup_task
>     return TASK_REGISTRY[args.task].setup_task(args)
>   File "/home/maksym/research/interlingua/fairseq/fairseq/tasks/multilingual_translation.py", line 118, in setup_task
>     dicts, training = cls.prepare(args, **kwargs)
>   File "/home/maksym/research/interlingua/fairseq/fairseq/tasks/multilingual_translation.py", line 126, in prepare
>     args.lang_pairs = args.lang_pairs.split(',')
> AttributeError: 'NoneType' object has no attribute 'split'

It seems like this command still requires --lang-pairs argument to be passed during inference.

https://github.com/pytorch/fairseq/issues/499#issuecomment-464181949

**Comment by myleott** [comment]
@pipibjc

**Comment by PC09** [comment]
Yes, even I faced this error. It still requires --lang-pairs argument to be passed.

**Comment by madaanpulkit** [comment]
> Yes, even I faced this error. It still requires --lang-pairs argument to be passed.

How to deal with it then? What should be passed and in what format?

**Comment by pipibjc** [comment]
Sorry for the late reply. During inference time, these three parameters `--lang-pairs`, `--encoder-langtok`, `--decoder-langtok` need to have the same value as training.
The format of `--lang-pairs` is  <src_lang1>-<target_lang1>[,<src_lang2>-<target-lang2>,...].

For example, in the [example page of multilingual translation](https://github.com/pytorch/fairseq/tree/master/examples/translation#multilingual-translation), we train a model that translates German and French into English. `--lang-pairs` should be set to `de-en,fr-en` for both training and inference.

I am updating the error message and the example page to make it more clearer.

**Comment by madaanpulkit** [comment]
> Sorry for the late reply. During inference time, these three parameters `--lang-pairs`, `--encoder-langtok`, `--decoder-langtok` need to have the same value as training.
> The format of `--lang-pairs` is <src_lang1>-<target_lang1>[,<src_lang2>-,...].
> 
> For example, in the [example page of multilingual translation](https://github.com/pytorch/fairseq/tree/master/examples/translation#multilingual-translation), we train a model that translates German and French into English. `--lang-pairs` should be set to `de-en,fr-en` for both training and inference.
> 
> I am updating the error message and the example page to make it more clear.

@pipibjc can you modify the example for many-to-many multilingual translation. Right now, the example only addresses many-to-one.

**Comment by PC09** [comment]
Hi , again I am facing a strange issue while running fairseq-interactive. I am running the following command-

cat test.bpe.hi-en.hi | fairseq-interactive data-bin/All_iicl_merged/ --task multilingual_translation --lang-pairs hi-en,bn-en,ml-en,te-en,ta-en,ur-en,en-hi,en-bn,en-ta,en-te,en-ml,en-ur --source-lang hi --target-lang en --path checkpoints/multilingual_transformer/checkpoint_best.pt  --buffer-size 200 --batch-size 128   --beam 5 --remove-bpe=sentencepiece

It throws up an error-

Namespace(beam=5, buffer_size=200, cpu=False, criterion='cross_entropy', data='data-bin/All_iicl_merged/', dataset_impl='cached', decoder_langtok=False, diverse_beam_groups=-1, diverse_beam_strength=0.5, encoder_langtok=None, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, gen_subset='test', input='-', lang_pairs='hi-en,bn-en,ml-en,te-en,ta-en,ur-en,en-hi,en-bn,en-ta,en-te,en-ml,en-ur', lazy_load=False, left_pad_source='True', left_pad_target='False', lenpen=1, log_format=None, log_interval=1000, lr_scheduler='fixed', lr_shrink=0.1, match_source_len=False, max_len_a=0, max_len_b=200, max_sentences=128, max_source_positions=1024, max_target_positions=1024, max_tokens=None, memory_efficient_fp16=False, min_len=1, min_loss_scale=0.0001, model_overrides='{}', momentum=0.99, nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, no_repeat_ngram_size=0, num_shards=1, num_workers=0, optimizer='nag', path='checkpoints/multilingual_transformer/checkpoint_best.pt', prefix_size=0, print_alignment=False, quiet=False, raw_text=False, remove_bpe='sentencepiece', replace_unk=None, required_batch_size_multiple=8, results_path=None, sacrebleu=False, sampling=False, sampling_topk=-1, score_reference=False, seed=1, shard_id=0, skip_invalid_size_inputs_valid_test=False, source_lang='hi', target_lang='en', task='multilingual_translation', tbmf_wrapper=False, temperature=1.0, tensorboard_logdir='', threshold_loss_scale=None, unkpen=0, unnormalized=False, upsample_primary=1, user_dir=None, warmup_updates=0, weight_decay=0.0)
| [bn] dictionary: 31728 types
| [en] dictionary: 31728 types
| [hi] dictionary: 31728 types
| [ml] dictionary: 31728 types
| [ta] dictionary: 31728 types
| [te] dictionary: 31728 types
| [ur] dictionary: 31728 types
| loading model(s) from checkpoints/multilingual_transformer/checkpoint_best.pt
Traceback (most recent call last):
  File "/home/sriram/anaconda3/envs/py3/bin/fairseq-interactive", line 10, in <module>
    sys.exit(cli_main())
  File "/home/sriram/anaconda3/envs/py3/lib/python3.7/site-packages/fairseq_cli/interactive.py", line 185, in cli_main
    main(args)
  File "/home/sriram/anaconda3/envs/py3/lib/python3.7/site-packages/fairseq_cli/interactive.py", line 83, in main
    task=task,
  File "/home/sriram/anaconda3/envs/py3/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 153, in load_model_ensemble
    ensemble, args, _task = _load_model_ensemble(filenames, arg_overrides, task)
  File "/home/sriram/anaconda3/envs/py3/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 171, in _load_model_ensemble
    model = task.build_model(args)
  File "/home/sriram/anaconda3/envs/py3/lib/python3.7/site-packages/fairseq/tasks/multilingual_translation.py", line 264, in build_model
    check_args()
  File "/home/sriram/anaconda3/envs/py3/lib/python3.7/site-packages/fairseq/tasks/multilingual_translation.py", line 261, in check_args
    raise ValueError(' '.join(messages))
ValueError: --lang-pairs should include all the language pairs ['hi-en', 'bn-en', 'ml-en', 'te-en', 'ta-en', 'ur-en', 'en-hi', 'en-bn', 'en-ta', 'en-te', 'en-ml', 'en-ur'].

Even though I have specified the lang-pairs , its giving me this error. Please let me know a solution. Earlier the same command was working fine.

**Comment by lematt1991** [comment]
@PC09, are you still having issues with this?  If so, can you please open a new issue following the new issue templates.
