### ISSUE TITLE
Missing key(s) in state_dict when I generate en2de by using transformer_big

### ISSUE THREAD

**Issue by BaohaoLiao** [pytorch/fairseq#660]
Hi,

I train the model like the translation in examples. However, when I generate it shows:
`Traceback (most recent call last):
  File "/u/bliao/miniconda3/envs/pt/bin/fairseq-generate", line 11, in <module>
    load_entry_point('fairseq==0.6.2', 'console_scripts', 'fairseq-generate')()
  File "/u/bliao/miniconda3/envs/pt/lib/python3.7/site-packages/fairseq-0.6.2-py3.7-linux-x86_64.egg/fairseq_cli/generate.py", line 188, in cli_main
    main(args)
  File "/u/bliao/miniconda3/envs/pt/lib/python3.7/site-packages/fairseq-0.6.2-py3.7-linux-x86_64.egg/fairseq_cli/generate.py", line 49, in main
    args.path.split(':'), task, model_arg_overrides=eval(args.model_overrides),
  File "/u/bliao/miniconda3/envs/pt/lib/python3.7/site-packages/fairseq-0.6.2-py3.7-linux-x86_64.egg/fairseq/utils.py", line 169, in load_ensemble_for_inference
    model.load_state_dict(state['model'], strict=True)
  File "/u/bliao/miniconda3/envs/pt/lib/python3.7/site-packages/fairseq-0.6.2-py3.7-linux-x86_64.egg/fairseq/models/fairseq_model.py", line 66, in load_state_dict
    super().load_state_dict(state_dict, strict)
  File "/u/bliao/miniconda3/envs/pt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TransformerModel:
	Missing key(s) in state_dict: "encoder.layers.0.layer_norms.0.weight", "encoder.layers.0.layer_norms.0.bias", "encoder.layers.0.layer_norms.1.weight", "encoder.layers.0.layer_norms.1.bias", "encoder.layers.1.layer_norms.0.weight", "encoder.layers.1.layer_norms.0.bias", "encoder.layers.1.layer_norms.1.weight", "encoder.layers.1.layer_norms.1.bias", "encoder.layers.2.layer_norms.0.weight", "encoder.layers.2.layer_norms.0.bias", "encoder.layers.2.layer_norms.1.weight", "encoder.layers.2.layer_norms.1.bias", "encoder.layers.3.layer_norms.0.weight", "encoder.layers.3.layer_norms.0.bias", "encoder.layers.3.layer_norms.1.weight", "encoder.layers.3.layer_norms.1.bias", "encoder.layers.4.layer_norms.0.weight", "encoder.layers.4.layer_norms.0.bias", "encoder.layers.4.layer_norms.1.weight", "encoder.layers.4.layer_norms.1.bias", "encoder.layers.5.layer_norms.0.weight", "encoder.layers.5.layer_norms.0.bias", "encoder.layers.5.layer_norms.1.weight", "encoder.layers.5.layer_norms.1.bias". 
	Unexpected key(s) in state_dict: "encoder.layers.0.self_attn_layer_norm.weight", "encoder.layers.0.self_attn_layer_norm.bias", "encoder.layers.0.final_layer_norm.weight", "encoder.layers.0.final_layer_norm.bias", "encoder.layers.1.self_attn_layer_norm.weight", "encoder.layers.1.self_attn_layer_norm.bias", "encoder.layers.1.final_layer_norm.weight", "encoder.layers.1.final_layer_norm.bias", "encoder.layers.2.self_attn_layer_norm.weight", "encoder.layers.2.self_attn_layer_norm.bias", "encoder.layers.2.final_layer_norm.weight", "encoder.layers.2.final_layer_norm.bias", "encoder.layers.3.self_attn_layer_norm.weight", "encoder.layers.3.self_attn_layer_norm.bias", "encoder.layers.3.final_layer_norm.weight", "encoder.layers.3.final_layer_norm.bias", "encoder.layers.4.self_attn_layer_norm.weight", "encoder.layers.4.self_attn_layer_norm.bias", "encoder.layers.4.final_layer_norm.weight", "encoder.layers.4.final_layer_norm.bias", "encoder.layers.5.self_attn_layer_norm.weight", "encoder.layers.5.self_attn_layer_norm.bias", "encoder.layers.5.final_layer_norm.weight", "encoder.layers.5.final_layer_norm.bias". 
`
Do you have any idea about this problem. Thanks in advance.

**Comment by gvskalyan** [comment]
Clone the repository instead of installing via pip.
And install editable and try using its generate / interactive . I suppose it works

**Comment by huihuifan** [comment]
Looks like this issue is resolved, closing

**Comment by JohannesTK** [comment]
@huihuifan, are these related https://github.com/pytorch/fairseq/issues/742?
