### ISSUE TITLE
Tokenized text for each sentence

### ISSUE THREAD

**Issue by ashutoshsaboo** [pytorch/fairseq#663]
Hi,
Is there any way to get the tokenized pre-processed text for each text sentence in the corpus? Basically I'd like to see how each sentence in my corpus has been tokenized. 

For instance: if the sentence in corpus is: `Good Morning!`
The pre-processed tokens could be: `<Good> <Morning> <!>,` or if there are any `<unk>` tokens in place of either of them. I can view the tokens for each sentence, but can't view the original text. Is there any way to facilitate the same?
Thanks!

**Comment by huihuifan** [comment]
Yes, you can use the dictionary to map the tokens back to words.
