### ISSUE TITLE
fp16 is much slower than fp32 !!

### ISSUE THREAD

**Issue by zhao1iang** [pytorch/fairseq#668]
When doing translation via transformer ,I found  in one of my machines fp16 is much slower than fp32. I strongly suspect that the problem is caused by some packages of my python，because my friends use the same machine with me but it is ok for his use of fp16. The python I used is the default python of Anaconda3-2019.03(the lastest version until 4/25/2019 ) . Does anyone else have the same question? I am eagerly awaiting your answer. Excuse me  for my poor English.

**Comment by frankang** [comment]
you can try using your friend's anaconda environment to verify this issue.

**Comment by zhao1iang** [comment]
@frankang Thank you so much , I solved this problem.  It's due to my pytorch associated cuda version is 9.0，instead my friends is 10.0.3.After I reinstalled my pytorch use this command `conda install pytorch torchvision cudatoolkit=10.0 -c pytorch`  everything is back to normal.
