### ISSUE TITLE
 interactive.py from French back to English

### ISSUE THREAD

**Issue by kuanweih** [pytorch/fairseq#677]
Hello, 

I'm using the following command to translate from English to French based on wmt14.en-fr.joined-dict.transformer pre-trained model and it is going well. 

```python  interactive.py  --path  data-bin/wmt14.en-fr.joined-dict.transformer/model.pt data-bin/wmt14.en-fr.joined-dict.transformer  --beam 5  --source-lang  en  --target-lang  fr  --input  test-trans.tsv  >  output_test_fr.tsv```

However, when I try to translate from French to English with the command:

```python  interactive.py  --path  data-bin/wmt14.en-fr.joined-dict.transformer/model.pt data-bin/wmt14.en-fr.joined-dict.transformer  --beam 5  --source-lang  fr  --target-lang  en  --input  output_test_fr.tsv  >  output_test_en.tsv```

The output  is still in French:
S-0	<unk> Les besoins de la nation devaient pro@@ venir d&apos; un système de non @-@ emprunt . L&apos; argent était une valeur d &quot; échange neutre reliant les ressources , les gens et les besoins , sans qu&apos; il y ait de dette .
H-0	-0.2537561357021332	L&apos; argent était une valeur d &quot; échange neutre dépendant des ressources , les gens et les besoins , sans qu&apos; il y ait de dette .
P-0	-2.1667 -0.1153 -0.2221 -0.1224 -0.0721 -0.1008 -0.1023 -0.0729 -0.0365 -1.6899 -0.2752 -0.1001 -0.1054 -0.3694 -0.0415 -0.1061 -0.1042 -0.0805 -0.1257 -0.0976 -0.1862 -0.1168 -0.0819 -0.1426 -0.1082 -0.0840 -0.1313 -0.1474

Am I missing something? 
Or is there a better way to do back-translation? 

I've looked up the back-translation in the example directory but I couldn't find anything.

Thanks

**Comment by edunov** [comment]
You can't use the same model for both directions, for Fr->En you need to train another model. You can change --source-lang and --target-lang parameters of the train.py accordingly.
