### ISSUE TITLE
Using multiple binary files for training

### ISSUE THREAD

**Issue by Raghava14** [pytorch/fairseq#678]
Hi, 
Just like how the workers generate I have multiple train bin and idx files like  
```
train1.en-de.en.bin
train1.en-de.en.idx
train1.en-de.de.bin
train1.en-de.de.idx
```

```
train2.en-de.en.bin
train2.en-de.en.idx
train2.en-de.de.bin
train2.en-de.de.idx
```
Now I want to run the training on these multiple files like a single` bin` and` idx` file in each case. Is it possible in a straight forward way to do so or else should I need to change something ?
Thanks.

**Comment by huihuifan** [comment]
Sorry, I don't understand your question- you don't want multiple bin and idx files? Right now the binarization creates these, you would need to change that process and the data loading as well

**Comment by Raghava14** [comment]
Firstly sorry for late reply, My question is let's say I have 1000 parallel sentences and binarized them to create bin and idx files. Now I get another 1000 sentences and I do the same to get second set of bin and idx files. Now if I want to train the model on combined 2000 sentences instead for combining the sentences and binarizing again is there a way so that I can combine the binarized files (bin, idx ) files generated in each case.

**Comment by xdg988** [comment]
I also meet this problem. Does anyone successfully solve it?

**Comment by luofuli** [comment]
The following two steps may solve your problems.
1. Move the multiple train bin and idx files to separate directories, e.g, `train1` and `train2`.
2. Use a colon `:` to separate directories, which will be iterated upon during epochs in a round-robin manner. For example,  `fairseq-train --fp16  train1:train2`

**Comment by lematt1991** [comment]
@luofuli's answer is the recommended approach.
