### ISSUE TITLE
Is there any way to show the [models,tasks,criterations]-specific arguments in command line?

### ISSUE THREAD

**Issue by Beanocean** [pytorch/fairseq#701]
I am confused about the *-specific parser used in \_\_init\_\_.py scripts, eg: [models/\_\_init\_\_.py](https://github.com/pytorch/fairseq/blob/39264559f64f581098e298b45674f40e6c4a5ee9/fairseq/models/__init__.py#L115-L120). There are some parsers, like `fconv_parser` and `lstm_parser`, are declared, but they seem impossible to actually used in command line for the help information and argument parsing.

**Comment by myleott** [comment]
This was added for the documentation so we could automatically list the command-line arguments for each model: https://fairseq.readthedocs.io/en/latest/models.html#module-fairseq.models.fconv
