### ISSUE TITLE
Multiple Reference Translations for Scoring BLEU

### ISSUE THREAD

**Issue by ashutoshsaboo** [pytorch/fairseq#709]
Is it possible to use multiple reference translations for BLEU scoring in NMT like the one here: https://github.com/pytorch/fairseq/tree/master/examples/translation_moe for `translation_moe` task?

**Comment by myleott** [comment]
This isn't supported directly by generate.py. The preferred approach is to save the generations and score them using other utilities, e.g., sacrebleu.
