### ISSUE TITLE
Custom fairseq training input

### ISSUE THREAD

**Issue by kyquang97** [pytorch/fairseq#716]
hi faiseq team, i'm creating custom translation model that receives source sentence and also its pos tag. Are there any way to custom preprocess and train progress for this purpose ?

**Comment by kyquang97** [comment]
after reading fairseq code, i've been tried to custom preprocess.py by added --tagpref argument in options.py, then edit some lines in preprocess to make it can read the tag file and save it with txt, idx and bin extension.
![image](https://user-images.githubusercontent.com/17948800/57573354-9951ee80-7450-11e9-9f06-d0c23914bfca.png)
Now, i'm trying to make model can read train file and tag file at the same time, then receives its input as tensor. If anyone have any ideas, please give me some instructions :) Thanks

**Comment by huihuifan** [comment]
You can modify the data loader to take in two files, or binarize the POS along with the words and split it yourself in the dataloader before passing to the model
