### ISSUE TITLE
Error while calculating score

### ISSUE THREAD

**Issue by aastha19** [pytorch/fairseq#718]
Hi 
When I try to run the generate.py file and calculate the BLEU score, an ImportError is thrown.
ImportError: cannot import name 'libbleu' from 'fairseq' 
Any help would be appreciated.

**Comment by Corie96** [comment]
Hi! You can try `cd` into the folder containing fairseq's code, and run:
```
pip install --editable .
```

**Comment by huihuifan** [comment]
did you run the setup?

**Comment by aastha19** [comment]
Running the generate script results in
AttributeError: function 'bleu_zero_init' not found

**Comment by aastha19** [comment]
> did you run the setup?

Yes

**Comment by myleott** [comment]
The BLEU scorer depends on a C module that is compiled when you run `python setup.py develop` or `pip install --editable .`. Did that compilation succeed without errors and/or can you try again?

Alternatively you can `pip install sacrebleu` and pass the `--sacrebleu` option to generate.py

**Comment by aastha19** [comment]
> The BLEU scorer depends on a C module that is compiled when you run `python setup.py develop` or `pip install --editable .`. Did that compilation succeed without errors and/or can you try again?
> 
> Alternatively you can `pip install sacrebleu` and pass the `--sacrebleu` option to generate.py

Yes, compilation succeeded without any errors. using --sacreblue option solves the above error but throws another.
UnicodeEncodeError: 'charmap' codec can't encode characters in position 7-13: character maps to <undefined>

**Comment by chintanckg** [comment]
For windows, this https://github.com/pytorch/fairseq/issues/292 helped me.
