### ISSUE TITLE
tensorboard or required dependencies not found, please see README for using tensorboard

### ISSUE THREAD

**Issue by qazwsx74269** [pytorch/fairseq#728]
My virtual environment has installed tensorboard and I can run it normally. But why does this information appear when I try to add --tensorboard-logdir?

**Comment by ngoyal2707** [comment]
Do you also have tensorboardX installed? it's pytorch wrapper of tensorboard.

**Comment by qazwsx74269** [comment]
> Do you also have tensorboardX installed? it's pytorch wrapper of tensorboard.

Yes, you are right and I solve it after installing tensorboardX. Thank you!
