### ISSUE TITLE
Cite IWSLT Conv models

### ISSUE THREAD

**Issue by ashutoshsaboo** [pytorch/fairseq#740]
Is there any publication specifically referring to `fconv_iwslt_de_en` settings as described here - https://github.com/pytorch/fairseq/blob/master/fairseq/models/fconv.py#L610 ? I see that the original publication here - https://arxiv.org/abs/1705.03122 - just refers to the WMT settings. 

Thanks!

**Comment by myleott** [comment]
We used this architecture in this paper: https://arxiv.org/abs/1711.04956
