### ISSUE TITLE
How much graphics memory is needed to train GCNN-13 model on Google Billion Word?

### ISSUE THREAD

**Issue by cswangjiawei** [pytorch/fairseq#748]
How much graphics memory is needed to train GCNN-13 model on Google Billion Word? I train on 1080ti (11g memory) and "Runtime Error: CUDA out of memory" appeared on the fourth batch (batch_size=64).
![memory](https://user-images.githubusercontent.com/33107884/57970362-f7cc1f00-79b2-11e9-8764-b0fe76379a1f.jpg)

**Comment by huihuifan** [comment]
In the publication, we used tesla m40. Try to lower the batchsize, or you can make the model smaller - for example setting a more aggressive adaptive softmax cutoff
