### ISSUE TITLE
How long it takes to train GCNN-13 (Dataset: Google Billion Word) on single Tesla M40 GPU?

### ISSUE THREAD

**Issue by cswangjiawei** [pytorch/fairseq#749]
The paper "Language Modeling with Gated Convolutional Networks" says the majority of models are trained on single GPU, I wonder how long it takes to train GCNN-13 (Dataset: Google Billion Word) on single Tesla M40 GPU?

**Comment by huihuifan** [comment]
For the largest GCNN on GBW, we trained on 8 Tesla M40 GPU. For all of the other models, we trained on one. On 8 Tesla M40 GPU, it took a couple weeks to train fully. The PyTorch code we've open sourced here is faster and more efficient though.
