### ISSUE TITLE
Question about text summarization

### ISSUE THREAD

**Issue by garyhsu29** [pytorch/fairseq#750]
I read the paper in https://arxiv.org/pdf/1903.09722.pdf and I want to reproduce the abstractive text summarization part, but in the branch bi_trans_lm part (https://github.com/pytorch/fairseq/tree/bi_trans_lm/examples/pretraining) the Model download link seems broken. Any suggestion? Thanks!

**Comment by nng555** [comment]
Download links should work correctly now!
