### ISSUE TITLE
Resuming the training from a checkpoint isn't possible if FP16Optimizer is used.

### ISSUE THREAD

**Issue by AranKomat** [pytorch/fairseq#755]
A similar problem was fixed in #424. The fixed optimizer is now called MemoryEfficientFP16Optimizer, and FP16Optimizer now doesn't work, since it's similar to the one before it was fixed in #424. MemoryEfficientFP16Optimizer is slow, so I wonder if you can modify the current FP16Optimizer to accommodate the resuming option without making it slower? If you don't have a time to do it any time soon, could you give me a brief advice on how to fix it?

**Comment by myleott** [comment]
Can you provide more details? Resuming models trained with `--fp16` should work as expected. The `--memory-efficient-fp16` optimizer is somewhat experimental, but should it also be possible to resume models trained with it.
