### ISSUE TITLE
When will the new version be released?

### ISSUE THREAD

**Issue by davidecaroselli** [pytorch/fairseq#756]
I have seen a lot of changes since 0.6.2, and I would like to integrate the new version (with the mmap training set implementation) in our project, have you any ETR?
What would exactly change in the new release? Are there any major API changes?

Thanks!

**Comment by myleott** [comment]
Good call, it's been a while, I'll cut a new release next week. We'll probably go with 0.7.0, but I'll have to look closer at any major API changes and summarize them in the changelog.

**Comment by myleott** [comment]
Sorry for the delay — we’re hoping to get torch.hub integration in a good place before doing a release. Est. early next week.

**Comment by davidecaroselli** [comment]
Great! Thanks!

**Comment by myleott** [comment]
v0.7.1 is out!

**Comment by davidecaroselli** [comment]
Awesome!
