### ISSUE TITLE
Confusing the command of XLM

### ISSUE THREAD

**Issue by KelleyYin** [pytorch/fairseq#762]
In the [example script](https://github.com/pytorch/fairseq/tree/master/examples/cross_lingual_language_model) you provided, you process the text `monolingual_data/processed/` into  the binary and store in `monolingual_data/fairseq_processed`. However, the origin text file `monolingual_data/processed` is used to in the next training script.
Is this a mistake ?
I tried to correct it to `monolingual_data/fairseq_processed`, but the program reported an error.
Is there anyone who can help me ?

**Comment by KelleyYin** [comment]
You need to make some changes both in processing and training script.
- **preprocess.py**
remove  `--task cross_lingual_lm`
```
change 
sudo mv $stage.$lg-None.$lg.bin $stage.$lg.bin
to
sudo mv monolingual_data/fairseq_processed/$stage.$lg-None.$lg.bin monolingual_data/fairseq_processed/$stage.$lg.bin
```
****
- **train.py**
remove `--no-bias-kv`
```
change
--lazy-load
to
--dataset-impl lazy
````

**Comment by lematt1991** [comment]
I think that the `--task cross_lingual_lm` needs to stay, but I agree with the rest.  Happy to take a PR!
