### ISSUE TITLE
parallel decoding ?

### ISSUE THREAD

**Issue by mali-nuist** [pytorch/fairseq#764]
I modify the fairseq as a translation service, but it seems that the each request has to wait before previous request finishes even though i use concurrent programming and there are also some free gpu resources .
As i am not quiet understanding the computation logic of gpu, so i wonder if it's possible for me to make the code support parallel decoding, which can decode multi requests simultaneously. Though this can be done by start multi services on one gpu, but i would prefer parallel decoding  if it's possible. 
Thanks...

**Comment by lematt1991** [comment]
Can you be more specific about the changes that you made?  Can you include a link to a branch containing your modifications?

**Comment by mali-nuist** [comment]
> Can you be more specific about the changes that you made? Can you include a link to a branch containing your modifications?

Hello letmatt, thanks for your reply. 
I use tornado as service framework and  load the model resources in the tornado Handler __init__ method, all the code are almost same as:
https://github.com/pytorch/fairseq/blob/4ed5abc9e355ff22a971372d365f0bc27f2d941f/interactive.py#L74-L113

Then in the post/get method, reading all the sentences to be translated and make them in one batch like:
https://github.com/pytorch/fairseq/blob/4ed5abc9e355ff22a971372d365f0bc27f2d941f/interactive.py#L117-L129

Finally, call the inference function and return all the result back:
https://github.com/pytorch/fairseq/blob/4ed5abc9e355ff22a971372d365f0bc27f2d941f/interactive.py#L130-L163

Thanks

**Comment by lematt1991** [comment]
Sorry, I'm not familiar with tornado.  Maybe they can help you?  Closing this issue for now.  Please open a new one if you have additional concerns.  Thanks!
