### ISSUE TITLE
Output file contains extra lines that are not part of translation

### ISSUE THREAD

**Issue by ereday** [pytorch/fairseq#771]
Hi, 

I am trying to translate a raw text file by using `interactive.py` and  pre-trained NMT models in the fairseq repository as follows:

```
$ cat sample_input.final
```

> My name is ere@@ day .
> I like cats .
> Education is the passport to the future , for tomorrow bel@@ og@@ ns to those who prepare for it today .
> 

```
$ cat sample_input.final | python ./interactive.py ../wmt14.en-de.fconv-py/ --remove-bpe --path ../wmt14.en-de.fconv-py/model.pt -s en -t de --quiet  | tee output_file.txt
````

``` 
$ cat output_file.txt
 ```

> Namespace(beam=5, buffer_size=1, cpu=False, data='../wmt14.en-de.fconv-py/', dataset_impl='cached', diverse_beam_groups=-1, diverse_beam_strength=0.5, fp16=False,  ....
> | [en] dictionary: 40358 types
> | [de] dictionary: 42714 types
> | loading model(s) from ../wmt14.en-de.fconv-py/model.pt
> | Type the input sentence and press return:
> S-0	My name is ereday .
> H-0	-0.5524863004684448	Mein Name ist der heutige Tag .
> P-0	-0.3803 -0.0128 -0.1571 -1.7124 -2.1099 -0.0434 -0.0039 -0.0000
> S-1	I like cats .
> H-1	-0.14378516376018524	Ich mag Katzen .
> P-1	-0.1418 -0.2106 -0.4625 -0.0319 -0.0160 -0.0000
> S-2	Education is the passport to the future , for tomorrow belogns to those who prepare for it today .
> H-2	-0.43202051520347595	Bildung ist der Pass in die Zukunft , denn morgen erkennt man diejenigen , die sich heute darauf vorbereiten .
> P-2	-0.4543 -0.0735 -0.3153 -0.6046 -0.7592 -0.0248 -0.0019 -0.0628 -0.1889 -0.4038 -2.9709 -0.2125 -1.4647 -0.0550 -0.0086 -0.5473 -0.7326 -0.1416 -0.0409 -0.0090 -0.0003
> 

The command seems working, but in the output_file.txt I see some extra information which is not part of the translation.  Is there a way to create an output file which contains only the translation of the input file ?

**Comment by lematt1991** [comment]
`cat output_file.txt | grep -P '^H-' | sed 's/H-//' | cut -f3-` should do it

**Comment by ereday** [comment]
Thanks for reply. Agreed, however I was wondering if there is a more natural way to get translation only file.

**Comment by lematt1991** [comment]
Not currently, but perhaps there should be.
