### ISSUE TITLE
Checkpoint saving policy

### ISSUE THREAD

**Issue by cettolo** [pytorch/fairseq#775]
Hi All

by specifying these options for training (among others not affecting the checkpoint saving process):

"--max-update 200000 --save-interval-updates 2000 --keep-interval-updates 10 --keep-last-epochs 10"

the following checkpoints are saved:

...
...  3 giu 15.30 checkpoint_6_180000.pt
...  3 giu 16.55 checkpoint_6_182000.pt
...  3 giu 18.19 checkpoint_6_184000.pt
...  3 giu 19.43 checkpoint_6_186000.pt
...  3 giu 21.07 checkpoint_best.pt
...  4 giu 04.46 checkpoint6.pt
...  4 giu 05.33 checkpoint_7_200000.pt
...  4 giu 05.33 checkpoint_last.pt

As you can note, the checkpoints between 186k and 200k are not stored, likely because they are not better than the "best", generated right after checkpoint_6_186000.pt

In any case, the checkpoints generated in correspondence of the epoch 6 and of the last iteration (200k) are stored, despite they are below the best.

I'm wondering if this is the actual saving policy and which is the rationale behind it

Thank you

Mauro

**Comment by lematt1991** [comment]
The log should include something that says when a [checkpoint is saved](https://github.com/pytorch/fairseq/blob/master/fairseq/checkpoint_utils.py#L68).  Do you see such a line in your log corresponding to your missing checkpoints (188000, 190000, etc.)?

**Comment by cettolo** [comment]
Thanks for the reply, lematt1991.
I didn't see any such a message in my logs. Has that been added in recent versions? For example, using the following commit:

commit 184629a721adf84a4fbd1fd5db8306c49da7685d
Date:   Tue Feb 12 11:23:13 2019 -0800

it seems to me the message is not printed, even if checkpoints are actually saved.
Your question suggest to me that the behaviour I observed is not expected, is it?

**Comment by lematt1991** [comment]
It looks like that logging functionality was added later.  This commit is a bit old (~4 months), you might consider updating if possible.  This may make it easier to debug.

**Comment by cettolo** [comment]
ok, I'll do it. thanks

**Comment by davidecaroselli** [comment]
I'm having the same issue right now, I have latest pytorch 0.6.2. Following my training of issues #781 and #780 , I moved the training on a larger GPU RAM machine and resumed it successfully.

The training resumed from checkpoint 58000:
```
| max tokens per GPU = 1536 and max sentences per GPU = None
| loaded checkpoint /home/ubuntu/training/wd/en__pt/_temp_train/nn_model/checkpoint_last.pt (epoch 2 @ 58000 updates)
| epoch 002:    100 / 25374 loss=3.210, nll_loss=1.496, ppl=2.82, wps=6747, ups=0, wpb=81214.733, bsz=4526.339, num_updates=58101, lr=0.000131192, gnorm=0.213, clip=0.000, oom=0.000, wall=1214, train_wall=137245
```

But the checkpoint saving has stopped at `66000`, while the training is now at `79801`:
```
| epoch 002:  21700 / 25374 loss=3.192, nll_loss=1.478, ppl=2.79, wps=32778, ups=0, wpb=81208.537, bsz=4525.191, num_updates=79701, lr=0.000112013, gnorm=0.210, clip=0.000, oom=0.000, wall=53762, train_wall=188578
| epoch 002:  21800 / 25374 loss=3.192, nll_loss=1.478, ppl=2.78, wps=32781, ups=0, wpb=81207.423, bsz=4525.200, num_updates=79801, lr=0.000111943, gnorm=0.210, clip=0.000, oom=0.000, wall=54004, train_wall=188815
```

Nothing strange is present in the log, but if I look at the checkpoints folder:
```
total 29503848
-rw-rw-r-- 1 ubuntu ubuntu 2517655052 Jun  6 01:34 checkpoint_2_48000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655054 Jun  6 02:55 checkpoint_2_50000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655054 Jun  6 04:17 checkpoint_2_52000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655054 Jun  6 05:38 checkpoint_2_54000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655054 Jun  6 06:59 checkpoint_2_56000.pt
-rw-r--r-- 1 ubuntu ubuntu 2517655237 Jun  6 14:28 checkpoint_2_58000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655687 Jun  6 17:24 checkpoint_2_60000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655637 Jun  6 18:45 checkpoint_2_62000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655641 Jun  6 20:06 checkpoint_2_64000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517656003 Jun  6 21:27 checkpoint_2_66000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517656015 Jun  7 05:34 checkpoint_best.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517656007 Jun  7 05:34 checkpoint_last.pt
```

You can notice that the checkpoint `checkpoint_2_66000.pt` has been saved at `21:27` while best and last at `05:34`. This means that the training has continued updating the last and best checkpoints, but has skipped completely the numerated checkpoints.

How can this be possible? Is there any condition for the training to skip saving checkpoints?

**Comment by davidecaroselli** [comment]
... and just like @cettolo , the training has just started saving checkpoints again now:
```
-rw-rw-r-- 1 ubuntu ubuntu 2517655054 Jun  6 02:55 checkpoint_2_50000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655054 Jun  6 04:17 checkpoint_2_52000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655054 Jun  6 05:38 checkpoint_2_54000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655054 Jun  6 06:59 checkpoint_2_56000.pt
-rw-r--r-- 1 ubuntu ubuntu 2517655237 Jun  6 14:28 checkpoint_2_58000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655687 Jun  6 17:24 checkpoint_2_60000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655637 Jun  6 18:45 checkpoint_2_62000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655641 Jun  6 20:06 checkpoint_2_64000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517656003 Jun  6 21:27 checkpoint_2_66000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655995 Jun  7 09:37 checkpoint_3_84000.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655893 Jun  7 09:12 checkpoint_best.pt
-rw-rw-r-- 1 ubuntu ubuntu 2517655979 Jun  7 09:37 checkpoint_last.pt
```

so there is a gap between 66000 and 84000 updates.

**Comment by myleott** [comment]
I believe this bug was fixed in master, but may be present in the release version. Should be fixed with the next release (very soon...).

**Comment by cettolo** [comment]
Great! Thank you

**Comment by lematt1991** [comment]
It sounds like this has been resolved.  I'm going to close this for now.  Please open a new issue if you are still having trouble.
