### ISSUE TITLE
question about "language_modeling" task

### ISSUE THREAD

**Issue by nicolabertoldi** [pytorch/fairseq#783]
I have a couple of questions about "language_modeling" task; I am sunin gthe "transformer_lm" architecture.

- Which is the training termination policy for the "language_modeling" task?

- Which are reasonably good value for the best_loss and the perplexity, when the training data contains about 4M subtokens and the sub-token dictionary  has about 32K entries?

**Comment by lematt1991** [comment]
The training termination policy is the same as the other tasks:

1. `--min-lr`
2. `--max-epoch`
3. `--max-update`

It's hard to say for your exact setting, but in the [example](https://github.com/pytorch/fairseq/tree/master/examples/language_model) that reproduces [this](https://arxiv.org/pdf/1809.10853.pdf) paper, they report perplexity 18.7

**Comment by nicolabertoldi** [comment]
@lematt1991 

I will try with that setting to reproduce their figures.

**Comment by lematt1991** [comment]
Sounds good!  I'm going to close this issue for now.  Please re-open if you have further questions.
