### ISSUE TITLE
Statistical significance tests?

### ISSUE THREAD

**Issue by jordiae** [pytorch/fairseq#786]
In PyTorch Translate, there is a script (https://github.com/pytorch/translate/blob/master/pytorch_translate/bleu_significance.py) to perform Statistical significance tests for machine translation evaluation as in Koehn, 2004.

Is there any equivalent thing implemented in Fairseq? Alternatively, which would be the most straightforward way of using the PyTorch Translate script within Fairseq generation? AFAIK Fairseq's generate.py outputs the translations along with the BLEU scores and sorted by increasing sequence length, so I'm not sure if the generated translations could be easily input to PyTorch Translate. Ideally, it would be nice to have an option in generate.py to compute the BLEU significance score.

**Comment by myleott** [comment]
We don’t have cycles to work on this at the moment, but would happily take a PR! Ideally this functionality could be integrated into sacrebleu and fairseq could call into it (generate.py already supports sacrebleu).

**Comment by jordiae** [comment]
@myleott Thanks for your answer. If I have time, I'll give it a try.

**Comment by lorelupo** [comment]
Hello, is there any news on this?
