### ISSUE TITLE
pre-trained model doesn't perform well on dataset.

### ISSUE THREAD

**Issue by ToWeRT1An** [pytorch/fairseq#788]
i followed the tutorial on (https://github.com/pytorch/fairseq/blob/master/examples/scaling_nmt/README.md)
first , i download the pretrained model in ./model
secondly , i download the dataset (wmt16 en-de). Then 
1:Extract the WMT'16 En-De data:
`$ TEXT=wmt16_en_de_bpe32k`
`$ mkdir $TEXT`
`$ tar -xzvf wmt16_en_de.tar.gz -C $TEXT`
2:Preprocess the dataset with a joined dictionary:
`$ fairseq-preprocess --source-lang en --target-lang de \
  --trainpref $TEXT/train.tok.clean.bpe.32000 \
  --validpref $TEXT/newstest2013.tok.bpe.32000 \
  --testpref $TEXT/newstest2014.tok.bpe.32000 \
  --destdir data-bin/wmt16_en_de_bpe32k \
  --nwordssrc 32768 --nwordstgt 32768 \
  --joined-dictionary`
3: test the model 
`fairseq-generate data-bin/wmt16_en_de_bpe32k --path model/model.pt --batch-size 128 --beam 5 --remove-bpe >r_generate`
but i got bleu score at only 10.15

however, I test the model on the 'newstest2014 (shared vocab)' dataset provided in the tutorial, the bleu score is 29.15.  So how could this happen? how can I use the pre-trained model on the wmt16 en-de dataset?

**Comment by ToWeRT1An** [comment]
please help me, I have been stuck in the problem for nearly a week.

**Comment by ToWeRT1An** [comment]
@myleott could you please give me some suggestion? Sorry for borthering you. but I really have no idea what's' going on.

**Comment by lematt1991** [comment]
If you want to use the pretrained model, you need to preprocess the data with the same dictionary that was used when the model was trained initially.  If you uncompress the pretrained model, you'll find two dictionaries.  You need to provide one of these to the preprocess script.  

```
fairseq-preprocess --source-lang en --target-lang de \
  --trainpref $TEXT/train.tok.clean.bpe.32000 \
  --validpref $TEXT/newstest2013.tok.bpe.32000 \
  --testpref $TEXT/newstest2014.tok.bpe.32000 \
  --destdir data-bin/wmt16_en_de_bpe32k \
  --nwordssrc 32768 --nwordstgt 32768 \
  --joined-dictionary \
  --srcdict <model_dir>/wmt16.en-de.joined-dict.transformer/dict.en.txt
```

**Comment by ToWeRT1An** [comment]
> that was used when the model was trained initially. If you uncompress the pretrained model, you'll find two dictionaries. You need to provide one of these to the preprocess script.

thanks!!!!! that helps a lot!

**Comment by lematt1991** [comment]
Yes, just be sure to use the en-fr dictionaries that come with the [pre-trained models](https://github.com/pytorch/fairseq/blob/master/examples/scaling_nmt/README.md#pre-trained-models)
