### ISSUE TITLE
the instance order is fixed in round_robin_zip_dataset and multi_corpus_sampled_dataset

### ISSUE THREAD

**Issue by hxbai** [pytorch/fairseq#790]
In these two datasets, self._ordered_indices is set once

so in different epoch, the data instance order is the same.

Is it a bug or a design?

Thanks!

**Comment by myleott** [comment]
Ordered indices controls how the examples are chunked into batches. Once the batches are created we typically keep them fixed, but we iterate over the batches in a different order each epoch. This is done in EpochBatchIterator.next_epoch_itr.
