### ISSUE TITLE
Pretrained embedding file is not found when generate from pretrained model

### ISSUE THREAD

**Issue by lengockyquang** [pytorch/fairseq#795]
Hi fairseq team, i have a pretrained translation model (use pretrain embedding file located with path "drive/data3/emb/word-embv5.2.txt". Then for some reason, i changed embedding filename to word-embv5-nothreshold.txt. Now, when i used generate script to generate translation result from my pretrained model, it gave me this error
![image](https://user-images.githubusercontent.com/45225905/59257510-44c4ad80-8c60-11e9-9f87-fc7cd1e4aec5.png)

Then i solved this error by rename it back to word-embv5.2.txt,
So the question, is there any option to set pretrain emb path for pretrained model ?

**Comment by lematt1991** [comment]
Did you try using `--encoder-embed-path/--decoder-embed-path` (same as when you trained the model)?

**Comment by lengockyquang** [comment]
Yeah, i have tried both options but they are unrecognized arguments.

**Comment by lematt1991** [comment]
How about `--model-overrides '{"encoder_embed_path": "<path_to_embeddings"}'`

**Comment by lengockyquang** [comment]
ohh thanks @lematt1991  it works
