### ISSUE TITLE
Preprocess Error in Multilingual Translation

### ISSUE THREAD

**Issue by madaanpulkit** [pytorch/fairseq#798]
Not able to use pre-processing part of the multilingual translation [example](https://github.com/pytorch/fairseq/tree/master/examples/translation#multilingual-translation) for `de-en,fr-en,de-de,fr-fr` as `--lang-pairs`

ERROR:

> Namespace(alignfile=None, cpu=False, criterion='cross_entropy', dataset_impl='cached', destdir='Method_3/xx.xx.bpe16k/../data-bin/xx.xx.bpe16k', fp16=True, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_format=None, log_interval=1000, lr_scheduler='fixed', memory_efficient_fp16=False, min_loss_scale=0.0001, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=False, optimizer='nag', padding_factor=8, seed=1, source_lang='de', srcdict='Method_3/xx.xx.bpe16k/../data-bin/xx.xx.bpe16k/dict.de.txt', target_lang='de', task='translation', tbmf_wrapper=False, tensorboard_logdir='', testpref=None, tgtdict=None, threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, trainpref='Method_3/xx.xx.bpe16k/train.bpe.de-de', user_dir=None, validpref='Method_3/xx.xx.bpe16k/valid.bpe.de-de', workers=10)
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-preprocess", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-preprocess')()
  File "/content/fairseq/fairseq_cli/preprocess.py", line 265, in cli_main
    main(args)
  File "/content/fairseq/fairseq_cli/preprocess.py", line 62, in main
    raise FileExistsError(dict_path(args.target_lang))
FileExistsError: Method_3/xx.xx.bpe16k/../data-bin/xx.xx.bpe16k/dict.de.txt

This further leads to an error while training.

> Traceback (most recent call last):
  File "/usr/local/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/content/fairseq/fairseq_cli/train.py", line 302, in cli_main
    main(args)
  File "/content/fairseq/fairseq_cli/train.py", line 46, in main
    task.load_dataset(valid_sub_split, combine=True, epoch=0)
  File "/content/fairseq/fairseq/tasks/multilingual_translation.py", line 223, in load_dataset
    for lang_pair in self.args.lang_pairs
  File "/content/fairseq/fairseq/tasks/multilingual_translation.py", line 223, in <listcomp>
    for lang_pair in self.args.lang_pairs
  File "/content/fairseq/fairseq/tasks/multilingual_translation.py", line 211, in language_pair_dataset
    max_target_positions=self.args.max_target_positions,
  File "/content/fairseq/fairseq/tasks/translation.py", line 47, in load_langpair_dataset
    raise FileNotFoundError('Dataset not found: {} ({})'.format(split, data_path))
FileNotFoundError: Dataset not found: valid (Method_3/data-bin/xx.xx.bpe16k/)

>

**Comment by pipibjc** [comment]
The reason is that there is already de dictionary file in the target dictionary, and our pre-processing script doesn't have the assumption that there would be multiple parallel data with the same language in the destination folder.

One quick workaround is to set the destination directory of each language pair to a new folder, and manually copy the .idx/.bin file and the dictionary files into the same data-bin folder.

**Comment by madaanpulkit** [comment]
> The reason is that there is already de dictionary file in the target dictionary, and our pre-processing script doesn't have the assumption that there would be multiple parallel data with the same language in the destination folder.
> 
> One quick workaround is to set the destination directory of each language pair to a new folder, and manually copy the .idx/.bin file and the dictionary files into the same data-bin folder.

There will still be 2 de dictionary files, which one of them should I use?

**Comment by pipibjc** [comment]
We don't support the same language in source and target language use different dictionaries, so please use the same dictionary for both source and target in your `'de-de'` pair. To do that, you can add `--joined-dictionary` in your preprocess command.

After that, the output dict will be exactly the same as the assigned one. So either one is fine.
