### ISSUE TITLE
BacktranslationDataset doesn't work with multiple workers

### ISSUE THREAD

**Issue by hxbai** [pytorch/fairseq#805]
if num_workers > 0, there will be an error:
`AttributeError: Can't pickle local object 'SemisupervisedTranslationTask.build_model.<locals>.backtranslate_fn'`

**Comment by lematt1991** [comment]
Yeah, I'm not sure `BacktranslationDataset` was ever intended to be run with multiple workers since it relies on models that are on the GPU.   cc @pipibjc

**Comment by pipibjc** [comment]
Thanks for reporting! I will need to find some workaround of it. For now we can only use one worker if we want to use `BacktranslationDataset`

**Comment by mnoukhov** [comment]
This is still an issue
