### ISSUE TITLE
Should the output be tokenized each time during iterative translation ?

### ISSUE THREAD

**Issue by ereday** [pytorch/fairseq#806]
I trained two Transformer based NMT model using Fairseq scripts. One for `En ->De` and one for `De->En`.  I would like to use these two systems to translate and backtranslate my english input files. 

This is what I am doing right now: 

```
# To translate from En to De
fn= 'my_english_file.txt'
(1) perl mosesdecoder/scripts/tokenizer/tokenizer.perl  -l en < $fn > ${fn}.tok
(2) python subword-nmt/subword_nmt/apply_bpe.py -c ./bpecodes < ${fn}.tok > ${fn}.tok.bpe 
(3) cat {fn}.tok.bpe | python ./fairseq/interactive.py ../ --remove-bpe --path ../model.pt -s en -t de | tee ./translations_tmp/${fn}.translation
(4) cat ./translations_tmp/${fn}.translation | grep -P '^H-' | sed 's/H-//' | cut -f3- > ./translations/${fn}.translation

```

```
# To translate from De to EN
(5) perl mosesdecoder/scripts/tokenizer/tokenizer.perl  -l de < ./translations/${fn}.translation > ./toks/${fn}.translation.tok
(6) python subword-nmt/subword_nmt/apply_bpe.py -c ../bpe.32000 < ./toks/${fn}.translation.tok > ./${fn}.translation.tok.bpe
(7) cat  ./${fn}.translation.tok.bpe | python ./fairseq/interactive.py ../transformer_big-py/ --remove-bpe --path ../transformer_big-py/model.pt -s de -t en | tee ./translations_tmp/${fn}.back_translation


```

Do I need to again tokenize the output file generated by `interactive.py` before feeding to second NMT system (the step 5 above)?

Another question is about special characters on the output file. When I check the output of interact.py, (output of step 4), I see tokens like `&apos;` `&quot;`. Should I convert those tokens to `&` and `"` before moving to `De to En` translation step  ?

**Comment by lematt1991** [comment]
> Do I need to again tokenize the output file generated by interactive.py before feeding to second NMT system (the step 5 above)?

The output should already be tokenized, however, you will need to BPE-encode it.

> Another question is about special characters on the output file. When I check the output of interact.py, (output of step 4), I see tokens like &apos; &quot;. Should I convert those tokens to & and " before moving to De to En translation step ?

I believe this is a result of [moses tokenization](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/tokenizer/tokenizer.perl#L398), so it should be fine to leave them as is
