### ISSUE TITLE
Replace `resize_` calls

### ISSUE THREAD

**Issue by ailzhang** [pytorch/fairseq#809]
We have some calls to `resize_` in the codebase, e.g https://github.com/pytorch/fairseq/blob/6d1233fa2f0711cb715a3f1466a5efc19732c9f1/fairseq/models/transformer.py#L468. 
However `resize_` can be effectively replaced by pytorch APIs like `reshape` and similar, `resize_` is touching the underlying storage, it might not be the API model is looking for. 
https://pytorch.org/docs/stable/tensors.html#torch.Tensor.resize_

**Comment by ailzhang** [comment]
@dlibenzi @soumith

**Comment by soumith** [comment]
here the correct call is `torch.empty((dim, dim), dtype=self._future_mask, device=self._future_mask)`
