### ISSUE TITLE
fairseq vs pytorch/translate for Torch Script compile and ONNX export

### ISSUE THREAD

**Issue by tsauri** [pytorch/fairseq#824]
Which one should I consider?
I want to compile the whole trained model for small deployments, e.g. laptop with no cuda, jetson nano, etc.

So far fairseq has no consideration for Caffe2 ONNX export -- for example most return use dictionary which is incompatible.
 (whilst pytorch/translate uses tuples).
 How about torch.jit support? for Torch Script compilation?

I want to use pytorch/translate but it is changing a lot, and is not as actively used as fairseq, 

Will both repos be merged in future? Such defragmentation of projects.
pytorch/translate has lots sequence level criterions and rnn-transformer hybrids, and lots of training regimes like semi-supervised and distillations, yet fairseq has convolution architectures not in pytorch/translate, and support more tasks other than translation

**Comment by myleott** [comment]
fairseq is our research framework and includes reference implementations of various papers. translate builds on top of fairseq and includes the other functionality you mentioned (onnx export, distillation, etc.). As you noted, fairseq is a bit broader in scope than translate, which focuses primarily on translation.

In general, any models implemented in fairseq can be used in translate, but not necessarily the other way around. We don't currently have any concrete plans to merge the projects.
