### ISSUE TITLE
wrong amount of examples for task "language modeling"

### ISSUE THREAD

**Issue by nicolabertoldi** [pytorch/fairseq#825]
I observed an odd behavior

I prepared the binary data generated through fairseq-preprocess from a corpus of 1958927 sentence pairs.
Then I used this for a task "translation" and I see in the log that the reported number of the training examples is 1958927 examples.

BUT if  I used the same binary data for a task "language_modeling"; i just changed the names of the binary data to fit the format; the log reports that there are "only" 63058 examples

Why this big difference?
Do the reported figures have different meaning?

**Comment by myleott** [comment]
For language modeling we typically pack sentences together into a single example to improve training efficiency. This is controlled with the `--sample-break-mode` option: https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/language_modeling.py#L62-L67.

If you set `--sample-break-mode=eos` then you should get one sentence per row and the number of examples should match.
