### ISSUE TITLE
Is there any option to replace unknown words using alignments of the attention mechanism

### ISSUE THREAD

**Issue by lengockyquang** [pytorch/fairseq#832]
Hi, I have used OpenNMT-py and they have replace unk option that can replace unk words with words have highest attention weight (http://opennmt.net/OpenNMT/translation/unknowns/). Does fairseq have any option like that ?

**Comment by gvskalyan** [comment]
Use --print-alignment (to give alignment scores) and --replace-unk (uses the alignment scores to replace the '<unk>' token). if your unk format differs change it in data/dictionary.py before preprocessing

**Comment by lengockyquang** [comment]
When i used replace-unk option with fairseq-generate, it gave me this error

> Traceback (most recent call last):
  File "/usr/local/bin/fairseq-generate", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')()
  File "/content/fairseq/fairseq_cli/generate.py", line 188, in cli_main
    main(args)
  File "/content/fairseq/fairseq_cli/generate.py", line 23, in main
    '--replace-unk requires a raw text dataset (--raw-text)'
AssertionError: --replace-unk requires a raw text dataset (--raw-text)

Does i miss something ?

**Comment by gvskalyan** [comment]
Use interactivate.py it does not run this check.

**Comment by lengockyquang** [comment]
so it can't use with fairseq-generate ?

**Comment by gvskalyan** [comment]
Yes

**Comment by lengockyquang** [comment]
I use replace unk with interactive. It runs without error but it seem doesn't replace <unk> with "Quang" (name) 
![image](https://user-images.githubusercontent.com/45225905/60320717-c167c380-99a4-11e9-9b5d-4c6e444b3b71.png)

**Comment by gvskalyan** [comment]
Though I don't get unk in my output without/with giving the flags , even when one of the token is <unk>
![image](https://user-images.githubusercontent.com/42022935/60639913-35d9b100-9e42-11e9-9857-390010a22813.png)

Since I used de-en model output sentence is in English.
@myleott

**Comment by echan00** [comment]
@lengockyquang  @gvskalyan  did you find a solution to this?  I would also like my transformer output to NOT show <unk> and replace it with the source token.

**Comment by lhk** [comment]
also interested.

**Comment by ioannist** [comment]
> Yes

Shouldn't --replace-unk be removed from fairseq-generate since it cannot be used? Is there another use case I am missing?

**Comment by xihajun** [comment]
> Use --print-alignment (to give alignment scores) and --replace-unk (uses the alignment scores to replace the '' token). if your unk format differs change it in data/dictionary.py before preprocessing

thanks

**Comment by xihajun** [comment]
> unk

I have a solution that replaces all the special characters and names to `<unk>`, then the model would learn to predict `unk` we just need one script to replace it by order maybe
