### ISSUE TITLE
why didn't  the saved model size get smaller when I  used the fp16 training?

### ISSUE THREAD

**Issue by wangwang110** [pytorch/fairseq#834]

**Comment by gvskalyan** [comment]
Please recheck whether you are using 2080ti to train the model , if thats not the case even with --fp16 it trains fp32 model and saves it. (with a warning)

**Comment by wangwang110** [comment]
> Please recheck whether you are using 2080ti to train the model , if thats not the case even with --fp16 it trains fp32 model and saves it. (with a warning)

Thank for your answer，I  have solved this problem，and I want to ask another question. 
In the machine translation task, how faster using the fp16 inference than fp32 inference?

**Comment by gvskalyan** [comment]
In CPU, the model is not halved and hence same inference speed whereas in GPU it is halved and inference speed is almost half of fp32's.

please go through these disussions.
https://github.com/OpenNMT/OpenNMT-py/pull/1208
https://github.com/pytorch/fairseq/issues/464

**Comment by huihuifan** [comment]
Thanks @gvskalyan for answering!
