### ISSUE TITLE
Doubt regrading LAMB optimizer

### ISSUE THREAD

**Issue by gvskalyan** [pytorch/fairseq#836]
It is claimed that this optimizer helps in `Reducing BERT Pre-Training Time from 3 Days to 76 Minutes`
Did anyone here try this?
If, then please share ADAM vs LAMB stats and lamb betas plus the large batch size / no of words which proved to be effective

**Comment by myleott** [comment]
We ran some preliminary experiments with it but did not find it to be helpful. It is also based on an old version of the preprint and I believe the algorithm has changed slightly in more recent versions -- we should probably remove it until it is confirmed that it works properly.

**Comment by gvskalyan** [comment]
Thank you.

**Comment by GabboM** [comment]
Any updates on LAMB optimizer?
