### ISSUE TITLE
The problem of train

### ISSUE THREAD

**Issue by breeef** [pytorch/fairseq#837]
![1](https://user-images.githubusercontent.com/16204293/60230942-3914f000-98ca-11e9-9618-bff947b22c52.png)
This process has been here for more than 10 hours without error. There are no files in the chickpoints directory. I checked that only one GPU is in use. Does it stop here because of the bug of multiple GPUs?

**Comment by breeef** [comment]
By the way, I'm using this version:v0.6.0,fairseq @ 864b89d

**Comment by breeef** [comment]
It's from this project:pytorch-human-performance-gec

**Comment by breeef** [comment]
I seem to have found out why when tried run on single gpu.
Is it because my dictionary is too big? I've minimized token and batch size
![image](https://user-images.githubusercontent.com/16204293/60237280-543d2b00-98dd-11e9-82a2-a12e06c7f665.png)

**Comment by gvskalyan** [comment]
If possible please use the latest version of fairseq 0.7.1 but there seems no issue with Multiple GPU s in 0.6.0 else restart the process.
It is advisable to use --max-tokens around 4k or 3k . There are around 223 Million train sentences ! It would take time to train and epoch save checkpoints.

**Comment by ShilinHe** [comment]
Did you use the bpe to reduce the dictionary size?

**Comment by breeef** [comment]
Problem solved, I tried to limit the --nwordssrc/tgt when use the preprocess.py scripts,800k is too big

**Comment by wulouzhu** [comment]
@breeef 
Did you use this project:pytorch-human-performance-gec  for Chinese grammatical error correction?

**Comment by breeef** [comment]
> @breeef
> Did you use this project:pytorch-human-performance-gec for Chinese grammatical error correction?

你做中文纠正数据没问题就基本ok，我做的中文到中文的转述效果还行
