### ISSUE TITLE
The function (convert_padding_direction) in (fairseq/utils.py) does not work properly

### ISSUE THREAD

**Issue by vineetk1** [pytorch/fairseq#840]
def convert_padding_direction(src_tokens, padding_idx, right_to_left=False, left_to_right=False) in [https://github.com/pytorch/fairseq/blob/master/fairseq/utils.py](url) does not work properly

If src_tokens is left-padded and (left_to_right is True) and (right_to_left is False) then src_tokens should not be changed because it is already left-padded. However, the function returns with src_tokens as right-padded.

**Example of left-padding**: If a sequence [4, 7, 9, 2] is left-padded then it becomes [1, 1, 4, 7, 9, 2], assuming the padding_idx is 1

If I am right then the following code, in Lines 197 through 202, should be replaced:
`if left_to_right and not pad_mask[:, 0].any():
        # already right padded
        return src_tokens
    if right_to_left and not pad_mask[:, -1].any():
        # already left padded
        return src_tokens`

The suggested replacement code is as follows:
`if left_to_right and pad_mask[:, 0].any():`
`     # already left padded`
`        return src_tokens`   
`    if right_to_left and pad_mask[:, -1].any():`
`        # already right padded`
`        return src_tokens`  
`    if not pad_mask[:, 0].any() and not pad_mask[:, -1].any():`
`        # not padded`
`        return src_tokens`

**Comment by myleott** [comment]
> If src_tokens is left-padded and (left_to_right is True) and (right_to_left is False) then src_tokens should not be changed because it is already left-padded.

That's incorrect. When `left_to_right=True` we expect the input to be left-padded and will return a right-padded result (i.e., we convert from left-padded to right-padded).

See the unit tests here for examples: https://github.com/pytorch/fairseq/blob/master/tests/test_utils.py#L17-L45
