### ISSUE TITLE
In function (forward) of file (fairseq/models/lstm.py), line 211 takes only one condition into account

### ISSUE THREAD

**Issue by vineetk1** [pytorch/fairseq#841]
In file [https://github.com/pytorch/fairseq/blob/c86d70cc2f1c2276725497519c69e5e97f80c36c/fairseq/models/lstm.py](url), function def forward(self, src_tokens, src_lengths), and line # 211, only one condition is taken into account.  In addition to checking for (self.left_pad is True), also check for (self.left_pad is False)

Suggestion is to replace lines 211 through 217 with the following code:
`        if self.left_pad:
            # convert left-padding to right-padding
            src_tokens = utils.convert_padding_direction(
                src_tokens,
                self.padding_idx,
                left_to_right=True,
            )`
`        else:
            # convert right-padding to  left-padding
            src_tokens = utils.convert_padding_direction(
                src_tokens,
                self.padding_idx,
                right_to_left=True,
            )`

Sorry , that the indentation in code is not showing up.

FYI: src_tokens have already been padded correctly before they are passed in the function "def forward(self, src_tokens, src_lengths):". So, there is no reason to check whether src_tokens is padded correctly. An assert may be more appropriate.

**Comment by myleott** [comment]
fairseq generally pads the source sentences on the left. However, `pack_padded_sequence` requires padding to be on the right, so we convert inside the forward. We expose `left_pad` as an option in case the user has already passed in right-padded input and wants to avoid the conversion.

**Comment by vineetk1** [comment]
The PyTorch document on pack_padded_sequence has no information regarding a requirement that padding must be on the right. To avoid others from asking the same question, this information should be in the form of a comment in the code.

**Comment by myleott** [comment]
Good point, do you mind submitting a PR?

**Comment by vineetk1** [comment]
submitted
