### ISSUE TITLE
Question: what is the batch size for the wav2seq pretrained model.

### ISSUE THREAD

**Issue by wanglouis49** [pytorch/fairseq#842]
In section 3.4 in the wav2vec paper, it says the model is pretrained for 400k steps with 8 gpus. I am curious what is the batch size for each gpu? I couldn't find this information in the wav2vec example here, either.

**Comment by wanglouis49** [comment]
Also, is the pretrained module freezed during finetuning or its parameters are allowed to change?

**Comment by huihuifan** [comment]
@alexeib ?

**Comment by wanglouis49** [comment]
Any follow-up?

**Comment by stephen-song** [comment]
also confused about it.

**Comment by wanglouis49** [comment]
The default batch size per gpu is 8. I ran it and used pdb to check.

**Comment by shamanez** [comment]
> In section 3.4 in the wav2vec paper, it says the model is pretrained for 400k steps with 8 gpus. I am curious what is the batch size for each gpu? I couldn't find this information in the wav2vec example here, either.

Hi, what do you mean by 400k steps? Are that epochs?

**Comment by wanglouis49** [comment]
> > In section 3.4 in the wav2vec paper, it says the model is pretrained for 400k steps with 8 gpus. I am curious what is the batch size for each gpu? I couldn't find this information in the wav2vec example here, either.
> 
> Hi, what do you mean by 400k steps? Are that epochs?

No, I think it means 400k steps of mini-batches fed into the model during training.

**Comment by rajeevbaalwan** [comment]
> In section 3.4 in the wav2vec paper, it says the model is pretrained for 400k steps with 8 gpus

here how 400k steps is considered. if we train on 8 GPU with batch size 8 then progress bar during training show num_update parameter updated by 1 value in 1 iteration but effectively it should be increased by 8  because in 1 iteration the update is done parallely on 8 batches. if this is the scenario then should we train for 400K/8 i.e 50K update steps or not ????
