### ISSUE TITLE
[Feature Request] Enable freeze part of the parameters when training

### ISSUE THREAD

**Issue by fuzihaofzh** [pytorch/fairseq#845]
Since fairseq uses pytorch's parallel tool to train. It requires that all parameters are involved. Is it possible to freeze part of the parameters and train the model on multi GPUs? Maybe we can give some callback function for the optimizer.

**Comment by lematt1991** [comment]
Happy to take a PR!

**Comment by robotsp** [comment]
@fuzihaofzh , have you solved your problem? I have a similar problem on freezing params using fairseq transformer.

**Comment by fuzihaofzh** [comment]
@robotsp unfortunately, no. I guess it may not be an easy fix for fairseq?

**Comment by robotsp** [comment]
@fuzihaofzh may I know what's the root cause? Thanks
