### ISSUE TITLE
Odd behavior in 0.7.1: load_state_dict()

### ISSUE THREAD

**Issue by davidecaroselli** [pytorch/fairseq#846]
Hello team!

I'm trying to port our machine translation solution ([ModernMT](https://github.com/modernmt/modernmt)) to newest 0.7.1, but we found a big problem.
I'll try to keep it as short as possible: with ModernMT we do real-time adaptation, in other words we reset the model to its initial state reading the parameters from a "state dict":
```python
self._model.load_state_dict(checkpoint.state, strict=True)
```

We use this also to switch between different languages (translate en>it, load_state_dict(), translate en>de). It all worked as expected with version 0.6.2, but now the model seems to remain always the same after the first reset.

Are you aware of any change that could break this process? Are the old (0.6.2) checkpoints 100% compatible with new ones?

Thanks for your help!

**Comment by davidecaroselli** [comment]
Turns out it was a really really unlucky problem with new `task.args.data` format change form `array` to `string`.

Sorry for having opened a misleading issue!

**Comment by myleott** [comment]
Glad you figured it out! I missed that change in the release notes, sorry about that :/
