### ISSUE TITLE
Continue training shoud begin at N+1

### ISSUE THREAD

**Issue by fuzihaofzh** [pytorch/fairseq#848]
I just found the epoch counting method may not proper. For example, we start from chechpoint at epoch 10, then the current method will train epoch 10 again. However, it should start at epoch 11. I will submit a pull request to fix this.

**Comment by myleott** [comment]
You closed the PR, is this resolved? One tricky part about resuming is that we want to support resuming in the middle of an epoch (in which case you don't increment the counter) and resuming from an end-of-epoch checkpoint (in which case we should increment). I thought it worked properly, but please confirm.

**Comment by fuzihaofzh** [comment]
I found that. For this setting, the code is good. Just wondering this setting is somehow confusing. why resuming in the middle of an epoch without increment the counter?

**Comment by myleott** [comment]
For example if you have a long-running job and it's interrupted, then you may want to resume to where you were.
