### ISSUE TITLE
too long startup time on a machine  with multiple GPUs

### ISSUE THREAD

**Issue by nicolabertoldi** [pytorch/fairseq#850]
I need to train a transformer_big on one AWS machine (p3.16xlarge), which has 8 GPU NVIDIA Tesla V100 on board.
I am using ``--fp16`` and ``--ddp-backend no_c10d`` parameters.

At the beginning, the process starts correctly and at the end of the log is printed the following
```
| distributed init (rank 1): tcp://localhost:16344
| distributed init (rank 6): tcp://localhost:16344
| distributed init (rank 5): tcp://localhost:16344
| distributed init (rank 3): tcp://localhost:16344
| distributed init (rank 0): tcp://localhost:16344
| distributed init (rank 2): tcp://localhost:16344
| distributed init (rank 7): tcp://localhost:16344
| distributed init (rank 4): tcp://localhost:16344
```

But after more than 5 hours, the process does not output anything in the log; so I suppose it is still in a setup phase.
Note that:
- both CPUs and GPUs are working at maximum rate (around 100%)
- the same training run on a different 8-GPU machine (GEForce GTX 1080 Ti) works well, and after less than 1 hour,  the process starts output the log information like
```
epoch 001:    100 / 22049 loss=13.682, nll_loss=13.444, ppl=11143.65, wps=8264, ups=0.1, wpb=83506, bsz=3835, num_updates=98, lr=1.23476e-05, gnorm=2.459, clip=0%, oom=0, loss_scale=16.000, wall=990, train_wall=293
| epoch 001:    200 / 22049 loss=12.734, nll_loss=12.379, ppl=5326.90, wps=12874, ups=0.2, wpb=83483, bsz=3854, num_updates=198, lr=2.48451e-05, gnorm=1.754, clip=0%, oom=0, loss_scale=16.000, wall=1284, train_wall=579
```
- the same training run on a AWS p3.2xlarge (similar to p3.16xlarge but with only 1 GPU) runs properly and starts update after less then 20 minutes.

I have a few questions:
- do you have any idea why the process takes so much time to start on AWS p3.16xalrge?
- what fairseq does in the phase ``distribute init``?
- does ``--fp16`` have an effect on the startup time, i.e. the time before starting the update phase?
- what parameter ``--ddp-backend no_c10d`` does?
- does ``--ddp-backend no_c10d`` have an effect on the startup time, i.e. the time before starting the update phase?

**Comment by myleott** [comment]
This is what happens in distributed_init: https://github.com/pytorch/fairseq/blob/master/fairseq/distributed_utils.py#L68-L92.

Please add some debug logging/prints to see where it's actually hanging -- e.g., is it having trouble communicating with the other GPUs, or is it loading data?

I've used p3.16xlarge before with Amazon's Deep Learning AMI and not had issues, in case that's a helpful data point.

**Comment by nicolabertoldi** [comment]
unfortunately I have no additional messages in the log but what I reported above
```
| distributed init (rank 1): tcp://localhost:16344
...
| distributed init (rank 4): tcp://localhost:16344
```


so I suppose, it is working on this piece of code
```
        dist.init_process_group(
            backend=args.distributed_backend,
            init_method=args.distributed_init_method,
            world_size=args.distributed_world_size,
            rank=args.distributed_rank,
        )
```

Note that If I use a p3.8xlarge (with 4GPU) activating only 2 of them (through CUDA_VISIBLE_DEVICES) the startup time is reasonable and close to what I measured on a single-gpu p3.2xlarge.

**Comment by libeineu** [comment]
This problem may occur due to the wrong matching between the version of PyTorch and Fairseq. And if the matching was wrong, FP16 training may be very slow. Your log has shown that the wps=8264, which is abnormal. It should be 60K~70K words per second.

**Comment by nicolabertoldi** [comment]
@libeineu 
versions fo PyTorch and Fairseq are the same on p3.2xlarge and p3.16xlarge, because I used the same "image" on AWS and just changed the instance type.


The first reported wps (8264) is very low because this score includes a sort of startup time.
Actually the wps without this initial time is about 28K, which is a quite reasonable time for the machine I worked on.

**Comment by jiezhangGt** [comment]
> This problem may occur due to the wrong matching between the version of PyTorch and Fairseq. And if the matching was wrong, FP16 training may be very slow. Your log has shown that the wps=8264, which is abnormal. It should be 60K~70K words per second.

Hello，wps should be 60~70k words per second? while my wps=40K， is that normal？Look forward to your reply，thank you very much!

**Comment by libeineu** [comment]
the wps depends on the batch size and your model size.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Jay Zhang <notifications@github.com>
发送时间: Wednesday, July 31, 2019 1:27:42 PM
收件人: pytorch/fairseq <fairseq@noreply.github.com>
抄送: LiBei <libei_neu@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [pytorch/fairseq] too long startup time on a machine with multiple GPUs (#850)


This problem may occur due to the wrong matching between the version of PyTorch and Fairseq. And if the matching was wrong, FP16 training may be very slow. Your log has shown that the wps=8264, which is abnormal. It should be 60K~70K words per second.

Hello，wps should be 60~70k words per second? while my wps=40K， is that normal？Look forward to your reply，thank you very much!

―

**Comment by Shujian2015** [comment]
Hi @nicolabertoldi , have you solved the issue? I have exactly the same problem with Google Cloud 8-v100 GPU node.

**Comment by Shujian2015** [comment]
I found this help: https://github.com/pytorch/fairseq/issues/1171#issuecomment-534981208 
with `--num-worker 1`.

**Comment by lematt1991** [comment]
Sounds like this is resolved.
