### ISSUE TITLE
fairseq-interactive and fairseq-generate for language modeling task

### ISSUE THREAD

**Issue by nicolabertoldi** [pytorch/fairseq#854]
which is the actual goal of the two commands ``fairseq-interactive`` and ``fairseq-generate`` in case of language modeling task?

**Comment by myleott** [comment]
`fairseq-generate` is for batched data and `fairseq-interactive` is for streaming data (and interactive use). Otherwise they are very similar.

**Comment by nicolabertoldi** [comment]
@nicolabertoldi 

This was clear.

What was less clear is the following: are these commands used to create new text from a given seed text?
Since I suppose the answer is yes, I have a follow up question: how is it possible to force the continue a sentence ending with a strong punctuation?

I tried to continue such a sentence *Hello !*, but the process does not generate any new word.

Should I set some parameter differently from the default?

**Comment by Nagoudi** [comment]
> `fairseq-generate` is for batched data and `fairseq-interactive` is for streaming data (and interactive use). Otherwise they are very similar.

Hi, Any suggestions are welcome @myleott 
I've the same question of  @nicolabertoldi

1- I trained my model (wikitext-103) as illustrated here: [](https://github.com/pytorch/fairseq/blob/master/examples/language_model/README.md#2-train-a-language-model).

2- Then, I evaluated my model: 
( https://github.com/pytorch/fairseq/tree/master/examples/language_model#3-evaluate )

3- Now, I want to use this model to generate some sentences using **fairseq-generate**  (As the language modeling task is compatible with :mod:`fairseq-train`,  `fairseq-generate` , and :mod:`fairseq-eval-lm)

See : https://github.com/pytorch/fairseq/blob/810e61ab3ffba169a47d7e72538e082d2467f2b4/fairseq/models/fairseq_model.py#L150 



So how is it possible to  continue a sentence  if I provide  the words "barack obama"   using **fairseq-generate**

PS: 
I used this method but he didn't work 

from fairseq.models.transformer_lm import TransformerLanguageModel
custom_lm = TransformerLanguageModel.from_pretrained('/path/to/model/dir', 'checkpoint100.pt', tokenizer='moses', bpe='fastbpe')
custom_lm.sample('Barack Obama', beam=5) 

Thanks

**Comment by mhagiwara** [comment]
@Nagoudi Did you try `fairseq-interactive`? You can do, for example:

```
fairseq-interactive /path/to/bin/dir \
  --task language_modeling \
  --path /path/to/checkpoint.pt \
  --sampling --beam 1```

And just type "Barack Obama". The command will generate the rest. You can even supply the prefixes from stdin.

**Comment by lqniunjunlper** [comment]
@mhagiwara How to use fairseq generate new sentence give some words with raw txt input file instead of stdin

**Comment by mhagiwara** [comment]
@lqniunjunlper try the `--prefix-size` option with fariseq generate
