### ISSUE TITLE
Using fairseq-interactive to translate one sentence at a time outside terminal

### ISSUE THREAD

**Issue by sharad461** [pytorch/fairseq#858]
I want to write a Python script that loads a checkpoint file once and waits for inputs and translates when input is received. It will be the same as running fairseq-interactive in the terminal and inputting sentences one by one, but here it will be done in a Python file.

Something like the Python Hub example in https://github.com/pytorch/fairseq/tree/master/examples/translation. I think fairseq.tasks.translation.TranslationTask is what I'm looking for, but there's not enough details to implement it. An example would help. 

I'm new to PyTorch.

**Comment by sharad461** [comment]
I accomplished it by modifying interactive.py. If anyone knows a better way, do write.

**Comment by huihuifan** [comment]
I think your way sounds good!

**Comment by PeteSolid** [comment]
@sharad461 So how did you do it??

**Comment by sharad461** [comment]
https://github.com/sharad461/nepali-translator/blob/master/translator/app/modules/interactive.py

I made a class for the job that interactive.py does. There is also a usage example towards the end.

**Comment by amanag1** [comment]
@sharad461  As here https://github.com/sharad461/nepali-translator/blob/master/translator/app/modules/interactive.py you had created a class and post which you are calling method but it will call the constructor again and again whenever there is any call having '**fairseq-interactive $BPE_TXT --batch-size 1 --path $MODEL_FILE --fixed-dictionary $DICT -s $SRC -t $TGT --remove-bpe 'sentencepiece' --beam 5 --task translation_multi_simple_epoch --lang-pairs $LANG_PAIR --decoder-langtok --encoder-langtok src**'.
How could we resolve that?

**Comment by sharad461** [comment]
I wouldn't be surprised if my solution doesn't work anymore - it's almost 3 years old now. By this time maybe there's a better way to do it, one offered by fairseq itself perhaps.
