### ISSUE TITLE
Error occurs when Learning-rate goes to zero

### ISSUE THREAD

**Issue by vineetk1** [pytorch/fairseq#863]
Error occurs when Learning-rate goes to zero. See the trace below:

| epoch 523:   6%| | 1/16 [00:00<00:03,  4.24it/s, loss=1.355, nll_loss=0.432, ppl=1.35, wps=1406, ups=0, wpb=2931.000, bsz=512.000, num_updates=8353, lr=0, gnorm=0.030, clip=0.000, oom=0.000, wall=9258, train_wall=1648]Traceback (most recent call last):
  File "/usr/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/usr/lib/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/vin/fairseq/train.py", line 306, in <module>
    cli_main()
  File "/home/vin/fairseq/train.py", line 302, in cli_main
    main(args)
  File "/home/vin/fairseq/train.py", line 78, in main
    while lr > args.min_lr and epoch_itr.epoch < max_epoch and trainer.get_num_updates() < max_update:
  File "/home/vin/fairseq/train.py", line 121, in train
    log_output = trainer.train_step(samples)
  File "/home/vin/fairseq/fairseq/trainer.py", line 347, in train_step
    self.optimizer.step()
  File "/home/vin/fairseq/fairseq/optim/fairseq_optimizer.py", line 91, in step
    self.optimizer.step(closure)
  File "/home/vin/fairseq/fairseq/optim/nag.py", line 70, in step
    lr_correct = lr / lr_old
ZeroDivisionError: float division by zero
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/vin/fairseq/fairseq/optim/nag.py(70)step()
-> lr_correct = lr / lr_old

**Comment by lematt1991** [comment]
Can you provide the command that was used to reproduce this result?

**Comment by vineetk1** [comment]
CUDA_VISIBLE_DEVICES=0 python3 train.py --task dialog_task data-bin/dialog/task1 --arch lstm_dialog --save-dir checkpoints/dialog/task1 --max-tokens 200 --required-batch-size-multiple 1 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --optimizer nag --lr-scheduler fixed --force-anneal 200 --lr 0.25 --clip-norm 0.1

Let me know if you need more information

**Comment by vineetk1** [comment]
What is the status of this issue?

**Comment by lematt1991** [comment]
I think the easiest way around this is to set `--min-lr` to some small non-zero value.  This way training will stop once the learning rate gets too small and will avoid the divide by zero.

**Comment by vineetk1** [comment]
That is what I have been doing. I am assuming that sometime in future this issue will be resolved.
