### ISSUE TITLE
--decoder-langtok doesn't work in multilingual translation

### ISSUE THREAD

**Issue by OneMoreSecond** [pytorch/fairseq#864]
I'm training a one-to-many multilingual translation model with ```--decoder-langtok``` option.
However, in inference time the output can't be controlled by the ```--target-lang``` and the first token in source sentence seems often ignored by the model.
So I think ```--decoder-langtok``` doesn't work in training.

Line 219 in ```fairseq/tasks/multilingual_translation.py``` seems strange.
``` python
            return self.alter_dataset_langtok(
                langpair_dataset,
                src_eos=self.dicts[tgt].eos(),
                # why is tgt eos passed as src eos and no tgt eos passed?
                src_lang=src,
                tgt_lang=tgt,
            )
```

Also ```--decoder-langtok``` doesn't work in ```alter_dataset_langtok``` function because ```tgt_eos``` argument is never passed, which might cause training/test decoder BOS mismatching. If I disable ```--decoder-langtok``` in ```inference_step``` function, the model can give reasonable translation though language not controlled.

**Comment by pipibjc** [comment]
You are right. I messed it up in previous commit. I am fixing it.

**Comment by lematt1991** [comment]
This should be resolved now.
