### ISSUE TITLE
can't understand the meaning of parameters?

### ISSUE THREAD

**Issue by wangwang110** [pytorch/fairseq#866]
in the fconv saved models, I find these parameters, I  can understand "encoder.fc1.weight_v",
"encoder.fc1.bias", but I am confused about "encoder.fc1.weight_g"

the sizes of " encoder.fc1.weight_g , encoder.fc1.weight_v, encoder.fc1.bias" are 
torch.Size([1024, 1])
torch.Size([1024, 500])
torch.Size([1024])

what the "encoder.fc1.weight_g" means ?

**Comment by myleott** [comment]
The `_g` and `_v` versions come from weight norm: https://pytorch.org/docs/master/nn.html#torch.nn.utils.weight_norm
