### ISSUE TITLE
Interactive.py don't run on multiGPU as well as not recognizing GPU (1,2,3)

### ISSUE THREAD

**Issue by jalajthanaki** [pytorch/fairseq#874]
Hi,

I'm new to fairseq library. 

I'm trying to run `interactive.py` for generating translation hypothesis. I have 4 GPUs. I wanted to use GPU number 1 for running interactive.py. I have set the flag CUDA_VISIBLE_DEVICE=1 but interactive.py doesn't consider GPU number 1. This is same if I set GPU number to 2 or 3. Interactive.py. Whenever I set CUDA_VISIBLE_DEVICE=1 or 2 or 3 script failed to recognized the GPUs and it is starting using CPU

Here is the command that I'm trying to execute.
`CUDA_VISIBLE_DEVICE=1 python3.6 ./checkpoint_best.pt --beam $value --nbest $value  --source-lang src --target-lang trg --buffer-size 10 --batch-size 10 <input.txt > output.txt
`

Please note that when I set CUDA_VISIBLE_DEVICE=0 script is running perfectly. 
`CUDA_VISIBLE_DEVICE=0 python3.6 ./checkpoint_best.pt --beam $value --nbest $value  --source-lang src --target-lang trg --buffer-size 10 --batch-size 10 <input.txt > output.txt
`

What if I want to run interactive.py on multi-GPUs?
- I have tried setting multiple GPUs as CUDA_VISIBLE_DEVICE but it uses only one GPU instead of multiple GPUs. The GPU number is GPU-0 which script can recognize.

`CUDA_VISIBLE_DEVICE=0,1,2,3 python3.6 ./checkpoint_best.pt --beam $value --nbest $value  --source-lang src --target-lang trg --buffer-size 10 --batch-size 10 <input.txt > output.txt
`
Is there anything I'm missing?

Any help is much appreciated.

**Comment by nicolabertoldi** [comment]
to my knowledge, the directive is 
CUDA_VISIBLE_DEVICES
and not
CUDA_VISIBLE_DEVICE

all the following work properly
CUDA_VISIBLE_DEVICES=0
CUDA_VISIBLE_DEVICE=1,2

**Comment by huihuifan** [comment]
Generation only runs on 1 gpu. To run on multiple GPUs, you can launch multiple commands setting the --shard-id and --num-shards arguments

**Comment by ZhenYangIACAS** [comment]
Could you please give an example for doing inference on multiple GPUs?

**Comment by tuzhucheng** [comment]
Looking at the code it seems `interactive.py` doesn't current supports shards, but `generate.py` does.
