### ISSUE TITLE
wave2vec: Can we directly download a pretrained model ?

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#878]

**Comment by huihuifan** [comment]
@alexeib ?

**Comment by alexeib** [comment]
We will make some models available in a few weeks

**Comment by lingss0918** [comment]
Any updates on this? Really want to try it. @alexeib

**Comment by lematt1991** [comment]
Looks like [this has been resolved](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec)
