### ISSUE TITLE
In fairseq Version 0.7.1, whether multiple GPUs can only share one copy of data in memory

### ISSUE THREAD

**Issue by dongdaoking** [pytorch/fairseq#880]

**Comment by myleott** [comment]
Is your goal to improve memory usage and/or train on larger datasets?

If you use `--dataset-impl lazy --fix-batches-to-gpus` then each process should only load the data it needs.

Alternatively you should also try `--dataset-impl mmap`. That will require preprocessing your dataset again (with `fairseq-preprocess --dataset-impl mmap (...)`), but will significantly reduce memory usage and maybe also storage requirements.

Finally you can simply split your data and pass a colon-separated list of dataset as the `data` argument. Fairseq will cycle over each split as if it were an epoch. For example `fairseq-train data-dir1:data-dir2:data-dir3 (...)`

**Comment by dongdaoking** [comment]
Yes, i need to load larger datasets for multiple GPUs. Your ideas help a lot and thanks for your reply.

**Comment by BinWone** [comment]
> Finally you can simply split your data and pass a colon-separated list of dataset as the `data` argument. Fairseq will cycle over each split as if it were an epoch. For example `fairseq-train data-dir1:data-dir2:data-dir3 (...)`

I train by this way `fairseq-train dataset1:dataset2`, it returns a error `FileNotFoundError: [Errno 2] No such file or directory: 'dataset1:dataset2/dict.en.txt'`, it seems that not split the data dir.

**Comment by echan00** [comment]
Hi @myleott, I was having memory problems and able to use `--dataset-impl lazy --fix-batches-to-gpus` successfully on a 7-gpu server w/ 24GB of memory.

The problem I have now is that training is very slow (24 hours per half an epoch). What is the difference between the two arguments? Or do you have any other suggestions?

**Comment by myleott** [comment]
This is quite stale. We've since introduced `--dataset-impl=mmap`, which is the default. Please preprocess your data using the latest fairseq and it should scale much better with large datasets.
