### ISSUE TITLE
Strategies for Structuring Story Generation code

### ISSUE THREAD

**Issue by mcshen99** [pytorch/fairseq#881]
i recently read [this article]( https://arxiv.org/pdf/1902.01109.pdf ) and was interested in the model updates of the model from the paper. i was wondering if there were any plans to release the code for the experiments in this paper.

**Comment by huihuifan** [comment]
Thanks for your interest! We are working on it. In the meantime, if you have questions, please feel free to open an issue or send me an email. Thanks!

**Comment by bigheiniu** [comment]
Hi Fan,
Thanks for your work in the story generation. When will you release the code for this paper?

**Comment by lfthwjx** [comment]
Any update on the code release? @huihuifan Thanks!
