### ISSUE TITLE
is the attention in dynamic conv better than original attention mechanisms

### ISSUE THREAD

**Issue by zhaoguangxiang** [pytorch/fairseq#883]
how about  directly substitute the attention of the tranformer by the dynamic conv?

**Comment by zhaoguangxiang** [comment]
it can save many parameters

**Comment by zhaoguangxiang** [comment]
is glu useful for the original transformer model

**Comment by huihuifan** [comment]
We use the dynamic and light conv to replace self-attention. We did not try replacing attention completely, but would be very interested in the results if you try it! 

For GLU, we found it could be useful for computing self attention mechanisms, see: https://arxiv.org/abs/1805.04833
