### ISSUE TITLE
*Help* when I add a new model and I using multi-gpu does not work and keep salient.

### ISSUE THREAD

**Issue by PlayDeep** [pytorch/fairseq#884]
when I add a new model, I set multi-GPU but the program will be salient and not given any information. and then I using the default model transformer will work correctly. I have try to debug this problem and check my implement which is follow transformer. Have any information can help me to check or debug?

**Comment by huihuifan** [comment]
What do you mean, the program doesn't give any information? I need more details

**Comment by PlayDeep** [comment]
@huihuifan like this log file, it is waiting something in a long time. 
![image](https://user-images.githubusercontent.com/12473617/62509034-3e0b7e80-b83c-11e9-9329-9d2919a25e1e.png)

**Comment by huihuifan** [comment]
does it run if you use 1 gpu? there's many potential reasons- one that often happens is the two gpus are not in sync. for example, if one process on one gpu runs out of memory, the other waits for it. can you check this by potentially reducing the batchsize, using nvidia-smi to track, setting the log interval to 1 to see if the model starts training at all, etc

**Comment by edunov** [comment]
I'd also suggest to scale it down first, you have 370M parameters, which is not huge, but is a lot, try smaller and simpler model for debugging, make sure the dataset size is also small. If you still see the issue, consider sharing your code

**Comment by PlayDeep** [comment]
@huihuifan @edunov Thank you for your insight comment  which is useful.
