### ISSUE TITLE
wav2vec : The training script wav2vec fails with the following bash error

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#885]
It seems the error caused by  "--conv-feature-layers" argument.

**"bash: syntax error near unexpected token `('"**

**Comment by huihuifan** [comment]
@alexeib

**Comment by martini9393** [comment]
You may want to try: 
```
--conv-feature-layers "[(512, 10, 5), (512, 8, 4), (512, 4, 2), (512, 4, 2), (512, 4, 2), (512, 1, 1), (512, 1, 1)]"
```
similar for `--conv-aggregator-layers`.

**Comment by wahyubram82** [comment]
it's still error with :
`--conv-feature-layers "[(512, 10, 5), etc....`
or 
`--conv-aggregator-layers "[(512, etc.....`

any suggest?
