### ISSUE TITLE
In the machine translation task, how faster using the fp16 than fp32 in inference step?

### ISSUE THREAD

**Issue by wangwang110** [pytorch/fairseq#886]

**Comment by gvskalyan** [comment]
Please refer this https://github.com/pytorch/fairseq/issues/834

**Comment by edunov** [comment]
Depends on whether you're doing it on CPU or GPU. On CPU it is not faster at all. On GPU I see speedup roughly comparable to what we see during training 2-3x, but it also depends on the model and batch size.
