### ISSUE TITLE
change "self.left_pad" from True to False after "src_tokens" is converted from left-pad to right-pad

### ISSUE THREAD

**Issue by vineetk1** [pytorch/fairseq#887]
Lines 211 through 218 in [https://github.com/pytorch/fairseq/blob/master/fairseq/models/lstm.py](url) convert **src_tokens** from left-padded to right-padded. However, **self.left_pad** is not changed from True to False.
Suggestion is to add a new line between existing lines 218 and 219 within the if-block. This new line will have the following content:
self.left_pad = False

**Comment by huihuifan** [comment]
Can you make a pull request?

**Comment by vineetk1** [comment]
Pull Request submitted

**Comment by myleott** [comment]
Left comments in #893 😄
