### ISSUE TITLE
patience to support early stopping

### ISSUE THREAD

**Issue by gvskalyan** [pytorch/fairseq#897]
Please support patience to stop early without waiting for max no of epochs.

Since there are multiple validation losses for various subsets but based on first element of the list checkpoint is saved, similarly based on it, can patience be implemented in the repo?

Else instead of returning if no-save-checkpoint as soon as it enters save_checkpoint in [checkpoint_utils](https://github.com/pytorch/fairseq/blob/master/fairseq/checkpoint_utils.py#L27)  calculate is the new valid_losses[0] is best or not and increment a counter and early stop once it exceeds the counter as in https://github.com/RayeRen/multilingual-kd-pytorch/blob/master/train.py#L126

**Comment by gvskalyan** [comment]
https://github.com/pytorch/fairseq/pull/904

**Comment by myleott** [comment]
Added in 1512a0e6213c9a84c5bb1eb918147bd6e96092cd
