### ISSUE TITLE
Reproduce Billion Word benchmark for paper by Baevski and Auli, 2018.

### ISSUE THREAD

**Issue by yilegu** [pytorch/fairseq#898]
There is only example on how to run for WikiText-103, but not Billion Word, for the adaptive input paper by Baevski and Auli, 2018.

There is a difference between the two, as Billion Word is of short sentences. Can anyone help out?

**Comment by huihuifan** [comment]
@alexeib

**Comment by jeremyasapp** [comment]
Would be interested in this too!

**Comment by apeterswu** [comment]
Also interested in the correct setting to reproduce the resutls.

**Comment by DavidHerel** [comment]
This issue is still not resolved. There is no documentation on how to reproduce results on Billion Word benchamark for paper Baevski and Ali, 2018.
