### ISSUE TITLE
Older wikitext pretrained models

### ISSUE THREAD

**Issue by rococode** [pytorch/fairseq#903]
Are there older language models pretrained on WikiText-103 that are no longer available?

I found this link in an old issue:
https://s3.amazonaws.com/fairseq-py/models/wiki103_fconv_lm.tar.bz2

But it appears to be unavailable at that url. From the naming I expect it's different from the current adaptive LM that's linked here: https://github.com/pytorch/fairseq/blob/master/examples/language_model/README.md

I ask because I'm trying to run an old codebase that that needs this pretrained model, but the one currently linked seems to be incompatible. Is there an older version that can still be downloaded? 

(the error I get is very standard for version mismatch, wrong keys and stuff)

**Comment by huihuifan** [comment]
@alexeib
