### ISSUE TITLE
"Help" fairseq now is support transformer_from_pretrained_xlm and I found it is not compatible for pretrained_xlm checkpoint

### ISSUE THREAD

**Issue by PlayDeep** [pytorch/fairseq#907]
is it support to load a pretrained xlm model or Not? or it is means using fairseq pretrain a xlm model and load ?

**Comment by beichao1314** [comment]
I meet the similar problem. And I'm testing the latest code for transformer_from_pretrained_xlm.

**Comment by sdll** [comment]
Any updates on this?

**Comment by lematt1991** [comment]
Yes this is for loading an already trained XLM model.  Please open a new issue following the issue template if you are still having problems.
