### ISSUE TITLE
RoBERTa model

### ISSUE THREAD

**Issue by stefan-it** [pytorch/fairseq#908]
Hi,

thanks for releasing the RoBERTa model :heart: 

I've one question regarding to the output features:

```python
features = roberta.extract_features(tokens)
features.size()
torch.Size([1, 5, 1024])
```

Are these features the output of the last layer (layer nr. 24) of the Transformer model? Is it currently possible to select a specific layer?

Thanks in advance,

Stefan

**Comment by myleott** [comment]
Yes, it’s the last layer before lm_head. I will add an option to expose specific layers, but for now you can copy this: https://github.com/pytorch/fairseq/blob/master/fairseq/models/roberta.py#L106

If you remove features_only=True, then the second element of the returned tuple will contain all of the inner states.

**Comment by myleott** [comment]
Exposed new functionality in https://github.com/pytorch/fairseq/pull/909:

```
>>> roberta.eval()

>>> tokens = roberta.encode('Hello world.')

>>> last_layer_features = roberta.extract_features(tokens)
>>> last_layer_features.size()
torch.Size([1, 6, 1024])

>>> all_layers = roberta.extract_features(tokens, return_all_hiddens=True)
>>> len(all_layers)
25
>>> all_layers[-1].size()
torch.Size([1, 6, 1024])

>>> torch.all(all_layers[-1] == last_layer_features)
tensor(1, dtype=torch.uint8)
```

**Comment by stefan-it** [comment]
Hi @myleott thanks for your kind help and extending in the interface :heart: I could now integrate the *RoBERTa* into an upcoming version of Flair 🤗
