### ISSUE TITLE
Facing RuntimeError while loading roBERTa with torch hub

### ISSUE THREAD

**Issue by Arjunsankarlal** [pytorch/fairseq#918]
I am trying to load roBERTa large mnli model and while doing it, I am facing this issue.

Code I tried, 

> import torch
> 
> roberta = torch.hub.load('pytorch/fairseq', 'roberta.large', force_reload=True)
> roberta.eval()  # disable dropout (or leave in train mode to finetune)

Log,

```
Downloading: "https://github.com/pytorch/fairseq/archive/master.zip" to /Users/arjun-zt235/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "/Users/pytorch-transformers/examples/roBERTa.py", line 22, in <module>
    roberta = torch.hub.load('pytorch/fairseq', 'roberta.large', force_reload=True)
  File "/Users/pytorch-transformers/torchtransformersenv/lib/python3.6/site-packages/torch/hub.py", line 338, in load
    entry = _load_entry_from_hubconf(hub_module, model)
  File "/Users/pytorch-transformers/torchtransformersenv/lib/python3.6/site-packages/torch/hub.py", line 216, in _load_entry_from_hubconf
    raise RuntimeError('Cannot find callable {} in hubconf'.format(model))
RuntimeError: Cannot find callable roberta.large in hubconf
```

I'm I missing anything here? Should I be configuring or creating any hubconfig files? Any lead would be appreciated! Also thanks for roBERTa❤️

**Comment by myleott** [comment]
Sorry about that, fix is here: https://github.com/pytorch/fairseq/pull/920

**Comment by Arjunsankarlal** [comment]
Thanks for the quick response @myleott :)

**Comment by myleott** [comment]
This should be fixed now.
