### ISSUE TITLE
Restart training from last saved checkpoint

### ISSUE THREAD

**Issue by amrit-bhaskar** [pytorch/fairseq#919]
I am working on Multilingual translation. How to restart the training from the last saved checkpoint.

**Comment by huihuifan** [comment]
It should automatically do this if you point the --save-dir where the last saved checkpoint is. Do you have an error message you are getting?

**Comment by huihuifan** [comment]
I'm closing this, please re-open if you are still having problems. Note the code automatically looks for checkpoint_last.pt in the --save-dir directory
