### ISSUE TITLE
tokens bug of RoBERTa

### ISSUE THREAD

**Issue by orchardchang** [pytorch/fairseq#926]
My pytroch version is 1.1.0, using following code:
```
import torch  
roberta = torch.hub.load('pytorch/fairseq', 'roberta.large')  
roberta.eval() 

tokens = roberta.encode('Hello world!')
tokens
```
I expect to get tokens:
`tensor([    0, 31414,   232,   328,     2])`

however I got the tokens:
`tensor([    0, 31414,   232,   328,     2,     2])`

There is one more token `2` in the end.  Also I have tried other sentences, and the second token `2`still exists. 
Is it a bug?

**Comment by luv4me** [comment]
I get the same tensor as you

**Comment by myleott** [comment]
Good catch, that was a bug introduced when trying to support multiple sequences. Fix is attached
