### ISSUE TITLE
pip install fairseq does not gets the latest changes

### ISSUE THREAD

**Issue by Arjunsankarlal** [pytorch/fairseq#934]
The changes regarding roBERTa is not reflected while installing using pip. (pip install fairseq).

Also after installing with git clone and installing with pip install --editable . it is not reflected in site packages.

Any help would be appreciated!

**Comment by myleott** [comment]
Ah we didn't do a new release on pypi. I'll do one today.

**Comment by Arjunsankarlal** [comment]
Okay @myleott. Also installing from source caused the same problem.

**Comment by myleott** [comment]
With `pip install --editable .` it will be added to easy-install.pth.

If you run `pip install --editable .` are you later able to `import fairseq`?

**Comment by Arjunsankarlal** [comment]
Actually after doing this step, it was not available in site packages, and while trying to import it in Pycharm, it pointed to the the repo which was cloned, rather than the site packages location (however it wasn't there)

**Comment by myleott** [comment]
To do a full install just remove `--editable`. But that will copy the package into site-packages and it will not reflect realtime changes to the original cloned source files.

**Comment by Arjunsankarlal** [comment]
I am able to infer the results now. Thanks for the quick responses @myleott.
