### ISSUE TITLE
Small errors in preprocessing script for GLUE data

### ISSUE THREAD

**Issue by villmow** [pytorch/fairseq#936]
Hi,

I try to fine-tune the roberta model on the GLUE data as explained in the example directory. While preprocessing the data with the [preprocess_GLUE_tasks.sh](https://github.com/pytorch/fairseq/blob/master/examples/roberta/preprocess_GLUE_tasks.sh) script I stumbled upon some small bugs:
 1. gpt2_bpe_utils.py uses the package `regex`, which is not mentioned anywere. It needs to be installed with `pip install regex` as the ImportError prints. You could mention that in the tutorial.
 2. The script calls the fairseq [preprocess.py](https://github.com/pytorch/fairseq/blob/master/preprocess.py) script directly. As the [preprocess_GLUE_tasks.sh](https://github.com/pytorch/fairseq/blob/master/examples/roberta/preprocess_GLUE_tasks.sh) is located in the example directory this fails. Easy fix is using the command-line interface: `fairseq-preprocess` at this line: https://github.com/pytorch/fairseq/blob/d82517e9553ab690b8a264f7ca5be46a41eee700/examples/roberta/preprocess_GLUE_tasks.sh#L162

**Comment by myleott** [comment]
Thanks!
