### ISSUE TITLE
How to finetune RoBERTa?

### ISSUE THREAD

**Issue by chengfx** [pytorch/fairseq#938]
Thanks for the RoBERTa.
I want to finetune RoBERTa in custom dataset for different task such as MRC, Classification, Generation and so. Could you share some details about how to finetune RoBERTa. I can not find it in Readme.

**Comment by ngoyal2707** [comment]
We have added tutorial for simple binary classification [here](https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.finetune_custom_classification.md) with taking `IMDB` classification as example. 
For MRC, we will add our code for fine-tuning on SQuAD which is being tracked here (https://github.com/pytorch/fairseq/issues/933).

Text generation from `masked_lm` is somewhat difficult problem and we haven't yet explored that in our work on RoBERTa. One possible way of generating could be as mentioned in [this paper](https://arxiv.org/pdf/1902.04094.pdf) . You are definitely welcome to try that with the provided model.
