### ISSUE TITLE
Can we train roBERTa offline

### ISSUE THREAD

**Issue by SchenbergZY** [pytorch/fairseq#943]
Hi based on my poor Internet connection I need to train the model offline... 
Is there any documentation or any instruction for offline operations?

**Comment by myleott** [comment]
I’m not sure what you mean by offline. Are you trying to finetune or pretrain a new model? Do you have access to a GPU?

**Comment by SchenbergZY** [comment]
Thank you for quick response.
Well the exact question is: how I can build a model by calling ```RobertaModel.build_model()``` without any additional downloading? Then I can load dictionary.txt and call ```model.load_state_dict(torch.load(model.pt))``` locally.

**Comment by myleott** [comment]
That's not really supported. When you load a model you have to specify a bunch of configuration, e.g., the number of layers, embedding size, dictionary size, maximum sequence length, etc.

You can follow the instructions here: https://github.com/pytorch/fairseq/tree/master/examples/roberta#load-roberta-for-pytorch-10.

If you use `roberta.base` the download is only 221MB.

**Comment by thangld201** [comment]
Hi @myleott, I find that the code to load RoBERTa models in https://github.com/pytorch/fairseq/tree/master/examples/roberta#load-roberta-for-pytorch-10 fails if one does not have internet access, even if the model files and bpes are already cached. Do you have a solution ?
