### ISSUE TITLE
Encoding Multiple Sentences for Roberta?

### ISSUE THREAD

**Issue by amitness** [pytorch/fairseq#946]
The .encode method converts all the 3 sentences to a 1-D array with placeholders('\<s\>') to signify separators. How do I use this as an input to a classification task for 3 sentences?

![image](https://user-images.githubusercontent.com/8587189/62268776-ac24ff80-b450-11e9-9815-85ef384fd8c3.png)

Since output size is flattened [18], the model with a classification head of 2 classes, is just returning a single prediction instead of 3 predictions. Is there a way to encode multiple sentences in bulk as separate tokens?

**Comment by myleott** [comment]
Ah, for three separate examples you should call encode three times. You can then use fairseq.data.data_utils.collate_tokens to merge them into a batch. The predict function will operate fine on the batch of inputs and return a 3x2 output.

**Comment by amitness** [comment]
Thank you for clarifying. Won't it be a performance bottleneck to make repeated calls to encode for large number of responses? How was this handled during your experiments?

**Comment by myleott** [comment]
Ah, if you want to BPE-encode a large volume of text then you should use the multiprocessing_bpe_encoder: https://github.com/pytorch/fairseq/blob/master/examples/roberta/multiprocessing_bpe_encoder.py

Then you can pass through the standard fairseq-preprocess script using the dict.txt from the RoBERTa archive.

**Comment by myleott** [comment]
We wrote a more detailed writeup here: https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.finetune_custom_classification.md

**Comment by justachetan** [comment]
Hey! I was wondering how would the `predict` function for `mnli.large` model work in case the input is provided in batches. As in, what would the scores indicate?

I have also opened a separate issue about this here: https://github.com/pytorch/fairseq/issues/1167

Would be grateful for some help.
