### ISSUE TITLE
Masked Token Prediction?

### ISSUE THREAD

**Issue by tseretelitornike** [pytorch/fairseq#947]
Hi, great work on the tool! 

I'm interested in predicting a masked token in a sequence. Is the MaskedLMModel possible to be set up in a comparable setting to that of BERT as described in the pytorch-transformers implementation?

https://github.com/huggingface/pytorch-transformers/blob/master/docs/source/quickstart.md

Thanks!

**Comment by lematt1991** [comment]
I believe `--arch bert_base` or `--arch bert_large` should give you what you want.  See more details [here](https://github.com/pytorch/fairseq/blob/master/fairseq/models/masked_lm.py#L297-L331)
