### ISSUE TITLE
vocab_size for roberta?

### ISSUE THREAD

**Issue by rush86999** [pytorch/fairseq#949]
I m trying to train a transformer model attention only but I don't see the vocab size. is it the same size as bert? You are using bpe so I am assuming it is different. Is the value dynamic? On the topic, will there be a tutorial on using a custom dataset coming soon?

**Comment by lematt1991** [comment]
The easiest way to get the vocab size is probably to download whichever pretrained model you are interested in and inspect the state_dict.  The following

```Python
import torch
roberta = torch.hub.load('pytorch/fairseq', 'roberta.large')
print(roberta.model.decoder.sentence_encoder.embed_tokens.weight.shape)
```

yields

`torch.Size([50265, 1024])`

Please let me know if you have further questions.  Thanks!
