### ISSUE TITLE
Where is fairseq-preprocess

### ISSUE THREAD

**Issue by chengfx** [pytorch/fairseq#955]
When I run following command in the shell script

```bash
for input_index in $(seq 1 2); do
  fairseq-preprocess \
      --only-source \
      --trainpref $processed_data_dir/train.${input_index}.bpe \
      --validpref $processed_data_dir/dev.${input_index}.bpe \
      --testpref $processed_data_dir/test.${input_index}.bpe \
      --destdir $processed_data_dir/Input.${input_index} \
      --workers 4 \
      --srcdict ${roberta_vocab_dir}/dict.txt
done
```
There is an issue that command not found
```bash
fairseq-preprocess: command not found
```

**Comment by myleott** [comment]
You need to run “pip install --editable .” to install the fairseq-preprocess executable.

**Comment by nonononanana** [comment]
sorry, from which directory shall I run “pip install --editable .” ?

**Comment by Skylixia** [comment]
> You need to run “pip install --editable .” to install the fairseq-preprocess executable.

@myleott 
Even after running this and having fairseq successfully installed the fairseq-preprocess is not found

**Comment by yarakhater** [comment]
@Skylixia Were you able to fix this?
