### ISSUE TITLE
RuntimeError: Schema not found for node. File a bug report.

### ISSUE THREAD

**Issue by Dod-o** [pytorch/fairseq#957]
hi,

I use the LSTM code from [https://fairseq.readthedocs.io/en/latest/tutorial_simple_lstm.html](url), and every thing is ok. Now I want to convert the model to onnx.

I add the forward function in SimpleLSTMModel, I think I can control the flow of data in this way.
```
def forward(self, src_tokens, src_lengths, prev_output_tokens):
    encoder_out = self.encoder(src_tokens, src_lengths)
    decoder_out = self.decoder(prev_output_tokens, encoder_out)
    return decoder_out
```

Then, I use generate.py and add the following code after it loads the model, hoping to convert the loaded model into onnx.

```
    # Load ensemble
    print('| loading model(s) from {}'.format(args.path))
    models, _model_args = checkpoint_utils.load_model_ensemble(
        args.path.split(':'),
        arg_overrides=eval(args.model_overrides),
        task=task,
    )

    #-----------my code-------------
    batch_size = 32
    seq_len = 64
    src_tokens = torch.ones(size=(batch_size, seq_len), dtype=torch.int64)
    src_lengths = torch.ones(size=(batch_size,), dtype=torch.int64)
    prev_output_tokens = torch.ones(size=(batch_size, 1), dtype=torch.int64)

    torch.onnx.export(models[0], (src_tokens, src_lengths, prev_output_tokens), 'output/simple_lstm.onnx')
```

But there was an error
 "**RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got NoneType**"

I found that the reason is one of the return values of decoder is None which is used for mask. And then I constructed the mask manually so that the return is not None, but there was another error.

```
RuntimeError: 
Schema not found for node. File a bug report.
Node: %55 : Long(64) = aten::arange(%54), scope: SimpleLSTMModel/SimpleLSTMEncoder[encoder]
```

So if I want to output the LSTM structure in the tutorial as onnx, what should I do?

Thanks

**Comment by myleott** [comment]
Sorry, I don't have much context on ONNX. Please refile this bug report with the ONNX or PyTorch teams. Alternatively you can try using pytorch/translate: https://github.com/pytorch/translate. That library inherits from fairseq and is more production-focused. There are various LSTM implementations there that should be compatible with ONNX.

**Comment by YoonaX** [comment]
请问你解决了这个问题吗？我也遇到了和你一样的问题
