### ISSUE TITLE
Where can I find example of QQP uses and finetuned data? 

### ISSUE THREAD

**Issue by fourcolorstech** [pytorch/fairseq#966]
I am trying sentence comparison task. Is finetuned RoBERTa with QQP available? Also, where can I find example of QQP task use?

**Comment by ngoyal2707** [comment]
We are not planning to release model finetuned for each of the GLUE task.

However you can follow the instructions [here](https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.finetune_glue.md) to finetune the released RoBERTa model on QQP.
Let me know if you have any more questions about that.
