### ISSUE TITLE
will you release the how to train BERT or RoBERTa from scratch code?

### ISSUE THREAD

**Issue by gaopengcuhk** [pytorch/fairseq#967]
If there is plan, can you tell me how long I need to wait?

**Comment by stefan-it** [comment]
Would be awesome! I really want to try training a RoBERTa model from scratch for low-resource languages in order to compare the performance against e.g. ELMo on downstream tasks :)

**Comment by myleott** [comment]
Instructions are here: https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md

**Comment by crowegian** [comment]
Is there source code available for fairseq-train. I want to look at how pre-training is done.

**Comment by crowegian** [comment]
I am ashamed of my own incompetence. 

Thanks!
