### ISSUE TITLE
tokenization and subword

### ISSUE THREAD

**Issue by hoangcuong2011** [pytorch/fairseq#977]
Hi there,

I am looking at your (great) wmt 2019 pretrained models, which are the best participant for WMT 2019 shared tasks. Congratulations for a great superhuman translation performance. So good!
 
One point not so clear to me is how do you use both tokenization and subword in your models.

I a, a bit confused because I think when we use subword, we don't need to do tokenization. In other words, we learn subword directly from raw text.

But here you used both. Does it mean that you tokenize the text first (e.g. Thanks! This is great! -> Thanks ! This is great !), and then you do subword on the tokenized text?

If so, how do you do detokenize back the translated text when you do translate (e.g. given a translation output: Thanks ! This is great !, how could you convert back to Thanks! This is great!. Which processing tool you used for this?

Thanks!

Best,

**Comment by myleott** [comment]
Yes, your understanding is correct. We apply BPE over the tokenized input.

Re: tokenization, we use sacremoses, which is a Python port of the Moses tokenizer. It contains a rule-based detokenizer, which is not perfect, but is usually able to reverse the tokenization.

**Comment by arendu** [comment]
A quick follow up, are you using the `--no-escape` flag during tokenization? (assuming that you are using moses tokenization).
