### ISSUE TITLE
Why is bias default to be off for attentive LSTM?

### ISSUE THREAD

**Issue by Zhaofeng-Wu** [pytorch/fairseq#983]
https://github.com/pytorch/fairseq/blob/e75cff5f2c1d62f12dc911e0bf420025eb1a4e33/fairseq/models/lstm.py#L346

**Comment by myleott** [comment]
Similar to #983, this is meant to match the original Luong et al. code. Happy to take a PR that makes this configurable :)

**Comment by Zhaofeng-Wu** [comment]
I think you meant to say #985. Thanks :)
