### ISSUE TITLE
Ensembling with RoBERTa?

### ISSUE THREAD

**Issue by sleepinyourhat** [pytorch/fairseq#984]
Could you share instructions to (roughly) reproduce the ensembled pretraining runs on GLUE?

[Mainly for Yinhan Liu, @myleott et al.]

**Comment by ngoyal2707** [comment]
Sure, so for the all the GLUE tasks, we ran `15` different seeds for the selected hyperparam, and ensemble top `7` model based on dev set metrics.  For `WNLI` we ensembled `5` models.
 
For all the classification tasks, ensemble was based on average of probabilities. For `STS-B` it was average of scores.

Let me know if you are looking for any more specific things?

**Comment by ngoyal2707** [comment]
The ensembling code is pretty intertwined with our scheduling system and we don't have plans to release them. But we are definitely happy to help debug any issues.

**Comment by ngoyal2707** [comment]
I will close this issue. Feel free to reopen if you have more questions
