### ISSUE TITLE
Why are module weights for LSTM re-initialized uniformly?

### ISSUE THREAD

**Issue by Zhaofeng-Wu** [pytorch/fairseq#985]
E.g. https://github.com/pytorch/fairseq/blob/e75cff5f2c1d62f12dc911e0bf420025eb1a4e33/fairseq/models/lstm.py#L497

Are there studies that show this helps achieve better performance?

**Comment by myleott** [comment]
This was to match the original Luong et al. code, and I expect that other initializations might perform better. In general, the LSTM implementation in fairseq is meant to demonstrate how to implement LSTMs in fairseq, but is probably far from optimal. Happy to take a PR that makes this configurable :)
