### ISSUE TITLE
mkdir -p for ./examples/roberta/preprocess_GLUE_tasks.sh

### ISSUE THREAD

**Issue by gmhafiz** [pytorch/fairseq#987]
The shell script is missing -p parameter for creating subdirectories on line 87 and 181.

**Comment by myleott** [comment]
Good call, can you submit a PR to fix?

**Comment by gmhafiz** [comment]
Done: https://github.com/pytorch/fairseq/pull/997
Although https://code.facebook.com/cla is giving me an error saying:
 "Sorry, something went wrong. We're working on getting this fixed as soon as we can."

**Comment by myleott** [comment]
The CLA part seems to be working now, I'll merge the PR, thanks!
