### ISSUE TITLE
No such file or directory: 'data-bin/iwslt14.tokenized.de-en/dict.de.txt'

### ISSUE THREAD

**Issue by Trinkle23897** [pytorch/fairseq#998]
Hi! I want to run the code in https://fairseq.readthedocs.io/en/latest/tutorial_simple_lstm.html, and in step 3 it needs iwslt14 dataset. 

I use the script in https://github.com/pytorch/fairseq/blob/master/examples/translation/prepare-iwslt14.sh to download the dataset, and run the following command:

```bash
fairseq-train data-bin/iwslt14.tokenized.de-en \
  --arch tutorial_simple_lstm \
  --encoder-dropout 0.2 --decoder-dropout 0.2 \
  --optimizer adam --lr 0.005 --lr-shrink 0.5 \
  --max-tokens 12000
```

it turns out `Exception: Could not infer language pair, please provide it explicitly`. I look at previous issue and add `--source-lang de --target-lang en` arguments, then turns out the following:

`FileNotFoundError: [Errno 2] No such file or directory: 'data-bin/iwslt14.tokenized.de-en/dict.de.txt'`

However, there is no such file which will be generated from this script. Where should I find this dict.de.txt?

**Comment by NikhilPr95** [comment]
What was the solution to this issue? I am facing the same right now

**Comment by zbchern** [comment]
> What was the solution to this issue? I am facing the same right now

prepare-iwslt14.sh only download the dataset, you need to pre-process and binarize it. Please refer to https://fairseq.readthedocs.io/en/latest/getting_started.html#data-pre-processing
